[레벨 2 글쓰기 미션] 케빈(박진홍) 미션 제출합니다.
woowacourse/woowa-writing-3 pull request #101
Opened 2021-05-28 10:52 UTC by xlffm3

잘 부탁드립니다~

2021-05-28 23:11 UTC, sihyung92 commented
케빈 하위~~ 지나가던 웨지예염 ㅎ_ㅎ
글 잘 봤습니다!! what, why, how 학습법 멋집니다 👏
케고수 블로그 보면서 상세한 정리와 깊이에 감탄하곤 합니다
앞으로도 멋진 글들 기대할게용 ㅎ_ㅎ

2021-05-29 06:04 UTC, Be-poz approved these changes
저 또한 레벨 2에 들어 학습 테스트를 작성하며 학습 내용을 확인해보는 습관을 가지게 되었습니다. 좋은 것 같아요!! 현재 내가 사용하려는 메서드 외에도 다른 메서드들 과의 차이점이 무엇인지 파악하는 과정을 가지고나면 확실히 그 키워드에 대한 자신감도 생기고 기억에 잘 남더라구요! 백엔드 강의실을 지나가면서 항상 앉아서 열심히 몰두하고 있는 모습을 종종 보게되는데 그 때마다 멋있다는 생각을 합니다! 케빈이 되고 싶어하는 기본에 충실한 개발자가 정말 되실 것 같습니다! 레벨 3도 화이팅입니다!!! 글에 대한 수정 피드백은 제 개인적인 의견이니깐 꼭 반영하실 필요는 없습니다~~

2021-05-29 06:04 UTC, Be-poz commented on level2/README.md
> +Spring Core 레퍼런스 학습 초기에는 의욕이 앞서 모든 내용을 학습하려고 시도했습니다. 그 결과, 보기 좋게 학습에 흥미를 잃었습니다. 사실 레퍼런스 내용 전체를 빠짐없이 학습한다는 것 자체가 허무맹랑한 목표였습니다. 레퍼런스는 말 그대로 참고 자료일 뿐이기 때문에, 다음과 같은 정보들까지 가감 없이 집대성되어 있습니다.
오우.. 래퍼런스 전체내용 정독이라니  ... 마음먹으신 것도 대단하네요

2021-05-29 06:04 UTC, Be-poz commented on level2/README.md
> +그러나 점차 새로운 기능을 더욱 확실하고 즐겁게 익힐 수 있었습니다. 해당 기능이 왜 필요하며, 다양한 조건에서 어떻게 동작하는지 등을 직접 확인했습니다. 또한 이렇게 작성해둔 샘플 코드를 실제 개발 중에 요긴하게 참조할 수 있다는 부수적인 장점이 존재했습니다.
작성해둔 샘플 코드들 다 보고 싶네요...

2021-05-29 06:04 UTC, Be-poz commented on level2/README.md
> +기술의 배경지식을 상세하게 정리하면서 학습하다 보니 시간이 많이 투입되곤 했습니다. 당장 신속한 기능 구현에 착수하지 못하더라도, 학습한 내용이 효과적으로 기억에 각인되는 등 상기한 단점의 비용을 상쇄한다고 느꼈습니다.
개인적으로 ``투입`` 보다는 ``소요``가 더 자연스러운 것 같아요!

2021-05-29 06:04 UTC, Be-poz commented on level2/README.md
> +3. 현재 내 수준에 비해 너무 심화한 내용.
``심화된``이 덜 어색한 것 같아요~!

2021-05-29 16:13 UTC, TaewanKimmmm requested changes
안녕하세요, 케Bean!

좋은 글 잘 봤습니다. 몇 가지 의견 제시해 봤어요!

학습한 내용이 휘발되지 않도록 하는 방법을 습득하신 것 같군요..

What Why How 아주 좋은 키워드 같아요 저도 차용할게요 👍

2021-05-29 16:13 UTC, TaewanKimmmm commented on level2/README.md
> +
명심하겠습니다..케Bean..

2021-05-29 16:13 UTC, TaewanKimmmm commented on level2/README.md
> +처음 보는 기능을 눈으로만 보고 정리하다 보니 학습 내용이 쉽게 휘발되는 단점이 존재했습니다. 이를 개선하고자, 브라운 코치 및 토비의 스프링 저자 토비가 권장하는 **학습 테스트 작성** 방법을 시도했습니다. 처음에는 테스트 작성으로 인해 시간이 오래 소요되고는 했습니다.
`처음 접하는 기능을`로 표현하는 것은 어떨까요? 뒤에 `눈으로만 보고`라는 표현과 약간 겹치는 느낌이라서요!

2021-05-29 16:13 UTC, TaewanKimmmm commented on level2/README.md
> +처음 보는 기능을 눈으로만 보고 정리하다 보니 학습 내용이 쉽게 휘발되는 단점이 존재했습니다. 이를 개선하고자, 브라운 코치 및 토비의 스프링 저자 토비가 권장하는 **학습 테스트 작성** 방법을 시도했습니다. 처음에는 테스트 작성으로 인해 시간이 오래 소요되고는 했습니다.
`오랜 시간이 소요되고는 했습니다.` 도 좋을 것 같아요!

2021-05-29 16:13 UTC, TaewanKimmmm commented on level2/README.md
> +
매우 공감되네요

2021-05-30 04:09 UTC, 2SOOY reviewed
안녕하세요! 케빈 :)
정말 오랜만이네요 ㅎㅎ

우테코 생활을 하면서 체득한 케빈의 학습법에 대해 이야기 해주셔서 감사합니다
글 전반적으로 소제목도 적절하게 잘 지으신 것 같아요 👍 
`What, Why, How`의 학습 사이클이 인상깊네요 :) 저도 다음 학습에 당장 적용해봐야겠네요 !

2021-05-30 04:09 UTC, 2SOOY commented on level2/README.md
> +처음 보는 기능을 눈으로만 보고 정리하다 보니 학습 내용이 쉽게 휘발되는 단점이 존재했습니다. 이를 개선하고자, 브라운 코치 및 토비의 스프링 저자 토비가 권장하는 **학습 테스트 작성** 방법을 시도했습니다. 처음에는 테스트 작성으로 인해 시간이 오래 소요되고는 했습니다.
첵 제목은 `《토비의 스프링》` 또는 `『토비의 스프링』` 형태로 작성해 주시면 좋을 것 같아요 :)

2021-05-30 04:09 UTC, 2SOOY commented on level2/README.md
> +처음 보는 기능을 눈으로만 보고 정리하다 보니 학습 내용이 쉽게 휘발되는 단점이 존재했습니다. 이를 개선하고자, 브라운 코치 및 토비의 스프링 저자 토비가 권장하는 **학습 테스트 작성** 방법을 시도했습니다. 처음에는 테스트 작성으로 인해 시간이 오래 소요되고는 했습니다.
`학습 테스트 작성` 어떤 방법인지 궁금하네요! 🤔

2021-05-30 04:09 UTC, 2SOOY commented on level2/README.md
> +
명심하겠습니다..

2021-05-30 04:09 UTC, 2SOOY commented on level2/README.md
> +* 해당 기술의 사용법이 무엇인지?
오 저도 다음 학습에 적용해봐야겠군요 👍👍👍

2021-05-30 04:09 UTC, 2SOOY commented on level2/README.md
> +레벨 2 과정은 많은 시행착오로 인해 고난의 연속이었습니다. 하지만 다양한 시도를 통해 새로운 기술을 학습하는 방법에 대한 인사이트를 얻을 수 있는 좋은 기회였습니다. 앞으로도 새로운 기술을 접할 기회가 많을 것입니다. 그 방대한 학습 분량을 두려워 하지 않고, 천천히 기본에 충실한 방식으로 정복하는 개발자가 되고 싶습니다. 😇
파이팅 ✊✊✊

2021-05-30 05:03 UTC, thisisyoungbin reviewed
케빈 안녕하세요!
몇 가지 코멘트 남겼는데 개인적인 의견이니 참고해주세요 :)

공식문서 완독... 전 엄두도 못냈던 부분인데 시도한 자체가 대단하네요.
어쩐지 모던자바 스터디 때 고수의 향기가 나던데..
완독 시도에 실패했더라도, 덕분에 우선순위를 두고 공부하는 방식을 효율적으로 택하게 되어 오히려 좋은 거 같네요ㅎ

what, why, how 학습법도 인상적이었습니다! 전 아직 how에만 집중하고 있는 것 같은데.. 많이 반성했네요.
글 잘 읽었습니다! 어느덧 레벨2도 끝나가는데 남은 기간까지 같이 화이팅해요~~

2021-05-30 05:03 UTC, thisisyoungbin commented on level2/README.md
> +과정 중반부터는 이러한 방식을 가급적 지양하고, 공식 레퍼런스를 기반으로 학습하려고 노력했습니다. 타인이 작성한 자료를 참고하는 방식이 나쁜 것만은 아닙니다. 다만 타인이 작성한 접근성 높은 자료에 과하게 의존하면 장기적으로 개발 습관에 악영향을 끼칠 것으로 판단했습니다. 공식 레퍼런스에서 원하는 정보를 신속하게 취사선택하는 것 또한 좋은 개발자의 자세이
공식문서 보는 습관... 저도 요즘들어서 느끼고 있어요. 공감되네요ㅎㅎㅎ

2021-05-30 05:03 UTC, thisisyoungbin commented on level2/README.md
> +공부란 끝이 없으며, 많이 알면 알수록 좋은 것이 사실입니다. 그러나 시간은 한정돼 있습니다. 현재 내 상황에서 무엇이 더 중요한지 우선순위를 두고 필터링하며 레퍼런스를 읽는 것이 중요합니다. 욕심을 버리고 학습하다 보니 지치지 않고 학습을 지속할 수 있었습니다.
`공부란 끝이 없으며, 많이 알수록 좋은 것이 사실입니다.` 로 표현해도 될 거 같은데 케빈 생각은 어떠신가요?

2021-05-30 05:03 UTC, thisisyoungbin commented on level2/README.md
> +처음 보는 기능을 눈으로만 보고 정리하다 보니 학습 내용이 쉽게 휘발되는 단점이 존재했습니다. 이를 개선하고자, 브라운 코치 및 토비의 스프링 저자 토비가 권장하는 **학습 테스트 작성** 방법을 시도했습니다. 처음에는 테스트 작성으로 인해 시간이 오래 소요되고는 했습니다.
저도 콜린 의견처럼 학습 테스트 작성에 대한 간단한 소개 정도의 내용이 들어가도 좋을 거 같아요!

2021-05-30 05:03 UTC, thisisyoungbin commented on level2/README.md
> +기술의 배경지식을 상세하게 정리하면서 학습하다 보니 시간이 많이 투입되곤 했습니다. 당장 신속한 기능 구현에 착수하지 못하더라도, 학습한 내용이 효과적으로 기억에 각인되는 등 상기한 단점의 비용을 상쇄한다고 느꼈습니다.
`당장 신속한 기능 구현에 ...`가 조금 중의적인 표현처럼 읽히는데요. `빠르게 기능 구현에 착수하지 못하더라도`, `신속하게 기능 구현에 착수하지 못하더라도`, `당장 기능 구현에 착수하지 못하더라도` 등이 자연스러워 보여요!

2021-05-30 08:05 UTC, jho2301 reviewed
안녕하세요 케빈

글 잘 읽었어요

기술의 용도와 당위성을 파악하는게 중요하다고 느끼고 있는데

케빈은 어떻게 이것을 학습하는지 볼 수 있어 좋았습니다

2021-05-30 08:05 UTC, jho2301 commented on level2/README.md
> +처음 보는 기능을 눈으로만 보고 정리하다 보니 학습 내용이 쉽게 휘발되는 단점이 존재했습니다. 이를 개선하고자, 브라운 코치 및 토비의 스프링 저자 토비가 권장하는 **학습 테스트 작성** 방법을 시도했습니다. 처음에는 테스트 작성으로 인해 시간이 오래 소요되고는 했습니다.
저도 숟가락 얹어봅니다 ㅎㅎ
여기만 보완하면 완벽해질 것 같아요

2021-05-30 11:11 UTC, pjy1368 approved these changes
안녕하세요 케빈 🎁
우테코 전부터 대단하다고 느꼈는데, 글을 읽어보니 체계적으로 학습하려고 노력하신 점이 엿보이네요. 글 자체는 다른 분들이 많이 피드백해 주셔서 거의 고칠 부분은 없어보여요.
앞으로도 기본에 충실한다면 어떠한 개념도 익히실 수 있을 거에요 👍

2021-05-30 11:11 UTC, pjy1368 commented on level2/README.md
> +3. 현재 내 수준에 비해 너무 심화한 내용.
파즈 의견에 동의합니다.

2021-05-30 11:11 UTC, pjy1368 commented on level2/README.md
> +처음 보는 기능을 눈으로만 보고 정리하다 보니 학습 내용이 쉽게 휘발되는 단점이 존재했습니다. 이를 개선하고자, 브라운 코치 및 토비의 스프링 저자 토비가 권장하는 **학습 테스트 작성** 방법을 시도했습니다. 처음에는 테스트 작성으로 인해 시간이 오래 소요되고는 했습니다.
날먹같지만, 파피와 콜린의 의견 반영하면 좋을 것 같아요.

2021-05-30 11:11 UTC, pjy1368 commented on level2/README.md
> +기술의 배경지식을 상세하게 정리하면서 학습하다 보니 시간이 많이 투입되곤 했습니다. 당장 신속한 기능 구현에 착수하지 못하더라도, 학습한 내용이 효과적으로 기억에 각인되는 등 상기한 단점의 비용을 상쇄한다고 느꼈습니다.
'시간이 많이 걸리곤 했습니다.' 정도로 간결하게 작성하는 것도 좋을 것 같아요.

2021-05-30 11:11 UTC, pjy1368 commented on level2/README.md
> +레벨 2 과정은 많은 시행착오로 인해 고난의 연속이었습니다. 하지만 다양한 시도를 통해 새로운 기술을 학습하는 방법에 대한 인사이트를 얻을 수 있는 좋은 기회였습니다. 앞으로도 새로운 기술을 접할 기회가 많을 것입니다. 그 방대한 학습 분량을 두려워 하지 않고, 천천히 기본에 충실한 방식으로 정복하는 개발자가 되고 싶습니다. 😇
👍👍

2021-05-30 11:41 UTC, qhals321 commented
안녕하세요~ 지나가던 나봄입니다!!!
정말 케빈만의 철학이 보이는 글이라 너무 좋았네요!!
어마어마한 케빈의 프로그래밍 지식이 이런 학습법에서 나왔군요!! 많이 배워갑니다!!!
이미 케빈은 개성이 뚜렷한 개발자가 된 것 같아 부럽네요!!
남은 기간도 파이팅하세요!! 아자아자!!

2021-05-30 13:24 UTC, xlffm3 commented on level2/README.md
> +기술의 배경지식을 상세하게 정리하면서 학습하다 보니 시간이 많이 투입되곤 했습니다. 당장 신속한 기능 구현에 착수하지 못하더라도, 학습한 내용이 효과적으로 기억에 각인되는 등 상기한 단점의 비용을 상쇄한다고 느꼈습니다.
넵 반영했습니다 :)

2021-05-30 13:25 UTC, xlffm3 commented on level2/README.md
> +3. 현재 내 수준에 비해 너무 심화한 내용.
반영했습니다!

2021-05-30 13:25 UTC, xlffm3 commented on level2/README.md
> +처음 보는 기능을 눈으로만 보고 정리하다 보니 학습 내용이 쉽게 휘발되는 단점이 존재했습니다. 이를 개선하고자, 브라운 코치 및 토비의 스프링 저자 토비가 권장하는 **학습 테스트 작성** 방법을 시도했습니다. 처음에는 테스트 작성으로 인해 시간이 오래 소요되고는 했습니다.
반영했습니다!

2021-05-30 13:26 UTC, xlffm3 commented on level2/README.md
> +처음 보는 기능을 눈으로만 보고 정리하다 보니 학습 내용이 쉽게 휘발되는 단점이 존재했습니다. 이를 개선하고자, 브라운 코치 및 토비의 스프링 저자 토비가 권장하는 **학습 테스트 작성** 방법을 시도했습니다. 처음에는 테스트 작성으로 인해 시간이 오래 소요되고는 했습니다.
반영했습니다. 큰 차이는 없네요 ㅋㅋ

2021-05-30 13:26 UTC, xlffm3 commented on level2/README.md
> +처음 보는 기능을 눈으로만 보고 정리하다 보니 학습 내용이 쉽게 휘발되는 단점이 존재했습니다. 이를 개선하고자, 브라운 코치 및 토비의 스프링 저자 토비가 권장하는 **학습 테스트 작성** 방법을 시도했습니다. 처음에는 테스트 작성으로 인해 시간이 오래 소요되고는 했습니다.
꼼꼼한 지적 감사합니다! ㅎㅎ 해당 부분도 반영했습니다.

2021-05-30 13:27 UTC, xlffm3 commented on level2/README.md
> +공부란 끝이 없으며, 많이 알면 알수록 좋은 것이 사실입니다. 그러나 시간은 한정돼 있습니다. 현재 내 상황에서 무엇이 더 중요한지 우선순위를 두고 필터링하며 레퍼런스를 읽는 것이 중요합니다. 욕심을 버리고 학습하다 보니 지치지 않고 학습을 지속할 수 있었습니다.
ㅎㅎ 비교급 표현을 너무 강조했었나봅니다. 알면 알수록이 너무 장황한것같아 욘 의견 반영했어요 :)

2021-05-30 13:28 UTC, xlffm3 commented on level2/README.md
> +처음 보는 기능을 눈으로만 보고 정리하다 보니 학습 내용이 쉽게 휘발되는 단점이 존재했습니다. 이를 개선하고자, 브라운 코치 및 토비의 스프링 저자 토비가 권장하는 **학습 테스트 작성** 방법을 시도했습니다. 처음에는 테스트 작성으로 인해 시간이 오래 소요되고는 했습니다.
넵 해당부분 함께 반영했습니다. :)

2021-05-30 13:29 UTC, xlffm3 commented on level2/README.md
> +기술의 배경지식을 상세하게 정리하면서 학습하다 보니 시간이 많이 투입되곤 했습니다. 당장 신속한 기능 구현에 착수하지 못하더라도, 학습한 내용이 효과적으로 기억에 각인되는 등 상기한 단점의 비용을 상쇄한다고 느꼈습니다.
너무 많은 부사때문에 다소 중의적으로 들렸나보군요! ``신속하게 기능 구현에 착수하지 못하더라도``로 반영했습니다!

2021-05-30 13:29 UTC, xlffm3 commented on level2/README.md
> +처음 보는 기능을 눈으로만 보고 정리하다 보니 학습 내용이 쉽게 휘발되는 단점이 존재했습니다. 이를 개선하고자, 브라운 코치 및 토비의 스프링 저자 토비가 권장하는 **학습 테스트 작성** 방법을 시도했습니다. 처음에는 테스트 작성으로 인해 시간이 오래 소요되고는 했습니다.
넵 알겠습니다~ :)

2021-05-30 14:52 UTC, thisisyoungbin approved these changes
케빈! 코멘트 반영된 부분 확인했습니다~
감사해요! 바로 어프루브 할게요~~~!!!!

2021-05-30 18:50 UTC, 2SOOY approved these changes
케빈 글 작성하시느라 고생 많으셨습니다 !
남은 레벨2 기간 잘 마무리 하시길 바랍니당 😄

2021-05-31 06:41 UTC, jho2301 approved these changes
아 어프루브인데 안올렸네요! 어프루브로 올려용

2021-05-31 11:45 UTC, TaewanKimmmm commented on level2/README.md
> +처음 보는 기능을 눈으로만 보고 정리하다 보니 학습 내용이 쉽게 휘발되는 단점이 존재했습니다. 이를 개선하고자, 브라운 코치 및 토비의 스프링 저자 토비가 권장하는 **학습 테스트 작성** 방법을 시도했습니다. 처음에는 테스트 작성으로 인해 시간이 오래 소요되고는 했습니다.
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2021-05-31 11:46 UTC, TaewanKimmmm approved these changes
고생하셨습니다~ 케빈 화이팅!

2021-06-01 08:24 UTC, pobiconan approved these changes
맞아요. 우테코는 친절하게 하나씩 api 사용법을 가르치지 않아요. 
그보다는 물 속에 풍덩 던져놓고 그 속에서 살아남을 방법을 찾으라고 압박하는 방식이죠.
이제는 물 밖으로 나올만하면 다시 한번 밀어 넣고의 반복이네요.
우테코가 이런 방식으로 진행하는 이유는 가능한 현장과 비슷한 환경을 경험하도록 하기 위함입니다.
케빈이 글에서 적었듯이 우선순위를 매기고, 효과적인 학습 방법을 익히고, What, Why, How에 대해 궁금증을 가지도록 하기 위함입니다. 
레벨2의 경험이 케빈이 좋은 개발자로 성장하는데 밑거름이 되기를 바래요 💯

2021-06-01 08:24 UTC, merged