[레벨 2 글쓰기 미션] 파즈(강승윤) 미션 제출합니다.
woowacourse/woowa-writing-3 pull request #102
Opened 2021-05-28 14:45 UTC by Be-poz

욘, 콜린, 제이온, 케빈, 파피, 파노  안녕하세요 리뷰 부탁드리겠습니다~!  

[요기서](https://github.com/Be-poz/woowa-writing-3/tree/bepoz_level2/level2) 보시면 되겠습니다~!

2021-05-28 23:16 UTC, sihyung92 commented
파즈 하위~~ 
자기만의 방법을 찾아가고 있군여 ㅎ_ㅎ
항상 꾸준히 열심히 하는 파즈 
보고있으면 마음에 안정감을 주는 든든한 서타일이랄까
사람 됨됨이는 나이순이 아니라는 걸 알게 해주는 친구입니당
앞으로도 재밌게 화이팅~~ 지칠거 같으면 서로 돕기~~

2021-05-29 08:23 UTC, xlffm3 requested changes
안녕하세요 파즈~
글 잘 읽었어요
저도 레벨 2때 학습한 방식을 돌이켜보니 Top-Down을 사용하고 있었네요.
파즈 말처럼 공부를 하면 할수록 파편화된 지식들이 모여 하나의 큰 퍼즐을 완성하는 느낌을 많이 받았어요.
레벨 3때도 큰 그림을 볼 수 있는 지속적인 학습 함께 해나가요!

2021-05-29 08:23 UTC, xlffm3 commented on level2/README.md
> + 나는 하루를 마무리하기 전에 다음날에 할 일들을 미리 적어놓고 자는 스타일이다. 그리고 다음 날에 계획한 순서대로 일을 진행하는 방법을 고수해왔다. 레벨 2를 진행하면서 이 부분이 살짝 바뀌었다. 가용시간이 1시간 정도고 현재 집중을 할 수 있는 상황이 아닌데도 불구하고, 집중해야 하는 작업을 고집한다면 효율이 정말 안 나올 것으로 생각했다. 나는 간단
4번째 문장에서 '나는'을 생략해도 될 것 같아요.

``집중할 수 있는 충분한 시간이 주어지면 그 시간을 몰두가 필요한 작업에 투자했다`` 를 ``집중할 수 있는 충분한 시간이 주어지면 몰두가 필요한 작업에 투자했다``와 같이 중복되는 명사들은 제거해도 좋을 것 같아요 ㅎㅎ

2021-05-29 08:23 UTC, xlffm3 commented on level2/README.md
> + 레벨 2 때에는 취침 시간을 크게 신경 쓰지 않고 집중이 된다면 최대한 집중이 유지되는 순간까지 공부했다. 그 덕분에 그날 하고자 했던 일 들을 모두 이룬 날이 늘었고 발 뻗고 개운하게 잠자리에 들 수 있었다. '직장을 가지게 되면 일찍 일어나야 하니 미리미리 몸에 익혀놔야 해!'라고 생각하고 다른 크루들의 하루 루틴이 이상적인 루틴으로 보여서 일찍 자
'직장을 가지게 되면 일찍 일어나야 하니 미리미리 몸에 익혀놔야 해!'라고 생각하고 다른 크루들의 하루 루틴이 이상적인 루틴으로 보여서 일찍 자고 일찍 일어나려고 했었다

해당 부분도 명사가 중복되서

'직장을 가지게 되면 일찍 일어나야 하니 미리미리 몸에 익혀놔야 해!'라고 생각하고 다른 크루들의 하루 루틴이 이상적으로 보여서 실천하려고 했다

와 같이 호흡을 짧게 줄일 수 있을 것 같아요 :)

2021-05-29 16:36 UTC, TaewanKimmmm approved these changes
안녕하세요, 파즈! 진중해 보이는 모습이 참 닮고 싶은 크루라고 생각합니다ㅎㅎㅎ

루틴을 정해놓고 계획적으로 사시는 것도 본받고 싶었네요.

학습하면서 느낀 점도 공감 많이 됐어요.

좋은 글 잘 읽었습니다~!

2021-05-29 16:36 UTC, TaewanKimmmm commented on level2/README.md
> + 레벨 1 때에는 올빼미 습성을 고치고자 다른 크루들의 기상 패턴을 파악하면서 '나도 일찍 자고 일찍 일어나야겠다'라고 다짐하며 실천하려고 노력했다. 그 결과 평소 집중을 하는 시간대인 새벽 시간을 이용하지 못하게 되면서 공부 효율이 떨어지기 시작했다.
실은 저도 올빼미족인데 크게 공감되네요..

2021-05-29 16:36 UTC, TaewanKimmmm commented on level2/README.md
> + 모르는 키워드를 맞닥뜨릴 때, 해당 키워드에 대해 조사하고 마크다운 형식으로 정리하며 학습한다. 이 상황에서 구글링을 먼저 하게 되는데, 레벨 1 때에는 사람들의 블로그를 통한 학습을 우선시했다. 레벨 2에 들어서는 공식문서를 먼저 훑으며 대략적인 내용을 파악한 후, 블로그를 통해 어떤 식으로 코드가 진행되는지 살펴보는 식으로 바뀌었다. 이러한 변경의
저도 요즘엔 공식 문서 찾는 빈도가 늘었어요 ㅎㅎ

2021-05-29 16:36 UTC, TaewanKimmmm commented on level2/README.md
> + 레벨 1 때에는 올빼미 습성을 고치고자 다른 크루들의 기상 패턴을 파악하면서 '나도 일찍 자고 일찍 일어나야겠다'라고 다짐하며 실천하려고 노력했다. 그 결과 평소 집중을 하는 시간대인 새벽 시간을 이용하지 못하게 되면서 공부 효율이 떨어지기 시작했다.
`평소 집중하는 시간대인`은 어떨까요!

2021-05-30 05:24 UTC, thisisyoungbin reviewed
파즈 안녕하세요~~ 
글 읽으면서 몇몇 부분들에 코멘트 남겼어요
개인적인 의견이라 파즈의 색깔이 남는 글이 되도록 참고해주세요 :)

학습방법에 자신의 루틴을 가져야 한다는 부분도 포함되어 좋았어요~~
시간을 효율적으로 사용하고 계신 게 멋지네요. 개인적으로 제가 어려워 하는 부분인데 저도 순서상관 없이 내일 할 일들을 정해봐야겠군요..

글 잘 읽었어요! 본인만의 루틴, 남들의 학습법을 따라야 하지 않는다고 생각하는 점에서 파즈 본인만의 방식을 잘 찾아가고 있는 거 같네요 :) 
파즈도 방학을 넘어 남은 기간 화이팅해요~~!!

2021-05-30 05:24 UTC, thisisyoungbin commented on level2/README.md
> + 레벨 2 때에는 취침 시간을 크게 신경 쓰지 않고 집중이 된다면 최대한 집중이 유지되는 순간까지 공부했다. 그 덕분에 그날 하고자 했던 일 들을 모두 이룬 날이 늘었고 발 뻗고 개운하게 잠자리에 들 수 있었다. '직장을 가지게 되면 일찍 일어나야 하니 미리미리 몸에 익혀놔야 해!'라고 생각하고 다른 크루들의 하루 루틴이 이상적인 루틴으로 보여서 일찍 자
`레벨 2 때에는 취침 시간을 크게 신경 쓰지 않고 집중이 된다면 최대한 집중이 유지되는 순간까지 공부했다.` 
'집중이 된다면 최대한 집중이 유지되는 순간까지'가 중복된 표현인 것 같아서
`레벨 2 때에는 취침 시간을 크게 신경쓰지 않고 최대한 집중이 유지되는 순간까지 공부했다.`로 표현해도 될 거 같아요!

2021-05-30 05:24 UTC, thisisyoungbin commented on level2/README.md
> + 레벨 2 때에는 취침 시간을 크게 신경 쓰지 않고 집중이 된다면 최대한 집중이 유지되는 순간까지 공부했다. 그 덕분에 그날 하고자 했던 일 들을 모두 이룬 날이 늘었고 발 뻗고 개운하게 잠자리에 들 수 있었다. '직장을 가지게 되면 일찍 일어나야 하니 미리미리 몸에 익혀놔야 해!'라고 생각하고 다른 크루들의 하루 루틴이 이상적인 루틴으로 보여서 일찍 자
`그러나 역시 본인한테 맞는 자신만의 루틴을 가지는 게 최고라는 것을 이번 기회에 확실하게 깨닫게 되었다. ` 이 부분도 위와 같이 `그러나 역시 본인한테 맞는 루틴을 가지는 게 최고라는 것을 ~` 혹은 `그러나 역시 자신만의 루틴을 가지는게 ~` 식으로 표현할 수 있을 거 같아요!

2021-05-30 05:24 UTC, thisisyoungbin commented on level2/README.md
> + 모르는 키워드를 맞닥뜨릴 때, 해당 키워드에 대해 조사하고 마크다운 형식으로 정리하며 학습한다. 이 상황에서 구글링을 먼저 하게 되는데, 레벨 1 때에는 사람들의 블로그를 통한 학습을 우선시했다. 레벨 2에 들어서는 공식문서를 먼저 훑으며 대략적인 내용을 파악한 후, 블로그를 통해 어떤 식으로 코드가 진행되는지 살펴보는 식으로 바뀌었다. 이러한 변경의
학습할 양이 많아질 수록 파즈 방식대로 공식문서를 먼저 찾아보는 게 좋은 거 같아요ㅋㅋ 그 후 구글링으로 취사 선택!

2021-05-30 05:24 UTC, thisisyoungbin commented on level2/README.md
> +사람마다 제각기 학습법이 다르고 꼭 남들의 학습법을 따라야 한다고 생각하지는 않는다. 좋아 보이는 것은 그것대로 내 것으로 취하면 될 것이고, 나와 맞지 않는다고 생각된다면 그냥 넘기면 된다. 그래서 이번 주제에 대해 다른 크루들의 학습 방법이 정말 기대된다. 레벨 3을 진행하면서 학습법은 또다시 바뀔 수 있다고 생각한다. 다들 본인에게 맞는 학습법을 꼭
파즈도 화이팅!! 👍 👍

2021-05-30 05:40 UTC, Be-poz commented on level2/README.md
> + 레벨 2 때에는 취침 시간을 크게 신경 쓰지 않고 집중이 된다면 최대한 집중이 유지되는 순간까지 공부했다. 그 덕분에 그날 하고자 했던 일 들을 모두 이룬 날이 늘었고 발 뻗고 개운하게 잠자리에 들 수 있었다. '직장을 가지게 되면 일찍 일어나야 하니 미리미리 몸에 익혀놔야 해!'라고 생각하고 다른 크루들의 하루 루틴이 이상적인 루틴으로 보여서 일찍 자
케빈 첨삭 감사해요~! 진짜 언어고수 느낌나네요!!

2021-05-30 05:41 UTC, Be-poz commented on level2/README.md
> + 레벨 1 때에는 올빼미 습성을 고치고자 다른 크루들의 기상 패턴을 파악하면서 '나도 일찍 자고 일찍 일어나야겠다'라고 다짐하며 실천하려고 노력했다. 그 결과 평소 집중을 하는 시간대인 새벽 시간을 이용하지 못하게 되면서 공부 효율이 떨어지기 시작했다.
저는 이제 받아들이고 새벽시간을 즐기고 있습니다! 그 다음날 힘들긴 하지만요 ㅎㅎ

2021-05-30 05:41 UTC, Be-poz commented on level2/README.md
> + 레벨 1 때에는 올빼미 습성을 고치고자 다른 크루들의 기상 패턴을 파악하면서 '나도 일찍 자고 일찍 일어나야겠다'라고 다짐하며 실천하려고 노력했다. 그 결과 평소 집중을 하는 시간대인 새벽 시간을 이용하지 못하게 되면서 공부 효율이 떨어지기 시작했다.
좋은 지적입니다 감사합니다~

2021-05-30 05:42 UTC, Be-poz commented on level2/README.md
> + 레벨 2 때에는 취침 시간을 크게 신경 쓰지 않고 집중이 된다면 최대한 집중이 유지되는 순간까지 공부했다. 그 덕분에 그날 하고자 했던 일 들을 모두 이룬 날이 늘었고 발 뻗고 개운하게 잠자리에 들 수 있었다. '직장을 가지게 되면 일찍 일어나야 하니 미리미리 몸에 익혀놔야 해!'라고 생각하고 다른 크루들의 하루 루틴이 이상적인 루틴으로 보여서 일찍 자
좋아요~!

2021-05-30 05:43 UTC, Be-poz commented on level2/README.md
> + 레벨 2 때에는 취침 시간을 크게 신경 쓰지 않고 집중이 된다면 최대한 집중이 유지되는 순간까지 공부했다. 그 덕분에 그날 하고자 했던 일 들을 모두 이룬 날이 늘었고 발 뻗고 개운하게 잠자리에 들 수 있었다. '직장을 가지게 되면 일찍 일어나야 하니 미리미리 몸에 익혀놔야 해!'라고 생각하고 다른 크루들의 하루 루틴이 이상적인 루틴으로 보여서 일찍 자
여기서도 중복이 있었네요 . .!! 지적 감사합니다

2021-05-30 06:16 UTC, Be-poz commented
@xlffm3 , @thisisyoungbin , @TaewanKimmmm  
피드백 반영했습니다~! 추가 수정해야 될 부분 보이시면 말씀해주세욥!

2021-05-30 08:00 UTC, jho2301 reviewed
안녕하세요 파즈 
글 잘 읽었습니다 ㅎㅎ

수정사항 간단하게 남겨봤어요
읽어주시고 의견 남겨주시면 감사하겠습니다~

2021-05-30 08:00 UTC, jho2301 commented on level2/README.md
> + 모르는 키워드를 맞닥뜨릴 때, 해당 키워드에 대해 조사하고 마크다운 형식으로 정리하며 학습한다. 이 상황에서 구글링을 먼저 하게 되는데, 레벨 1 때에는 사람들의 블로그를 통한 학습을 우선시했다. 레벨 2에 들어서는 공식문서를 먼저 훑으며 대략적인 내용을 파악한 후, 블로그를 통해 어떤 식으로 코드가 진행되는지 살펴보는 식으로 바뀌었다. 이러한 변경의
내용이 깊어질수록 블로그 포스팅들의 중복이 잦아지는 것을 느꼈고 확실한 신뢰가 가지 않았다.

`중복이 잦아져서 신뢰가 가지 않았다`는 문장의 근거가 조금 막연한 것 같아요!
중복이 잦다는게 어떤 의미인지 부연해주셔도 좋지 않을까 싶네요!

2021-05-30 08:00 UTC, jho2301 commented on level2/README.md
> +사람마다 제각기 학습법이 다르고 꼭 남들의 학습법을 따라야 한다고 생각하지는 않는다. 좋아 보이는 것은 그것대로 내 것으로 취하면 될 것이고, 나와 맞지 않는다고 생각된다면 그냥 넘기면 된다. 그래서 이번 주제에 대해 다른 크루들의 학습 방법이 정말 기대된다. 레벨 3을 진행하면서 학습법은 또다시 바뀔 수 있다고 생각한다. 다들 본인에게 맞는 학습법을 꼭
화이팅입니다 ㅎㅎ!

2021-05-30 10:25 UTC, pjy1368 approved these changes
안녕하세요 파즈 😃
다른 크루들이 피드백을 잘해주셔서 크게 건드릴 내용이 없네요.
맹목적으로 남의 루틴을 따르는 것이 아니라, 남을 참고하여 자신만의 효과적인 루틴을 만드는 방식이 인상적이었어요.
이렇게 앞으로 어려운 일이 있어도 자신만의 루틴을 만들어서 헤쳐나가시면 좋을 것 같아요 👍

2021-05-30 10:25 UTC, pjy1368 commented on README.md
> +미션을 진행하며 대부분의 시간을 보냈다. 페어와 함께일 때는 남는 저녁 시간에도 미션에 대해 고민했다. 페어와 깨지고 난 뒤에는 오직 오전과 낮에만 수행했다. 남은 저녁 시간에는 필독서와 미션을 진행하면서 생긴 의문점들을 찾아보고 정리했다. 나름 알차게 보낸 것 같은데 대체 어디서 불안감이 스멀스멀 올라오는 것일까? 내 생활 패턴을 살펴봐야겠다.
```suggestion
미션을 진행하며 대부분의 시간을 보냈다. 페어와 함께일 때는 남는 저녁 시간에도 미션에 대해 고민했다. 페어와 깨지고 난 뒤에는 오직 오전과 낮에만 수행했다. 남은 저녁 시간에는 필독서를 읽고, 미션을 진행하면서 생긴 의문점들을 찾아보고 정리했다. 나름 알차게 보낸 것 같은데 대체 어디서 불안감이 스멀스멀 올라오는 것일까? 내 생활 패턴을 살펴봐야겠다.  
```
필독서를 A로 두고, 미션을 진행하면서 생긴 의문점들을 B로 두었을 때, 'A와 B를 찾아보고 정리했다.'라는 문장이 되겠네요. 필독서를 찾아 보고 정리했다라는 문맥이 의도하신 것이면 이대로 두면 괜찮으나, 제 개인적인 생각은 '필독서를 읽었다.'로 문맥을 이어가는 것이 어떨까요?

2021-05-30 10:25 UTC, pjy1368 commented on README.md
> +우테코 전의 생활은 올빼미 그 자체였다. 저녁이 되면 모든 방 불을 끄고 스탠드 하나에 의지한 채 어둡고 조용한 환경 속에서 집중하는 것을 즐겼다. 실제로 집중도 더 잘됐다. 새벽 3, 4시에 잠들고 9시 30분이나 10시 사이에 일어나곤 했다. 이랬던 생활 패턴을 우테코를 시작하고부터는 낮 시간을 조금 더 활용하는 방향으로 바꿨다. 당연하게도 잠자리에
```suggestion
우테코 전의 생활은 올빼미 그 자체였다. 저녁이 되면 모든 방 불을 끄고 스탠드 하나에 의지한 채 어둡고 조용한 환경 속에서 집중하는 것을 즐겼다. 실제로 집중도 더 잘됐다. 새벽 3, 4시에 잠들고 9시 30분이나 10시 사이에 일어나곤 했다. 이랬던 생활 패턴을 우테코를 시작하고부터는 낮 시간을 조금 더 활용하는 방향으로 바꿨다. 당연하게도 잠자리에 드는 시간은 한 번에 바꾸기가 힘들어 취침 시간을 줄이는 방향을 택했다. 자극을 받기 위해 데일리 크루들의 취침 시간과 기상 시간을 물어보고 다녔다. 크루들의 부지런한 생활 패턴에 자극을 받고 난 뒤에는 크루들의 취침, 기상 시간을 따라 해보려고 노력했다. 그러나 무작정 따라 하려다 보니 학습의 능률이 떨어졌다. 이를 통해 나의 생활과 조화를 이루는 형태로 타인의 장점을 받아들여야 한다는 것을 알았다. 그저 현재의 내가 가진 생활 패턴이 잘못됐다고 생각하고 상대의 패턴을 그대로 받아들이려 한 것이 독이 됐던 것이다. 다른 사람들은 정 시간에 자고 일어난다는 생각. 즉, 나 이외의 사람들은 알차게 보내고 있다는 무의식적인 생각이 나를 괴롭히고 있었다. 꼭 취침과 관련된 것이 아니더라도 말이다. 열심인 크루들이 많기 때문에 괜히 조바심을 내고 불안해한 것이다. 하지만, 그에 대한 자극이 있었고 그것은 분명 자신을 불타오르게 했다.
```
본인보다는 '나'라는 표현을 쓰는 것이 어떨까요?

2021-05-30 10:25 UTC, pjy1368 commented on level2/README.md
> + 모르는 키워드를 맞닥뜨릴 때, 해당 키워드에 대해 조사하고 마크다운 형식으로 정리하며 학습한다. 이 상황에서 구글링을 먼저 하게 되는데, 레벨 1 때에는 사람들의 블로그를 통한 학습을 우선시했다. 레벨 2에 들어서는 공식문서를 먼저 훑으며 대략적인 내용을 파악한 후, 블로그를 통해 어떤 식으로 코드가 진행되는지 살펴보는 식으로 바뀌었다. 이러한 변경의
내용이 중복된다고 신뢰가 가지 않는 것일까요? 파즈가 신뢰가 가지 않았던 이유를 더 명확하게 써 주시면 좋을 것 같아요.

2021-05-30 11:47 UTC, qhals321 commented
안녕하세요~! 지나가던 나봄이에요!!
파즈의 학습 열정을 엿볼 수 있는 글이어서 너무 좋았어요!!
파즈가 학습하는 것을 옆에서 볼 때마다 대단하다라고 생각했는데 이렇게 글을 보니 더 대단하게 느껴지네요!!
본인만의 색깔을 가진 파즈! 계속해서 응원할게요!! 파이팅~!!

2021-05-30 14:09 UTC, Be-poz commented on README.md
> +미션을 진행하며 대부분의 시간을 보냈다. 페어와 함께일 때는 남는 저녁 시간에도 미션에 대해 고민했다. 페어와 깨지고 난 뒤에는 오직 오전과 낮에만 수행했다. 남은 저녁 시간에는 필독서와 미션을 진행하면서 생긴 의문점들을 찾아보고 정리했다. 나름 알차게 보낸 것 같은데 대체 어디서 불안감이 스멀스멀 올라오는 것일까? 내 생활 패턴을 살펴봐야겠다.
오메메 이거 레벨1 리드미에요 . . ㅜ.ㅜ

2021-05-30 14:09 UTC, Be-poz commented on README.md
> +우테코 전의 생활은 올빼미 그 자체였다. 저녁이 되면 모든 방 불을 끄고 스탠드 하나에 의지한 채 어둡고 조용한 환경 속에서 집중하는 것을 즐겼다. 실제로 집중도 더 잘됐다. 새벽 3, 4시에 잠들고 9시 30분이나 10시 사이에 일어나곤 했다. 이랬던 생활 패턴을 우테코를 시작하고부터는 낮 시간을 조금 더 활용하는 방향으로 바꿨다. 당연하게도 잠자리에
ㅠㅠ오것두 렙1. .

2021-05-30 14:09 UTC, Be-poz commented on level2/README.md
> + 모르는 키워드를 맞닥뜨릴 때, 해당 키워드에 대해 조사하고 마크다운 형식으로 정리하며 학습한다. 이 상황에서 구글링을 먼저 하게 되는데, 레벨 1 때에는 사람들의 블로그를 통한 학습을 우선시했다. 레벨 2에 들어서는 공식문서를 먼저 훑으며 대략적인 내용을 파악한 후, 블로그를 통해 어떤 식으로 코드가 진행되는지 살펴보는 식으로 바뀌었다. 이러한 변경의
알겠습니닸!!

2021-05-30 14:10 UTC, Be-poz commented on level2/README.md
> + 모르는 키워드를 맞닥뜨릴 때, 해당 키워드에 대해 조사하고 마크다운 형식으로 정리하며 학습한다. 이 상황에서 구글링을 먼저 하게 되는데, 레벨 1 때에는 사람들의 블로그를 통한 학습을 우선시했다. 레벨 2에 들어서는 공식문서를 먼저 훑으며 대략적인 내용을 파악한 후, 블로그를 통해 어떤 식으로 코드가 진행되는지 살펴보는 식으로 바뀌었다. 이러한 변경의
내용 추가해보겠습니다~!

2021-05-30 14:27 UTC, 2SOOY approved these changes
안녕하세요 :) 파즈 !

파즈의 다른 크루들의 학습법에 맞추려 했던 시도에서 자신한테 가장 걸맞는 학습법을 찾은 경험을 잘 이야기 잘 읽었습니다 👍👍👍
중간 중간 공감가는 표현의 문장들이 있어서 좋았습니다 :)

`공식문서 + 블로그(아티클)`을 번갈아 가는 공부법이 기억에 남네요 !

글 작성하시느라 고생 많으셨습니다 :)

2021-05-30 14:27 UTC, 2SOOY commented on level2/README.md
> + 레벨 2 때에는 취침 시간을 크게 신경 쓰지 않고 최대한 집중이 유지되는 순간까지 공부했다. 그 덕분에 그날 하고자 했던 일 들을 모두 이룬 날이 늘었고 발 뻗고 개운하게 잠자리에 들 수 있었다. '직장을 가지게 되면 일찍 일어나야 하니 미리미리 몸에 익혀놔야 해!'라고 생각하고 다른 크루들의 하루 루틴이 이상적으로 보여서 실천하려고 했다. 그러나 역시
> 역시 자신만의 루틴을 가지는 게 최고라는 것을 이번 기회에 확실하게 깨닫게 되었다.

취침 습관을 통해 파즈만의 루틴에 대해 재정립하셨군요 👍

2021-05-30 14:27 UTC, 2SOOY commented on level2/README.md
> + 모르는 키워드를 맞닥뜨릴 때, 해당 키워드에 대해 조사하고 마크다운 형식으로 정리하며 학습한다. 이 상황에서 구글링을 먼저 하게 되는데, 레벨 1 때에는 사람들의 블로그를 통한 학습을 우선시했다. 레벨 2에 들어서는 공식문서를 먼저 훑으며 대략적인 내용을 파악한 후, 블로그를 통해 어떤 식으로 코드가 진행되는지 살펴보는 식으로 바뀌었다. 이러한 변경의
> 레벨 2에 들어서는 공식문서를 먼저 훑으며 대략적인 내용을 파악한 후, 블로그를 통해 어떤 식으로 코드가 진행되는지 살펴보는 식으로 바뀌었다.

항상 공식 문서를 접하면 이해가 안돼도 계속 붙들곤 했는데, 이런 학습 방법도 좋겠군요 :)

2021-05-30 14:27 UTC, 2SOOY commented on level2/README.md
> + 모든 기본적인 내용을 숙지한 상태로 심화 내용을 학습하는 것이 익숙했다. 그러나 스프링을 학습하면서 기존의 학습 방법을 유지하려니 공부해야 할 양에 압도되어 불가능하다는 것을 깨달았다. 결국 Top-Down 방식을 채택하게 되었다. 그 순간 막히는 부분만 해결하고 넘어갔다. 처음에는 이 방법이 익숙지 않아서 이게 맞는 방법인지 확신이 들지 않았다. 그러
> '아, 이거 지난번에 공부했던 그 내용이 이 내용과 관련 있었던 거구나' 하며 그제야 작은 그림들이 맞춰지며 큰 그림이 되어간다는 것을 느낄 수가 있었다.

개인적으로 이 표현이 마음에 드네용 👍 저는 이런 느낌이 무언가를 학습하는데 있어 재미를 느끼게 하는 것 같네요 !!!

2021-05-30 14:27 UTC, 2SOOY commented on level2/README.md
> +사람마다 제각기 학습법이 다르고 꼭 남들의 학습법을 따라야 한다고 생각하지는 않는다. 좋아 보이는 것은 그것대로 내 것으로 취하면 될 것이고, 나와 맞지 않는다고 생각된다면 그냥 넘기면 된다. 그래서 이번 주제에 대해 다른 크루들의 학습 방법이 정말 기대된다. 레벨 3을 진행하면서 학습법은 또다시 바뀔 수 있다고 생각한다. 다들 본인에게 맞는 학습법을 꼭
파이팅 ✊✊✊

2021-05-31 03:36 UTC, thisisyoungbin approved these changes
파즈~~ 수정하신 사항 확인했어용 리뷰 반영 감사합니다!!
바~로 어프루브 하겠습니다!! 👍

2021-05-31 03:49 UTC, xlffm3 approved these changes
안녕하세요 파즈! 피드백 반영 잘 하셨네요. 수고많으셨습니다~~ 레벨 3도 화이팅!

2021-05-31 03:54 UTC, TaewanKimmmm commented
안녕하세요 파즈 ㅎㅎㅎ수고 많이하셨어요 방학 야무지게 보내시고 레벨3 화이팅입니다!

2021-05-31 06:29 UTC, jho2301 approved these changes
피드백 반영확인했어요! 어프루브할게요!

2021-06-22 07:33 UTC, Wonmi91 approved these changes
안녕하세요 파즈. 워니입니다 :)

파즈는 자신만의 학습법이 명확하게 있군요. 그 4가지를 읽기 쉽게 정리해 주셔서 잘 읽을 수 있었습니다. 이 또한 파즈가 경험하고 터득한 것이겠죠! 
파즈의 말대로 사람마다 제각기 다른 학습법을 가지고 있기 때문에 본인 색깔에 맞는 적절한 학습법을 취하는 것이 정말 중요한 것 같아요.

글 쓰느라 고생 많으셨어요 :)

2021-06-22 07:33 UTC, merged