[레벨 1 글쓰기 미션] 도비(김정혁) 미션 제출합니다.
woowacourse/woowa-writing-3 pull request #11
Opened 2021-03-16 00:14 UTC by zereight

[여기서 읽으실 수 있습니다!](https://github.com/zereight/woowa-writing-3)

에드 (@sjpark-dev)
배럴 (@knae11)
조엘 (@PapimonLikelion)
로키 (@Rok93)
욘 (@thisisyoungbin)
하루 (@365kim)

어떤 구체적인 활동보다, 우테코 한 달간의 전체적인 회고처럼 작성해봤어요!
저는 어떤 리뷰라도 상처받지 않으니, 저의 README.md를 리뷰로 부숴주세요!

2021-03-16 13:15 UTC, knae11 reviewed
오ㅎㅎㅎ 칼럼스러운 글을 작성해주셔서 공감되는 내용도 많았네요ㅎㅎㅎ 실패를 하며 더 도전하고 배우고 싶게 만드는 글입니다👍

2021-03-16 13:15 UTC, knae11 commented on README.md
> +우테코 곳곳에 스며들어있는, 어쩌면 지식을 습득하는 공부보다 하찮게 여겨질 수 있는 그런 활동들이 있다. 하지만 그런 하찭아 보일 수 있는 행동들이 결국 나의 성장에 유의미한 거름이 되고, 함께 성장할 수 있는 조직문화를 만들었다.
```suggestion
우테코 곳곳에 스며들어있는, 어쩌면 지식을 습득하는 공부보다 하찮게 여겨질 수 있는 그런 활동들이 있다. 하지만 그런 하찮아 보일 수 있는 행동들이 결국 나의 성장에 유의미한 거름이 되고, 함께 성장할 수 있는 조직문화를 만들었다.
```

오타인듯 합니당

2021-03-16 13:15 UTC, knae11 commented on README.md
> +그럼 답은 간단하다. 최대한 실패를 많이 해도 되는 시기에, 수많은 실패를 해버리고 성장해야 나중에 실패할 확률이 낮아지는 것이다.
```suggestion
그럼 답은 간단하다. 최대한 실패를 많이 해도 되는 시기에, 수많은 실패를 하고 성장해야 나중에 실패할 확률이 낮아지는 것이다.
```
이런식으로 바꾸면 조금 더 자연스러울까 싶어요ㅎㅎ

2021-03-16 13:15 UTC, knae11 commented on README.md
> +그럼 답은 간단하다. 최대한 실패를 많이 해도 되는 시기에, 수많은 실패를 해버리고 성장해야 나중에 실패할 확률이 낮아지는 것이다.
좋은얘기네요ㅎㅎㅎ👍👍

2021-03-16 13:15 UTC, knae11 commented on README.md
> +하지만 우리 사회는 가파른 성장을 해오면서 항상 빠른 성공을 기대해왔다. 실패보단 성공이 좋은 것이라 배웠고, 실패한 사람에게 손가락질을 해왔다. 그렇게 실패는 두렵고, 기피해야 할 대상이 되었다. 우리는 실패를 통한 유의미한 성장이 아니라 실패 없이 빠른 성공에 집착하는 이른바 ‘성공의 민족’이었던 것이다.
```suggestion
하지만 우리 사회는 가파른 성장을 해오면서 항상 빠른 성공을 기대해왔다. 실패보단 성공이 좋은 것이라 배웠고, 실패한 사람에게 손가락질을 해왔다. 그렇게 실패는 두렵고, 기피해야 할 대상이 되었다. 우리는 실패를 통한 유의미한 성장을 하는 것이 아니라 실패 없이 빠른 성공에 집착하는 이른바 ‘성공의 민족’이었던 것이다. 
```
이렇게 하면 좀 더 나을까요?!😃

2021-03-16 13:15 UTC, knae11 commented on README.md
> +그야말로 ‘실패에 최적화된’ 환경이었다. 또한, 그것을 통해 함께 성장할 수 있는 환경이 마련된 곳이었다. 성장하고자 하는 의지만 있으면 성장을 할 수 있는 곳이라는 확신이 생기는 곳이었다. 한 달밖에 경험해보지 못했지만, 점차 내가 ‘성공의 민족’에서 ‘성장의 민족’으로 바뀌고 있다는 느낌을 받아서 참으로 뿌듯했다.
```suggestion
그야말로 ‘실패에 최적화된’ 환경이었다. 또한, 그것을 통해 함께 성장할 수 있는 환경이 마련된 곳이었다. 성장하고자 하는 의지만 있으면 성장을 할 수 있는 곳이라는 확신이 생기는 곳이었다. 우테코 과정을 경험한지 한 달이지만, 점차 내가 ‘성공의 민족’에서 ‘성장의 민족’으로 바뀌고 있다는 느낌을 받아서 참으로 뿌듯했다.
```
좀더 능동적 표현이 가능할것같아요😆

2021-03-16 13:15 UTC, knae11 commented on README.md
> +막연히 함께 공부하는 것이 좋다는 사실은 알았다. 하지만 그 효과를 체험해볼 생각은 하지 못했었다. 다행히 우테코는 나에게 그런 기회를 주었다.
체험해볼 생각을 못한걸까요?  체험할 기회가 없었던 걸까요?

2021-03-16 14:01 UTC, 365kim commented on README.md
> +개인마다 다르지만, 인생에서 실패할 수 있는 횟수는 정해져 있다고 한다.
정말 멋진 말이에요!👍👍👍  실패할 총량이 정해져있다면 빨리 실패해버리자! 싶은 마음이 들기도 하구용 ㅎㅎㅎ💪💪

2021-03-16 14:02 UTC, 365kim commented on README.md
> +그럼 답은 간단하다. 최대한 실패를 많이 해도 되는 시기에, 수많은 실패를 해버리고 성장해야 나중에 실패할 확률이 낮아지는 것이다.
엇 저는 `해버리고`가 '해치워버린다'라는 느낌이 있어서 `해버리고`도 좋은 것 같아용! 개인 취향입니당 ㅎㅎ

2021-03-16 14:04 UTC, 365kim commented on README.md
> +하지만 우리 사회는 가파른 성장을 해오면서 항상 빠른 성공을 기대해왔다. 실패보단 성공이 좋은 것이라 배웠고, 실패한 사람에게 손가락질을 해왔다. 그렇게 실패는 두렵고, 기피해야 할 대상이 되었다. 우리는 실패를 통한 유의미한 성장이 아니라 실패 없이 빠른 성공에 집착하는 이른바 ‘성공의 민족’이었던 것이다.
실패한 사람에게 손가락질을... 수업시간에 들었던 `심리적 안전`과는 반대되는 현실이네요 😭😭

2021-03-16 14:07 UTC, 365kim commented on README.md
> +사람은 사회적인 동물이라서, 사회적인 관념 속에 진실을 묻고 자신을 속이며 살아가고 있기 때문이 아닐까? 또한 그사이의 괴리감 때문에 불행을 느끼고 있는 것은 아닐까?
시간적 거리는 `그사이(그새)` 와 같이 붙여쓰고 공간적 거리는 `그 사이`로 띄어쓴다고 합니다. 여기서는 맥락상 시간적 거리보다 공간적 거리를 의미한 것 같아서 띄어쓰는 것이 맞지 않을까 싶어용 :) [참고링크](https://news.joins.com/article/20500767)

2021-03-16 14:08 UTC, 365kim commented on README.md
> +우테코는 나에게 그런 곳이었다. 학습에 열정이 있는 사람들이 모여, 서로의 의견을 공유하고 발전 시켜 나간다. 실패하더라도 그 누구도 비난하거나 우습게 보지 않는다. 좋은 시도였으며 어떻게 하면 더 발전해나갈 수 있을지에 대해 고민을 하게 한다. 평소와는 다른 방법, 자신만의 생각과 표현들이 자유롭게 오가고 서로가 서로에게 새로운 인사이트를 제시한다.
도비두~? 야나두~! 🙌🙌

2021-03-16 14:10 UTC, 365kim commented on README.md
> +이미 우리가 걷고 있는 길을 걸어가 보았던 믿고 의지할 수 있는 코치, 선배들도 생겼다.
그냥 담백한 문장인데 읽으면 왠지 가슴이 웅장해지는 문장이네요,,, 🥺😎

2021-03-16 14:13 UTC, 365kim commented on README.md
> +어쩌면 지식을 습득하는 것보다 중요한 것이, 지식을 습득할 수 있는 환경을 만드는 것이 아닐까 하는 생각이 들었다. 그리고 함께하는 성장을 위해 놓치고 있는 또 다른 하찮은 행동들이 뭐가 있을지에 대해 고민하게 된 한 달이었다.
처음에 정말 하찮은 것을 의미했던 `하찮다`이라는 표현이, 끝에는 자연스럽게 `중요하다`라는 의미로 전환되어 읽히네요 ㅎㅎ 하찮은 것의 중요함! 👍 매력적인 표현이에요! 👍

2021-03-16 14:14 UTC, 365kim commented on README.md
> +하지만 우리 사회는 가파른 성장을 해오면서 항상 빠른 성공을 기대해왔다. 실패보단 성공이 좋은 것이라 배웠고, 실패한 사람에게 손가락질을 해왔다. 그렇게 실패는 두렵고, 기피해야 할 대상이 되었다. 우리는 실패를 통한 유의미한 성장이 아니라 실패 없이 빠른 성공에 집착하는 이른바 ‘성공의 민족’이었던 것이다.
`성공`이랑 `성장`이라는 워딩이 대조되는 부분도 좋았어요! 👏👏👏

2021-03-16 14:17 UTC, 365kim commented
코멘트 남겨봤어요 👏👏👏   도비의 재치있는 표현이 돋보인 글이네용!! 
띄어쓰기 맞춤법 확인 한 번 해주시면 바로 approve하겠습니다 :) 🚀🚀🚀

2021-03-16 14:17 UTC, 365kim requested changes
코멘트 남겨봤어요 👏👏👏   도비의 재치있는 표현이 돋보인 글이네용!! 
띄어쓰기 맞춤법 확인 한 번 해주시면 바로 approve하겠습니다 :) 🚀🚀🚀

2021-03-16 14:58 UTC, zereight commented on README.md
> +우테코 곳곳에 스며들어있는, 어쩌면 지식을 습득하는 공부보다 하찮게 여겨질 수 있는 그런 활동들이 있다. 하지만 그런 하찭아 보일 수 있는 행동들이 결국 나의 성장에 유의미한 거름이 되고, 함께 성장할 수 있는 조직문화를 만들었다.
배럴 안녕하세요~~ 글쓰기 미션으로 먼저 뵙게되어서 아쉽네요 ㅜㅜ
갑자기 궁금한건데 닉네임의 `배럴`은 `더블 배럴 샷건`의 배럴에서 유래한 것일까요? 알려주세요오! >_< <del>총 게임 중독자임</del>

> 오타인듯 합니당

앗 배럴 꼼꼼한 리뷰 감사합니다~~! 
맞춤법검사기 돌렸는데 왜 못찾았지..!

2021-03-16 15:00 UTC, zereight commented on README.md
> +우테코 곳곳에 스며들어있는, 어쩌면 지식을 습득하는 공부보다 하찮게 여겨질 수 있는 그런 활동들이 있다. 하지만 그런 하찭아 보일 수 있는 행동들이 결국 나의 성장에 유의미한 거름이 되고, 함께 성장할 수 있는 조직문화를 만들었다.
[수정](https://github.com/woowacourse/woowa-writing-3/pull/11/commits/472bb02ba934c53ccb92a5fb80ed24242f1c1d1e)했어요!

2021-03-16 15:13 UTC, zereight commented on README.md
> +그야말로 ‘실패에 최적화된’ 환경이었다. 또한, 그것을 통해 함께 성장할 수 있는 환경이 마련된 곳이었다. 성장하고자 하는 의지만 있으면 성장을 할 수 있는 곳이라는 확신이 생기는 곳이었다. 한 달밖에 경험해보지 못했지만, 점차 내가 ‘성공의 민족’에서 ‘성장의 민족’으로 바뀌고 있다는 느낌을 받아서 참으로 뿌듯했다.
배럴의 좋은 피드백에 살좀 붙여봤어요 히히  괜찮나요?!
`우테코 과정을 경험한지 이제 겨우 한 달이지만` 
[수정](https://github.com/woowacourse/woowa-writing-3/pull/11/commits/4ce8c2e4c3970b43f928c0dcb951b8ec82b4c09c)

2021-03-16 15:14 UTC, zereight commented on README.md
> +개인마다 다르지만, 인생에서 실패할 수 있는 횟수는 정해져 있다고 한다.
맞아요 하루 어서 많이 실패해버리세요~!!

2021-03-16 15:16 UTC, zereight commented on README.md
> +하지만 우리 사회는 가파른 성장을 해오면서 항상 빠른 성공을 기대해왔다. 실패보단 성공이 좋은 것이라 배웠고, 실패한 사람에게 손가락질을 해왔다. 그렇게 실패는 두렵고, 기피해야 할 대상이 되었다. 우리는 실패를 통한 유의미한 성장이 아니라 실패 없이 빠른 성공에 집착하는 이른바 ‘성공의 민족’이었던 것이다.
감사합니다 >_<

2021-03-16 15:19 UTC, zereight commented on README.md
> +막연히 함께 공부하는 것이 좋다는 사실은 알았다. 하지만 그 효과를 체험해볼 생각은 하지 못했었다. 다행히 우테코는 나에게 그런 기회를 주었다.
기회는 충분히 만들어갈 수 있었으나, 노력해볼 생각을 하지 못했던것 같아요! 흑흑
어쩌면 새로운 시도가 두려웠던것 같기도 하구요. 😭

2021-03-16 15:25 UTC, zereight commented on README.md
> +사람은 사회적인 동물이라서, 사회적인 관념 속에 진실을 묻고 자신을 속이며 살아가고 있기 때문이 아닐까? 또한 그사이의 괴리감 때문에 불행을 느끼고 있는 것은 아닐까?
와우 오늘 처음 알았어요. 충격이네요 ㅋㅋ [수정](https://github.com/woowacourse/woowa-writing-3/pull/11/commits/ea414afbd7acb800f3da2f1dfa8c06d7dde0be8d) 했어요!
하루는 국어를 참 잘하시는군요!

2021-03-16 15:25 UTC, zereight commented on README.md
> +우테코는 나에게 그런 곳이었다. 학습에 열정이 있는 사람들이 모여, 서로의 의견을 공유하고 발전 시켜 나간다. 실패하더라도 그 누구도 비난하거나 우습게 보지 않는다. 좋은 시도였으며 어떻게 하면 더 발전해나갈 수 있을지에 대해 고민을 하게 한다. 평소와는 다른 방법, 자신만의 생각과 표현들이 자유롭게 오가고 서로가 서로에게 새로운 인사이트를 제시한다.
더 공감해주세요!

2021-03-16 15:27 UTC, zereight commented on README.md
> +이미 우리가 걷고 있는 길을 걸어가 보았던 믿고 의지할 수 있는 코치, 선배들도 생겼다.
하루는 감수성이 참 풍부하시군요!

2021-03-16 15:28 UTC, zereight commented on README.md
> +어쩌면 지식을 습득하는 것보다 중요한 것이, 지식을 습득할 수 있는 환경을 만드는 것이 아닐까 하는 생각이 들었다. 그리고 함께하는 성장을 위해 놓치고 있는 또 다른 하찮은 행동들이 뭐가 있을지에 대해 고민하게 된 한 달이었다.
사실 저말은 우아한 형제들 한명수 이사님이 말해주신 겁니다! (비밀)

2021-03-16 15:33 UTC, thisisyoungbin reviewed
도비 안녕하세요~!!! 백엔드 크루 욘입니다 !!ㅎㅎ
하루와 마찬가지로 FE 크루들을 루터회관이 아닌 글쓰기 리뷰를 통해 먼저 만나뵙게 돼서 참 아쉬워요ㅠㅜ...


도비가 가진 `실패에 대한 용기`가 정말 멋있다고 생각이 드는 글이었어요!!
우테코 한 달 생활을 하며 크루나 코치진들에게 느끼는 부분도 많이 공감했습니다.ㅎㅎㅎ


리뷰 남긴 부분들은 도비 글을 읽으며 든 개인적인 생각들이에요. '이렇게 읽는 사람도 있구나'하고 읽어주시고 참고할 만한 부분은 참고해주시면 될 것 같아요!! 성장 to 성공!!으로 수료까지 같이 힘내봐요 💪

2021-03-16 15:33 UTC, thisisyoungbin commented on README.md
> +도대체 왜 ‘실패는 성공의 어머니’라는 진실을 수십 번을 듣고 머리로는 알고 있는데, 왜 사람들은 모순적으로 실패를 기피하는 대상으로 보는 것일까?
`도대체 왜 ‘실패는 성공의 어머니’라는 진실을 수십 번을 듣고 머리로는 알고 있는데, 왜 사람들은 모순적으로 실패를 기피하는 대상으로 보는 것일까?` 
왜 라는 의문표현이 두 번 나와서 좀 어색하게 읽혔는데요! 


`'실패는 성공의 어머니'라는 진실을 .. , 왜 사람들은 모순적으로 ... ' `
`'실패는 성공의 어머니'라는 진실을 .. , 모순적이게도 사람들은 실패를 기피하는 대상으로 본다.' `
이런식으로 줄여볼 수 있을 것 같아요!

2021-03-16 15:33 UTC, thisisyoungbin commented on README.md
> +그렇다면 실패를 장려하고 격려해주는 동료가 있고, 이끌어주는 의지할만한 멘토가 있는 환경이 생긴다면 어떨까?
실패를 격려해준다는 표현으로 읽혀서 개인적으로 조금 어색했어요!

`실패를 장려하고, 실패했을 때 격려해주는 동료와 이끌어 주는 ... ` 이런식으로 의미를 분명하게 나타낼 수 있을 것 같아요 :)

2021-03-16 15:33 UTC, thisisyoungbin commented on README.md
> +우테코는 나에게 그런 곳이었다. 학습에 열정이 있는 사람들이 모여, 서로의 의견을 공유하고 발전 시켜 나간다. 실패하더라도 그 누구도 비난하거나 우습게 보지 않는다. 좋은 시도였으며 어떻게 하면 더 발전해나갈 수 있을지에 대해 고민을 하게 한다. 평소와는 다른 방법, 자신만의 생각과 표현들이 자유롭게 오가고 서로가 서로에게 새로운 인사이트를 제시한다.
워니가 한 말이 생각나서... 
`서로의 의견을 공유하고 발전 시켜 나간다.` 라는 사동형 문장보단
`서로의 의견을 공유하며 발전한다`식의 능동형 문장을 사용해보면 어떨까요...!

2021-03-16 15:33 UTC, thisisyoungbin commented on README.md
> +그럼 답은 간단하다. 최대한 실패를 많이 해도 되는 시기에, 수많은 실패를 해버리고 성장해야 나중에 실패할 확률이 낮아지는 것이다.
실패를 두려워 하지 않는 모습... 멋있네요 도비 👍

2021-03-16 15:41 UTC, zereight commented on README.md
> +그럼 답은 간단하다. 최대한 실패를 많이 해도 되는 시기에, 수많은 실패를 해버리고 성장해야 나중에 실패할 확률이 낮아지는 것이다.
윽 .. 둘다 맘에 들어서 엄청난 고민을 했어요.
`수많은 실패를 해버리고 성장해야`, `수많은 실패를 하고 성장해야`
를 수십번 반복해서 읽어보니, 갑자기 `~고 성장해야` 이 부분이 어색하게 느껴지는 기이한 현상을 경험했어요. <del>피곤해서 그런가..</del>

그래서 저는 `수많은 실패를 통해 성장해야`로  [수정](https://github.com/woowacourse/woowa-writing-3/pull/11/commits/144e6abcb6f587b0456274204cba024e2e6670d0)해봤어요. 괜찮은가요?!

2021-03-16 15:49 UTC, zereight commented on README.md
> +도대체 왜 ‘실패는 성공의 어머니’라는 진실을 수십 번을 듣고 머리로는 알고 있는데, 왜 사람들은 모순적으로 실패를 기피하는 대상으로 보는 것일까?
욘 안녕하세요~~ 저도 실제로 못뵙게되서 아쉽네요 ㅜㅜ

> 왜 라는 의문표현이 두 번 나와서 

오오 중복을 잡아주셨군요! 욘은 코드도 중복없이 잘 짜실것같아요!!  꼼꼼한 리뷰 감사합니다 >_<

2021-03-16 15:53 UTC, zereight commented on README.md
> +그렇다면 실패를 장려하고 격려해주는 동료가 있고, 이끌어주는 의지할만한 멘토가 있는 환경이 생긴다면 어떨까?
와 정말 그러네요?!
이런 피드백 너어무 좋습니닷 고마워요!
(수정)[https://github.com/woowacourse/woowa-writing-3/pull/11/commits/e43288b116eee2c0611233858d0b044095908ea8]했어요~!!

2021-03-16 16:01 UTC, zereight commented on README.md
> +우테코는 나에게 그런 곳이었다. 학습에 열정이 있는 사람들이 모여, 서로의 의견을 공유하고 발전 시켜 나간다. 실패하더라도 그 누구도 비난하거나 우습게 보지 않는다. 좋은 시도였으며 어떻게 하면 더 발전해나갈 수 있을지에 대해 고민을 하게 한다. 평소와는 다른 방법, 자신만의 생각과 표현들이 자유롭게 오가고 서로가 서로에게 새로운 인사이트를 제시한다.
앗.. 그러네요!
욘의 좋은 피드백에 살을 붙여서 [수정](https://github.com/woowacourse/woowa-writing-3/pull/11/commits/05bf3d6676dbd323426cfecda894bac920558315)해보았어요!
어떠신가요? >_<

2021-03-16 16:05 UTC, zereight commented on README.md
> +그럼 답은 간단하다. 최대한 실패를 많이 해도 되는 시기에, 수많은 실패를 해버리고 성장해야 나중에 실패할 확률이 낮아지는 것이다.
<del>사실 무서워요</del>
+ 저는 사실 말투만봐도 어떤 사람인지 알 수 있어요.
욘도 실패를 두려워하지 않는 사람일거에요. 👍

2021-03-16 16:08 UTC, zereight commented on README.md
> +하지만 우리 사회는 가파른 성장을 해오면서 항상 빠른 성공을 기대해왔다. 실패보단 성공이 좋은 것이라 배웠고, 실패한 사람에게 손가락질을 해왔다. 그렇게 실패는 두렵고, 기피해야 할 대상이 되었다. 우리는 실패를 통한 유의미한 성장이 아니라 실패 없이 빠른 성공에 집착하는 이른바 ‘성공의 민족’이었던 것이다.
확실히 더 나은것 같아요 배럴! 
좋은 피드백 바로 반영했습니닷!

2021-03-16 22:44 UTC, knae11 commented on README.md
> +우테코 곳곳에 스며들어있는, 어쩌면 지식을 습득하는 공부보다 하찮게 여겨질 수 있는 그런 활동들이 있다. 하지만 그런 하찭아 보일 수 있는 행동들이 결국 나의 성장에 유의미한 거름이 되고, 함께 성장할 수 있는 조직문화를 만들었다.
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ총게임을 좋아하시는 군요!ㅋㅋㅋㅋ 생각해보지도 못했네욬ㅋㅋㅋ 제 이름이 `나은`이어서 여기서 가져온 배럴입니다!ㅋㅋㅋㅋㅋ

2021-03-16 22:44 UTC, knae11 commented on README.md
> +그럼 답은 간단하다. 최대한 실패를 많이 해도 되는 시기에, 수많은 실패를 해버리고 성장해야 나중에 실패할 확률이 낮아지는 것이다.
제 피드백보다 훨씬 자연스러운 것 같아요!👍

2021-03-16 22:45 UTC, knae11 commented on README.md
> +하지만 우리 사회는 가파른 성장을 해오면서 항상 빠른 성공을 기대해왔다. 실패보단 성공이 좋은 것이라 배웠고, 실패한 사람에게 손가락질을 해왔다. 그렇게 실패는 두렵고, 기피해야 할 대상이 되었다. 우리는 실패를 통한 유의미한 성장이 아니라 실패 없이 빠른 성공에 집착하는 이른바 ‘성공의 민족’이었던 것이다.
피드백 반영 감사합니다!😃

2021-03-16 22:45 UTC, knae11 commented on README.md
> +그야말로 ‘실패에 최적화된’ 환경이었다. 또한, 그것을 통해 함께 성장할 수 있는 환경이 마련된 곳이었다. 성장하고자 하는 의지만 있으면 성장을 할 수 있는 곳이라는 확신이 생기는 곳이었다. 한 달밖에 경험해보지 못했지만, 점차 내가 ‘성공의 민족’에서 ‘성장의 민족’으로 바뀌고 있다는 느낌을 받아서 참으로 뿌듯했다.
오~ 역시 피드백의 피드백이 최고네요! 👍

2021-03-16 22:47 UTC, knae11 commented on README.md
> +막연히 함께 공부하는 것이 좋다는 사실은 알았다. 하지만 그 효과를 체험해볼 생각은 하지 못했었다. 다행히 우테코는 나에게 그런 기회를 주었다.
이런 부분에 대해 좀 더 명확하게 작성해주시면 좋을 것 같아요!ㅎㅎㅎ 사실 지금 상태에서도 읽는데 불편하거나 하진 않아요ㅎㅎㅎ 리뷰어의 입장에서 어떻게 하면 조금이라도 더 고칠 수 있을까하는 눈으로 바라본 것이라서요!ㅎㅎㅎ 충분하다고 생각하면 반영하지 않으셔도 됩니다~ㅎㅎㅎ

2021-03-17 01:04 UTC, 365kim commented on README.md
> +개인마다 다르지만, 인생에서 실패할 수 있는 횟수는 정해져 있다고 한다.
제 실패에 함께해주세요 😆😆😆

2021-03-17 01:05 UTC, 365kim commented on README.md
> +하지만 우리 사회는 가파른 성장을 해오면서 항상 빠른 성공을 기대해왔다. 실패보단 성공이 좋은 것이라 배웠고, 실패한 사람에게 손가락질을 해왔다. 그렇게 실패는 두렵고, 기피해야 할 대상이 되었다. 우리는 실패를 통한 유의미한 성장이 아니라 실패 없이 빠른 성공에 집착하는 이른바 ‘성공의 민족’이었던 것이다.
도비에게 주어지는 합격 목걸이 🏅🏅🏅

2021-03-17 01:07 UTC, 365kim commented on README.md
> +사람은 사회적인 동물이라서, 사회적인 관념 속에 진실을 묻고 자신을 속이며 살아가고 있기 때문이 아닐까? 또한 그사이의 괴리감 때문에 불행을 느끼고 있는 것은 아닐까?
저도 잘 몰라서 찾아봤어용! 히히

2021-03-17 01:12 UTC, 365kim commented on README.md
> +우테코는 나에게 그런 곳이었다. 학습에 열정이 있는 사람들이 모여, 서로의 의견을 공유하고 발전 시켜 나간다. 실패하더라도 그 누구도 비난하거나 우습게 보지 않는다. 좋은 시도였으며 어떻게 하면 더 발전해나갈 수 있을지에 대해 고민을 하게 한다. 평소와는 다른 방법, 자신만의 생각과 표현들이 자유롭게 오가고 서로가 서로에게 새로운 인사이트를 제시한다.
흐음 +Infinity 정도 밖에 공감되지 않네요,,,

2021-03-17 01:12 UTC, 365kim commented on README.md
> +이미 우리가 걷고 있는 길을 걸어가 보았던 믿고 의지할 수 있는 코치, 선배들도 생겼다.
도비의 문장에 울림이 있는걸요~

2021-03-17 01:15 UTC, 365kim commented on README.md
> +어쩌면 지식을 습득하는 것보다 중요한 것이, 지식을 습득할 수 있는 환경을 만드는 것이 아닐까 하는 생각이 들었다. 그리고 함께하는 성장을 위해 놓치고 있는 또 다른 하찮은 행동들이 뭐가 있을지에 대해 고민하게 된 한 달이었다.
오오,,, 나중에 얘기 더 들려주세용😁

2021-03-17 01:56 UTC, 365kim approved these changes
피드백 잘 반영된 것으로 확인했습니다! 어프루브 할게용👍👍👍
그리고 돌체라떼는 금요일 아침에 배달할 거에요🤖 ☕️

2021-03-17 11:11 UTC, zereight commented on README.md
> +우테코 곳곳에 스며들어있는, 어쩌면 지식을 습득하는 공부보다 하찮게 여겨질 수 있는 그런 활동들이 있다. 하지만 그런 하찭아 보일 수 있는 행동들이 결국 나의 성장에 유의미한 거름이 되고, 함께 성장할 수 있는 조직문화를 만들었다.
아하 better 이었군요!

2021-03-17 11:20 UTC, zereight commented on README.md
> +그야말로 ‘실패에 최적화된’ 환경이었다. 또한, 그것을 통해 함께 성장할 수 있는 환경이 마련된 곳이었다. 성장하고자 하는 의지만 있으면 성장을 할 수 있는 곳이라는 확신이 생기는 곳이었다. 한 달밖에 경험해보지 못했지만, 점차 내가 ‘성공의 민족’에서 ‘성장의 민족’으로 바뀌고 있다는 느낌을 받아서 참으로 뿌듯했다.
피드백이 좋아서 그런거에요~~!

2021-03-17 11:22 UTC, zereight commented on README.md
> +막연히 함께 공부하는 것이 좋다는 사실은 알았다. 하지만 그 효과를 체험해볼 생각은 하지 못했었다. 다행히 우테코는 나에게 그런 기회를 주었다.
문장에 부연설명을 해봤어요! [수정](https://github.com/woowacourse/woowa-writing-3/pull/11/commits/88f65b8918ef339ac419822c71f2e7f1d65a5cc0)
`막연히 함께 공부하는 것이 좋다는 사실은 알았다. 하지만 그 효과를 체험해볼 생각은 하지 못했었다. 아마 기회가 있었음에도 변화가 두려웠기 때문에 외면했을지도 모른다. 다행히 우테코는 나에게 그런 기회를 주었다.`

2021-03-17 12:38 UTC, sjpark-dev requested changes
도비! 멋진 글 잘 읽었습니다. 👍
눈에 불을 켜고 피드백 드릴 부분을 찾아봤지만...
글을 잘 쓰셔서 힘들었네요... 😅
몇가지 제안을 드렸지만 꼭 고칠 필요는 없어 보입니다. 😊

2021-03-17 12:38 UTC, sjpark-dev commented on README.md
> +개인마다 다르지만, 인생에서 실패할 수 있는 횟수는 정해져 있다고 한다.
너무 멋진 문단이네요. 👍

더 간결하게 만들 수 있지 않을까요?

```suggestion
인생에서 실패할 수 있는 횟수는 사람마다 정해져 있다고 한다.
```

2021-03-17 12:38 UTC, sjpark-dev commented on README.md
> +‘실패는 성공의 어머니’라는 진실을 수십 번을 듣고 머리로는 알고 있는데, 왜 사람들은 모순적으로 실패를 기피하는 대상으로 보는 것일까?
저부터 반성하게 만드는 문장이네요. 😅

문장을 나눌 수 있지 않을까요?

```suggestion
사람들은 ‘실패는 성공의 어머니’라는 진실을 수십 번을 듣고 머리로는 알고 있다. 그런데 왜 모순적으로 실패를 기피하는 대상으로 보는 것일까?
```

2021-03-17 12:38 UTC, sjpark-dev commented on README.md
> +사실 개발 공부는 우테코를 시작하기 전까지 혼자 진행했었다. 프로그래밍 언어를 배울 때에나 프레임 워크를 접해볼 때도 유튜브와 인강이 나의 유일한 개발 친구였다.
공감되네요... 저도 그랬어요. 😂

2021-03-17 12:38 UTC, sjpark-dev commented on README.md
> +이미 우리가 걷고 있는 길을 걸어가 보았던 믿고 의지할 수 있는 코치, 선배들도 생겼다.
문장을 나눌 수 있지 않을까요?

```suggestion
의지할 수 있는 코치와 선배들도 생겼다. 그들은 우리가 걷고 있는 길을 이미 걸어 봤기에 믿을 수 있다.
```

2021-03-17 12:38 UTC, sjpark-dev commented on README.md
> +우테코 곳곳에 스며들어있는, 어쩌면 지식을 습득하는 공부보다 하찮게 여겨질 수 있는 그런 활동들이 있다. 하지만 그런 하찮아 보일 수 있는 행동들이 결국 나의 성장에 유의미한 거름이 되고, 함께 성장할 수 있는 조직문화를 만들었다.
```suggestion
우테코 곳곳에 스며들어있는, 어쩌면 지식을 습득하는 공부보다 하찮게 여겨질 수 있는 그런 활동들이 있다. 하지만 그런 하찮아 보일 수 있는 행동들이 결국 나의 성장에 유의미한 거름이 되고, 함께 성장할 수 있는 조직문화를 만든다.
```

저는 이렇게 바꾸는게 더 자연스럽게 느껴져요!

2021-03-17 12:38 UTC, sjpark-dev commented on README.md
> +어쩌면 지식을 습득하는 것보다 중요한 것이, 지식을 습득할 수 있는 환경을 만드는 것이 아닐까 하는 생각이 들었다. 그리고 함께하는 성장을 위해 놓치고 있는 또 다른 하찮은 행동들이 뭐가 있을지에 대해 고민하게 된 한 달이었다.
문장을 나눌 수 있지 않을까요?

```suggestion
어쩌면 지식을 습득하는 것보다 중요한 것이 있다. 그것은 지식을 습득할 수 있는 환경을 만드는 것이 아닐까 생각한다. 그리고 함께하는 성장을 위해 놓치고 있는 또 다른 하찮은 행동들이 뭐가 있을지에 대해 고민하게 된 한 달이었다.
```

2021-03-17 13:38 UTC, PapimonLikelion reviewed
글이 너무 좋아서 크게 내용적으로는 수정할 곳이 없어요!
최대한 빠르게 실패하여, 나중의 성공확률을 높인다는 말은 참으로 멋진 생각같아요!

다만 문체를 자주 과거형태로 쓰시는 것 같아요
이를 현재형으로 바꿔주시면 글의 느낌이 한 층 더 희망차질 것 같습니다!

좋은 글 잘 읽었습니다 도비 :)

2021-03-17 13:38 UTC, PapimonLikelion commented on README.md
> +우테코는 나에게 그런 곳이었다. 학습에 열정이 있는 사람들이 모여, 서로의 의견을 공유하고 지식과 경험을 온전히 자신의 것으로 만든다. 실패하더라도 그 누구도 비난하거나 우습게 보지 않는다. 좋은 시도였으며 어떻게 하면 더 발전해나갈 수 있을지에 대해 고민을 하게 한다. 평소와는 다른 방법, 자신만의 생각과 표현들이 자유롭게 오가고 서로가 서로에게 새로운
우테코는 나에게 그런 곳이다. 
학습에 열정이 있는 사람들이 모여, 서로의 의견을 자유롭게 공유한다. 
우리의 지식과 경험을 온전히 각자의 것으로 만든다. 
혹시나 실패하더라도, 그 누구도 비난하거나 우습게 보지 않는다. 
오히려 좋은 시도였다며 칭찬하고, 어떻게 하면 더 발전해나갈 수 있을지에 대해 고민한다. 
자신만의 생각과 표현들이 자유롭게 오가고 서로가 서로에게 새로운 인사이트를 제시한다.

문장이 조금 어색해서 조금 수정해봤어요! 
조금 문장이 명확해 질 수 있을 것 같아요!

2021-03-17 14:54 UTC, zereight commented on README.md
> +개인마다 다르지만, 인생에서 실패할 수 있는 횟수는 정해져 있다고 한다.
와~~ 에드! 더욱 간결해졌어요. 감사합니다!
[수정](https://github.com/zereight/woowa-writing-3/commit/69b69dd283692459f3f231df89d43a247b0740d5)

2021-03-17 14:57 UTC, zereight commented on README.md
> +‘실패는 성공의 어머니’라는 진실을 수십 번을 듣고 머리로는 알고 있는데, 왜 사람들은 모순적으로 실패를 기피하는 대상으로 보는 것일까?
오 살짝 어색했었는데, 에드덕붙에 좀 더 깔끔해졌어요 👍👍👍 에드의 좋은 피드백에 살좀 붙여서 
[수정](https://github.com/zereight/woowa-writing-3/commit/031fb73f30d1a4a56e6ffa74372aafbc481e2a39)했습니다 ㅎㅎ

2021-03-17 14:58 UTC, zereight commented on README.md
> +사실 개발 공부는 우테코를 시작하기 전까지 혼자 진행했었다. 프로그래밍 언어를 배울 때에나 프레임 워크를 접해볼 때도 유튜브와 인강이 나의 유일한 개발 친구였다.
저랑 개발 친구해요!

2021-03-17 15:02 UTC, zereight commented on README.md
> +이미 우리가 걷고 있는 길을 걸어가 보았던 믿고 의지할 수 있는 코치, 선배들도 생겼다.
에드! 이 문장은 앞 2문장과 `생겼다`의 라임을 꼭 맞추고 싶어요 🥺 ㅜㅜ 
이 부분은 생각해보고 더 좋게 개선할 수 있으면 개선해볼게요..! 😄

2021-03-17 15:04 UTC, zereight commented on README.md
> +우테코 곳곳에 스며들어있는, 어쩌면 지식을 습득하는 공부보다 하찮게 여겨질 수 있는 그런 활동들이 있다. 하지만 그런 하찮아 보일 수 있는 행동들이 결국 나의 성장에 유의미한 거름이 되고, 함께 성장할 수 있는 조직문화를 만들었다.
오 과거형보다 더 좋은 것 같아요 👍👍👍
[수정](https://github.com/zereight/woowa-writing-3/commit/ec300b2824d6cf5501034dfa5358852a7079bedf)

2021-03-17 15:23 UTC, zereight commented on README.md
> +어쩌면 지식을 습득하는 것보다 중요한 것이, 지식을 습득할 수 있는 환경을 만드는 것이 아닐까 하는 생각이 들었다. 그리고 함께하는 성장을 위해 놓치고 있는 또 다른 하찮은 행동들이 뭐가 있을지에 대해 고민하게 된 한 달이었다.
오 에드 말 처럼 문장을 나눌 수 있겠네요!
에드는 리팩토링 엄청 잘하실것 같아요!! [수정](https://github.com/zereight/woowa-writing-3/commit/8f7760e33d628a46cd1cef20250ad057f283a227) 했습니다 ㅎㅎ.
그리고 뒤 문장도 앞 문장과 이어지게 바꿔봤어요!

2021-03-17 15:27 UTC, zereight commented on README.md
> +우테코는 나에게 그런 곳이었다. 학습에 열정이 있는 사람들이 모여, 서로의 의견을 공유하고 지식과 경험을 온전히 자신의 것으로 만든다. 실패하더라도 그 누구도 비난하거나 우습게 보지 않는다. 좋은 시도였으며 어떻게 하면 더 발전해나갈 수 있을지에 대해 고민을 하게 한다. 평소와는 다른 방법, 자신만의 생각과 표현들이 자유롭게 오가고 서로가 서로에게 새로운
조엘 안녕하세요~!!! 

> 문장이 조금 어색해서 조금 수정해봤어요!
조금 문장이 명확해 질 수 있을 것 같아요!

오, 과거형 문장들이 대량으로 현재형으로 바뀌었어요!
조엘에게 과거형 문장 컴파일러 자격증을 수여합니다! 감사합니다~!!
[수정](https://github.com/zereight/woowa-writing-3/commit/7f6236a678a089e9c7fb35ab68c0c3d5594a5937)했어요! ㅎㅎ

2021-03-18 02:09 UTC, sjpark-dev commented on README.md
> +이미 우리가 걷고 있는 길을 걸어가 보았던 믿고 의지할 수 있는 코치, 선배들도 생겼다.
제가 라임을 못봤네요. 🙄
제가 말씀 드린 것들은 초보자의 제안일 뿐이니 한귀로 듣고 한귀로 흘리셔도 좋습니다. 😉
도비의 글은 지금도 충분히 멋집니다. 👍

2021-03-18 14:05 UTC, sjpark-dev requested changes
도비! 한가지 검토힐게 있어요!
제 피드백을 반영하면서 그 여파로 생긴 어색한 문장이 있네요 😅

2021-03-18 14:05 UTC, sjpark-dev commented on README.md
> +우테코는 나에게 그런 곳이다. 학습에 열정이 있는 사람들이 모여, 서로의 의견을 자유롭게 공유한다. 우리의 지식과 경험을 온전히 각자의 것으로 만든다. 혹시나 실패하더라도, 그 누구도 비난하거나 우습게 보지 않는다.오히려 좋은 시도였다며 칭찬하고, 어떻게 하면 더 발전해나갈 수 있을지에 대해 고민한다. 자신만의 생각과 표현들이 자유롭게 오가고 서로가 서로
띄어쓰기 깜빡하셨네요 😅

```suggestion
우테코는 나에게 그런 곳이다. 학습에 열정이 있는 사람들이 모여, 서로의 의견을 자유롭게 공유한다. 우리의 지식과 경험을 온전히 각자의 것으로 만든다. 혹시나 실패하더라도, 그 누구도 비난하거나 우습게 보지 않는다. 오히려 좋은 시도였다며 칭찬하고, 어떻게 하면 더 발전해나갈 수 있을지에 대해 고민한다. 자신만의 생각과 표현들이 자유롭게 오가고 서로가 서로에게 새로운 인사이트를 제시한다.
```

2021-03-18 14:05 UTC, sjpark-dev commented on README.md
> +이렇게 지난 한 달은 함께하는 성장을 위해 놓치고 있는 또 다른 하찮은 행동들이 뭐가 있을지에 대해 고민을 시작하게 된 시발점이었다.
이 문장이 너무 많은 정보를 가지고 있어서 의미가 불분명하네요 🤔

2021-03-18 14:06 UTC, sjpark-dev commented on README.md
> +이렇게 지난 한 달은 함께하는 성장을 위해 놓치고 있는 또 다른 하찮은 행동들이 뭐가 있을지에 대해 고민을 시작하게 된 시발점이었다.
34의 문장입니다!

2021-03-19 14:35 UTC, zereight commented on README.md
> +우테코는 나에게 그런 곳이다. 학습에 열정이 있는 사람들이 모여, 서로의 의견을 자유롭게 공유한다. 우리의 지식과 경험을 온전히 각자의 것으로 만든다. 혹시나 실패하더라도, 그 누구도 비난하거나 우습게 보지 않는다.오히려 좋은 시도였다며 칭찬하고, 어떻게 하면 더 발전해나갈 수 있을지에 대해 고민한다. 자신만의 생각과 표현들이 자유롭게 오가고 서로가 서로
앗 ㅋㅋㅋㅋ 이걸 찾아내시다니!
[수정](https://github.com/woowacourse/woowa-writing-3/pull/11/commits/bbc4fec26f3cf449741a29901d8cb99768a713ad)했어요 감사합니다 🙏

2021-03-19 15:30 UTC, zereight commented on README.md
> +이렇게 지난 한 달은 함께하는 성장을 위해 놓치고 있는 또 다른 하찮은 행동들이 뭐가 있을지에 대해 고민을 시작하게 된 시발점이었다.
[수정](https://github.com/woowacourse/woowa-writing-3/pull/11/commits/a144eee9100a9ee42bea3246b45e66560fb3844d) 해봤어요!
이상한점이 있다면 피드백 부탁드려요 🙏

2021-03-20 08:19 UTC, PapimonLikelion approved these changes
제가 드릴 수 있는 피드백은 모두 드린 것 같아서 Approve 하겠습니다!
좋은 글 감사합니다 도비!
레벨 1 마무리 잘하시고 코로나 조심하세요 :) 💪

2021-03-20 12:02 UTC, sjpark-dev commented on README.md
> +이번 한 달을 통해서, 함께할 수 있는 성장에 도움을 줄 수 있는 하찮은 행동들이 뭐가 있을지 고민해보는 계기가 되었다.
문장이 저번보다 더 좋아졌어요. 👍 
그런데 더 명확하게 표현할 수 있을 것 같아요. 😊
'있는'이 두번 들어 있는게 마음에 걸리네요. 😅
그리고 무엇이 계기가 되었는지 불명확한 것 같아요. 🙄

아래 예시는 참고만 해주세요!

```suggestion
이번 한 달은, 함께 성장하는데 도움을 줄 수 있는 하찮은 행동들이 뭐가 있을지 고민해보는 시간이 되었다.
```

2021-03-20 12:39 UTC, knae11 reviewed
다시 읽어보면서 수정할 곳이 있나 살펴보았어요 :) 

과거형보다 현재형으로 사용해주면 좀 더 깔끔해질 것 같다는 생각이 들었네요ㅎㅎㅎ 더불어 몇가지 의견 적어보았는데 뭔가 제가 이유를 설명하기는 어려운걸 보니 저도 사실 잘 모르겠어요ㅎㅎㅎ 다시 생각해보시고 이상한거 없는데?! 싶으면 유지해주시면 좋을 것 같네요:)

2021-03-20 12:39 UTC, knae11 commented on README.md
> +막연히 함께 공부하는 것이 좋다는 사실은 알았다. 하지만 그 효과를 체험해볼 생각은 하지 못했었다. 아마 기회가 있었음에도 변화가 두려웠기 때문에 외면했을지도 모른다. 다행히 우테코는 나에게 그런 기회를 주었다.
```suggestion
막연히 함께 공부하는 것이 좋다는 사실은 알았다. 하지만 그 효과를 체험해볼 생각은 하지 못했었다. 아마 기회가 있었음에도 변화가 두려웠기 때문에 외면했을지도 모른다. 다행히 우테코는 나에게 함께 공부할 수 있는 기회를 주었다.
```
좀 더 구체적으로 정리해주면 좋을 수도 있을 것 같아요!ㅎㅎㅎ

2021-03-20 12:39 UTC, knae11 commented on README.md
> +그럼 답은 간단하다. 최대한 실패를 많이 해도 되는 시기에, 수많은 실패를 통해 성장해야 나중에 실패할 확률이 낮아지는 것이다.
```suggestion
그럼 답은 간단하다. 최대한 실패를 많이 해도 되는 시기에, 수많은 실패를 통해 성장하면 나중에 실패할 확률을 낮출 수 있다.
```
수정해 보았는데 어떤가요? 약~~간 어색한 느낌이 들기도 하는 것 같아서요ㅠㅠ 제가 이유는 잘 모르겠는걸 보니 괜찮은 것 같기도 한데 한 번 생각해봐 주세요 ㅎㅎㅎ

2021-03-20 12:39 UTC, knae11 commented on README.md
> +하지만 우리 사회는 가파른 성장을 해오면서 항상 빠른 성공을 기대해왔다. 실패보단 성공이 좋은 것이라 배웠고, 실패한 사람에게 손가락질을 해왔다. 그렇게 실패는 두렵고, 기피해야 할 대상이 되었다. 우리는 실패를 통한 유의미한 성장을 하는 것이 아니라 실패 없이 빠른 성공에 집착하는 이른바 ‘성공의 민족’이었던 것이다.
```suggestion
하지만 우리 사회는 가파른 성장을 해오면서 항상 빠른 성공을 기대한다. 실패보단 성공이 좋은 것이라 배우고, 실패한 사람에게 손가락질을 한다. 그렇게 실패는 두렵고, 기피해야 할 대상이 되었다. 우리는 실패를 통한 유의미한 성장을 하는 것이 아니라 실패 없이 빠른 성공에 집착하는 이른바 ‘성공의 민족’이었다.
```
앞에 내용은 사실을 의미하는 것 같기도 해서 현재형인 게 좋을 것 같다는 생각이 들었어요. 그런데 변화를 표현하려고 일부러 성공의 민족은 과거형으로 작성하려는 것 같아서 저도 명확히 어떻게 수정하면 좋겠다고 하기 어렵네요ㅠㅠ

진짜 과거의 사실이 아니면 현재형이 좋은 것 같은 느낌이 들어서요!ㅎㅎㅎ 한 번 생각만 해봐 주세요~!ㅎㅎㅎ

2021-03-20 12:39 UTC, knae11 commented on README.md
> +그야말로 ‘실패에 최적화된’ 환경이었다. 또한, 그것을 통해 함께 성장할 수 있는 환경이 마련된 곳이었다. 성장하고자 하는 의지만 있으면 성장을 할 수 있는 곳이라는 확신이 생기는 곳이었다. 우테코 과정을 경험한지 이제 겨우 한 달이지만, 점차 내가 ‘성공의 민족’에서 ‘성장의 민족’으로 바뀌고 있다는 느낌을 받아서 참으로 뿌듯했다.
```suggestion
그야말로 ‘실패에 최적화된’ 환경이다. 또한, 그것을 통해 함께 성장할 수 있는 환경이 마련된 곳이다. 성장하고자 하는 의지만 있으면 성장을 할 수 있는 곳이라는 확신이 생기는 곳이다. 우테코 과정을 경험한지 이제 겨우 한 달이지만, 점차 내가 ‘성공의 민족’에서 ‘성장의 민족’으로 바뀌고 있다는 느낌을 받아서 참으로 뿌듯하다.
```
현재형으로 바꾸면 좋을 것 같아요 :)

2021-03-20 15:33 UTC, Rok93 commented on README.md
> +그럼 답은 간단하다. 최대한 실패를 많이 해도 되는 시기에, 수많은 실패를 해버리고 성장해야 나중에 실패할 확률이 낮아지는 것이다.
이 표현 정말 좋은 것 같아요  👍  마음껏 실패해도되는 공간 그 이름 우테코! 😎😎😎😎 
저희 많이 실패해서 앞으로는 성공의 확률을 압도적으로 늘려봐요 😁😁😁

2021-03-20 17:28 UTC, Rok93 reviewed
도비 안녕하세요 ~ 로키에요 👋🏻
진실성 있는 글이고 그런 도비와 함께 우테코생활을 하고 있다는 것이 뿌듯하게 느껴지네요 😘 
항상 저 자신을 소개할 때, 0개국어라고 표현하는데 그만큼 제가 제 나름의 피드백을 드렸지만 항상 옳은(~~틀린게 더 많을지도...~~) 피드백이 아닐 수도 있다는 점 양해부탁드려요 😅 

제 피드백은 하나의 의견일뿐이니 도비의 의도나 생각이 제 의견과 다르다면 도비의 생각대로 해주세요!!

2021-03-20 17:28 UTC, Rok93 commented on README.md
> +그럼 답은 간단하다. 최대한 실패를 많이 해도 되는 시기에, 수많은 실패를 통해 성장해야 나중에 실패할 확률이 낮아지는 것이다.
이 표현 정말 좋은 것 같아요 👍 마음껏 실패해도되는 공간 그 이름 우테코! 😎😎😎😎
저희 많이 실패해서 앞으로는 성공의 확률을 압도적으로 늘려봐요 😁😁😁

2021-03-20 17:28 UTC, Rok93 commented on README.md
> +하지만 우리 사회는 가파른 성장을 해오면서 항상 빠른 성공을 기대해왔다. 실패보단 성공이 좋은 것이라 배웠고, 실패한 사람에게 손가락질을 해왔다. 그렇게 실패는 두렵고, 기피해야 할 대상이 되었다. 우리는 실패를 통한 유의미한 성장을 하는 것이 아니라 실패 없이 빠른 성공에 집착하는 이른바 ‘성공의 민족’이었던 것이다.
이 부분은 저도 배럴의 의견과 같아요 : )    과거형이 나쁜 것은 아닌데, 과거형이 연속적으로 나오니까 약간 어색하게 느껴지더라구요! 
전 배럴이 수정한 부분에서 조금 더 의견을 덧대서 

``하지만 우리 사회는 가파르게 성장한 탓에 항상 빠른 성공을 기대한다. 실패보단 성공이 좋은 것이라 배우고, 실패한 사람에게 손가락질을 한다.``

이런 구조는 어떨까요??

2021-03-20 17:28 UTC, Rok93 commented on README.md
> +사람들은 ‘실패는 성공의 어머니’라는 진실을 수십 번을 듣고 머리로는 알고 있다. 그런데 왜 실패를 기피하는 대상으로 여기는 것일까?
``그런데 왜 실패를 기피하는 대상으로 여기는 것일까?`` 이 표현을 ``그런데 왜 실패를 기피하는 것일까?`` 라고 바꿔보는건 어떨까요?  🤔

2021-03-20 17:28 UTC, Rok93 commented on README.md
> +그렇다면 실패를 장려하고, 실패했을 때 격려해주는 동료가 있고, 이끌어주는 의지할만한 멘토가 있는 환경이 생긴다면 어떨까?
```suggestion
그렇다면 실패를 장려하고 실패했을 때 격려해주는 동료와 이끌어주고 의지할만한 멘토가 있는 환경이 생긴다면 어떨까?
```

이렇게 변경해보면 어떨까요?  🤔

2021-03-20 17:28 UTC, Rok93 commented on README.md
> +사실 개발 공부는 우테코를 시작하기 전까지 혼자 진행했었다. 프로그래밍 언어를 배울 때에나 프레임 워크를 접해볼 때도 유튜브와 인강이 나의 유일한 개발 친구였다.
한국인들이 무의식적으로 가장 많이 쓰는 말 중 하나가 ``사실`` 이라고해요! 
그리고 개인적으로 ``공부를 진행했었다`` 라는 표현은 조금 어색하게 느껴지는 것 같아요. 
도비는 어떻게 생각하시나요? 
저라면 아래와 같이 고쳐볼 것 같아요!! 

```suggestion
우테코를 시작하기 전까지는 혼자서 개발 공부를 해왔다. 프로그래밍 언어를 배울 때에나 프레임 워크를 접해볼 때도 유튜브와 인강이 나의 유일한 개발 친구였다.
```

2021-03-20 17:28 UTC, Rok93 commented on README.md
> +막연히 함께 공부하는 것이 좋다는 사실은 알았다. 하지만 그 효과를 체험해볼 생각은 하지 못했었다. 아마 기회가 있었음에도 변화가 두려웠기 때문에 외면했을지도 모른다. 다행히 우테코는 나에게 그런 기회를 주었다.
앞의 두 문장은 이어주는 것도 괜찮은 것 같아요!! 

```suggestion 
함께 공부하는 것이 좋다는 사실은 막연하게 알고 있었지만 그 방법을 활용해 볼 생각은 하지 못했었다. 아마 기회가 있었음에도 변화가 두려웠기 때문에 외면했을지도 모른다. 다행히 우테코는 나에게 그런 기회를 주었다.
```

2021-03-20 17:28 UTC, Rok93 commented on README.md
> +같은 목표를 향해 고민을 할 수 있는 동료들도 생겼다.
```suggestion
같은 목표를 가지고 함께 고민할 수 있는 동료들도 생겼다.
```

2021-03-20 17:28 UTC, Rok93 commented on README.md
> +어쩌면 지식을 습득하는 것보다 중요한 것이 있다. 그것은 지식을 습득할 수 있는 환경을 만드는 것이 아닐까 생각한다.
이 두 문장 모두 중간에 ``어쩌면`` 이라는 표현이 있는데, '어쩌면' 보다 더 좋은 표현이 없을까? 란 생각이 들었어요. 
제 머릿속으로는 잘 안떠올라서... 혹시나 저와 비슷한 의견이 있으시다면 다른 크루들(혹은 도비)도 의견을 주셨으면 해요!! 🙌 (=원기옥)

2021-03-21 06:15 UTC, zereight commented on README.md
> +이번 한 달을 통해서, 함께할 수 있는 성장에 도움을 줄 수 있는 하찮은 행동들이 뭐가 있을지 고민해보는 계기가 되었다.
주신 피드백에 살을 붙여서 [수정](https://github.com/woowacourse/woowa-writing-3/pull/11/commits/0e811bc9612880de7f71201ceeb31593c3f9b41a)해보았어요!

2021-03-21 06:18 UTC, zereight commented on README.md
> +그럼 답은 간단하다. 최대한 실패를 많이 해도 되는 시기에, 수많은 실패를 통해 성장해야 나중에 실패할 확률이 낮아지는 것이다.
오잉 더 괜찮은데요?! 배럴의 꼼꼼한 피드백 감사합니다!
[수정](https://github.com/woowacourse/woowa-writing-3/pull/11/commits/4101f0d9485453e9b0c7bea7ddd95cc4c5ba8fcd)

2021-03-21 06:19 UTC, zereight commented on README.md
> +막연히 함께 공부하는 것이 좋다는 사실은 알았다. 하지만 그 효과를 체험해볼 생각은 하지 못했었다. 아마 기회가 있었음에도 변화가 두려웠기 때문에 외면했을지도 모른다. 다행히 우테코는 나에게 그런 기회를 주었다.
[수정](https://github.com/woowacourse/woowa-writing-3/pull/11/commits/4101f0d9485453e9b0c7bea7ddd95cc4c5ba8fcd)했어요!
확실히 구체적이니까 가독성이 좋아지는군요!

2021-03-21 06:20 UTC, zereight commented on README.md
> +하지만 우리 사회는 가파른 성장을 해오면서 항상 빠른 성공을 기대해왔다. 실패보단 성공이 좋은 것이라 배웠고, 실패한 사람에게 손가락질을 해왔다. 그렇게 실패는 두렵고, 기피해야 할 대상이 되었다. 우리는 실패를 통한 유의미한 성장을 하는 것이 아니라 실패 없이 빠른 성공에 집착하는 이른바 ‘성공의 민족’이었던 것이다.
현재형이 훨씬 좋군요~!
피드백 주신 부분 반영하여 [수정](https://github.com/woowacourse/woowa-writing-3/pull/11/commits/4101f0d9485453e9b0c7bea7ddd95cc4c5ba8fcd) 했어요! ㅎㅎ

2021-03-21 06:20 UTC, zereight commented on README.md
> +그야말로 ‘실패에 최적화된’ 환경이었다. 또한, 그것을 통해 함께 성장할 수 있는 환경이 마련된 곳이었다. 성장하고자 하는 의지만 있으면 성장을 할 수 있는 곳이라는 확신이 생기는 곳이었다. 우테코 과정을 경험한지 이제 겨우 한 달이지만, 점차 내가 ‘성공의 민족’에서 ‘성장의 민족’으로 바뀌고 있다는 느낌을 받아서 참으로 뿌듯했다.
여기도 [수정](https://github.com/woowacourse/woowa-writing-3/pull/11/commits/4101f0d9485453e9b0c7bea7ddd95cc4c5ba8fcd)했습니다 ㅎㅎ

2021-03-21 06:22 UTC, zereight commented on README.md
> +그럼 답은 간단하다. 최대한 실패를 많이 해도 되는 시기에, 수많은 실패를 통해 성장해야 나중에 실패할 확률이 낮아지는 것이다.
좋아요~! 로키도 우테코에서 남은 실패많이하세요! 
11월에 있는 도전은 실패하지마시구요! (무슨뜻인지 알죠? 😉)

2021-03-21 06:25 UTC, zereight commented on README.md
> +그렇다면 실패를 장려하고, 실패했을 때 격려해주는 동료가 있고, 이끌어주는 의지할만한 멘토가 있는 환경이 생긴다면 어떨까?
로키! 이 부분은 문장이 너무 길어져서 중간중간 쉼표로 쉬게해주고 싶었어요!
이 부분은 그대로 가도 괜찮을까요? 🤗

2021-03-21 06:32 UTC, zereight commented on README.md
> +사람들은 ‘실패는 성공의 어머니’라는 진실을 수십 번을 듣고 머리로는 알고 있다. 그런데 왜 실패를 기피하는 대상으로 여기는 것일까?
아하 좀 더 간결해지는군요! [수정](https://github.com/woowacourse/woowa-writing-3/pull/11/commits/3ddbe47f288a87fe3ed95e21961a7804ce3ab24c)했어요!

2021-03-21 06:33 UTC, zereight commented on README.md
> +사실 개발 공부는 우테코를 시작하기 전까지 혼자 진행했었다. 프로그래밍 언어를 배울 때에나 프레임 워크를 접해볼 때도 유튜브와 인강이 나의 유일한 개발 친구였다.
오호 습관적으로 사용한 부분까지 찾아주시다니! 👍👍
피드백 [반영](https://github.com/woowacourse/woowa-writing-3/pull/11/commits/3ddbe47f288a87fe3ed95e21961a7804ce3ab24c)하였습니다!

2021-03-21 06:34 UTC, zereight commented on README.md
> +막연히 함께 공부하는 것이 좋다는 사실은 알았다. 하지만 그 효과를 체험해볼 생각은 하지 못했었다. 아마 기회가 있었음에도 변화가 두려웠기 때문에 외면했을지도 모른다. 다행히 우테코는 나에게 그런 기회를 주었다.
아하 짧은 문장이 여러개 이어지니까, 흐름의 템포(?)가 빨라지는군요!
저도 로키와 생각이 같아서 [수정](https://github.com/woowacourse/woowa-writing-3/pull/11/commits/3ddbe47f288a87fe3ed95e21961a7804ce3ab24c)했습니다! ㅎㅎ

2021-03-21 06:35 UTC, zereight commented on README.md
> +같은 목표를 향해 고민을 할 수 있는 동료들도 생겼다.
오 좀 더 와닿은 문장이 되었어요 👍👍
[수정](https://github.com/woowacourse/woowa-writing-3/pull/11/commits/3ddbe47f288a87fe3ed95e21961a7804ce3ab24c)

2021-03-21 06:36 UTC, zereight commented on README.md
> +어쩌면 지식을 습득하는 것보다 중요한 것이 있다. 그것은 지식을 습득할 수 있는 환경을 만드는 것이 아닐까 생각한다.
첫번째의 `어쩌면`을 삭제하고 두번째의 `어쩌면`은 `아마도`로 바꿨어요!
한번 [검토](https://github.com/woowacourse/woowa-writing-3/pull/11/commits/3ddbe47f288a87fe3ed95e21961a7804ce3ab24c) 부탁드립니닷!

2021-03-21 07:20 UTC, Rok93 commented on README.md
> +그렇다면 실패를 장려하고, 실패했을 때 격려해주는 동료가 있고, 이끌어주는 의지할만한 멘토가 있는 환경이 생긴다면 어떨까?
아하~!  도비의 의도는 이해했어요! 
제가 이 부분에 피드백을 드렸던 이유는 ``이끌어주는 의지할만한 멘토``  라는 표현이 조금 어색하게 느껴져서 그랬던 것 같아요! 두 가지의 뜻 을 모두 담고 싶은 마음은 알겠는데... 이 부분을 조금 더 자연스러운 단어? 문장? 으로 바꿀 수 있는 방법 없을까요?? 🤔

2021-03-21 07:32 UTC, zereight commented on README.md
> +그렇다면 실패를 장려하고, 실패했을 때 격려해주는 동료가 있고, 이끌어주는 의지할만한 멘토가 있는 환경이 생긴다면 어떨까?
아하 저 문장이 어색한거였군요!!
지금 읽어보니까 어색하네요!
`이끌어주고`를 제거하는 방향으로 [수정](https://github.com/woowacourse/woowa-writing-3/pull/11/commits/403dc9bcaeb30e79a954d81d5e05f1ca7dec0120)해보았어요!

2021-03-21 07:33 UTC, Rok93 commented on README.md
> +어쩌면 지식을 습득하는 것보다 중요한 것이 있다. 그것은 지식을 습득할 수 있는 환경을 만드는 것이 아닐까 생각한다.
이전 글도 나쁘지 않았지만, 개인적으로 지금 글이 더 좋다고 느껴져요!!! 
이 수정한부분 조금 더 덧붙여서!!  개인적으로 이 문장에서 ``스며들어있는`` 이 부분을 살리고 싶은데, 지금 문장은 조금 어색하게 느껴지는 것 같아요. 혹시 아래와 같이 순서를 변경해보는건 어떻게 생각하세요!??  (+ '우아한테크코스' 라고 붙여 쓰는게 정식 풀 명칭이라고 해요!!) 
바꾸고 읽어보니 ``그런`` 이라는 표현이 앞뒤로 중복적으로 발생하는 것 같아서 앞 문장에서는 빼는게 어떨까 싶어요!! 

``우아한 테크코스 곳곳에 스며들어있는, 지식 위주의 공부보다 하찮게 여겨질 수 있는 그런 활동들이 있다`` 
-->  ``우아한테크코스 곳곳에는 지식 위주의 공부보다 하찮게 여겨질 수 있는 활동들이 스며들어있다.``


이 이외에 바꾼 부분들은  제 기준에서는 👍👍👍👍

2021-03-21 10:14 UTC, sjpark-dev approved these changes
도비! 제가 드릴 수 있는 피드백은 다 드린 것 같아요!
이전 보다 더 멋진 글이 되었네요! 👍👍👍
이만 Approve 하겠습니다! ✔
피드백 반영하느라 수고하셨습니다! 😊

2021-03-21 11:21 UTC, zereight commented on README.md
> +어쩌면 지식을 습득하는 것보다 중요한 것이 있다. 그것은 지식을 습득할 수 있는 환경을 만드는 것이 아닐까 생각한다.
와우 로키 정말 꼼꼼하게 봐주셔서 감사해요!
로키가 수정한 문장은 항상 더 좋은것 같아용 ㅎㅎ
[수정](https://github.com/woowacourse/woowa-writing-3/pull/11/commits/292d6d45485f37a0f06312105e1acd19f3822a45)했습니다!

2021-03-21 11:25 UTC, Rok93 approved these changes
도비의 글에서 제가 피드백 드릴 부분은 이제 없는 것 같아요 👍 
전체적으로 매끄럽게 잘 읽혔고 도비가 어떤 말을 하고 싶은지도 잘 전달되고 있다고 생각돼요 : ) 👏👏👏
저는 이만 여기서 Approve 드립니다.

![image](https://pbs.twimg.com/media/EigIEIxUwAAiyrY.jpg)

2021-03-22 06:15 UTC, thisisyoungbin approved these changes
우테코가 어떤 곳인지, 도비의 성장과 변화의 과정을 확인할 수 있는 글이였어요!! 피드백 반영된 부분들을 쭉 읽으면서 더 이상 피드백 드릴 곳이 없어서 이만 Approve 하겠습니다 !!

남은 우테코 과정도 같이 화이팅해요!! 루터회관에서 뵐 날을 기다리며..!! 👍 😄

2021-03-22 22:54 UTC, knae11 approved these changes
Approve 하겠습니다!ㅎㅎㅎㅎ 수정사항 반영하시느라 고생 많으셨어요 👏👏👏

2021-08-02 04:22 UTC, gracefulBrown approved these changes

2021-08-02 04:24 UTC, merged