[레벨 2 글쓰기 미션] 조앤(서민정) 미션 제출합니다.
woowacourse/woowa-writing-3 pull request #115
Opened 2021-05-29 11:53 UTC by seovalue

안녕하세요~! 조앤입니다라라라라랄

[여기](https://github.com/seovalue/woowa-writing-3/blob/seovalue/level2.md) 에서 확인하실 수 있습니당 ㅎㅎㅎㅎ
감사합니다 ~! 늦게 제출해서 죄송해요 ㅠㅠㅠ

2021-05-29 17:28 UTC, lns13301 requested changes
조앤 반가워요!
피드백 남겼으니 참고해 보시고 수정이 필요한 부분은 수정해 주시면 되겠습니다.
수정 후 리뷰 재요청 해주세요.

2021-05-29 17:28 UTC, lns13301 commented on README.md
> +우아한 테크코스 글쓰기에서 작성한 글입니다. ✍🏻
안녕하세요 조앤! 리뷰를 하게된 와일더 입니다.
잘부탁드려요. 😁

2021-05-29 17:28 UTC, lns13301 commented on level2.md
> +우아한 테크코스에서 가장 많이 느낀 것은, 개발을 할 때 나만의 철학이 필요하다는 것이다. 철학이라 하니 무언가 거창하게 느껴지지만, 사실 내가 말하는 철학은 "나만의 주관" 또는 "나만의 의견"으로 해석할 수 있다.
정말 좋은 글인데 맞춤법을 조금씩 틀린곳이 존재 하네요. 😉

이곳에서 맞춤법을 한 번 정리하면 어떨까요?
[맞춤법 검사기](https://speller.cs.pusan.ac.kr/results)

2021-05-29 17:28 UTC, lns13301 commented on level2.md
> +사실 나만의 의견을 갖는 것은 매우 쉽다. 하지만 "정당한 이유를 가진" 나만의 의견을 갖는 것은 매우 어렵다. 개발에는 여러 가지 정답을 가진 질문들이 존재한다. 다르게 말하자면, 납득할 만한 이유가 있다면 네가 주장하는 그 방법을 사용해도 된다는 것이다.
저도 우아한테크코스를 진행하면서 느낀점입니다.
자신만의 타당한 이유가 있다는 것이 중요하다고 생각합니다! 😋

제가 글을 작성하는 방식은 문단의 핵심이 되는 내용을 인용구로 빼는 방식인데요, 한 번 생각해 보면 좋을 것 같아요.
전하고자 하는 내용을 강조해서 알려줄 수 있거든요! ☺️

> 정당한 이유를 가진 나만의 의견을 갖는 것은 매우 어렵다.

2021-05-29 17:28 UTC, lns13301 commented on level2.md
> +이렇게 이 글의 문을 연 이유는, 내가 이 글을 통해 말하고자 하는 것이 "효과적으로 나만의 의견을 갖는 법"이기 때문이다. 우아한 테크코스에 들어오기 전까지의 나는, 결과를 위한 공부를 중시했다. 학점만 잘 나오면 장땡이라고 여겼고 깊이 있는 배움보다는 빠르고 효율적인 학습을 추구했다. 시험 기간이 다가와야만 공부를 시작했고, 그 공부 또한 시험을 위한
조앤이 지금 블로그에 올린 글을 보면 이런 삶을 살아온 것이 상상이 안되네요! 🤯

2021-05-29 17:28 UTC, lns13301 commented on level2.md
> +> 학점은 A+인데, 받은 만큼 대답하지 못하면 네 성적에 대해 신뢰가 떨어진다.
그래도 학점을 포기할 수는 없죠! 😰

2021-05-29 17:28 UTC, lns13301 commented on level2.md
> +그리고 우아한 테크코스에 들어와 많은 크루들이 스터디를 하고, 개발과 관련된 주제에 대해서 자신들의 의견을 이야기하고, 토론하는 것을 보았다. 처음엔 의문이 들었다. '그냥 하라는 대로 하면 되지, 왜 저렇게 자기 의견을 피력하려고 할까?', '왜 굳이..'. 그리고 페어를 하면서 또 느꼈다. 사소한 것에서도 나에게 어떻게 생각하냐고 물었을 때, 내 대답
나는, 나도가 불필요하게 많이 사용되는 모습이 보이네요. 생략해도 문장이 어색하지 않다면 생략해 주시면 좋겠어요. 😌

2021-05-29 17:28 UTC, lns13301 commented on level2.md
> +그래서 얻게 된 내 방법은, **질문하기**이다. 이렇게 거창하게 글을 써놓고, 고작 질문하기라는 생각이 들 수도 있다. 하지만 질문하기는 나에게 매우 효과적이었다. 특정 논제에 대해 궁금한 점이 생겼고, 그에 대해 나만의 의견을 못 늘어놓겠다는 생각이 들면, 일단 밖으로 나선다. 일단 눈에 보이는 사람에게 다가가 이 것에 대해 어떻게 생각하는지 물어본다
글의 흐름으로 봤을 때, '내가 생각하기에도 저 사람의 의견이 정답인가?', '저 크루는 왜 이렇게 말했을까?' 따옴표로 묶어주는게 좋겠네요.

그러게 -> 그렇게 가 맞겠죠?

2021-05-29 17:28 UTC, lns13301 commented on level2.md
> +끗!
조앤 잘 읽었습니다!! 👏
글쓰기 레벨 1때는 조금 더 과감하게 리뷰를 했었는데, 돌이켜보면 각자의 색이 있는데 그걸 너무 건드렸다고 생각이 들었습니다.
그래서 이번에는 최대한 필요한 부분에 대해서만 리뷰 남기고 공감을 위주로 피드백 드렸습니다.
혹시 더 궁금한 내용이 있으시면 DM 주세요~👍

2021-05-29 19:29 UTC, SunYoungKwon approved these changes
조앤! 안녕하세요ㅎㅎ 

문장들이 잘 정돈되어 술술 잘 읽히는 글이었어요! 조앤의 고민과 결론을 내기까지의 과정이 잘 드러나서 좋았습니다. 다른 크루/코치들의 의견을 들어보며 나의 생각을 정리하는 방식도 너무 좋은 학습법이라고 생각해요! 조앤의 질문을 받은 사람들도 답변하며 자신의 생각을 정리하는 시간을 가질 수 있겠네요. 혹시 프론트에 궁금한 점이 있다면 저에게 마구 질문해주세요😁

저는 수정해야할 부분이 보이지 않아 바로 Approve하겠습니다. Level2 글쓰기 미션 수고하셨어요!

2021-05-29 19:29 UTC, SunYoungKwon commented on level2.md
> +우아한 테크코스에서 가장 많이 느낀 것은, 개발을 할 때 나만의 철학이 필요하다는 것이다. 철학이라 하니 무언가 거창하게 느껴지지만, 사실 내가 말하는 철학은 "나만의 주관" 또는 "나만의 의견"으로 해석할 수 있다.
우아한테크코스는 띄어쓰기 없이 작성한다고 알고있어요!

2021-05-29 19:29 UTC, SunYoungKwon commented on level2.md
> +이렇게 이 글의 문을 연 이유는, 내가 이 글을 통해 말하고자 하는 것이 "효과적으로 나만의 의견을 갖는 법"이기 때문이다. 우아한 테크코스에 들어오기 전까지의 나는, 결과를 위한 공부를 중시했다. 학점만 잘 나오면 장땡이라고 여겼고 깊이 있는 배움보다는 빠르고 효율적인 학습을 추구했다. 시험 기간이 다가와야만 공부를 시작했고, 그 공부 또한 시험을 위한
```suggestion
이렇게 이 글의 문을 연 이유는, 내가 이 글을 통해 말하고자 하는 것이 "효과적으로 나만의 의견을 갖는 법"이기 때문이다. 우아한 테크코스에 들어오기 전까지의 나는 결과를 위한 공부를 중시했다. 학점만 잘 나오면 장땡이라고 여겼고 깊이 있는 배움보다는 빠르고 효율적인 학습을 추구했다. 시험 기간이 다가와야만 공부를 시작했고, 그 공부 또한 시험을 위한 공부였기 때문에 "기출 위주", "과제 위주", "암기 위주"였다. 그러다보니 시험만 끝나면 내 머릿속에 남는 것이 하나도 없었다. 분명 시험 보기 전날에는 다른 친구들에게 알려줄 수 있었는데, 시험을 보고 난 이후 누군가 나에게 똑같은 것을 물어본다면 "시험 끝나서 다 까먹었어."라는 대답만 할 뿐이었다. 그러다보니, 점점 특정 주제에 대해 내 의견을 내세울 수 없었다. 의견을 내세우려면 아는 것이 있어야 하는데, 기억나는 것도 없고 아는 것도 없으니 의견을 만들기는 커녕 대답이라도 할 수 있으면 다행이었다. 하지만 그 때의 나는 기출문제의 의견만 잘 외운다면 좋은 학점을 받을 수 있었기에  "굳이 내 의견을 가질 필요가 있나?"라는 생각이 강해서 더 깊은 학습으로 나아가지 못했다.
```

문장에 꼭 필요하지 않은 부분이라고 여겨져서 몇몇 부분을 지워봤어요. 그냥 참고만 해주세요!

2021-05-30 05:48 UTC, TaewanKimmmm commented on level2.md
> +> 학점은 A+인데, 받은 만큼 대답하지 못하면 네 성적에 대해 신뢰가 떨어진다.
학점 A+..부럽네요..

2021-05-30 08:55 UTC, sihyung92 commented
조앤 하이~ 지나가던 웨지예염~
재미난 글이네용
레벨 1이었었나요 학습법에 대해 깊게 고민하고 방법을 찾아나가던 조앤과 대화하던 기억이 나네요^^
그 때의 치열한 고민의 결과로 좋은 방법을 찾아내신 것 같아 읽으면서 즐거웠습니당당당
앞으로도 많이 질문하고 대화하고 토론하면서 같이 배웁시당~~!! 
조씨 삼남매 막내 조앤 앞으로도 파이팅입니당

2021-05-30 09:04 UTC, Joyykim commented
안녕 조앤~👋 글 잘읽었어!
평소 블로그 정리하는거 보면서 "조앤은 자신만의 학습법을 잘 만들었구나"라고 생각하고 있었는데 조앤도 이런저런 고민이 많았구나!
조앤이 가끔 질문을 하러 와줄 때마다 서로 생각을 나누면서 나도 많이 성장할 수 있어서 고마웠어😆
앞으로도 자주 얘기하면서 많이 배우고 성장하자! 남은 레벨3, 4도 잘부탁해~~🙌

2021-05-30 12:37 UTC, qhals321 commented
안녕하세요 조앤~ 지나가던 나봄입니다!!
조앤은 질문 속에서 많은 것을 배워가는군요!! 너무나 좋은 방법 같아요!!
질문은 본인 뿐만이 아니라 상대방도 성장하게끔 도와주는 것 같아요!!
조앤은 정말 멋진 일을 하고 있었네요~!!
개성을 가진 개발자가 된 것 같아 왠지 부럽고 응원하게 되네요!!
우리 남은 기간도 파이팅해요!!!!!

2021-05-30 14:30 UTC, seovalue commented on level2.md
> +그래서 얻게 된 내 방법은, **질문하기**이다. 이렇게 거창하게 글을 써놓고, 고작 질문하기라는 생각이 들 수도 있다. 하지만 질문하기는 나에게 매우 효과적이었다. 특정 논제에 대해 궁금한 점이 생겼고, 그에 대해 나만의 의견을 못 늘어놓겠다는 생각이 들면, 일단 밖으로 나선다. 일단 눈에 보이는 사람에게 다가가 이 것에 대해 어떻게 생각하는지 물어본다
매의눈

2021-05-30 16:00 UTC, lns13301 approved these changes
글쓰기 하시느라 고생많으셨습니다.
저는 이만 승인할게요. 🙏

2021-05-30 17:31 UTC, pkeugine approved these changes
안녕하세요 조앤! 🙌
글의 내용도 좋고 표현 방식도 좋아서 크게 수정할 부분이 없었어요.
조앤의 '알맹이'를 찾아가는 과정을 읽는게 정말 재밌었습니다.
저는 바로 approve 드릴게요.
'내' 와 '네' 중 어떤 것이 의도된 것인지만 확인해주세요!
고생하셨습니다~~~ 👍

2021-05-30 17:31 UTC, pkeugine commented on level2.md
> +개발에는 여러 가지 정답을 가진 질문들이 존재한다. 다르게 말하자면, 납득할 만한 이유가 있다면 네가 주장하는 그 방법을 사용해도 된다는 것이다.
```suggestion
개발에는 여러 가지 정답을 가진 질문들이 존재한다. 다르게 말하자면, 납득할 만한 이유가 있다면 내가 주장하는 그 방법을 사용해도 된다는 것이다. 
```
혹시 이 '네'가 의도된 부분인가요?
'네' 또는 '내' 둘 다 가능해서 유지해도 괜찮겠네요 😁

2021-05-30 17:31 UTC, pkeugine commented on level2.md
> +이렇게 이 글의 문을 연 이유는, 내가 이 글을 통해 말하고자 하는 것이 **효과적으로 나만의 의견을 갖는 법**이기 때문이다. 우아한 테크코스에 들어오기 전까지의 나는 결과를 위한 공부를 중시했다. 학점만 잘 나오면 장땡이라고 여겼고 깊이 있는 배움보다는 빠르고 효율적인 학습을 추구했다. 시험 기간이 다가와야만 공부를 시작했고, 그 공부 또한 시험을 위
확실히 '학점을 위한 공부'와 '내가 의지를 갖고 고민하는 공부'는 그 결과가 정말 다른 것 같아요! 공감가는 부분입니다 🥲

2021-05-30 17:31 UTC, pkeugine commented on level2.md
> +그때, 처음으로 느꼈다. 사실 난 껍데기만 잘 꾸며놓고, 알맹이는 없다는 것을. 하지만 다시 학교생활로 돌아가며 그 충격은 저 먼 곳으로 사라졌다.
이젠 알맹이도 알차다는 것을 암시하는 부분인가? 😁

2021-05-30 17:31 UTC, pkeugine commented on level2.md
> +그리고 우아한테크코스에 들어와 많은 크루들이 스터디를 하고, 개발과 관련된 주제에 대해서 자신들의 의견을 이야기하고, 토론하는 것을 보았다. 처음엔 의문이 들었다. '그냥 하라는 대로 하면 되지, 왜 저렇게 자기 의견을 피력하려고 할까?', '왜 굳이..'. 그리고 페어를 하면서 또 느꼈다. 사소한 것에서도 나에게 어떻게 생각하냐고 물었을 때, 내 대답은
페어와 의견 나누다가 커밋 내용 한 줄인 걸 발견하는 것만큼 웃픈(?) 일도 없죠 🤔

2021-05-31 03:53 UTC, hchayan approved these changes
안녕하세요 조앤!
제가 리뷰 남긴줄 알았는데 안남겼다라구요ㅠㅠ
늦게 리뷰 드려 죄송합니다 ㅠㅠ

밑에서도 적었는데,
같은 프로젝트를 하고 비슷한 목적을 가지고 공부하는 크루들이 있다는것만해도
자신의 성장의 큰 도움이될수 있는 기회가 많이 있는거같아요!
앞으로도 우테코의 이런 특징을 이용해 원하는 바 이루시길 바랍니다!

글을 크게 피드백 남길게 없어서 바로 approve 드리겠습니다 ㅎㅎ

2021-05-31 03:53 UTC, hchayan commented on level2.md
> +그때, 처음으로 느꼈다. 사실 난 껍데기만 잘 꾸며놓고, 알맹이는 없다는 것을. 하지만 다시 학교생활로 돌아가며 그 충격은 저 먼 곳으로 사라졌다.
저도 학부생때 첫 면접보고 비슷한 생각을 했어서 공감되네요 ㅠㅠ

2021-05-31 03:53 UTC, hchayan commented on level2.md
> +그러면 난 그 의견을 들은 뒤 생각한다. '내가 생각하기에도 저 사람의 의견이 정답인가?' 그리고 또 다른 크루에게도 같은 논제에 관해 또 물어본다. 그렇게 몇몇 크루들에게 물어보고 나면, 서로 다른 의견이 이어질 때도 있고 오히려 모두 같은 이야기를 할 때도 있다. 그리고 지나가던 다른 크루들도 합류해 토론의 장이 열리기도 한다. 그럼 나는 이제 그 의
이런게 가능하다는 점이 우테코의 큰 장점이라고 생각해요 ㅎㅎ

2021-05-31 05:09 UTC, seovalue commented on level2.md
> +개발에는 여러 가지 정답을 가진 질문들이 존재한다. 다르게 말하자면, 납득할 만한 이유가 있다면 네가 주장하는 그 방법을 사용해도 된다는 것이다.
의도는 '네'였는데 '내'가 더 잘어울리는 것 같아서 바꿔야겠어요 ㅎㅎ

2021-05-31 05:30 UTC, xrabcde approved these changes
안녕하세요 조앤! 바다입니다 🌊
간단히 맞춤법과 어감이 어색한 부분에 대해 피드백 남겼어요
리뷰가 많이 늦어져 죄송합니다ㅠㅜ
좋은 글 써주셔서 감사합니다! 💯

2021-05-31 05:30 UTC, xrabcde commented on level2.md
> +사실 나만의 의견을 갖기는 매우 쉽다.
```suggestion
우아한테크코스에서 가장 많이 느낀 것은, 개발할 때 나만의 철학이 필요하다는 것이다. 철학이라 하니 무언가 거창하게 느껴지지만, 내가 말하는 철학은 "나만의 주관" 또는 "나만의 의견"으로 해석할 수 있다.
사실 나만의 의견을 갖기는 매우 쉽다. 
```

`사실` 이 두 번 반복되어 조금 어색하게 느껴지는데 두 번째 줄의 `사실` 만 남기고 지우는 건 어떤가요!

2021-05-31 05:30 UTC, xrabcde commented on level2.md
> +이렇게 이 글의 문을 연 이유는, 내가 이 글을 통해 말하고자 하는 것이 **효과적으로 나만의 의견을 갖는 법**이기 때문이다. 우아한 테크코스에 들어오기 전까지의 나는 결과를 위한 공부를 중시했다. 학점만 잘 나오면 장땡이라고 여겼고 깊이 있는 배움보다는 빠르고 효율적인 학습을 추구했다. 시험 기간이 다가와야만 공부를 시작했고, 그 공부 또한 시험을 위
너무 공감되는 부분이라 글이 술술 읽히네요!! 👍

```suggestion
이렇게 이 글의 문을 연 이유는, 내가 이 글을 통해 말하고자 하는 것이 **효과적으로 나만의 의견을 갖는 법**이기 때문이다. 우아한 테크코스에 들어오기 전까지의 나는 결과를 위한 공부를 중시했다. 학점만 잘 나오면 장땡이라고 여겼고 깊이 있는 배움보다는 빠르고 효율적인 학습을 추구했다. 시험 기간이 다가와야만 공부를 시작했고, 그 공부 또한 시험을 위한 공부였기 때문에 "기출 위주", "과제 위주", "암기 위주"였다. 그러다 보니 시험만 끝나면 내 머릿속에 남는 것이 하나도 없었다. 분명 시험 보기 전날에는 다른 친구들에게 알려줄 수 있었는데, 시험을 보고 난 이후 누군가가 나에게 똑같은 것을 물어본다면 "시험 끝나서 다 까먹었어."라는 대답만 할 뿐이었다. 그러다 보니, 점점 특정 주제에 대해 내 의견을 내세울 수 없었다. 의견을 내세우려면 아는 것이 있어야 하는데, 기억나는 것도 없고 아는 것도 없으니 의견을 만들기는커녕 대답이라도 할 수 있으면 다행이었다. 하지만 그때의 나는 기출문제의 의견만 잘 외운다면 좋은 학점을 받을 수 있었고 "굳이 내 의견을 가질 필요가 있나?"라는 생각이 더욱 강했기 때문에 더 깊은 학습으로 나아가지 못했다.
```

2021-05-31 05:30 UTC, xrabcde commented on level2.md
> +그러던 와중, 면접을 볼 수 있는 기회가 생겼다. 학교 연계형이었기 때문에 교수님과 먼저 면접을 보고, 교수님께서 보시기에 괜찮다면 실제 회사 면접까지 이어지는 구조였다. 면접 보기 전, 부랴부랴 면접 기출문제를 찾아봤다. 네트워크 관련 직종이었기 때문에 깃허브에 검색하면 나오는 운영체제 면접 기출, 컴퓨터 네트워크 면접 기출 등을 전날 달달 외웠다. 그
```suggestion
그러던 와중, 면접을 볼 수 있는 기회가 생겼다. 학교 연계형이었기 때문에 교수님과 먼저 면접을 보고, 교수님께서 보시기에 괜찮다면 실제 회사 면접까지 이어지는 구조였다. 면접 보기 전, 부랴부랴 면접 기출문제를 찾아봤다. 네트워크 관련 직종이었기 때문에 깃허브에 검색하면 나오는 운영체제 면접 기출, 컴퓨터 네트워크 면접 기출 등을 전날 달달 외웠다. 그리고 면접을 보았는데, 역시나 운영체제와 컴퓨터 네트워크와 관련된 질문이 나왔다. 내가 분명히 외웠던 것이기에 대답할 수 있으리라 생각했는데, 그 키워드를 내가 봤다는 사실만 기억나고, 그게 무엇인지는 기억나지 않았다. 심지어 수업 시간에 배운 내용이라는 것까지 기억났지만 정작 답변은 전혀 할 수 없었다. 대부분의 질문을 얼버무린 채 면접이 마무리되었다. 교수님께서 내게 말씀하셨다. 
```

2021-05-31 05:30 UTC, xrabcde commented on level2.md
> +이렇게 거창하게 글을 써놓고, 고작 질문하기라는 생각이 들 수도 있다. 하지만 질문하기는 나에게 매우 효과적이었다. 특정 논제에 대해 궁금한 점이 생기고, 그에 대해 나만의 의견을 못 늘어놓겠다는 생각이 들면 먼저 밖으로 나선다. 루터회관을 순회하며 눈에 보이는 크루나 코치에게 다가가 이에 대해 어떻게 생각하는지 질문한다. 매우 고맙게도 뛰어난 크루/코치
바뀐 학습방법이 저와 비슷한 것 같네요! 
루터는 정말 질문하기 좋은 환경이죠 🤗

2021-05-31 05:30 UTC, xrabcde commented on level2.md
> +그렇게 정립된 것들은 내 생각이 되고, 내 의견이 된다. 그리고 그 과정에서 나는 학습한다.
조앤이 레벨 2를 통해 배우게 된 학습 방법을 딱! 한 줄로 요약해주는 문장인 것 같네요 💯💯

2021-05-31 05:58 UTC, seovalue commented on level2.md
> +그러던 와중, 면접을 볼 수 있는 기회가 생겼다. 학교 연계형이었기 때문에 교수님과 먼저 면접을 보고, 교수님께서 보시기에 괜찮다면 실제 회사 면접까지 이어지는 구조였다. 면접 보기 전, 부랴부랴 면접 기출문제를 찾아봤다. 네트워크 관련 직종이었기 때문에 깃허브에 검색하면 나오는 운영체제 면접 기출, 컴퓨터 네트워크 면접 기출 등을 전날 달달 외웠다. 그
wowowowow

2021-05-31 06:26 UTC, seovalue commented on level2.md
> +그렇게 정립된 것들은 내 생각이 되고, 내 의견이 된다. 그리고 그 과정에서 나는 학습한다.
딱딱!

2021-05-31 06:27 UTC, seovalue commented on level2.md
> +이렇게 거창하게 글을 써놓고, 고작 질문하기라는 생각이 들 수도 있다. 하지만 질문하기는 나에게 매우 효과적이었다. 특정 논제에 대해 궁금한 점이 생기고, 그에 대해 나만의 의견을 못 늘어놓겠다는 생각이 들면 먼저 밖으로 나선다. 루터회관을 순회하며 눈에 보이는 크루나 코치에게 다가가 이에 대해 어떻게 생각하는지 질문한다. 매우 고맙게도 뛰어난 크루/코치
이제 바다도 제 목표물입니다.. 그렇게 똑똑하고 밝으시담서요? ㅎㅎ 기대합니다

2021-05-31 08:33 UTC, jum0 approved these changes
조앤 늦게 리뷰 남겨서 죄송합니당ㅠ 조앤의 글 잘 읽었습니다! 나만의 의견을 만드는 것 자체가 학습으로써 정말 좋은 것 같아요! 조앤과는 글쓰기 미션에서 만났지만, 다음에는 직접 볼 수 있었으면 좋겠어요! 따로 수정할 부분이 없을 것 같아서 바로 approve 드릴게요

2021-05-31 08:33 UTC, jum0 commented on level2.md
> +이렇게 이 글의 문을 연 이유는, 내가 이 글을 통해 말하고자 하는 것이 **효과적으로 나만의 의견을 갖는 법**이기 때문이다. 우아한 테크코스에 들어오기 전까지의 나는 결과를 위한 공부를 중시했다. 학점만 잘 나오면 장땡이라고 여겼고 깊이 있는 배움보다는 빠르고 효율적인 학습을 추구했다. 시험 기간이 다가와야만 공부를 시작했고, 그 공부 또한 시험을 위
'나만의 의견 갖기'라는 부분 공감합니다! 전 이 부분이 약해서..ㅠ

2021-05-31 09:12 UTC, seovalue commented on level2.md
> +사실 나만의 의견을 갖기는 매우 쉽다.
반영했습니당 ㅎㅎ!

2021-05-31 09:12 UTC, seovalue commented on level2.md
> +이렇게 이 글의 문을 연 이유는, 내가 이 글을 통해 말하고자 하는 것이 **효과적으로 나만의 의견을 갖는 법**이기 때문이다. 우아한 테크코스에 들어오기 전까지의 나는 결과를 위한 공부를 중시했다. 학점만 잘 나오면 장땡이라고 여겼고 깊이 있는 배움보다는 빠르고 효율적인 학습을 추구했다. 시험 기간이 다가와야만 공부를 시작했고, 그 공부 또한 시험을 위
반영완료! 문맥 흐름 찾기 대장이네요 바다.. 최고입니다

2021-06-01 06:03 UTC, kang-hyungu approved these changes
조앤 글 잘 쓰셨어요 👍 
pr은 머지 처리할게요 수고하셨어요~!

2021-06-01 06:04 UTC, merged