[레벨 2 글쓰기 미션] 완태(김태완) 미션 제출합니다.
woowacourse/woowa-writing-3 pull request #153
Opened 2021-05-30 20:05 UTC by wannte

늦었네요.! 잘부탁드려요!
[여기](https://github.com/wannte/woowa-writing-3/blob/level2/%EC%9A%B0%EC%95%84%ED%95%9C%ED%85%8C%ED%81%AC%EC%BD%94%EC%8A%A4%EC%97%90%EC%84%9C_%EC%B0%BE%EC%9D%80_%EB%82%98%EB%A7%8C%EC%9D%98_%ED%9A%A8%EA%B3%BC%EC%A0%81%EC%9D%B8_%EA%B3%B5%EB%B6%80%EB%B2%95.md) << gogo

리뷰어 : @루트/@중간곰/@현구막/@검프/@포모/@춘식

2021-05-30 22:12 UTC, Junroot requested changes
안녕하세요 완태! 글 잘 읽었습니다!
전체적으로 문장이 깔끔해서 읽기 편했습니다!
다만, 글에 나와있는 발견한 나의 공부 성향이 공부법이 어떻게 연결이 되었는지 설명을 해주시면 좋을 것 같습니다! 이 부분만 고치면 바로 Approve 해드리겠습니다!

2021-05-31 03:44 UTC, Hyeon9mak reviewed
안녕하세요 완태!! 
완태의 공부법은 이미 완성되어있지만, 집중력에 관련해서 고민이 많으신거같아요!
저도 완태처럼 환경에 영향을 많이 받아서 최대한 밖으로 나가려 합니다 😭 👍 

글을 읽으면서 'HOW? WHY?' 가 많이 떠올랐어요!
그런 부분들에 대해서 제 취향대로 피드백 남겨보았습니다!!

2021-05-31 03:44 UTC, Hyeon9mak commented on 우아한테크코스에서_찾은_나만의_효과적인_공부법.md
> +벌써 우테코를 시작한 지 4개월이 지났다. 나만의 공부법을 찾아 자신 있게 적고 싶지만, 아직 찾지 못했다. 대신에, 우테코 기간 동안 도전했지만 실패했던 공부법, 그리고 발견한 공부 성향에 대해서 적어보고자 한다.
- `벌써` 라는 시간적 표현이 `4개월`과 함께 나오면 더 자연스러울거 같아요!
- `나만의 공부법을 자신있게 적고 싶지만, 아쉽게도 아직 찾지 못했다.` 식으로 완태의 감정을 조금 녹여보는건 어떨까요?
- `대신에`를 `대신`으로 바꿔도 자연스럽게 연결될거 같아요!
- `실패했던 공부법`, `공부 성향`의 순서를 바꾸면 아래 이어나오는 공부 성향이 자연스럽게 연결될거 같아요!

2021-05-31 03:44 UTC, Hyeon9mak commented on 우아한테크코스에서_찾은_나만의_효과적인_공부법.md
> +고등학교 때에도 많이 느꼈지만, 우테코 생활을 하면서 확실하게 깨달은 것은 나는 "벼락치기형 인간"이다. 안 하면 삶이 끝날 것 같은 선까지 가서야 엄청난 긴장감 속에 최고의 효율을 내며 일을 마무리한다. 미션을 진행함에도 마지막에 가서야 높은 집중력을 발휘해 마무리한 경우가 태반이다. 이러한 성향의 단점은 일을 미룬다는 것이, 스트레스로부터 자유로워지는
- `안 하면 삶이 끝날 것 같은 선까지 가서야` 자극적인 표현 😆 👍 👍 👍 
시간을 표현하는 단어도 살짝 포함해보면 어떨까요? `당장 안 하면`
- 단점에 대한 표현이 아쉬운거 같아요. 당장 완태의 이야기를 보면 '스트레스 조금 받고 효율 낼만한데?' 라는 생각이 들어요. 🤔 
  어떤 스트레스나 압박을 받았는지, 어떻게 건강이 나빠지는 경험을 했는지 살짝 녹여주시면 설득 될거 같아요!

2021-05-31 03:44 UTC, Hyeon9mak commented on 우아한테크코스에서_찾은_나만의_효과적인_공부법.md
> +다른 크루들이 멋지게 해내고 있는 공부 방법을 한 달간 해보자 도전을 했지만, 일주일도 지속하지 못했다. 매일 글을 작성한다는 것이 대부분 책이나 다른 블로그의 글을 옮겨 적고 있는 나 자신을 발견했다. 나중에 공부하여 기록했던 부분을 다시 찾을 때도, 내 기록보다 구글링할 것이라는 생각이 들었다. Spring 공식 문서 중 일부를 번역하는 것이 더 의미
왜 실패했는지, 왜 지속 가능하기 힘들었는지 궁금해요! 실패라고 생각하신 기준은 무엇인가요?!

2021-05-31 03:44 UTC, Hyeon9mak commented on 우아한테크코스에서_찾은_나만의_효과적인_공부법.md
> +모션 데스크와 34인치 모니터로 완전히 무장한 재택환경이지만, 나의 공부 효율은 최악이다. 물론 기한이 다다랐을 때는 열심히 하지만, 그 외의 경우 그렇지 못했다. 혼자보다는 여럿이서 함께하며, 발생한 문제들을 고민하며 흥미가 가는 주제를 찾을 수 있었다.
구체적으로 어떻게 최악일까요?!

2021-05-31 03:44 UTC, Hyeon9mak commented on 우아한테크코스에서_찾은_나만의_효과적인_공부법.md
> +하나에 꽂히면, 그거에 대해서 깊게 파고드는 때가 종종 있다. 꽂힐 만한 주제를 찾기 위해서 더 많은 문제에 맞닥뜨려야 한다. 혼자서 발견 할 수 있는 문제는 제한이 있기 때문에, 더 많은 사람의 고민을 함께하며 유효 충돌을 늘려나가야 한다.
루트가 이야기하신 부분이 이쪽이 아닐까 싶어요!
이 문단이 실패했던 공부법들을 소개한 후에 등장하는게 자연스러워 보이네요!

2021-05-31 03:44 UTC, Hyeon9mak commented on 우아한테크코스에서_찾은_나만의_효과적인_공부법.md
> +전에는 벼락치기형 성향이 게으르다고 스스로 채찍질했지만, 충분히 이러한 성향의 장점을 잘 활용할 수 있으리라 생각한다. 집에서 혼자서 공부할 수 있다는 허튼 생각 말고, 떠나라 용사여
저처럼 환경의 영향을 많이 받으시는군요! 떠나십시오 완태용사! 👍 👑 ⚔️

2021-05-31 03:45 UTC, Livenow14 approved these changes
전반적으로 깔끔한 문장이나, 예시가 조금 부족한거같아요 ㅎㅎ 
완태의 경험을  조금더 보여줘도 좋을거같아요..! 

구조는 잘 잡혀있다 생각하여, 몇가지 피드백만 남기고 approve할게요 ㅎㅎ ㅎ

2021-05-31 03:45 UTC, Livenow14 commented on 우아한테크코스에서_찾은_나만의_효과적인_공부법.md
> +
```suggestion
고등학교 때에도 많이 느꼈지만, 우테코 생활을 하면서 확실하게 깨달은 것은 "벼락치기형 인간"이라는 사실이다. 안 하면 삶이 끝날 것 같은 선까지 가서야 엄청난 긴장감 속에 최고의 효율을 내며 일을 마무리한다. 미션을 진행함에도 마지막에 가서야 높은 집중력을 발휘해 마무리한 경우가 태반이다. 이러한 성향의 단점은 일을 미룬다는 것이, 스트레스로부터 자유로워지는 것은 아니다. 이러한 스트레스가 중첩되게 되다 보니 건강까지 해쳤던 경험도 있다.

```

2021-05-31 03:45 UTC, Livenow14 commented on 우아한테크코스에서_찾은_나만의_효과적인_공부법.md
> +### 실패했던 공부 방법 - 매일 기록을 하는 공부 방법(TIL)
이 부분은 조금더 예시를 들어도 좋을듯요!

2021-05-31 03:45 UTC, Livenow14 commented on 우아한테크코스에서_찾은_나만의_효과적인_공부법.md
> +
```suggestion
다른 크루들이 멋지게 해내고 있는 공부 방법을 한 달간 해보자 도전을 했지만, 일주일도 지속하지 못했다. 매일 글을 작성한다는 목표였는데, 대부분 책이나 다른 블로그의 글을 옮겨 적고 있는 나 자신을 발견했다. 나중에 공부하여 기록했던 부분을 다시 찾을 때도, 내 기록보다 구글링할 것이라는 생각이 들었다. Spring 공식 문서 중 일부를 번역하는 것이 더 의미 있다고 생각하여 몇 번 진행했지만, 이는 지속 가능하기는 힘들었다.

```

2021-05-31 03:45 UTC, Livenow14 commented on 우아한테크코스에서_찾은_나만의_효과적인_공부법.md
> +
이부분도 예시가 조금더 있으면 좋을거같아요..!

2021-05-31 05:40 UTC, RinSabbit approved these changes
반가워요 완태~~
저랑 비슷한 성향인 거 같아 공감이 많이 가는 글이었어요.
언젠가 완태만의 완벽한 공부법을 찾길 응원하겠슴다!!
가볍게 짚고 넘어갈게요!! 어프루브는 바로 할게요 😉

2021-05-31 05:40 UTC, RinSabbit commented on 우아한테크코스에서_찾은_나만의_효과적인_공부법.md
> +고등학교 때에도 많이 느꼈지만, 우테코 생활을 하면서 확실하게 깨달은 것은 나는 "벼락치기형 인간"이다. 안 하면 삶이 끝날 것 같은 선까지 가서야 엄청난 긴장감 속에 최고의 효율을 내며 일을 마무리한다. 미션을 진행함에도 마지막에 가서야 높은 집중력을 발휘해 마무리한 경우가 태반이다. 이러한 성향의 단점은 일을 미룬다는 것이, 스트레스로부터 자유로워지는
저와 같은 벼락치기형이군요 반갑습니다ㅎㅎ 
`이러한 성향의 단점은 일을 미룬다는 것이, 스트레스로부터 자유로워지는 것은 아니다. 이러한 스트레스가 중첩되게 되다 보니 건강까지 해치는 경험도 했다.`
이어지는 두 문장에서 이러한이 중첩되는데 더 좋게 다듬을 수 있지 않을까요!?

2021-05-31 05:40 UTC, RinSabbit commented on 우아한테크코스에서_찾은_나만의_효과적인_공부법.md
> +다른 크루들이 멋지게 해내고 있는 공부 방법을 한 달간 해보자 도전을 했지만, 일주일도 지속하지 못했다. 매일 글을 작성한다는 것이 대부분 책이나 다른 블로그의 글을 옮겨 적고 있는 나 자신을 발견했다. 나중에 공부하여 기록했던 부분을 다시 찾을 때도, 내 기록보다 구글링할 것이라는 생각이 들었다. Spring 공식 문서 중 일부를 번역하는 것이 더 의미
`나중에 공부하여 기록했던 부분을 다시 찾을 때도, 내 기록보다 구글링할 것이라는 생각이 들었다.`
이 문장이 조금 어색한 거 같아요! 👀

2021-05-31 05:40 UTC, RinSabbit commented on 우아한테크코스에서_찾은_나만의_효과적인_공부법.md
> +전에는 벼락치기형 성향이 게으르다고 스스로 채찍질했지만, 충분히 이러한 성향의 장점을 잘 활용할 수 있으리라 생각한다. 집에서 혼자서 공부할 수 있다는 허튼 생각 말고, 떠나라 용사여
어떤 공부방법이든 장점과 단점이 있기 마련인 거 같아요. 벼락치기도 잘 활용하면 더 멋진 공부방법이 되리라 믿습니다 😉 떠나라 용사여~~~ 🏃 🏃

2021-05-31 09:21 UTC, bosl95 reviewed
완태 재밌는 글 잘 봤습니다!!!!!!!
저의 개인적인 의견을 몇자 적어보았어요! 
보시고 괜찮은 거 같으면 수정해보셔도 괜찮을 거 같아요!!!! 👍

2021-05-31 09:21 UTC, bosl95 commented on 우아한테크코스에서_찾은_나만의_효과적인_공부법.md
> +벌써 우테코를 시작한 지 4개월이 지났다. 나만의 공부법을 찾아 자신 있게 적고 싶지만, 아직 찾지 못했다. 대신에, 우테코 기간 동안 도전했지만 실패했던 공부법, 그리고 발견한 공부 성향에 대해서 적어보고자 한다.
`,`가 2번 쓰이는데 `대신에,` 여기에서는 빼주어도 될 거 같아용!

2021-05-31 09:21 UTC, bosl95 commented on 우아한테크코스에서_찾은_나만의_효과적인_공부법.md
> +하나에 꽂히면, 그거에 대해서 깊게 파고드는 때가 종종 있다. 꽂힐 만한 주제를 찾기 위해서 더 많은 문제에 맞닥뜨려야 한다. 혼자서 발견 할 수 있는 문제는 제한이 있기 때문에, 더 많은 사람의 고민을 함께하며 유효 충돌을 늘려나가야 한다.
`더 많은 사람의 고민을 함께하며`
-> `더 많은 사람들과 함께 고민하며`

라고 쓰는 건 어때용?

2021-05-31 09:21 UTC, bosl95 commented on 우아한테크코스에서_찾은_나만의_효과적인_공부법.md
> +다른 크루들이 멋지게 해내고 있는 공부 방법을 한 달간 해보자 도전을 했지만, 일주일도 지속하지 못했다. 매일 글을 작성한다는 것이 대부분 책이나 다른 블로그의 글을 옮겨 적고 있는 나 자신을 발견했다. 나중에 공부하여 기록했던 부분을 다시 찾을 때도, 내 기록보다 구글링할 것이라는 생각이 들었다. Spring 공식 문서 중 일부를 번역하는 것이 더 의미
`매일 글을 작성한다는 것이 대부분 책이나 다른 블로그의 글을 옮겨 적고 있는 나 자신을 발견했다.`

문장이 어색하게 읽히는데, 조금 수정해도 괜찮을 거 같아용!

2021-05-31 09:21 UTC, bosl95 commented on 우아한테크코스에서_찾은_나만의_효과적인_공부법.md
> +모션 데스크와 34인치 모니터로 완전히 무장한 재택환경이지만, 나의 공부 효율은 최악이다. 물론 기한이 다다랐을 때는 열심히 하지만, 그 외의 경우 그렇지 못했다. 혼자보다는 여럿이서 함께하며, 발생한 문제들을 고민하며 흥미가 가는 주제를 찾을 수 있었다.
`혼자보다는 여럿이서 함께하며, 발생한 문제들을 고민하며 흥미가 가는 주제를 찾을 수 있었다.`

-> `혼자보다는 여럿이 함께하며, 발생한 문제를 고민하고 흥미로운 주제를 찾을 수 있었다.`

요렇게도 수정해 볼 수 있을 거 같아요 👀

2021-05-31 09:21 UTC, bosl95 commented on 우아한테크코스에서_찾은_나만의_효과적인_공부법.md
> +전에는 벼락치기형 성향이 게으르다고 스스로 채찍질했지만, 충분히 이러한 성향의 장점을 잘 활용할 수 있으리라 생각한다. 집에서 혼자서 공부할 수 있다는 허튼 생각 말고, 떠나라 용사여
떠나라 용사여 ㅋㅋㅋㅋㅋ
완태용사 화이팅입니다 ㅎㅎㅎㅎ

2021-05-31 12:15 UTC, ggyool approved these changes
완태 글 잘 읽었어요👍
저랑 비슷한 부분이 많네요!
주관적인 수정을 살짝 했으니, 와닿는 부분이 있으면 반영하시면 될 것 같아요.

2021-05-31 12:15 UTC, ggyool commented on 우아한테크코스에서_찾은_나만의_효과적인_공부법.md
> +다른 크루들이 멋지게 해내고 있는 공부 방법을 한 달간 해보자 도전을 했지만, 일주일도 지속하지 못했다. 매일 글을 작성한다는 목표였는데, 대부분 책이나 다른 블로그의 글을 옮겨 적고 있는 자신을 발견했다. 공부하여 기록했던 부분을 다시 찾을 때도, 내 기록을 보기 보다는 구글링하고 있는 자신을 발견했다. Spring 공식 문서 중 일부를 번역하는 것이
```suggestion
한 달 동안 다른 크루들이 멋지게 해내고 있는 공부 방법을 적용하는 데 도전했지만, 일주일도 지속하지 못했다. 매일 글을 작성한다는 목표였는데, 대부분 책이나 다른 블로그의 글을 옮겨 적고 있는 자신을 발견했다. 공부하며 기록했던 부분을 다시 찾을 때도, 내 기록을 보기보다는 구글링을 하고 있다는 사실을 깨달았다. Spring 공식 문서 중 일부를 번역하는 것이 더 의미 있다고 생각하여 몇 번 진행했지만, 이를 지속 가능하기는 힘들었다.
```
```해보자 도전을 했지만``` 부분이 어색해서 바꿔봤습니다.
```자신을 발견했다``` 라는 표현이 연속으로 나와서 수정했습니다.

2021-05-31 12:15 UTC, ggyool commented on 우아한테크코스에서_찾은_나만의_효과적인_공부법.md
> +모션 데스크와 34인치 모니터로 완전히 무장한 재택환경이지만, 나의 공부 효율은 그리 좋지 못하다. 집중력도 떨어지고, 유튜브나 SNS에 매몰되어 빠져나오지 못하는 경우도 종종있다. 함께 공부하게 되면, 죽는 시간은 확연히 줄어든다. 또한, 공부한 내용을 함께 토론하는 시간 또한 즐겁다. 시간이나 비용적인 측면에서 효율적인 혼자서 공부하기지만, 오히려 죽
무장했다는 표현이 재밌네요👍
부럽습니다 😳

2021-05-31 12:15 UTC, ggyool commented on 우아한테크코스에서_찾은_나만의_효과적인_공부법.md
> +모션 데스크와 34인치 모니터로 완전히 무장한 재택환경이지만, 나의 공부 효율은 그리 좋지 못하다. 집중력도 떨어지고, 유튜브나 SNS에 매몰되어 빠져나오지 못하는 경우도 종종있다. 함께 공부하게 되면, 죽는 시간은 확연히 줄어든다. 또한, 공부한 내용을 함께 토론하는 시간 또한 즐겁다. 시간이나 비용적인 측면에서 효율적인 혼자서 공부하기지만, 오히려 죽
```suggestion
모션 데스크와 34인치 모니터로 완전히 무장한 재택환경이지만, 나의 공부 효율은 그리 좋지 못하다. 집중력도 떨어지고, 유튜브나 SNS에 매몰되어 빠져나오지 못하는 경우도 종종 있다. 하지만 함께 공부하게 되면, 죽는 시간은 확연히 줄어든다. 또한, 공부한 내용을 함께 토론할 수 있어 즐겁다. 혼자서 공부하는 건 시간이나 비용적인 측면에서 효율적이지만, 오히려 죽는 시간이 더 많아지는 공부법이다.
```
개인적으로 어색함이 느껴지는 부분을 바꿔봤는데, 마음에 드는 부분만 반영하심 될 것 같습니다!

2021-05-31 12:15 UTC, ggyool commented on 우아한테크코스에서_찾은_나만의_효과적인_공부법.md
> +고등학교 때에도 많이 느꼈지만, 우테코 생활을 하면서 확실하게 깨달은 것은 "벼락치기형 인간"이라는 사실이다. 안 하면 삶이 끝날 것 같은 선까지 가서야 엄청난 긴장감 속에 최고의 효율을 내며 일을 마무리한다. 미션을 진행함에도 마지막에 가서야 높은 집중력을 발휘해 마무리한 경우가 태반이다. 이런 성향의 단점은 일을 미룬다는 것이, 스트레스로부터 자유로워
```suggestion
고등학교 때에도 많이 느꼈지만, 우테코 생활을 하면서 확실하게 깨달은 것은 "벼락치기형 인간"이라는 사실이다. 안 하면 삶이 끝날 것 같은 선까지 가서야 엄청난 긴장감 속에 최고의 효율을 내며 일을 마무리한다. 미션을 진행할 때도 마지막에 가서야 높은 집중력을 발휘해 마무리한 경우가 태반이다. 이런 성향의 단점은 일을 미루는 과정에서 스트레스로부터 자유롭지 않다는 것이다. 스트레스가 중첩되다 보니 건강까지 해쳤던 경험도 있다.
```

2021-05-31 12:15 UTC, ggyool commented on 우아한테크코스에서_찾은_나만의_효과적인_공부법.md
> +하나에 꽂히면, 그것에 대해 깊게 파고드는 때가 종종 있다. 그 한 주제로 다른 일을 미뤄두고 하루종일 시간을 쓰기도 한다. 좋은 습관이라 생각한다. 그러기 위해서는 흥미를 끌만한 주제를 찾아야하며, 더 많은 문제에 맞닥뜨려야 한다. 혼자서 발견 할 수 있는 문제는 제한이 있기 때문에, 더 많은 사람의 고민을 함께하며 유효 충돌을 늘려나가야 한다.
```suggestion
하나에 꽂히면, 그것에 대해 깊게 파고드는 때가 종종 있다. 그 한 주제로 다른 일을 미뤄두고 하루 종일 시간을 쓰기도 한다. 좋은 습관이라 생각한다. 그러기 위해서는 흥미를 끌만한 주제를 찾아야 하며, 더 많은 문제에 맞닥뜨려야 한다. 혼자서 발견할 수 있는 문제는 제한이 있기 때문에, 더 많은 사람의 고민을 함께하며 유효 충돌을 늘려나가야 한다.
```

2021-05-31 12:29 UTC, wannte commented on 우아한테크코스에서_찾은_나만의_효과적인_공부법.md
> +벌써 우테코를 시작한 지 4개월이 지났다. 나만의 공부법을 찾아 자신 있게 적고 싶지만, 아직 찾지 못했다. 대신에, 우테코 기간 동안 도전했지만 실패했던 공부법, 그리고 발견한 공부 성향에 대해서 적어보고자 한다.
뒤에껄 빼고 연결 하는게 더 좋을 것 같아요 :+1:  그렇게 반영하겠습니다.

2021-05-31 12:48 UTC, Hyeon9mak approved these changes
구체적인 사례들이 추가되어서 완태가 겪어온 공부법들이 어떻게 실패했는지,
앞으로 어떻게 하면 실패하지 않을 수 있을지 알게 되었어요! 👍 👍 👍 
문단의 순서도 이전보다 더 매끄럽게 변경된거 같네요!

제가 피드백 드렸던 부분 잘 반영해주신거같아요!
이만 머지 드리겠습니다 🙏 🤣

2021-05-31 13:13 UTC, Junroot approved these changes
안녕하세요 완태! 
솔직하게 자신의 상태를 적여주셔서 감명깊었어요. 사실 저도 Spring 공식 문서를 번역하는 작업을 하고 있는데 생각보다 힘든 점이 많네요 😅  영어가 발목을 잡기도하고, 공식 문서는 이미 많은 개념을 이해한 사람 입장에서 작성되어서 이해하기가 굉장히 힘들었어요. 그리고 꽂히면 하루종일 파고드는게 저랑 비슷한거같아서 반가웠어요!! ㅎㅎ 
제가 요구한 피드백 반영해주셨네요! Approve하도록 하겠습니다!

2021-05-31 13:56 UTC, bosl95 approved these changes

2021-06-02 11:40 UTC, sihyung92 commented
완태 하위~ 지나가던 웨지예욤
요즘 모각코에서 보기 힘들다가 오늘 집을 떠난 용사룰 봐서 반가웠습니당^^
글을 과제에서 끝내지 않고 실행으로 옮긴 완태 간지남이시네요
앞으로도 멋있는 완태의 행보 기대하겠습니다

2021-08-02 04:20 UTC, gracefulBrown approved these changes

2021-08-02 04:20 UTC, merged