[레벨 3 글쓰기 미션] 김김(김기문) 미션 제출합니다.
woowacourse/woowa-writing-3 pull request #174
Opened 2021-08-01 16:25 UTC by tributetothemoon

안녕하세요 김김입니다~

[이 곳에서 편히 보실 수 있습니다.](https://github.com/tributetothemoon/woowa-writing-3/blob/level3essay/Level3Essay.md)

다들 정신없으실텐데 남은 레벨 3 기간도 파이팅입니다:) !

2021-08-01 23:27 UTC, Hyeon9mak commented on Level3Essay.md
> +> 아뇨... 개발자는 사람을 대하는 직업이 맞아요... 인간관계가 너무나도 중요한 사회적 직업입니다.
👍

2021-08-03 15:45 UTC, 365kim commented on Level3Essay.md
> +드디어 우테코에 들어와 첫 프로젝트를 시작했습니다. 그리고 종종 도전적인 상황들을 종종 마주하고 다시 시험에 들었습니다. 하지만 이를 해결하고 오히려 프로젝트엔 시련들이 좀 있어줘야 한다는 생각까지 들은 걸 보면, 우테코 프로젝트로부터 개발자로서의 길에 대한 확신을 다시 한번 얻은 것 같습니다.
그리고 `종종` 도전적인 상황들을 `종종` 마주하고 다시 시험에 들었습니다.
종종이 두 번 들어간 건 역시 `김김`이 `김김`이어서 일까요 😆

2021-08-03 15:50 UTC, 365kim commented on Level3Essay.md
> +하지만 이런 때야말로, 개발자로서 갖추어야 할 소양에 대한 시험에 드는 것 같습니다. 이 난해한 과정을 풀어나갈 수 있는 응용력이 있는지, 이를 뒷받침해줄 수 있는 체계적인 지식이 갖추어져 있는지, 그리고 이 과정들을 이겨낼 수 있는 인내심이 있는지를 말입니다.
이 난해한 과정을 풀어나갈 수 있는 '응용력'이 있는지, 이를 뒷받침해줄 수 있는 '체계적인 지식'이 갖추어져 있는지, 그리고 이 과정들을 이겨낼 수 있는 '인내심'이 있는지를 말입니다.

요렇게 강조 표시를 추가해주는 것은 어떨까요? 이 문장을 한 번 읽고나서 세 개가 뭐였지~? 하고 다시 돌아가서 읽게 되더라고요. 그래서 강조 표시가 있으면 따라 읽기가 더 좋을 것 같아서 가볍게 제안 드려봅니다.

2021-08-03 15:59 UTC, 365kim commented on Level3Essay.md
> +### 개발자는 결국 프로젝트로부터 나온다.
저는 이 제목이 조금 헷갈렸어요. `나온다` 라는 표현이 `yield` 같은 의미인지 `escape from` 같은 의미인지 고민했어요. 저희가 받은 글의 주제를 생각해보면 역시 그래도 긍정적인 의미일테니 전자의 의미일거라고 미루어 짐작할 수는 있었지만 `훌륭한 개발자는 프로젝트로부터 나온다` 등과 같이 수정되면 더 명확해지지 않을까 싶습니다. 하지만 저만 그렇게 읽었을 수도 있으니 가벼운 제안으로 봐주시면 감사하겠습니다. 🙏

2021-08-03 16:01 UTC, 365kim commented on Level3Essay.md
> +하지만 개발자는 누군가 만들어놓은 참고 자료를 읽고, 시험 문제마냥 누군가 의도해서 만들어놓은 문제만을 해결하는 것으로는 부족합니다. 조금만 진중하게 진행되는 단체 프로젝트에 들어가는 순간, 개인 공부를 할 때와는 다른 양상의 문제가 터져 나오기 때문이죠. 그곳엔 개인 공부를 할 때 보던 강의나 책에서의 아주 깔.끔.한 문제 상황 같은 건 나오지 않습니다
`아주 깔.끔.한 문제 상황 같은 건 나오지 않습니다.`
너무 공감되서 웃음이 나왔습니당 ㅋㅋㅋㅋ 김김의 말하는 듯한 문체 덕분에 글이 술술 잘읽히네용 👍

2021-08-03 16:08 UTC, 365kim requested changes
김김 안녕하세요!

처음 인사드리는 것 같네요 :)
저번 데모데이 발표도 잘 들었고 찜꽁 단체티도 잘봤씁니당 👍 
`맞아, 개발자는 이런 거였지`라는 큰 제목 아래 전체적으로 일관성 있게 전개해 주시고, 김김 특유의 개성있는 문체까지 더해져서 편하고 재미있게 잘 읽었어요. 감사합니다.

가벼운 수정 제안 몇 가지 코멘트 남겼는데 확인해주시면 어프루브 하겠습니다.
고생하셨어요. 👏👏👏👏👏

2021-08-03 16:40 UTC, yujo11 approved these changes
불과 며칠 전에 김김과 함께 발표 준비를 해서 그런지 글을 읽는 내내 김김의 발표를 듣는 것 같은 기분이었어요!

구어체가 많이 들어가 있어서 김김과 대화를 나누는 기분도 들었네요! 

저는 글에서 수정하고 싶은 부분을 찾지 못 해서 Approve 드리겠습니다!

글의 말미에 김김이 스스로에게 던진 질문은 저도 스스로에게 질문하게 되네요.

> 그토록 즐거운 개발만이 개발자의 전부가 아닌데, 그래도 개발자로서 살아갈 것인가?

좋은 인사이트 감사합니다 김김! 글 잘 읽었어요!! 👍👍👍

2021-08-03 16:40 UTC, yujo11 commented on Level3Essay.md
> +개발자로 살아가고자 한다면 꼭 한 번쯤 해보아야 하는 질문이라고 생각합니다. 이에 대해 그래도 yes라고 이야기하는 저를 보며, 프로젝트가 저에게 또 하나의 확신을 남겼다는 생각이 들었습니다.
크... 👍👍👍👍

2021-08-03 16:40 UTC, yujo11 commented on Level3Essay.md
> +하지만 개발자는 누군가 만들어놓은 참고 자료를 읽고, 시험 문제마냥 누군가 의도해서 만들어놓은 문제만을 해결하는 것으로는 부족합니다. 조금만 진중하게 진행되는 단체 프로젝트에 들어가는 순간, 개인 공부를 할 때와는 다른 양상의 문제가 터져 나오기 때문이죠. 그곳엔 개인 공부를 할 때 보던 강의나 책에서의 아주 깔.끔.한 문제 상황 같은 건 나오지 않습니다
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ ㅋㅋㅋㅋㅋㅋㅋ

2021-08-03 16:40 UTC, yujo11 commented on Level3Essay.md
> +> 그토록 즐거운 개발만이 개발자의 전부가 아닌데, 그래도 개발자로서 살아갈 것인가?
저도  스스로한테 다시 한번 되묻게 되네요 

> 그토록 즐거운 개발만이 개발자의 전부가 아닌데, 그래도 개발자로서 살아갈 것인가?

2021-08-03 23:45 UTC, sihyung92 commented
김김 하위~~
문제을 두려워하지 않는 개발자..@_@ 프로구만~~
개발자로 살면 앞으로도 풀리지 않는 수수께끼에 머리 싸맬 일이 많겠지만~~~
어려운 건 서로 물어가며 해결해봅시다ㅎ_ㅎ

2021-08-04 05:35 UTC, hsik0225 approved these changes
안녕하세요 김김!
저도 유조처럼 글을 읽으면서 김김이 저에게 이야기를 해준다는 느낌을 받았네요.
글을 재밌게 잘 쓰시는 것 같아요 😄

간단히 저의 의견을 코멘트로 달아두었습니다.
딱히 수정할 부분이 안보여서 이만 `Approve` 할게요!

2021-08-04 05:35 UTC, hsik0225 commented on Level3Essay.md
> + 솔직히 바보 같은 질문일 정도로 모두가 "No"라는 대답을 해올 것이라 장담합니다.
본문을 시작 하기 전에 사람들의 시선을 확 잡아 끄는 이 도입부가 너무 좋은 것 같아요!

2021-08-04 05:35 UTC, hsik0225 commented on Level3Essay.md
> +물론 개인 공부도 중요합니다. 허구한 날 맨땅에 헤딩하듯 일단 부딪혀 볼 일이 많은 직업이 개발자이긴 하지만, 개인 공부를 통해 체계적이고 심도 깊은 지식이 있어라야 좋은 개발자가 될 수 있는 건 당연하죠.
> 체계적이고 심도 깊은 지식이 있어라야

`라`가 중간에 추가된 것 같아요 😄

2021-08-04 05:35 UTC, hsik0225 commented on Level3Essay.md
> +하지만 개발자는 누군가 만들어놓은 참고 자료를 읽고, 시험 문제마냥 누군가 의도해서 만들어놓은 문제만을 해결하는 것으로는 부족합니다. 조금만 진중하게 진행되는 단체 프로젝트에 들어가는 순간, 개인 공부를 할 때와는 다른 양상의 문제가 터져 나오기 때문이죠. 그곳엔 개인 공부를 할 때 보던 강의나 책에서의 아주 깔.끔.한 문제 상황 같은 건 나오지 않습니다
정말 공감되는 문단이에요 😆

2021-08-04 05:35 UTC, hsik0225 commented on Level3Essay.md
> +그리고 다시 한번 앞으로의 제 개발자로서의 삶을 재고해보았습니다. 스스로에게 이런 질문을 해보았습니다.
`그리고`를 사용하여 문장을 잇다보니 다음 문장도 왜인지 `그리고`가 나올 것 같네요.
`그리고`가 아닌 다른 접속사를 사용하거나 문장을 끊는 건 어떨까요?

2021-08-04 14:30 UTC, knae11 commented
저번 글에 이어 김김 특유의 문체가 느껴지는 글ㅋㅋㅋㅋㅋㅋ 김김 화이팅!!

2021-08-05 15:52 UTC, DWL5 approved these changes
김김 진짜 개발자 잡지에 실릴법한 에세이 문 읽는 것 같았어요
잘 읽었습니다!!!!!!
소프트 스킬에 대한 글을 이렇게 빌드업한다고!!!!!!!!!? 
 

전체적으로 문장이 긴 듯한 느낌이 있지만 이 글만이 풍기는 분위기도 있어서 언급만하고 넘어갈게요!!
approve 드리겠습니다~

2021-08-05 15:52 UTC, DWL5 commented on Level3Essay.md
> + 솔직히 바보 같은 질문일 정도로 모두가 "No"라는 대답을 해올 것이라 장담합니다.
오 도입문 진짜 좋네요... 여기 읽는데 뒷얘기가 벌써 궁금해지네

2021-08-05 15:52 UTC, DWL5 commented on Level3Essay.md
> +하지만 개발자는 누군가 만들어놓은 참고 자료를 읽고, 시험 문제마냥 누군가 의도해서 만들어놓은 문제만을 해결하는 것으로는 부족합니다. 조금만 진중하게 진행되는 단체 프로젝트에 들어가는 순간, 개인 공부를 할 때와는 다른 양상의 문제가 터져 나오기 때문이죠. 그곳엔 개인 공부를 할 때 보던 강의나 책에서의 아주 깔.끔.한 문제 상황 같은 건 나오지 않습니다
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 데모데이 전 마다 마주치는 깔끔하지 않은 상황들 ㅠㅠ 공감되네요

2021-08-05 15:52 UTC, DWL5 commented on Level3Essay.md
> +
와 리얼 소름돋았어요..; 표현력 무엇 진짜 이번에 플젝하면서 느낀 것을 하나로 표현하시네요 🥺

2021-08-07 05:05 UTC, sakjung approved these changes
김김...다른 사람들이 리뷰를 잘 써줘서 딱히 달 코멘트는 없네.
글 너무 잘읽었어. 좋은 글귀가 많네... 감명 받았달까? ㅎ
우리 앞으로도 멋지게 개발해보자. 찜꽁 화이팅~

2021-08-07 05:05 UTC, sakjung commented on Level3Essay.md
> +하지만 개발자는 누군가 만들어놓은 참고 자료를 읽고, 시험 문제마냥 누군가 의도해서 만들어놓은 문제만을 해결하는 것으로는 부족합니다. 조금만 진중하게 진행되는 단체 프로젝트에 들어가는 순간, 개인 공부를 할 때와는 다른 양상의 문제가 터져 나오기 때문이죠. 그곳엔 개인 공부를 할 때 보던 강의나 책에서의 아주 깔.끔.한 문제 상황 같은 건 나오지 않습니다
참...재미난 상황을 많이 겪었죠 우리? ㅎ..ㅎ

2021-08-07 05:05 UTC, sakjung commented on Level3Essay.md
> +드디어 우테코에 들어와 첫 프로젝트를 시작했습니다. 그리고 종종 도전적인 상황들을 종종 마주하고 다시 시험에 들었습니다. 하지만 이를 해결하고 오히려 프로젝트엔 시련들이 좀 있어줘야 한다는 생각까지 들은 걸 보면, 우테코 프로젝트로부터 개발자로서의 길에 대한 확신을 다시 한번 얻은 것 같습니다.
김김이 멋들어지게 해결한 이슈들이 떠오르는 글귀네요~
그대가 찜꽁의 인재랄까요?

2021-08-07 05:05 UTC, sakjung commented on Level3Essay.md
> +이럴 때 원활히 상황을 해결해나갈 수 있는, 소위 '소프트 스킬'이란 결국 프로젝트를 통한 협업을 해보지 않고서는 쉽사리 기를 수 없다고 생각합니다. 소프트웨어 프로젝트의 세계에서는 무조건 당차게 의견을 개진하는 것도, 무조건 성심껏 양보하는 것도 상황에 따라 답이 아닐 때가 있습니다. 그 미묘한 차이들을 알아가는 것은 결국 경험 없이는 힘든 일이죠.
공감이 아주 많이 가네요... 좋은 글이네요

2021-08-07 11:09 UTC, tributetothemoon commented on Level3Essay.md
> +드디어 우테코에 들어와 첫 프로젝트를 시작했습니다. 그리고 종종 도전적인 상황들을 종종 마주하고 다시 시험에 들었습니다. 하지만 이를 해결하고 오히려 프로젝트엔 시련들이 좀 있어줘야 한다는 생각까지 들은 걸 보면, 우테코 프로젝트로부터 개발자로서의 길에 대한 확신을 다시 한번 얻은 것 같습니다.
> 종종이 두 번 들어간 건 역시 김김이 김김이어서 일까요 😆

ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ센스 넘치는 피드백 감사합니다 :)

2021-08-07 11:36 UTC, tributetothemoon commented on Level3Essay.md
> +### 개발자는 결국 프로젝트로부터 나온다.
ㅋㅋㅋㅋㅋㅋ 바꾸기 다소 아쉽단 생각이 들긴했지만, 중의성을 의도한 건 아니었고, '훌륭한'이 들어가면 너무 교훈적인 상투적인 글의 제목 같아서, `프로젝트 없는 개발자는 없다`로 바꾸어버렸습니다! 피드백 감사해요~~

2021-08-07 11:49 UTC, tributetothemoon commented on Level3Essay.md
> +하지만 이런 때야말로, 개발자로서 갖추어야 할 소양에 대한 시험에 드는 것 같습니다. 이 난해한 과정을 풀어나갈 수 있는 응용력이 있는지, 이를 뒷받침해줄 수 있는 체계적인 지식이 갖추어져 있는지, 그리고 이 과정들을 이겨낼 수 있는 인내심이 있는지를 말입니다.
잘 기억이 안 나신다니, 추가하는 게 맞는 것 같습니다!! 감사합니다 😄

2021-08-07 11:51 UTC, tributetothemoon commented on Level3Essay.md
> +그리고 다시 한번 앞으로의 제 개발자로서의 삶을 재고해보았습니다. 스스로에게 이런 질문을 해보았습니다.
..!! 그러게요 `그리고` 라는 접속사가 너무 많네요😅. 좀 줄여보았습니다!

2021-08-07 13:30 UTC, 365kim commented on Level3Essay.md
> +### 개발자는 결국 프로젝트로부터 나온다.
앗 바꿔주신 제목도 좋지만, 원작자의 애정(?)이 담긴 표현을 바꾸시길 바란건 아니라...😭  원래의 표현을 살려주시는게 어떨까요...! 😭 괜한 피드백을 드린 것 같아 죄송하네요...! 🙇🏻‍♀️🙇🏻‍♀️

2021-08-07 14:45 UTC, tributetothemoon commented on Level3Essay.md
> +### 개발자는 결국 프로젝트로부터 나온다.
아니에요!! 의도는 했지만 헷갈리길 바란 것도 아니었으니까요! 그닥 애정(?)이 많지도 않았답니다😅.

2021-08-07 15:09 UTC, tributetothemoon commented on Level3Essay.md
> +하지만 개발자는 누군가 만들어놓은 참고 자료를 읽고, 시험 문제마냥 누군가 의도해서 만들어놓은 문제만을 해결하는 것으로는 부족합니다. 조금만 진중하게 진행되는 단체 프로젝트에 들어가는 순간, 개인 공부를 할 때와는 다른 양상의 문제가 터져 나오기 때문이죠. 그곳엔 개인 공부를 할 때 보던 강의나 책에서의 아주 깔.끔.한 문제 상황 같은 건 나오지 않습니다
ㅎ..ㅎ...즐거웠죠 삭정...

2021-08-07 15:12 UTC, 365kim approved these changes
리뷰 반영해주셔서 감사합니다! 고생하셨어요! 👏👏👏👏👏

2021-08-08 05:27 UTC, 2SOOY approved these changes
안녕하세요 김김 :)

지하철 미션에 저를 구원해주셨죠,, 아직까지 감사함을 표현하지 못했네요ㅜ
항상 감사하게 생각하고 있습니다 🙏🙏🙏 

`개발자`에 대한 생각을 잘 표현해주신 것 같아요 !!! 재미있게 읽었습니다 :)
글을 읽으면서 개발자에 대해서 다시 생각해보는 계기가 되었습니다.
함께 개발하는 과정에서 발생하는 상황에 대해 잘 정리해주신 점 감사합니다 !    

더욱 확고해진 김김의 개발 인생 응원해용 🔥 
남은 프로젝트 기간 동안 파이팅 입니다!! ✊✊✊

2021-08-08 05:27 UTC, 2SOOY commented on Level3Essay.md
> +하지만 개발자는 누군가 만들어놓은 참고 자료를 읽고, 시험 문제마냥 누군가 의도해서 만들어놓은 문제만을 해결하는 것으로는 부족합니다. 조금만 진중하게 진행되는 단체 프로젝트에 들어가는 순간, 개인 공부를 할 때와는 다른 양상의 문제가 터져 나오기 때문이죠. 그곳엔 개인 공부를 할 때 보던 강의나 책에서의 아주 깔.끔.한 문제 상황 같은 건 나오지 않습니다
표현 잘해주셨네용 ㅎㅎㅎㅎ
깔끔하지 못한 문제 상황,,, 쉽지 않네용 😢

2021-08-08 05:27 UTC, 2SOOY commented on Level3Essay.md
> +하지만 이런 때야말로, 개발자로서 갖추어야 할 소양에 대한 시험에 드는 것 같습니다. 이 난해한 과정을 풀어나갈 수 있는 '응용력'이 있는지, 이를 뒷받침해줄 수 있는 '체계적인 지식'이 갖추어져 있는지, 그리고 이 과정들을 이겨낼 수 있는 '인내심'이 있는지를 말입니다.
`응용력` / `체계적인 지식` / `인내심`
김김이 생각하시는 개발자의 덕목이군요 👍👍👍 
정말 중요한 것들을 잘 표현해주셨네요 !!!

2021-08-08 05:27 UTC, 2SOOY commented on Level3Essay.md
> +이럴 때 원활히 상황을 해결해나갈 수 있는, 소위 '소프트 스킬'이란 결국 프로젝트를 통한 협업을 해보지 않고서는 쉽사리 기를 수 없다고 생각합니다. 소프트웨어 프로젝트의 세계에서는 무조건 당차게 의견을 개진하는 것도, 무조건 성심껏 양보하는 것도 상황에 따라 답이 아닐 때가 있습니다. 그 미묘한 차이들을 알아가는 것은 결국 경험 없이는 힘든 일이죠.
정말 공감 가는 문장입니다. 상대방과 코드로 대화하고 미묘함을 겪으면서 대화의 싱크를 맞춰가는 과정이 정말 중요하죠,, 어렵지만 재밌는 것 같아요 :)

2021-08-08 05:27 UTC, 2SOOY commented on Level3Essay.md
> +개발자로 살아가고자 한다면 꼭 한 번쯤 해보아야 하는 질문이라고 생각합니다. 이에 대해 그래도 yes라고 이야기하는 저를 보며, 프로젝트가 저에게 또 하나의 확신을 남겼다는 생각이 들었습니다.
이번 프로젝트를 통해 개발자의 길에 대한 확신을 더했군요 :)
멋있습니당 김김 👍👍👍

2021-08-08 08:02 UTC, tributetothemoon commented on Level3Essay.md
> +물론 개인 공부도 중요합니다. 허구한 날 맨땅에 헤딩하듯 일단 부딪혀 볼 일이 많은 직업이 개발자이긴 하지만, 개인 공부를 통해 체계적이고 심도 깊은 지식이 있어라야 좋은 개발자가 될 수 있는 건 당연하죠.
앗! 이것은 사실 의도한 것입니다. 
> 저도 유조처럼 글을 읽으면서 김김이 저에게 이야기를 해준다는 느낌을 받았네요.

이런 말투 자주 쓰거든요😁

2021-08-08 08:03 UTC, tributetothemoon commented on Level3Essay.md
> +하지만 이런 때야말로, 개발자로서 갖추어야 할 소양에 대한 시험에 드는 것 같습니다. 이 난해한 과정을 풀어나갈 수 있는 '응용력'이 있는지, 이를 뒷받침해줄 수 있는 '체계적인 지식'이 갖추어져 있는지, 그리고 이 과정들을 이겨낼 수 있는 '인내심'이 있는지를 말입니다.
확실히 하루의 피드백 대로 따옴표로 강조표시를 하니 잘 드러나나봐요! 콜린에게 잘 전달되었다니 다행이네요!

2021-08-08 08:03 UTC, tributetothemoon commented on Level3Essay.md
> +이럴 때 원활히 상황을 해결해나갈 수 있는, 소위 '소프트 스킬'이란 결국 프로젝트를 통한 협업을 해보지 않고서는 쉽사리 기를 수 없다고 생각합니다. 소프트웨어 프로젝트의 세계에서는 무조건 당차게 의견을 개진하는 것도, 무조건 성심껏 양보하는 것도 상황에 따라 답이 아닐 때가 있습니다. 그 미묘한 차이들을 알아가는 것은 결국 경험 없이는 힘든 일이죠.
> 상대방과 코드로 대화하고 미묘함을 겪으면서 대화의 싱크를 맞춰가는 과정이 정말 중요하죠,,

콜린도 표현력이 대단하군요...

2021-10-18 04:51 UTC, merged