[레벨 1 글쓰기 미션] 디토(천영석) 미션 제출합니다.
woowacourse/woowa-writing-3 pull request #2
Opened 2021-03-14 10:11 UTC by dudtjr913

## [우아한테크코스 한 달 생활기](https://github.com/dudtjr913/woowa-writing-3/blob/dudtjr913/Level1.md)

2021-03-15 08:03 UTC, daum7766 commented on Level1.md
> +개발은 잘 못하지만 단지 운이 좋아서 붙었다는 생각을 떨칠 수가 없었다.
꿈에 한 발자국 다가감과 동시에 어쩌면 낙오자가 될지도 모른다는 생각 때문일까?
개발은 잘 못하지만 단지 운이 좋아서 붙었다는 생각을 떨칠 수가 없었다.

불안감은 확신보다 추측하는 느낌의 글이 좀 더 생동감이 있을거 같아요!

2021-03-15 08:13 UTC, daum7766 commented on Level1.md
> +자신감을 되찾을 수 있게 도와준 위의 두 가지에 대해서 글을 이어나가려고 한다.
위에서 두 가지
아래서 두 가지가 같은 내용을 가리키고 있는데 조금 어색하다는 느낌이 들었어요!

2021-03-15 08:18 UTC, Junroot requested changes
안녕하세요 디토! 글 읽으면서 공감되는 부분이 많아서 몰입하며 읽었어요!
저도 글쓰기에 부족한 부분이 많지만 몇 가지 코멘트를 남겨봤습니다!
제가 제시한 게 정답은 아니니 같이 고민해봐요!

2021-03-15 08:18 UTC, Junroot commented on Level1.md
> +개발은 잘 못하지만 단지 운이 좋아서 붙었다는 생각을 떨칠 수가 없었다.
`잘 못하다`라는 표현을 저도 평소에 많이 사용하지만, 글로 쓸 때는 혼란의 여지가 있다는 생각이 들어요.

- 틀리거나 그릇된 행동을 하다.
- `잘하다`의 부정 표현

두 가지 의미로 해석될 여지가 있으니 그냥 `못하다` 또는 `잘하지 못하다`로 표현하는 것도 괜찮을 거라는 생각이드네요!

https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=110832

2021-03-15 08:18 UTC, Junroot commented on Level1.md
> +즉, 스스로 정의한 나만이 존재할 뿐 **나 자신을 객관적으로 알지 못했던 것이다.**
이 문장은 두 개의 정보를 담고 있다는 생각이드네요! 디토는 어떻게 생각하세요?😊

2021-03-15 08:18 UTC, Junroot commented on Level1.md
> +간단하게 설명하면 2주간 페어 프로그래밍을 진행하고 헤어지기 전에 회고를 하는 것이다.<br>
`회고를 하는 것이다`는 `회고 하는 것이다`로 표현하면 더 짧고 간결해질 수 있겠다는 생각이 드네요!

2021-03-15 08:25 UTC, daum7766 commented on Level1.md
> +즉, 스스로 정의한 나만이 존재할 뿐 **나 자신을 객관적으로 알지 못했던 것이다.**
어색한 느낌이 나는데 이게 맞는지는 잘 모르겠어요.

26,27 라인은 진행형이고 28은 과거형이여서 어색한 느낌이 나는것 같아요.

2021-03-15 08:26 UTC, daum7766 commented on Level1.md
> +우아한테크코스를 시작하면서 가장 충격적이었던 것은 페어와의 **회고를 통한 상호 피드백**이었다.<br>
왜 충격적인지 바로 밑에 나오면 좋을거같아요!
밑에 가도 왜 충격적인지가 빠져있는거 같아요

2021-03-15 08:27 UTC, daum7766 commented on Level1.md
> +즉, 회고 & 피드백을 통해 타인이 바라보는 자신에 대해 알 수 있게 된다.<br>
즉 -> 정리하는 느낌인데 밑에 글이있어서 질질끈다는 느낌을 받게된는거 같아요
즉 을 빼면 어떨까요?

2021-03-15 08:32 UTC, daum7766 commented on Level1.md
> +지금까지 3명의 페어로부터 받은 공통된 **고쳐야 할 점** 피드백이 있다.<br>
고쳐야 할 점 피드백 이란 말이 어색한거같아요

**고쳐야 할 피드백이 있었다.** 같은 느낌은 어떤가요?

2021-03-15 08:36 UTC, daum7766 commented on Level1.md
> +다시 돌이켜보면 처음 우아한테크코스에 합격했을 때 느꼈던 불안, 걱정은 자존감이 낮았기 때문이다.<br>
돌이켜 보면 -> 과거 회상인데 뒤에는 때문이다. 여기서 어색한 거 같아요

이다 보다 **이었다.** 혹은 **낮았었기 때문이다.** 와 같은 글은 어떤가요?

2021-03-15 08:42 UTC, daum7766 commented on Level1.md
> +만약 우아한테크코스에서 회고와 피드백 없이 페어 프로그래밍만 진행했다면 자존감과 자신감은 점점 더 낮아졌을 것이다.<br>
프로그래밍만 진행했다면 자존감과 자신감은 부분에서 주체가 없는거 같아요!

문맥상 누구를 지칭하는지 아는데 **나의** 를 포함하면 좋을거같아요

2021-03-15 08:46 UTC, daum7766 reviewed
생각나는데로 적어보았어요!
저도 잘 못하는 입장에서 리뷰를 남기려니 어색하네요.
반영할만하다고 생각되는 부분만 반영해주세요!

2021-03-15 08:58 UTC, shinsehantan commented on Level1.md
> +한 달 동안 우아한테크코스를 시작하고 변한 것을 적어본다.
'불안과 걱정', '회고&피드백'이라는 제목으로 내용을 어느 정도 짐작할 수 있었던 것처럼 '느낀점'도 내용을 담을 수 있는 제목으로 바꾸면 좋을 것 같아요 :) 내용의 핵심이 한 달간의 변화인 것 같은데 그런 내용을 담은 제목은 어떨까요?ㅎㅎ

2021-03-15 09:00 UTC, shinsehantan commented on Level1.md
> +
이 소제목만 문장형인데, 다른 제목/소제목과 통일성을 가질 수 있게 수정되면 좋을 것 같아요ㅎㅎ

2021-03-15 09:01 UTC, shinsehantan commented on Level1.md
> +한 달 동안 우아한테크코스를 시작하고 변한 것을 적어본다.
'우아한테크코스를 시작하고 한 달 동안~~'으로 바꾸면 문장이 더 자연스러울 것 같아요!

2021-03-15 09:01 UTC, dudtjr913 commented on Level1.md
> +개발은 잘 못하지만 단지 운이 좋아서 붙었다는 생각을 떨칠 수가 없었다.
오.. 생동감이 느껴지네요!! 좋은 방식인 것 같습니다. 반영하겠습니다.😍😍

2021-03-15 09:15 UTC, dudtjr913 commented on Level1.md
> +자신감을 되찾을 수 있게 도와준 위의 두 가지에 대해서 글을 이어나가려고 한다.
중복이 있었네요. 짚어주셔서 감사합니다. 수정하겠습니다.😀

2021-03-15 09:20 UTC, dudtjr913 commented on Level1.md
> +개발은 잘 못하지만 단지 운이 좋아서 붙었다는 생각을 떨칠 수가 없었다.
`잘 못하다`라는 표현이 애매한 표현이 될 수 있었네요. 좋은 의견 감사합니다.
`못하다`로 바꾸도록 하겠습니다.😍😍

2021-03-15 09:22 UTC, dudtjr913 commented on Level1.md
> +즉, 스스로 정의한 나만이 존재할 뿐 **나 자신을 객관적으로 알지 못했던 것이다.**
저도 그렇게 생각합니다. 문장을 분리하도록 하겠습니다.😥😥

2021-03-15 09:24 UTC, dudtjr913 commented on Level1.md
> +간단하게 설명하면 2주간 페어 프로그래밍을 진행하고 헤어지기 전에 회고를 하는 것이다.<br>
수정하겠습니다. 좋은 방법이네요!

2021-03-15 09:27 UTC, dudtjr913 commented on Level1.md
> +즉, 스스로 정의한 나만이 존재할 뿐 **나 자신을 객관적으로 알지 못했던 것이다.**
모두 진행형으로 바꿔 어색한 부분을 없애도록 하겠습니다.
글을 작성할 때 확인하지 못한 부분인데 피드백 감사합니다.😁

2021-03-15 09:39 UTC, dudtjr913 commented on Level1.md
> +우아한테크코스를 시작하면서 가장 충격적이었던 것은 페어와의 **회고를 통한 상호 피드백**이었다.<br>
```
우아한테크코스에서는 페어와의 회고를 통한 상호 피드백을 한다.
간단하게 설명하면 2주간 페어 프로그래밍을 진행하고 헤어지기 전에 회고 하는 것이다.
이때, 서로의 성장을 위해 좋았던 것, 고쳤으면 좋겠다고 생각하는 것을 말해준다.
상대방에게 직접 고쳐야할 점을 말해줘야 한다는 점이 충격이다.
```
문장 자체를 진행형으로 바꾸면서 충격적인지에 대한 문장은 맨 아래에 만들었습니다.😍😍

2021-03-15 09:40 UTC, dudtjr913 commented on Level1.md
> +즉, 회고 & 피드백을 통해 타인이 바라보는 자신에 대해 알 수 있게 된다.<br>
위와 마찬가지로 충격적인 이유 다음에 나오는 문장으로 즉 => `하지만`으로 변경했습니다.
충격적이지만 회고 & 피드백은 좋다라는 느낌을 주기 위해서 `하지만`으로 변경하게 되었습니다.😆😆

2021-03-15 09:41 UTC, dudtjr913 commented on Level1.md
> +지금까지 3명의 페어로부터 받은 공통된 **고쳐야 할 점** 피드백이 있다.<br>
와우.. 고쳐야 할 점 피드백이라니!! 정말 이상한 단어를 사용했었네요.
좋은 지적 감사합니다!😍

2021-03-15 09:44 UTC, dudtjr913 commented on Level1.md
> +다시 돌이켜보면 처음 우아한테크코스에 합격했을 때 느꼈던 불안, 걱정은 자존감이 낮았기 때문이다.<br>
과거형으로 바꿔서 **낮았었기 때문이다.** 로 수정하였습니다.
그리고 바로 아래 문장에도 **낮았던**을 **낮았었던**으로 수정하였습니다.

2021-03-15 09:46 UTC, dudtjr913 commented on Level1.md
> +만약 우아한테크코스에서 회고와 피드백 없이 페어 프로그래밍만 진행했다면 자존감과 자신감은 점점 더 낮아졌을 것이다.<br>
**나**를 사용하는 것을 최대한 지양하려다 보니 이해하기 힘들 수도 있는 부분이 생기는군요!
**나의**를 추가하겠습니다. 감사합니다.😍😍😍

2021-03-15 09:48 UTC, dudtjr913 commented on Level1.md
> +한 달 동안 우아한테크코스를 시작하고 변한 것을 적어본다.
와우!🤩 좋은 피드백입니다. 느낀 점을 **한 달간의 변화**로 수정하였습니다.
제목만 봐도 글의 내용을 짐작할 수 있도록 하기! 명심하겠습니다.

2021-03-15 09:51 UTC, dudtjr913 commented on Level1.md
> +
**객관적인 나를 발견하기**로 소제목을 수정했습니다.
통일성을 지키지 못했군요..ㅠㅠ 
피드백 감사합니다.😍😍😍

2021-03-15 09:52 UTC, dudtjr913 commented on Level1.md
> +한 달 동안 우아한테크코스를 시작하고 변한 것을 적어본다.
와우 부끄럽네요..ㅋㅋㅋㅋ 이런 문장을 작성하다니;; 
얼른 바꾸겠습니다.😅😅😅😅

2021-03-24 05:03 UTC, daum7766 approved these changes
저는 읽었을때 매끄럽게 잘 읽어지고 이해가 잘된다고 생각해서 여기서 리뷰를 마무리하겠습니다.
피드백 반영하느라 수고하셨어요!
디토! 나머지 미션도 화이팅해요!

2021-03-25 15:26 UTC, shinsehantan approved these changes
합격했을 때, 그리고 생활 초반에 느꼈던 감정이 저와 비슷해서 공감하며 읽었어요. 저와 디토가 다른 점이라면, 디토는 그 불안감을 빠르게 극복해서 자신감을 되찾았다는 점이고, 저는 아직 그 과도기에 있다는 점이겠죠? 

아는지 모르겠지만 저는 디토와 페어 프로그래밍 하면서 자존감을 많이 회복하고 있어요. '신세한탄 천재야!', '신세한탄 얼른 이 버그 고쳐줘봐. 잘 하잖아.' 디토가 농담으로 던지는 말이 얼마나 힘이 되는지 알까요~ 디토는 좋은 영향력을 가진 크루라는 사실도 알려주고 싶어서 덧붙여봅니다 :) 앞으로도 같이 우테코 생활을 잘 해나가 보아요!

approve!🧚🧚🏼‍♂️

2021-03-26 06:52 UTC, Junroot approved these changes
피드백 잘 반영해주셔서 감사합니다! 더 이상 피드백 할 부분이 보이지 않으니 여기서 마무라하도록 하겠습니다!
페어 프로그래밍하면서 서로 직접 피드백을 주셨나보군요! 좀 아프긴 하지만 자신의 문제점을 빨리 인지하고 고칠 수 있으니 좋을거 같습니다! 계속 자신을 발전시키려는 모습이 멋있어요! 저도 본받아서 열심히 하겠습니다! 수고하셨어요!!

2021-03-26 16:08 UTC, unluckyjung commented on Level1.md
> +짧은 기간 동안 이렇게 많이 변할 줄은 생각지도 못했다. 이렇게 좋은 기회를 준 우아한테크코스에게 감사하며 더 나은 개발자가 되기 위해 부단히 노력할 것이다.
오프라인에서 가장 처음으로본 디토! + (인치)

설날에 맥주 한잔하면서 이야기 하신 몇가지 고민과 의문점에 대해서 스스로 답을 찾으신것 처럼 보이는군요 ㅎㅎ
우리가 만난지도 벌써 한달반이 넘어가는데, 시간되면 맥주 한잔하시죠 ㅋㅋ.
처음만났을때와는 또 다른 느낌으로 재밌게 떠들수 있을것 같아요 ㅋㅋ

2021-03-27 05:31 UTC, binghe819 reviewed
디토 안녕하세요!! 마크에요!

글 너무 잘 읽었어요ㅎㅎ 

프로그래밍 실력뿐만 아니라 자신을 되돌아보는 과정을 통해 의식이 성장한 부분이 인상이 깊네요!ㅎㅎ

몇 가지 고쳤으면 하는 피드백을 남겼는데요! 제 관점에서의 피드백이므로 꼭 변경할 필요는 없을 것 같아요!!

2021-03-27 05:31 UTC, binghe819 commented on Level1.md
> +두 달 전, 우아한테크코스 합격 메일을 받고 기쁨과 함께 불안감이 몰려왔다. 꿈에 한 발자국 다가감과 동시에 어쩌면 낙오자가 될지도 모른다는 생각 때문일까? 그래서인지 개발은 못하지만 단지 운이 좋아서 붙었다는 생각을 떨칠 수가 없었다.
```suggestion
두 달 전, 우아한테크코스 합격 메일을 받고 기쁨과 함께 불안감이 몰려왔다. 꿈에 한 발자국 다가감과 동시에 어쩌면 낙오자가 될지도 모른다는 생각 때문일까? 그래서인지 개발은 못 하지만 단지 운이 좋아서 붙었다는 생각을 떨칠 수가 없었다.

```

2021-03-27 05:31 UTC, binghe819 commented on Level1.md
> +> 실력도 있고, 충분히 가치 있는 사람이고, 가진 것도 많은데 자존감이 낮은 것 같다. 자존감을 높이고 자신감을 좀 가져라.
디토가 페어 기간동안 어떤 행동을 해서 페어가 이렇게 생각했는지를 간단한 예시로 설명해주면 더 좋을 것 같아요!
( 굳이 변경할 필요는 없을 것 같아요!ㅎㅎㅎ 그냥 제가 궁금하기도 하고.. 다른 독자중에도 궁금해할 수 있을 것 같아 코멘트 남깁니다!)

2021-03-27 05:31 UTC, binghe819 commented on Level1.md
> +우아한테크코스에서는 페어와의 **회고를 통한 상호 피드백**을 한다. 간단하게 설명하면 2주간 페어 프로그래밍을 진행하고 헤어지기 전에 회고 하는 것이다. 이때, 서로의 성장을 위해 **좋았던 것**, **고쳤으면 좋겠다고 생각하는 것**을 말해준다. 상대방에게 직접 고쳐야할 점을 말해줘야 한다는 점이 충격이다.
```suggestion
우아한테크코스에서는 페어와의 **회고를 통한 상호 피드백**을 한다. 간단하게 설명하면 2주간 페어 프로그래밍을 진행하고 헤어지기 전에 회고하는 것이다. 이때, 서로의 성장을 위해 **좋았던 것**, **고쳤으면 좋겠다고 생각하는 것**을 말해준다. 상대방에게 직접 고쳐야 할 점을 말해줘야 한다는 점이 충격이다.
```

2021-03-27 05:31 UTC, binghe819 commented on Level1.md
> +- 혼자가 아닌 페어와 함께 프로그래밍을 하는 것이 더 즐겁다.
```suggestion
- 혼자가 아닌 페어와 함께 프로그래밍하는 것이 더 즐겁다.
```

2021-03-27 05:31 UTC, binghe819 commented on Level1.md
> +
```suggestion

<br>

```
디토! 저도 최근에 알아낸 꿀팁인데요ㅎㅎ 저렇게 하면 소제목간의 띄워쓰기가 생겨서 전체적인 구조가 보기 좋더라구요!

2021-03-27 19:03 UTC, da-nyee approved these changes
안녕하세요 디토! 다니입니다 🙌
먼저 리뷰가 늦어져서 죄송합니다 ㅠㅠ

글 잘 읽었습니다!
우테코에서 생활하며 자신감과 자존감을 높여가는 디토의 모습이 인상적인 글이었어요!

직접 뵌 적은 아직 없지만, 조만간 대면으로 만나서 같이 얘기 나누고 싶네요 🤗

앞서 다른 크루들이 피드백을 잘 해주어서 제가 크게 남길 게 없었어요!
단순히 문법적인 부분들만 몇 개 리뷰 남겼습니다!
디토가 판단했을 때 굳이 수정해야 하나? 싶다면 그대로 둬도 괜찮습니다~!

저는 전체적인 글에 만족하기 때문에 우선 Approve 하겠습니다! 수고하셨습니다 👏👏

2021-03-27 19:03 UTC, da-nyee commented on Level1.md
> +아쉽게도 지금까지 나 역시도 부족한 점을 들었던 적이 없다. 그래서 스스로 생각하는 나의 부족한 점은 있지만, 내가 생각한 부족한 점을 상대방도 같게 느끼는지 알 수 없다. 스스로 정의한 나만이 존재할 뿐이다. 결국 **나 자신을 객관적으로 알지 못한 것이다.**
```suggestion
아쉽게도, 지금까지 나 또한 부족한 점을 들었던 적이 없다. 그래서 스스로 생각하는 나의 부족한 점은 있지만, 내가 생각한 부족한 점을 상대방도 같게 느끼는지 알 수 없다. 스스로 정의한 나만이 존재할 뿐이다. 결국 **나 자신을 객관적으로 알지 못한 것이다.**
```

2021-03-27 19:03 UTC, da-nyee commented on Level1.md
> +다시 돌이켜보면 처음 우아한테크코스에 합격했을 때 느꼈던 불안, 걱정은 자존감이 낮았었기 때문이다. 자존감이 낮았었던 이유는 **스스로** 판단하기에 실력이 부족하다고 느꼈기 때문이다.
```suggestion
다시 돌이켜보면 처음 우아한테크코스에 합격했을 때 느꼈던 불안과 걱정은 자존감이 낮았었기 때문이다. 자존감이 낮았었던 이유는 **스스로** 판단하기에 실력이 부족하다고 느꼈기 때문이다.
```

2021-03-27 19:03 UTC, da-nyee commented on Level1.md
> +다시 돌이켜보면 처음 우아한테크코스에 합격했을 때 느꼈던 불안, 걱정은 자존감이 낮았었기 때문이다. 자존감이 낮았었던 이유는 **스스로** 판단하기에 실력이 부족하다고 느꼈기 때문이다.
나열된 단어가 2개 뿐이니까 `,` 보다는 `과` 가 낫지 않을까?! 싶어서 suggestion 남겼어요!

2021-03-28 02:14 UTC, dudtjr913 commented on Level1.md
> +두 달 전, 우아한테크코스 합격 메일을 받고 기쁨과 함께 불안감이 몰려왔다. 꿈에 한 발자국 다가감과 동시에 어쩌면 낙오자가 될지도 모른다는 생각 때문일까? 그래서인지 개발은 못하지만 단지 운이 좋아서 붙었다는 생각을 떨칠 수가 없었다.
엇!! 감사합니다. 당연히 `못하지만`으로 붙여 쓰는 건 줄 알았어요.. 수정하겠습니다.

2021-03-28 02:17 UTC, dudtjr913 commented on Level1.md
> +
꿀팁 감사합니다!!!

2021-03-28 02:19 UTC, dudtjr913 commented on Level1.md
> +우아한테크코스에서는 페어와의 **회고를 통한 상호 피드백**을 한다. 간단하게 설명하면 2주간 페어 프로그래밍을 진행하고 헤어지기 전에 회고 하는 것이다. 이때, 서로의 성장을 위해 **좋았던 것**, **고쳤으면 좋겠다고 생각하는 것**을 말해준다. 상대방에게 직접 고쳐야할 점을 말해줘야 한다는 점이 충격이다.
띄어쓰기를 잘해야겠네요ㅜㅜㅜㅜ 감사합니다.

2021-03-28 02:19 UTC, dudtjr913 commented on Level1.md
> +- 혼자가 아닌 페어와 함께 프로그래밍을 하는 것이 더 즐겁다.
꼼꼼하게 봐주셔서 감사합니다.😍😍

2021-03-28 02:21 UTC, dudtjr913 commented on Level1.md
> +아쉽게도 지금까지 나 역시도 부족한 점을 들었던 적이 없다. 그래서 스스로 생각하는 나의 부족한 점은 있지만, 내가 생각한 부족한 점을 상대방도 같게 느끼는지 알 수 없다. 스스로 정의한 나만이 존재할 뿐이다. 결국 **나 자신을 객관적으로 알지 못한 것이다.**
제 생각에도 `또한`이 더 나은 것 같아요! 생각하지 못한 부분인데 감사합니다.

2021-03-28 02:21 UTC, dudtjr913 commented on Level1.md
> +다시 돌이켜보면 처음 우아한테크코스에 합격했을 때 느꼈던 불안, 걱정은 자존감이 낮았었기 때문이다. 자존감이 낮았었던 이유는 **스스로** 판단하기에 실력이 부족하다고 느꼈기 때문이다.
여기는 왜 `,`로 했을까요?? `과`가 더 읽기 좋은 것 같아요. 감사합니다 수정할게요!

2021-03-28 02:31 UTC, dudtjr913 commented on Level1.md
> +> 실력도 있고, 충분히 가치 있는 사람이고, 가진 것도 많은데 자존감이 낮은 것 같다. 자존감을 높이고 자신감을 좀 가져라.
수정했습니다. b131271 커밋 위치에요! 글이 더 매끄러워진 것 같아요👍👍 감사합니다~

2021-03-28 09:51 UTC, binghe819 approved these changes

2021-03-29 05:38 UTC, unluckyjung approved these changes

2021-05-14 06:25 UTC, woowahanCU approved these changes
디토! 안녕하세요~ 아직 한번도 이야기해 본적이 없어 그런지, 글이 묵직하네요 😅
글을 보니, 결국 자신감을 회복한 것이지요?! ㅎㅎ
우테코 크루들 중 잘하는 친구들이 많아서, 25:1로 비교하기 시작하면 참 위축되지요.
하지만 교육을 하는 저희는 여러분에 대한 자신이 있어요.
여러분 한명한명이 좋은 사람들이기에 다른 곳에 가서도 인정받을 거라 생각해요.
날씨가 더워지면서 텐션이 떨어질 수 있는데, 건강 관리 잘해서 우선은 5월 한달 목표한 바 잘 이뤄내길 바래요~ 🙏🏻

2021-05-14 06:25 UTC, merged