[레벨 3 글쓰기 미션] 포모(박은소리) 미션 제출합니다.
woowacourse/woowa-writing-3 pull request #208
Opened 2021-08-02 13:59 UTC by bosl95

글쓰기 미션 제출이 늦었습니당 😂😂😂
일기처럼 막 쓰다보니 글이 길어졌네요.. 이런 날것(?)의 글에 피드백 주셔서 감사합니다 ㅎㅎ 
👉 [편하게 보세요!](https://github.com/bosl95/woowa-writing-3/blob/bosl95/level3-writing.md)

@Tanney-102
@zereight
@seovalue
@Sehwan-Jang
@xrabcde
@SunYoungKwon

2021-08-03 00:52 UTC, zereight commented on level3-writing.md
> +뿐만 아니라 아침 오기상을 통해 어제 이상한 꿈을 꾼 크루들의 이야기를 듣기도 하며 다소 피곤할 수 있는 아침을 유쾌하게 시작하곤 한다.
오 좋은 팀문화네요!

2021-08-03 00:53 UTC, zereight commented on level3-writing.md
> +놀토팀은 힘든 상황에서도 `분노 0.1 스택 쌓았다`며 유쾌하게 웃고 지나간다.
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2021-08-03 00:54 UTC, zereight commented on level3-writing.md
> +- 의견이 나뉘더라도 한쪽으로 치우치지 않도록 한다.
👍👍👍👍👍

2021-08-03 00:56 UTC, zereight commented
안녕하세요 포모!
놀토팀의 팀 분위기가 잘 느껴지네요 ㅎㅎ
글을 3번 읽었는데 피드백할 점을 찾지 못해서 저는 approve 드리겠습니다. (되겠지? 👀)
남은 프로젝트 기간도 파이팅하십셔!

2021-08-03 00:56 UTC, zereight approved these changes

2021-08-03 05:23 UTC, seovalue commented on level3-writing.md
> +이를 위해서 팀 문화를 세울 때 그날의 기분 상태를 이야기하는 게 어떨지 제안해보았다.
오! 정말 좋은 것 같아요 👍 가끔은 피해가 될까봐 내 상태를 말하는게 쉽지 않은데!

2021-08-03 05:24 UTC, seovalue commented on level3-writing.md
> +이러한 팀원들에게 있어 나 또한 의견을 존중할 줄 아는 팀원이 되기 위해 많은 고민을 했다.
포모는 멋진 팀원이군요 👍

2021-08-03 05:25 UTC, seovalue approved these changes
포모 글 잘 읽었어요! 팀의 일원으로서 포모는 참 멋진 사람일 것 같아요 👍 
바쁘신 와중 좋은 글 남겨주시느라 수고 많으셨어요!
남은 프로젝트 기간도 응원할게요 💯

2021-08-04 15:30 UTC, Sehwan-Jang approved these changes
첫 페어때부터 느꼈지만 포모는 항상 상대방을 배려하려 노력하는 크루인 것 같아요.
이번 글을 읽으면서 더욱 확신이 들었습니다! 😊 

글도 술술 잘 읽히고 지적할 만한 부분이 없는 것 같아 approve 드릴게요.
글 쓰시느라 수고 많으셨어요!

2021-08-04 15:30 UTC, Sehwan-Jang commented on level3-writing.md
> +이를 위해서 팀 문화를 세울 때 그날의 기분 상태를 이야기하는 게 어떨지 제안해보았다.
감정회고 👍👍👍

2021-08-04 15:30 UTC, Sehwan-Jang commented on level3-writing.md
> +고민이 많아지다 보면 의견을 낼 타이밍을 놓치기도 했다.
맞아요 저도 머뭇거리다 말할 타이밍 놓친 적이 많은 것 같아요 ㅠㅠ

2021-08-07 05:23 UTC, xrabcde approved these changes
안녕하세요 포모~ 바다입니다 🌊
포모의 글에서 프로젝트기간 동안 포모가 느낀 감정이 전해져서 좋았어요 ㅎㅎ
바쁜데도 좋은 글 써주셔서 감사합니다 ❤️

2021-08-07 05:23 UTC, xrabcde commented on level3-writing.md
> +다양한 의견이 나오다보면 팀원 모두가 100% 만족하기는 결론에 도달하는 데에 어려움이 있다.
문장을 조금 자연스럽게 수정해보았어요~
```suggestion
다양한 의견이 나오다 보니 팀원 모두가 100% 만족할 수 있는 결론에 도달하기는 어렵다.   
```

2021-08-07 05:23 UTC, xrabcde commented on level3-writing.md
> +결과적으로 레벨3 초반에 걱정했던 프로젝트의 완성도에 대한 불안감이 점차 사라졌고, 팀원들에 대한 믿음이 생겼다.
공감되는 부분이네요 ㅎㅎ

2021-08-08 11:33 UTC, DWL5 commented
하잇 포모 글에서 놀토팀 분위기가 보인당 보여
분노 0.1 스택 쌓았다 ㅋㅋㅋㅋ
스택 많이 쌓으면 나서스처럼 캐리할 수 있는건가!!!!!!!!!! 
성장해서 왕귀개발자 되자 홧팅~

2021-08-08 12:16 UTC, bosl95 commented on level3-writing.md
> +이를 위해서 팀 문화를 세울 때 그날의 기분 상태를 이야기하는 게 어떨지 제안해보았다.
> 오! 정말 좋은 것 같아요 👍 가끔은 피해가 될까봐 내 상태를 말하는게 쉽지 않은데!

맞아요ㅠㅠ! 아예 저렇게 시간을 딱 정해놓으니 말하기도 편하더라구요!! ㅎㅎ

2021-08-08 12:17 UTC, bosl95 commented on level3-writing.md
> +고민이 많아지다 보면 의견을 낼 타이밍을 놓치기도 했다.
흑 ㅠㅠ 지금도 열심히 노력중입니당 .. ㅎㅎㅎ

2021-08-08 12:18 UTC, bosl95 commented on level3-writing.md
> +다양한 의견이 나오다보면 팀원 모두가 100% 만족하기는 결론에 도달하는 데에 어려움이 있다.
오 너무 좋아요~~ 감사합니당ㅎㅎ

2021-08-08 12:19 UTC, Tanney-102 approved these changes
안녕하에요 포모! 브콜입니다 ㅎㅎ
이번 프로젝트가 포모에게 '즐거운 프로젝트' 경험이 될 수 있었던 것에
팀문화를 위한 포모의 고민과 노력도 한 몫을 한 것 같네요 ㅎㅎ
좋은 글 잘 읽었습니다!

2021-08-08 12:19 UTC, Tanney-102 commented on level3-writing.md
> +'커피를 안 마셔서 아직 부팅이 덜 됐어요.', '홍삼을 먹어서 그런지 컨디션 최고예요.' 등 **오늘의 기분 상태**를 이야기하는 데일리, **오기상**을 매일 진행하였다.
구체적인 오기상 좋네요 ㅎㅎ

2021-08-08 12:19 UTC, Tanney-102 commented on level3-writing.md
> +소극적인 성격 탓인지 의견을 단호하게 거부당하면 다음 의견을 낼 때 '지금 이 의견이 과연 괜찮은 걸까?'라는 생각과 함께 고민이 많아진다.
아무래도 위축이 되죠ㅜ

2021-08-08 13:49 UTC, da-nyee reviewed
🧡 포모 🧡

포모포모 보고싶어서 들렸습니다 ㅎㅎㅎ
놀토 팀을 위해 노력하는 포모 넘 멋있어요 ✨

항상 응원하고 있으니까 남은 기간도 파이팅!! 💖

2021-08-08 19:25 UTC, SunYoungKwon approved these changes
안녕하세요. 포모!
포모의 글에서 놀토팀의 팀문화가 얼마나 좋은지 느껴지네요ㅎㅎ
데일리 시작에 앞서 그날의 기분을 이야기하는 규칙이 너무 좋아보여요! 그런 시간들이 쌓여 서로서로 편하게 대화하고 의견을 낼 수 있는 분위기를 만드는게 아닐까 싶어요.
좋은 글 감사합니다👍

2021-08-08 19:25 UTC, SunYoungKwon commented on level3-writing.md
> +이를 위해서 팀 문화를 세울 때 그날의 기분 상태를 이야기하는 게 어떨지 제안해보았다.
좋은 방법이네요!

2021-08-08 23:14 UTC, sihyung92 commented
뭔가 못보는데 자주보는거 같은 포모 하이✋
오기상 좋다! 줄임말로 표현한 부분이 특히 좋았어 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
농담이구 하루 컨디션을 공유하는 것도 중요한것 같아! 서로를 알아가는 데도 도움되고 실수해도 이해해줄 수 있는 바탕이 되고😌
포모라면 분명히 좋은분위기를 만들어가는데 일조하고 있을거라 생각해~! 마지막 일주일도 웃으면서 끝내길!!💪

2021-08-09 00:47 UTC, bosl95 commented on level3-writing.md
> +'커피를 안 마셔서 아직 부팅이 덜 됐어요.', '홍삼을 먹어서 그런지 컨디션 최고예요.' 등 **오늘의 기분 상태**를 이야기하는 데일리, **오기상**을 매일 진행하였다.
😊

2021-08-09 00:49 UTC, bosl95 commented on level3-writing.md
> +소극적인 성격 탓인지 의견을 단호하게 거부당하면 다음 의견을 낼 때 '지금 이 의견이 과연 괜찮은 걸까?'라는 생각과 함께 고민이 많아진다.
저만 그런게 아니었군요!!  🙂

2021-08-12 13:24 UTC, devJang requested changes
항상 밝은 포모를 보다보니 이런 고민을 하고 있을 것이라고는 생각도 못했는데
속으로는 이런 고민들을 품고 있었군요

사실 걱정의 대부분은 일어나지 않을 수 있는 일이기도 합니다~!
앞으로는 침묵보다는 적극적인 의견과 경청으로 달라진 포모를 기대해봅니다~~

(아 그리고 오타가 하나 있어서 코멘트 남겼어요)

2021-08-12 13:24 UTC, devJang commented on level3-writing.md
> +다양한 의견이 나오다 보니 팀원 모두가 100% 만족헐 수 있는 결론에 도달하기는 어렵다.
```suggestion
다양한 의견이 나오다 보니 팀원 모두가 100% 만족할 수 있는 결론에 도달하기는 어렵다.
```

2021-08-16 05:28 UTC, bosl95 commented on level3-writing.md
> +다양한 의견이 나오다 보니 팀원 모두가 100% 만족헐 수 있는 결론에 도달하기는 어렵다.
빠르게 수정했습니당!!!!! 😂

2021-08-17 12:46 UTC, merged