[레벨 3 글쓰기 미션] 다니(이다은) 미션 제출합니다.
woowacourse/woowa-writing-3 pull request #217
Opened 2021-08-02 14:39 UTC by da-nyee

안녕하세요! 다니입니다 🙌

[팀 프로젝트가 나에게 남긴 것](https://github.com/da-nyee/woowa-writing-3/blob/level3/LEVEL3.md) 작성했습니다!

@sunhpark42 서니
@ggyool 중간곰
@hyuuunjukim 엘라
@yungo1846 곤이
@yjksw 코다
@bigsaigon333 동동

리뷰 잘 부탁드립니다 ✨

2021-08-03 05:40 UTC, Hyeon9mak commented on LEVEL3.md
> +백엔드 팀원들이 소위 `개발을 잘한다`고 언급되는 크루들이었기 때문이다.<br/>
자기 소개 잘 봤습니다

2021-08-03 10:34 UTC, DWL5 commented on LEVEL3.md
> +백엔드 팀원들이 소위 `개발을 잘한다`고 언급되는 크루들이었기 때문이다.<br/>
깃-들다 팀원이 되고 원하는 프로젝트를 진행할 수 있다는 기쁨이 있었지만, 동시에 걱정도 많이 됐다.<br/>
백엔드 팀원들이 소위 `개발을 잘한다`고 언급되는 크루들이었기 때문이다.<br/> 

-> 근대 내가 더 잘해서 기죽일까봐

2021-08-03 10:36 UTC, Hyeon9mak commented on LEVEL3.md
> +백엔드 팀원들이 소위 `개발을 잘한다`고 언급되는 크루들이었기 때문이다.<br/>
진짜 ㅠㅠ 팀원들 숨은 쉬고 있을까?

2021-08-03 13:36 UTC, da-nyee commented on LEVEL3.md
> +백엔드 팀원들이 소위 `개발을 잘한다`고 언급되는 크루들이었기 때문이다.<br/>
ㅋㅋㅋㅋㅋㅋㅋㅋ아 구막 수리 😂

2021-08-03 14:46 UTC, bosl95 commented
낰낰 여기저기 출몰하는 우테코 마당발 다니가 안 보여서 제가 찾으러 왔습니당
레벨 1 글쓰기 미션 때 글 잘 쓴거 같냐고 보여줬던 다니의 모습이 엊그제 같은데 벌써 레벨3네요!
남은 기간까지 화이팅!!!!!!!!

2021-08-04 14:24 UTC, knae11 commented
다니 힘내!!

2021-08-04 15:04 UTC, yungo1846 reviewed
안녕하세요 다니 :)
문장 단위가 짧아서 쉽고 재밌게 읽을 수 있었습니다!
글을 읽으면서 공감 가는 내용도 있었고 제가 다니에게 배우고 싶은 점도 발견할 수 있었습니다 👍
피드백을 드리고 싶은데 군더더기 없이 쓰여진 글이라고 생각돼서 크게 드릴 말씀이 없습니다 ㅎㅎ
좋은 글 써주셔서 감사합니다.

2021-08-04 15:04 UTC, goni-ssi commented on LEVEL3.md
> +요즘은 이를 방지하기 위해 손을 들고 차례를 기다리거나, 이 의견을 지금 말하는 게 맞는지 다시 한번 점검하는 노력을 하고 있다.<br/>
의욕 넘치는 팀원이 있으면 같이 일하는 팀원들도 의욕이 생기죠 ㅎㅎ
저도 불현듯 아이디어가 떠오르면 앞뒤 안 재고 이야기하는 성격인데 다니를 보고 배우겠습니다.
차례를 기다리거나, 다시 한번 더 고민해보고 이야기하는 것으로 말이죠...!

2021-08-04 15:04 UTC, yungo1846 commented on LEVEL3.md
> +우리 팀이 유독 워커홀릭 성향이 강해서인지 조금 여유롭게 진행하려 해도 잘 되지 않는 것 같다. 일 얘기 외에도 적당히 잡담하며 팀원들에 대해 더 알아가고 싶다.<br/>
저도 팀원들과 일 외적인 이야기를 더 할 수 있으면 좋았을텐데하는 아쉬움이 있네요 😂
코로나가 빨리 끝나서 팀원들이랑 여행도 가고 술도 마실 날이 오면 좋겠습니다.

2021-08-06 23:16 UTC, pika96 approved these changes
깃들다 팀에서 잘 하고 있다고 생각이 들었는데
개인적으로 이런 저런 고민이 있었군요!
다니라면 잘 해결할 수 있을 거라 생각해요~
팀원들과도 하루빨리 더 친해지길 바랄께요~

2021-08-06 23:16 UTC, pika96 commented on LEVEL3.md
> +그래서 1지망으로 지원했다. 유독 경쟁이 치열했던 프로젝트여서 운에 맡겨야 했다. 운이 좋게도 붙었고 팀원이 됐다.<br/>
다니가 정말 들어가고 싶었던게 생각나네요..!
붙어서 다행이예요!

2021-08-06 23:16 UTC, pika96 commented on LEVEL3.md
> +백엔드 팀원들이 소위 `개발을 잘한다`고 언급되는 크루들이었기 때문이다.<br/>
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2021-08-06 23:16 UTC, pika96 commented on LEVEL3.md
> +긍정적인 마인드로 바라보는 게 좋기 때문에 전자보다는 후자의 생각을 가지고 프로젝트를 시작하게 됐다.<br/>
저도 잘하는 팀원들 안에 있어서 가끔 힘들지만 배우는 것도 많기때문에 더 열심히 하려고 하는 것 같아요!
근데 다니도 워낙 잘하니까 상관없을 것 같아요!

2021-08-06 23:16 UTC, pika96 commented on LEVEL3.md
> +이 시절에는 욕심이 별로 없어 그랬는지도 모른다. 하지만 우테코 프로젝트는 달랐다. 프로젝트에 큰 기여를 하고 싶었고, 그래서 욕심이 많이 났다.<br/>
마크랑 비슷하네요! 팀장을 닮는 팀원!

2021-08-06 23:16 UTC, pika96 commented on LEVEL3.md
> +회의 장소가 개인적으로 조금 먼 곳이기도 했고, 날도 유독 더워서 이동하며 힘들었다.<br/>
회의 장소가 어딘가요?

2021-08-06 23:16 UTC, pika96 commented on LEVEL3.md
> +지금 당장 열정을 쏟아붓는 것도 좋지만, 앞으로의 개발 생활을 길 것이기 때문에 천천히 멀리 가는 게 중요하다.<br/>
개발은 단거리가 아닌 마라톤!!

2021-08-06 23:16 UTC, pika96 commented on LEVEL3.md
> +앞으로 남은 기간 동안 어떻게 보내고 싶은지 생각하면, 내가 맡은 일을 잘 처리하고 팀에 더 도움되는 팀원이 되고 싶다. 그리고 팀원들과 더 친해지고 싶다.<br/>
깃들다 팀에서 서로 되게 많이 친하다고 생각했는데 아직인가보군요!
하루빨리 친해지길 바랄께요!!

2021-08-07 14:17 UTC, da-nyee commented on LEVEL3.md
> +백엔드 팀원들이 소위 `개발을 잘한다`고 언급되는 크루들이었기 때문이다.<br/>
우리 팀원들 최고 ✨

2021-08-07 14:21 UTC, da-nyee commented on LEVEL3.md
> +회의 장소가 개인적으로 조금 먼 곳이기도 했고, 날도 유독 더워서 이동하며 힘들었다.<br/>
ㅋㅋㅋㅋㅋㅋㅋ 잠실 근처에 있습니다 😉

2021-08-07 14:30 UTC, da-nyee commented on LEVEL3.md
> +앞으로 남은 기간 동안 어떻게 보내고 싶은지 생각하면, 내가 맡은 일을 잘 처리하고 팀에 더 도움되는 팀원이 되고 싶다. 그리고 팀원들과 더 친해지고 싶다.<br/>
팀원 다같이 모일 수가 없어서 넘넘 아쉬워요 😥

2021-08-07 14:33 UTC, yjksw approved these changes
다니~~~!! 재미있는 글 잘 읽었어요!! 
다니가 쓴 글을 쭉 읽으니 지금까지 흘러온 우리 팀 프로젝트를 돌아보고 
얼마 되진 않았지만 그랬었지...하면서 추억에 잠기기도 했네요 ㅎㅎㅎ
저희 처음 만나서 기획도 하고 기대하는 것도 말하고 그리고 하나씩 적용해가면서 
서로 조율하고 이해하고 도와주며 잘 지내온 것 같아요 😊  
가끔씩 다니랑 눈만 마주쳐도 속마음이 통해서 빵 터졌던 게 생각나네요 .....ㅋ
도움이 되는 피드백을 남기고 싶었지만 전체적으로 깔끔하게 잘 읽히고 내용도 구체적이고 좋았던 것 같아요!! 
앞으로 남은 날도 화이팅하고 끝나고도 쭉 봅시다유 !! 💓🎉

2021-08-07 14:33 UTC, yjksw commented on LEVEL3.md
> +그 이유는 `Git` 도메인이 탐났다. 개인적으로 가지고 있는 기술적 강점 중 하나가 Git이라 생각하는데, 이와 관련한 프로젝트란 점에서 끌렸다.<br/>
역시 우리 깃문가 다니 🎉👍

2021-08-07 14:33 UTC, yjksw commented on LEVEL3.md
> +긍정적인 마인드로 바라보는 게 좋기 때문에 전자보다는 후자의 생각을 가지고 프로젝트를 시작하게 됐다.<br/>
열정에서는 다니를 따라갈수가 없지요!!! 👏

2021-08-07 14:33 UTC, yjksw commented on LEVEL3.md
> +요즘은 이를 방지하기 위해 손을 들고 차례를 기다리거나, 이 의견을 지금 말하는 게 맞는지 다시 한번 점검하는 노력을 하고 있다.<br/>
나름의 해결책을 잘 찾고 조율해가고 있는 것 같아요 ~!! 구체적인 상황까지 말해주니까 더더더 잘 그려지네요👍

2021-08-07 14:33 UTC, yjksw commented on LEVEL3.md
> +회의 장소가 개인적으로 조금 먼 곳이기도 했고, 날도 유독 더워서 이동하며 힘들었다.<br/>
피카야 집을 더 쾌적하게 했어야지,,

2021-08-07 14:33 UTC, yjksw commented on LEVEL3.md
> +다행히도 팀원들이 이해해줬고 덕분에 체력을 회복할 수 있었다.<br/>
그렇게 조율해가는 시간이 있었죠!! 다니의 글을 읽어보니 저희 나름 우여곡절 겪으면서 잘 적응한 것 같네요 😊

2021-08-07 14:33 UTC, yjksw commented on LEVEL3.md
> +앞으로 남은 기간 동안 어떻게 보내고 싶은지 생각하면, 내가 맡은 일을 잘 처리하고 팀에 더 도움되는 팀원이 되고 싶다. 그리고 팀원들과 더 친해지고 싶다.<br/>
끝없이 친해져야지~~!! 아직 멀었다구요 !! 💓

2021-08-07 14:33 UTC, yjksw commented on LEVEL3.md
> +우리 팀이 유독 워커홀릭 성향이 강해서인지 조금 여유롭게 진행하려 해도 잘 되지 않는 것 같다. 일 얘기 외에도 적당히 잡담하며 팀원들에 대해 더 알아가고 싶다.<br/>
워커홀릭ㅋㅋㅋㅋㅋㅋㅋㅋ 개발 안하고 만나면 뭐 할지 잘 안 그려지긴 하네요ㅋㅋㅋㅋㅋ😅 그래도 갑시다 !! 예카도 여행도 🙌

2021-08-07 16:00 UTC, HyuuunjuKim approved these changes
안녕하세요 다니 엘라입니다 🙋🏻‍♀️

다니의 솔직한 심정이 담긴 글 너무 잘 읽었습니다! 글의 흐름이 너무 자연스러워서 정말 많이 공감하면서 읽었어요!!! 특히나 조금 지쳤던 다니의 상황에서 많이 공감한 것 같아요 ㅎ ㅎ 이제 곧 레벨3가 끝나니 방학에 다시 언능 체력 회복해봐요 우리 😁

따로 수정해주실 부분은 없는 것 같아요 !!! ㅎ ㅎ 다니의 글을 읽으면서 든 제 생각과 공감의 표현들을 조금 달아놨어요 ㅎㅎㅎ 좋은 글 너무 잘 읽었습니다 !

2021-08-07 16:00 UTC, bucketHaneul commented on LEVEL3.md
> +이 시절에는 욕심이 별로 없어 그랬는지도 모른다. 하지만 우테코 프로젝트는 달랐다. 프로젝트에 큰 기여를 하고 싶었고, 그래서 욕심이 많이 났다.<br/>
마자요,,, 저도 예전과 다르게 우테코에서 진행하는 모든 활동에는 많이 기여하고 싶고 그만큼 욕심도 많이 갖게 되는 것 같아요 ㅎ ㅎ

2021-08-07 16:00 UTC, bucketHaneul commented on LEVEL3.md
> +요즘은 이를 방지하기 위해 손을 들고 차례를 기다리거나, 이 의견을 지금 말하는 게 맞는지 다시 한번 점검하는 노력을 하고 있다.<br/>
으하핳하하 저희 팀이랑 비슷하군요!!! 저희 팀도 누군가 얘기를 하고 있으면 줌에서 다들 손을 들고 기다립니다 ㅎㅎ 
이렇게 회의를 진행하니깐 팀원들의 의견을 하나하나 다 차근히 듣게 되더라구요 오히려  회의가 더 수월하게 진행되는 느낌,,?

2021-08-07 16:00 UTC, bucketHaneul commented on LEVEL3.md
> +그래서 1지망으로 지원했다. 유독 경쟁이 치열했던 프로젝트여서 운에 맡겨야 했다. 운이 좋게도 붙었고 팀원이 됐다.<br/>
ㅎㅎㅎ 다니가 하고 싶던 플젝에 들어갔다니!!!!!!!!!!! 괜히 제가 같이 기쁘네용 ❤️

2021-08-07 16:00 UTC, bucketHaneul commented on LEVEL3.md
> +더 이상 지쳐있을 수만은 없었기에 회고 회의 시간에 팀원들에게 한번 말을 해봤다. 웬만하면 비대면으로 진행하고, 진짜 필요한 경우에만 만났으면 좋겠다고 말했다.<br/>
이 세상 사람들은 코로나 전에 다들 어떻게 오프라인으로 모든 일을 진행했을까요,,? 코로나로 저희가 나약해진 걸까요 ㅜ ㅜ

저도 점점 레벨을 진행하면 진행할 수록 체력적으로 너무너무 지쳤던 것 같아요,,,ㅜ ㅜ 여름이 오니깐 아마 더 그러지 않았을까 싶기도 하네요 ㅜ ㅜ 그러다보니 오프라인으로 진행하는 날에 뚜렷한 결과물이 없으면 괜히 실망하게 되고 그러더라구요,,

그래도 결국에는 좋은 방향으로 플젝이 진행 된 것 같네요 ㅎㅎㅎ

2021-08-07 16:00 UTC, bucketHaneul commented on LEVEL3.md
> +우리 팀이 유독 워커홀릭 성향이 강해서인지 조금 여유롭게 진행하려 해도 잘 되지 않는 것 같다. 일 얘기 외에도 적당히 잡담하며 팀원들에 대해 더 알아가고 싶다.<br/>
ㅎㅎㅎ 팀원 모두 워커홀릭이라니 ㅎㅎㅎㅎ 그래서 깃들다 팀의 서비스가 그렇게 진행속도도 빠르게 예쁜 결과물이 나온 거였군요 ㅎㅎ

저랑도 더 알아가는 시간을 가져요 다니 💍

2021-08-08 10:06 UTC, ggyool approved these changes
술술 읽히는 글이었습니다 👍
'나'에 대해 고민하는 과정에서 진정성이 느껴지네요😃
레벨3 막바지라 바쁘실텐데, 화이팅~
바로 Approve 드리겠습니다~~

2021-08-08 10:06 UTC, ggyool commented on LEVEL3.md
> +그 이유는 `Git` 도메인이 탐났다. 개인적으로 가지고 있는 기술적 강점 중 하나가 Git이라 생각하는데, 이와 관련한 프로젝트란 점에서 끌렸다.<br/>
스스로가 생각하는 기술적 강점이 있다는 것이 참 멋있네요 👍

2021-08-08 10:06 UTC, ggyool commented on LEVEL3.md
> +긍정적인 마인드로 바라보는 게 좋기 때문에 전자보다는 후자의 생각을 가지고 프로젝트를 시작하게 됐다.<br/>
레벨3 막바지인데 지금은 어떤 생각인지 궁금하네요!

2021-08-08 10:06 UTC, ggyool commented on LEVEL3.md
> +요즘은 이를 방지하기 위해 손을 들고 차례를 기다리거나, 이 의견을 지금 말하는 게 맞는지 다시 한번 점검하는 노력을 하고 있다.<br/>
노력하는 자세가 멋있네요 🐻
저는 항상 커뮤니케이션 부분이 어렵더라고요 😭

2021-08-08 10:06 UTC, ggyool commented on LEVEL3.md
> +지금 당장 열정을 쏟아붓는 것도 좋지만, 앞으로의 개발 생활을 길 것이기 때문에 천천히 멀리 가는 게 중요하다.<br/>
노련해졌다니 👍

2021-08-08 10:06 UTC, ggyool commented on LEVEL3.md
> +우리 팀이 유독 워커홀릭 성향이 강해서인지 조금 여유롭게 진행하려 해도 잘 되지 않는 것 같다. 일 얘기 외에도 적당히 잡담하며 팀원들에 대해 더 알아가고 싶다.<br/>
개발자들이 모인 그룹이라 어쩔 수 없는 걸까요? 🙃
저도 같은 아쉬움을 느끼네요

2021-08-08 13:05 UTC, sunhpark42 requested changes
안녕하세요 다니~ 리뷰가 늦었습니다 ㅠㅠ 집에 내려와있다 보니 신경을 많이 못썼네요. 글을 읽으면서 다니가 프로젝트를 하면서 느꼈던 감정과 힘듦, 그리고 그걸 어떻게 극복해 나갔는지가 보여서 글 재미있게 읽었어요. 문법적으로 주술 합치 안되는게 있어서 그것만 고쳐주시면 좋을 것 같아요~~~ 남은 기간도 화이팅 빠쌰빠쌰~~

2021-08-08 13:05 UTC, sunhpark42 commented on LEVEL3.md
> +그 이유는 `Git` 도메인이 탐났다. 개인적으로 가지고 있는 기술적 강점 중 하나가 Git이라 생각하는데, 이와 관련한 프로젝트란 점에서 끌렸다.<br/>
```suggestion
그 이유는 `Git` 도메인이 탐났기 때문이다. 개인적으로 가지고 있는 기술적 강점 중 하나가 Git이라 생각하는데, 이와 관련한 프로젝트란 점에서 끌렸다.<br/>
```
```suggestion
 `Git` 도메인이 탐났다. 개인적으로 가지고 있는 기술적 강점 중 하나가 Git이라 생각하는데, 이와 관련한 프로젝트란 점에서 끌렸다.<br/>
```
정도는 어떨까요? 그 이유는 이라는 주어와 탐났다라는 서술어가 잘 안맞는 것 같아요.

다니의 기술적 강점은 깃이군요! 역시 그래서 깃스타 그램이 점점 멋있어지나봐용

2021-08-08 13:05 UTC, sunhpark42 commented on LEVEL3.md
> +백엔드 팀원들이 소위 `개발을 잘한다`고 언급되는 크루들이었기 때문이다.<br/>
ㅋㅋㅋ 맞아요. 다들 너무 잘 해보여서 처음엔 위축됐는데 하다보니 다니가 더 잘하는 것도 있고, 많이 배우는 것도 있었을 거라고 생각해요~!

2021-08-08 13:05 UTC, sunhpark42 commented on LEVEL3.md
> +요즘은 이를 방지하기 위해 손을 들고 차례를 기다리거나, 이 의견을 지금 말하는 게 맞는지 다시 한번 점검하는 노력을 하고 있다.<br/>
의욕과 애정이 넘치면 자연스럽게 그렇게 되는 것 같아요! 커뮤니케이션을 위해 노력하는 다니의 모습 멋집니다~

2021-08-08 13:05 UTC, sunhpark42 commented on LEVEL3.md
> +회의 장소가 개인적으로 조금 먼 곳이기도 했고, 날도 유독 더워서 이동하며 힘들었다.<br/>
피카가 잘못했네 ㅠㅠ

2021-08-08 13:05 UTC, sunhpark42 commented on LEVEL3.md
> +더 이상 지쳐있을 수만은 없었기에 회고 회의 시간에 팀원들에게 한번 말을 해봤다. 웬만하면 비대면으로 진행하고, 진짜 필요한 경우에만 만났으면 좋겠다고 말했다.<br/>
힘든일이 있을 때 팀원들과 자유롭게 공유할 수 있다는 것이 큰 장점인 것 같아요. 체력을 회복할 수 있었다니 다행이네요

2021-08-08 13:05 UTC, sunhpark42 commented on LEVEL3.md
> +우리 팀이 유독 워커홀릭 성향이 강해서인지 조금 여유롭게 진행하려 해도 잘 되지 않는 것 같다. 일 얘기 외에도 적당히 잡담하며 팀원들에 대해 더 알아가고 싶다.<br/>
ㅋㅋㅋㅋㅋ깃들다 팀이 워커홀릭들이긴 하죠.. 술마시고 코드짜는 거 보고 조금 놀랐습니다...

2021-08-08 13:36 UTC, sunhpark42 approved these changes
확인했습니다~ 빠른 피드백 멋졍

2021-08-08 15:05 UTC, bigsaigon333 approved these changes
리뷰가 늦어져 죄송합니다..

다른 분들의 리뷰로 인해 이미 글이 다듬어져있어 제가 딱히 말씀드릴 부분이 없네요 ㅎㅎ..

열정적으로 의견을 제시하고 회의 시간이 길어지는게 저는 열정이 없어서 조용히 있는 것보다 훨씬 좋다고 생각합니다

프로젝트에 대한 애정없이 그냥 해야하는거라고 생각하면서 개발하는 건 너무 아쉽죠...

워라밸을 잘 잡으시면서 롱런하는 개발자로 성장해갑시다~!

2021-08-08 15:05 UTC, bigsaigon333 commented on LEVEL3.md
> +개인적으로 가지고 있는 기술적 강점 중 하나가 Git이라 생각하는데, 이와 관련한 프로젝트란 점에서 끌렸다.<br/>
```suggestion
나의 기술적 강점 중 하나가 Git이라 생각하는데, 이와 관련한 프로젝트란 점에서 끌렸다.<br/>
```

한번 제안드려봅니다 ㅎㅎ

2021-08-08 15:05 UTC, bigsaigon333 commented on LEVEL3.md
> +더 이상 지쳐있을 수만은 없었기에 회고 회의 시간에 팀원들에게 한번 말을 해봤다. 웬만하면 비대면으로 진행하고, 진짜 필요한 경우에만 만났으면 좋겠다고 말했다.<br/>
```suggestion
매일 만났지만 회의가 알차지 못한 날도 있었고, 이런저런 이유로 지금 가고 있는 방향이 맞나 혼란스러웠다. 이러면서 자연스레 지쳤던 것 같다.<br/>
레벨 1에는 이렇게까지 즐거워도 괜찮나, 평소에도 텐션이 높았지만 요즘 유독 높은 것 같다 싶었는데, 레벨 3에는 점점 지쳐가는 모습이 보였다.<br/>
더 이상 지쳐있을 수만은 없기에 회고 시간에 팀원들에게 한번 제안해보았다. 웬만하면 비대면으로 진행하고, 진짜 필요한 경우에만 만났으면 좋겠다고 말했다.<br/>
```

회고도 회의에 포함되나요..? (사실 저희 팀 내에서도 의견이 갈리는 부분 중 하나입니다...)

`말했다` 라는 표현이 중복되어서 한번 이렇게 제안드려봅니다

2021-08-08 15:42 UTC, da-nyee commented on LEVEL3.md
> +개인적으로 가지고 있는 기술적 강점 중 하나가 Git이라 생각하는데, 이와 관련한 프로젝트란 점에서 끌렸다.<br/>
`나`로 시작하는 문장은 최대한 지양하고 싶어서 `개인적인`으로 변경하겠습니다!

2021-08-08 15:44 UTC, da-nyee commented on LEVEL3.md
> +더 이상 지쳐있을 수만은 없었기에 회고 회의 시간에 팀원들에게 한번 말을 해봤다. 웬만하면 비대면으로 진행하고, 진짜 필요한 경우에만 만났으면 좋겠다고 말했다.<br/>
저희 팀은 회고도 회의로 간주하고 있습니다 ㅎㅎ

2021-08-08 16:18 UTC, yungo1846 approved these changes

2021-08-08 23:26 UTC, sihyung92 commented
항상 열심히 하는 다니~~ 파이팅 하고 있다는 소식을 전해들은거 같은데🔥🔥
번아웃 되지않게 컨디션 조절 잘하길 바라
하루이틀 할것도 아니니까! 팀원들과 조잘조잘 재밌는 얘기도 해가며 일도 열심히 쉼도 열심히 하는 다니되길..💪

2021-10-18 04:48 UTC, merged