[레벨 3 글쓰기 미션] 시드(김현식) 미션 제출합니다.
woowacourse/woowa-writing-3 pull request #219
Opened 2021-08-02 14:50 UTC by hsik0225

2021-08-03 07:35 UTC, Hyeon9mak commented on Level3.md
> +안 하려던 방법으로 말을 하려고 하니 힘들었다. 하지만 최대한 내 주장과 근거, 예시 등을 가지고 이야기하려고 노력했다. 지금은 어색하지만 언젠가는 무의식적으로도 논리적으로 말할 수 있게 되길 바란다.
면접에서 시드의 엄청난 모습을 보았쥬

2021-08-05 04:15 UTC, 365kim commented on Level3.md
> +코드봐줘 팀은 현재 Jenkins를 이용하여 CI/CD 를 진행하고 있다. 이 Jenkins 작업은 같은 팀원인 알리가 담당해주었다. 알리는 맡은 일을 진행하면서 동시에 문서화 작업까지 해주었다. Jenkins를 어떻게 설치하는지, 자주 사용하는 설정은 무엇이고, 어떻게 배포해야 하는지 등을 정리해주었다.
이어지는 문장들을 읽고 추론이 가능하지만, 아래와 같이 `코드봐줘 팀이 시드의 팀이라는 내용`이 들어가면 조금 더 매끄럽게 읽을 수도 있을 것 같습니당 :)
```suggestion
내가 속해 있는 코드봐줘 팀은 현재 Jenkins를 이용하여 CI/CD 를 진행하고 있다. 이 Jenkins 작업은 같은 팀원인 알리가 담당해주었다. 알리는 맡은 일을 진행하면서 동시에 문서화 작업까지 해주었다. Jenkins를 어떻게 설치하는지, 자주 사용하는 설정은 무엇이고, 어떻게 배포해야 하는지 등을 정리해주었다.
```

2021-08-05 04:36 UTC, 365kim commented on Level3.md
> +대학생 시절 때까지는 혼자 공부하고, 시험을 봤기 때문에, 내 생각을 논리적으로 말할 필요가 없었다. 하지만 팀 프로젝트는 달랐다. 사람은 100이면 100 다 모두 다른 생각이 있다. 저마다의 생각이 있는 사람들이 모여 팀 프로젝트를 하게 되니, 자연스레 의견 충돌이 일어났다. 나와 의견이 다른 팀원을 설득시키기 위해서 논리적으로 말해야 했고, 이번 팀
요 부분을 읽고나서 각 문장이 함축적 또는 축약적 편이라는 인상을 받았어요. 이게 시드 문체만의 매력이라고 생각하지만 아래와 같이 조금 더 풀어서 작성하는 방법도 있을 것 같아요 :) 위에 남겼던 코멘트나 요것도 그냥 가벼운 제안으로 봐주시면 감사하겠습니당.

```suggestion
대학생 시절 때까지는 혼자 공부한 내용을 필기시험을 통해 보여주는 것으로 충분했다. 그래서 내 생각을 논리적인 말로 정리해서 전달해야 하는 경우는 많지 않았다. 하지만 우아한테크코스의 팀 프로젝트는 달랐다. 사람은 100이면 100 모두 다 다른 생각이 있다. 저마다의 생각이 있는 사람들이 모여 팀 프로젝트를 하게 되니, 자연스레 의견 충돌이 일어났다. 나와 의견이 다른 팀원을 설득시키기 위해서 논리적으로 말해야 했고, 이번 팀 프로젝트에서 그 연습을 했다. 
```

2021-08-05 04:40 UTC, 365kim commented on Level3.md
> +팀 프로젝트를 경험하기 전까지 여러 명이 같이 협업한다는 것에 대해서 많이 부정적이었다. 사람이 적으면 적을수록 의사 결정도 빨리 되고, 여러 인간관계에 대해 스트레스를 받지 않기 때문에 개발 품질이 더 좋아진다고 생각했기 때문이다. 하지만 그것은 정말 좋은 팀원을 만나보지 못했기 때문이었다고 지금은 생각한다. 앞으로 어떤 프로젝트를 하게 되든 현재와 같
이 문장 처음에서 지칭해주신 `팀 프로젝트`는 우아한테크코스의 팀프로젝트를 말씀하시는 걸까요, 아니면 시드가 경험하신 모든 팀프로젝트를 말씀하시는 걸까용? 글을 읽는 동안 `아, 우테코의 팀프로젝트가 생애 첫 팀플이셨던건가` `아 아닌가` 하면서 혼자 조금 헷갈렸었거든용 ㅎㅎ 제가 캐치를 잘 못해서 그런거지만 👉👈 글에서 그런 부분이 조금 더 명확하게 표현되면 어떨까 싶습니당 :) 그리고 만약 후자처럼 통틀어서 첫 팀프로젝트 를 경험하신거라면 그것도 굉장히 기념비적인 의미가 있어서 글에 표현이 되면 좋겠다는 생각도 들었습니당 👍

2021-08-05 04:44 UTC, 365kim commented on Level3.md
> +### 소통
이 후에 이어지는 내용을 다 읽고 나니, `소통` 대신에 `논리적으로 말하는 연습` 과 같은 소제목은 어떨까하는 생각이 살포시 들었습니당. 또는 이 앞의 소제목 `지식 공유를 하자`과 라임을 맞춰서 `논리적으로 말하자` 같은 제목도 한번 고려해주시면 감사하겠습니당 👍

2021-08-05 04:45 UTC, 365kim commented on Level3.md
> +### 지식 공유를 하자
별건 아니지만서도 요렇게 바꿔보는 것은 어떨까용?
```suggestion
### 지식을 공유하자
```

2021-08-05 04:49 UTC, 365kim requested changes
시드 안녕하세요!
글쓰기 미션에서 같은 조로 매칭된 덕분에 인사드릴 기회가 생긴 것 같네용 ㅎㅎ

우선 글 잘 읽었습니당!
시드가 이번 팀 프로젝트를 진행하시면서 느꼈던 점들이 진솔하게 담겨있어서 재밌게 잘봤습니당 👍

몇 가지 코멘트를 남겼는데 제가 미처 제대로 파악하지 못하고 잘못 얘기한 부분이 있을 수 있으니 가볍게 봐주시면 감사하겠습니다. 코멘트 확인해주시면 바로 approve 할게요!
수고하셨습니다. 👏👏👏👏

2021-08-05 12:45 UTC, yujo11 reviewed
안녕하세요 시드!

얼굴 본 지도 오래 됐는데 글로나마 이렇게 만나니 반갑네요ㅎㅎ

시드가 팀 프로젝트를 진행하기 전, 후로 바뀐 생각들이 저와 비슷한 부분이 있어서 공감하면서 읽을 수 있었어요!

코멘트 하나 남겼는데 확인해주시면 감사하겠습니다!

좋은 글 감사해요 시드 고생하셨어요! 👍👍👍

2021-08-05 12:45 UTC, yujo11 commented on Level3.md
> +그 후, 집에서 모여 알리가 한 명씩 천천히 Jenkins 설치 및 설정에 대해 가르쳐주었다. 알리만 알고 있었던 Jenkins 에 대한 지식을 팀원들에게 공유해주니 다들 처음 해보는 Jenkins임에도 불구하고 어렵지 않게 진행할 수 있었다. 알리에게 설명을 듣고 나서, 우리 프로젝트가 어떻게 Jenkins 를 사용하고 있는지, 우리 서비스의 인프라 구
지식을 한 명, 한 명에게  공유하다니 알리 멋지네요! 👍👍👍

2021-08-05 12:45 UTC, yujo11 commented on Level3.md
> +한 명이 마주한 이슈 및 해결 방법 등을 정리 및 팀원에게 전파하니, 다른 팀원들은 해당 문제를 쉽게 해결할 수 있었다. 한 사람의 노력이 다른 모든 팀원에게 영향을 미치는 것을 보고, 앞으로도 꼭 문서화를 통한 지식 공유를 하자고 다짐했다.
크 👍👍👍

2021-08-05 12:45 UTC, yujo11 commented on Level3.md
> +안 하려던 방법으로 말을 하려고 하니 힘들었다. 하지만 최대한 내 주장과 근거, 예시 등을 가지고 이야기하려고 노력했다. 지금은 어색하지만 언젠가는 무의식적으로도 논리적으로 말할 수 있게 되길 바란다.
```suggestion
평소와 달리 논리적으로 말을 하려고 하니 힘들었다. 하지만 최대한 내 주장과 근거, 예시 등을 가지고 이야기하려고 노력했다. 지금은 어색하지만 언젠가는 무의식적으로도 논리적으로 말할 수 있게 되길 바란다.
```

이런 식으로 '안 하려던 방법'이 어떤 것인지 좀 더 자세히 적어주면 더 자연스럽게 읽을 수 있을거 같아요!

2021-08-05 12:45 UTC, yujo11 commented on Level3.md
> +팀 프로젝트를 경험하기 전까지 여러 명이 같이 협업한다는 것에 대해서 많이 부정적이었다. 사람이 적으면 적을수록 의사 결정도 빨리 되고, 여러 인간관계에 대해 스트레스를 받지 않기 때문에 개발 품질이 더 좋아진다고 생각했기 때문이다. 하지만 그것은 정말 좋은 팀원을 만나보지 못했기 때문이었다고 지금은 생각한다. 앞으로 어떤 프로젝트를 하게 되든 현재와 같
정말 좋은 팀원들과 함께 하고 있군요 시드! 멋지네요!! 👍👍👍

2021-08-07 05:26 UTC, sakjung approved these changes
안녕하세요 시드 삭정입니다 ㅎㅎ
좋은 팀원들을 만나서 알차게 개발을 하고 계시는 게 드러나 보이는 글이라서 좋았습니다.
글 잘 읽고 갑니다!

2021-08-07 05:26 UTC, sakjung commented on Level3.md
> +한 명이 마주한 이슈 및 해결 방법 등을 정리 및 팀원에게 전파하니, 다른 팀원들은 해당 문제를 쉽게 해결할 수 있었다. 한 사람의 노력이 다른 모든 팀원에게 영향을 미치는 것을 보고, 앞으로도 꼭 문서화를 통한 지식 공유를 하자고 다짐했다.
정말 지식 공유는 중요한 것 같습니다 ㅎㅎ

2021-08-07 05:26 UTC, sakjung commented on Level3.md
> +안 하려던 방법으로 말을 하려고 하니 힘들었다. 하지만 최대한 내 주장과 근거, 예시 등을 가지고 이야기하려고 노력했다. 지금은 어색하지만 언젠가는 무의식적으로도 논리적으로 말할 수 있게 되길 바란다.
저도 제 주장을 말할 때 매끄럽게 말하지 못하는 편이라서 공감이 많이 가네요...
같이 열심히 연습해봐요 ㅎㅎ

2021-08-08 04:22 UTC, DWL5 approved these changes
팀프로젝트를 하면서 좋은 팀원들은 만나 시드에 생각이 변화하게 된게 인상 깊네요..
팀프로젝트에서는 사람이 제일 중요한 것 같아요!!
글 잘 읽었습니다~

피드백 남겼는데 확인 부탁드리고 반영은 하셔도 되고 하지 않으셔도 됩니다!! 피드백일 뿐이에욥!
approve 드리겠습니다~

2021-08-08 04:22 UTC, DWL5 commented on Level3.md
> +### 지식 공유를 하자
여럿이서 라는 말이 중복되는 것 같아요 앞의 두 문장 중 에서 하나만 빼도 괜찮을 것 같아요!

2021-08-08 04:22 UTC, DWL5 commented on Level3.md
> +코드봐줘 팀은 현재 Jenkins를 이용하여 CI/CD 를 진행하고 있다. 이 Jenkins 작업은 같은 팀원인 알리가 담당해주었다. 알리는 맡은 일을 진행하면서 동시에 문서화 작업까지 해주었다. Jenkins를 어떻게 설치하는지, 자주 사용하는 설정은 무엇이고, 어떻게 배포해야 하는지 등을 정리해주었다.
오.. 알리 대단하네요

2021-08-08 04:22 UTC, DWL5 commented on Level3.md
> +한 명이 마주한 이슈 및 해결 방법 등을 정리 및 팀원에게 전파하니, 다른 팀원들은 해당 문제를 쉽게 해결할 수 있었다. 한 사람의 노력이 다른 모든 팀원에게 영향을 미치는 것을 보고, 앞으로도 꼭 문서화를 통한 지식 공유를 하자고 다짐했다.
팀플에서 분업을 하다보니 지식 공유 정말 중요한 것 같아요 ㅜ

2021-08-08 04:22 UTC, DWL5 commented on Level3.md
> +안 하려던 방법으로 말을 하려고 하니 힘들었다. 하지만 최대한 내 주장과 근거, 예시 등을 가지고 이야기하려고 노력했다. 지금은 어색하지만 언젠가는 무의식적으로도 논리적으로 말할 수 있게 되길 바란다.
궁금하네요...

2021-08-08 05:33 UTC, tributetothemoon reviewed
안녕하세요 시드! 김김입니다. 글쓰기 미션에서는 또 뵙네요~

현구막이 면접에서 시드의 엄청난 모습을 보았다고 하는데...상당한 능력자이신 것 같군요...호기심이 돋아요.

논리적으로 말하기 위해 노력한다고 하셨지만 엄살 부리시는 거 아니신가 모르겠네요😎.

몇 가지 코멘트를 남겨보았습니다. 다른 분들의 좋은 리뷰가 있으니, 같이 진행해주시면 좋을 것 같아요!!

2021-08-08 05:33 UTC, tributetothemoon commented on Level3.md
> +그 후, 집에서 모여 알리가 한 명씩 천천히 Jenkins 설치 및 설정에 대해 가르쳐주었다. 알리만 알고 있었던 Jenkins 에 대한 지식을 팀원들에게 공유해주니 다들 처음 해보는 Jenkins임에도 불구하고 어렵지 않게 진행할 수 있었다. 알리에게 설명을 듣고 나서, 우리 프로젝트가 어떻게 Jenkins 를 사용하고 있는지, 우리 서비스의 인프라 구
서로 알려주는 문화가 정말 보기 좋네요!

2021-08-08 05:33 UTC, tributetothemoon commented on Level3.md
> +### 소통
좋은 의견이에요 하루! 숟가락 얹는 것 같지만, 다시 보니 소제목을 스치듯 보고 지나가버렸네요.
하루의 의견처럼 소제목에서 주제가 더 명확히 드러나게 하거나, 아니면 아싸리 모호한듯 호기심이 갈듯한 다소 문학적이면서 신선한 표현을 써주면 더 좋겠다는 생각이 들었습니다.

2021-08-08 05:33 UTC, tributetothemoon commented on Level3.md
> +대학생 시절 때까지는 혼자 공부하고, 시험을 봤기 때문에, 내 생각을 논리적으로 말할 필요가 없었다. 하지만 팀 프로젝트는 달랐다. 사람은 100이면 100 다 모두 다른 생각이 있다. 저마다의 생각이 있는 사람들이 모여 팀 프로젝트를 하게 되니, 자연스레 의견 충돌이 일어났다. 나와 의견이 다른 팀원을 설득시키기 위해서 논리적으로 말해야 했고, 이번 팀
전반적으로 글에 쉼표가 많고 호흡이 끊긴다는 느낌을 받았어요. 이 단락을 보니 더욱 그러한 느낌이 들어요😢. 혹시나 리뷰를 반영하면서, 전반적으로 쳐내는 작업이 있으면 좋겠다는 생각이 들었습니다!

2021-08-08 05:33 UTC, tributetothemoon commented on Level3.md
> +안 하려던 방법으로 말을 하려고 하니 힘들었다. 하지만 최대한 내 주장과 근거, 예시 등을 가지고 이야기하려고 노력했다. 지금은 어색하지만 언젠가는 무의식적으로도 논리적으로 말할 수 있게 되길 바란다.
> 면접에서 시드의 엄청난 모습을 보았쥬

궁금증 폭발...

2021-08-08 05:33 UTC, tributetothemoon commented on Level3.md
> +팀 프로젝트를 경험하기 전까지 여러 명이 같이 협업한다는 것에 대해서 많이 부정적이었다. 사람이 적으면 적을수록 의사 결정도 빨리 되고, 여러 인간관계에 대해 스트레스를 받지 않기 때문에 개발 품질이 더 좋아진다고 생각했기 때문이다. 하지만 그것은 정말 좋은 팀원을 만나보지 못했기 때문이었다고 지금은 생각한다. 앞으로 어떤 프로젝트를 하게 되든 현재와 같
```suggestion
팀 프로젝트를 경험하기 전까지 여러 명이 같이 협업한다는 것에 대해서 많이 부정적이었다. 사람이 적으면 적을수록 의사 결정도 빨리 되고, 여러 인간관계에 대해 스트레스를 받지 않기 때문에 개발 품질이 더 좋아진다고 생각했기 때문이다. 하지만 그것은 정말 좋은 팀원을 만나보지 못했기 때문이었다고 지금은 생각한다. 앞으로 어떤 프로젝트를 하게 되든 '코드봐줘'와 같은 좋은 팀원들과 분위기 속에서 진행하고 싶다.
```

'좋은 팀원을 만나보니 여러명이 같이 하는 것도 좋더라' 가 핵심인 것 같은 느낌을 받았네요. 아니라면 그대로 진행하셔도 좋을 것 같아요!

2021-08-08 06:01 UTC, 2SOOY approved these changes
안녕하세요 시드 :)

근로 때 종종 뵙고 글로 뵈니 더욱 반갑네용 ㅎㅎ

프로젝트를 진행하면서 지식을 적극적으로 공유하는 팀원을 만나 새로운 다짐을 하게된 점
초기 여럿이 같이 하는 경험에 대한 부정적인 생각에서 좋은 팀원들을 만나 생각이 변화했던 과정을 잘 표현해주신 것 같아요 :) 

앞으로 남은 기간 동안 프로젝트 파이팅입니다 ✊✊✊ 
(+시드 면접보는 모습 보고 싶네용,,,ㅎㅎ)

2021-08-08 06:01 UTC, 2SOOY commented on Level3.md
> +한 명이 마주한 이슈 및 해결 방법 등을 정리 및 팀원에게 전파하니, 다른 팀원들은 해당 문제를 쉽게 해결할 수 있었다. 한 사람의 노력이 다른 모든 팀원에게 영향을 미치는 것을 보고, 앞으로도 꼭 문서화를 통한 지식 공유를 하자고 다짐했다.
지식 공유 맨날 해야만 한다는 생각만 하고,, 실천하기 어렵네요 😢
`시드의 문서화` 기대하겠습니다 :)

2021-08-08 06:01 UTC, 2SOOY commented on Level3.md
> +팀 프로젝트를 경험하기 전까지 여러 명이 같이 협업한다는 것에 대해서 많이 부정적이었다. 사람이 적으면 적을수록 의사 결정도 빨리 되고, 여러 인간관계에 대해 스트레스를 받지 않기 때문에 개발 품질이 더 좋아진다고 생각했기 때문이다. 하지만 그것은 정말 좋은 팀원을 만나보지 못했기 때문이었다고 지금은 생각한다. 앞으로 어떤 프로젝트를 하게 되든 현재와 같
팀 프로젝트에 대해 부정적인 생각에서 좋은 팀원들을 만나고 생각이 변화한 점이 인상 깊네요 👍👍👍 멋져용 ㅎㅎ

2021-08-08 13:21 UTC, hsik0225 commented on Level3.md
> +코드봐줘 팀은 현재 Jenkins를 이용하여 CI/CD 를 진행하고 있다. 이 Jenkins 작업은 같은 팀원인 알리가 담당해주었다. 알리는 맡은 일을 진행하면서 동시에 문서화 작업까지 해주었다. Jenkins를 어떻게 설치하는지, 자주 사용하는 설정은 무엇이고, 어떻게 배포해야 하는지 등을 정리해주었다.
확실히 설명해주는게 `코드봐줘` 팀에 대한 이야기를 전개하는데 좋을 것 같네요.
수정하겠습니다!

2021-08-08 13:23 UTC, hsik0225 commented on Level3.md
> +대학생 시절 때까지는 혼자 공부하고, 시험을 봤기 때문에, 내 생각을 논리적으로 말할 필요가 없었다. 하지만 팀 프로젝트는 달랐다. 사람은 100이면 100 다 모두 다른 생각이 있다. 저마다의 생각이 있는 사람들이 모여 팀 프로젝트를 하게 되니, 자연스레 의견 충돌이 일어났다. 나와 의견이 다른 팀원을 설득시키기 위해서 논리적으로 말해야 했고, 이번 팀
글을 짧게 짧게 쓰려고 하다보니 글에 설명이 부족하고, 쉼표가 많이 들어가게 되어버렸네요.
두 분의 의견대로 고쳐보겠습니다!

2021-08-08 13:31 UTC, hsik0225 commented on Level3.md
> +안 하려던 방법으로 말을 하려고 하니 힘들었다. 하지만 최대한 내 주장과 근거, 예시 등을 가지고 이야기하려고 노력했다. 지금은 어색하지만 언젠가는 무의식적으로도 논리적으로 말할 수 있게 되길 바란다.
앞에서 `논리적`이라는 단어를 많이 사용한 것 같아 조금 바꿔보려고 했는데 그것이 오히려 읽는데 방해가 되었나보네요 😄
수정했습니다!

2021-08-08 14:37 UTC, 365kim approved these changes
시드, 피드백 반영해주셔서 감사해요! 고생하셨습니다! 👏👏👏
남은 레벨3 마지막까지 빠이팅이에요~~!! 😆

2021-08-09 03:13 UTC, tributetothemoon approved these changes
반영하느라 고생하셨습니다!! 레벨 3 파이팅입니다~

2021-08-09 07:53 UTC, yujo11 approved these changes
고생하셨어요!! 👍👍👍

2021-10-18 05:55 UTC, kang-hyungu approved these changes
이번 팀 프로젝트를 통해 협업에 대한 생각이 긍정적으로 바뀌었다니 좋은 경험하셨네요
저도 시드의 문서화 기대하겠습니다 :)
좋은 글 잘 읽었습니다

2021-10-18 05:55 UTC, merged