[레벨 3 글쓰기 미션] 나봄(윤보민) 미션 제출합니다.
woowacourse/woowa-writing-3 pull request #224
Opened 2021-08-02 14:58 UTC by qhals321

여러분 안녕하신가요... 늦었네요.. 죄송합니당!!!
이번 팀 프로젝트를 진행하며 느꼈던 점을 적어봤어요!! 모두 잘 부탁드립니당!!!!

그루밍, 포츈, 와일더, 크로플, 인치, 파노 사랑해유!!!

2021-08-03 08:28 UTC, Hyeon9mak commented on blob/level3.md
> +윈도우... 아니 발표천재 '크로플' <br>
QA가 가능한 노트북...

2021-08-03 08:28 UTC, Hyeon9mak commented on blob/level3.md
> +이 말에 많은 위로는 물론이고 생각에 잠기게 되었다. 이런 글귀가 생각났다. '꼰대가 될 거면 멋진 꼰대가 되라'. 그래, '이왕 고집있을 거 좋은 고집을 갖자'.
👍

2021-08-03 10:46 UTC, ddongule approved these changes
안녕하세요 나봄~~!!!! 
그루밍입니다~~!! 💫💫💫
팀 프로젝트를 하면서 저도 비슷한 고민들을 했던 것 같아서 공감하면서 재밌게 읽었네요~~!!
크게 고쳐야 할 부분이 보이질 않아 Approve 드립니다~~!!!
같이 남은 프로젝트도 화이팅해요오~~!!

2021-08-03 10:46 UTC, ddongule commented on blob/level3.md
> +정말 팀원들이 너무나 좋다. 우리는 매일 회고를 한다. 그리고 매 주마다 일주일동안 느낀 점을 회고한다. 협업의 대가 '웨지'의 추천으로 KPT 회고를 진행하고 있다. 이 회고를 통해 나는 매 주마다 성장하는 우리의 팀을 보며 정말 감동을 받는다. 혼자 성장하는 것보다 뭔가 더 뭉클한 마음이 든다.
저희도 매일 회고하는데, 회고 정말 죠은 것 같아욥!!!!! 👍

2021-08-03 16:59 UTC, lns13301 reviewed
안녕하세요. 나봄! 🌱
재미있게 글을 읽었습니다.
내용상 건드릴 부분은 안보이네요. 👏
나봄의 색이 잘 묻어난 글이라고 생각합니다.
맞춤법 관련해서 몇 가지 코멘트 드렸으니 확인해 보시고 리뷰 요청 주세요. 👻

2021-08-03 16:59 UTC, lns13301 commented on blob/level3.md
> +매번 팀 회의가 끝나면 후회의 시간이 찾아왔다. '내가 너무 고집부린 것 같다..', 고집은 많으면서 소심한 나... 그러다 최근에 팀원들이 내게 이런 말을 해줬다. "고집이 있어도 논리있는 고집이어서 괜찮아!".
```suggestion
매번 팀 회의가 끝나면 후회의 시간이 찾아왔다. '내가 너무 고집부린 것 같다..', 고집은 많으면서 소심한 나... 그러다 최근에 팀원들이 내게 이런 말을 해줬다. "고집이 있어도 논리 있는 고집이어서 괜찮아!".
```

논리있는 고집 제가 잘 알죠 😉

2021-08-03 16:59 UTC, lns13301 commented on blob/level3.md
> +정말 팀원들이 너무나 좋다. 우리는 매일 회고를 한다. 그리고 매 주마다 일주일동안 느낀 점을 회고한다. 협업의 대가 '웨지'의 추천으로 KPT 회고를 진행하고 있다. 이 회고를 통해 나는 매 주마다 성장하는 우리의 팀을 보며 정말 감동을 받는다. 혼자 성장하는 것보다 뭔가 더 뭉클한 마음이 든다.
```suggestion
정말 팀원들이 너무나 좋다. 우리는 매일 회고를 한다. 그리고 주마다 일주일 동안 느낀 점을 회고한다. 협업의 대가 '웨지'의 추천으로 KPT 회고를 진행하고 있다. 이 회고를 통해 나는 주마다 성장하는 우리의 팀을 보며 정말 감동을 받는다. 혼자 성장하는 것보다 뭔가 더 뭉클한 마음이 든다.
```

2021-08-03 16:59 UTC, lns13301 commented on blob/level3.md
> +# 팀프로젝트가 나에게 남긴 것
```suggestion
# 팀 프로젝트가 나에게 남긴 것
```

2021-08-03 16:59 UTC, lns13301 commented on blob/level3.md
> +### 고집있는 나
```suggestion
### 고집 있는 나
```

2021-08-03 16:59 UTC, lns13301 commented on blob/level3.md
> +나에게 팀 프로젝트는 아예 처음이었다. 과연 내가 팀 프로젝트를 잘 할 수 있을까? 라는 고민이 많았다. 고민이 생길 수 밖에 없었다. 왜냐하면 나는 내가 고집이 많은 것도 스스로 알고 있고 혼자 하는 것을 좋아하는 성향을 가지고 있기 때문이다.
```suggestion
나에게 팀 프로젝트는 아예 처음이었다. 과연 내가 팀 프로젝트를 잘 할 수 있을까? 라는 고민이 많았다. 고민이 생길 수밖에 없었다. 왜냐하면 나는 내가 고집이 많은 것도 스스로 알고 있고 혼자 하는 것을 좋아하는 성향을 가지고 있기 때문이다.
```

2021-08-03 16:59 UTC, lns13301 commented on blob/level3.md
> +이 말에 많은 위로는 물론이고 생각에 잠기게 되었다. 이런 글귀가 생각났다. '꼰대가 될 거면 멋진 꼰대가 되라'. 그래, '이왕 고집있을 거 좋은 고집을 갖자'.
```suggestion
이 말에 많은 위로는 물론이고 생각에 잠기게 되었다. 이런 글귀가 생각났다. '꼰대가 될 거면 멋진 꼰대가 돼라'. 그래, '이왕 고집 있을 거 좋은 고집을 갖자'.
```

2021-08-03 16:59 UTC, lns13301 commented on blob/level3.md
> +장난끼와 스마트함을 같이 가진 '서니', <br>
```suggestion
장난기와 스마트함을 같이 가진 '서니', <br>
```

2021-08-03 16:59 UTC, lns13301 commented on blob/level3.md
> +윈도우... 아니 발표천재 '크로플' <br>
척척박사 스윗크루 '나봄' 😁

2021-08-03 16:59 UTC, lns13301 commented on blob/level3.md
> +몸은 연약하지만 개발만큼은 풀스택 '소롱', <br>
```suggestion
몸은 연약하지만, 개발만큼은 풀스택 '소롱', <br>
```

2021-08-03 16:59 UTC, lns13301 commented on blob/level3.md
> +함께이기에 배운 것들이 있다. 혼자 개발하는 것보다 훨씬 복잡했다. 서로 작성한 코드가 프로젝트에 각각 잘 적용되야 했다. 이를 위해 깃 전략이 필수였다. 이를 통해 깃에 대해 조금 더 알 수 있는 시간이 되었다.
```suggestion
함께이기에 배운 것들이 있다. 혼자 개발하는 것보다 훨씬 복잡했다. 서로 작성한 코드가 프로젝트에 각각 잘 적용돼야 했다. 이를 위해 깃 전략이 필수였다. 이를 통해 깃에 대해 조금 더 알 수 있는 시간이 되었다.
```

2021-08-03 16:59 UTC, lns13301 commented on blob/level3.md
> +서로 머리를 맞대어 구조나 배포 등을 생각하면서 혼자 생각할 수 없던 부분을 채워나가게 되었다. 아.. 집단지성이라는 것이 이런거구나! 특히, 첫 배포날 우리의 결과물이 보여질 때 정말 소름이 돋았다. 우리가 너무 멋졌다!
```suggestion
서로 머리를 맞대어 구조나 배포 등을 생각하면서 혼자 생각할 수 없던 부분을 채워나가게 되었다. 아.. 집단지성이라는 것이 이런 거구나! 특히, 첫 배포 날 우리의 결과물이 보여질 때 정말 소름이 돋았다. 우리가 너무 멋졌다!
```

2021-08-03 16:59 UTC, lns13301 commented on blob/level3.md
> +시간이 가면 갈 수록 이 프로젝트는 끝이 날 수 있다는 생각에 마음이 섭섭할 정도로 현재 팀 프로젝트가 너무나 행복하다. 이 추억은 평생 갈 듯 하다. 남은 기간도 아자아자! 파이팅.
```suggestion
시간이 가면 갈수록 이 프로젝트는 끝이 날 수 있다는 생각에 마음이 섭섭할 정도로 현재 팀 프로젝트가 너무나 행복하다. 이 추억은 평생 갈 듯하다. 남은 기간도 아자아자! 파이팅.
```

2021-08-04 14:29 UTC, knae11 commented
나봄같은 글이다! 나봄 얼굴 까먹을뻔 했는데 다시 생각나는 글이네

2021-08-05 14:39 UTC, jho2301 reviewed
안녕하세요 나봄 ㅎㅎ
나봄이 프로젝트를 통해 배운 것과 팀을 얼마나 좋아하는지 엿볼 수 있어서 저도 기분이 좋아지는 글이 었습니다!
간단하게 의견 남겨봤어요. 좀만 더 힘냅시다~

2021-08-05 14:39 UTC, jho2301 commented on blob/level3.md
> +매번 팀 회의가 끝나면 후회의 시간이 찾아왔다. '내가 너무 고집부린 것 같다..', 고집은 많으면서 소심한 나... 그러다 최근에 팀원들이 내게 이런 말을 해줬다. "고집이 있어도 논리있는 고집이어서 괜찮아!".
저도 고집 좀 부리는데, 프로젝트를 하면서 어디가 적정선인지 찾아가고 있는 것 같아요 ㅋㅋ

2021-08-05 14:39 UTC, jho2301 commented on blob/level3.md
> +정말 팀원들이 너무나 좋다. 우리는 매일 회고를 한다. 그리고 매 주마다 일주일동안 느낀 점을 회고한다. 협업의 대가 '웨지'의 추천으로 KPT 회고를 진행하고 있다. 이 회고를 통해 나는 매 주마다 성장하는 우리의 팀을 보며 정말 감동을 받는다. 혼자 성장하는 것보다 뭔가 더 뭉클한 마음이 든다.
kpt가 어떤 방식인지 궁금하네요 간단하게 한 줄 정도로 적어주면 어떨까요??

2021-08-05 14:42 UTC, unluckyjung approved these changes
첫 팀플이 우테코에서의 팀플이라니..  
부러우면서도, 한편으로는 걱정이되네요.  
팀원들의 기준치가 너무 높아져서, 다른 집단의 인원들과의 팀플에서 살짝 고생하실수도 있을꺼 같다는, 기인지우를 하고 갑니다 ㅋㅋ!

2021-08-05 14:42 UTC, unluckyjung commented on blob/level3.md
> +나에게 팀 프로젝트는 아예 처음이었다. 과연 내가 팀 프로젝트를 잘 할 수 있을까? 라는 고민이 많았다. 고민이 생길 수 밖에 없었다. 왜냐하면 나는 내가 고집이 많은 것도 스스로 알고 있고 혼자 하는 것을 좋아하는 성향을 가지고 있기 때문이다.
```suggestion
나에게 팀 프로젝트는 아예 처음이었다. 과연 내가 팀 프로젝트를 잘 할 수 있을까? 라는 고민이 많았다. 고민이 생길 수 밖에 없었다. 왜냐하면, 나는 내가 고집이 강한 것도 스스로 알고 있고 혼자 하는 것을 좋아하는 성향을 가지고 있기 때문이다.
```

고집이 **많다** 보다는, **강하다**가 어울리다고 생각하는데, 좋은쪽 선택하심 되겠어요!

2021-08-05 14:42 UTC, unluckyjung commented on blob/level3.md
> +이 말에 많은 위로는 물론이고 생각에 잠기게 되었다. 이런 글귀가 생각났다. '꼰대가 될 거면 멋진 꼰대가 되라'. 그래, '이왕 고집있을 거 좋은 고집을 갖자'.
```suggestion
이 말에 많은 위로는 물론이고 생각에 잠기게 되었다. 이런 글귀가 생각났다. '꼰대가 될 거면 멋진 꼰대가 되라'. 그래, '이왕 고집 있을 거 좋은 고집을 갖자'.
```

2021-08-05 14:42 UTC, unluckyjung commented on blob/level3.md
> +시간이 가면 갈 수록 이 프로젝트는 끝이 날 수 있다는 생각에 마음이 섭섭할 정도로 현재 팀 프로젝트가 너무나 행복하다. 이 추억은 평생 갈 듯 하다. 남은 기간도 아자아자! 파이팅.
오호.. 이쪽은 우테코 기간 끝나면 프로젝트도 같이 끝나나요 ㅋㅋ?? 😈

2021-08-05 14:42 UTC, unluckyjung commented on blob/level3.md
> +나에게 팀 프로젝트는 아예 처음이었다. 과연 내가 팀 프로젝트를 잘 할 수 있을까? 라는 고민이 많았다. 고민이 생길 수 밖에 없었다. 왜냐하면 나는 내가 고집이 많은 것도 스스로 알고 있고 혼자 하는 것을 좋아하는 성향을 가지고 있기 때문이다.
처음이라니 ㅋㅋ 이것도 이거나름대로 놀랍네요.

2021-08-05 14:54 UTC, perenok requested changes
나봄의 우리 너무 멋지다 소리에 다들 실없이 웃곤 하지만 우리 진짜 멋있을지도...? 라는 생각을 무심코 하고 마는 나라는 사람 이미 나봄에게 세뇌당한 걸까...?ㅋㅋㅋㅋ
나봄의 커밋과도 비슷한 문체가 느껴지는 글 잘 봤습니다 중간중간 피드백 넣어놨으니 참고하시고 맘에 안들면 그대로 두셔도 됩니다ㅋㅋㅋ

2021-08-05 14:54 UTC, perenok commented on blob/level3.md
> +나에게 팀 프로젝트는 아예 처음이었다. 과연 내가 팀 프로젝트를 잘 할 수 있을까? 라는 고민이 많았다. 고민이 생길 수 밖에 없었다. 왜냐하면 나는 내가 고집이 많은 것도 스스로 알고 있고 혼자 하는 것을 좋아하는 성향을 가지고 있기 때문이다.
나에게를 빼도 괜찮을 거 같은데 어떻게 생각하시나요?ㅎㅎ

2021-08-05 14:54 UTC, perenok commented on blob/level3.md
> +이 말에 많은 위로는 물론이고 생각에 잠기게 되었다. 이런 글귀가 생각났다. '꼰대가 될 거면 멋진 꼰대가 되라'. 그래, '이왕 고집있을 거 좋은 고집을 갖자'.
hoxy... 포비...?

2021-08-05 14:54 UTC, perenok commented on blob/level3.md
> +함께이기에 배운 것들이 있다. 혼자 개발하는 것보다 훨씬 복잡했다. 서로 작성한 코드가 프로젝트에 각각 잘 적용되야 했다. 이를 위해 깃 전략이 필수였다. 이를 통해 깃에 대해 조금 더 알 수 있는 시간이 되었다.
```suggestion
함께이기에 배운 것들이 있다. 혼자 개발하는 것보다 훨씬 복잡했다. 서로 작성한 코드가 프로젝트에 각각 잘 적용되야 했다. 이를 위해선 깃 전략이 필수였다. 팀원들과 전략을 세우면서 깃에 대해 조금 더 알 수 있는 시간이 되었다.
```

2021-08-05 14:54 UTC, perenok commented on blob/level3.md
> +시간이 가면 갈 수록 이 프로젝트는 끝이 날 수 있다는 생각에 마음이 섭섭할 정도로 현재 팀 프로젝트가 너무나 행복하다. 이 추억은 평생 갈 듯 하다. 남은 기간도 아자아자! 파이팅.
```suggestion
시간이 가면 갈 수록 이 프로젝트가 끝이 날 수 있다는 생각에 마음이 섭섭할 정도로 현재 너무나 행복하다. 이 추억은 평생 갈 듯 하다. 남은 기간도 아자아자! 파이팅.
```

2021-08-07 06:09 UTC, hchayan approved these changes
안녕하세요 나봄!
나봄이 프로젝트 하면서 같이 성장해나가고 있는거 같아서 좋네요 ㅋㅋ

문법 오류는 다른 크루들이 대부분 잡아준거 같아서 크게 손댈 곳이 없는거 같네요!
고생하셧어요 ㅎㅎ

2021-08-07 06:09 UTC, hchayan commented on blob/level3.md
> +이 말에 많은 위로는 물론이고 생각에 잠기게 되었다. 이런 글귀가 생각났다. '꼰대가 될 거면 멋진 꼰대가 되라'. 그래, '이왕 고집있을 거 좋은 고집을 갖자'.
고집과 강단은 한끝 차이죠!

2021-08-07 06:09 UTC, hchayan commented on blob/level3.md
> +윈도우... 아니 발표천재 '크로플' <br>
이팀도 한명만 윈도우인가요 ㅋㅋㅋ

2021-08-07 06:09 UTC, hchayan commented on blob/level3.md
> +함께이기에 배운 것들이 있다. 혼자 개발하는 것보다 훨씬 복잡했다. 서로 작성한 코드가 프로젝트에 각각 잘 적용되야 했다. 이를 위해 깃 전략이 필수였다. 이를 통해 깃에 대해 조금 더 알 수 있는 시간이 되었다.
평소 잘 신경안쓰던 부분들이 팀프로젝트하면서 신경써야되는게 많더라구요!

2021-08-08 08:44 UTC, lns13301 approved these changes
고생많았습니다!!
남은 팀 프로젝트도 파이팅 💪🌱

2021-08-08 10:04 UTC, qhals321 commented on blob/level3.md
> +윈도우... 아니 발표천재 '크로플' <br>
또르르르르

2021-08-08 12:16 UTC, perenok approved these changes
확인했습니다~~

2021-08-08 15:38 UTC, sunhpark42 commented on blob/level3.md
> +윈도우... 아니 발표천재 '크로플' <br>
Edge보유자 절찬리 우대중~

2021-08-08 15:39 UTC, sunhpark42 commented on blob/level3.md
> +시간이 가면 갈 수록 이 프로젝트는 끝이 날 수 있다는 생각에 마음이 섭섭할 정도로 현재 팀 프로젝트가 너무나 행복하다. 이 추억은 평생 갈 듯 하다. 남은 기간도 아자아자! 파이팅.
나봄..왜 끝날거 생각해..? 내년까지 유지해서 광고 붙일거 아니였어...? ㅠㅠㅠㅠㅠㅠㅠ

2021-08-08 23:53 UTC, sihyung92 commented
나봄 하이~~
가만보면 감수성 풍부해서 지나가는 말도 오래오래 곱씹는단 말이지?🤔

그래서 그냥 진솔하게 느낀점 그대로 말해보자면,

팀플레이에 약하다고 하지만 본인 아는 지식을 이렇게까지 팀원에게 친절하게 공유하고 설명해주는 사람을 난 살면서 본적이 없고,

더 좋은 의견있으면 서슴없이 말하며 그렇다고 남의 의견을 귀담아듣지 않는 것도 아니고,

하루종일 일하고나서 많지않은 쉬는시간을 활용해 학습하고 배운 내용을 도입하려고 시도하며,

팀원의 기분을 살펴 배려하고 행동할줄 알면서,

다른 팀원의 업무도 발벗고 나서 내 일처럼 도와주려는 사람이 내가 느낀 팀에서의 나봄이었쓰

본문에선 나를 협업의 대가라고 적어주었지만 사실 그 말에 진짜 어울리는건 나봄이 아닌가 싶네 ㅎ_ㅎ 아마 누구라도 같은 팀원하고 싶은 인재일꺼야

롤만 잘하면 될건데;

2021-08-09 10:57 UTC, jho2301 approved these changes
안녕하세요 나봄!
수정 제안 드릴 부분을 잘 반영해주셔서 감사합니다 ㅎㅎ.
다시 전체적으로 글을 읽으면서 주절주절팀이 얼마나 성장에 대한 의지가 강한지 알 수 있어서 좋았습니다!
각양각색인 것 같아 분위기도 정말 재밌을 것 같네요 
더 피드백할 부분이 없는 것 같아 저는 어프루브하도록 하겠습니다.
이외 궁금한 사항이 있으면 자유롭게 연락주세요! 감사합니다

2021-10-12 01:03 UTC, merged