[레벨 3 글쓰기 미션] 수리(이다원) 미션 제출합니다.
woowacourse/woowa-writing-3 pull request #230
Opened 2021-08-02 15:06 UTC by DWL5

제출합니다.

2021-08-03 10:21 UTC, Hyeon9mak commented on 수리_팀프로젝트가_남긴것.md
> +이번 3번째 데모데이를 하기 전날 거의 새벽 3시까지 팀프로젝트를 하였다. 줌으로 진행되어 목소리가 끊길 때도 많고 밤이라 피곤하고 게다가 열대야 까지 있었다. 짜증날 법한 상황이다. 그러나 이상하게도 화가 나지 않았다. 왜 그런걸까? 이 모든 건 우테코에서 받은 회식 쿠폰으로 부터 비롯된 것 같다. 아니면 팀문화로 정한 반말모드의 힘인가? 아니면 우리
브롤스타즈 QA 바랍니다

2021-08-03 15:10 UTC, 365kim commented on 수리_팀프로젝트가_남긴것.md
> +레벨 3이 시작되고 나서 함께자라기라는 책을 읽었다. 전문가일 수록 사회적기술과 사회적 인프라를 중요하게 생각한다는 것이다.  그 중 굉장히 인상깊은 부분이 있었다. 조직 내에서 새로운 기술을 도입하고자 노력하였는데, 조직원들이 수동적이고 보수적이어서 실패하였다는 청중이 있었다. 저자는 그 청중에게 "그 조직원들이 선생님을 좋아하나요?"라는 질문을 했다고
가독성 측면에서 '함께자라기'에 문장부호를 추가하면 어떨까 싶어 검색하면서, 서적 인용에 여러가지 옵션이 있다는 걸 새로 배울 수 있었어요. 아래 참고해서 반영해주시면 좋을 것 같습니당 :)

[참고링크](https://www.korean.go.kr/front/page/pageView.do?page_id=P000204)
문장 안에서 책의 제목이나 신문 이름 등을 나타낼 때는 그 앞뒤에 겹낫표나 겹화살괄호를 쓰는 것이 원칙이고 큰따옴표를 쓰는 것도 허용된다.
`레벨 3이 시작되고 나서 『함께자라기』라는 책을 읽었다.`
`레벨 3이 시작되고 나서 ≪함께자라기≫라는 책을 읽었다.`
`레벨 3이 시작되고 나서 "함께자라기"라는 책을 읽었다.`

2021-08-03 15:17 UTC, 365kim commented on 수리_팀프로젝트가_남긴것.md
> +팀 프로젝트를 시작 하기 전에는 내가 아직 부족하다는 생각이 많이 들었다. 그래서 어떻게든 팀에 도움이 되는 사람이 되자라는 마음가짐이 컸다. 그 중 가장 기본적인 것이 적극적으로 참여하는 것이라고 생각했다. 적극적이려면 지식이 있어야 했다. 그래서 Oauth2, S3등 새로운 기술을 도입하려고 했을 때 미리 한번 연습삼아 구현을 해보고 참여하였다. 또한
저도 항상 헷갈려서 찾아보는데 직접 인용이면 `-라고`, 간접인용이면 `-고` 로 쓰는게 맞춤법에 맞는 것 같습니당 아래 참고해주시면 좋을 것 같습니당
 
[참고링크](https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=118299)
`그래서 "어떻게든 팀에 도움이 되는 사람이 되자"라는 마음가짐이 컸다.`
`그래서 어떻게든 팀에 도움이 되는 사람이 되자는 마음가짐이 컸다.`

2021-08-03 15:20 UTC, 365kim commented on 수리_팀프로젝트가_남긴것.md
> +팀 프로젝트를 시작 하기 전에는 내가 아직 부족하다는 생각이 많이 들었다. 그래서 어떻게든 팀에 도움이 되는 사람이 되자라는 마음가짐이 컸다. 그 중 가장 기본적인 것이 적극적으로 참여하는 것이라고 생각했다. 적극적이려면 지식이 있어야 했다. 그래서 Oauth2, S3등 새로운 기술을 도입하려고 했을 때 미리 한번 연습삼아 구현을 해보고 참여하였다. 또한
오옷 데모데이 때 본 게 수리의 아이디어로 완성된 것이었군요 👍👍👍👍

2021-08-03 15:21 UTC, 365kim commented on 수리_팀프로젝트가_남긴것.md
> +그러나 이번 스프린트에 '약관'작성을 팀끼리 같이 해야하는 일이 있었다. 처음에 나는 약관을 한번도 작성해 보지 않아서 부담스러웠었다. 막상 참여하고 보니 약관을 작성하면서 도메인에 대한 이해도 명확해지고 결제, 환불에 대한 플로우를 명확하게 잡을 수 있었다. 어디에서나 배울 것이 있었다.
발표 때 약관보고 감탄이 절로 나왔어요. 고생많으셨어요 👏👏👏👏

2021-08-03 15:23 UTC, 365kim commented on 수리_팀프로젝트가_남긴것.md
> +우리가 처음 딱 모였을 때는 집단이 었을지도 모른다. 그러나 같이 팀 문화를 고민하고, 서비스에 대해 토론한다. 소소하게는 데일리에서 오늘 먹을 점심을 공유하고 서로가 어떤 MBTI인지 말한다. 이렇게 점차 우리는 팀이 되어가고 있었다. 처음 시작때보다 단톡방이 훨씬 활발해졌다. 메시지로 대화하다가 잘 안풀리면 바로 줌 ㄱㄱ를 외치친다. 이러한 것들만 봐
앗 바쁜 와중에 작성하시느라 오타가 들어간 것 같아요. 확인해주시면 감사하겠습니당

메시지로 대화하다가 잘 안풀리면 바로 줌 ㄱㄱ를 `외치친다.` 
이러한 것들만 봐도`  팀에 되어가고 있는` 증거인 것 같다.

2021-08-03 15:25 UTC, 365kim requested changes
수리 안녕하세요!
TYF_ 팀에서 즐겁고 유익한 프로젝트 생활을 보내신게 느껴지는 글이었어요 :)
수리의 적극성과 수리네 팀의 끈끈한 동료애(?)도 느껴졌어요. 
잘 읽었습니다.

소소한 수정 제안 코멘트 남겼는데 확인해주시면 바로 어프-하겠습니다.
고생하셨습니다. 👏👏👏

2021-08-04 06:07 UTC, hsik0225 approved these changes
안녕하세요 수리!

글 잘 읽었습니다.
흥미로운 서론으로 독자의 흥미 유발 및 자연스러운 내용 전개가 인상 깊었어요!

간단한 맞춤법만을 적어두었어요.
이만 Approve 하겠습니다!

2021-08-04 06:07 UTC, hsik0225 commented on 수리_팀프로젝트가_남긴것.md
> +레벨 3이 시작되고 나서 함께자라기라는 책을 읽었다. 전문가일 수록 사회적기술과 사회적 인프라를 중요하게 생각한다는 것이다.  그 중 굉장히 인상깊은 부분이 있었다. 조직 내에서 새로운 기술을 도입하고자 노력하였는데, 조직원들이 수동적이고 보수적이어서 실패하였다는 청중이 있었다. 저자는 그 청중에게 "그 조직원들이 선생님을 좋아하나요?"라는 질문을 했다고
> 전문가일 수록 사회적기술과 사회적 인프라를 중요하게 생각한다는 것이다. 

전문가일 수록 -> 전문가일수록
사회적기술 -> 사회적 기술

2021-08-04 06:07 UTC, hsik0225 commented on 수리_팀프로젝트가_남긴것.md
> +이번 3번째 데모데이를 하기 전날 거의 새벽 3시까지 팀프로젝트를 하였다. 줌으로 진행되어 목소리가 끊길 때도 많고 밤이라 피곤하고 게다가 열대야 까지 있었다. 짜증날 법한 상황이다. 그러나 이상하게도 화가 나지 않았다. 왜 그런걸까? 이 모든 건 우테코에서 받은 회식 쿠폰으로 부터 비롯된 것 같다. 아니면 팀문화로 정한 반말모드의 힘인가? 아니면 우리
> 줌으로 진행되어 목소리가 끊길 때도 많고 밤이라 피곤하고 게다가 열대야 까지 있었다.

`,`로 한 번씩 끊어주면 좋을 것 같아요!

2021-08-04 06:07 UTC, hsik0225 commented on 수리_팀프로젝트가_남긴것.md
> +레벨 3이 시작되고 나서 함께자라기라는 책을 읽었다. 전문가일 수록 사회적기술과 사회적 인프라를 중요하게 생각한다는 것이다.  그 중 굉장히 인상깊은 부분이 있었다. 조직 내에서 새로운 기술을 도입하고자 노력하였는데, 조직원들이 수동적이고 보수적이어서 실패하였다는 청중이 있었다. 저자는 그 청중에게 "그 조직원들이 선생님을 좋아하나요?"라는 질문을 했다고
여럿이서 같이 하는 일인 만큼 인간관계도 정말 중요한 것 같아요 😅

2021-08-05 12:22 UTC, yujo11 approved these changes
안녕하세요 수리! 

수리의 솔직한 생각과 감정이 잘 드러나 있어서 공감하면서 글을 읽을 수 있었어요 👍👍👍

위에 다른 크루들이 먼저 남겨준 리뷰 외에는 수정할 부분을 찾지 못 해서 어프로브 남기고 가겠습니다!

좋은 글 감사합니다!! 👍👍👍

2021-08-05 12:22 UTC, yujo11 commented on 수리_팀프로젝트가_남긴것.md
> +레벨 3이 시작되고 나서 함께자라기라는 책을 읽었다. 전문가일 수록 사회적기술과 사회적 인프라를 중요하게 생각한다는 것이다.  그 중 굉장히 인상깊은 부분이 있었다. 조직 내에서 새로운 기술을 도입하고자 노력하였는데, 조직원들이 수동적이고 보수적이어서 실패하였다는 청중이 있었다. 저자는 그 청중에게 "그 조직원들이 선생님을 좋아하나요?"라는 질문을 했다고
저도 위에 남겨준 하루의 의견처럼 '함께 자라기'라는 책을 표현할 수 있는 부호가 들어가면 좋을거 같아요!

인용해주신 부분이 저도 책에서 인상 깊게 읽었던 부분이라 글 내용에 더 공감이 가네요ㅎㅎ

2021-08-05 12:22 UTC, yujo11 commented on 수리_팀프로젝트가_남긴것.md
> +그러나 이번 스프린트에 '약관'작성을 팀끼리 같이 해야하는 일이 있었다. 처음에 나는 약관을 한번도 작성해 보지 않아서 부담스러웠었다. 막상 참여하고 보니 약관을 작성하면서 도메인에 대한 이해도 명확해지고 결제, 환불에 대한 플로우를 명확하게 잡을 수 있었다. 어디에서나 배울 것이 있었다.
우와 약관을 직접 작성한거였군요! 멋져요!! 👍👍👍

2021-08-07 05:46 UTC, sakjung approved these changes
안녕하세요 수리 ㅎㅎ 삭정입니다
단순 사람들의 집단에서 끈끈한 팀이 되어가는 과정이 와닿아서 재밌게 읽었습니다 ㅋㅋ.
앞으로도 행복개발하시길 응원할게요~

2021-08-07 05:46 UTC, sakjung commented on 수리_팀프로젝트가_남긴것.md
> +레벨 3이 시작되고 나서 함께자라기라는 책을 읽었다. 전문가일 수록 사회적기술과 사회적 인프라를 중요하게 생각한다는 것이다.  그 중 굉장히 인상깊은 부분이 있었다. 조직 내에서 새로운 기술을 도입하고자 노력하였는데, 조직원들이 수동적이고 보수적이어서 실패하였다는 청중이 있었다. 저자는 그 청중에게 "그 조직원들이 선생님을 좋아하나요?"라는 질문을 했다고
인용한 부분을 보고 저도 멍해졌네요... 조직생활에서 중요한 부분이라고 생각합니다

2021-08-08 04:14 UTC, DWL5 commented on 수리_팀프로젝트가_남긴것.md
> +팀 프로젝트를 시작 하기 전에는 내가 아직 부족하다는 생각이 많이 들었다. 그래서 어떻게든 팀에 도움이 되는 사람이 되자라는 마음가짐이 컸다. 그 중 가장 기본적인 것이 적극적으로 참여하는 것이라고 생각했다. 적극적이려면 지식이 있어야 했다. 그래서 Oauth2, S3등 새로운 기술을 도입하려고 했을 때 미리 한번 연습삼아 구현을 해보고 참여하였다. 또한
배우고 갑니다👍

2021-08-08 04:43 UTC, 2SOOY approved these changes
안녕하세요 수리 :)

수리의 글을 읽으면서 팀에 도움이 되고자 스스로 노력했던 모습 !
프로젝트를 하면서 팀에 잘 녹아든 수리의 모습이 잘 표현된 것 같아서 재밌게 읽었습니다 👍 

앞으로 남은 기간도 파이팅 입니다 ✊✊✊
글 작성하시느라 고생하셨습니다 :)

2021-08-08 04:43 UTC, 2SOOY commented on 수리_팀프로젝트가_남긴것.md
> +레벨 3이 시작되고 나서 "함께자라기"라는 책을 읽었다. 전문가일수록 사회적 기술과 사회적 인프라를 중요하게 생각한다는 것이다.  그 중 굉장히 인상깊은 부분이 있었다. 조직 내에서 새로운 기술을 도입하고자 노력하였는데, 조직원들이 수동적이고 보수적이어서 실패하였다는 청중이 있었다. 저자는 그 청중에게 "그 조직원들이 선생님을 좋아하나요?"라는 질문을 했
> 그 조직원들이 선생님을 좋아하시나요?

저를 돌아보게끔 하는 문장이네요,,,

2021-08-08 04:43 UTC, 2SOOY commented on 수리_팀프로젝트가_남긴것.md
> +그러나 이번 스프린트에 '약관'작성을 팀끼리 같이 해야하는 일이 있었다. 처음에 나는 약관을 한번도 작성해 보지 않아서 부담스러웠었다. 막상 참여하고 보니 약관을 작성하면서 도메인에 대한 이해도 명확해지고 결제, 환불에 대한 플로우를 명확하게 잡을 수 있었다. 어디에서나 배울 것이 있었다.
저도 약관 보고 정말 감탄했습니다 👍👍👍

2021-08-08 04:43 UTC, 2SOOY commented on 수리_팀프로젝트가_남긴것.md
> +우리가 처음 딱 모였을 때는 집단이 었을지도 모른다. 그러나 같이 팀 문화를 고민하고, 서비스에 대해 토론한다. 소소하게는 데일리에서 오늘 먹을 점심을 공유하고 서로가 어떤 MBTI인지 말한다. 이렇게 점차 우리는 팀이 되어가고 있었다. 처음 시작때보다 단톡방이 훨씬 활발해졌다. 메시지로 대화하다가 잘 안풀리면 바로 줌 ㄱㄱ를 외친다. 이러한 것들만 봐도
> 이 모든 건 우테코에서 받은 회식 쿠폰으로 부터 비롯된 것 같다.


👍👍👍

2021-08-08 04:43 UTC, 2SOOY commented on 수리_팀프로젝트가_남긴것.md
> +팀 프로젝트를 시작 하기 전에는 내가 아직 부족하다는 생각이 많이 들었다. 그래서 "어떻게든 팀에 도움이 되는 사람이 되자"라는 마음가짐이 컸다. 그 중 가장 기본적인 것이 적극적으로 참여하는 것이라고 생각했다. 적극적이려면 지식이 있어야 했다. 그래서 Oauth2, S3등 새로운 기술을 도입하려고 했을 때 미리 한번 연습삼아 구현을 해보고 참여하였다.
팀원들에게 도움이 되기 위해서 노력한 부분들 멋져용 👍👍👍

2021-08-08 04:43 UTC, 2SOOY commented on 수리_팀프로젝트가_남긴것.md
> +우리가 처음 딱 모였을 때는 집단이 었을지도 모른다. 그러나 같이 팀 문화를 고민하고, 서비스에 대해 토론한다. 소소하게는 데일리에서 오늘 먹을 점심을 공유하고 서로가 어떤 MBTI인지 말한다. 이렇게 점차 우리는 팀이 되어가고 있었다. 처음 시작때보다 단톡방이 훨씬 활발해졌다. 메시지로 대화하다가 잘 안풀리면 바로 줌 ㄱㄱ를 외친다. 이러한 것들만 봐도
집단에서 진정한 팀이 되어가고 있다는 것이 잘 전해지네용 👏👏👏

2021-08-08 04:48 UTC, tributetothemoon approved these changes
안녕하세요 수리!! 레벨 3 출근일이 갈리고 전사 재택까지 ㅠ 오랜 기간 못 본 것 같네요.

하지만 글에서 수리가 어떻게 살고 있는지 너무나 잘 느껴져서 ㅋㅋㅋ 오래 안 본듯하면서도 얼마 안 된 것 같다는 느낌까지 받았습니다!

정말 열심히 프로젝트에 참여하려는 모습이 보였고, 그 속에서 배운 것들 또한 많았던 점을 글에 자연스럽게 녹아내셨네요.

'줌 ㄱㄱ' 라는 표현에서는 갑자기 수리 목소리가 들리는 것 같은 환청을 들은듯 했어요🤣.

고생하셨습니다!! 리뷰가 늦어 죄송해요😢!!

2021-08-08 04:48 UTC, tributetothemoon commented on 수리_팀프로젝트가_남긴것.md
> +레벨 3이 시작되고 나서 "함께자라기"라는 책을 읽었다. 전문가일수록 사회적 기술과 사회적 인프라를 중요하게 생각한다는 것이다.  그 중 굉장히 인상깊은 부분이 있었다. 조직 내에서 새로운 기술을 도입하고자 노력하였는데, 조직원들이 수동적이고 보수적이어서 실패하였다는 청중이 있었다. 저자는 그 청중에게 "그 조직원들이 선생님을 좋아하나요?"라는 질문을 했
> (왜 상처는 나도 받는가..🥺 )

🤣🤣🤣🤣🤣🤣🤣 공감능력이 뛰어나시네요!

2021-08-08 04:48 UTC, tributetothemoon commented on 수리_팀프로젝트가_남긴것.md
> +### 집단이 팀은 아니다.
개발자라면 머리를 끄덕일 수 있는 강렬한 소제목이네요! 👍

2021-08-08 04:48 UTC, tributetothemoon commented on 수리_팀프로젝트가_남긴것.md
> +이번 3번째 데모데이를 하기 전날 거의 새벽 3시까지 팀프로젝트를 하였다. 줌으로 진행되어 목소리가 끊길 때도 많고, 밤이라 피곤하고, 게다가 열대야 까지 있었다. 짜증날 법한 상황이다. 그러나 이상하게도 화가 나지 않았다. 왜 그런걸까? 이 모든 건 우테코에서 받은 회식 쿠폰으로 부터 비롯된 것 같다. 아니면 팀문화로 정한 반말모드의 힘인가? 아니면 우
```suggestion
이번 3번째 데모데이를 하기 전날 거의 새벽 3시까지 팀프로젝트를 하였다. 줌으로 진행되어 목소리가 끊길 때도 많고, 밤이라 피곤하고, 게다가 열대야 까지 있었다. 짜증날 법한 상황이다. 그러나 이상하게도 화가 나지 않았다. 왜 그런걸까? 이 모든 건 우테코에서 받은 회식 쿠폰으로 부터 비롯된 것 같다. 아니면 팀문화로 정한 반말모드의 힘인가? 혹은 우리 팀 모두 즐기게된 게임인 브롤스타즈 덕분 일지도 모르겠다.
```

단어의 반복을 줄이는 게 더 자연스러울 것 같단 생각을 해봤습니다.!

2021-08-08 10:08 UTC, 365kim approved these changes
피드백 반영해주셔서 감사해요! 수고하셨습니당 👏👏👏👏👏

2021-08-08 10:20 UTC, RinSabbit reviewed
수리 하이하이~~
도장 슬쩍 감!!!!
플젝 퐈이테에에엥

2021-08-08 10:20 UTC, RinSabbit commented on 수리_팀프로젝트가_남긴것.md
> +이번 3번째 데모데이를 하기 전날 거의 새벽 3시까지 팀프로젝트를 하였다. 줌으로 진행되어 목소리가 끊길 때도 많고, 밤이라 피곤하고, 게다가 열대야 까지 있었다. 짜증날 법한 상황이다. 그러나 이상하게도 화가 나지 않았다. 왜 그런걸까? 이 모든 건 우테코에서 받은 회식 쿠폰으로 부터 비롯된 것 같다. 아니면 팀문화로 정한 반말모드의 힘인가? 아니면 우
우와 같이 겜도 하다니ㅋㅋㅋㅋㅋㅋㅋㅋㅋ멋지다!!!

2021-08-08 10:20 UTC, RinSabbit commented on 수리_팀프로젝트가_남긴것.md
> +우리가 처음 딱 모였을 때는 집단이 었을지도 모른다. 그러나 같이 팀 문화를 고민하고, 서비스에 대해 토론한다. 소소하게는 데일리에서 오늘 먹을 점심을 공유하고 서로가 어떤 MBTI인지 말한다. 이렇게 점차 우리는 팀이 되어가고 있었다. 처음 시작때보다 단톡방이 훨씬 활발해졌다. 메시지로 대화하다가 잘 안풀리면 바로 줌 ㄱㄱ를 외친다. 이러한 것들만 봐도
`ㄱㄱ`
ㅋㅋㅋㅋㅋㅋㅋㅋ굵고 강하다ㅋㅋㅋㅋㅋㅋㅋㅋ

2021-08-08 11:06 UTC, DWL5 commented on 수리_팀프로젝트가_남긴것.md
> +우리가 처음 딱 모였을 때는 집단이 었을지도 모른다. 그러나 같이 팀 문화를 고민하고, 서비스에 대해 토론한다. 소소하게는 데일리에서 오늘 먹을 점심을 공유하고 서로가 어떤 MBTI인지 말한다. 이렇게 점차 우리는 팀이 되어가고 있었다. 처음 시작때보다 단톡방이 훨씬 활발해졌다. 메시지로 대화하다가 잘 안풀리면 바로 줌 ㄱㄱ를 외치친다. 이러한 것들만 봐
오 두번 띄어쓰기도 봐주셨군요!! 반영하겠습니다 ㅎㅎ

2021-08-08 11:07 UTC, DWL5 commented on 수리_팀프로젝트가_남긴것.md
> +이번 3번째 데모데이를 하기 전날 거의 새벽 3시까지 팀프로젝트를 하였다. 줌으로 진행되어 목소리가 끊길 때도 많고, 밤이라 피곤하고, 게다가 열대야 까지 있었다. 짜증날 법한 상황이다. 그러나 이상하게도 화가 나지 않았다. 왜 그런걸까? 이 모든 건 우테코에서 받은 회식 쿠폰으로 부터 비롯된 것 같다. 아니면 팀문화로 정한 반말모드의 힘인가? 아니면 우
오 춘식 ㅋㅋㅋㅋㅋㅋㅋ 하이하이
간단히 스트레스 풀기 좋드라구!!!!!!!

2021-08-08 11:08 UTC, DWL5 commented on 수리_팀프로젝트가_남긴것.md
> +우리가 처음 딱 모였을 때는 집단이 었을지도 모른다. 그러나 같이 팀 문화를 고민하고, 서비스에 대해 토론한다. 소소하게는 데일리에서 오늘 먹을 점심을 공유하고 서로가 어떤 MBTI인지 말한다. 이렇게 점차 우리는 팀이 되어가고 있었다. 처음 시작때보다 단톡방이 훨씬 활발해졌다. 메시지로 대화하다가 잘 안풀리면 바로 줌 ㄱㄱ를 외친다. 이러한 것들만 봐도
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 말투가 편해지고이써

2021-08-08 11:08 UTC, DWL5 commented on 수리_팀프로젝트가_남긴것.md
> +이번 3번째 데모데이를 하기 전날 거의 새벽 3시까지 팀프로젝트를 하였다. 줌으로 진행되어 목소리가 끊길 때도 많고, 밤이라 피곤하고, 게다가 열대야 까지 있었다. 짜증날 법한 상황이다. 그러나 이상하게도 화가 나지 않았다. 왜 그런걸까? 이 모든 건 우테코에서 받은 회식 쿠폰으로 부터 비롯된 것 같다. 아니면 팀문화로 정한 반말모드의 힘인가? 아니면 우
그렇네요 반영했숩니다~

2021-08-08 11:09 UTC, DWL5 commented on 수리_팀프로젝트가_남긴것.md
> +이번 3번째 데모데이를 하기 전날 거의 새벽 3시까지 팀프로젝트를 하였다. 줌으로 진행되어 목소리가 끊길 때도 많고 밤이라 피곤하고 게다가 열대야 까지 있었다. 짜증날 법한 상황이다. 그러나 이상하게도 화가 나지 않았다. 왜 그런걸까? 이 모든 건 우테코에서 받은 회식 쿠폰으로 부터 비롯된 것 같다. 아니면 팀문화로 정한 반말모드의 힘인가? 아니면 우리
시켜줘.. 브롤스타즈QA 롤도환영

2021-08-08 14:40 UTC, da-nyee reviewed
💛 수리 💛

수리수리 저희는 집도 가까운데 왜 한번도 못 보는 거죠,,? 🥺
다음에 모각코라도 합시다 보고싶어요 ~~!

땡큐포 팀에 도움이 되기 위해 노력하는 수리 최고예요 👍
앞으로도 지금처럼 항상 파이팅입니닷 💝

2021-10-12 07:30 UTC, woowapark commented
~~이 모든 건 우테코에서 받은 회식 쿠폰으로 부터 비롯된 것 같다.(ㅋㅋㅋㅋㅋ)~~ 
안녕하세요 수리! 함께 자라기 책을 읽은 지 오래 되었는데, 수리 글에서 소개된 일화를 보니 새삼스럽게 저도 저를 되돌아보게 되네요(...🥺)    
걱정되고 부담스러운 마음들을 딛고 하나씩 해내면서 성장하고 있는 수리한테 박수를 보내드립니다 👏👏👏     
지금까지 해온 것처럼 우테코 생활 마지막까지 잘 마무리할 수 있길 응원할게요!

2021-10-12 07:31 UTC, merged