[레벨 3 글쓰기 미션] 오즈(오주형) 미션 제출합니다.
woowacourse/woowa-writing-3 pull request #232
Opened 2021-08-02 15:13 UTC by ohjoohyung

@0imbean0
@jum0
@junroot
@ecsimsw
@rinsabbit
@livenow14

글솜씨가 부족해서 부끄럽네요
잘부탁드립니다~

2021-08-03 00:08 UTC, ecsimsw approved these changes
편하게 고민 이야기를 듣는거 같아서 좋았어요.
특별히 안읽히는 문장없이 재밌게 잘읽었습니다.

Yes맨,,, 그거 안걱정하셔도 될 것 같은데요?
좋은 팀원이신거 같아요.

남은 기간도 화이팅입니다!!!

2021-08-03 00:08 UTC, ecsimsw commented on level3/README.md
> +"난 형이 그랬다는 거 전혀 못 느꼈는데? 괜찮아!"
이 사람 말투로 읽히네요. 🤣

생각보다 걱정과는 다른 상황이 많은거 같아요.
저도 이런 생각, 저런 생각으로 엄청 고민하지만 막상 보면 다른 사람들은 못 느끼고 있는 상황 많았거든요. 혼자 끙끙됐던 경험.

2021-08-03 00:08 UTC, ecsimsw commented on level3/README.md
> +그리하여 다시 한번 생각을 다잡고 가기로 했다. 좋아! 그렇다면 적어도 코드에서만큼은 yes맨이 되지말자!
제가 팀원이 아니라 잘 모르겠지만, 
Yes맨 좋은데요? 

오히려 Yes맨이, No를 얘기해주는 순간. 그 무게감이 다르더라고요.
좋은 팀원인거 같아요.

2021-08-03 00:08 UTC, ecsimsw commented on level3/README.md
> +팀프로젝트는 의견을 내는 법의 필요성 그리고 소통의 중요성을 다시 한번 깨닫게 해주는 좋은 기회가 되었다고 생각한다.
저는 반대로 의견이 많은 편이라, 바르게 의견 내는 방법? 어떻게 의견을 내야하는지에 대한 고민을 많이 했어요.

소통의 중요성. 정말 공감합니다.

2021-08-03 00:08 UTC, ecsimsw commented on level3/README.md
> +사실 팀프로젝트 자체를 경험해본 적이 거의 없다.
팀과 프로젝트 사이를 띄어주면 어떨까요?
더 잘 읽힐 것 같아서 제안 드립니다 ㅎㅎ

![image](https://user-images.githubusercontent.com/46060746/127938048-4c6f63ab-cf4e-4abe-89f8-0628bf2bfb16.png)

2021-08-03 00:08 UTC, ecsimsw commented on level3/README.md
> +앞으로 진행될 마지막 한 번의 데모데이를 끝으로 레벨3는 종료하게 된다.
그러게요. 정말 너무 빠른거 같아요.
시작한게 엊그제 같은데 이제 마지막 데모를 남겼네요.

남은 기간까지 화이팅하시길 바랍니다.

2021-08-03 10:23 UTC, Hyeon9mak commented on level3/README.md
> +"난 형이 그랬다는 거 전혀 못 느꼈는데? 괜찮아!"
사장님!

2021-08-04 06:01 UTC, RinSabbit reviewed
반가워요 오즈!!
개인적으로 공감 가는 부분이 많은 글이었습니다 🤣 
가볍게 짚고 갈게요~~~

2021-08-04 06:01 UTC, bimppap commented on level3/README.md
> +팀프로젝트는 의견을 내는 법의 필요성 그리고 소통의 중요성을 다시 한번 깨닫게 해주는 좋은 기회가 되었다고 생각한다.
```suggestion
팀프로젝트는 의견의 필요성 그리고 소통의 중요성을 다시 한번 깨닫게 해주는 좋은 기회가 되었다고 생각한다.
```
이런 식으로 해도 되지 않을까요? 제가 잘못 이해한 거라면 넘어가도 됩니다!

2021-08-04 06:01 UTC, bimppap commented on level3/README.md
> +워낙에 의욕이나 승부욕이 강한 사람도 아니고 물 흐르는 대로 살아가는 사람이다 보니 그랬던 것 같다.
저인 줄 알았네요 오즈... 혹시 도플갱어?

2021-08-04 06:01 UTC, bimppap commented on level3/README.md
> +특히, 데모데이 전날에 main 브랜치로 merge를 하고 우리가 구현한 것들을 시연해 보고 정상적으로 기능이 작동되었을 때의 느낌은 너무 짜릿하다.
시연이 잘 될 때의 짜릿함 너무 공감합니다ㅋㅋㅋ저흰 데모데이날 이슈가 생겨서 급하게 수습을 했는데 너무 떨렸었어요ㅎㅎ

2021-08-04 06:01 UTC, bimppap commented on level3/README.md
> +그런 생각을 하고 있던 때에 우리 보고 또 보고 프로젝트 사장님과 맥주를 한잔 하게 되었다.
```suggestion
그런 생각을 하고 있던 때에 우리 '보고 또 보고' 프로젝트 사장님과 맥주를 한잔 하게 되었다.  
```

2021-08-04 17:38 UTC, dudtjr913 commented on level3/README.md
> +"난 형이 그랬다는 거 전혀 못 느꼈는데? 괜찮아!"
크.... 역시 사장님 ㅠㅠㅠ

2021-08-04 17:40 UTC, dudtjr913 commented on level3/README.md
> +특히, 데모데이 전날에 main 브랜치로 merge를 하고 우리가 구현한 것들을 시연해 보고 정상적으로 기능이 작동되었을 때의 느낌은 너무 짜릿하다.
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ정상적으로 작동할 때의 그 느낌!!!!!!!!

2021-08-04 17:40 UTC, dudtjr913 commented on level3/README.md
> +남은 기간 동안 프로젝트를 무사히 마무리 짓고 이름이 '보고 또 보고'인 만큼 현재 팀원들과도 앞으로도 보고 또 봤으면 좋겠다.
오즈와 함께해서 정말 행복해요!! 프로젝트 끝나도 계속 보고 또 봐요👍😍

2021-08-05 07:10 UTC, Junroot requested changes

2021-08-05 07:10 UTC, Junroot commented on level3/README.md
> +이 말이 꽤 크게 위로가 되었고 이미 지나간 일에 너무 크게 상심하지 않기로 했다.
`되었고` 앞 부분의 주어는 `이 말`이고 뒷 부분은 `나`에 해당한 것으로 보이네요!
문장의 주어가 서로 달라서 헷갈릴 수도 있다고 생각이 들어요.
문장을 한 번 분리해보는건 어떨까요?

2021-08-05 07:10 UTC, Junroot commented on level3/README.md
> +팀프로젝트는 의견을 내는 법의 필요성 그리고 소통의 중요성을 다시 한번 깨닫게 해주는 좋은 기회가 되었다고 생각한다.
```suggestion
팀프로젝트는 의견을 내는 법의 필요성 그리고 소통의 중요성을 다시 한번 깨닫게 해주는 기회가 되었다.
```
수식어가 많아서 문장의 의미를 파악하는데 집중이 필요하네요! 위의 제안이 아니더라도 어느 정도 문장을 정리할 수 있다고 생각합니다~

2021-08-05 07:10 UTC, Junroot commented on level3/README.md
> +그래서 과연 내가 팀프로젝트에 잘 적응할 수 있을까라는 생각도 있었고 역시나 여러 가지 고민에 맞닥뜨리게 되었다.
어떤 고민이 있었을까요? 궁금해요!

2021-08-05 07:10 UTC, Junroot commented on level3/README.md
> +특히, 데모데이 전날에 main 브랜치로 merge를 하고 우리가 구현한 것들을 시연해 보고 정상적으로 기능이 작동되었을 때의 느낌은 너무 짜릿하다.
🥳

2021-08-07 15:34 UTC, jum0 approved these changes
오즈 글 잘 읽었습니다! 저도 웬만하면 더 좋다고 하는 성격이라 오즈의 마음이 잘 이해됐어요! 한 가지 정도 피드백 드렸는데, 사실 중요한 부분은 아니라고 생각이 들어서 바로 approve 드리겠습니다! 레벨 3 남은 기간까지 화이팅입니다!!

2021-08-07 15:34 UTC, jum0 commented on level3/README.md
> +'좋아, 그거 괜찮은데?', '어? 듣다 보니 그것도 괜찮은걸?'이라고 생각을 하는 나 자신을 발견할 수 있었다.
저도 비슷한 성향인데 오즈도 그랬군요ㅠ

2021-08-07 15:34 UTC, jum0 commented on level3/README.md
> +# 경험의 부재
제가 이해한 문단은 `팀 프로젝트에 대한 걱정 -> 팀 프로젝트 과정 속에서 찾은 즐거움`으로 이어지는 것 같아서 경험의 부재보다는 다른 제목으로 쓰는 것은 어떨까 하는 개인적인 생각이 들었습니다!

2021-08-07 17:15 UTC, 0imbean0 reviewed
안녕하세요. 오즈. 심밤니다. 🦁

프로젝트를 하면서 느꼈던 고민과 경험이 담백하게 쓰여있어서 읽기 좋았어요.
데모데이 날 시연을 할 때의 짜릿함은 너무 공감이 되네요. 😆

문맥이나 문법에 대해 피드백 할 부분이 없어 Approve 남겼습니다. 🙂

2021-08-07 17:16 UTC, 0imbean0 approved these changes

2021-08-08 05:56 UTC, ohjoohyung commented on level3/README.md
> +"난 형이 그랬다는 거 전혀 못 느꼈는데? 괜찮아!"
ㅠㅠㅠㅠ

2021-08-08 06:21 UTC, ohjoohyung commented on level3/README.md
> +그래서 과연 내가 팀프로젝트에 잘 적응할 수 있을까라는 생각도 있었고 역시나 여러 가지 고민에 맞닥뜨리게 되었다.
위에서 했던 고민을 얘기하고 싶었던건데 너무 추상적으로 적은거같네요ㅋㅋㅋ 살짝 수정했습니다!

2021-08-08 10:55 UTC, Livenow14 approved these changes
오즈가 직접 말하는것처럼 느껴지는 글이네요 ㅎㅎ 

자신의 마음들을 드러낸다는 점이 인상깊은 글이었어요.

한 문장씩, 글을 나누어  피드백할 부분이 많이 보이지 않네요! 수고하셧습니다

2021-08-08 10:55 UTC, Livenow14 commented on level3/README.md
> +팀 프로젝트는 의견을 내는 법의 필요성 그리고 소통의 중요성을 다시 한번 깨닫게 해주는 기회가 되었다.
의견을 잘 내는 방법, 정말 중요한거 같아요

2021-08-08 10:55 UTC, Livenow14 commented on level3/README.md
> +특히, 데모데이 전날에 main 브랜치로 merge를 하고 우리가 구현한 것들을 시연해 보고 정상적으로 기능이 작동되었을 때의 느낌은 너무 짜릿하다.
개발에 재미를 들이는거 자체가 정말 좋은거같아요

2021-08-08 15:46 UTC, Junroot approved these changes
피드백 반영 확인했습니다! Approve 할게요~
저도 오즈와 비슷하게 팀 프로젝트를 하면서 기술적인 지식 뿐만 아니라 내가 다른 사람과 함께 일할 수 있는 적절한 사람인가에 대한 고민을 많이했어요. 공감을 많이하면서 읽었습니다 ㅎㅎ
다음 팀프로젝트 기간 화이팅입니다! 다음 데모데이 발표 기대하고 있곘습니다!

2021-08-09 05:20 UTC, RinSabbit approved these changes
수정된 거 확인했습니다!!
approve 하겠습니다. 남은 프로젝트 기간동안 파이팅해보아요!!!

2021-10-12 01:24 UTC, gracefulBrown approved these changes
다른사람이 보는 나와 내가 보는 나는 다를 수 있는거 같아요ㅎㅎ
앞으로도 깊고 다양한 고민을 통해 좋은 개발자가 될 수 있길 응원할께요 :)

2021-10-12 01:24 UTC, merged