[레벨4 글쓰기 미션] 웨지(성시형) 미션 제출합니다.
woowacourse/woowa-writing-3 pull request #245
Opened 2021-10-13 16:29 UTC by sihyung92

ㅎ_ㅎ 신나서 썼습니다! 분량이 조금 많아지긴 했는데 리뷰 잘 부탁드려요! 죄송!

@완태
@시드
@현구막
@나봄
@마크

백엔드 밭이네요!
리뷰 잘 부탁드립니다
[편하게 보기](https://github.com/sihyung92/woowa-writing-3/tree/step4/step4)

2021-10-14 13:59 UTC, daum7766 reviewed
웨지 HI~~

다른 사람보다 먼저 글을 남기고 싶어서 후다닥 써봤습니다.
웨지랑 글쓰기 팀이 되진 않았지만 매번 챙겨보고 있어요
그때마다 새로운 모습을 알아가는것 같네요.

이번글도 잘보고 가요!
- 웨지를 존경하는 멍토가-

2021-10-14 13:59 UTC, daum7766 commented on step4/README.md
> +> 🤖씨유bot (갑자기 매우 진지하게) : 저는 근무하는 환경과 함께 일하는 사람들이 훨씬 중요해서요, 천만 원 이천만 원 정도에 직장을 옮길 것 같지 않네요.
씨유 멋있다

2021-10-14 13:59 UTC, daum7766 commented on step4/README.md
> +왜냐하면 공부하는 법, 직업을 대하는 태도, 심지어는 인생관까지 바꾼 계기가 되었기 때문이에요.
오? 그런가요?
저는 웨지가 열심히 사는걸 보면 우테코에 오지 않았더라도 결국 성공하셨을 거라고 생각해요.
물론 우테코가 성공기간을 많이 단축시켜줬다고 생각 하지만요!!

2021-10-14 13:59 UTC, daum7766 commented on step4/README.md
> +그저 '계속적 소득활동'에 불과한 무엇인가에 행복의 열쇠가 있었다는 게 신기합니다.
워커홀릭인줄 알았던 웨지가 베짱이 시절이 있었다니... 충격!

2021-10-14 13:59 UTC, daum7766 commented on step4/README.md
> +쉬지 않고 개발과 관련된 수다를 떨어댄 것을 통해 훈련된 것이라 생각해요. 사람이 별로 없는 엘리베이터를 보고 `null null하네` 라고 말했던 순간(구구가 `이건 empty()죠` 라고 정정해줌),
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2021-10-14 13:59 UTC, daum7766 commented on step4/README.md
> +TCP 3 way handshake를 배운 후 지나가는 크루들에게 맥락 없이 "씬!(syn)" 외쳐대던 순간들이 떠오르네요. 받아주신 크루들 감사합니다.
ACK!

2021-10-14 14:09 UTC, pika96 approved these changes
항상 옆에서 보면서 존경이 가득했는데 글을 보면서 더 깊은 사람이라는 걸 알게되었네요~
갈수록 여러 방면에서 성장하는 웨지를 보면서 부러웠는데 글을 보면서 느낀 점이 많네요..!

항상 열정적이고 꾸준한 웨지! 가는 길에 항상 행복만 있기를 바랄께요! 화이팅~

2021-10-16 00:35 UTC, zigsong commented on step4/README.md
> +저는 우테코가 좋습니다. 빛나는 우테코에 제가 입성했다는 느낌을 주는 게 아니라, 저 스스로 빛날 수 있도록 도와주는 우테코라서 좋습니다.
진짜 멋진 말이에요

2021-10-16 00:35 UTC, zigsong commented on step4/README.md
> +TCP 3 way handshake를 배운 후 지나가는 크루들에게 맥락 없이 "씬!(syn)" 외쳐대던 순간들이 떠오르네요. 받아주신 크루들 감사합니다.
ACK!

2021-10-16 01:23 UTC, sihyung92 commented on step4/README.md
> +TCP 3 way handshake를 배운 후 지나가는 크루들에게 맥락 없이 "씬!(syn)" 외쳐대던 순간들이 떠오르네요. 받아주신 크루들 감사합니다.
SYN

connection established...

2021-10-17 19:19 UTC, bosl95 commented
웨지 하이!!!! 글쓰기 미션 하면 항상 댓글 달아줬는데 한번을 안 왔지??😅 (배은망덕쓰)
맨날 '대단한 사람이야~'라고 장난식으로 얘기하곤 했었는데 진짜 진심이야 ㅋㅋㅋ
웨지의 우테코 이전 스토리를 조금 들려줘서 인지도 모르지만 어쩌면 인간 승리의 표본은 웨지가 아닐까 생각해 ㅋㅋㅋ
산전수전도 많이 겪었지만 결국 일궈내는 모습에 대리 만족된다 ㅎㅎ
표현한 적은 없지만 항상 크루들이나 나한테 용기있게 손 내밀어주는 모습도 대단하고, 고맙다고 생각하고 있어!! 
앞으로 어딜 가서도 멋지게 빛나는 웨지가 되길 바라!!!! 마지막까지 화이팅!!!!!!!!! 🔥🔥🔥🔥

2021-10-18 10:25 UTC, seovalue commented on step4/README.md
> +저는 몰입하며 일하고 싶고, 주위 사람들과의 관계를 소중히 여기고, 제가 가장 사랑하는 모습으로 살아가고 싶으며, 꾸준히 포기하지 않고, 제가 받은 것을 나누어주는 프로그래머를 꿈꿉니다.
지금도 그렇게 살아가고 있는 것 같은데요? ㅎㅎ
웨지가 우테코 기간동안 많은 것을 얻은 만큼, 크루들도 우테코 기간 동안 웨지에게 많은 것을 얻었다고 생각해요! 
멋진 웨지 항상 응원합니다! 👍

2021-10-19 00:14 UTC, Livenow14 commented
하이 웨지~~ 
과정속에서 뭘 배웠고, 뭘 목표로 해야할지 자신만의 방법으로 정리 된 것 같아서 보기 좋다 :) 
즐거움이 느껴지는 글이네, 우테코라서 빛나는 게 아닌, 빛날 수 있게 도와주는 우테코, 각자가 빛이 나는 과정을 함께 할 수 있는게 행복이라 생각함 ㅎㅎㅎ 
지금까지 달려온다고 고생했고, 또 앞으로 갈 길에 대해 고생하자 😊 파이팅

2021-10-19 00:23 UTC, Hyeon9mak approved these changes
어떻게 글에서 웨지 목소리가 들리는거지
뭔가 잠콩에서 미션하다가 점심에 웨지 썰 들은 기분이네유 ㅋㅅㅋ

문단 별로 이야기가 잘게잘게 나뉘어 있어서 끊어가면서 정신없이 읽었어유
리뷰할 건 딱히 모르겠어서 어떻게든 쥐어짰으니 선 Approve 받으세유~

2021-10-19 00:23 UTC, Hyeon9mak commented on step4/README.md
> +제가 우테코에서 배운 것들에 대한 이야기를 들려드리면 어떤 프로그래머가 되고 싶은지도 자연스럽게 드러날 거라 생각합니다!
첫 줄부터 자극 👍 👍

2021-10-19 00:23 UTC, Hyeon9mak commented on step4/README.md
> +
개념, 사실, 연습이라는 단어를 이해할 것, 외워야 할 것, 해봐야 할 것으로 풀어서 적어주신거 엄청 좋네유!!!!!!
정말 '어떻게 공부하는가'가 그려지는 느낌쓰

2021-10-19 00:23 UTC, Hyeon9mak commented on step4/README.md
> +일단 무작정 적용해보고 안 되면 학습 테스트도 만들어 보고~ 그래도 안 되면 코치들과 크루들을 물고 늘어지고! 왜 안 되지 징징거렸던 시간만큼 실력이 느는 것 같습니다.
'책으로만 배운 연애' 도입부 미쳤네요. 백점 만점에 만점 드립니다. 💯 👍 🥇

2021-10-19 00:23 UTC, Hyeon9mak commented on step4/README.md
> +빠르게 학습하고 적용하면 빈틈은 반드시 발생합니다. 빠른 피드백은 아교처럼 이 공백을 꼼꼼하게 메꿔줍니다.
회고 중독은 웨지인데

2021-10-19 00:23 UTC, Hyeon9mak commented on step4/README.md
> +저는 제가 좋아하는 환경을 찾았고 자신을 거기에 둠으로써 그리 힘들이지 않고 '열심히' 하고 있습니다.
- `최소한 저는 그렇습니다.` 이후에 `그래도 재밌을 때는 열심히 해요!`가 빠지면 조금 더 극적으로 보이지 않을까 싶어요!
- 우테코 환경에 대해 많은 이야기가 나왔으니, `밖에 나와서 남들과 함께 공부하는 순간` 대신 `밖으로 나와 크루들과 함께 공부하는 동안은`로 바뀌면 어떨까요?! 우리가 남이가~

2021-10-19 00:23 UTC, Hyeon9mak commented on step4/README.md
> +> 🤖씨유bot (갑자기 매우 진지하게) : 저는 근무하는 환경과 함께 일하는 사람들이 훨씬 중요해서요, 천만 원 이천만 원 정도에 직장을 옮길 것 같지 않네요.
실례가 안된다면 아이스크림 하나만 사주십시오

2021-10-19 00:23 UTC, Hyeon9mak commented on step4/README.md
> +그래서 저도 그렇다고 말하고 싶은 마음과 해봐야 변명이라는 마음 중간에서 어부버부애배배 하다가 퇴장했던 기억이 있습니다. (🤖 : 뭐지?)
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 뭐지? 너무 귀여움 🤣 👍

2021-10-19 00:23 UTC, Hyeon9mak commented on step4/README.md
> +그저 '계속적 소득활동'에 불과한 무엇인가에 행복의 열쇠가 있었다는 게 신기합니다.
회고홀릭인줄 알았더니... 충격!

2021-10-19 00:23 UTC, Hyeon9mak commented on step4/README.md
> +큰 성공을 거둔 타다, 예상치 못한 암초를 만난 타다, 법령으로 사업이 금지당한 타다... 새롭게 사업을 정비하고 다시 일어서기까지.
어떤 이유 때문에 '내가 이걸 볼 땐가'라는 생각이 들었는지 구체적인 예시도 제시되면 
그 마음도 공감되고, 그럼에도 의심을 한 방에 날릴 정도로 유익했다라는 느낌이 더 극적으로 전달될거 같아요!

2021-10-19 00:23 UTC, Hyeon9mak commented on step4/README.md
> +
어떤 일터에 갈지 막연하게 생각한 이후 뚜렷한 목표가 생긴걸까요?! 아니면 학습 외 취업 활동도 준비를 시작했다는 걸까요?!

2021-10-19 00:23 UTC, Hyeon9mak commented on step4/README.md
> +그러나 앞으로 남은 인생을 어떤 면으로 살아갈지는 행운에 맡기지 않으려 합니다. 행운을 필연으로 바꾸기 위해선 노력이 필요할 겁니다.
지금 찾아낸 주사위의 면이 웨지의 완전한 평면이 되기를~

2021-10-19 00:23 UTC, Hyeon9mak commented on step4/README.md
> +쉬지 않고 개발과 관련된 수다를 떨어댄 것을 통해 훈련된 것이라 생각해요. 사람이 별로 없는 엘리베이터를 보고 `null null하네` 라고 말했던 순간(구구가 `이건 empty()죠` 라고 정정해줌),
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2021-10-19 00:23 UTC, Hyeon9mak commented on step4/README.md
> +TCP 3 way handshake를 배운 후 지나가는 크루들에게 맥락 없이 "씬!(syn)" 외쳐대던 순간들이 떠오르네요. 받아주신 크루들 감사합니다.
NAK

2021-10-19 00:23 UTC, Hyeon9mak commented on step4/README.md
> +깨닫고 나니 무언가를 잘하는 사람을 보면 '저 사람은 저 분야에서 꾸준했구나.' 여기게 되었습니다. 그 꾸준함을 존중합니다. 자연스럽게 열등감도 '나도 꾸준하면 되겠구나.' 하는 근거 없는 자신감으로 바뀌었습니다.
👍 👍 👍

2021-10-19 08:26 UTC, Be-poz approved these changes
지난번에 이미 읽었었지만 또 읽었습니다! 수필 잘 읽고갑니다. 웨지라는 사람을 같은 크루로 만나게 돼서 정말 행운이라고 생각합니다. 앞으로도 연락 계속하면서 많이 뽑아먹을 거니깐 학습을 더욱 해두고 계시길 바랍니다. 후후

2021-10-19 08:26 UTC, Be-poz commented on step4/README.md
> +'발리고 오라'고 격려해 주는데요, 제 입장에선 성장을 바라는 응원이라고요.🤪
말씀하신대로 발리고... 왔습니다...

2021-10-19 08:26 UTC, Be-poz commented on step4/README.md
> +혼자선 20분도 집중 못 하지만 밖에 나와서 남들과 함께 공부하는 순간은 다섯시간이고 열 시간이고 재밌게 할 수 있습니다.
성능 좋은 일꾼이다!

2021-10-19 08:26 UTC, Be-poz commented on step4/README.md
> +> 🤖씨유bot (갑자기 매우 진지하게) : 저는 근무하는 환경과 함께 일하는 사람들이 훨씬 중요해서요, 천만 원 이천만 원 정도에 직장을 옮길 것 같지 않네요.
나는 정말 좋은 사람들과 일한다면 안가겠지만 그냥 평범한 느낌의 개발환경이라면 갈 것 같어

2021-10-19 08:26 UTC, Be-poz commented on step4/README.md
> +아니 무슨 거창하게 인생관까지? 네 저도 민망하긴 한데! `하고 싶은 말, 해도 되는구나.` 도 새롭게 얻은 인생관이라 시원하게 쏘겠습니다.
일단 저지르고 본다

2021-10-19 08:26 UTC, Be-poz commented on step4/README.md
> +좋은 사람들 속에서 지낸 지도 9개월이 되어갑니다. 저는 원래 아싸 체질입니다. 한 번씩 또라이 같아도
> 저는 원래 아싸 체질입니다.

인싸 특) 본인을 아싸라고 지칭함

2021-10-19 08:26 UTC, Be-poz commented on step4/README.md
> +TCP 3 way handshake를 배운 후 지나가는 크루들에게 맥락 없이 "씬!(syn)" 외쳐대던 순간들이 떠오르네요. 받아주신 크루들 감사합니다.
ㅋ 난 UDP ㅋ

2021-10-19 08:26 UTC, Be-poz commented on step4/README.md
> +최근에 우아한형제들 CEO 김범준님 특강에서도 김범준님의 '배민다움'을 여쭸는데, 조직의 중심이 되는 사람의 답변이 궁금했습니다. 리더조차도 회사의 단편이지만,
웨지의 '배민다움' 은 무엇인가요 ?

2021-10-19 10:32 UTC, qhals321 approved these changes
안녕하세요! 웨지!!!
너무나 잘 읽었어요!! 웨지는 항상 장난스러워보이면서도 모든 면에서 진지해보이기도 하고 해서 참 신기한 사람이에요!
그러다보니 장난스럽지만 엄청 믿음직스러운 동료라고 느껴지게 되네요!
항상 웨지의 개발 스킬도 너무너무 멋지지만 소프트 스킬이 정말 정말 멋지다고 생각이 들면서 배워야겠다는 생각도 엄청 많이 하게 되요!!
글 리뷰하러 왔지만 글 자체가 웨지를 너무 잘 표현해주는 것 같아서 감탄하면서 계속 읽게 되었네요!!
이제 남은 기간 조금 남았지만 계속 파이팅해요 우리!!!

2021-10-19 10:32 UTC, qhals321 commented on step4/README.md
> +학습 메타인지는 내가 무엇을 알고 있는지, 무엇을 학습해야 하는지 구체적으로 알고 있는 것을 뜻합니다.
오~ 처음에 학습 메타가 무엇인지 설명해주는 것이 너무 좋네요!!

2021-10-19 10:32 UTC, qhals321 commented on step4/README.md
> +요즘은 학습을 시작하기 전에 개념(이해해야 할 것), 사실(외워야 할 것), 연습(해봐야 할 것)을 미리 적어보고 학습을 시작하는 습관을 기르고 있어요!
오~ 저도 이 공부법에 완전 공감되네요!
이해해야할 것과 외워야 할 것 그리고 해봐야 할 것들을 명확하게 나눠서 접근하는 것이 정말 효율적인 것 같네요~!

2021-10-19 10:32 UTC, qhals321 commented on step4/README.md
> +'책으로만 배운 연애'라는 말이 있죠. 여러 매체를 통해 습득한 지식을 실제로 적용해보려 할 때 어려움을 겪는 경우가 있습니다.
에휴 저도 연애 박사인줄만 알았지 뭐에요

2021-10-19 10:32 UTC, qhals321 commented on step4/README.md
> +방어적인 태도는 건전한 피드백이 오가는 것을 막습니다. 상대가 나에게 위해를 가하려는 게 아니라는 신뢰,
방어적인 태도.. 정말 공감이 가네요!! 피드백을 무서워하면 안되겠다 라는 생각을 우테코 내에서 많이 생각하게 돼요!

2021-10-19 10:32 UTC, qhals321 commented on step4/README.md
> +빠르게 학습하고 적용하면 빈틈은 반드시 발생합니다. 빠른 피드백은 아교처럼 이 공백을 꼼꼼하게 메꿔줍니다.
저도 그렇게 생각했쥬

2021-10-19 10:32 UTC, qhals321 commented on step4/README.md
> +근성장의 기본원리는 점진적 과부하입니다. 근육을 한계에 다다르게 해 상처입혀야 새로운 근세포가 자라납니다.
정말 비유가 찰떡이게끔 시작하네요.. 멋져요!!

2021-10-19 10:32 UTC, qhals321 commented on step4/README.md
> +인간의 의지는 나약합니다. 최소한 저는 그렇습니다. 그래도 재밌을 때는 열심히 해요!
전 저 자체가 나약해서 ㅠㅠㅠㅠㅠㅠㅠㅠㅠ

2021-10-19 10:32 UTC, qhals321 commented on step4/README.md
> +> 🤖씨유bot (갑자기 매우 진지하게) : 저는 근무하는 환경과 함께 일하는 사람들이 훨씬 중요해서요, 천만 원 이천만 원 정도에 직장을 옮길 것 같지 않네요.
돈 많이 주는 곳에 좋은 사람들이 모일 것 같은 그런 느낌이랄까요

2021-10-19 10:32 UTC, qhals321 commented on step4/README.md
> +법에서 정의한 직업의 의미를 찾아보니 '생활의 기본적 수요를 충족시키기 위한 계속적 소득활동' 이네요.
참 첫 문장이 항상 임팩트 있어서 좋네요!!

2021-10-19 10:32 UTC, qhals321 commented on step4/README.md
> +### 사람은 주사위 같지만, 어떤 면을 보여줄 지는 내가 정할 수 있구나
너무 너무 너무 멋진말이네요!!!! 엄청 공감도 가고..!!

2021-10-19 10:32 UTC, qhals321 commented on step4/README.md
> +저는 우테코가 좋습니다. 빛나는 우테코에 제가 입성했다는 느낌을 주는 게 아니라, 저 스스로 빛날 수 있도록 도와주는 우테코라서 좋습니다.
너무 멋진말 가득하네요... 최고

2021-10-19 12:29 UTC, hsik0225 requested changes
안녕하세요 웨지 😄

글 잘 읽었습니다!
웨지가 다른 크루들과 이야기하는 것을 좋아하기 때문일까요?
글이 웨지와 대화하는 듯한 느낌을 받았어 재밌었어요.

간단히 몇 개 코멘트를 남겼어요.
확인 부탁드릴게요 :)

2021-10-19 12:29 UTC, hsik0225 commented on step4/README.md
> +요즘은 학습을 시작하기 전에 개념(이해해야 할 것), 사실(외워야 할 것), 연습(해봐야 할 것)을 미리 적어보고 학습을 시작하는 습관을 기르고 있어요!
```suggestion
요즘은 학습을 시작하기 전에 개념(이해해야 할 것), 사실(외워야 할 것), 연습(해봐야 할 것)을 미리 적어보는 습관을 기르고 있어요! 
```

`학습을 시작하기 전에` 라는 말이 앞에 나오니 뒤의 말은 빼는 건 어떨까요?

2021-10-19 12:29 UTC, hsik0225 commented on step4/README.md
> +'책으로만 배운 연애'라는 말이 있죠. 여러 매체를 통해 습득한 지식을 실제로 적용해보려 할 때 어려움을 겪는 경우가 있습니다.
'책으로만 배운 연애' 😆

2021-10-19 12:29 UTC, hsik0225 commented on step4/README.md
> +학습하는 환경과 적용을 하는 환경이 다르기 때문입니다. 이를 해소하기 위해선 적용과 학습을 병행해야 합니다.
저에게는 `환경`이라는 말이 집과 루터 회관과 같은 장소의 차이, 즉`주변 환경`과 같은 의미로 들리네요.

```suggestion
학습과 실습은 다르기 때문입니다. 이를 해소하기 위해선 학습과 실습을 병행해야 합니다. 
```

와 같이 `환경`이 아닌 다른 단어를 사용해보는 것은 어떨까요?

2021-10-19 12:29 UTC, hsik0225 commented on step4/README.md
> +일단 무작정 적용해보고 안 되면 학습 테스트도 만들어 보고~ 그래도 안 되면 코치들과 크루들을 물고 늘어지고! 왜 안 되지 징징거렸던 시간만큼 실력이 느는 것 같습니다.
`~`, `!`와 같은 문장 부호가 글을 무겁지 않게 만들어주네요 👍

2021-10-19 12:29 UTC, hsik0225 commented on step4/README.md
> +방어적인 태도는 건전한 피드백이 오가는 것을 막습니다. 상대가 나에게 위해를 가하려는 게 아니라는 신뢰,
저도 이 부분 많이 공감되네요.
피드백으로 인한 스트레스를 피하기 위해 피드백을 안하고 있진 않았는가 되돌아봐야겠어요!

2021-10-19 12:29 UTC, hsik0225 commented on step4/README.md
> +예전의 저라면 이런 사람도 있구나, 신기하네 하고 넘어갔을 겁니다. 하지만 레벨 2에는 '사랑하는 동료들'과 '하고 싶은 일'을 같이 할 수 있는 게 얼마나 행복한 일인지 깨달아 가고 있던 와중이었기 때문에, 그것을 알기 전의 마인드로 가볍게 말해버린 것이 너무나 부끄러웠습니다.
작은 따옴표로 감싸주면 웨지의 속마음이라는 것을 명확히 알 수 있을 것 같아요!

```suggestion
예전의 저라면 '이런 사람도 있구나, 신기하네.' 하고 넘어갔을 겁니다. 하지만 레벨 2에는 '사랑하는 동료들'과 '하고 싶은 일'을 같이 할 수 있는 게 얼마나 행복한 일인지 깨달아 가고 있던 와중이었기 때문에, 그것을 알기 전의 마인드로 가볍게 말해버린 것이 너무나 부끄러웠습니다.
```

2021-10-19 12:29 UTC, hsik0225 commented on step4/README.md
> +그래서 저도 그렇다고 말하고 싶은 마음과 해봐야 변명이라는 마음 중간에서 어부버부애배배 하다가 퇴장했던 기억이 있습니다. (🤖 : 뭐지?)
`어부버부애배배` 
그 상황을 너무 잘 나타내는 의태어인 것 같아요 😆

2021-10-19 12:29 UTC, hsik0225 commented on step4/README.md
> +그리고 최근 '타다: 대한민국 스타트업의 초상'이라는 다큐멘터리 영화를 보게 되었습니다. 우연히 시사회 표를 얻게 되어 '내가 이걸 볼 땐가' 반신반의하며 참석했습니다.
이전 문단과 이어지는 내용이 아니므로 `그리고`를 빼는 게 어떨까요?

2021-10-19 12:29 UTC, hsik0225 commented on step4/README.md
> +영화엔 구성원들의 희노애락이 그대로 담겨있었고 거기엔 단순히 '내 수입원이 위험해' 이상의, 일에 대한 몰입과 열정이 느껴졌습니다.
[단어장 '희노애락'과 '희로애락' 중 바른 표기는?](https://news.korean.go.kr/index.jsp?control=page&part=view&idx=10023&preview=null)

```suggestion
영화엔 구성원들의 희로애락이 그대로 담겨있었고 거기엔 단순히 '내 수입원이 위험해' 이상의, 일에 대한 몰입과 열정이 느껴졌습니다.
```

2021-10-19 12:29 UTC, hsik0225 commented on step4/README.md
> +아니 무슨 거창하게 인생관까지? 네 저도 민망하긴 한데! `하고 싶은 말, 해도 되는구나.` 도 새롭게 얻은 인생관이라 시원하게 쏘겠습니다.
오타가 맞겠죠?

```suggestion
아니 무슨 거창하게 인생관까지? 네 저도 민망하긴 한데! `하고 싶은 말, 해도 되는구나.` 도 새롭게 얻은 인생관이라 시원하게 쓰겠습니다.
```

2021-10-19 12:29 UTC, hsik0225 commented on step4/README.md
> +쉬지 않고 개발과 관련된 수다를 떨어댄 것을 통해 훈련된 것이라 생각해요. 사람이 별로 없는 엘리베이터를 보고 `null null하네` 라고 말했던 순간(구구가 `이건 empty()죠` 라고 정정해줌),
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2021-10-21 13:35 UTC, DWL5 approved these changes
웨지 월욜날 글 한번 읽었었는데, 
이번에 다른 크루들이 더 글을 남겨 줘서 진짜 재밌게 또 읽었다..

웨지 글 진짜 잘쓰는걸...?

어떤 조직이 있으면 소속감을 가지는게 굉장히 중요하다고 생각해!
이번 우테코 3기에서는 웨지가 이런 측면에서 큰일을 하지 않았나 싶음!!

웨지 덕분에 네트워크 스터디도 재밌게하고 월욜 클럽도 재밌게하고....
덕분에 우테코 3기 생각하면 떠오르는 것들이 많아 졌어!!

지금 까지 행보를 보면 어느 조직에서나 필요한 사람인 것 같아!!!!!!!!

글 다 읽고 보니 님아 진짜 대단한 사람인듯....
언제나 빛나는 웨지 되길 응원할게 화이팅!

2021-10-21 13:35 UTC, DWL5 commented on step4/README.md
> +요즘은 학습을 시작하기 전에 개념(이해해야 할 것), 사실(외워야 할 것), 연습(해봐야 할 것)을 미리 적어보고 학습을 시작하는 습관을 기르고 있어요!
오 이거 포스트잇에 적어놔야지!

2021-10-21 13:35 UTC, DWL5 commented on step4/README.md
> +방어적인 태도는 건전한 피드백이 오가는 것을 막습니다. 상대가 나에게 위해를 가하려는 게 아니라는 신뢰,
이 말 정말 공감간다!!!!! 
뭐든지 진심으로 행동해야 정말 좋은 피드백이 오갈 수 있는 듯..
나는 아직도 어렵지만 우테코와서 많이 좋아진듯 해!!!!!

2021-10-21 13:35 UTC, DWL5 commented on step4/README.md
> +근성장의 기본원리는 점진적 과부하입니다. 근육을 한계에 다다르게 해 상처입혀야 새로운 근세포가 자라납니다.
귀검사 칼 생각난당
No pain No gain

2021-10-21 13:35 UTC, DWL5 commented on step4/README.md
> +인간의 의지는 나약합니다. 최소한 저는 그렇습니다. 그래도 재밌을 때는 열심히 해요!
ㅜㅜㅜㅜㅜㅜㅜ 나봄힘내

2021-10-21 13:35 UTC, DWL5 commented on step4/README.md
> +그저 '계속적 소득활동'에 불과한 무엇인가에 행복의 열쇠가 있었다는 게 신기합니다.
베짱이 웨지 상상이 안가......
베짱이 시절에도 아침 7시에 일어나서 운동은 갔을 듯....

2021-10-21 13:35 UTC, DWL5 commented on step4/README.md
> +아니 무슨 거창하게 인생관까지? 네 저도 민망하긴 한데! `하고 싶은 말, 해도 되는구나.` 도 새롭게 얻은 인생관이라 시원하게 쏘겠습니다.
페르소나 따위 집어치웡!

2021-10-21 13:35 UTC, DWL5 commented on step4/README.md
> +좋은 사람들 속에서 지낸 지도 9개월이 되어갑니다. 저는 원래 아싸 체질입니다. 한 번씩 또라이 같아도
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2021-10-21 13:35 UTC, DWL5 commented on step4/README.md
> +### 사람은 주사위 같지만, 어떤 면을 보여줄 지는 내가 정할 수 있구나
상상이 안가... 내향적인 웨지

우테코 3기 예비 단톡방에서도 프로필사진에 찐얼굴과 찐본명으로 들어와서 기억나는디 성시형
우테코가 많은 좋은 영향을 준 건 인정 👍👍👍👍👍👍👍👍

2021-10-21 13:35 UTC, DWL5 commented on step4/README.md
> +그러나 앞으로 남은 인생을 어떤 면으로 살아갈지는 행운에 맡기지 않으려 합니다. 행운을 필연으로 바꾸기 위해선 노력이 필요할 겁니다.
주사위 단락은 진짜 글 잘썼다.. 머리 한대 맞은듯..

2021-10-21 13:35 UTC, DWL5 commented on step4/README.md
> +TCP 3 way handshake를 배운 후 지나가는 크루들에게 맥락 없이 "씬!(syn)" 외쳐대던 순간들이 떠오르네요. 받아주신 크루들 감사합니다.
독고다이 비연결지향 파즈

2021-10-21 13:35 UTC, DWL5 commented on step4/README.md
> +깨닫고 나니 무언가를 잘하는 사람을 보면 '저 사람은 저 분야에서 꾸준했구나.' 여기게 되었습니다. 그 꾸준함을 존중합니다. 자연스럽게 열등감도 '나도 꾸준하면 되겠구나.' 하는 근거 없는 자신감으로 바뀌었습니다.
가즈아앙!!!!!

2021-10-21 13:35 UTC, DWL5 commented on step4/README.md
> +깨닫고 나니 무언가를 잘하는 사람을 보면 '저 사람은 저 분야에서 꾸준했구나.' 여기게 되었습니다. 그 꾸준함을 존중합니다. 자연스럽게 열등감도 '나도 꾸준하면 되겠구나.' 하는 근거 없는 자신감으로 바뀌었습니다.
가즈아앙!!!!!

2021-10-21 13:55 UTC, sihyung92 commented on step4/README.md
> +최근에 우아한형제들 CEO 김범준님 특강에서도 김범준님의 '배민다움'을 여쭸는데, 조직의 중심이 되는 사람의 답변이 궁금했습니다. 리더조차도 회사의 단편이지만,
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 즐기는거요! 주위사람도 같이 즐길 수 있게 뭐 많이하고 ^_^

2021-10-21 14:22 UTC, sihyung92 commented
나봄 세세하게 읽어주고 피드백 해줘서 고마워~~!
시드와 현구막도 좋은 피드백 너무 고마워!! 내가 좋아하는 글인데 더 나아지는데 도움을 줘서~~!
수리 검프 포모 조앤 파즈 지그 멍토 피카 도 읽고 응원해줘서 너무너무너무 고맙습니다 🙇🏻
기타 읽어준 크루들도 고마워요~~~
피드백 몽땅 환영

2021-10-22 17:56 UTC, pkeugine commented on step4/README.md
> +왜냐하면 공부하는 법, 직업을 대하는 태도, 심지어는 인생관까지 바꾼 계기가 되었기 때문이에요.
이거 나도 공감!
웨지 보면서 항상 '우테코 들어와서 이런 사람 만나길 잘했다' 생각합니다 ㅋㅋㅋ

2021-10-22 18:11 UTC, pkeugine commented
웨하~
글 잘 읽고 갑니다 😁
웨형과 우테코 함께 하면서 많이 배우고, 도움도 많이 받고, 느끼는 것도 정말 많았어.
형이 있는 곳이라면 그 곳이 좋은 직장이라고 할 수 있을 정도로 정말 듬직한 사람이 아닐까 싶다.
과연 미래의 웨지는 어떤 모습일까 궁금할 정도로 대단한 사람이야 ㅋㅋㅋㅋ
우테코에서 함께 했던 모든 것들 정말 고맙고 앞으로도 이런 멋진 웨형의 모습 계속해서 보여주길!!

2021-10-23 07:26 UTC, jum0 reviewed
웨지 나 주모~~

설명도 잘하고, 성격도 좋고, 왜 그냥 좋은 것은 다 갖고 있는거야~~?
심지어 글도 읽으면서 많은 생각할 수 있도록 해주네.. 다 좋아..❤️

정말 얼마 남지 않았는데, 마지막까지 화이팅하자!!!

2021-10-24 04:08 UTC, wannte approved these changes
재밌고 감동있는 글이네요 ㅎㅎ. 잘 읽었습니다!

간단한 피드백 남겼습니다. 반영은 자유입니다~

2021-10-24 04:08 UTC, wannte commented on step4/README.md
> +### comfort zone에 머물지 않기
Learning With Doing 와 통일성을 위해, 단어의 첫글자는 대문자는 어떨까요?

2021-10-24 04:08 UTC, wannte commented on step4/README.md
> +그래서 저도 그렇다고 말하고 싶은 마음과 해봐야 변명이라는 마음 중간에서 어부버부애배배 하다가 퇴장했던 기억이 있습니다. (🤖 : 뭐지?)
`어부버부애배배` ㅋㅋㅋㅋ 상황을 잘 나타내는 건 맞는데, 읽는 데 어떻게 읽어야할지 모르겠는 느낌..?

2021-10-24 04:08 UTC, wannte commented on step4/README.md
> +그저 '계속적 소득활동'에 불과한 무엇인가에 행복의 열쇠가 있었다는 게 신기합니다.
```suggestion
그저 '소득활동'에 불과한 무엇인가에 행복의 열쇠가 있었다는 게 신기합니다.
```
위의 직업의 의미에서의 표현을 다시 언급한 부분은 좋지만, 소득 활동에만 초점을 두는 것은 어떨까요?

2021-10-24 04:08 UTC, wannte commented on step4/README.md
> +그리고 최근 '타다: 대한민국 스타트업의 초상'이라는 다큐멘터리 영화를 보게 되었습니다. 우연히 시사회 표를 얻었는데요, 프로젝트다 미션이다 매우 바쁘던 터라 '내가 이걸 볼 땐가' 반신반의하며 참석했습니다.
ㅋㅋ 까먹었는데, 내일 아침 8시 10분에 예약해버렸다!

2021-10-24 04:08 UTC, wannte commented on step4/README.md
> +그러나 앞으로 남은 인생을 어떤 면으로 살아갈지는 행운에 맡기지 않으려 합니다. 행운을 필연으로 바꾸기 위해선 노력이 필요할 겁니다.
재밌는 글이네요!

저는 이상하게도 웨지의 다른 주사위 면도 궁금해지네요. 지금보다 웨지가 더 좋아하는 주사위  면이 많이 기다리고 있지 않을까요?

2021-10-24 04:08 UTC, wannte commented on step4/README.md
> +깨닫고 나니 무언가를 잘하는 사람을 보면 '저 사람은 저 분야에서 꾸준했구나.' 여기게 되었습니다. 그 꾸준함을 존중합니다. 자연스럽게 열등감도 '나도 꾸준하면 되겠구나.' 하는 근거 없는 자신감으로 바뀌었습니다.
즐겼기에 꾸준할 수 있었던 것 아닐까요? :+1:

2021-10-24 04:08 UTC, wannte commented on step4/README.md
> +읽으면서 `우테코가 사람 하나 살렸네` 싶으실 것 같네요.🥳
`웨지가 우테코 하나 살렸네`~

2021-10-24 12:51 UTC, hsik0225 approved these changes
피드백 반영한 거 확인했습니다.
이만 어프로브할게요!!

2021-10-24 13:25 UTC, binghe819 approved these changes
와우! 웨지!

글 너무 잘 읽었어요!! 너무 멋진말이 많아서 시간 가는 줄 모르고 봤네요!

`우테코가 사람 하나 살렸네`라고 적어주셨어요! 

제 생각엔 웨지가 있기에 우테코 3기가 좋은 분위기가 유지된다고 생각합니다 :)

멋진 웨지 항상 응원할게요 👍 👍 

> 피드백 늦어서 미안해요ㅠ

2021-10-24 13:25 UTC, binghe819 commented on step4/README.md
> +학습 메타인지는 내가 무엇을 알고 있는지, 무엇을 학습해야 하는지 구체적으로 알고 있는 것을 뜻합니다.
오! 저도 나봄 의견에 동의! 무엇인지 먼저 설명해주는거 너무 좋네요

2021-10-24 13:25 UTC, binghe819 commented on step4/README.md
> +학습 메타인지는 효과적인 학습 로드맵을 세우는 데 필수적입니다. 이 공부를 왜 해야 하는지(웨지?), 무엇을 배워야 하는지, 어떻게 해야 하는지에 대한 설계는 공부 그 자체만큼이나 중요하다는 것을 알게 되었네요!
개인적으론 `설계`라는 말이 조금 와닿지 않는 것 같아요! `고민`, `생각`이 더 자연스러운 듯 합니다!

(물론 개인적 의견ㅎㅎ)

2021-10-24 13:25 UTC, binghe819 commented on step4/README.md
> +요즘은 학습을 시작하기 전에 개념(이해해야 할 것), 사실(외워야 할 것), 연습(해봐야 할 것)을 미리 적어보는 습관을 기르고 있어요!
오! 좋은 방법인 것 같아요! 벤치마킹해봐야겠네요 👍

2021-10-24 13:25 UTC, binghe819 commented on step4/README.md
> +'책으로만 배운 연애'라는 말이 있죠. 여러 매체를 통해 습득한 지식을 실제로 적용해보려 할 때 어려움을 겪는 경우가 있습니다.
`책으로만 배운 연애` 개발에도 그대로 적용시킬 수 있는 좋은 비유인 것 같아요!

2021-10-24 13:25 UTC, binghe819 commented on step4/README.md
> +빠르게 학습하고 적용하면 빈틈은 반드시 발생합니다. 빠른 피드백은 아교처럼 이 공백을 꼼꼼하게 메꿔줍니다.
ㅇㅈ

2021-10-24 13:25 UTC, binghe819 commented on step4/README.md
> +방어적인 태도는 건전한 피드백이 오가는 것을 막습니다. 상대가 나에게 위해를 가하려는 게 아니라는 신뢰,
저두 이 부분 공감 많이 가네요!! 제 자신을 되돌아보게 되돌봐야겠어요..

4기한테 꼭 말해주면 좋을 듯 합니다 👍

2021-10-24 13:25 UTC, binghe819 commented on step4/README.md
> +근성장의 기본원리는 점진적 과부하입니다. 근육을 한계에 다다르게 해 상처입혀야 새로운 근세포가 자라납니다.
너무 멋진 비유네요! 👍  웨지 비유 엄청 잘하시네요!

2021-10-24 13:25 UTC, binghe819 commented on step4/README.md
> +잘 알고 있던 CS 복습을 통해서는 '공부했다'는 정신적 포만감은 느낄지언정, 진짜 성장하긴 어렵습니다.
'컴포트 존을 벗어나라'의 굉장히 좋은 비유인 것 같아요! 👍

2021-10-24 13:25 UTC, binghe819 commented on step4/README.md
> +저는 제가 좋아하는 환경을 찾았고 자신을 거기에 둠으로써 그리 힘들이지 않고 '열심히' 하고 있습니다.
```suggestion
저는 제가 좋아하는 환경을 찾았고 자신을 거기에 위치시킴으로써 그리 힘들이지 않고 '열심히' 하고 있습니다.
```
이게 더 자연스러운 것 같아서 피드백 남겨요~

2021-10-24 13:25 UTC, binghe819 commented on step4/README.md
> +내일 오늘보다 조금 더 나아진 '나'를 만들기 위해 노력하는 크루들을 보면서 조금씩 감화되어 갔습니다. 동경했고 닮아지기 위해 노력했습니다.
```suggestion
오늘보다 조금 더 나아진 내일의 '나'를 만들기 위해 노력하는 크루들을 보면서 조금씩 감화되어 갔습니다. 동경했고 닮아지기 위해 노력했습니다.
```
이렇게 바꾸는게 더 자연스러워보여서 피드백 남겨요!

2021-10-24 13:25 UTC, binghe819 commented on step4/README.md
> +베짱이인 줄 알았는데 워커홀릭이었을 줄이야. 개발 이야기 할 때가 제일 재밌고 제가 아는 것으로 남을 돕는 순간이 가장 뿌듯합니다.
`제가 아는 것으로 남을 돕는 순간이 가장 뿌듯합니다. `

교육자 👍

2021-10-24 13:25 UTC, binghe819 commented on step4/README.md
> +쉬지 않고 개발과 관련된 수다를 떨어댄 것을 통해 훈련된 것이라 생각해요. 사람이 별로 없는 엘리베이터를 보고 `null null하네` 라고 말했던 순간(구구가 `이건 empty()죠` 라고 정정해줌),
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2021-10-25 00:39 UTC, sihyung92 commented on step4/README.md
> +요즘은 학습을 시작하기 전에 개념(이해해야 할 것), 사실(외워야 할 것), 연습(해봐야 할 것)을 미리 적어보는 습관을 기르고 있어요!
학습 동기 유지하는데 상당히 도움되는 중~! 한번 하고가면 방향이 보이고 목적이 분명해져서 좋은거같아

2021-10-25 00:40 UTC, sihyung92 commented on step4/README.md
> +근성장의 기본원리는 점진적 과부하입니다. 근육을 한계에 다다르게 해 상처입혀야 새로운 근세포가 자라납니다.
음화화

2021-10-25 00:41 UTC, sihyung92 commented on step4/README.md
> +내일 오늘보다 조금 더 나아진 '나'를 만들기 위해 노력하는 크루들을 보면서 조금씩 감화되어 갔습니다. 동경했고 닮아지기 위해 노력했습니다.
조와요 조와요 좋은 피드백!!

2021-10-25 00:42 UTC, sihyung92 commented on step4/README.md
> +읽으면서 `우테코가 사람 하나 살렸네` 싶으실 것 같네요.🥳
유지만 잘 하면 대성공이야~~ ㅎ_ㅎ

2021-10-25 00:44 UTC, sihyung92 commented on step4/README.md
> +### comfort zone에 머물지 않기
조와요 조와요

2021-10-25 00:55 UTC, sihyung92 commented on step4/README.md
> +그저 '계속적 소득활동'에 불과한 무엇인가에 행복의 열쇠가 있었다는 게 신기합니다.
'계속적 소득활동'이라는 말이 보편적이지 않은데서 오는 불편함을 의도했어요! 사전적 의미에서의 직업과 제가 느끼는 직업이 다르다는걸 부각하기 위해서~~

2021-10-25 01:10 UTC, NewWisdom reviewed
하이 포테이토 ~
모든 사람들의 글에 방문해 일일히 코멘트 달아주는 정성보고 저도 찾아왔어여 ㅎㅎㅎ
크루들에게 쏟는 정성 보면서 항상 대단하다고 느끼고, 참으로 많이 배웁니다 👏👏
글 자체가 정말 웨지같아서 흥미롭게 읽었어요 ㅎㅎㅎ
우울증 치료를 했던 잠할 > 잠콩의 시작으로 월요클럽 탄생한게 엊그제 같은데 벌써 시간이...... 흙
무맥락으로 던지는 말들에 웃기도 하지만 가끔 진지하게 조언해주는 멋좽이 🔥🔥
천하무적 웻지 마지막까지 화이팅 월요클럽도 화이팅 👏

2021-10-25 05:23 UTC, yujo11 reviewed
웨지 글 잘 읽었어요!

우테코 과정에서 웨지가 느꼈던 인사이트들을 공유해줘서 고마워요!  👍 👍👍

2021-10-25 05:23 UTC, yujo11 commented on step4/README.md
> +> 🤖씨유bot (갑자기 매우 진지하게) : 저는 근무하는 환경과 함께 일하는 사람들이 훨씬 중요해서요, 천만 원 이천만 원 정도에 직장을 옮길 것 같지 않네요.
와 정말 멋지네요 근무하는 환경과 함께 일하는 사람들

2021-10-25 05:23 UTC, yujo11 commented on step4/README.md
> +저는 우테코가 좋습니다. 빛나는 우테코에 제가 입성했다는 느낌을 주는 게 아니라, 저 스스로 빛날 수 있도록 도와주는 우테코라서 좋습니다.
저는 웨지가 좋아요 😆

2021-10-25 05:23 UTC, yujo11 commented on step4/README.md
> +쉬지 않고 개발과 관련된 수다를 떨어댄 것을 통해 훈련된 것이라 생각해요. 사람이 별로 없는 엘리베이터를 보고 `null null하네` 라고 말했던 순간(구구가 `이건 empty()죠` 라고 정정해줌),
웨지의 설명을 들을 때마다 흐렸던 개념이 명확해져서 좋았는데 처음부터 설명을 잘 하지는 않았었군요!

2021-11-03 12:04 UTC, devJang approved these changes
>읽으면서 우테코가 사람 하나 살렸네 싶으실 것 같네요.🥳 저는 우테코가 좋습니다. 빛나는 우테코에 제가 입성했다는 느낌을 주는 게 아니라, 저 스스로 빛날 수 있도록 도와주는 우테코라서 좋습니다.

ㅋㅋ굉장히 재미있는 글을 작성해주셨네요
웨지 그동안 고생 많으셨고 앞으로 훌륭한 개발자로 잘 성장하실거라 믿습니다
아 그리고 위에 연애 얘기도 적어주셨는데요.
너무 개발만하지마시고 가끔은 연애도하시길..!

2021-11-03 12:05 UTC, merged