[글쓰기 4단계] 코기(김진환) 미션 제출합니다.
woowacourse/woowa-writing-3 pull request #254
Opened 2021-10-16 20:12 UTC by ecsimsw

잘부탁드립니다.  [링크](https://github.com/ecsimsw/woowa-writing-3/blob/ecsimsw/내가%20꿈꾸는%20프로그래머로서의%20삶.md)

@seovalue 
@ddongule
@yujo11
@Rok93
@Livenow14

2021-10-17 00:26 UTC, sihyung92 commented
와 직접 만든 샤프 ㅋㅋㅋㅋㅋㅋㅋㅋㅋ 발명왕 코기 라고 부르겟쓰

사람을 아끼는 코기가 드러나는 글이라서 재밌게 보구 감니돠

2021-10-17 10:00 UTC, seovalue approved these changes
안녕하세요, 코기! 조앤이에요 ㅎㅎ
코기의 진심이 담긴 글 잘 읽었어요, 주제와도 걸맞게 좋은 내용을 작성해주셨다고 생각해요.
한가지 코멘트 남겨보았는데 제 생각인지라 그대로 유지해도 좋다고 생각해서, 바로 어프루브 할게요!
바쁜 와중 좋은 글 쓰시느라 고생 많으셨어요! 
남은 우테코 기간도 응원할게요 🏆 화이팅!

2021-10-17 10:00 UTC, seovalue commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +책장에는 추리 소설이나 퀴즈 책만 있었고, 장기, 체스가 세상에서 가장 재밌는 게임이었으며, 수학 문제를 푸는 희열에 중고등학교 때는 솔직히 수학만 했다.
오.. 엄청난데요? 역시 떡잎부터 👍

2021-10-17 10:00 UTC, seovalue commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +그 작은 샤프도 내가 만들었었다.
코기가 만든 샤프.. 궁금하네요 👀

2021-10-17 10:00 UTC, seovalue commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +그저 앞에서 말한 행복을 느낄 수 있는 것들, 문제 사항을 해결하면서 즐거움을 느낄 수 있다면, 아이디어를 실현할 수 있다면, 사람들과 함께 일을 하고, 그들에게 긍정적인 영향을 줄 수 있다면, 정말 그걸로 만족스런 삶이 될 것 같다.
코기의 생각이 담긴 정말 좋은 문장이라고 생각해요. 하지만 쉼표로 자주 이어져있어서 두 문장 정도로 나누어도 좋을 것 같다는 생각이 들어요! ㅎㅎ

2021-10-17 10:00 UTC, seovalue commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +결론은 다 필요 없고 일을 즐길 줄 아는 개발자로 살고 싶다. 하루에 행복을 느끼며 재밌게 일 할 수 있는 삶을 살고 싶다.
그런 삶을 보낼 코기를 응원할게요 🚀 화이팅! ㅎㅎ

2021-10-17 11:25 UTC, Rok93 requested changes
코기 최근 근로 일로 자주 뵙었는데, 글쓰기 미션에서 만나게 돼서 반갑네요 🤗 
`코기가 꿈꾸는 개발자로서의 삶`을 알게된 좋은 계기었네요 😃 
지금의 스탠스로 꾸준히 나아가신다면 코기가 꿈꾸는 삶이 먼 미래가 아닐거라 생각해요😉 
맞춤법 관련해서 몇몇 코멘트 남겨주셨는데!  시간 되실 때, 반영해주시면 좋을 것 같아요. 
다른 부분은 크게 드릴 코멘트가 없어서 🤔 다음에 한번 더 읽어보면서 (될 수 있으면) 다른 의견을 더 드려보려고 해요 😃

2021-10-17 11:25 UTC, Rok93 commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +사람들이랑 어울리면서 에너지를 얻고, 내가 얻은 에너지를 그 사람에게도 전달해주고 싶다는 욕구가 큰 것 같다. 그런 상호작용이 느껴질 때 행복하다.
이 문구는 코기가 정말 이런 사람이라는 것을 많이 느끼는 것 같아요 😃

2021-10-17 11:25 UTC, Rok93 commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +그저 앞에서 말한 행복을 느낄 수 있는 것들, 문제 사항을 해결하면서 즐거움을 느낄 수 있다면, 아이디어를 실현할 수 있다면, 사람들과 함께 일을 하고, 그들에게 긍정적인 영향을 줄 수 있다면, 정말 그걸로 만족스런 삶이 될 것 같다.
이미 우테코에서도 코기가 만족하는 삶들을 실현중인 것 같아요 🤗
지금도 코기의 번뜩이는 아이디어와 코기의 긍정적인 영향력... 저는 특히나 근로활동을 같이하다보니 그런 부분을 더더욱 많이 느끼고 있어요!!  😁
나중에 현업으로 나간 코기는 정말 어떤 개발자가 될지 궁금해지네요 👍

2021-10-17 11:25 UTC, Rok93 commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +죄다 과학자나 대통령을 꿈꾸던 주변 친구들이 하나둘씩 현실적인 장래희망을 갖게 될 때 까지도 나는 발명가를 꿈꿨다.
`장래희망`은 `장래 희망` 으로 띄어써야한다고 하네요! 😉
`때 까지도` 는 범위의 끝을 나타내는 '-까지'는 조사이기 때문에 앞 말과 항상 붙여써야해서 `때까지도`로 붙여써야한다고 해요! 🤗
```suggestion
죄다 과학자나 대통령을 꿈꾸던 주변 친구들이 하나둘씩 현실적인 장래 희망을 갖게 될 때까지도 나는 발명가를 꿈꿨다. 
```

2021-10-17 11:25 UTC, Rok93 commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +그리고 사람을 좋아한다. 그냥 사람들과 함께 하는게 너무 재밌다. 내가 좋아하는 사람들과 웃고 떠들면서 행복함을 느낀다.
`하는게`라는 표현은 조사를 잘못 쓴 표현이라고해요!  아래와 같이 변경해보면 어떨까요? 🤔
```suggestion
그리고 사람을 좋아한다. 그냥 사람들과 함께 하는 게 너무 재밌다. 내가 좋아하는 사람들과 웃고 떠들면서 행복함을 느낀다. 
```

2021-10-17 11:25 UTC, Rok93 commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +그저 앞에서 말한 행복을 느낄 수 있는 것들, 문제 사항을 해결하면서 즐거움을 느낄 수 있다면, 아이디어를 실현할 수 있다면, 사람들과 함께 일을 하고, 그들에게 긍정적인 영향을 줄 수 있다면, 정말 그걸로 만족스런 삶이 될 것 같다.
-스럽다, -답다 등은 `-스러운`, `-다운`으로 는 것이 바른 활용이라고해요! 😃

```suggestion
그저 앞에서 말한 행복을 느낄 수 있는 것들, 문제 사항을 해결하면서 즐거움을 느낄 수 있다면, 아이디어를 실현할 수 있다면, 사람들과 함께 일을 하고, 그들에게 긍정적인 영향을 줄 수 있다면, 정말 그걸로 만족스러운 삶이 될 것 같다. 
```

2021-10-17 11:25 UTC, Rok93 commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +결론은 다 필요 없고 일을 즐길 줄 아는 개발자로 살고 싶다. 하루에 행복을 느끼며 재밌게 일 할 수 있는 삶을 살고 싶다.
일을 즐길 줄 아는 개발자라... 제가 아는 개발자 중에서는 코기가 대표적인 사례라고 생각해요 😃
앞으로의 코기도 그런 개발자겠죠?  
믿쑵니다 🙏

2021-10-19 01:10 UTC, Livenow14 approved these changes
나는 어떨때 행복할까? 에 대한 고민에 코기만의 정의를 내린거 같아! 
글을 읽으면서 "이사람 진짜 사람 좋아하네, 개발을 즐길 줄 아네"라고 생각했어 ㅋㅋㅋㅋ 
평소에 생각했던 너와 글에서 느껴지는 너가 다르지 않아서 좋다. :) 
너랑 같이 개발을 즐길 줄 아는 개발자가 되고 싶네 ㅎㅎㅎ 

간단한 피드백남겼어 😊

2021-10-19 01:10 UTC, Livenow14 commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +
```suggestion
풀이를 고민하고 딱 해결했을 때의 그 쾌감, 그리고 그걸로 주변 친구들에게 받던 인정이 그렇게 좋았다. 다른 어느 때보다 재밌었다.
```
요렇게 바꿔도 좋은 문장이 될듯요 ㅎㅎ

2021-10-19 01:10 UTC, Livenow14 commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +그리고 사람을 좋아한다. 그냥 사람들과 함께 하는게 너무 재밌다. 내가 좋아하는 사람들과 웃고 떠들면서 행복함을 느낀다.
사람을 좋아하는 코기를 좋아하는 나 ㅎㅎ

2021-10-19 01:10 UTC, Livenow14 commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +다른 사람들이 봤을 때 조금 덜 대단해도 행복할 수 있는 개발자가 되고 싶다.
```suggestion
### 대단한 사람과 행복한 사람
많은 사람들에게 인정받는 대단한 프로그래머가 되고 싶지는 않다. 
사람들 앞에서 콧대를 세울 수 있는 직장이나 연봉을 바라지도 않고, 한 분야에 일인자가 되어 유명해지거나, 누군가의 위인이 되지 않아도 된다. 
조금 덜 대단해도 행복할 수 있는 개발자가 되고 싶다. 
```
이렇게 바꿔도 나름 괜찮을듯?!

2021-10-19 01:10 UTC, Livenow14 commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +
재미를, 행복을 아는 개발자. 
같이 즐기며 행복하게 개발하고 싶네 :) 나 나중에 뽑아줄거지? ㅎ

2021-10-19 01:10 UTC, Livenow14 commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +결론은 다 필요 없고 일을 즐길 줄 아는 개발자로 살고 싶다. 하루에 행복을 느끼며 재밌게 일 할 수 있는 삶을 살고 싶다.
정말 코기라면 그럴거같아. 이미 즐기고 있고, 
같은 미래를 그려 나간다는게 행복이다 :)

2021-10-19 08:47 UTC, Be-poz approved these changes

2021-10-19 08:47 UTC, Be-poz commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +책장에는 추리 소설이나 퀴즈 책만 있었고, 장기, 체스가 세상에서 가장 재밌는 게임이었으며, 수학 문제를 푸는 희열에 중고등학교 때는 솔직히 수학만 했다.
모태 이과다 !!

2021-10-19 08:47 UTC, Be-poz commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +그저 즐겁게 개발하고 싶다. 직장이나 연봉, 유명세는 그 부가적인 가치가 되지 주가 되는 요소가 되진 않았으면 한다.
마인드 진짜 믓지다 👍

2021-10-19 08:47 UTC, Be-poz commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +결론은 다 필요 없고 일을 즐길 줄 아는 개발자로 살고 싶다. 하루에 행복을 느끼며 재밌게 일 할 수 있는 삶을 살고 싶다.
멋있네....... 😢

2021-10-19 08:47 UTC, Be-poz commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +죄다 과학자나 대통령을 꿈꾸던 주변 친구들이 하나둘씩 현실적인 장래희망을 갖게 될 때 까지도 나는 발명가를 꿈꿨다.
기가막힌 서비스를 발명할 코기!

2021-10-19 17:12 UTC, daum7766 reviewed
안녕하세요 코기
순회왔습니다.

글을 읽으면서 코기가 원하는 목표가 어떤건지 알수 있었어요
앞으로 코기가 스트레스 덜 받으면서 행복한 프로그래머가 되면 좋겠네요!

앞으로 남은 기간 화이팅입니다

2021-10-19 17:12 UTC, daum7766 commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +책장에는 추리 소설이나 퀴즈 책만 있었고, 장기, 체스가 세상에서 가장 재밌는 게임이었으며, 수학 문제를 푸는 희열에 중고등학교 때는 솔직히 수학만 했다.
와... 찐이네요?

2021-10-19 17:12 UTC, daum7766 commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +죄다 과학자나 대통령을 꿈꾸던 주변 친구들이 하나둘씩 현실적인 장래희망을 갖게 될 때 까지도 나는 발명가를 꿈꿨다.
기가막힌 언어를 발명할 코기!

2021-10-19 17:12 UTC, daum7766 commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +그 작은 샤프도 내가 만들었었다.
샤프를 만드셨다니? 역시 코기다

2021-10-19 17:12 UTC, daum7766 commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +그리고 사람을 좋아한다. 그냥 사람들과 함께 하는게 너무 재밌다. 내가 좋아하는 사람들과 웃고 떠들면서 행복함을 느낀다.
고백인가요? ㅋㅋ

2021-10-19 17:12 UTC, daum7766 commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +다른 사람들이 봤을 때 조금 덜 대단해도 행복할 수 있는 개발자가 되고 싶다.
가치를 외부적 요인에 두지 않는군요! 대단합니다.

2021-10-20 11:37 UTC, ecsimsw commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +결론은 다 필요 없고 일을 즐길 줄 아는 개발자로 살고 싶다. 하루에 행복을 느끼며 재밌게 일 할 수 있는 삶을 살고 싶다.
응원 감사합니다!!
화이팅이에요 :)

2021-10-20 11:39 UTC, ecsimsw commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +그저 앞에서 말한 행복을 느낄 수 있는 것들, 문제 사항을 해결하면서 즐거움을 느낄 수 있다면, 아이디어를 실현할 수 있다면, 사람들과 함께 일을 하고, 그들에게 긍정적인 영향을 줄 수 있다면, 정말 그걸로 만족스런 삶이 될 것 같다.
우와 진짜 힘나네요!!!!
번뜩이는 아이디어와 긍정적 영향력... 저는 항상 제 부족함만 보이는거 같아요. 실수한 것만 생각나고 ㅋㅋ
응원 감사해요.

2021-10-20 11:47 UTC, ecsimsw commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +
음 뽑아준다는 표현보다 같이 만들어 가고 싶다는 생각이 크네!! 같이 할 때 엄청 든든한 사람이니까.

지금 당장은 집중해야할 부분이 있으니, 조금씩 더 힘내서 환경 만들고 목표를 구체화해보자. 

진짜 재밌을 것 같다. 나는 그거면 돼 ㅋㅋ

2021-10-20 13:42 UTC, bosl95 commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +- 당신이랑 같이 일할 수 있으면 연봉이 조금 적더라도 그 회사 갈 것 같다.
크,, 컴퓨터를 사랑하는 geek과 함께 giggle을 만들고 싶다며 반짝반짝 눈이 빛나던 코기를 잊지모태 진짜 멋져 최고야!! 요즘 연락은 자주 못 하지만😥 항상 응원하고 있다구!! 🤟

2021-10-20 13:56 UTC, ecsimsw commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +- 당신이랑 같이 일할 수 있으면 연봉이 조금 적더라도 그 회사 갈 것 같다.
나 기글 진짜 키울거야!!!!!!!! 크크

2021-10-20 14:08 UTC, ddongule approved these changes
안녕하세요 코기!!!!!!!!!!!!!!!!!!!
그루밍입니다!!
글자 하나하나에 코기의 진심이 묻어나는 글이었어요. 
사람을 정말 좋아하고 개발에 대해 진심으로 생각하고 있다는 점이 깊게 와닿네요
읽으면서 너무 좋았던 글이었어요!!! > ___ <ㅎㅎㅎㅎ 꺄!!!!
다음에 기회가 있다면 코기랑도 함께 개발하고 싶다는 생각이 들었어요
저도 뽑아주십쇼 .
케케켘ㅋㅋㅋㅋ

2021-10-20 14:08 UTC, ddongule commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +죄다 과학자나 대통령을 꿈꾸던 주변 친구들이 하나둘씩 현실적인 장래희망을 갖게 될 때 까지도 나는 발명가를 꿈꿨다.
그냥 기가 막힌 코기!

2021-10-20 14:08 UTC, ddongule commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +그 작은 샤프도 내가 만들었었다.
그 샤프.. 얼마면 살 수 있나요..

2021-10-20 14:08 UTC, ddongule commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +다른 사람들이 봤을 때 조금 덜 대단해도 행복할 수 있는 개발자가 되고 싶다.
본받고 싶은 마인드네요!!

2021-10-20 19:22 UTC, ecsimsw commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +죄다 과학자나 대통령을 꿈꾸던 주변 친구들이 하나둘씩 현실적인 장래희망을 갖게 될 때 까지도 나는 발명가를 꿈꿨다.
ㅋㅋㅋㅋㅋ

2021-10-21 13:43 UTC, DWL5 approved these changes

2021-10-21 13:43 UTC, DWL5 commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +책장에는 추리 소설이나 퀴즈 책만 있었고, 장기, 체스가 세상에서 가장 재밌는 게임이었으며, 수학 문제를 푸는 희열에 중고등학교 때는 솔직히 수학만 했다.
한 학기 수학이 갑자기 재밌어서 이과를 선택한 나랑은 정말 다르다.....

2021-10-21 13:43 UTC, DWL5 commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +죄다 과학자나 대통령을 꿈꾸던 주변 친구들이 하나둘씩 현실적인 장래희망을 갖게 될 때 까지도 나는 발명가를 꿈꿨다.
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 기가 막힌 코기 ㅋㅋㅋㅋㅋㅋㅋㅋ

2021-10-21 13:43 UTC, DWL5 commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +그 작은 샤프도 내가 만들었었다.
샤프... 도대체 어떻게 만드는거야?
신기방기..

2021-10-21 13:43 UTC, DWL5 commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +그리고 사람을 좋아한다. 그냥 사람들과 함께 하는게 너무 재밌다. 내가 좋아하는 사람들과 웃고 떠들면서 행복함을 느낀다.
코기는 인정

2021-10-21 13:43 UTC, DWL5 commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +- 당신이랑 같이 일할 수 있으면 연봉이 조금 적더라도 그 회사 갈 것 같다.
뭐야 giggle 검색엔진이야!!?? 나 그것만 쓸래

2021-10-21 13:43 UTC, DWL5 commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +결론은 다 필요 없고 일을 즐길 줄 아는 개발자로 살고 싶다. 하루에 행복을 느끼며 재밌게 일 할 수 있는 삶을 살고 싶다.
진짜 수코톡 도메인 토론할 때가 언제인지..
그때도 코기 너무 똑똑해서 놀라쓰..!!
영특하고 친절하고 항상 열심히나는 코기
언제나 응원할게!!!!!

2021-10-21 13:44 UTC, DWL5 commented
코기코기 글 잘읽고 가
글에서 부터 코기의 온화함이 느껴진다!!

같이 배포를 하고 나서도 조금 더 해보겠다고 로드밸런싱 까지 해보는 코기
진짜 그때 나 너무 자극 받았자나..
나중에 코기의 서비스 열혈 사용자가 될게!! 꼭 출시해줘
화이팅!!!!!!!!

2021-10-22 18:45 UTC, pkeugine commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +
뭐야 나 빼고 여기서 얘기하고 있었던거야? ㅎㅎ

2021-10-22 18:56 UTC, pkeugine commented
글 잘 읽고 간다~
함께 했던 순간이 너무나도 많아서, 그리고 함께 주고받은 말들이 정말 많아서
글이 더더욱 와 닿는 것 같아.
덕분에 특별한 한 해를 보낼 수 있었고, 앞으로의 시간이 더 기대가 돼.
누구보다 큰 목표를 제시하지만 누구보다 그 목표에 적합한 인재가 아닌가 싶다.
늘 믿고 응원한다!! :)

2021-10-22 23:00 UTC, ecsimsw commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +
🤣

2021-10-23 11:40 UTC, Rok93 approved these changes
리뷰사항 잘 반영해준 것 같아서 이만 approve 할께!  😉

2021-10-23 20:16 UTC, yujo11 approved these changes
안녕하세요 코기!

리뷰를 조금 늦게 남기게 되면서 다른 크루들이 먼저 남긴 리뷰들을 같이 보게 됐습니다.

다른 크루들에게 많은 사랑을 받는 코기의 모습 속에서 이미 코기가 꿈꾸는 행복한 개발자의 모습을 어느정도 이룬거 같다는 생각이 들었네요! 👍 👍 👍 

코기가 꿈꾸는 프로그래머의 삶을 응원합니다!! 💪 💪 💪

2021-10-23 20:16 UTC, yujo11 commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +다른 사람들이 봤을 때 조금 덜 대단해도 행복할 수 있는 개발자가 되고 싶다.
정말 멋진 마인드셋이네요! 👍 👍 👍

2021-10-23 20:16 UTC, yujo11 commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +- 수익이 적더라도 내 아이디어로 사용자를 만들 수 있으면 만들면 정말 행복하게 살 수 있을 것 같다.
와 생각만 해도 정말 즐거운 미래네요!

이런 식으로는 생각해보지 못 했는데 멋져요 코기! 👍 👍 👍

2021-10-23 20:16 UTC, yujo11 commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +결론은 다 필요 없고 일을 즐길 줄 아는 개발자로 살고 싶다. 하루에 행복을 느끼며 재밌게 일 할 수 있는 삶을 살고 싶다.
👍 👍 👍

2021-10-24 01:06 UTC, ecsimsw commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +그리고 사람을 좋아한다. 그냥 사람들과 함께 하는게 너무 재밌다. 내가 좋아하는 사람들과 웃고 떠들면서 행복함을 느낀다.
반영했습니다. 감사합니다~

2021-10-24 01:06 UTC, ecsimsw commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +그저 앞에서 말한 행복을 느낄 수 있는 것들, 문제 사항을 해결하면서 즐거움을 느낄 수 있다면, 아이디어를 실현할 수 있다면, 사람들과 함께 일을 하고, 그들에게 긍정적인 영향을 줄 수 있다면, 정말 그걸로 만족스런 삶이 될 것 같다.
반영했습니다. 감사합니다~

2021-10-24 01:06 UTC, ecsimsw commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +죄다 과학자나 대통령을 꿈꾸던 주변 친구들이 하나둘씩 현실적인 장래희망을 갖게 될 때 까지도 나는 발명가를 꿈꿨다.
반영했습니다. 감사합니다~

2021-10-24 01:06 UTC, ecsimsw commented on 내가 꿈꾸는 프로그래머로서의 삶.md
> +
반영했습니다. 감사합니다~

2021-10-24 12:38 UTC, wannte reviewed
밤새 공부해 오고, 그걸 팀원에게 공유할 때 누구보다 신나있던 코기의 모습이 떠오르는 그런 글이네요! ㅎㅎ
프로그래밍을 이 정도로 사랑할 수 있을까? 라는 생각이 들 정도로 부러웠던 코기!
응원합니다!

2022-03-13 10:38 UTC, closed without merging