[레벨 4 글쓰기 미션] 코다(김윤정) 미션 제출합니다.
woowacourse/woowa-writing-3 pull request #311
Opened 2021-10-19 15:56 UTC by yjksw

안녕하세요 ~~~!!! 늦게 제출해서 죄송합니다ㅠㅠㅠㅠ 

요 근래 감기가 갑자기 걸려서 글을 늦게 제출하게 되었네요 !! 
벌써 레벨4 글쓰기 미션이라니 ...!! 시원섭섭하네요 😢 시간이 멈춰버렸으면 !! 
다들 루터에서 꼭꼭 보고 싶은데 수료전에 꼭 볼 수 있기를 바래봅니다 ...ㅎㅎ 
날씨가 갑자기 추워졌는데 모두 감기 조심하세요 꼭꼭 !! 🙌 

[잘 봐주세요 😆](https://github.com/yjksw/woowa-writing-3/blob/level4/woowa-4thMission.md)

2021-10-19 16:31 UTC, jaeseongDev approved these changes
코다 하이하이! 잘 지내고있나🤚🤚
글 읽으면서 내가 꿈꾸는 방향이랑 비슷하다는 생각도 많이 들고
공감도 많이 되고 배울 점도 많았던 것 같애!
앞으로도 걸어가는 길 항상 응원할게!!
앞으로 남은 우테코 기간 마무리 잘하자구우우우

2021-10-19 16:31 UTC, jaeseongDev commented on woowa-4thMission.md
> +처음 프로그래머를 꿈꾸게 된 명확한 이유가 있다. 많은 사람에게 영향을 줄 수 있는 가장 좋은 도구이기 때문이다. 나이가 많거나 적거나, 물질적으로 풍요롭거나 아니거나, 어떤 언어를 쓰거나 상관없이 대부분의 사람은 기술을 접할 수 있는 기기를 하나씩 가지고 있다. 한 애플리케이션을 전 세계가 쓰기도 하고, 특정 플랫폼을 통해 콘텐츠가 확 퍼지기도 한다.
키야 멋있어멋있어!! 👍👍👍

2021-10-19 16:31 UTC, jaeseongDev commented on woowa-4thMission.md
> +그렇다고 붕 뜨면서 말도 안 되는 꿈만 꾸는 것은 아무래도 적성에 맞지 않는다. 곰곰이 고민해보았을 때 꿈을 현실로 만들 방법 중 가장 현실적이며 합리적인 리소스로 실현할 수 있는 방법이 프로그래밍이라고 생각했다. 지금은 그 프로그래밍에 대한 역량을 키워야 할 때다. 선한 목적과 꿈이 실력을 키워주지는 않는다. 다만 분명한 목적이 있다면 그것이 없는 다른
뭐야 왤케 멋있는거야🙄
진짜 진지하고 치열하게 고민한 흔적들이 보인다잉!

2021-10-19 16:31 UTC, jaeseongDev commented on woowa-4thMission.md
> +오늘날에는 누구든지 기술을 사용하기 때문에 프로그래밍은 일상에 침투하기 가장 좋은 수단이다. 무언가가 많은 사람의 일상이 되면 그것은 하나의 문화가 된다. 마치 배달의 민족이 배달문화를 만들고 당근마켓이 또 하나의 문화가 된 것처럼 말이다. 그것이 선한 문화라면 사람이 사람을 돕는 가장 자연스러운 방법일 것이다.
코다가 꿈꾸는 선한 영향력을 발휘할 수 있게,
걸어나가는 길이 험난하더라도 꾸준히 할 수 있도록 재미있고 설레는 길이었으면 좋겠다🐭

2021-10-19 16:31 UTC, jaeseongDev commented on woowa-4thMission.md
> +마지막 글이라고 나름의 인생관을 적어보자면 나는 아무래도 나 혼자 행복하자고 사는 삶은 좀 시시한 것 같다. 언젠가는 끝나는 인생이기도 하고 행복 자체가 목적이라면 행복의 그릇을 조금 줄인다면 금방 행복해질 수 있다. (나만 해도 좋은 사람들과 때 되면 먹을 수 있기만 해도 매우 행복….) 또 나 혼자 잘 살기에는 세상에는 너무 많은 사람이 함께 살고 있
인연이 닿아 머지않은 미래에 긍정적인 영향을 만들어내는 활동을 같이 하는 날이 왔으면 좋겠다!
코다가 가진 꿈 응원할게
화이팅이야 화이팅!!!

2021-10-19 16:45 UTC, da-nyee reviewed
코다 체고 💓

2021-10-19 16:45 UTC, da-nyee commented on woowa-4thMission.md
> +굉장히 붕 뜬 이상주의자처럼 들릴 수도 있지만 사실 나는 그런 사람은 아니다. 한때 MBTI 검사를 하면 감정을 나타내는 수치인 F가 빵점이 나올 정도로 (지금은 많이 바뀌었다) 기본이 이성적인 사람이다. 흔히 이성적이며 현실적인 사람에 대해서 이야기할 때 부정적이고 “현실적으로 안 된다”라고 말하는 사람으로 형용할 때가 많다. 나도 그런 사람 중 일인자
코다랑 페어할 때 MBTI 얘기했던 거 기억난다!
나에게 코다는 따수운 사람이어서, 고등학생 때까지만 해도 F가 거의 0이었다는 거 듣고 엄청 놀랐는데..!!! 😮

2021-10-19 16:45 UTC, da-nyee commented on woowa-4thMission.md
> +그렇다고 붕 뜨면서 말도 안 되는 꿈만 꾸는 것은 아무래도 적성에 맞지 않는다. 곰곰이 고민해보았을 때 꿈을 현실로 만들 방법 중 가장 현실적이며 합리적인 리소스로 실현할 수 있는 방법이 프로그래밍이라고 생각했다. 지금은 그 프로그래밍에 대한 역량을 키워야 할 때다. 선한 목적과 꿈이 실력을 키워주지는 않는다. 다만 분명한 목적이 있다면 그것이 없는 다른
> 괜히 부푼 꿈만 말하면서 상응하는 실력이 없는 사람이 되기는 싫다.

완전 공감이야

2021-10-19 16:45 UTC, da-nyee commented on woowa-4thMission.md
> +프로그래밍을 처음 시작한 때부터 지금까지 내 가치관이 불분명했던 적은 없다. 나에게 프로그래밍은 그 자체가 목적이기보다 선한 목적을 이루게 위한 좋은 도구이다. 그 때문에 내 블로그 이름도 *FromCoding* 코딩으로 시작되는 무언가를 암시하는 이름으로 정했다. 깃헙에 소개 글도 마찬가지이다.
오오 블로그 이름 멋져 👍

2021-10-19 16:45 UTC, da-nyee commented on woowa-4thMission.md
> +마지막으로 쑥스러운 마음에 굳이 밝히지 않았던 *코다*라는 별명의 내재한 뜻을 말해보려고 한다. 누가 물어보면 그냥 우리 집 고양이 이름이라고 소개했지만 (맞는 말이긴 하다) ‘코딩이 다가 아닌 개발자’라는 나만의 의미를 담고 있다. 코딩이 다가 아니라 그것이 끼치는 영향까지 고려하는 개발자, 그래서 항상 선한 뜻을 실현하고자 하는 개발자가 내가 꿈꾸는 
코다는 코딩이 다가 아닌 개발자!!! ✨

코다랑 페어, 플젝하며 많이 배우고 있어 !

2021-10-19 16:45 UTC, da-nyee commented on woowa-4thMission.md
> +마지막 글이라고 나름의 인생관을 적어보자면 나는 아무래도 나 혼자 행복하자고 사는 삶은 좀 시시한 것 같다. 언젠가는 끝나는 인생이기도 하고 행복 자체가 목적이라면 행복의 그릇을 조금 줄인다면 금방 행복해질 수 있다. (나만 해도 좋은 사람들과 때 되면 먹을 수 있기만 해도 매우 행복….) 또 나 혼자 잘 살기에는 세상에는 너무 많은 사람이 함께 살고 있
앞으로도 파이팅이야 ~!
우테코 수료 이후의 코다도 계속 응원할게 🙌💜

2021-10-19 17:07 UTC, Be-poz approved these changes
코다 글 잘 읽었어~!  
나는 코다하면 기억나는게 어떤 주제였는지 기억안나는데 미션 이었나.. 엘레강트 오브젝트였나... 미션이었던 것 같긴한데! 나한테 생각을 묻고 나는 그것에 대한 내 생각을 말하고 코다의 생각을 물었던 적이 있었어! 그때 코다의 답변을 듣고 아 코다 굉장히 깊게 생각하는 크루구나! 라고 느꼈었어 (진짜임 실화임)  

그리고 직화집가서 대화나눴던게 생각난다! 그때 코다가 어떤 사람인지 더 알 수 있게되는 그런 자리였었는데! 재밌었던 기억 ㅎㅎ 글 전반적으로 어떤 프로그래머를 원하는지 나타내고 있어서 흥미로웠어. 꿈꾸는 프로그래머가 될 수 있을 거라고 생각해! 글 잘 읽었어 코다 남은 레벨도 화이팅 하자~!

2021-10-19 17:07 UTC, Be-poz commented on woowa-4thMission.md
> +굉장히 붕 뜬 이상주의자처럼 들릴 수도 있지만 사실 나는 그런 사람은 아니다. 한때 MBTI 검사를 하면 감정을 나타내는 수치인 F가 빵점이 나올 정도로 (지금은 많이 바뀌었다) 기본이 이성적인 사람이다. 흔히 이성적이며 현실적인 사람에 대해서 이야기할 때 부정적이고 “현실적으로 안 된다”라고 말하는 사람으로 형용할 때가 많다. 나도 그런 사람 중 일인자
와 F가 0 !! 극 이성!!

2021-10-19 17:07 UTC, Be-poz commented on woowa-4thMission.md
> +굉장히 붕 뜬 이상주의자처럼 들릴 수도 있지만 사실 나는 그런 사람은 아니다. 한때 MBTI 검사를 하면 감정을 나타내는 수치인 F가 빵점이 나올 정도로 (지금은 많이 바뀌었다) 기본이 이성적인 사람이다. 흔히 이성적이며 현실적인 사람에 대해서 이야기할 때 부정적이고 “현실적으로 안 된다”라고 말하는 사람으로 형용할 때가 많다. 나도 그런 사람 중 일인자
> 누군가에게 이렇다 할 변화를 만들어내는 것도 현실에 안주하지 않고 그 이상을 꿈꾸는 사람들이라는 것을 목격하면서 

궁금해!

2021-10-19 17:07 UTC, Be-poz commented on woowa-4thMission.md
> +그렇다고 붕 뜨면서 말도 안 되는 꿈만 꾸는 것은 아무래도 적성에 맞지 않는다. 곰곰이 고민해보았을 때 꿈을 현실로 만들 방법 중 가장 현실적이며 합리적인 리소스로 실현할 수 있는 방법이 프로그래밍이라고 생각했다. 지금은 그 프로그래밍에 대한 역량을 키워야 할 때다. 선한 목적과 꿈이 실력을 키워주지는 않는다. 다만 분명한 목적이 있다면 그것이 없는 다른
> 꿈을 현실로 만들 방법 중 가장 현실적이며 합리적인 리소스로 실현할 수 있는 방법이 프로그래밍이라고 생각했다

괜시리 이성적이다 느끼게 되는 문장이었어! 이성의 코다  

> 선한 목적과 꿈이 실력을 키워주지는 않는다.

냉철코다  

> 괜히 부푼 꿈만 말하면서 상응하는 실력이 없는 사람이 되기는 싫다.

멋있다

2021-10-19 17:07 UTC, Be-poz commented on woowa-4thMission.md
> +마지막으로 쑥스러운 마음에 굳이 밝히지 않았던 *코다*라는 별명의 내재한 뜻을 말해보려고 한다. 누가 물어보면 그냥 우리 집 고양이 이름이라고 소개했지만 (맞는 말이긴 하다) ‘코딩이 다가 아닌 개발자’라는 나만의 의미를 담고 있다. 코딩이 다가 아니라 그것이 끼치는 영향까지 고려하는 개발자, 그래서 항상 선한 뜻을 실현하고자 하는 개발자가 내가 꿈꾸는 
후... 코다는 나한테 또 또 또또또또또 거짓말을 했구나 불과 2주전인데...!!!!!!!!  😢  

> 그래서 항상 선한 뜻을 실현하고자 하는 개발자가 내가 꿈꾸는 프로그래머로의 삶이다.

선한 영향력을 끼치는 프로그래머가 되고 싶은 코다

2021-10-19 17:07 UTC, Be-poz commented on woowa-4thMission.md
> +마지막 글이라고 나름의 인생관을 적어보자면 나는 아무래도 나 혼자 행복하자고 사는 삶은 좀 시시한 것 같다. 언젠가는 끝나는 인생이기도 하고 행복 자체가 목적이라면 행복의 그릇을 조금 줄인다면 금방 행복해질 수 있다. (나만 해도 좋은 사람들과 때 되면 먹을 수 있기만 해도 매우 행복….) 또 나 혼자 잘 살기에는 세상에는 너무 많은 사람이 함께 살고 있
> (나만 해도 좋은 사람들과 때 되면 먹을 수 있기만 해도 매우 행복….)

밥을 먹는다는거지? 문장이 조금 어색한 것 같아 조금 더 자연스럽게 고치면 좋을 것 같다~!  

> 행복 자체가 목적이라면 행복의 그릇을 조금 줄인다면 금방 행복해질 수 있다.

물이 반 밖에 없네? -> 컵을 가로로 반을 잘라 내버림 댕강 -> 물이 꽉 차 있네!!!  

> 아무래도 나 혼자 행복하자고 사는 삶은 좀 시시한 것 같다. 

더불어 사는게 재밌지~!!

2021-10-20 19:12 UTC, ecsimsw commented on woowa-4thMission.md
> +마지막으로 쑥스러운 마음에 굳이 밝히지 않았던 *코다*라는 별명의 내재한 뜻을 말해보려고 한다. 누가 물어보면 그냥 우리 집 고양이 이름이라고 소개했지만 (맞는 말이긴 하다) ‘코딩이 다가 아닌 개발자’라는 나만의 의미를 담고 있다. 코딩이 다가 아니라 그것이 끼치는 영향까지 고려하는 개발자, 그래서 항상 선한 뜻을 실현하고자 하는 개발자가 내가 꿈꾸는 
곰돌이 코다가 아니고?? 😄

2021-10-21 12:46 UTC, 365kim commented on woowa-4thMission.md
> +처음 프로그래머를 꿈꾸게 된 명확한 이유가 있다. 많은 사람에게 영향을 줄 수 있는 가장 좋은 도구이기 때문이다. 나이가 많거나 적거나, 물질적으로 풍요롭거나 아니거나, 어떤 언어를 쓰거나 상관없이 대부분의 사람은 기술을 접할 수 있는 기기를 하나씩 가지고 있다. 한 애플리케이션을 전 세계가 쓰기도 하고, 특정 플랫폼을 통해 콘텐츠가 확 퍼지기도 한다.
지금도 충분히 문맥을 이해하는데 문제는 없지만 요렇게 주어를 명확하게 넣어주는 것은 어떨까용? ☺️
```suggestion
처음 프로그래머를 꿈꾸게 된 명확한 이유가 있다. 프로그래밍은 많은 사람에게 영향을 줄 수 있는 가장 좋은 도구이기 때문이다. 나이가 많거나 적거나, 물질적으로 풍요롭거나 아니거나, 어떤 언어를 쓰거나 상관없이 대부분의 사람은 기술을 접할 수 있는 기기를 하나씩 가지고 있다. 한 애플리케이션을 전 세계가 쓰기도 하고, 특정 플랫폼을 통해 콘텐츠가 확 퍼지기도 한다. 그렇기에 내가 꿈꾸는 프로그래머로의 삶은 많은 사람에게 선한 영향력을 끼치는 것이다.
```

2021-10-21 12:46 UTC, 365kim commented on woowa-4thMission.md
> +처음 프로그래머를 꿈꾸게 된 명확한 이유가 있다. 많은 사람에게 영향을 줄 수 있는 가장 좋은 도구이기 때문이다. 나이가 많거나 적거나, 물질적으로 풍요롭거나 아니거나, 어떤 언어를 쓰거나 상관없이 대부분의 사람은 기술을 접할 수 있는 기기를 하나씩 가지고 있다. 한 애플리케이션을 전 세계가 쓰기도 하고, 특정 플랫폼을 통해 콘텐츠가 확 퍼지기도 한다.
`선한 영향력` 너무 좋은 단어네요 :)

2021-10-21 12:49 UTC, 365kim commented on woowa-4thMission.md
> +굉장히 붕 뜬 이상주의자처럼 들릴 수도 있지만 사실 나는 그런 사람은 아니다. 한때 MBTI 검사를 하면 감정을 나타내는 수치인 F가 빵점이 나올 정도로 (지금은 많이 바뀌었다) 기본이 이성적인 사람이다. 흔히 이성적이며 현실적인 사람에 대해서 이야기할 때 부정적이고 “현실적으로 안 된다”라고 말하는 사람으로 형용할 때가 많다. 나도 그런 사람 중 일인자
`흔히 이성적이며 현실적인 사람에 대해서 이야기할 때 부정적이고 “현실적으로 안 된다”라고 말하는 사람으로 형용할 때가 많다. `

- `흔히 ~ 라고 형용한다.`
- `~라고 형용할 때가 많다.`
의미가 중복으로 들어가있는 것 같아서, 하나만 넣어주어도 의미가 충분히 전달되지 않을까 조심스레 생각해봅니당,,,!

2021-10-21 12:51 UTC, 365kim commented on woowa-4thMission.md
> +굉장히 붕 뜬 이상주의자처럼 들릴 수도 있지만 사실 나는 그런 사람은 아니다. 한때 MBTI 검사를 하면 감정을 나타내는 수치인 F가 빵점이 나올 정도로 (지금은 많이 바뀌었다) 기본이 이성적인 사람이다. 흔히 이성적이며 현실적인 사람에 대해서 이야기할 때 부정적이고 “현실적으로 안 된다”라고 말하는 사람으로 형용할 때가 많다. 나도 그런 사람 중 일인자
`굉장히 붕 뜬 이상주의자처럼 들릴 수도 있지만 사실 나는 그런 사람은 아니다.`
글의 흐름상 `아니었다.`처럼 과거형으로 적는 것도 괜찮을 것 같아용 :)

2021-10-21 13:01 UTC, 365kim commented on woowa-4thMission.md
> +굉장히 붕 뜬 이상주의자처럼 들릴 수도 있지만 사실 나는 그런 사람은 아니다. 한때 MBTI 검사를 하면 감정을 나타내는 수치인 F가 빵점이 나올 정도로 (지금은 많이 바뀌었다) 기본이 이성적인 사람이다. 흔히 이성적이며 현실적인 사람에 대해서 이야기할 때 부정적이고 “현실적으로 안 된다”라고 말하는 사람으로 형용할 때가 많다. 나도 그런 사람 중 일인자
적고나니 뭘 이렇게까지 싶지만서도,,,,👉👈  이런 의견도 있구나~ 하고 봐주시면 감사하겠습니당 🙏

개인적으로 `좋은 사람들을 만나면서 바뀌었다.`, `내 가치관이 변했다.` 라는 표현에서, 마치 코다의 성향이 T형에서 F형으로 대대적으로(?) 바뀌었을 것처럼 읽혔는데, 이어지는 단락에서는 다시 T에 대한 이야기가 나와서, 코다의 현재 성향이 어떤 것인지 파악하기 조금 어려웠던 것 같아요...! `좋은 사람들을 만나면서 조금 바뀌었다.`, `내 가치관에도 약간의 변화가 있었다.`와 같은 표현으로 여전히 T형에 가까움을 암시해주시는건 어떨까 싶습니다...!

### 첫번째 단락
- F 스러운 이상향

### 두번째 단락
- F형처럼 들리지만 사실 아니다.(현재 T에 가까움) 
- F점수 0점이었다.(과거 T)
- 기본이 이성적인 사람이다. (현재 T)
- 좋은 사람들을 만나면서 바뀌었다. (과거T -> `현재 F로 바뀜`)
- 내 가치관이 변했다. (과거T -> `현재 F로 바뀜`)

### 세번째 단락
- 아무래도 적성에 맞지 않는다. (현재 T)

2021-10-21 13:02 UTC, 365kim commented on woowa-4thMission.md
> +> 일상에 스미는 좋은 기술로 사람이 사람을 돕는 문화를 꿈꾸는 개발자입니다👩‍💻
`좋은 기술로 사람이 사람을 돕는` 너무 멋진 글귀에요 🥺

2021-10-21 13:04 UTC, 365kim commented on woowa-4thMission.md
> +마지막으로 쑥스러운 마음에 굳이 밝히지 않았던 *코다*라는 별명의 내재한 뜻을 말해보려고 한다. 누가 물어보면 그냥 우리 집 고양이 이름이라고 소개했지만 (맞는 말이긴 하다) ‘코딩이 다가 아닌 개발자’라는 나만의 의미를 담고 있다. 코딩이 다가 아니라 그것이 끼치는 영향까지 고려하는 개발자, 그래서 항상 선한 뜻을 실현하고자 하는 개발자가 내가 꿈꾸는 
오 코다의 뜻을 이렇게 알게되는군용! 
`코딩이 다가 아닌 개발자`, `사람을 위한, 사람에게 이로운 개발자` 코다 멋져용 😎

2021-10-21 13:10 UTC, 365kim requested changes
코다 안녕하세요~!

이제 컨디션은 조금 괜찮으신지요,,,!! 💊💊
코다의 글을 읽으며, 코다의 확고한 비전 `선한 영향력`에 대해 엿볼 수 있었어요. 
이성적이지만 따뜻한 코다는 앞으로 어떤 일을 맡게 되더라도 주변 사람들에게, 그리고 우리 사회에 이로운 일을 해주실 것 같은 멋진 사람이라고 확신합니다. 😎

코다의 글을 읽으면서 이렇게 표현하는 것은 어떨까 싶은 부분에 코멘트를 남겼는데,
저 개인의 의견이고 다른 분들은 또 다르게 받아들이실 수 있을 것 같아서 가볍게 참고만 해주시면 감사하겠습니다. 🥰

코멘트 확인만 해주시면 바로 Approve하러 달려올게용!
남은 기간 동안 감기 조심하시고, 화이팅입니다~!

(마지막) 글쓰기 미션 수고하셨어요...!! 👏👏👏

2021-10-21 13:51 UTC, sihyung92 commented
일상에 스미는 코딩이 다가 아닌 개발자 코다 하이

코다에 대해 재밌는거 많이 알아가네 키키
얘기하면 다른 점도 많아서 들어보면 재밌고 혼자 동동거리는게 귀여운(?) 코다
지금처럼 꾸준히 열심히만 하면 코다는 크다가 되있을거 같아
작지만크다 인가? 아무튼

앞으로도 열씸히~ 선한 영향력을 펼치는데 힘이 모자라면 부르고~~ ㅎ_ㅎ

2021-10-22 09:15 UTC, taehee-kim-dev approved these changes
### 코다 하이하이~!!!
정말 오랜만이네.. 잘 지냈지??
프로그래밍을 통해 많은 사람들에게 선한 영향력을 끼치고 싶다는 부분이 매우 인상적이었어.
또, 이 글에서 처음 "코다"닉네임의 본래 의미를 알게되어서 놀라웠고. ㅎㅎ
전체적으로 코다의 선함이 느껴지는 글이어서 좋았어.

앞으로도 함께 행복하게 개발하자구!!
글 잘 읽었어~!!! 👍 👍 👍

2021-10-22 09:15 UTC, taehee-kim-dev commented on woowa-4thMission.md
> +처음 프로그래머를 꿈꾸게 된 명확한 이유가 있다. 많은 사람에게 영향을 줄 수 있는 가장 좋은 도구이기 때문이다. 나이가 많거나 적거나, 물질적으로 풍요롭거나 아니거나, 어떤 언어를 쓰거나 상관없이 대부분의 사람은 기술을 접할 수 있는 기기를 하나씩 가지고 있다. 한 애플리케이션을 전 세계가 쓰기도 하고, 특정 플랫폼을 통해 콘텐츠가 확 퍼지기도 한다.
프로그래밍의 특성 + 선한 영향력 !!
프로그래머를 꿈꾸게 된 이유가 정말 훌륭하네!!

2021-10-22 09:15 UTC, taehee-kim-dev commented on woowa-4thMission.md
> +굉장히 붕 뜬 이상주의자처럼 들릴 수도 있지만 사실 나는 그런 사람은 아니다. 한때 MBTI 검사를 하면 감정을 나타내는 수치인 F가 빵점이 나올 정도로 (지금은 많이 바뀌었다) 기본이 이성적인 사람이다. 흔히 이성적이며 현실적인 사람에 대해서 이야기할 때 부정적이고 “현실적으로 안 된다”라고 말하는 사람으로 형용할 때가 많다. 나도 그런 사람 중 일인자
개인적으로 이 문단이 조~금 이해하기 어려웠어!!
여러 번 읽어보고 의미를 파악할 수 있었어.
조금 더 쉽게 풀어내도 좋을 것 같다는 생각이 드네 ㅎㅎ

공감이 많이가는 문단이었어.
세상을 바꾸거나, 굉장히 행복한 삶을 사는 사람들은
현실의 틀 안에서 안주하며 살지 않고,
그 벽을 깨버리는 사람들이라고 생각하거든!!

2021-10-22 09:15 UTC, taehee-kim-dev commented on woowa-4thMission.md
> +그렇다고 붕 뜨면서 말도 안 되는 꿈만 꾸는 것은 아무래도 적성에 맞지 않는다. 곰곰이 고민해보았을 때 꿈을 현실로 만들 방법 중 가장 현실적이며 합리적인 리소스로 실현할 수 있는 방법이 프로그래밍이라고 생각했다. 지금은 그 프로그래밍에 대한 역량을 키워야 할 때다. 선한 목적과 꿈이 실력을 키워주지는 않는다. 다만 분명한 목적이 있다면 그것이 없는 다른
내가 본 코다는 이미 선한 목적과 꿈을 마음껏 프로그래밍으로 이루어 낼 수 있는 실력자야.
그럼에도 꿈과 그에 필요한 실력에 대해 항상 고민하고 노력하는 모습이 존경스럽다. 👍 👍

2021-10-22 09:15 UTC, taehee-kim-dev commented on woowa-4thMission.md
> +프로그래밍을 처음 시작한 때부터 지금까지 내 가치관이 불분명했던 적은 없다. 나에게 프로그래밍은 그 자체가 목적이기보다 선한 목적을 이루게 위한 좋은 도구이다. 그 때문에 내 블로그 이름도 *FromCoding* 코딩으로 시작되는 무언가를 암시하는 이름으로 정했다. 깃헙에 소개 글도 마찬가지이다.
```suggestion
프로그래밍을 처음 시작한 때부터 지금까지 내 가치관이 불분명했던 적은 없다. 나에게 프로그래밍은 그 자체가 목적이기보다 선한 목적을 이루기 위한 좋은 도구이다. 그 때문에 내 블로그 이름도 *FromCoding* 코딩으로 시작되는 무언가를 암시하는 이름으로 정했다. 깃헙에 소개 글도 마찬가지이다.
```

오타같은데 맞나?? ㅎㅎ

2021-10-22 09:15 UTC, taehee-kim-dev commented on woowa-4thMission.md
> +마지막으로 쑥스러운 마음에 굳이 밝히지 않았던 *코다*라는 별명의 내재한 뜻을 말해보려고 한다. 누가 물어보면 그냥 우리 집 고양이 이름이라고 소개했지만 (맞는 말이긴 하다) ‘코딩이 다가 아닌 개발자’라는 나만의 의미를 담고 있다. 코딩이 다가 아니라 그것이 끼치는 영향까지 고려하는 개발자, 그래서 항상 선한 뜻을 실현하고자 하는 개발자가 내가 꿈꾸는 
헐 충격 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
이 엄청난 의미를 여태 숨기고 있었다니...
이제서야 참뜻을 알아갑니다!!!

2021-10-22 09:15 UTC, taehee-kim-dev commented on woowa-4thMission.md
> +마지막 글이라고 나름의 인생관을 적어보자면 나는 아무래도 나 혼자 행복하자고 사는 삶은 좀 시시한 것 같다. 언젠가는 끝나는 인생이기도 하고 행복 자체가 목적이라면 행복의 그릇을 조금 줄인다면 금방 행복해질 수 있다. (나만 해도 좋은 사람들과 때 되면 먹을 수 있기만 해도 매우 행복….) 또 나 혼자 잘 살기에는 세상에는 너무 많은 사람이 함께 살고 있
함께 행복한 삶을 살고싶은 코다!!
나도 그렇게 생각해. 함께 행복해야 그 행복은 배가 되는 것 같아.
이렇게 좋은 생각을 갖고 있는 코다는 이미 "같이 일하고 싶은 좋은 개발자"야.
앞으로도 함께 행복한 개발 하자!! 💪 💪

2021-10-24 17:56 UTC, ggyool approved these changes
선한 영향력을 끼치는 프로그래머라니 멋있어요!
지금까지 해온 것처럼만 하다 보면 금방 이루실 것 같아요!
글 잘 읽었습니다👏👏👏

2021-10-24 17:56 UTC, ggyool commented on woowa-4thMission.md
> +그렇다고 붕 뜨면서 말도 안 되는 꿈만 꾸는 것은 아무래도 적성에 맞지 않는다. 곰곰이 고민해보았을 때 꿈을 현실로 만들 방법 중 가장 현실적이며 합리적인 리소스로 실현할 수 있는 방법이 프로그래밍이라고 생각했다. 지금은 그 프로그래밍에 대한 역량을 키워야 할 때다. 선한 목적과 꿈이 실력을 키워주지는 않는다. 다만 분명한 목적이 있다면 그것이 없는 다른
작은 수정입니다!
```suggestion
그렇다고 붕 뜨면서 말도 안 되는 꿈만 꾸는 것은 아무래도 적성에 맞지 않는다. 곰곰이 고민해보았을 때 꿈을 현실로 만들 방법 중 가장 현실적이며 합리적인 리소스로 실현할 수 있는 방법이 프로그래밍이라고 생각했다. 지금은 그 프로그래밍에 대한 역량을 키워야 할 때다. 선한 목적과 꿈이 실력을 키워주지는 않는다. 다만 분명한 목적이 있다면 그것이 없는 다른 이들보다 훨씬 멀리 오래 갈 수 있을 거라 생각한다. 괜히 부푼 꿈만 말하면서 상응하는 실력이 없는 사람이 되기는 싫다.
```

2021-10-24 17:56 UTC, ggyool commented on woowa-4thMission.md
> +마지막으로 쑥스러운 마음에 굳이 밝히지 않았던 *코다*라는 별명의 내재한 뜻을 말해보려고 한다. 누가 물어보면 그냥 우리 집 고양이 이름이라고 소개했지만 (맞는 말이긴 하다) ‘코딩이 다가 아닌 개발자’라는 나만의 의미를 담고 있다. 코딩이 다가 아니라 그것이 끼치는 영향까지 고려하는 개발자, 그래서 항상 선한 뜻을 실현하고자 하는 개발자가 내가 꿈꾸는 
갸벼운 제안입니다!
```suggestion
마지막으로 쑥스러운 마음에 굳이 밝히지 않았던 *코다*라는 별명에 내재된 뜻을 말해보려고 한다. 누가 물어보면 그냥 우리 집 고양이 이름이라고 소개했지만 (맞는 말이긴 하다) ‘코딩이 다가 아닌 개발자’라는 나만의 의미를 담고 있다. 코딩이 다가 아니라 그것이 끼치는 영향까지 고려하는 개발자, 그래서 항상 선한 뜻을 실현하고자 하는 개발자가 내가 꿈꾸는 프로그래머로의 삶이다. 일단 코딩이 다가 아니라면 적어도 코딩은 잘해야 한다는 뜻이기도 하다.
```

2021-10-24 17:56 UTC, ggyool commented on woowa-4thMission.md
> +마지막으로 쑥스러운 마음에 굳이 밝히지 않았던 *코다*라는 별명의 내재한 뜻을 말해보려고 한다. 누가 물어보면 그냥 우리 집 고양이 이름이라고 소개했지만 (맞는 말이긴 하다) ‘코딩이 다가 아닌 개발자’라는 나만의 의미를 담고 있다. 코딩이 다가 아니라 그것이 끼치는 영향까지 고려하는 개발자, 그래서 항상 선한 뜻을 실현하고자 하는 개발자가 내가 꿈꾸는 
예전에 제가 물었을 때는 애니메이션 캐릭터에서 따왔다고 했었는데.. 아닌가 🤔

2021-10-24 17:56 UTC, ggyool commented on woowa-4thMission.md
> +마지막 글이라고 나름의 인생관을 적어보자면 나는 아무래도 나 혼자 행복하자고 사는 삶은 좀 시시한 것 같다. 언젠가는 끝나는 인생이기도 하고 행복 자체가 목적이라면 행복의 그릇을 조금 줄인다면 금방 행복해질 수 있다. (나만 해도 좋은 사람들과 때 되면 먹을 수 있기만 해도 매우 행복….) 또 나 혼자 잘 살기에는 세상에는 너무 많은 사람이 함께 살고 있
잘 하고 있어요 화이팅 💪

2021-10-25 08:32 UTC, jho2301 approved these changes
안녕하세요 코다:)
코다의 목적의식이 뚜렷하게 보여서 집중력있게 읽어나갈 수 있었던 좋은 글이었습니다!
선한 영향력은 왜 갖게 되는건지 저한테 되물음 해보게 되네요.
어프루브 남겨요!

2021-10-25 08:32 UTC, jho2301 commented on woowa-4thMission.md
> +굉장히 붕 뜬 이상주의자처럼 들릴 수도 있지만 사실 나는 그런 사람은 아니다. 한때 MBTI 검사를 하면 감정을 나타내는 수치인 F가 빵점이 나올 정도로 (지금은 많이 바뀌었다) 기본이 이성적인 사람이다. 흔히 이성적이며 현실적인 사람에 대해서 이야기할 때 부정적이고 “현실적으로 안 된다”라고 말하는 사람으로 형용할 때가 많다. 나도 그런 사람 중 일인자
어떤 크루였는지 궁금해지네요!

2021-10-25 08:32 UTC, jho2301 commented on woowa-4thMission.md
> +오늘날에는 누구든지 기술을 사용하기 때문에 프로그래밍은 일상에 침투하기 가장 좋은 수단이다. 무언가가 많은 사람의 일상이 되면 그것은 하나의 문화가 된다. 마치 배달의 민족이 배달문화를 만들고 당근마켓이 또 하나의 문화가 된 것처럼 말이다. 그것이 선한 문화라면 사람이 사람을 돕는 가장 자연스러운 방법일 것이다.
요즘처럼 기술이 사람들의 일상에 가까이 있었던 적이 있나 생각해보면 정말 프로그래머가 필요한 세상이구나 느끼게 되네요

2021-10-25 08:32 UTC, jho2301 commented on woowa-4thMission.md
> +마지막으로 쑥스러운 마음에 굳이 밝히지 않았던 *코다*라는 별명의 내재한 뜻을 말해보려고 한다. 누가 물어보면 그냥 우리 집 고양이 이름이라고 소개했지만 (맞는 말이긴 하다) ‘코딩이 다가 아닌 개발자’라는 나만의 의미를 담고 있다. 코딩이 다가 아니라 그것이 끼치는 영향까지 고려하는 개발자, 그래서 항상 선한 뜻을 실현하고자 하는 개발자가 내가 꿈꾸는 
코딩이 다가 아닌 개발자 뭔가 생각을 하게 만드는데요 ㅋㅋ
저한테는 코딩말고 뭐가 있나 생각을 좀 해봐야겠어요

2021-10-26 06:40 UTC, yjksw commented on woowa-4thMission.md
> +굉장히 붕 뜬 이상주의자처럼 들릴 수도 있지만 사실 나는 그런 사람은 아니다. 한때 MBTI 검사를 하면 감정을 나타내는 수치인 F가 빵점이 나올 정도로 (지금은 많이 바뀌었다) 기본이 이성적인 사람이다. 흔히 이성적이며 현실적인 사람에 대해서 이야기할 때 부정적이고 “현실적으로 안 된다”라고 말하는 사람으로 형용할 때가 많다. 나도 그런 사람 중 일인자
오오 너무 감사합니다 ~~!!!

2021-10-26 06:40 UTC, yjksw commented on woowa-4thMission.md
> +굉장히 붕 뜬 이상주의자처럼 들릴 수도 있지만 사실 나는 그런 사람은 아니다. 한때 MBTI 검사를 하면 감정을 나타내는 수치인 F가 빵점이 나올 정도로 (지금은 많이 바뀌었다) 기본이 이성적인 사람이다. 흔히 이성적이며 현실적인 사람에 대해서 이야기할 때 부정적이고 “현실적으로 안 된다”라고 말하는 사람으로 형용할 때가 많다. 나도 그런 사람 중 일인자
와 정말 자세하게 봐 주셔서 감사요 !! 다시 읽어보니까 흐름이 어색하네요 ,,ㅎㅎ 하루 덕분에 더 꼼꼼히 들여다봅니다 !!

2021-10-26 06:41 UTC, yjksw commented on woowa-4thMission.md
> +굉장히 붕 뜬 이상주의자처럼 들릴 수도 있지만 사실 나는 그런 사람은 아니다. 한때 MBTI 검사를 하면 감정을 나타내는 수치인 F가 빵점이 나올 정도로 (지금은 많이 바뀌었다) 기본이 이성적인 사람이다. 흔히 이성적이며 현실적인 사람에 대해서 이야기할 때 부정적이고 “현실적으로 안 된다”라고 말하는 사람으로 형용할 때가 많다. 나도 그런 사람 중 일인자
맞어 ~!!! 우테코에 특히나 그런 사람들이 너무 많아서 감사하다 ㅎㅎㅎ 인비도 그중 하나야 ~~ !!

2021-10-26 06:41 UTC, yjksw commented on woowa-4thMission.md
> +프로그래밍을 처음 시작한 때부터 지금까지 내 가치관이 불분명했던 적은 없다. 나에게 프로그래밍은 그 자체가 목적이기보다 선한 목적을 이루게 위한 좋은 도구이다. 그 때문에 내 블로그 이름도 *FromCoding* 코딩으로 시작되는 무언가를 암시하는 이름으로 정했다. 깃헙에 소개 글도 마찬가지이다.
오오 감사합니다 ~!!

2021-10-26 06:41 UTC, yjksw commented on woowa-4thMission.md
> +그렇다고 붕 뜨면서 말도 안 되는 꿈만 꾸는 것은 아무래도 적성에 맞지 않는다. 곰곰이 고민해보았을 때 꿈을 현실로 만들 방법 중 가장 현실적이며 합리적인 리소스로 실현할 수 있는 방법이 프로그래밍이라고 생각했다. 지금은 그 프로그래밍에 대한 역량을 키워야 할 때다. 선한 목적과 꿈이 실력을 키워주지는 않는다. 다만 분명한 목적이 있다면 그것이 없는 다른
와 ~~!! 감사합니다!! ㅎㅎㅎ

2021-10-26 06:41 UTC, yjksw commented on woowa-4thMission.md
> +마지막으로 쑥스러운 마음에 굳이 밝히지 않았던 *코다*라는 별명의 내재한 뜻을 말해보려고 한다. 누가 물어보면 그냥 우리 집 고양이 이름이라고 소개했지만 (맞는 말이긴 하다) ‘코딩이 다가 아닌 개발자’라는 나만의 의미를 담고 있다. 코딩이 다가 아니라 그것이 끼치는 영향까지 고려하는 개발자, 그래서 항상 선한 뜻을 실현하고자 하는 개발자가 내가 꿈꾸는 
꼼꼼하게 봐주셔서 감사합니다 ~~!! ㅎㅎㅎ 수정했어요 !!

2021-10-26 06:42 UTC, yjksw commented on woowa-4thMission.md
> +마지막으로 쑥스러운 마음에 굳이 밝히지 않았던 *코다*라는 별명의 내재한 뜻을 말해보려고 한다. 누가 물어보면 그냥 우리 집 고양이 이름이라고 소개했지만 (맞는 말이긴 하다) ‘코딩이 다가 아닌 개발자’라는 나만의 의미를 담고 있다. 코딩이 다가 아니라 그것이 끼치는 영향까지 고려하는 개발자, 그래서 항상 선한 뜻을 실현하고자 하는 개발자가 내가 꿈꾸는 
크크 그것도 맞아요 ~~!! 저희 고양이 이름 유래가 그 애니메이션이라..ㅋㅋ 3중 의미가 되었군요 ..ㅋㅋㅋ

2021-10-26 06:42 UTC, yjksw commented on woowa-4thMission.md
> +오늘날에는 누구든지 기술을 사용하기 때문에 프로그래밍은 일상에 침투하기 가장 좋은 수단이다. 무언가가 많은 사람의 일상이 되면 그것은 하나의 문화가 된다. 마치 배달의 민족이 배달문화를 만들고 당근마켓이 또 하나의 문화가 된 것처럼 말이다. 그것이 선한 문화라면 사람이 사람을 돕는 가장 자연스러운 방법일 것이다.
맞아요 ~~!! 이럴 때 프로그래밍에 흥미를 느껴서 얼마나 감사한지 ㅎㅎ

2021-10-26 06:43 UTC, yjksw commented on woowa-4thMission.md
> +마지막 글이라고 나름의 인생관을 적어보자면 나는 아무래도 나 혼자 행복하자고 사는 삶은 좀 시시한 것 같다. 언젠가는 끝나는 인생이기도 하고 행복 자체가 목적이라면 행복의 그릇을 조금 줄인다면 금방 행복해질 수 있다. (나만 해도 좋은 사람들과 때 되면 먹을 수 있기만 해도 매우 행복….) 또 나 혼자 잘 살기에는 세상에는 너무 많은 사람이 함께 살고 있
정말 ~~!! 미래에 같이 일하고 싶은 크루 제리 👍 생각만 해도 든든하다 !! 여기저기서 큰 일을 하고 있을 우테코 크루들 ㅎㅎ

2021-10-26 06:43 UTC, yjksw commented on woowa-4thMission.md
> +마지막으로 쑥스러운 마음에 굳이 밝히지 않았던 *코다*라는 별명의 내재한 뜻을 말해보려고 한다. 누가 물어보면 그냥 우리 집 고양이 이름이라고 소개했지만 (맞는 말이긴 하다) ‘코딩이 다가 아닌 개발자’라는 나만의 의미를 담고 있다. 코딩이 다가 아니라 그것이 끼치는 영향까지 고려하는 개발자, 그래서 항상 선한 뜻을 실현하고자 하는 개발자가 내가 꿈꾸는 
다니랑 여러가지 활동 같이 하면서 긍정적 에너지도 얻고 !!! 
일하면서 꼼꼼하게 처리하는 것 보고 반성도 많이 하면서 배우고 있어 👍
우테코 최고 인싸 다니 😆

2021-10-26 06:44 UTC, yjksw commented on woowa-4thMission.md
> +그렇다고 붕 뜨면서 말도 안 되는 꿈만 꾸는 것은 아무래도 적성에 맞지 않는다. 곰곰이 고민해보았을 때 꿈을 현실로 만들 방법 중 가장 현실적이며 합리적인 리소스로 실현할 수 있는 방법이 프로그래밍이라고 생각했다. 지금은 그 프로그래밍에 대한 역량을 키워야 할 때다. 선한 목적과 꿈이 실력을 키워주지는 않는다. 다만 분명한 목적이 있다면 그것이 없는 다른
크크 코멘트 재밌당 ㅋㅋㅋㅋㅋ

2021-10-26 06:44 UTC, yjksw commented on woowa-4thMission.md
> +마지막 글이라고 나름의 인생관을 적어보자면 나는 아무래도 나 혼자 행복하자고 사는 삶은 좀 시시한 것 같다. 언젠가는 끝나는 인생이기도 하고 행복 자체가 목적이라면 행복의 그릇을 조금 줄인다면 금방 행복해질 수 있다. (나만 해도 좋은 사람들과 때 되면 먹을 수 있기만 해도 매우 행복….) 또 나 혼자 잘 살기에는 세상에는 너무 많은 사람이 함께 살고 있
오오 그렇네 !! 꼼꼼히 봐줘서 고마워 ㅎㅎ 수정했슴다 ~~!!

2021-11-24 09:08 UTC, woowapark approved these changes
코딩이 다가 아닌 코다! 글 재밌게 잘 읽었습니다 :)  
무엇보다 마지막 글의 마지막이 "'과정'이 재밌다"는 말로 끝나서 좋네요. 

현실적이라는 게 꼭 부정적인 의미는 아닐 것 같아요. 
이상을 꿈꾸는 사람들과 현실을 고려할 줄 아는 사람들이 서로에게 인사이트를 얻고, 함께 협력하면서 더 큰 영향력을 발휘할 수 있지 않을까요? 

코다가 생각하는 좋은 사람들과 함께하는 좋은 세상은 어떤 문화가 자리잡게 될 지 궁금하네요.
이미 목표만 바라보는 게 아니라 과정 자체를 재밌게 이어나가고 계신 것 같아서 걱정 없이,
우테코 이후의 코다에게 응원만 잔뜩 보낼게요!

2021-11-24 09:08 UTC, merged