[레벨 4 글쓰기 미션] 우기(박병욱) 미션 제출합니다.
woowacourse/woowa-writing-3 pull request #312
Opened 2021-10-21 06:04 UTC by jujubebat

안녕하세요 우기입니다 ㅎㅎ

제출이 늦었습니다. 

잘 부탁드립니다!! 감사합니다.

[보러가기](https://github.com/jujubebat/woowa-writing-3/tree/level4)

엘라 - @HyuuunjuKim
피케이 - @pkeugine
썬 - @SunYoungKwon
피터 - @iborymagic
알리 - @jh8579

2021-10-21 18:30 UTC, jh8579 approved these changes
안녕하세요 알리입니다!

공감되는 내용도 있고 (자료구조 재밌다는 부분 빼고...)
깔끔하게 작성해주셔서 의견만 남겼습니다.

글 잘읽었습니다!

2021-10-21 18:30 UTC, jh8579 commented on README.md
> +나는 컴퓨터공학과를 졸업하긴 했지만 개발을 좋아하는 사람은 전혀아니었다. 1학년때 C프로그래밍 수업을 들을때만 하더라도 너무 재미가 없어서 수업을 아예 안듣고 시험을 안 보기도 했다. 그리곤 다른 학과로 전과를 고민하기도 했다. 그러다가 2학년때 우연히 자료구조 수업을 듣게 되었다. 단순 문법만 배우던 C프로그래밍 수업과 달리 자료구조 수업에서는 내가 직
전 자료구조 때문에 전과하고 싶었는데....

2021-10-21 18:30 UTC, jh8579 commented on README.md
> +군대를 다녀온 후에는 1학년 자료구조 수업때 느꼈던 프로그래밍에 대한 흥미를 잃었다. 알고보니 자료구조는 프로그래밍의 기본이고 일부였다.  소프트웨어 개발을 하려면 알아야 하는 지식이 너무나도 많았다. 그런 지식을 어떻게 공부할지 감 조차 안왔다. 사실 알아야 하는 지식 자체가 뭔지 몰랐다. 그럼에도 항상 나 자신을 발전시키려는 의지가 강한 성향 덕분에
`구체적인 목표가 없다보니 성장의 방향은 어긋나고 속도는 느렸다.`
이 부분이 정말 공감되네요
저도 처음에는 열심히만 하면 될 줄 알았는데, 구체적인 목표가 없으니까 남는 게 없더라구요

2021-10-21 18:52 UTC, iborymagic requested changes
안녕하세요 우기!
찐 개발자의 글 재미있게 잘 읽었습니다~!
크게 이상하게 느낀 점 없이 잘 읽혔던 것 같고, 
맞춤법만 몇 개(거의 띄어쓰기) 고쳐주시면 될 것 같아요!
재밌었습니다!

2021-10-21 18:52 UTC, iborymagic commented on README.md
> +나는 컴퓨터공학과를 졸업하긴 했지만 개발을 좋아하는 사람은 전혀아니었다. 1학년때 C프로그래밍 수업을 들을때만 하더라도 너무 재미가 없어서 수업을 아예 안듣고 시험을 안 보기도 했다. 그리곤 다른 학과로 전과를 고민하기도 했다. 그러다가 2학년때 우연히 자료구조 수업을 듣게 되었다. 단순 문법만 배우던 C프로그래밍 수업과 달리 자료구조 수업에서는 내가 직
```suggestion
나는 컴퓨터공학과를 졸업하긴 했지만 개발을 좋아하는 사람은 전혀 아니었다. 1학년 때 C프로그래밍 수업을 들을 때만 하더라도 너무 재미가 없어서 수업을 아예 안듣고 시험을 안 보기도 했다. 그리곤 다른 학과로 전과를 고민하기도 했다. 그러다가 2학년 때 우연히 자료구조 수업을 듣게 되었다. 단순 문법만 배우던 C프로그래밍 수업과 달리 자료구조 수업에서는 내가 직접 동작하는 무언가를 만드는 경험을 하며 처음으로 흥미를 느꼈던 것 같다. 당시 기말고사 시험 문제는 연결 리스트, 트리, 힙을 손코딩으로 작성하는 것이었는데 재미를 느끼며 시험을 쳤고, 좋은 성적을 받았다. 그리고 이때부터 "아 이 분야가 나한테 맞는 건가?"라는 생각을 하게 되며 꿈을 시작하게 된 것 같다.   
```
띄어쓰기 몇 개만 고쳐주세용 ㅎㅎ

2021-10-21 18:52 UTC, iborymagic commented on README.md
> +나는 컴퓨터공학과를 졸업하긴 했지만 개발을 좋아하는 사람은 전혀아니었다. 1학년때 C프로그래밍 수업을 들을때만 하더라도 너무 재미가 없어서 수업을 아예 안듣고 시험을 안 보기도 했다. 그리곤 다른 학과로 전과를 고민하기도 했다. 그러다가 2학년때 우연히 자료구조 수업을 듣게 되었다. 단순 문법만 배우던 C프로그래밍 수업과 달리 자료구조 수업에서는 내가 직
자료구조 손코딩에...재미를...!?
세상에

2021-10-21 18:52 UTC, iborymagic commented on README.md
> +군대를 다녀온 후에는 1학년 자료구조 수업때 느꼈던 프로그래밍에 대한 흥미를 잃었다. 알고보니 자료구조는 프로그래밍의 기본이고 일부였다.  소프트웨어 개발을 하려면 알아야 하는 지식이 너무나도 많았다. 그런 지식을 어떻게 공부할지 감 조차 안왔다. 사실 알아야 하는 지식 자체가 뭔지 몰랐다. 그럼에도 항상 나 자신을 발전시키려는 의지가 강한 성향 덕분에
```suggestion
군대를 다녀온 후에는 1학년 자료구조 수업 때 느꼈던 프로그래밍에 대한 흥미를 잃었다. 알고보니 자료구조는 프로그래밍의 기본이고 일부였다.  소프트웨어 개발을 하려면 알아야 하는 지식이 너무나도 많았다. 그런 지식을 어떻게 공부할지 감조차 안 왔다. 사실 알아야 하는 지식 자체가 뭔지 몰랐다. 그럼에도 항상 나 자신을 발전시키려는 의지가 강한 성향 덕분에 무언갈 열심히는 했던 것 같다. 학교 전공 수업을 열심히 듣기도 했고, 연구실에 들어가 논문을 쓰기도 했다. 개발 공모전에 나가서 상을 타고, 알고리즘 문제를 정말 열심히 풀었다. 하지만 지금 생각해보니 가장 중요한 것을 놓치고 있었다. "나는 왜 개발자가 되고 싶은지?", "나는 어떤 개발자가 되고 싶은지?"에 대해 전혀 생각하지 않았다. 구체적인 목표가 없다 보니 성장의 방향은 어긋나고 속도는 느렸다. 
```
진짜 방향성을 설계하는 게 엄청 중요한 것 같아요..
크게 공감!

2021-10-21 18:52 UTC, iborymagic commented on README.md
> +방황하는 나에게는 당장 취업을 하는 것 보다 더 큰 미래를 위한 이정표가 필요하다고 생각했다. 그래서 작년하반기 취업 지원을 아예하지 않고 우아한테크코스를 지원했다. 감사하게도 합격했고 여기까지 오게 되었다. 그리고 이제는 "나는 왜 개발자가 되고 싶은지?", "나는 어떤 개발자가 되고 싶은지?"라는 질문에 답을 할 수 있게 되었다. 나는 컴퓨터 기술을
```suggestion
방황하는 나에게는 당장 취업을 하는 것보다 더 큰 미래를 위한 이정표가 필요하다고 생각했다. 그래서 작년 하반기 취업 지원을 아예 하지 않고 우아한테크코스를 지원했다. 감사하게도 합격했고 여기까지 오게 되었다. 그리고 이제는 "나는 왜 개발자가 되고 싶은지?", "나는 어떤 개발자가 되고 싶은지?"라는 질문에 답을 할 수 있게 되었다. 나는 컴퓨터 기술을 공부하는 게 재밌다. 그렇게 배운 기술을 기반으로 비즈니스 문제를 프로그래밍으로 풀 때 정말 큰 성취를 느낀다. 그래서 나는 개발자가 되고 싶다. 또한 동료들과 함께 문제를 잘 해결하는 개발자가 되고 싶어졌다. 팀 프로젝트를 통해 프로그래밍은 같이하면 더 잘할 수 있고, 더 재밌다는 것을 온몸으로 느꼈기 때문이다. 
```
오.. 우아한테크코스가 방향성을 잡는 데에 엄청난 역할을 한 것 같네요!! 다행!

2021-10-21 18:52 UTC, iborymagic commented on README.md
> +우아한테크코스에서 지난 10개월 동안 백 엔드 개발자로서 정말 큰 성장을 했다. 하지만 우테코에서 얻은 가장 큰 소득은 개발 실력이 아니라고 생각한다. 앞으로 내가 20년, 30년 개발자로 지속해서 살아갈 수 있게 하는 원동력이 더 커졌다. 이것이 우테코에서 얻게 된 가장 큰 가치라고 생각한다. 항상 좋은 가르침을 주시는 우아한테크코스 모든 코치분들 크루
```suggestion
우아한테크코스에서 지난 10개월 동안 백 엔드 개발자로서 정말 큰 성장을 했다. 하지만 우테코에서 얻은 가장 큰 소득은 개발 실력이 아니라고 생각한다. 앞으로 내가 20년, 30년 개발자로 지속해서 살아갈 수 있게 하는 원동력이 더 커졌다. 이것이 우테코에서 얻게 된 가장 큰 가치라고 생각한다. 항상 좋은 가르침을 주시는 우아한테크코스 모든 코치분들 크루들 덕분이라고 생각한다. 프로그래밍 공부가 힘들 때마다 포비가 "프로그래밍은 누구나 할 수 있다."라고 말씀하신 것이 매번 나에게 힘을 줬던 것 같다. 앞으로도 우테코에서 배운 정말 많은 교훈과 가르침을 매번 떠올리며 개발자로 살아갈 수 있다는 게 감사하고 기쁘다.
```
앞으로 펼쳐질 우기의 개발자 인생을 응원합니다!!

2021-10-22 17:53 UTC, pkeugine approved these changes
안녕하세요 우기!!
자료구조와 손코딩 부분에서 '와 이 분은 진정한 개발자다' 라고 느꼈습니다.
20년, 30년을 넘어서 훨씬 오랜 시간동안 개발을 하면서 좋은 프로그램을 만들어 주셨으면 좋겠네요.
글 정말 잘 읽었습니다!!
바로 어푸르브 할게요! 고생하셨습니다 👍

2021-10-22 17:53 UTC, pkeugine commented on README.md
> +나는 컴퓨터공학과를 졸업하긴 했지만 개발을 좋아하는 사람은 전혀아니었다. 1학년때 C프로그래밍 수업을 들을때만 하더라도 너무 재미가 없어서 수업을 아예 안듣고 시험을 안 보기도 했다. 그리곤 다른 학과로 전과를 고민하기도 했다. 그러다가 2학년때 우연히 자료구조 수업을 듣게 되었다. 단순 문법만 배우던 C프로그래밍 수업과 달리 자료구조 수업에서는 내가 직
자료구조 + 손 코딩...
난 내가 프로그래밍을 즐긴다고 생각했는데 진정으로 즐기시는 분이 여기 있네요 ㄷㄷ 👍

2021-10-22 17:53 UTC, pkeugine commented on README.md
> +군대를 다녀온 후에는 1학년 자료구조 수업때 느꼈던 프로그래밍에 대한 흥미를 잃었다. 알고보니 자료구조는 프로그래밍의 기본이고 일부였다.  소프트웨어 개발을 하려면 알아야 하는 지식이 너무나도 많았다. 그런 지식을 어떻게 공부할지 감 조차 안왔다. 사실 알아야 하는 지식 자체가 뭔지 몰랐다. 그럼에도 항상 나 자신을 발전시키려는 의지가 강한 성향 덕분에
저는 즐기기만 하면 될 줄 알았는데 즐기기만 해도 방향과 목표가 없으면 제자리 걸음만 하고 컴포트존을 못 벗어나더라구요.
정말 공감합니다.

2021-10-22 17:53 UTC, pkeugine commented on README.md
> +우아한테크코스에서 지난 10개월 동안 백 엔드 개발자로서 정말 큰 성장을 했다. 하지만 우테코에서 얻은 가장 큰 소득은 개발 실력이 아니라고 생각한다. 앞으로 내가 20년, 30년 개발자로 지속해서 살아갈 수 있게 하는 원동력이 더 커졌다. 이것이 우테코에서 얻게 된 가장 큰 가치라고 생각한다. 항상 좋은 가르침을 주시는 우아한테크코스 모든 코치분들 크루
`20년, 30년 개발자로 지속해서 살아갈 수 있는 원동력이 더 커졌다` 라는 표현이 정말 좋네요 ㅋㅋㅋ
그만큼 큰 가치를 얻은 건 아마 크루들 덕도 있지만 우기가 그만한 노력을 해서가 아닐까 싶네요!

2021-10-24 06:18 UTC, SunYoungKwon approved these changes
안녕하세요! 우기가 프로그래머가 되기 위해 지금까지 걸어온 길이 잘 나타나는 진솔한 글이었어요.
개인적으로 졸업 직전에 뭔가 만들어보고서야 개발자를 해야겠다고 마음을 굳혔는데, 자료구조 수업부터 흥미를 느끼셨다니 대단하네요!

> 앞으로 내가 20년, 30년 개발자로 지속해서 살아갈 수 있게 하는 원동력이 더 커졌다.
저는 이 부분이 지난 1년이 앞으로의 20~30년에 영향을 줄 만큼 열심히 배우고, 노력하셨다는 이야기로 들리네요.

글쓰기미션 수고하셨어요! (리뷰가 늦어 죄송합니다ㅠㅠ)

2021-10-24 06:18 UTC, SunYoungKwon commented on README.md
> +나는 컴퓨터공학과를 졸업하긴 했지만 개발을 좋아하는 사람은 전혀아니었다. 1학년때 C프로그래밍 수업을 들을때만 하더라도 너무 재미가 없어서 수업을 아예 안듣고 시험을 안 보기도 했다. 그리곤 다른 학과로 전과를 고민하기도 했다. 그러다가 2학년때 우연히 자료구조 수업을 듣게 되었다. 단순 문법만 배우던 C프로그래밍 수업과 달리 자료구조 수업에서는 내가 직
저는 자료구조들을 때까지도 아...이거 아닌가? 싶었는데ㅋㅋㅋㅋ 대단해요!

2021-10-24 06:18 UTC, SunYoungKwon commented on README.md
> +군대를 다녀온 후에는 1학년 자료구조 수업때 느꼈던 프로그래밍에 대한 흥미를 잃었다. 알고보니 자료구조는 프로그래밍의 기본이고 일부였다.  소프트웨어 개발을 하려면 알아야 하는 지식이 너무나도 많았다. 그런 지식을 어떻게 공부할지 감 조차 안왔다. 사실 알아야 하는 지식 자체가 뭔지 몰랐다. 그럼에도 항상 나 자신을 발전시키려는 의지가 강한 성향 덕분에
> 저는 즐기기만 하면 될 줄 알았는데 즐기기만 해도 방향과 목표가 없으면 제자리 걸음만 하고 컴포트존을 못 벗어나더라구요.
정말 공감합니다.

저도 완전 공감합니다.

2021-10-25 01:28 UTC, bucketHaneul approved these changes
안녕하세요 우기, 프론트엔드 엘라입니다 ㅎㅎㅎㅎ 우기의 프로그래머가 되고싶은 이유가 담긴 글 너무 잘 읽었어요 ㅎㅎㅎ 공감가는 부분이 많았습니다 👍🏻👍🏻👍🏻

따로 수정 요청 드릴 부분은 없어서 공감되는 부분에 코멘트 살짝 남겼습니당. 바로 어프루브 할게요 😊

(아, 최종 제출 전에 맞춤법 검사기 한번 돌리면 너무 좋을 것 같아요~!!!)

2021-10-25 01:28 UTC, bucketHaneul commented on README.md
> +나는 컴퓨터공학과를 졸업하긴 했지만 개발을 좋아하는 사람은 전혀아니었다. 1학년때 C프로그래밍 수업을 들을때만 하더라도 너무 재미가 없어서 수업을 아예 안듣고 시험을 안 보기도 했다. 그리곤 다른 학과로 전과를 고민하기도 했다. 그러다가 2학년때 우연히 자료구조 수업을 듣게 되었다. 단순 문법만 배우던 C프로그래밍 수업과 달리 자료구조 수업에서는 내가 직
헉 저도 1학년때 C언어 강의 듣다가 수업 탈주했는데,,,ㅎㅎㅎ,,,ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

자료구조도 탈주할까 고민했던 저와 달리 우기는 흥미를 느끼셨군요,,,리스펙,,,,,

2021-10-25 01:28 UTC, bucketHaneul commented on README.md
> +군대를 다녀온 후에는 1학년 자료구조 수업때 느꼈던 프로그래밍에 대한 흥미를 잃었다. 알고보니 자료구조는 프로그래밍의 기본이고 일부였다.  소프트웨어 개발을 하려면 알아야 하는 지식이 너무나도 많았다. 그런 지식을 어떻게 공부할지 감 조차 안왔다. 사실 알아야 하는 지식 자체가 뭔지 몰랐다. 그럼에도 항상 나 자신을 발전시키려는 의지가 강한 성향 덕분에
```suggestion
군대를 다녀온 후에는 1학년 자료구조 수업때 느꼈던 프로그래밍에 대한 흥미를 잃었다. 알고보니 자료구조는 프로그래밍의 기본이고 일부였다. 소프트웨어 개발을 하려면 알아야 하는 지식이 너무나도 많았다. 그런 지식을 어떻게 공부할지 감 조차 안왔다. 사실 알아야 하는 지식 자체가 뭔지 몰랐다. 그럼에도 항상 나 자신을 발전시키려는 의지가 강한 성향 덕분에 무언갈 열심히는 했던 것 같다. 학교 전공 수업을 열심히 듣기고 했고, 연구실에 들어가 논문을 쓰기도 했다. 개발 공모전에 나가서 상을 타고, 알고리즘 문제를 정말 열심히 풀었다. 하지만 지금 생각해보니 가장 중요한 것을 놓치고 있었다. "나는 왜 개발자가 되고 싶은지?", "나는 어떤 개발자가 되고 싶은지?"에 대해 전혀 생각하지 않았다. 구체적인 목표가 없다보니 성장의 방향은 어긋나고 속도는 느렸다. 
```
space가 하나 더 들어간 부분이 있네요 ㅎㅎ

저도 처음에는 개발이 재밌어서 무작정 계속했는데,,,,결국에는 그래서 이걸 왜 하고 싶은건지에 대한 이유를 묻게 되더라구요! 그래야 계속 이어갈 수 있는것 같아요 😊  완전 공감합니다

2021-10-25 01:28 UTC, bucketHaneul commented on README.md
> +방황하는 나에게는 당장 취업을 하는 것 보다 더 큰 미래를 위한 이정표가 필요하다고 생각했다. 그래서 작년하반기 취업 지원을 아예하지 않고 우아한테크코스를 지원했다. 감사하게도 합격했고 여기까지 오게 되었다. 그리고 이제는 "나는 왜 개발자가 되고 싶은지?", "나는 어떤 개발자가 되고 싶은지?"라는 질문에 답을 할 수 있게 되었다. 나는 컴퓨터 기술을
이 문단은 전체적으로 너무 공감되네요 ㅎㅎㅎ 학습에 대해 흥미를 느끼고, 학습한 내용을 토대로 비즈니스 문제를 해결하려는 우기, 너무 멋있어요 👍🏻👍🏻👍🏻

2021-10-26 10:24 UTC, iborymagic approved these changes

2021-11-03 13:17 UTC, devJang approved these changes
와 멋진데요
하반기 취업 지원을 일절 하지 않고 우테코에 지원하다니 이런 과감한 결정에 3기에 합격하고 수료를 앞두고 있다는 점 뿌듯합니다.
우테코에서 얻은 좋은 원동력으로 앞으로 우기에게 펼쳐질 미래를 잘 그려보세요~

2021-11-03 13:17 UTC, merged