[레벨 1 글쓰기 미션] 피카(윤지우) 미션 제출합니다.
woowacourse/woowa-writing-3 pull request #33
Opened 2021-03-24 10:29 UTC by pika96

[Level. 1 글쓰기](https://github.com/pika96/woowa-writing-3/blob/pika96/Level.1%20%EA%B8%80%EC%93%B0%EA%B8%B0.md)

이쁘게 봐주세요! ㅎ

2021-03-25 02:42 UTC, Livenow14 requested changes
"나" 혹은 "내"를 빼면 더 좋은 문장이 될 것 같아요..!
또한 "우아한테크코스"를 "과정"이나, "활동"으로 바꿔도 좋을거같아요...! 

추가적인 감상평은 approve때 할꼐요 .

2021-03-25 02:42 UTC, Livenow14 commented on Level.1 글쓰기.md
> +기쁨, 걱정 그리고 설레임. 우아한 테크코스에서 합격 메일을 받았을 때, 내가 느낀 감정이다. 평소에 진로에 관해 많은 고민이 있었던 나는 졸업을 한 후 내가 해야할 일에 대해 생각하고 있었다. 물론 바로 취업이 되면 좋겠지만, 취업보다는 나의 개발 역량을 알기 때문에 조금 더 개발에 대해 공부하고자 하는 열망이 컸다. 그러다 우연히 우아한테크코스를 보게
```suggestion
기쁨, 걱정 그리고 설레임. 우아한 테크코스에서 합격 메일을 받았을 때 느낀 감정이다. 평소에 진로에 관해 고민이 많았다. 졸업을 한 후 해야할 일에 대해 생각하는 것 쉽지않았다. 물론 바로 취업이 되면 좋겠지만, 취업보다는 개발 역량을 키우자 하는 열망이 컸다. 우연히 우아한테크코스를 지원하고, 합격메일을 받은 순간, 매우 기뻤다. 사실 많이 걱정도 됐다. 10개월동안 우아한테크코스의 과정을 따라갈 수 있을까? 먼 미래에 지금 이 과정을 선택한 것을 후회하지 않을까? 물론 지금은 선택에 대해 후회는 없지만, 그 당시에는 많은 걱정과 고민을 했었다. 결국 내린 결정은 '부딪혀보자' 였다. 한 번 결정을 내리니 걱정보다는 나와 같은 길을 걸어갈 약 70명의 크루들과 10개월을 보낼 생각에 매우 설레였다. 그렇게 우아한테크코스의 생활이 시작되었다.
```

"나" 혹은 "내"를 빼면 더 좋은 문장이 될 것 같아요..!

2021-03-25 02:42 UTC, Livenow14 commented on Level.1 글쓰기.md
> +우아한테크코스의 레벨 1이 거의 끝나가고 있다. 포비가 말한대로 나는 지금 내 걸음으로 잘 걸어 왔는가? 아마 잘 걸어왔고 남은 기간도 내 걸음에 맞추어 잘 걸어 갈 것이라고 믿고 있다.
```suggestion
OT 때 포비가 해준 말 중 가장 인상 깊은 말이 있다. '자신의 속도에 맞추어라'. 사람들은 각자의 속도와 시간이 있다. 몇 년 전만 해도 매우 조급해 있었다. 남들과 비교하며 항상 채찍질 했었다. '왜 다른 사람은 이만큼 했는데, 나는 뭘한걸까?', '내가 뒤쳐졌으니까 더 많이, 빨리 해야겠다.' 조급한 만큼 항상 좋은 결과가 나왔던 것도 아니였다. 중요한 것은 주변의 남과 비교하지 않는 것이었다. 그렇기 때문에 포비의 말에 매우 공감이 되었다. 실제로 우아한테크코스에는 잘하는 크루들이 많다. 하지만 다른 크루들과 비교하지 않고, 내 속도에 맞추어 길을 가려고 노력하고 있다. 
우아한테크코스의 레벨 1이 거의 끝나가고 있다. 포비가 말한대로 나는 지금 내 걸음으로 잘 걸어 왔는가? 아마 잘 걸어왔고 남은 기간도 내 걸음에 맞추어 잘 걸어 갈 것이라고 믿고 있다.
```

저도 '자신의 속도에 맞추어라' 이말은 정말 좋아합니다..! 😊
잘하실거라 믿어요! 
이부분도 "나" 혹은 "내"를 빼면 더 좋은 문장이 될 것 같아요!!

2021-03-25 02:42 UTC, Livenow14 commented on Level.1 글쓰기.md
> +우아한테크코스의 꽃이라고 할 수 있는 페어 프로그래밍. 우아한테크코스를 시작하기 전부터 많이 들었기 때문에, 매우 기대가 되는 활동 중 하나였다. 페어 프로그래밍이란, 하나의 미션을 짝을 지어 수행하는 것을 뜻한다. 처음 페어 프로그래밍을 할 때 매우 느린 개발 속도때문에 답답했다. 아무래도 서로 익숙치 않고 페어와 토론을 하다보니 혼자서하는 것보다 느릴
```suggestion
우아한테크코스의 꽃이라고 할 수 있는 페어 프로그래밍. 과정을 시작하기 전부터 많이 들었기 때문에, 매우 기대가 되는 활동 중 하나였다. 페어 프로그래밍이란, 하나의 미션을 짝을 지어 수행하는 것을 뜻한다. 처음 페어 프로그래밍을 할 때 매우 느린 개발 속도때문에 답답했다. 아무래도 서로 익숙치 않고 페어와 토론을 하다보니 혼자서하는 것보다 느릴 수 밖에 없었다. 하지만 계속 진행하다보니 페어 프로그래밍의 장점들이 많이 느껴졌다. 우선, 토론을 많이 하다보니 설계가 탄탄해졌고 설계를 바탕으로 코드를 짜니 속도도 빨라졌다. 페어와 의견을 나누면서 다양한 생각을 들을 수 있었고, 이는 코드 품질 향상으로 이어졌다. 마지막으로는 페어 프로그래밍의 가장 좋은 장점은 페어와 친해지는 것이라고 생각한다. 페어와 1:1로 같이 미션을 하니 페어에 대해 더 잘 알 수 있고, 많이 친해질 수 있었다. 앞으로 남은 8개월동안 페어 프로그래밍을 통해 다양한 크루들과 만나고 많이 친해지는 것을 목표로 해야겠다.
```
많이 친해져요..! ㅎㅎㅎ

2021-03-25 02:42 UTC, Livenow14 commented on Level.1 글쓰기.md
> +우아한테크코스의 한 달은 개발 뿐만 아니라 개발 외적인 것 또한 배웠던 한 달이였다. 한 달동안 많이 성장했다고 느끼기에 우아한테크코스를 수료하고 성장했을 내가 기다려진다. 앞으로 남은 기간동안 원하는 결과를 얻기 위해 열심히 노력할 것이다.
```suggestion
우아한테크코스의 한 달은 개발 뿐만 아니라 개발 외적인 것 또한 배웠던 한 달이였다. 한 달동안 많이 성장했다고 느끼기에 우아한테크코스를 수료하고 성장할 것이라 믿어 의심치 않는다.. 앞으로 남은 기간동안 원하는 결과를 얻기 위해 열심히 노력할 것이다.
```
같이 성장해요..!

2021-03-25 11:58 UTC, zigsong requested changes
안녕하세요 피카!
닉네임이 귀여워요 피카피카

글이 담백하고 가독성이 좋은 것 같아요 🙃😊
검프가 자세히 수정해주셔서 저는 덧붙여서 일부 코멘트 남겼습니다!

2021-03-25 11:58 UTC, zigsong commented on Level.1 글쓰기.md
> +기쁨, 걱정 그리고 설레임. 우아한 테크코스에서 합격 메일을 받았을 때, 내가 느낀 감정이다. 평소에 진로에 관해 많은 고민이 있었던 나는 졸업을 한 후 내가 해야할 일에 대해 생각하고 있었다. 물론 바로 취업이 되면 좋겠지만, 취업보다는 나의 개발 역량을 알기 때문에 조금 더 개발에 대해 공부하고자 하는 열망이 컸다. 그러다 우연히 우아한테크코스를 보게
`보게되고` -> `보게 되고`가 맞는 것 같습니다!

2021-03-25 11:58 UTC, zigsong commented on Level.1 글쓰기.md
> +기쁨, 걱정 그리고 설레임. 우아한 테크코스에서 합격 메일을 받았을 때, 내가 느낀 감정이다. 평소에 진로에 관해 많은 고민이 있었던 나는 졸업을 한 후 내가 해야할 일에 대해 생각하고 있었다. 물론 바로 취업이 되면 좋겠지만, 취업보다는 나의 개발 역량을 알기 때문에 조금 더 개발에 대해 공부하고자 하는 열망이 컸다. 그러다 우연히 우아한테크코스를 보게
`기쁘지 않을 수 없었다`도 이중부정으로 지양되는 표현이라 검프의 제안에 한 표 추가해봅니당..!

2021-03-25 11:58 UTC, zigsong commented on Level.1 글쓰기.md
> +OT 때 포비가 해준 말 중 가장 인상 깊은 말이 있다. '자신의 속도에 맞추어라' 이 말은 내가 좋아하는 말 중 하나이다. 사람들은 각자의 속도와 시간이 있다. 몇 년 전만 해도 나는 매우 조급했었다. 남들과 비교하며 나 자신을 항상 채찍질 했었다. '왜 다른 사람은 이만큼 했는데, 나는 뭘한걸까?', '내가 뒤쳐졌으니까 더 많이, 빨리 해야겠다.' 조
저도 조급한 게 큰 문제였는데 😂 공감이 되네요
저와 비슷한 걱정과 고민들을 했던 크루들이 많은 것 같아요!

2021-03-25 11:58 UTC, zigsong commented on Level.1 글쓰기.md
> +우아한테크코스의 꽃이라고 할 수 있는 페어 프로그래밍. 우아한테크코스를 시작하기 전부터 많이 들었기 때문에, 매우 기대가 되는 활동 중 하나였다. 페어 프로그래밍이란, 하나의 미션을 짝을 지어 수행하는 것을 뜻한다. 처음 페어 프로그래밍을 할 때 매우 느린 개발 속도때문에 답답했다. 아무래도 서로 익숙치 않고 페어와 토론을 하다보니 혼자서하는 것보다 느릴
프론트랑도 친해져요~~! 🤓

2021-03-26 00:18 UTC, GwangYeol-Im reviewed
코멘트 남겼습니다 :) 저도 최종 감상평은 Approve 에 남기도록 하겠습니다 !!

2021-03-26 00:18 UTC, GwangYeol-Im commented on Level.1 글쓰기.md
> +기쁨, 걱정 그리고 설레임. 우아한 테크코스에서 합격 메일을 받았을 때, 내가 느낀 감정이다. 평소에 진로에 관해 많은 고민이 있었던 나는 졸업을 한 후 내가 해야할 일에 대해 생각하고 있었다. 물론 바로 취업이 되면 좋겠지만, 취업보다는 나의 개발 역량을 알기 때문에 조금 더 개발에 대해 공부하고자 하는 열망이 컸다. 그러다 우연히 우아한테크코스를 보게
- 취업보다는 나의 개발 역량을 알기 때문에 조금 더 개발에 대해 공부하고자 하는 열망이 컸다 -> 나의 개발 역량을 알기 때문에 취업보다는 조금 더 개발에 대해 공부하고자 하는 열망이 컸다
- 매우 기쁘지 않을 수 없었다 : 이중 부정이 강한 긍정이긴 하지만 무언가 표현이 어색한 느낌이 들었어요!
- 설레였다 -> 설렜다 / 설레었다

2021-03-26 00:18 UTC, GwangYeol-Im commented on Level.1 글쓰기.md
> +OT 때 포비가 해준 말 중 가장 인상 깊은 말이 있다. '자신의 속도에 맞추어라' 이 말은 내가 좋아하는 말 중 하나이다. 사람들은 각자의 속도와 시간이 있다. 몇 년 전만 해도 나는 매우 조급했었다. 남들과 비교하며 나 자신을 항상 채찍질 했었다. '왜 다른 사람은 이만큼 했는데, 나는 뭘한걸까?', '내가 뒤쳐졌으니까 더 많이, 빨리 해야겠다.' 조
- '왜 다른 사람은 이만큼 했는데, 나는 뭘한걸까?' : 뉘앙스는 알 수 있지만, 문장 구조가 자연스럽지는 않은 것 같아요!
- 해당 문단에 대해서 공감이 많이 가네요 :)

2021-03-26 00:18 UTC, GwangYeol-Im commented on Level.1 글쓰기.md
> +우아한테크코스의 꽃이라고 할 수 있는 페어 프로그래밍. 우아한테크코스를 시작하기 전부터 많이 들었기 때문에, 매우 기대가 되는 활동 중 하나였다. 페어 프로그래밍이란, 하나의 미션을 짝을 지어 수행하는 것을 뜻한다. 처음 페어 프로그래밍을 할 때 매우 느린 개발 속도때문에 답답했다. 아무래도 서로 익숙치 않고 페어와 토론을 하다보니 혼자서하는 것보다 느릴
```suggestion
우아한테크코스의 꽃이라고 할 수 있는 페어 프로그래밍. 우아한테크코스를 시작하기 전부터 많이 들었기 때문에, 매우 기대가 되는 활동 중 하나였다. 페어 프로그래밍이란, 하나의 미션을 짝을 지어 수행하는 것을 뜻한다. 처음 페어 프로그래밍을 할 때 매우 느린 개발 속도때문에 답답했다. 아무래도 서로 익숙지 않은 상태로 토론까지 하다보니 혼자서 하는 것보다 느릴 수밖에 없었다. 하지만 계속 진행하다보니 페어 프로그래밍의 장점들이 많이 느껴졌다. 우선, 토론을 많이 하다보니 설계가 탄탄해졌고 설계를 바탕으로 코드를 짜니 속도도 빨라졌다. 페어와 의견을 나누면서 다양한 생각을 들을 수 있었고, 이는 코드 품질 향상으로 이어졌다. 마지막으로 내가 생각하기에 페어 프로그래밍의 가장 좋은 장점은 페어와 친해지는 것이라고 생각한다. 페어와 1:1로 같이 미션을 하니 페어에 대해 더 잘 알 수 있고, 많이 친해질 수 있었다. 앞으로 남은 8개월동안 페어 프로그래밍을 통해 다양한 크루들과 만나고 많이 친해지는 것을 목표로 해야겠다.
```

2021-03-26 00:18 UTC, GwangYeol-Im commented on Level.1 글쓰기.md
> +우아한테크코스의 꽃이라고 할 수 있는 페어 프로그래밍. 우아한테크코스를 시작하기 전부터 많이 들었기 때문에, 매우 기대가 되는 활동 중 하나였다. 페어 프로그래밍이란, 하나의 미션을 짝을 지어 수행하는 것을 뜻한다. 처음 페어 프로그래밍을 할 때 매우 느린 개발 속도때문에 답답했다. 아무래도 서로 익숙치 않고 페어와 토론을 하다보니 혼자서하는 것보다 느릴
\+ ~보니, ~니 로 표현되는 문장이 한 문단에서 자주 보이는 것 같아요. 이건 개인적인 취향 차이일 수도 있는데, 조금 더 다양하게 표현하려고 시도해보면 어떨까요? 그럼 읽는 사람도 더 다양한 표현들에 재밌게 읽을 수 있을 것 같아요 :)

2021-03-26 00:18 UTC, GwangYeol-Im commented on Level.1 글쓰기.md
> +우아한테크코스의 한 달은 개발 뿐만 아니라 개발 외적인 것 또한 배웠던 한 달이였다. 한 달동안 많이 성장했다고 느끼기에 우아한테크코스를 수료하고 성장했을 내가 기다려진다. 앞으로 남은 기간동안 원하는 결과를 얻기 위해 열심히 노력할 것이다.
```suggestion
우아한테크코스의 한 달은 개발 뿐만 아니라 개발 외적인 것 또한 배웠던 시기였다. 한 달동안 많이 성장했다고 느끼기에 우아한테크코스를 수료하고 더욱 성장할 내가 기다려진다. 앞으로 남은 기간동안 원하는 결과를 얻기 위해 열심히 노력할 것이다.
```

2021-03-26 07:29 UTC, pika96 commented on Level.1 글쓰기.md
> +기쁨, 걱정 그리고 설레임. 우아한 테크코스에서 합격 메일을 받았을 때, 내가 느낀 감정이다. 평소에 진로에 관해 많은 고민이 있었던 나는 졸업을 한 후 내가 해야할 일에 대해 생각하고 있었다. 물론 바로 취업이 되면 좋겠지만, 취업보다는 나의 개발 역량을 알기 때문에 조금 더 개발에 대해 공부하고자 하는 열망이 컸다. 그러다 우연히 우아한테크코스를 보게
와 감사합니다! 조금 더 깔끔해지네요~

2021-03-26 07:31 UTC, pika96 commented on Level.1 글쓰기.md
> +우아한테크코스의 레벨 1이 거의 끝나가고 있다. 포비가 말한대로 나는 지금 내 걸음으로 잘 걸어 왔는가? 아마 잘 걸어왔고 남은 기간도 내 걸음에 맞추어 잘 걸어 갈 것이라고 믿고 있다.
감사합니다! 나 라는 말이 많이 들어가있네요!

2021-03-26 07:31 UTC, pika96 commented on Level.1 글쓰기.md
> +우아한테크코스의 꽃이라고 할 수 있는 페어 프로그래밍. 우아한테크코스를 시작하기 전부터 많이 들었기 때문에, 매우 기대가 되는 활동 중 하나였다. 페어 프로그래밍이란, 하나의 미션을 짝을 지어 수행하는 것을 뜻한다. 처음 페어 프로그래밍을 할 때 매우 느린 개발 속도때문에 답답했다. 아무래도 서로 익숙치 않고 페어와 토론을 하다보니 혼자서하는 것보다 느릴
넵 ㅎ 조와요~

2021-03-26 07:33 UTC, pika96 commented on Level.1 글쓰기.md
> +우아한테크코스의 한 달은 개발 뿐만 아니라 개발 외적인 것 또한 배웠던 한 달이였다. 한 달동안 많이 성장했다고 느끼기에 우아한테크코스를 수료하고 성장했을 내가 기다려진다. 앞으로 남은 기간동안 원하는 결과를 얻기 위해 열심히 노력할 것이다.
좀 더 깔끔해지네요! 감사합니다 ㅎ

2021-03-26 07:33 UTC, pika96 commented on Level.1 글쓰기.md
> +기쁨, 걱정 그리고 설레임. 우아한 테크코스에서 합격 메일을 받았을 때, 내가 느낀 감정이다. 평소에 진로에 관해 많은 고민이 있었던 나는 졸업을 한 후 내가 해야할 일에 대해 생각하고 있었다. 물론 바로 취업이 되면 좋겠지만, 취업보다는 나의 개발 역량을 알기 때문에 조금 더 개발에 대해 공부하고자 하는 열망이 컸다. 그러다 우연히 우아한테크코스를 보게
감사합니다! 기뻤다는 표현을 많이 지적해주셨는데요! 원래는 강조하려고 쓴 부분이지만 어색하네요! 바꾸겠습니다 ㅎ

2021-03-26 07:34 UTC, pika96 commented on Level.1 글쓰기.md
> +OT 때 포비가 해준 말 중 가장 인상 깊은 말이 있다. '자신의 속도에 맞추어라' 이 말은 내가 좋아하는 말 중 하나이다. 사람들은 각자의 속도와 시간이 있다. 몇 년 전만 해도 나는 매우 조급했었다. 남들과 비교하며 나 자신을 항상 채찍질 했었다. '왜 다른 사람은 이만큼 했는데, 나는 뭘한걸까?', '내가 뒤쳐졌으니까 더 많이, 빨리 해야겠다.' 조
맞아요! 다들 잘하셔서 그런것 같아요 ㅎ

2021-03-26 07:34 UTC, pika96 commented on Level.1 글쓰기.md
> +우아한테크코스의 꽃이라고 할 수 있는 페어 프로그래밍. 우아한테크코스를 시작하기 전부터 많이 들었기 때문에, 매우 기대가 되는 활동 중 하나였다. 페어 프로그래밍이란, 하나의 미션을 짝을 지어 수행하는 것을 뜻한다. 처음 페어 프로그래밍을 할 때 매우 느린 개발 속도때문에 답답했다. 아무래도 서로 익숙치 않고 페어와 토론을 하다보니 혼자서하는 것보다 느릴
너무 좋아요~ 감사합니다!

2021-03-26 07:34 UTC, pika96 commented on Level.1 글쓰기.md
> +기쁨, 걱정 그리고 설레임. 우아한 테크코스에서 합격 메일을 받았을 때, 내가 느낀 감정이다. 평소에 진로에 관해 많은 고민이 있었던 나는 졸업을 한 후 내가 해야할 일에 대해 생각하고 있었다. 물론 바로 취업이 되면 좋겠지만, 취업보다는 나의 개발 역량을 알기 때문에 조금 더 개발에 대해 공부하고자 하는 열망이 컸다. 그러다 우연히 우아한테크코스를 보게
기뻤다는 부분을 많이 지적해주셨네요! 강한 긍정으로 사용하려했는데 어색한 것 같아요! 감사합니다 ㅎ

2021-03-26 07:35 UTC, pika96 commented on Level.1 글쓰기.md
> +OT 때 포비가 해준 말 중 가장 인상 깊은 말이 있다. '자신의 속도에 맞추어라' 이 말은 내가 좋아하는 말 중 하나이다. 사람들은 각자의 속도와 시간이 있다. 몇 년 전만 해도 나는 매우 조급했었다. 남들과 비교하며 나 자신을 항상 채찍질 했었다. '왜 다른 사람은 이만큼 했는데, 나는 뭘한걸까?', '내가 뒤쳐졌으니까 더 많이, 빨리 해야겠다.' 조
잘하시는 분들이 많아 다들 공감을 하시는 것 같아요~ 감사합니다 :)

2021-03-26 07:36 UTC, pika96 commented on Level.1 글쓰기.md
> +우아한테크코스의 꽃이라고 할 수 있는 페어 프로그래밍. 우아한테크코스를 시작하기 전부터 많이 들었기 때문에, 매우 기대가 되는 활동 중 하나였다. 페어 프로그래밍이란, 하나의 미션을 짝을 지어 수행하는 것을 뜻한다. 처음 페어 프로그래밍을 할 때 매우 느린 개발 속도때문에 답답했다. 아무래도 서로 익숙치 않고 페어와 토론을 하다보니 혼자서하는 것보다 느릴
다양한 표현을 사용해보도록 노력할께요! ㅎ 감사합니다~

2021-03-26 15:20 UTC, soulgchoi approved these changes
안녕하세요, 피카! 우테코의 연예인😎
글 잘 읽었습니다.
우테코 시작부터 현재에 이르기까지 피카의 감정선을 따라갈 수 있어서 좋았어요.
부정적이던 생각들이 모두 변화되어 가는 게 인상적이에요.
루터에서 몇 번 인사할 때의 피카와는 다른 면을 볼 수 있었네요.
결심대로 앞으로 많은 것을 이루시기 바랍니다!

2021-03-26 15:20 UTC, soulgchoi commented on Level.1 글쓰기.md
> +우아한테크코스의 레벨 1이 거의 끝나가고 있다. 포비가 말한대로 나는 지금 내 걸음으로 잘 걸어 왔는가? 아마 잘 걸어왔고 남은 기간도 내 걸음에 맞추어 잘 걸어 갈 것이라고 믿고 있다.
이 부분 정말 멋있어요👍 본받겠습니다.

2021-03-26 15:20 UTC, soulgchoi commented on Level.1 글쓰기.md
> +우아한테크코스의 한 달은 개발 뿐만 아니라 개발 외적인 것 또한 배웠던 시기였다. 한 달동안 많이 성장했다고 느끼기에 우아한테크코스를 수료하고 성장할 것이라 믿어 의심치 않는다. 앞으로 남은 기간동안 원하는 결과를 얻기 위해 열심히 노력할 것이다.
```suggestion
우아한테크코스의 한 달은 개발 뿐만 아니라 개발 외적인 것 또한 배웠던 시기였다. 한 달동안 많이 성장했다고 느끼기에 우아한테크코스를 수료하면 더욱더 성장할 것이라 믿어 의심치 않는다. 앞으로 남은 기간동안 원하는 결과를 얻기 위해 열심히 노력할 것이다.
```
이미 앞에서 성장했다고 썼으니까, 그보다 `더 많이` 성장했다고 표현하면 더 좋지 않을까 합니다.
앞에서 카일이 비슷하게 남겼지만 저도 조심스레 한 번 더 남겨봐요.
더더 성장하면 아무튼 좋으니까요~!

2021-03-27 05:28 UTC, zigsong approved these changes
말씀드린 것처럼 크게 흠잡 을 데 없는 깔끔한 글이네요!
피드백을 여러 번 거치면서 더욱 가독성이 좋아진 것 같습니다 🤓
조급하고, 뒤처진다는 느낌들에 공감도 많이 되었어요.
다음 글들도 기대하겠습니다 👍👍

저는 approve할게용!

2021-03-27 05:36 UTC, pika96 commented on Level.1 글쓰기.md
> +우아한테크코스의 레벨 1이 거의 끝나가고 있다. 포비가 말한대로 나는 지금 내 걸음으로 잘 걸어 왔는가? 아마 잘 걸어왔고 남은 기간도 내 걸음에 맞추어 잘 걸어 갈 것이라고 믿고 있다.
감사합니다 소롱!! ㅎ

2021-03-27 05:36 UTC, pika96 commented on Level.1 글쓰기.md
> +우아한테크코스의 한 달은 개발 뿐만 아니라 개발 외적인 것 또한 배웠던 시기였다. 한 달동안 많이 성장했다고 느끼기에 우아한테크코스를 수료하고 성장할 것이라 믿어 의심치 않는다. 앞으로 남은 기간동안 원하는 결과를 얻기 위해 열심히 노력할 것이다.
더욱더 성장할께요 소롱!! ㅎ 감사합니다~

2021-03-27 05:36 UTC, pika96 commented
> 말씀드린 것처럼 크게 흠잡 을 데 없는 깔끔한 글이네요!
> 피드백을 거치면서 더욱 가독성이 좋아진 것 같습니다 🤓
> 조급하고, 뒤처진다는 느낌들에 공감도 많이 되었어요.
> 다음 글들도 기대하겠습니다 👍👍
> 
> 저는 approve할게용!

감사합니다! ㅎ

2021-03-27 12:49 UTC, seojihwan approved these changes
안녕하세요 피카!
자신만의 페이스를 갖기 위해 노력하고 잘 수행하는 점이 멋있네요
한 가지 제안사항 남겨보았어요 확인만 해주시면 될 것 같아요

2021-03-27 12:49 UTC, seojihwan commented on Level.1 글쓰기.md
> +우아한테크코스의 레벨 1이 거의 끝나가고 있다. 포비가 말한대로 나는 지금 내 걸음으로 잘 걸어 왔는가? 아마 잘 걸어왔고 남은 기간도 내 걸음에 맞추어 잘 걸어 갈 것이라고 믿고 있다.
다른 사람을 신경안 쓰고 자신의 페이스를 유지한다는게 말처럼 쉽지 않은데 멋지네요👍

2021-03-27 12:49 UTC, seojihwan commented on Level.1 글쓰기.md
> +우아한테크코스의 한 달은 개발 뿐만 아니라 개발 외적인 것 또한 배웠던 시기였다. 한 달동안 많이 성장했다고 느끼기에 우아한테크코스를 수료하고 성장할 것이라 믿어 의심치 않는다. 앞으로 남은 기간동안 원하는 결과를 얻기 위해 열심히 노력할 것이다.
어떤점을 많이 성장하셨는지도 공유해주시면 어떨까요? 🤔
우테코 기간동안 원하는 결과가 어떤 것인지도 공유해주시면 좋겠네요👍

2021-03-28 03:36 UTC, pika96 commented on Level.1 글쓰기.md
> +우아한테크코스의 한 달은 개발 뿐만 아니라 개발 외적인 것 또한 배웠던 시기였다. 한 달동안 많이 성장했다고 느끼기에 우아한테크코스를 수료하고 성장할 것이라 믿어 의심치 않는다. 앞으로 남은 기간동안 원하는 결과를 얻기 위해 열심히 노력할 것이다.
감사합니다! ㅎ

2021-03-28 04:01 UTC, Livenow14 approved these changes
피드백 이후 더 가독성이 좋아진거 같아요 :) 
피카의 성장기? 를 보는듯한 느낌이어서 좋았어요! 😊
같이 성장하길 바랍니다!! 

approve할게요!

2021-03-28 04:09 UTC, GwangYeol-Im approved these changes
고생많으셨습니다 ! 한번도 대면으로 뵙지는 못했지만, 피카의 생각을 잘 알 수 있어 좋았어요 ㅎㅎ 앞으로도 화이팅하시길 바랍니다 :)

2021-03-28 06:37 UTC, jum0 reviewed
피카 글을 통해 피카를 좀 더 알 수 있었습니다!

간단하게 코멘트 몇 가지만 확인 부탁드려요!

2021-03-28 06:37 UTC, jum0 commented on Level.1 글쓰기.md
> +기쁨, 걱정 그리고 설레임. 우아한 테크코스에서 합격 메일을 받았을 때, 느낀 감정이다. 평소에 진로에 관해 많은 고민이 많았다. 졸업을 한 후 해야할 일에 대해 생각하는 것은 쉽지 않았다. 물론 바로 취업이 되면 좋겠지만, 취업보다는 나의 개발 역량을 키우고자 하는 열망이 컸다. 우연히 우아한테크코스를 지원하고, 합격메일을 받은 순간, 매우 기뻤다. 사
```suggestion
기쁨, 걱정 그리고 설레임. 우아한 테크코스에서 합격 메일을 받았을 때, 느낀 감정이다. 평소에 진로 문제로 고민이 많았다. 졸업을 한 후 해야할 일에 대해 생각하는 것은 쉽지 않았다. 물론 바로 취업이 되면 좋겠지만, 취업보다는 나의 개발 역량을 키우고자 하는 열망이 컸다. 우연히 우아한테크코스를 지원하고, 합격메일을 받은 순간, 매우 기뻤다. 사실 많이 걱정도 되었다. 내가 10개월동안 우아한테크코스의 과정을 따라갈 수 있을까? 먼 미래에 지금 이 과정을 선택한 것을 후회하지 않을까? 물론 지금은 선택에 대해 후회는 없지만, 그 당시에는 많은 걱정과 고민을 했었다. 결국 내린 결정은 '부딪혀보자' 였다. 한 번 결정을 내리니 걱정보다는 나와 같은 길을 걸어갈 약 70명의 크루들과 10개월을 보낼 생각에 매우 설레었다. 그렇게 우아한테크코스의 생활이 시작되었다.
```
- `많은 고민이 많았다`에 '많다'라는 의미가 중복되어 조금 어색하게 다가왔던 것 같아요!
- `~에 관하여(해)`는 일본식 표현이라 지양하는 게 좋다고 하더라구요.

2021-03-28 06:37 UTC, jum0 commented on Level.1 글쓰기.md
> +우아한테크코스의 꽃이라고 할 수 있는 페어 프로그래밍. 과정을 시작하기 전부터 많이 들었기 때문에, 매우 기대가 되는 활동 중 하나였다. 페어 프로그래밍이란, 하나의 미션을 짝을 지어 수행하는 것을 뜻한다. 처음 페어 프로그래밍을 할 때 매우 느린 개발 속도때문에 답답했다. 아무래도 서로 익숙하지 않은 상태로 토론까지 하다보니 혼자서하는 것보다 느릴 수
페어 프로그래밍을 깔끔하게 설명해주신 것 같아요!👍

2021-03-28 06:53 UTC, pika96 commented on Level.1 글쓰기.md
> +기쁨, 걱정 그리고 설레임. 우아한 테크코스에서 합격 메일을 받았을 때, 느낀 감정이다. 평소에 진로에 관해 많은 고민이 많았다. 졸업을 한 후 해야할 일에 대해 생각하는 것은 쉽지 않았다. 물론 바로 취업이 되면 좋겠지만, 취업보다는 나의 개발 역량을 키우고자 하는 열망이 컸다. 우연히 우아한테크코스를 지원하고, 합격메일을 받은 순간, 매우 기뻤다. 사
정말 '많다'가 중복되어있네요 감사합니다! :)

2021-03-28 06:53 UTC, pika96 commented on Level.1 글쓰기.md
> +우아한테크코스의 꽃이라고 할 수 있는 페어 프로그래밍. 과정을 시작하기 전부터 많이 들었기 때문에, 매우 기대가 되는 활동 중 하나였다. 페어 프로그래밍이란, 하나의 미션을 짝을 지어 수행하는 것을 뜻한다. 처음 페어 프로그래밍을 할 때 매우 느린 개발 속도때문에 답답했다. 아무래도 서로 익숙하지 않은 상태로 토론까지 하다보니 혼자서하는 것보다 느릴 수
칭찬 감사합니다! :)

2021-03-28 08:12 UTC, jum0 approved these changes
수정된 부분 확인했습니다!

피카의 글을 읽으면서 다른 페어와의 비교, 페어 프로그래밍의 장점을 다시 고민해 볼 수 있었어요!
한동안 이 생활에 익숙해져서 당연한 것으로만 여겼는데, 다시 그 의미를 생각해 보며 하려고 합니다:)

다음에는 글이 아닌 오프라인으로 만났으면 좋겠습니다🌸🌸

2021-04-12 07:03 UTC, Wonmi91 approved these changes
안녕하세요 피카 : ) 

자신만의 속도로 묵묵히 걸어가면 피카가 원하는 결과를 얻을 수 있을 거예요.
피카의 친화력이라면 모든 크루들과 친해지는 것도 금방 이루어질 것 같네요!
글 쓰느라 고생 많이 하셨습니다! (다음엔 지금보다 좀 더 길게 피카의 생각을 드러내주면 어떨까요~?)

2021-04-12 07:03 UTC, merged