[레벨 1 글쓰기 미션] 알리(허진호) 미션 제출합니다
woowacourse/woowa-writing-3 pull request #35
Opened 2021-03-24 14:49 UTC by jh8579

안녕하세요 와일더, 에어, 코다, 포모, 콜린, 체프!
다들 글을 너무 잘쓰셔서 제 글이 방학숙제 일기처럼 보일까 걱정이네요 ㅜ
좋은 피드백 많이 주시면 적용해볼게요.
감사합니다!

2021-03-25 13:09 UTC, lns13301 reviewed
안녕하세요 알리! 👻
제가 남긴 리뷰에서 필요한 부분만 참고하시면 되겠습니다. 🤗
알리가 한 달간 프로그래밍을 하면서 고뇌했던 부분을 알게 되었어요.
이번 글쓰기 미션도 쉽지 않으셨을 텐데, 미션 요구사항에 맞게 작성하기 위해 노력한 흔적들이 보이네요.
내용에 대해서 크게 리팩토링 할 부분이 많아 보이지는 않네요. 👍
다만 제가 아쉽게 느낀 부분은 전체적으로 반성하는 내용이 주류를 이루게 되면서 분위기가 가라앉는 느낌이 났어요. 😔
반성도 좋지만 우테코를 하면서 뿌듯했던 점, 성취한 점도 포함하면 글이 한 층 더 입체적인 글로 진화할 수 있겠네요. ✨
피드백 반영 후 리뷰 재요청해 주세요~!

2021-03-25 13:09 UTC, lns13301 commented on level1.md
> +코드만으로는 이해가 가지 않는다면 바로
'물어본다.' 를 붙여서 한 문장으로 만드는 게 좋아 보여요 😋

2021-03-25 13:09 UTC, lns13301 commented on level1.md
> +페어가 끝난 이후에 해당 내용을 정리해보면 좋을 것 같다.
'~할 것 같다.'라는 끝맺음 보다는 '~다.'로 끝나는 확답이 읽는 이를 더 집중시킬 수 있다고 생각해요. 🧐

2021-03-25 13:09 UTC, lns13301 commented on level1.md
> +# 우테코 한 달 후기
프로그래밍 미션에만 초점을 두고 글을 작성하셨네요.
이외의 이야기도 포함해서 글을 작성하면 글이 더 풍부해지고 재미있을 것 같아요! 😄

2021-03-25 13:09 UTC, lns13301 commented on level1.md
> +리팩토링을 시작하기 전에 내가 정확히 어떤 부분을 개선하고 싶은지 기록하고,
문장의 길이가 길어져서 분리하면 좋겠어요. 😣

리팩토링을 시작하기 전에 내가 정확히 어떤 부분을 개선하고 싶은지 기록한다.

2021-03-25 16:09 UTC, KJunseo reviewed
안녕하세요 알리! 에어입니다!!
깔끔하게 잘 쓰셨네요! 공감가는 부분도 있고 필요한 내용만 있어서 잘 읽혔어요👍🏻👍🏻
알리의 생각을 알게 되어 좋은 것 같네요!!
저도 글을 잘 쓰는 편이 아니라 개인적인 의견만 달아봤어요! 꼭 반영하실 필요는 절대 없습니다 ㅎㅎ 
잘 읽었어요!!

2021-03-25 16:09 UTC, KJunseo commented on level1.md
> +코드만으로는 이해가 가지 않는다면 바로
저도 와일더 의견에 동의해요! `코드만으로는 이해가 가지 않는다면 바로 물어본다.` 라고 붙여서 작성 후에 각 항목들이 나와도 좋을 것 같네요! 👍🏻
```suggestion
코드만으로는 이해가 가지 않는다면 바로 물어본다.
```

2021-03-25 16:09 UTC, KJunseo commented on level1.md
> +이렇게 넘어가면 나중에 비슷한 기능을 개발할 때,
`어떻게 동작을 하는지`와 `어떻게 사용하는지`를 물어보고 정리하지 않고 넘어가면 좋지 않다는 의미일까요?? 아주 조금 헷갈리는 것 같아요! 만약 정리하지 않고 넘어가는것이 좋지 않다는 의미가 맞다면 `물어보기만 하고 정리해두지 않는다면 ~ `과 같은 뉘앙스도 괜찮을 것 같다는 생각이 드네요! 😄

2021-03-25 16:09 UTC, KJunseo commented on level1.md
> +주변에서 하는 대로 수동적으로 무언가를 해왔다.
정말 공감가는 내용이네요 😭 저도 항상 수동적이었던 것 같아요

2021-03-25 16:09 UTC, KJunseo commented on level1.md
> +또 리팩토링한 부분을 페어와 공유할 수 있다면 더 좋은 리팩토링이 될 수 있다고 생각한다.
리팩토링 과정을 기록으로 남기는 것도 좋겠네요! 저도 나중에 한 번 해봐야겠어요👍🏻👍🏻

2021-03-26 08:15 UTC, bosl95 reviewed
저의 지극히 개인적인 의견을 달아보았습니다...🙏
보시고 괜찮으신거 같으면 적용해주세요 ㅎㅎ

2021-03-26 08:15 UTC, bosl95 commented on level1.md
> +위 목표를 함께 지킬 방법이 있을지 되새겨보려고 한다.
띄어쓰기를 하지 않아도 충분히 가독성이 있을 거 같아요!

2021-03-26 08:15 UTC, bosl95 commented on level1.md
> +이번 우테코를 시작하면서 두 가지를 목표를 세웠다.
초반에 '자기 주도적'이라는 이야기로 시작되는데, 그 부분을 우테코에 오셔서 시작하셨다는 내용이신거죠??? 👍👍👍👍
이 부분을 좀 더 표현해주시면 어떨까요?????☺️

2021-03-26 15:19 UTC, yjksw reviewed
알리 앞으로 하고 어떻게 하고 싶은지 잘 정리해서 써준 것 같아요~! 
이렇게 글에서 쓴대로 레벨2서부터는 잘 할 수 있길 기대합니다!! 😆
앞으로도 화이팅!!

2021-03-26 15:19 UTC, yjksw commented on level1.md
> +>"우테코를 통해 자기 주도적 학습 능력을 기르고 싶다."
우테코에서 얻고 싶은 것을 잘 언급하고 글을 시작해서 좋네요!!

2021-03-26 15:19 UTC, yjksw commented on level1.md
> +
앞으로는 꼭 할 수 있길!! 👍

2021-03-26 15:19 UTC, yjksw commented on level1.md
> +리팩토링을 시작하기 전에 내가 정확히 어떤 부분을 개선하고 싶은지 기록하고,
기록에 대해서 알리가 느낀 중요성이 글 전반적으로 잘 반영이 되어서 좋네요~!

2021-03-27 04:01 UTC, 2SOOY requested changes
안녕하세요 ! 알리 :)
우선 글 작성하시느라 고생 많으셨다는 말을 드리고 싶네요 👍👍👍

알리의 솔직한 이야기를 들려주셔서 감사합니다 🙏
전반적으로 `앞으로 어떻게 변화할지`에 대해 작성해주셨는데, 우테코에서 알리가 `했었던` 것에 대한 이야기도 듣고 싶네요 ! (미션 외의 이야기라면 더욱 좋을 것 같아요)

남은 기간 잘 마무리 하시고, 다음 레벨에서는 알리가 목표했던 것들을 꼭 이루셨으면 좋겠습니다 ✊✊✊

글 작성하시느라 고생 많으셨어요 👏👏👏

2021-03-27 04:01 UTC, 2SOOY commented on level1.md
> +과정을 하나도 지키지 못하고 있다...
알리가 목표했던 것들을 지키지 못한 원인이 무엇이었을지 궁금하네요 ❓

2021-03-27 11:15 UTC, Puterism commented on level1.md
> +페어가 끝난 이후에 해당 내용을 정리해보면 좋을 것 같다.
다짐한다는 뜻에서 '앞으로 ~해야겠다'와 같이 작성하시는 것도 좋을 것 같아요!

2021-03-27 11:19 UTC, Puterism commented on level1.md
> +그러다 보니 결국엔 결과만 남고 과정은 남지 않았다.
누군가 시키는 대로만 했더니 **왜** 결과만 남고 과정은 남지 않았는지 이야기해주시면 좋을 것 같아요!

2021-03-27 11:28 UTC, Puterism requested changes
알리 안녕하세요! 글 잘 읽었습니다!
문장 하나하나가 잘 분리되고 읽기 편한 글이어서 좋았습니다.

아쉽게도 너무 호흡이 짧아서 글을 읽는데 상황이 쉭쉭 바뀌는 듯한 느낌을 받았어요.
알리가 생각한 것들에 대해서 이유를 조금만 보충해주신다면 더 좋을 것 같아요!

2021-03-27 13:25 UTC, jh8579 commented
열심히 피드백 주신 부분들 적용해봤습니다.
다들 고생하셨어요!

2021-03-27 14:31 UTC, yjksw reviewed
알리 수고했어요~! ㅎㅎㅎ 
그래도 레벨1 한 호흡이 끝나니 조금만 더 힘내면 쉴 수 있네요 😊
그때까지 화이팅하면서 잘 배워봅시다! 👍

2021-03-27 14:31 UTC, yjksw approved these changes

2021-03-27 14:54 UTC, 2SOOY approved these changes
알리 고생 많으셨어요 👏👏👏

2021-03-27 15:03 UTC, lns13301 approved these changes
수고하셨습니다. 많이 오르셨으면 좋겠고, 남은 미션 마무리 잘하세요. 👍

2021-03-27 15:06 UTC, bosl95 approved these changes
글 쓰시느라 고생 많으셨습니다 👏👏👏👏👏
level2도 화이팅입니당!! ㅎㅎ

2021-03-27 16:03 UTC, KJunseo approved these changes
알리 글 잘 읽었습니다!! approve 드릴게요! 
남은 미션도 화이팅!!💪💪💪

2021-03-28 14:15 UTC, Puterism approved these changes
알리 이번 레벨 동안 고생 많으셨어요!! Approve 딱지 드립니다~~

2021-05-10 06:01 UTC, woowahan-pjs approved these changes
이 글을 쓴 지 한 달이 넘었어요! 지금의 알리는 어떤가요? 이만 Merge 할게요.

2021-05-10 06:01 UTC, merged