[레벨1 글쓰기 미션] 로키(김경록) 미션 제출합니다.
woowacourse/woowa-writing-3 pull request #36
Opened 2021-03-24 16:30 UTC by Rok93

글을 워낙 TMI하게 쓰는 경향이 있어서...😅  
다 쓰고도 글 줄이기 작업을 한참 했어요 😭 
열심히 적었는데 제 글에 참 만족을 못하겠네요.

이미 다른 분들의 글을 보면서 눈이 높아질대로 높아져서 그럴지도 모르겠네요 🤣🤣🤣
다들 어떻게 그리 잘적으시는지... 😳😳😳 
꼭 구체적이지 않더라도 편하게 피드백 주시면 달게 받겠습니다. 

[글 편하게 읽기](https://github.com/Rok93/woowa-writing-3/blob/rok93/level1.md) 

🌟 리뷰어님들 잘 부탁드려요 🙇‍♂️ 

에드 @sjpark-dev
조엘 @PapimonLikelion
욘 @thisisyoungbin 
하루 @365kim
도비 @zereight
배럴 @knae11

2021-03-25 00:37 UTC, knae11 reviewed
안녕하세요 로키! 제 글에도 피드백을 너무 잘 남겨주셔서 저도 열심히 남겨봤습니다!!ㅎㅎㅎ 제 피드백이 약간은 횡설수설한 것 같기도 한데요ㅠㅠ 혹시 피드백이 애매하다고 생각드는 부분이 있다면 답글 남겨주시면 다시 확인해 볼게요!

2021-03-25 00:37 UTC, knae11 commented on level1.md
> +우아한테크코스 크루로써 활동한 지 벌써 한 달이 지났다. 세 번의 지원 끝에 3기 백엔드 크루로 합류하여 우아한 개발자가 되기 위한 노력을 하고 있다. 우테코와 나의 인연은 꽤 오래됐다. 우아한테크코스가 첫 기수를 모집할 때, 우테코에 지원하면서 본격적으로 개발자의 길을 걷기 시작했다.
```suggestion
우아한테크코스 크루로서 활동한 지 벌써 한 달이 지났다. 우테코와 나의 인연은 꽤 오래됐다. 우아한테크코스가 첫 기수를 모집할 때, 우테코에 지원하면서 본격적으로 개발자의 길을 걷기 시작했다. 
세 번의 지원 끝에 3기 백엔드 크루로 합류할 수 있었고, 우아한 개발자가 되기 위한 노력을 하고 있다. 
```
[로서와 로써](https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=125661)
저도 이거 매번 헷갈려서 찾아보는데요 로서 가 적합한 것 같아요~ㅎㅎㅎ

문맥 구성을 바꿔보았는데 어떤가요?

2021-03-25 00:37 UTC, knae11 commented on level1.md
> +두 번째로 지원했던 우테코에 떨어지면서 시작했던 '우형없는 우테코' 스터디는 함께 공부하는 것에 대한 즐거움을 알게 해주었다. 스터디에서 우테코 프리코스 과정을 따라 하다가 1기 크루로부터 받았던 코드리뷰는 앞으로 어떤 공부를 해야 할지에 대한 방향을 제시해주었다.
어떤 방식의 스터디였는지 한줄정도로 짧게 설명해주면 뒤의 1기 크루들로부터 받았던 코드리뷰 이런것에 대한 이해가 높아질 것 같아요!ㅎㅎㅎ

2021-03-25 00:37 UTC, knae11 commented on level1.md
> +두 번의 쓴맛을 본 나는 우아한테크코스가 더더욱 환상과도 같았다. 환상은 현실에서 존재하지 않는 것이기에 우테코에 합류한 순간부터는 더는 우테코가 환상처럼 보이지 않을 것으로 생각했다.
뭔가 어떻게 생각하는지 좀 더 구체적으로 설명해주면 좋을 듯 싶어요!ㅎㅎㅎ 뭔가 의도하는 바는 알 것 같은데 조금 모호하게 느껴지는 느낌이에요.. 우테코가 환상처럼 보이지 않을 것으로 생각하면 어떻게 생각하는지??

2021-03-25 00:37 UTC, knae11 commented on level1.md
> +다행히 세 번째 미션부터는 일주일에 두 번은 루터회관에 갈 수 있게 되었고 처음으로 크루들과 코치들을 만났다. 수업방식은 동일했지만 크루들이 수업을 들으면서 느끼는 감정들을 현장에서 고스란히 느낄 수 있었고 크루들 코치들과 서로 교감한다고 느꼈다. 페어와의 짝 프로그래밍, 포비와 코치들의 가르침, 리뷰어의 피드백 등 성장을 할 수 밖에없는 좋은 환경이라고
```suggestion
다행히 세 번째 미션부터는 일주일에 두 번은 루터회관에 갈 수 있게 되었고 처음으로 크루들과 코치들을 만났다. 수업방식은 동일했지만 크루들이 수업을 들으면서 느끼는 감정들을 현장에서 고스란히 느낄 수 있다. 크루들 코치들과 서로 교감한다고 느꼈다. 페어와의 짝 프로그래밍, 포비와 코치들의 가르침, 리뷰어의 피드백 등 성장을 할 수 밖에없는 좋은 환경이라고 느꼈다. 
```
각각 어떤 교감이라고 느꼈는지 구체적으로 설명해주면 좀 더 좋을 것 같기도 해요!ㅎㅎㅎ

2021-03-25 00:37 UTC, knae11 commented on level1.md
> +누가 시키지 않았음에도 자연스럽게 스터디를 모집하는 것이 시작이었다. 코치들이 툭툭 던지는 주제들은 자연스럽게 많은 크루들의 토론으로 이어졌다. 또한, 공부한 것을 정리하여 서로에게 공유하기도 하고 To-Read list를 만들어 책 읽기를 권장하는 활동도 하였다. 무엇보다도 가장 좋은 점은 미션을 수행하다가 막히는 부분을 눈에 보이는 크루 아무나 붙잡아
ㅋㅋㅋㅋㅋㅋ공감되욬ㅋㅋㅋ 너무나 자연스럽게 개발 얘기하고 스터디하는 것들!!ㅋㅋㅋㅋ

2021-03-25 00:37 UTC, knae11 commented on level1.md
> +> "저의 꾸준한 자기개발과 소통능력으로 회사의 서비스에 기여하겠습니다".
```suggestion
> "저의 꾸준한 자기개발과 소통능력으로 회사의 서비스에 기여하겠습니다."
```
사소한데.. 마침표가 따옴표 안에 있는게 더 자연스러울 것 같아요.

2021-03-25 00:37 UTC, knae11 commented on level1.md
> +우테코의 미션은 매번 페어 프로그래밍으로 시작한다. 3인페어를 한 적도 있어 지금까지 5명의 짝을 만났다. 4번의 페어 프로그래밍을 통해서 면접장에서 했던 자기 소개는 정확히 4번째로 거짓말임이 증명됐다. 사람을 만나 대화하는 것을 좋아하고 낯선 사람한테도 말을 잘 붙이는 성격탓에 '나는 다르겠지'라는 생각을 했던 것 같다. 매번 페어 프로그래밍 끝에는
```suggestion
우테코의 미션은 매번 페어 프로그래밍으로 시작한다. 3인페어를 한 적도 있어 지금까지 5명의 짝을 만났다. 4번의 페어 프로그래밍을 통해서 면접장에서 했던 자기 소개는 4번의 페어프로그래밍으로 정확히 거짓말임이 증명됐다. 사람을 만나 대화하는 것을 좋아하고 낯선 사람한테도 말을 잘 붙이는 성격탓에 '나는 다르겠지'라는 생각을 했던 것 같다. 매번 페어 프로그래밍 끝에는 아쉬움이 남았다. 이번에는 이렇게 다음에는 저렇게 하며 나만의 의견 조율 방법을 찾기위한 시행착오를 거치고있다. 
```
이걸 의도하신 걸까요?? 4번째로 거짓말이 모호하게 느껴져서요! 다르겠지..이 부분이 저는 어떤 점에서 다를거라고 생각하는지 약간 이해가 잘 안 되요ㅠㅠ

2021-03-25 00:37 UTC, knae11 commented on level1.md
> +짝에게 설명을 하려다가 제대로 못한 적이 종종 있었고 내가 알고있다고 착각하는 것들이 많다는 것을 알게되었다. 덕분에 안다고 착각하던 중요한 개념들을 제대로 정리하는 계기가 되었다.
```suggestion
짝에게 설명을 하려다가 제대로 못한 적이 종종 있었고, 그동안 많은 것을 안다고 착각하고 있다는 사실을 알게 되었다. 덕분에 안다고 착각하던 중요한 개념들을 제대로 정리하는 계기가 되었다.
```
음.. 해당 문장이 조금 정리되었으면 좋겠다는 생각이 들어서 약간 수정해봤는데 잘 모르겠네요ㅠㅠ 알고 알고 가 반복되는 느낌이라 줄여보려고 했는데 제 문장에도 여전히 중복이라..ㅠㅠ 

이 문장이 정리되면 좋겠다고 생각해서 정리해보려고 했는데.. 부족한 피드백이네요🙏 조금 정리되면 좋겠다는 생각은 들어요!ㅎㅎㅎㅎ 제 피드백이 모호하시면 그냥 넘어가도 상관 없습니다!ㅎㅎ

2021-03-25 00:37 UTC, knae11 commented on level1.md
> +무엇보다도 가장 큰 수확은 '모르는 것을 모르겠다고 말할 용기'를 얻게 된 것이다. 이유는 모르겠지만 모르겠다라고 말하면 큰일이라도 날 것 같은 강박관념을 가졌었다. '아는 체' 하는 것이 가장 손해라고 포비도 코치들도 누누히 말했었지만 생각과는 다르게 실천으로 옮기지는 못했다. 짝 프로그래밍을 하면서 페어의 생각을 쫓아가지 못하면서도 아는 체 했던 적이
```suggestion
무엇보다도 가장 큰 수확은 '모르는 것을 모르겠다고 말할 용기'를 얻게 된 것이다. 이유는 알 수 없지만 `모르겠다`라고 말하면 큰일이라도 날 것 같은 강박관념을 가졌었다. '아는 체' 하는 것이 가장 손해라고 포비도 코치들도 누누히 말했었지만 생각과는 다르게 실천으로 옮기지는 못했다. 짝 프로그래밍을 하면서 페어의 생각을 쫓아가지 못하면서도 아는 체 했던 적이 있었다. 대충 넘어갔던 부분이 나중에는 더 복잡해져 도저히 코드를 이해할 수 없는 상황까지 이르렀다. 뒤늦게나마 페어에게 모르고 지나갔던 부분을 질문하며 생각의 차이를 좁힐 수 있었다. 이 경험으로 모르는 것은 처음부터 말해야 겠다는 용기를 가지게 되었다.
```
이것도 개인 취향이긴 한데, 같은 단어가 반복되는 것보다 동의어로 대체해주는게 반복스러운 느낌을 줄여주는 것 같더라구요! 

마지막에 정리 문장 추가해주면 좋을 듯 싶어요!ㅎㅎㅎㅎ

2021-03-25 00:37 UTC, knae11 commented on level1.md
> +어떤 개발자가 되고 싶냐는 질문을 받은 적이 있다. 어떤 개발자가 되고 싶은지에 대해 고민해본적이 한번도 없어서 두리뭉실한 대답을 했었다. 이 질문에 대해 고민해본 결과 팀원들에게 '함께 일하고 싶은 개발자'로 기억되는 것이 나에게 가장 큰 행복이라고 생각했다.함께 일하고 싶은 개발자는 '하드 스킬'뿐만 아니라 '소프트 스킬'도 겸비한 개발자라고 생각한다
```suggestion
어떤 개발자가 되고 싶냐는 질문을 받은 적이 있다. 어떤 개발자가 되고 싶은지에 대해 고민해본 적이 한 번도 없어서 두리뭉실한 대답을 했었다. 이 질문에 대해 고민해본 결과, 내가 되고 싶은 개발자는 팀원들에게 '함께 일하고 싶은 개발자`이다. 함께 일하고 싶은 개발자는 '하드 스킬'뿐만 아니라 '소프트 스킬'도 겸비한 개발자라고 생각한다. 앞으로 남은 우테코의 기간동안 많은 시도를 하며 나의 목표에 가까워질 것이다. 
```
어떤 개발자가 되고 싶은지 한문장으로 딱! 단언형으로 표현하면 더 명확해 질 것 같다는 생각이 들었어요. 

그리고 마지막 문장은 이유는 잘 모르겠지만 수정해본게 좀 더 목표에 가까워지는 느낌을 줄 것 같기도 해요.. 이건 이유는 잘 모르겠는걸 보니, 고민해보실 필요는 없고 참고만 해주세요! :)

2021-03-25 01:54 UTC, Rok93 commented on level1.md
> +우테코의 미션은 매번 페어 프로그래밍으로 시작한다. 3인페어를 한 적도 있어 지금까지 5명의 짝을 만났다. 4번의 페어 프로그래밍을 통해서 면접장에서 했던 자기 소개는 정확히 4번째로 거짓말임이 증명됐다. 사람을 만나 대화하는 것을 좋아하고 낯선 사람한테도 말을 잘 붙이는 성격탓에 '나는 다르겠지'라는 생각을 했던 것 같다. 매번 페어 프로그래밍 끝에는
음.. '새로운 페어를 만날 때 마다'  소통능력이 부족하다고 느낀다!? 라는 말을 강조하고 싶었는데 의도가 잘 안드러났던 것 같네요 😭

2021-03-25 05:17 UTC, thisisyoungbin reviewed
로키 안녕하세요~!!! ㅋㅋ 같이 글쓰기 미션 어떡할 건지 고민했었는데... 저희 둘 다 해내긴 했네요!! 
글을 읽으며 생각이 비슷한 부분들이 많아, 많이 공감하면서 읽었습니다.


제가 피드백 드린 부분들은 개인적으로 글을 읽으면서 들었던 생각들을 적어봤어요! 반드시 수정하거나 반영할 필요는 없으니 참고만 하시라고 말씀드리고 싶네요! 


로키의 개인적인 우테코 지원 경험 덕에 우테코가 특히 더 소중하게 느껴질 것 같은데요! 
수료까지 같이 화이팅해요!! 💪

2021-03-25 05:17 UTC, thisisyoungbin commented on level1.md
> +우아한테크코스 크루로써 활동한 지 벌써 한 달이 지났다. 세 번의 지원 끝에 3기 백엔드 크루로 합류하여 우아한 개발자가 되기 위한 노력을 하고 있다. 우테코와 나의 인연은 꽤 오래됐다. 우아한테크코스가 첫 기수를 모집할 때, 우테코에 지원하면서 본격적으로 개발자의 길을 걷기 시작했다.
배럴 의견에 추가해보면 `우아한테크코스 크루로 활동한 지 ~`식으로 적어도 될 것 같아요!

2021-03-25 05:17 UTC, thisisyoungbin commented on level1.md
> +두 번째로 지원했던 우테코에 떨어지면서 시작했던 '우형없는 우테코' 스터디는 함께 공부하는 것에 대한 즐거움을 알게 해주었다. 스터디에서 우테코 프리코스 과정을 따라 하다가 1기 크루로부터 받았던 코드리뷰는 앞으로 어떤 공부를 해야 할지에 대한 방향을 제시해주었다.
전 로키랑 페어하면서 들었던 이야기라 '그렇지 그렇지'했는데, 모르는 사람이 보면 어떤 스터디였는지 궁금할 수도 있겠네요!! 프리코스 과정을 따라한다는 것을 조금만 더 자세하게 설명해도 괜찮을 거 같네요!

2021-03-25 05:17 UTC, thisisyoungbin commented on level1.md
> +우테코의 교육과정은 기술적인 부분만큼 소프트 스킬도 중요시하는 우테코의 취지가 잘 녹아있다. 하지만 기대가 큰 탓이었는지 온라인으로 두 번의 미션을 진행할 때까지는 페어 프로그래밍을 제외하고는 우테코에 별다른 특별한 점을 못 느꼈다. 단순하게 우테코에 너무 큰 환상을 가지고 있었기에 아쉽게 느껴지는 것으로 생각했다.
소프트 스킬도 중요시하는 우테코의 교육과정 이야기가 나왔는데, 뒷문장에선 소프트 스킬과 관련된 이야기가 없어서 약간 연관성이 떨어진다고 느꼈어요..!

2021-03-25 05:17 UTC, thisisyoungbin commented on level1.md
> +누가 시키지 않았음에도 자연스럽게 스터디를 모집하는 것이 시작이었다. 코치들이 툭툭 던지는 주제들은 자연스럽게 많은 크루들의 토론으로 이어졌다. 또한, 공부한 것을 정리하여 서로에게 공유하기도 하고 To-Read list를 만들어 책 읽기를 권장하는 활동도 하였다. 무엇보다도 가장 좋은 점은 미션을 수행하다가 막히는 부분을 눈에 보이는 크루 아무나 붙잡아
각자가 우테코의 주인공이라 생각해요!! 개인마다 다른 단계별 목표를 수행 해나가면 수퍼히어로가 되는...!!

2021-03-25 05:17 UTC, thisisyoungbin commented on level1.md
> +우테코의 미션은 매번 페어 프로그래밍으로 시작한다. 3인페어를 한 적도 있어 지금까지 5명의 짝을 만났다. 4번의 페어 프로그래밍을 통해서 면접장에서 했던 자기 소개는 정확히 4번째로 거짓말임이 증명됐다. 사람을 만나 대화하는 것을 좋아하고 낯선 사람한테도 말을 잘 붙이는 성격탓에 '나는 다르겠지'라는 생각을 했던 것 같다. 매번 페어 프로그래밍 끝에는
`저도 4번째로 거짓말임이 증명됐다`는 문장이 잘 이해가 안 갔어요..! 네 번째 페어 프로그래밍을 하며 깨달으신 건지, 네 번의 페어프로그래밍을 하며 깨달으신 건지...! 

뒤에 적힌 문장을 봤을 때 소통능력에서 만족을 못하신 것 같은데, 표현을 구체적으로 해주시면 의도가 더 명확하게 드러날 것 같습니다 !!

2021-03-25 05:17 UTC, thisisyoungbin commented on level1.md
> +짝에게 설명을 하려다가 제대로 못한 적이 종종 있었고 내가 알고있다고 착각하는 것들이 많다는 것을 알게되었다. 덕분에 안다고 착각하던 중요한 개념들을 제대로 정리하는 계기가 되었다.
`짝에게 어떤 개념에 대해 설명하려다가 제대로 못한 적이 종종 있었다. 그리고 설명을 하며 내가 잘 알고 있다고 착각하는 것들이 많다는 것을 깨달았다` 문장의 호흡이 긴 것 같아 나눠봤어요~ 그리고 사동형 표현을 피해 `깨달았다`는 어떨까 제안드려봐요!! ㅎㅎ

2021-03-25 05:17 UTC, thisisyoungbin commented on level1.md
> +무엇보다도 가장 큰 수확은 '모르는 것을 모르겠다고 말할 용기'를 얻게 된 것이다. 이유는 모르겠지만 모르겠다라고 말하면 큰일이라도 날 것 같은 강박관념을 가졌었다. '아는 체' 하는 것이 가장 손해라고 포비도 코치들도 누누히 말했었지만 생각과는 다르게 실천으로 옮기지는 못했다. 짝 프로그래밍을 하면서 페어의 생각을 쫓아가지 못하면서도 아는 체 했던 적이
소주제가 있어서 의미전달은 충분히 되고 있는데요..! 문단 구분이 돼 있어서 `지금까지의 과정에서 가장 큰 수확은 ~ `으로 시작하는건 어떻게 생각하시나요?!

`'아는 체' 하는 것이 가장 손해라고 **포비와 코치들이** 누누히 말했지만~` 이 부분도 생동감을 위해 제안드려봐요! 

`대충 넘어갔던 부분이~ 이른적도 있다.` 앞 문장과의 시제를 맞추기 위해서 해당 부분도 과거형 시제를 맞춰서 써보는 것은 어떨까요?!

2021-03-25 05:17 UTC, thisisyoungbin commented on level1.md
> +어떤 개발자가 되고 싶냐는 질문을 받은 적이 있다. 어떤 개발자가 되고 싶은지에 대해 고민해본적이 한번도 없어서 두리뭉실한 대답을 했었다. 이 질문에 대해 고민해본 결과 팀원들에게 '함께 일하고 싶은 개발자'로 기억되는 것이 나에게 가장 큰 행복이라고 생각했다.함께 일하고 싶은 개발자는 '하드 스킬'뿐만 아니라 '소프트 스킬'도 겸비한 개발자라고 생각한다
`어떤 개발자가 되고 싶은지에 대해 고민해본 적이 한 번도 ~` 띄어쓰기 확인해주세용!
`이 질문에 대해 고민해본 결과 ~` 해당 문장은 질문에 대해 고민하고(과거) 생각을 정리(지금)한 부분이니
`~ 기억되는 것이 나에게 가장 큰 행복이라고 생각한다.` 혹은 `팀원들에게 '함께 일하고 싶은 개발자'가 되기로 결심했다.`
이렇게 현재 어떤 결정을 했는지 나타내주면 좋을 것 같아요~!

2021-03-25 09:47 UTC, zereight commented on level1.md
> +누가 시키지 않았음에도 자연스럽게 스터디를 모집하는 것이 시작이었다. 코치들이 툭툭 던지는 주제들은 자연스럽게 많은 크루들의 토론으로 이어졌다. 또한, 공부한 것을 정리하여 서로에게 공유하기도 하고 To-Read list를 만들어 책 읽기를 권장하는 활동도 하였다. 무엇보다도 가장 좋은 점은 미션을 수행하다가 막히는 부분을 눈에 보이는 크루 아무나 붙잡아
공감쓰~~

2021-03-25 09:50 UTC, zereight commented on level1.md
> +어떤 개발자가 되고 싶냐는 질문을 받은 적이 있다. 어떤 개발자가 되고 싶은지에 대해 고민해본적이 한번도 없어서 두리뭉실한 대답을 했었다. 이 질문에 대해 고민해본 결과 팀원들에게 '함께 일하고 싶은 개발자'로 기억되는 것이 나에게 가장 큰 행복이라고 생각했다.함께 일하고 싶은 개발자는 '하드 스킬'뿐만 아니라 '소프트 스킬'도 겸비한 개발자라고 생각한다
`두리뭉실`이 아니고 `두루뭉술`로 알고 있는데 맞나용?

2021-03-25 09:51 UTC, zereight commented on level1.md
> +무엇보다도 가장 큰 수확은 '모르는 것을 모르겠다고 말할 용기'를 얻게 된 것이다. 이유는 모르겠지만 모르겠다라고 말하면 큰일이라도 날 것 같은 강박관념을 가졌었다. '아는 체' 하는 것이 가장 손해라고 포비도 코치들도 누누히 말했었지만 생각과는 다르게 실천으로 옮기지는 못했다. 짝 프로그래밍을 하면서 페어의 생각을 쫓아가지 못하면서도 아는 체 했던 적이
`짝 프로그래밍`과 `페어 프로그래밍`을 혼용하고 있는 것 같은데, 하나로 통일하면 더 좋을것 같아용!

2021-03-25 09:55 UTC, zereight commented
록희~~!!
다른 크루분들이 리뷰를 잘 달아주셔서 리뷰달것이 많이 없었어요!!
제가 피드백 드린거 수정해주시면 바로 Approve할게요!
또 읽고 어색한점있다면 계속 코멘트 달겠습니당 ~~

2021-03-25 09:55 UTC, zereight commented on level1.md
> +우테코의 미션은 매번 페어 프로그래밍으로 시작한다. 3인페어를 한 적도 있어 지금까지 5명의 짝을 만났다. 4번의 페어 프로그래밍을 통해서 면접장에서 했던 자기 소개는 정확히 4번째로 거짓말임이 증명됐다. 사람을 만나 대화하는 것을 좋아하고 낯선 사람한테도 말을 잘 붙이는 성격탓에 '나는 다르겠지'라는 생각을 했던 것 같다. 매번 페어 프로그래밍 끝에는
👀

2021-03-25 13:31 UTC, sjpark-dev reviewed
안녕하세요, 로키. 😊
멋진 글 잘 읽었습니다. 👍
다른 리뷰어분들이 제가 드리고 싶은 피드백을 남겨주셔서 제안할 수 있는 부분이 없었네요 😅

2021-03-25 13:31 UTC, sjpark-dev commented on level1.md
> +두 번의 쓴맛을 본 나는 우아한테크코스가 더더욱 환상과도 같았다. 환상은 현실에서 존재하지 않는 것이기에 우테코에 합류한 순간부터는 더는 우테코가 환상처럼 보이지 않을 것으로 생각했다.
포기하지 않고 끊임없이 노력해서 원하는 결과를 얻은 모습이 너무 멋지네요. 👍👍👍

2021-03-25 13:31 UTC, sjpark-dev commented on level1.md
> +무엇보다도 가장 큰 수확은 '모르는 것을 모르겠다고 말할 용기'를 얻게 된 것이다. 이유는 모르겠지만 모르겠다라고 말하면 큰일이라도 날 것 같은 강박관념을 가졌었다. '아는 체' 하는 것이 가장 손해라고 포비도 코치들도 누누히 말했었지만 생각과는 다르게 실천으로 옮기지는 못했다. 짝 프로그래밍을 하면서 페어의 생각을 쫓아가지 못하면서도 아는 체 했던 적이
`짝 프로그래밍을 하면서 페어의 생각을 쫓아가지 못하면서도 아는 체 했던 적이 있었다. 대충 넘어갔던 부분이 나중에는 더 복잡해져 도저히 코드를 이해할 수 없는 상황까지 이르렀다. 뒤늦게나마 페어에게 모르고 지나갔던 부분을 질문하며 생각의 차이를 좁힐 수 있었다.`

너무 공감되네요 😆
제 얘기인줄 알았네요 😅

2021-03-25 14:51 UTC, 365kim commented on level1.md
> +우아한테크코스 크루로써 활동한 지 벌써 한 달이 지났다. 세 번의 지원 끝에 3기 백엔드 크루로 합류하여 우아한 개발자가 되기 위한 노력을 하고 있다. 우테코와 나의 인연은 꽤 오래됐다. 우아한테크코스가 첫 기수를 모집할 때, 우테코에 지원하면서 본격적으로 개발자의 길을 걷기 시작했다.
언제부터 인연이 시작된 것인지 (우아한테크코스가 첫 기수를 모집할 때가 정확히 언제인지) 조금 더 명확히 전달하기 위해서 `2년 전 우아한테크코스가 첫 기수를 모집할 때,`, `2019년 전 우아한테크코스가 첫 기수를 모집할 때,` 와 같이 숫자 표현을 넣어주는 건 어떨까요~~~? 그러면 우테코 과정이 10개월 과정인지 모르는 사람에게도 로키와 우테코의 인연👩‍❤️‍👨이 얼마나 오래되었는지 더 쉽게 와닿을 것 같아서요~~~

2021-03-25 14:53 UTC, 365kim commented on level1.md
> +누가 시키지 않았음에도 자연스럽게 스터디를 모집하는 것이 시작이었다. 코치들이 툭툭 던지는 주제들은 자연스럽게 많은 크루들의 토론으로 이어졌다. 또한, 공부한 것을 정리하여 서로에게 공유하기도 하고 To-Read list를 만들어 책 읽기를 권장하는 활동도 하였다. 무엇보다도 가장 좋은 점은 미션을 수행하다가 막히는 부분을 눈에 보이는 크루 아무나 붙잡아
`아무나 붙잡고 물어봐도` 의미있는 토론이 가능한 환경! 환상의 나라 맞습니다 ㅎㅎㅎㅎ 🦄🦄🦄

2021-03-25 15:12 UTC, 365kim commented on level1.md
> +우테코의 미션은 매번 페어 프로그래밍으로 시작한다. 3인페어를 한 적도 있어 지금까지 5명의 짝을 만났다. 4번의 페어 프로그래밍을 통해서 면접장에서 했던 자기 소개는 정확히 4번째로 거짓말임이 증명됐다. 사람을 만나 대화하는 것을 좋아하고 낯선 사람한테도 말을 잘 붙이는 성격탓에 '나는 다르겠지'라는 생각을 했던 것 같다. 매번 페어 프로그래밍 끝에는
면접장에서 자신을 소개하는 말로 사용했던 표현이 사실은 거짓이었다고 표현하시는 부분이 가장 인상적이었어요! 뒤에 이어지는 내용도 진솔하게 느껴져서 좋았어요! 👍👍👍

2021-03-25 15:12 UTC, 365kim commented on level1.md
> +우테코의 미션은 매번 페어 프로그래밍으로 시작한다. 3인페어를 한 적도 있어 지금까지 5명의 짝을 만났다. 4번의 페어 프로그래밍을 통해서 면접장에서 했던 자기 소개는 정확히 4번째로 거짓말임이 증명됐다. 사람을 만나 대화하는 것을 좋아하고 낯선 사람한테도 말을 잘 붙이는 성격탓에 '나는 다르겠지'라는 생각을 했던 것 같다. 매번 페어 프로그래밍 끝에는
글의 전개상 `꾸준한 자기개발`과 `소통능력`이 뛰어난 편이 아니었다는 내용이 나올 것으로 기대했는데, 자기개발 보다는 소통능력에 포커스되어서 전개된 것 같아요. 그래서 중간에 `면접장에서 소개한 나의 소통능력은` 이렇게 한정 지어주는 것도 좋을 것 같아요~~~

2021-03-25 15:15 UTC, 365kim commented on level1.md
> +무엇보다도 가장 큰 수확은 '모르는 것을 모르겠다고 말할 용기'를 얻게 된 것이다. 이유는 모르겠지만 모르겠다라고 말하면 큰일이라도 날 것 같은 강박관념을 가졌었다. '아는 체' 하는 것이 가장 손해라고 포비도 코치들도 누누히 말했었지만 생각과는 다르게 실천으로 옮기지는 못했다. 짝 프로그래밍을 하면서 페어의 생각을 쫓아가지 못하면서도 아는 체 했던 적이
`무엇보다도 가장 큰 수확은 '모르는 것을 모르겠다고 말할 용기'를 얻게 된 것이다.` 이 문장도 너무 좋았어요! 👏👏👏

2021-03-25 15:22 UTC, 365kim commented on level1.md
> +무엇보다도 가장 큰 수확은 '모르는 것을 모르겠다고 말할 용기'를 얻게 된 것이다. 이유는 모르겠지만 모르겠다라고 말하면 큰일이라도 날 것 같은 강박관념을 가졌었다. '아는 체' 하는 것이 가장 손해라고 포비도 코치들도 누누히 말했었지만 생각과는 다르게 실천으로 옮기지는 못했다. 짝 프로그래밍을 하면서 페어의 생각을 쫓아가지 못하면서도 아는 체 했던 적이
`누누히`는 [누누이](https://www.korean.go.kr/front/search/searchAllList.do)로 써주시는게 맞는 것 같아요! 참고로 `~~하게`로 바꾸어 말할 수 없다면 `~~이`로 쓰는 것이 맞다고 하네용!
```
깨끗하게 (O) -> 깨끗히(O)
곰곰하게(X) -> 곰곰이
```

2021-03-25 15:24 UTC, 365kim commented on level1.md
> +어떤 개발자가 되고 싶냐는 질문을 받은 적이 있다. 어떤 개발자가 되고 싶은지에 대해 고민해본적이 한번도 없어서 두리뭉실한 대답을 했었다. 이 질문에 대해 고민해본 결과 팀원들에게 '함께 일하고 싶은 개발자'로 기억되는 것이 나에게 가장 큰 행복이라고 생각했다.함께 일하고 싶은 개발자는 '하드 스킬'뿐만 아니라 '소프트 스킬'도 겸비한 개발자라고 생각한다
`고민해본적이`은 `고민해본 적이`로 띄어쓰는 것이 맞는 것 같아요! [(참고한 링크)](https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=201615)

2021-03-25 15:26 UTC, 365kim commented on level1.md
> +어떤 개발자가 되고 싶냐는 질문을 받은 적이 있다. 어떤 개발자가 되고 싶은지에 대해 고민해본적이 한번도 없어서 두리뭉실한 대답을 했었다. 이 질문에 대해 고민해본 결과 팀원들에게 '함께 일하고 싶은 개발자'로 기억되는 것이 나에게 가장 큰 행복이라고 생각했다.함께 일하고 싶은 개발자는 '하드 스킬'뿐만 아니라 '소프트 스킬'도 겸비한 개발자라고 생각한다
`.함께 일하고 싶은` 앞에 공백이 추가되어야 할 것 같아용,,,!

2021-03-25 15:29 UTC, 365kim commented on level1.md
> +어떤 개발자가 되고 싶냐는 질문을 받은 적이 있다. 어떤 개발자가 되고 싶은지에 대해 고민해본적이 한번도 없어서 두리뭉실한 대답을 했었다. 이 질문에 대해 고민해본 결과 팀원들에게 '함께 일하고 싶은 개발자'로 기억되는 것이 나에게 가장 큰 행복이라고 생각했다.함께 일하고 싶은 개발자는 '하드 스킬'뿐만 아니라 '소프트 스킬'도 겸비한 개발자라고 생각한다
저도 궁금해서 찾아봤는데, 두리뭉실 두루뭉술 모두 표준어라고 하네요! ㅎㅎ 덕분에 배워갑니다~~~ [국립국어원 답변](https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=92861) 
```
두리뭉실 (O)
두루뭉술 (O)
두루뭉수리 (O)
두루뭉실 (X)
두리뭉술 (X)
```

2021-03-25 15:40 UTC, 365kim requested changes
로키 안녕하세요~~~ 로키와 우테코의 깊은 인연과, 로키의 한달 간의 소회가 어떠했는지 알 수 있어서 참 좋은 글이었습니다! 🙏 마이너한 사항들이지만 내용이나 맞춤법 관련해서 피드백 드렸어요! 확인해주시면 바로 Approve하겠습니당 🚀🚀🚀

2021-03-25 18:14 UTC, Rok93 commented on level1.md
> +누가 시키지 않았음에도 자연스럽게 스터디를 모집하는 것이 시작이었다. 코치들이 툭툭 던지는 주제들은 자연스럽게 많은 크루들의 토론으로 이어졌다. 또한, 공부한 것을 정리하여 서로에게 공유하기도 하고 To-Read list를 만들어 책 읽기를 권장하는 활동도 하였다. 무엇보다도 가장 좋은 점은 미션을 수행하다가 막히는 부분을 눈에 보이는 크루 아무나 붙잡아
연극으로 비유를 하자면 저는 주인공뿐만 아니라 조연도 빛이나는 존재라고 생각해요! 조연이 없으면 주인공이 빛나지 않기 때문이죠 : ) 
이 말은 '조연' 이라는 표현이 저를 낮잡아 표현한게 아니라는 말을 하고싶었던 거였어요!! 

사실 위에서 했던 저의 생각은 둘째치고 약간 농담을 곁들인 표현인데 혹시 표현이 별로였을까요!?

2021-03-25 18:19 UTC, Rok93 commented on level1.md
> +> "저의 꾸준한 자기개발과 소통능력으로 회사의 서비스에 기여하겠습니다".
습관적으로 따옴표 밖에다가 '.' 을 찍게 되네요 : ) 매의눈으로 봐주셨군요 고마워요 배럴 ~~!

2021-03-25 18:20 UTC, Rok93 commented on level1.md
> +누가 시키지 않았음에도 자연스럽게 스터디를 모집하는 것이 시작이었다. 코치들이 툭툭 던지는 주제들은 자연스럽게 많은 크루들의 토론으로 이어졌다. 또한, 공부한 것을 정리하여 서로에게 공유하기도 하고 To-Read list를 만들어 책 읽기를 권장하는 활동도 하였다. 무엇보다도 가장 좋은 점은 미션을 수행하다가 막히는 부분을 눈에 보이는 크루 아무나 붙잡아
ㅋㅋㅋㅋㅋㅋㅋ 안녕하세요~!? 닉네임이 어떻게 되세요? 아 전 oo 입니다. 그런데 그거 혹시 짜셨어요....? 
아직도 지나가던 크루에게 들었던 첫인사가 잊혀지지 않네요

2021-03-26 02:43 UTC, Rok93 commented on level1.md
> +어떤 개발자가 되고 싶냐는 질문을 받은 적이 있다. 어떤 개발자가 되고 싶은지에 대해 고민해본적이 한번도 없어서 두리뭉실한 대답을 했었다. 이 질문에 대해 고민해본 결과 팀원들에게 '함께 일하고 싶은 개발자'로 기억되는 것이 나에게 가장 큰 행복이라고 생각했다.함께 일하고 싶은 개발자는 '하드 스킬'뿐만 아니라 '소프트 스킬'도 겸비한 개발자라고 생각한다
아이쿠 분명 전체적으로 맞춤법 검사기 돌렸다고 생각했는데, 수정하는 과정에서 누락된 부분이 있었네요 ㅠㅠ

2021-03-26 05:04 UTC, PapimonLikelion reviewed
안녕하세요 로키! 조엘이라고 해요 :)
좋은 글 잘 읽었습니다! 우테코에 오기까지 과정이 참으로 험난하셨군요!
포기하지 않고, 계속 도전하는 모습 멋졌습니다 👍👍👍

다른 분들이 문장에 대해서 말씀을 많이 해주셔서 저는 조금 글의 전개(?)적인 측면에서 피드백 몇개 드려봤어요! 

로키의 색을 살리면서 피드백 필요하시면 반영해주세요~

2021-03-26 05:04 UTC, joelonsw commented on level1.md
> +우아한테크코스 크루로써 활동한 지 벌써 한 달이 지났다. 세 번의 지원 끝에 3기 백엔드 크루로 합류하여 우아한 개발자가 되기 위한 노력을 하고 있다. 우테코와 나의 인연은 꽤 오래됐다. 우아한테크코스가 첫 기수를 모집할 때, 우테코에 지원하면서 본격적으로 개발자의 길을 걷기 시작했다.
```suggestion
우아한테크코스 크루로써 활동한 지 한 달이 지났다. 하지만, 사실 우테코와 나의 인연은 꽤 오래됐다. 
우테코에서 우아한 개발자가 되기 위한 노력을 하기까지 3년의 시간이 걸렸다. 
세번의 지원 끝에 드디어 3기 백엔드 크루로 합류할 수 있었다. 

우아한테크코스가 첫 기수를 모집할 때 지원하면서, 나는 본격적으로 개발자의 길을 걷기 시작했다. 
```
첫 문장을 이런식으로 풀어써주고 뒤의 내용을 이어가보는 것은 어떨까요??

2021-03-26 05:04 UTC, joelonsw commented on level1.md
> +두 번의 쓴맛을 본 나는 우아한테크코스가 더더욱 환상과도 같았다. 환상은 현실에서 존재하지 않는 것이기에 우테코에 합류한 순간부터는 더는 우테코가 환상처럼 보이지 않을 것으로 생각했다.
우테코...! 로키 덕분에 저도 더욱 감사한 마음을 갖게되네요!

2021-03-26 05:04 UTC, joelonsw commented on level1.md
> +우테코의 교육과정은 기술적인 부분만큼 소프트 스킬도 중요시하는 우테코의 취지가 잘 녹아있다. 하지만 기대가 큰 탓이었는지 온라인으로 두 번의 미션을 진행할 때까지는 페어 프로그래밍을 제외하고는 우테코에 별다른 특별한 점을 못 느꼈다. 단순하게 우테코에 너무 큰 환상을 가지고 있었기에 아쉽게 느껴지는 것으로 생각했다.
```suggestion
우테코의 교육과정은 기술적인 부분만큼 소프트 스킬도 중요시하는 우테코의 취지가 잘 녹아있다. 하지만 기대가 큰 탓이었을까? 온라인으로 진행한 두 번의 미션은 나에게 특별한 감정을 못 주었다. 페어 프로그래밍을 한다는 것 외에는 특별한 교육인지도 잘 모르겠었다. 아마 우테코에 너무 큰 환상을 가지고 있었기에 그랬던 것 같다.
```
꼭 이렇게 바꿔달라는 것은 아니고 그냥 추천입니다!
문장을 조금 바꿔봤어요 :)

2021-03-26 05:04 UTC, PapimonLikelion commented on level1.md
> +무엇보다도 가장 큰 수확은 '모르는 것을 모르겠다고 말할 용기'를 얻게 된 것이다. 이유는 모르겠지만 모르겠다라고 말하면 큰일이라도 날 것 같은 강박관념을 가졌었다. '아는 체' 하는 것이 가장 손해라고 포비도 코치들도 누누히 말했었지만 생각과는 다르게 실천으로 옮기지는 못했다. 짝 프로그래밍을 하면서 페어의 생각을 쫓아가지 못하면서도 아는 체 했던 적이
엉엉 나도 그랬었는데!ㅋㅋㅋㅋㅋㅋㅋㅋ
용기내서 우테코 생활 해봐요 :) 🎁

2021-03-26 05:05 UTC, PapimonLikelion commented on level1.md
> +우아한테크코스 크루로써 활동한 지 벌써 한 달이 지났다. 세 번의 지원 끝에 3기 백엔드 크루로 합류하여 우아한 개발자가 되기 위한 노력을 하고 있다. 우테코와 나의 인연은 꽤 오래됐다. 우아한테크코스가 첫 기수를 모집할 때, 우테코에 지원하면서 본격적으로 개발자의 길을 걷기 시작했다.
+ 우테코, 우아한테크코스 용어를 혼용하지 마시고 하나로 통일하는 것도 좋을 것 같아요!

2021-03-27 07:56 UTC, Rok93 commented on level1.md
> +우아한테크코스 크루로써 활동한 지 벌써 한 달이 지났다. 세 번의 지원 끝에 3기 백엔드 크루로 합류하여 우아한 개발자가 되기 위한 노력을 하고 있다. 우테코와 나의 인연은 꽤 오래됐다. 우아한테크코스가 첫 기수를 모집할 때, 우테코에 지원하면서 본격적으로 개발자의 길을 걷기 시작했다.
먼저 욘의 의견에 먼저 제 생각을 말하자면 욘의 제안도 괜찮지만 저는 ``~로서``의 늬앙스? 억양? 을 살리고싶어서 ``크루로서`` 라는 표현은 가지고 갈려고합니다! 

배럴이 이 부분 문맥구성에 대해 언급해주셔서  문맥구성이 어색하다는 것을 느꼈네요 😳 
단지 이 부분에서 문맥 구성을 변경하다보니 ``세 번째 지원 끝에 3기 백엔드 크루로 합류할 수 있었고, 우아한 개발자가 되기 위한 노력을 하고 있다.`` 이 문장의 위치가 어딜넣어도 조금 어색하다는 느낌이 드네요. 🤔 

이 문장을 지워볼까? 라는 생각도 하고 있는데 피드백 반영해서 수정해볼게요 : )

2021-03-27 08:40 UTC, Rok93 commented on level1.md
> +두 번째로 지원했던 우테코에 떨어지면서 시작했던 '우형없는 우테코' 스터디는 함께 공부하는 것에 대한 즐거움을 알게 해주었다. 스터디에서 우테코 프리코스 과정을 따라 하다가 1기 크루로부터 받았던 코드리뷰는 앞으로 어떤 공부를 해야 할지에 대한 방향을 제시해주었다.
스터디 방식이 처음에는 우테코 과정을 따라했는데 나중에는 주제 하나씩 정해서 같이 공부했다가 프로젝트도 했다가 중구난방이라 ㅋㅋㅋ ㅠㅠ 이걸 녹이기가 쉽지가 않네요. 가장 인상적인 스터디 내용을 한줄정도 추가해보는 걸로 수정해볼게요 😆

의견 감사해요 !!

2021-03-27 10:42 UTC, Rok93 commented on level1.md
> +두 번의 쓴맛을 본 나는 우아한테크코스가 더더욱 환상과도 같았다. 환상은 현실에서 존재하지 않는 것이기에 우테코에 합류한 순간부터는 더는 우테코가 환상처럼 보이지 않을 것으로 생각했다.
여기서 의도했던거는 제가 연속해서 우테코에 연달아 떨어져서 우테코를 갖지 못하는 환상이라고!?  표현을 하려고했어요! 그런데 이제 우테코에 합격했으니 (= 가졌으니..) 환상이 아닌 현실이라 우테코를 '환상'이 아닌 '현실'로 바라보게 될 것이다...? 이렇게 표현하고 보니 제가 무슨말 하는건지 잘 모르겠네요 😅 
전달하려는 의도 자체부터 정리가 안되고 있네요🤣!!  좋은 피드백 감사해요 👍

2021-03-27 10:46 UTC, Rok93 commented on level1.md
> +무엇보다도 가장 큰 수확은 '모르는 것을 모르겠다고 말할 용기'를 얻게 된 것이다. 이유는 모르겠지만 모르겠다라고 말하면 큰일이라도 날 것 같은 강박관념을 가졌었다. '아는 체' 하는 것이 가장 손해라고 포비도 코치들도 누누히 말했었지만 생각과는 다르게 실천으로 옮기지는 못했다. 짝 프로그래밍을 하면서 페어의 생각을 쫓아가지 못하면서도 아는 체 했던 적이
이 부분 배럴과 하루 피드백 둘다 반영했습니다 !!  
정말 한글은 자바 만큼이나 어려운 언어네요 😭

2021-03-27 11:13 UTC, Rok93 commented on level1.md
> +두 번째로 지원했던 우테코에 떨어지면서 시작했던 '우형없는 우테코' 스터디는 함께 공부하는 것에 대한 즐거움을 알게 해주었다. 스터디에서 우테코 프리코스 과정을 따라 하다가 1기 크루로부터 받았던 코드리뷰는 앞으로 어떤 공부를 해야 할지에 대한 방향을 제시해주었다.
주제가 중구난방 식으로 계속 바꼈던 터라 가장 인상적인 스터디 주제 or 방식을 간략히 언급해야겠어요!! 피드백 감사합니다  😁

2021-03-27 13:31 UTC, Rok93 commented on level1.md
> +두 번의 쓴맛을 본 나는 우아한테크코스가 더더욱 환상과도 같았다. 환상은 현실에서 존재하지 않는 것이기에 우테코에 합류한 순간부터는 더는 우테코가 환상처럼 보이지 않을 것으로 생각했다.
음 배럴의 말에 약간 뼈맞은 느낌이네요. 이 부분은 어떻게 수정을 해야할지 많이 고민되네요 😭 

이 부분은 문맥 구성을 바꾸고 내용을 약간 변경해서 ``환상은 현실에서 존재하지 않는 것이기에 우테코에 합류한 순간부터는 더는 우테코가 환상처럼 보이지 않을 것으로 생각했다. `` 이 말이 잘 연결되도록(= 제가 생각하기에는...?) 해봤는데, 이렇게 변경한건 어떨까요? 

변경한 내용은 아래와 같습니다. 이전 피드백에서 문맥구성을 변경해보라는 조언까지 섞어서(?) 반영했어요! 

```
두 번의 쓴맛을 본 나는 우테코가 더더욱 환상과도 같았다. 하지만 세 번의 지원 끝에 우테코는 나에게 현실이 되었다. 
환상은 현실에서 존재하지 않는 것이기에 우테코에 합류한 순간부터는 더는 우테코가 환상처럼 보이지 않을 것으로 생각했다. 
```

2021-03-27 13:48 UTC, Rok93 commented on level1.md
> +다행히 세 번째 미션부터는 일주일에 두 번은 루터회관에 갈 수 있게 되었고 처음으로 크루들과 코치들을 만났다. 수업방식은 동일했지만 크루들이 수업을 들으면서 느끼는 감정들을 현장에서 고스란히 느낄 수 있었고 크루들 코치들과 서로 교감한다고 느꼈다. 페어와의 짝 프로그래밍, 포비와 코치들의 가르침, 리뷰어의 피드백 등 성장을 할 수 밖에없는 좋은 환경이라고
```suggestion
다행히 세 번째 미션부터는 일주일에 두 번은 루터회관에 갈 수 있게 되었고 처음으로 크루들과 코치들을 만났다. 수업방식은 동일했지만 크루들이 수업을 들으면서 느끼는 감정들을 현장에서 느낄 수 있었다. 그리고 포비와 코치들이 수시로 크루들과 대화를 나누면서 서로 교감하였다. 페어와의 짝 프로그래밍, 포비와 코치들의 가르침, 리뷰어의 피드백 등 성장을 할 수 밖에없는 좋은 환경이라고 느꼈다. 
```

저는 이렇게 변경해보았어요!!

2021-03-27 14:08 UTC, Rok93 commented on level1.md
> +짝에게 설명을 하려다가 제대로 못한 적이 종종 있었고 내가 알고있다고 착각하는 것들이 많다는 것을 알게되었다. 덕분에 안다고 착각하던 중요한 개념들을 제대로 정리하는 계기가 되었다.
제 의도는 '이미 공부한 내용인데, 정확히 공부하지 않았다는 것을 알게 되었다' 의 의미여서 배럴이 제안해주신 형태와는 조금 의미가 다른 것 같아요 !!  

중복을 피하고 싶기는 한데...  꽤 오랫동안 고민해봤는데 ``내가 알고있다고 착각하는 것들이 많다는 것을 알게되었다`` 이 부분에  ``알고있다`` 의 중복을 피할 방법이 도저히 안 떠오르네요 😅😭   

일단은 이 부분은 넘어가는 걸로 하겠습니다. 더 좋은 표현이 없을지는 계속 고민해보겠습니다 💪

2021-03-27 14:21 UTC, Rok93 commented on level1.md
> +두 번째로 지원했던 우테코에 떨어지면서 시작했던 '우형없는 우테코' 스터디는 함께 공부하는 것에 대한 즐거움을 알게 해주었다. 스터디에서 우테코 프리코스 과정을 따라 하다가 1기 크루로부터 받았던 코드리뷰는 앞으로 어떤 공부를 해야 할지에 대한 방향을 제시해주었다.
이 부분은 배럴과 비슷한 의견을 주셔서!! 프리코스 과정을 따라했던 내용을 조금 더 추가했어요!

2021-03-27 14:23 UTC, Rok93 commented on level1.md
> +우테코의 미션은 매번 페어 프로그래밍으로 시작한다. 3인페어를 한 적도 있어 지금까지 5명의 짝을 만났다. 4번의 페어 프로그래밍을 통해서 면접장에서 했던 자기 소개는 정확히 4번째로 거짓말임이 증명됐다. 사람을 만나 대화하는 것을 좋아하고 낯선 사람한테도 말을 잘 붙이는 성격탓에 '나는 다르겠지'라는 생각을 했던 것 같다. 매번 페어 프로그래밍 끝에는
제 의도는 후자의 의미인데, 이 부분을 조금 더 명확하게 해야겠군요 다들 여기서 ... 😭

2021-03-27 14:26 UTC, Rok93 commented on level1.md
> +어떤 개발자가 되고 싶냐는 질문을 받은 적이 있다. 어떤 개발자가 되고 싶은지에 대해 고민해본적이 한번도 없어서 두리뭉실한 대답을 했었다. 이 질문에 대해 고민해본 결과 팀원들에게 '함께 일하고 싶은 개발자'로 기억되는 것이 나에게 가장 큰 행복이라고 생각했다.함께 일하고 싶은 개발자는 '하드 스킬'뿐만 아니라 '소프트 스킬'도 겸비한 개발자라고 생각한다
ㅎㅎ.... 국어 너무 어렵네요 
![image](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbgePKbJlcgPQcn70TVX66mzSq66UdURTCBIvvob6eY_GtMbe31wrHO7Qle5-SyuBitrE&usqp=CAU)

2021-03-27 14:30 UTC, Rok93 commented on level1.md
> +우테코의 미션은 매번 페어 프로그래밍으로 시작한다. 3인페어를 한 적도 있어 지금까지 5명의 짝을 만났다. 4번의 페어 프로그래밍을 통해서 면접장에서 했던 자기 소개는 정확히 4번째로 거짓말임이 증명됐다. 사람을 만나 대화하는 것을 좋아하고 낯선 사람한테도 말을 잘 붙이는 성격탓에 '나는 다르겠지'라는 생각을 했던 것 같다. 매번 페어 프로그래밍 끝에는
저는 배럴의 피드백에서 앞의 문자을 제거해서 아래와 같이 변경했어요!! 

```suggestion
우테코의 미션은 매번 페어 프로그래밍으로 시작한다. 3인페어를 한 적도 있어 지금까지 5명의 짝을 만났다. 면접장에서 했던 자기 소개는 정확히 4번째 페어 프로그래밍만에 거짓말임이 증명됐다. 사람을 만나 대화하는 것을 좋아하고 낯선 사람한테도 말을 잘 붙이는 성격탓에 '나는 다르겠지'라는 생각을 했던 것 같다. 매번 페어 프로그래밍 끝에는 아쉬움이 남았다. 이번에는 이렇게 다음에는 저렇게 하며 나만의 의견 조율 방법을 찾기위한 시행착오를 거치고있다. 
```

2021-03-27 14:38 UTC, Rok93 commented on level1.md
> +우테코의 교육과정은 기술적인 부분만큼 소프트 스킬도 중요시하는 우테코의 취지가 잘 녹아있다. 하지만 기대가 큰 탓이었는지 온라인으로 두 번의 미션을 진행할 때까지는 페어 프로그래밍을 제외하고는 우테코에 별다른 특별한 점을 못 느꼈다. 단순하게 우테코에 너무 큰 환상을 가지고 있었기에 아쉽게 느껴지는 것으로 생각했다.
저는 페어 프로그래밍이 하드스킬, 소프트 스킬 모두 학습하는데 큰 도움이 된다고 생각했어요!!

2021-03-27 14:40 UTC, Rok93 commented on level1.md
> +우테코의 미션은 매번 페어 프로그래밍으로 시작한다. 3인페어를 한 적도 있어 지금까지 5명의 짝을 만났다. 4번의 페어 프로그래밍을 통해서 면접장에서 했던 자기 소개는 정확히 4번째로 거짓말임이 증명됐다. 사람을 만나 대화하는 것을 좋아하고 낯선 사람한테도 말을 잘 붙이는 성격탓에 '나는 다르겠지'라는 생각을 했던 것 같다. 매번 페어 프로그래밍 끝에는
이 부분은 배럴의 피드백을 반영해서 

``4번의 페어 프로그래밍을 통해서 면접장에서 했던 자기 소개는 정확히 4번째로 거짓말임이 증명됐다`` 에서 

``면접장에서 했던 자기 소개는 정확히 4번째 페어 프로그래밍만에 거짓말임이 증명됐다.`` 으로 변경했어요! !

2021-03-27 14:52 UTC, Rok93 commented on level1.md
> +짝에게 설명을 하려다가 제대로 못한 적이 종종 있었고 내가 알고있다고 착각하는 것들이 많다는 것을 알게되었다. 덕분에 안다고 착각하던 중요한 개념들을 제대로 정리하는 계기가 되었다.
'알게되었다'를 ``깨달았다``로 변경하는 거 좋은것같아요!!   알고있다 의 표현이 중복되서 어떻게 바꿀까 고민하고있었는데, 욘이 답을 주셨네요 : )  

저도 문장의 호흡을 나누는건 좋은 의견인거같아요!! 단지 앞의 문장에 이어서 ``그리고 설명을 하며 내가 잘 알고 있다고 착각하는 것들이 많다는 것을 깨달았다`` 로 이어지는건 조금 부자연스럽다고 느껴져서 (이유는 잘 모르겠어요...)  뒷 문장은 조금 생각해서 다른걸로 변경해볼게요!

2021-03-27 15:31 UTC, Rok93 commented on level1.md
> +무엇보다도 가장 큰 수확은 '모르는 것을 모르겠다고 말할 용기'를 얻게 된 것이다. 이유는 모르겠지만 모르겠다라고 말하면 큰일이라도 날 것 같은 강박관념을 가졌었다. '아는 체' 하는 것이 가장 손해라고 포비도 코치들도 누누히 말했었지만 생각과는 다르게 실천으로 옮기지는 못했다. 짝 프로그래밍을 하면서 페어의 생각을 쫓아가지 못하면서도 아는 체 했던 적이
몇 단어 고쳤다고 문장에 생동감이 생겼네요 👍  
피드백 주신 세 부분은 모두 반영하였습니다!!

2021-03-27 15:56 UTC, Rok93 commented on level1.md
> +짝에게 설명을 하려다가 제대로 못한 적이 종종 있었고 내가 알고있다고 착각하는 것들이 많다는 것을 알게되었다. 덕분에 안다고 착각하던 중요한 개념들을 제대로 정리하는 계기가 되었다.
이 부분은 어떻게 작성을 해야할지 계속 고민되네요. 
``짝에게 어떤 개념을 설명하려다가 제대로 못 한 적이 종종 있었다`` 와 
``내가 알고 있다고 착각하는 것들이 많다는 것을 깨달았다``  이 두 문장을 자연스럽게 연결하고 싶은데.. 적절한 문장이 안떠오르네요 🤔


```suggestion
짝에게 어떤 개념을 설명하려다가 제대로 못 한 적이 종종 있었다. 내가 알고 있다고 착각하는 것들이 많다는 것을 깨달았다. 덕분에 안다고 착각하던 중요한 개념들을 제대로 정리하는 계기가 되었다.
```

2021-03-27 16:01 UTC, Rok93 commented on level1.md
> +무엇보다도 가장 큰 수확은 '모르는 것을 모르겠다고 말할 용기'를 얻게 된 것이다. 이유는 모르겠지만 모르겠다라고 말하면 큰일이라도 날 것 같은 강박관념을 가졌었다. '아는 체' 하는 것이 가장 손해라고 포비도 코치들도 누누히 말했었지만 생각과는 다르게 실천으로 옮기지는 못했다. 짝 프로그래밍을 하면서 페어의 생각을 쫓아가지 못하면서도 아는 체 했던 적이
너무 비슷한 단어를 반복하는 것 같아 이리저리 왔다갔다 쓴거였는데, 오히려 별로였던 것 같네요 : ) 
이 부분은 짝이라는 단어 대신 '페어'로 통일해서 사용하도록 변경했습니다~

2021-03-27 16:02 UTC, Rok93 commented on level1.md
> +우아한테크코스 크루로써 활동한 지 벌써 한 달이 지났다. 세 번의 지원 끝에 3기 백엔드 크루로 합류하여 우아한 개발자가 되기 위한 노력을 하고 있다. 우테코와 나의 인연은 꽤 오래됐다. 우아한테크코스가 첫 기수를 모집할 때, 우테코에 지원하면서 본격적으로 개발자의 길을 걷기 시작했다.
이 내용은 (+ 다음 문장)

```
우테코의 크루로서 활동한 지 벌써 한 달이 지났다. 
우테코와 나의 인연은 꽤 오래됐다. 
우테코 첫 기수를 모집하던 2019년 3월, 우테코에 지원하면서 본격적으로 개발자의 길을 걷기 시작했다. 

그해 10월에 우테코에 한 번 더 지원했지만, 결과는 같았다. 
```

이렇게 변경해봤는데!  하루는 어떻게 생각하시나요!??

2021-03-27 16:04 UTC, Rok93 commented on level1.md
> +우테코의 미션은 매번 페어 프로그래밍으로 시작한다. 3인페어를 한 적도 있어 지금까지 5명의 짝을 만났다. 4번의 페어 프로그래밍을 통해서 면접장에서 했던 자기 소개는 정확히 4번째로 거짓말임이 증명됐다. 사람을 만나 대화하는 것을 좋아하고 낯선 사람한테도 말을 잘 붙이는 성격탓에 '나는 다르겠지'라는 생각을 했던 것 같다. 매번 페어 프로그래밍 끝에는
이건 생각 못했네요 !!  앞에서  꾸준한 자기개발과 소통능력을 같이 다뤄두고는 ``꾸준한 자기개발``은 까맣게 잊고 있었네요! 
하루의 의견대로 뒤에서 소통능력으로 확실하게 한정지어서 말해주는게 더 명확할 것 같아요!!

2021-03-27 16:17 UTC, Rok93 commented on level1.md
> +우아한테크코스 크루로써 활동한 지 벌써 한 달이 지났다. 세 번의 지원 끝에 3기 백엔드 크루로 합류하여 우아한 개발자가 되기 위한 노력을 하고 있다. 우테코와 나의 인연은 꽤 오래됐다. 우아한테크코스가 첫 기수를 모집할 때, 우테코에 지원하면서 본격적으로 개발자의 길을 걷기 시작했다.
오 조엘말처럼 ``하지만, 사실`` 을 추가함으로써 문장이 더 매끄럽게 연결되는 것 같아요 !! 

이어서 제안해주신 내용도 좋지만 앞에서 배럴의 피드백을 반영하면서 내용이 조금 변경됐어요 !! 
이 구조도 괜찮다고 생각이 되서 아쉽지만 뒷부분의 내용은 지금의 내용을 그대로 쓰려고해요! 

조엘의 피드백 중 일부( ``하지만, 사실`` )도 반영하면 아래와 같이 바뀔 것 같아요! 

```
우테코의 크루로서 활동한 지 벌써 한 달이 지났다. 
하지만, 사실 우테코와 나의 인연은 꽤 오래됐다.
우테코 첫 기수를 모집하던 2019년 3월, 우테코에 지원하면서 본격적으로 개발자의 길을 걷기 시작했다.

그해 10월에 우테코에 한 번 더 지원했지만, 결과는 같았다.
```

조엘의 피드백도 좋다고 생각이 드는데 앞선 피드백을 반영하다보니 뒤에 이어지는 스터디 내용등 추가한 내용들이 처치곤란 해져서 😭 
아으... 첫문장 너무 좋은데 ㅠㅠ 못가져가는게 아쉽네요

2021-03-27 16:24 UTC, Rok93 commented on level1.md
> +우테코의 교육과정은 기술적인 부분만큼 소프트 스킬도 중요시하는 우테코의 취지가 잘 녹아있다. 하지만 기대가 큰 탓이었는지 온라인으로 두 번의 미션을 진행할 때까지는 페어 프로그래밍을 제외하고는 우테코에 별다른 특별한 점을 못 느꼈다. 단순하게 우테코에 너무 큰 환상을 가지고 있었기에 아쉽게 느껴지는 것으로 생각했다.
제가 제대로 표현못한 제 생각을  조엘이 오히려 표현을 잘해주시네요 ㅋㅋㅋㅋㅋㅋ  😂 
조엘의 추천대로 가는게 훨씬 나은 문장인 것 같네요 

``페어 프로그래밍을 한다는 것 외에는 특별한 교육인지도 잘 모르겠었다.`` 에서  '잘 모르겠었다' 의 표현이 조금 어색한 것 같아서 이 부분은 수정해서 반영했습니다. 

아래와 같이 반영하였습니다! 

```suggestion
우테코의 교육과정은 기술적인 부분만큼 소프트 스킬도 중요시하는 우테코의 취지가 잘 녹아있다. 하지만 기대가 큰 탓이었을까? 온라인으로 진행한 두 번의 미션은 나에게 특별한 감정을 못 주었다. 페어 프로그래밍을 한다는 것 외에는 특별한 교육이라고 느껴지지 않았다. 아마 우테코에 너무 큰 환상을 가져서 그랬던 것 같다.
```

2021-03-28 03:19 UTC, sjpark-dev approved these changes
안녕하세요, 로키. 😊
다시 한번 글을 읽어 봤는데 이전보다 훨씬 매끄러워졌네요. 
글이 술술 읽히네요. 👍👍👍
솔직하고 정성스러운 글을 읽을 수 있어서 너무 좋았습니다.
저는 이만 Approve 하겠습니다. ✔
피드백 반영하느라 수고하셨습니다. 👍

2021-03-28 03:25 UTC, TaewanKimmmm approved these changes
감동적인 글에 번외 approve 드립니다..

2021-03-28 03:25 UTC, TaewanKimmmm commented on level1.md
> +두 번의 쓴맛을 본 나는 우테코가 더더욱 환상과도 같았다. 하지만 세 번의 지원 끝에 우테코는 나에게 현실이 되었다.
너무 감동적인 한 마디네요..울 뻔 했습니다..😭

2021-03-28 03:42 UTC, PapimonLikelion approved these changes
안녕하세요 로키! 좋은 글 잘읽었어요~~ 😁😁
Approve 드립니다~ 레벨1 끝까지 화이팅!!

2021-03-28 04:44 UTC, thisisyoungbin commented on level1.md
> +누가 시키지 않았음에도 자연스럽게 스터디를 모집하는 것이 시작이었다. 코치들이 툭툭 던지는 주제들은 자연스럽게 많은 크루들의 토론으로 이어졌다. 또한, 공부한 것을 정리하여 서로에게 공유하기도 하고 To-Read list를 만들어 책 읽기를 권장하는 활동도 하였다. 무엇보다도 가장 좋은 점은 미션을 수행하다가 막히는 부분을 눈에 보이는 크루 아무나 붙잡아
주인공과 조연, 둘 다 의미하는 표현이라 생각하니 어떤 걸 의도했는지 알겠네요! 주인공으로서 역할도 하고, 크루들을 빛나게 해줄 수 있는..!
의미를 알고 다시 보니 아주 멋진 표현이라 생각합니다. :)
`앞으로도 환상의 나라의 주인공으로, 그리고 크루들을 빛낼 수 있는 조연의 역할로 남은 과정들을 훌륭하게 수행하는 것이 나의 목표다` 요런식으로 바꾸면 부연설명 없이 의미가 드러나지 않을까 싶어서 추가 코멘트 남겨봐요 로키!

2021-03-28 05:20 UTC, thisisyoungbin commented on level1.md
> +짝에게 설명을 하려다가 제대로 못한 적이 종종 있었고 내가 알고있다고 착각하는 것들이 많다는 것을 알게되었다. 덕분에 안다고 착각하던 중요한 개념들을 제대로 정리하는 계기가 되었다.
혹시 아직 고민중이시면 이 문단이 앞의 문단 `매번 페어프로그래밍 끝에는 아쉬움이 남았다` 뒤로 가는 건 어떤가요..? 페어프로그래밍을 하면서 느낀 아쉬움에 대한 것들이고, 그에 대한 결과라 저는 어색함이 없다고 생각들어서 의견 남겨봐요~ :)

2021-03-28 05:27 UTC, thisisyoungbin approved these changes
로키 안녕하세요 :) 
피드백 반영된 부분들까지 확인해서 다시 글을 읽어봤어요 :)
저 포함 크루들이 주신 피드백을 고민하며 반영하고, 또 아직 고민중이신 부분도 있는 것 같아
추가적인 코멘트들 남겨놓긴 했습니다! '바뀌면 좋겠다'가 아닌 같이 고민한다 생각하고 남긴 코멘트이니
반드시 반영할 필요는 없을 것 같아요! 그 외에는 추가적으로 피드백 드릴 부분이 없어 저도 이만 Approve 하겠습니다 !

2021-03-28 08:06 UTC, Rok93 commented on level1.md
> +누가 시키지 않았음에도 자연스럽게 스터디를 모집하는 것이 시작이었다. 코치들이 툭툭 던지는 주제들은 자연스럽게 많은 크루들의 토론으로 이어졌다. 또한, 공부한 것을 정리하여 서로에게 공유하기도 하고 To-Read list를 만들어 책 읽기를 권장하는 활동도 하였다. 무엇보다도 가장 좋은 점은 미션을 수행하다가 막히는 부분을 눈에 보이는 크루 아무나 붙잡아
제가 의도하는 내용은 욘의 피드백처럼 바꾸는게 더 명확하게 들어날 것 같아요!! 
제 글은 추가설명이 있어야 이해가 되는 반면, 욘이 추천해준 문장은 설명 없이도 단번에 이해가 되네요!!

2021-03-28 08:25 UTC, Rok93 commented on level1.md
> +짝에게 설명을 하려다가 제대로 못한 적이 종종 있었고 내가 알고있다고 착각하는 것들이 많다는 것을 알게되었다. 덕분에 안다고 착각하던 중요한 개념들을 제대로 정리하는 계기가 되었다.
이 부분은 ``알고 있다고 착각하는 것들이 많다는 것을 깨달았다. 페어에게 어떤 개념을 설명하려다가 제대로 못 한 적이 종종 있었다. 덕분에 안다고 착각하던 중요한 개념들을 제대로 정리하는 계기가 되었다.`` 

로  연결하려는 문장의 순서를 바꿔서 해봤는데, 이전보다 의미가 자연스럽게 잘 이어진다고 생각했어요!!

2021-03-28 10:03 UTC, knae11 commented on level1.md
> +짝에게 설명을 하려다가 제대로 못한 적이 종종 있었고 내가 알고있다고 착각하는 것들이 많다는 것을 알게되었다. 덕분에 안다고 착각하던 중요한 개념들을 제대로 정리하는 계기가 되었다.
아하 그렇군요!ㅋㅋㅋ 사실 저도 피드백을 드리면서 중복을 어떻게 피할 수 있을까 고민했는데, 피하기 어려운 것 같아요ㅠㅠㅠ 지금 내용도 충분히 좋다고 생각합니다!ㅎㅎㅎㅎ

2021-03-28 10:09 UTC, knae11 approved these changes
로키! 제가 약간 중구난방하게 피드백을 드려서 도움이 될까 싶었는데 (제 피드백 때문은 아니겠지만) 다시 읽어보니 글이 전보다 상당히 깔끔해진 것 같아요! 말하고자 하는 바가 좀 더 명확해진 느낌이랄까요??ㅎㅎㅎ 무튼 저는 로키의 글이 마음에 들기 때문에 이제 approve 합니다! 고생하셨어요!ㅎㅎㅎ👍👍👍

2021-03-28 15:34 UTC, zereight approved these changes

2021-03-28 15:35 UTC, zereight commented
로키이~~ Approve했어요 고생하셨습니닷!

2021-03-28 16:00 UTC, 365kim commented on level1.md
> +우아한테크코스 크루로써 활동한 지 벌써 한 달이 지났다. 세 번의 지원 끝에 3기 백엔드 크루로 합류하여 우아한 개발자가 되기 위한 노력을 하고 있다. 우테코와 나의 인연은 꽤 오래됐다. 우아한테크코스가 첫 기수를 모집할 때, 우테코에 지원하면서 본격적으로 개발자의 길을 걷기 시작했다.
지금은 아래와 같네용! 아주 좋은 것 같습니당 ☺️ 글에서 2019년이라고 알려주셔서 로키와 우테코의 오랜 인연을 더 잘 알 수 있게되었어요 👍
```
우테코의 크루로서 활동한 지 벌써 한 달이 지났다. 
하지만, 사실 우테코와 나의 인연은 꽤 오래됐다. 


우테코 첫 기수를 모집하던 2019년 3월, 우테코에 지원하면서 본격적으로 개발자의 길을 걷기 시작했다. 
그해 10월에 우테코에 한 번 더 지원했지만, 결과는 같았다.
```

2021-03-28 16:01 UTC, 365kim commented on level1.md
> +우테코의 미션은 매번 페어 프로그래밍으로 시작한다. 3인페어를 한 적도 있어 지금까지 5명의 짝을 만났다. 4번의 페어 프로그래밍을 통해서 면접장에서 했던 자기 소개는 정확히 4번째로 거짓말임이 증명됐다. 사람을 만나 대화하는 것을 좋아하고 낯선 사람한테도 말을 잘 붙이는 성격탓에 '나는 다르겠지'라는 생각을 했던 것 같다. 매번 페어 프로그래밍 끝에는
```
면접장에서 소개했던 나의 소통능력은 정확히 4번째 페어 프로그래밍만에 거짓말임이 증명됐다.
```
이렇게 바뀌었네요~! 다시 읽어보니까 앞 부분에 `누군가가 들으면 마치 '저 협업 잘해요'라고 들릴 수도 있다.`라는 힌트도 주셨었네요 ㅎㅎ 글의 흐름이 더 명확해져서 저는 좋습니다 :)

2021-03-28 16:03 UTC, 365kim approved these changes
아이쿠 어제밤에 수정해주셨는데 제가 이제야 확인했네요 🥲🥲 로키 늦어서 죄송해요! 피드백 잘 반영된 것으로 확인했습니다! 고생하셨어요 :) Approve할게용!

2021-05-14 06:12 UTC, woowahanCU approved these changes
4번째 페어 프로그래밍 때 상처가 많았군요 😭
함께 일하는 것이 정말 어렵죠. 
아마 아실텐데요. 
"자기보다 경험이 적은 사람에게 설득을 당할 수 있어야 하고,
자기보다 경험이 많은 사람을 설득 시킬 수 있어야 한다." 는 말이 있죠. 
그러려면 자존감이 높아야 한다고 생각해요. 엔지니어가 자존감이 높으려면 실력에 확신이 있어야 하구요. 
몇몇 지식을 모를 수는 있지만, 일을 성취해낼 자신감이 있는거죠.
앞으로 남은기간에 더 단단해지길 바래요~
환상의 나라에 오신걸 환영합니다 👋🏻

2021-05-14 06:12 UTC, merged