[레벨 1 글쓰기 미션] 엘라(김현주) 미션 제출합니다.
woowacourse/woowa-writing-3 pull request #41
Opened 2021-03-25 14:30 UTC by HyuuunjuKim

안녕하세요, 프론트엔드 엘라입니다 😊

잘 부탁 드리겠습니다. 자유롭게 피드백 주세요 ㅎ ㅎ

[우아한 테크 코스 레벨 1 글쓰기](https://github.com/HyuuunjuKim/woowa-writing-3/blob/hyuuunjukim/level-1.md)

2021-03-25 15:31 UTC, bperhaps reviewed
안녕하세요 엘라! 글 정말 잘 읽었습니다.
읽으면서 좋은 개발자가 되고싶다는 간절함이 계속 전해져서 정말 뭉클했습니다.
제가 했던 고민들과 많이 비슷해서 더욱 공감됐던 것 같아요!
엘라의 간절함이 글에서 뭍어나오는게 계속해서 여운이 남는군요.....

2021-03-25 15:31 UTC, bperhaps commented on level-1.md
> +3년 전, 코딩을 시작했다. 그냥 전공 공부 하기 싫어서 혼자 고민하던 중에 아는 선배를 따라 얼떨결에 코딩 동아리에 들어갔고, 그렇게 코딩을 하게 되었다.
```suggestion
3년 전, 전공 공부가 하기 싫어서 혼자 고민하던 중 아는 선배를 따라 얼떨결에 코딩 동아리에 들어갔고, 그렇게 코딩을 하게 되었다. 
```
코딩을 시작했다와 코딩을 하게 되었다. 문장의 앞과 뒤에서 같은 내용이 반복되면서 매끄럽지 않은 것 같아서 수정해 봤어요!

2021-03-25 15:31 UTC, bperhaps commented on level-1.md
> +그런데 생각보다 너무 재밌었다. 이 이유가 내가 지금도 코딩을 하고있는 이유다. 처음으로 내가 하는 공부와 일에 대해 열정을 느꼈고, 재미를 느꼈고, 밤을 새며 공부를 했고, 그렇게 '개발자'라는 꿈을 막연하게 꾸기 시작했다.
```suggestion
그렇게 시작한 코딩은 생각보다 너무 재밌었다. 이게 내가 지금도 코딩을 하고있는 이유다. 처음으로 내가 하는 공부와 일에 대해 열정과 재미를 느꼈고, 밤을 새며 공부하며 '개발자'라는 꿈을 막연하게 꾸기 시작했다. 
```
재미있는 이유가 너무 윗쪽 문장에 의존한다고 느껴져서 한번 다 상기시켜봤어요.
뒷쪽 문장은 ~고 가 반복돼어서 한번 줄여봤습니다!

2021-03-25 15:31 UTC, bperhaps commented on level-1.md
> +당시에는, 지금처럼 재밌게 코딩하다보면 어느샌가 내가 훌륭한 개발자가 되어있을 줄 알았다. 코딩이 나한테 있어서 재밌다는게 중요하다고 생각했고, 그렇게 그냥 즐기면서 했던 것 같다.
```suggestion
당시에는, 지금처럼 재밌게 코딩하다보면 어느샌가 내가 훌륭한 개발자가 되어있을 줄 알았다. 나한테 있어서  코딩이 재밌다는 사실이 무엇보다 중요하다고 생각했고, 그렇게 즐기면서 공부(코딩) 했던 것 같다. 
```

살짝 어색한 부분을 만져봤어요!
흠.. 뭔가 어색한 부분이 있는 것 같은데 문장의 의미가 흐트러질까봐 섣불리 손을 못대겠네요..

2021-03-25 15:31 UTC, bperhaps commented on level-1.md
> +그런데 시간이 흐를수록 그리고 취업할 시기가 다가올 수록, 나는 코딩에 대한 부담감을 갖기 시작했다. 막상 개발자로 취업하려하니 내가 참 이도저도 아닌 실력이라는 게 확연히 느껴졌다. 코딩 입문자들 중에서는 1등, 코딩 좀 해본 사람들 중에서는 꼴등. 딱 내 위치였다. 이런 생각들과 부담감을 계속 느끼다 보니 코딩이 재미없어졌다.
```suggestion
그런데 시간이 흐를수록, 그리고 취업할 시기가 다가올 수록 나는 코딩에 대한 부담감을 갖기 시작했다. 막상 개발자로 취업하려하니 내가 참 이도저도 아닌 실력이라는 게 확연히 느껴졌다. 
"코딩 입문자들 중에서는 1등, 코딩 좀 해본 사람들 중에서는 꼴등", 이게 바로 딱 내 위치였다. 이런 생각들과 부담감을 계속 느끼다 보니 코딩에 대한 흥미가 점점 떨어져 갔다.
```
문장이 무엇을 의미하는진 알겠는데 뭔가 입체적이지 않은 것 같아요. 
살짝 수정해 봤는데 계속해서 만져 볼 가치가 있는 문장인 것 같아요!

2021-03-25 15:31 UTC, bperhaps commented on level-1.md
> +그런데, 그렇게 10시에 데일리 미팅하고 코딩하고 밥먹고 코딩하고 하다가 문득 이런 생각을 했다.
글을 읽는 사람에게 있어서 사전 지식을 요구하는 내용인 것 같아요.
우테코 프로세스를 모르는 사람이 보면 데일리는 뭐지? 10시는 뭔 시간이지? 라고 생각이 들 것 같아요!
뭔가 우테코의 생활을 전반적으로 나타내면서 모두가 이해할 수 있는 문장으로 이루어지면 좋을 것 같아요

2021-03-25 15:31 UTC, bperhaps commented on level-1.md
> +자바스크립트를 자유자재로 쓰는 크루를 보면서, 차분하게 본인의 의견을 논리적으로 전달하는 크루를 보면서 자극을 받았다. 슬랙 방에서 적극적으로 질문하고 답변하는 크루들 코치들을 보면서, 나도 끼고 싶다는 생각을 했다. 코딩을 '잘'하고 싶어졌다.
```suggestion
자바스크립트를 자유자재로 쓰는 크루를 보면서, 그리고 차분하게 본인의 의견을 논리적으로 전달하는 크루를 보면서 많은 자극을 받았다. 슬랙 방에서 적극적으로 질문하고 답변하는 크루들과 코치들을 보면서, 나도 저 대화에 참여하고 싶다는 생각을 했다. 

그렇게, 코딩을 '잘'하고 싶다는 마음은 점점 커져갔다.
```

앞에서 코딩을 잘하고 싶다는 생각을 이미 서술했는데, 한번 더 서술하는게 어색하다고 느껴졌어요.
이유가 나왔으면 그 다음에는 앞에서 서술한 내용에 대한 변화를 보여야 할 것 같은데 그런 부분이 없어서 한번 재멋대로 수정해 봤습니다! 참고로만 봐주세요!!!

2021-03-25 15:31 UTC, bperhaps commented on level-1.md
> +그래서 자바스크립트 개념 책을 사고, 스터디도 하고, 미션을 열심히 하고 있다. 정말 하루 하루 최선을 다하고 있다. 여전히 내가 아는 것 보단 모르는 게 많은 것 같지만, 이를 인지하고 있다는 것 조차 나는 한 단계 성장했다고 생각한다.
```suggestion
현재 나는 자바스크립트 스터디와 우테코 미션을 하며 정말 하루 하루 최선을 다하고 있다. 
그럼에도 불구하고, 여전히 내가 아는 것 보단 모르는 게 많은 것 같다. 하지만 이를 인지하고 있다는 사실이 내가 한 단계 더 성장했다는 것을 보여준다고 생각한다.
```
새로운 문장을 시작하는데 접속사가 들어가는건 어색하다고 느꼈어요! 그리고 자스 책을 샀다는 내용은 글의 몰입을 방해하는 불필요한 부가 설명이라 생각해요! 결국 말하고자 하는건 "열심히 살고 있다" 인데 문장이 너무 기어져서 주제 전달이 힘들다고 느껴졌어요!
마지막 문장은 뭔가 어색함이 느껴지는 어떻게 고치는게 좋을지 몰라서 일단 제 스타일 대로 수정해봤는데 참고로 봐주세요!

2021-03-25 15:31 UTC, bperhaps commented on level-1.md
> +사실 할게 많아서 시간 관리에 대한 압박이 조금은 있지만, 이 압박도 한 두달 지속되다 보니 점점 없어지는 것 같다. 일단 할 거는 쌓여있고, 계속 쌓일 거고, 내가 지금 놀지 않고 열심히 하고 있으니 됐지 뭐. 이런 마인드가 생겼다.
```suggestion
사실, 처음에는 할게 많아서 시간 관리에 대한 압박이 조금은 느껴졌다. 하지만 이 압박도 한 두달 지속되다 보니 점점 없어지는 것 같다. 일단 할 일은 쌓여있고, 앞으로도 계속 쌓일 거다. 그래도 '내가 지금 놀지 않고 열심히 하고 있으니 됐지 뭐', 이런 마인드가 생겼다. 
```
첫 문장의 호흡이 너무 긴 것 같아서 2개 문장으로 나누고 접속사로 이어봤어요!
뒷 문장은 엘라의 생각과 글이 혼재돼 있어 어색함이 느껴져서 제가 느낀대로, 엘라의 생각을 작은따음표로 묶어봤습니다!

2021-03-25 15:31 UTC, bperhaps commented on level-1.md
> +그리고 이런 생활을 하면서, 이런 생각들을 하면서 다시 코딩이 재밌어졌다. 요구사항에 맞춰서 어플리케이션의 흐름을 파악하고, 논리를 생각하고, 코드를 작성하는 게 다시 너무 재밌어졌다. 이번에는 재미뿐만 아니라 코딩 실력까지도 끝까지 가져가고싶다. 이 마인드로 10개월을 버텨봐야겠다.
```suggestion
그리고 이런 생활과 생각들을 하면서 다시 코딩이 재밌어졌다. 요구사항에 맞춰서 어플리케이션의 흐름과 논리를 생각하고, 코드를 작성하는 게 다시 너무 재밌어졌다. 이번에는 재미뿐만 아니라 코딩 실력까지도 끝까지 가져가고싶다. (이 마인드로 10개월을 버텨봐야겠다.)
```

마지막에 이 마인드라는게 무슨 마인드를 말하는지 잘 모르겠어요! 한번 확인해 주시겠어요!?

2021-03-27 13:20 UTC, Sehwan-Jang reviewed
안녕하세요 엘라!
글에 진솔함을 담는 능력이 정말 뛰어나신 것 같아요.
아직 엘라를 만나본 적도 없지만 글이 담고 있는 솔직함, 진정성이 느껴져서 
이유 모를(?) 친근감도 생기고 어느새 정말 잘되길 응원하고 있었네요 😄 
원하시는 바 꼭 이루시고 남은 미션도 화이팅하세요!

2021-03-27 13:20 UTC, Sehwan-Jang commented on level-1.md
> +당시에는, 지금처럼 재밌게 코딩하다보면 어느샌가 내가 훌륭한 개발자가 되어있을 줄 알았다. 코딩이 나한테 있어서 재밌다는게 중요하다고 생각했고, 그렇게 그냥 즐기면서 했던 것 같다.
```suggestion
당시에는 내가 코딩을 재밌어 하는 것 자체가 중요하다고 생각했다.  지금처럼 재밌게 코딩하다보면 어느샌가 내가 훌륭한 개발자가 되어있을 줄 알았다. 
```
`재미있게 코딩하고 있다` 라는 의미가 중복되고 있는 것 같아 고쳐봤습니다 :)

2021-03-27 13:20 UTC, Sehwan-Jang commented on level-1.md
> +밝고 적극적인 크루들 사이에서 적응할 시간이 필요했고, 항상 혼자하던 코딩을 페어와 같이 맞춰가는 상황 속에서도 적응을 해야했다. 그런 시간들 속에서도 잠 자기 전 침대에 누워서는 내가 10개월 동안 우테코를 할 수 있을까 생각하다가 잠들었다. 뭔가 나자신에 대한 확신이 없었다.
```suggestion
밝고 적극적인 크루들 사이에서 적응할 시간이 필요했고, 항상 혼자하던 코딩을 페어와 같이 맞춰가는 상황 또한 적응을 해야했다. 그런 시간들 속에서도 잠 자기 전 침대에 누워서는 내가 10개월 동안 우테코를 할 수 있을까 생각하다가 잠들었다. 뭔가 나자신에 대한 확신이 없었다.
```
`상황 속에서도 적응한다` 라는 말이 살짝 어색한 것 같아요.

2021-03-27 14:50 UTC, dusdn1702 approved these changes
안녕하세요, 엘라!
제 프론트엔드 선생님이신데 이렇게 같은 팀으로 뵙게 되어 더욱 반갑네요 ☺️
글을 읽는데 제가 느끼는 감정과 비슷한 감정들을 많이 느끼고 계셔서 공감이 되어 그런지 재미있게 잘 읽었어요🤗
문법과 관련한 부분은 손너잘이 잘 리뷰해주어서 저는 간단한 코멘트 몇 개 달고 approve 하도록 하겠습니다!

저도, 엘라도 지금 이 열정과 감정 잃지 말고 지치지 말고 10개월 후에 **진짜 개발자**가 되어있길 기대하겠습니다! 레벨 1 수고 많으셨어요 👍

2021-03-27 14:50 UTC, dusdn1702 commented on level-1.md
> +당시에는, 지금처럼 재밌게 코딩하다보면 어느샌가 내가 훌륭한 개발자가 되어있을 줄 알았다. 코딩이 나한테 있어서 재밌다는게 중요하다고 생각했고, 그렇게 그냥 즐기면서 했던 것 같다.
정말 공감가는 부분이네요 😭

2021-03-27 14:50 UTC, dusdn1702 commented on level-1.md
> +밝고 적극적인 크루들 사이에서 적응할 시간이 필요했고, 항상 혼자하던 코딩을 페어와 같이 맞춰가는 상황 속에서도 적응을 해야했다. 그런 시간들 속에서도 잠 자기 전 침대에 누워서는 내가 10개월 동안 우테코를 할 수 있을까 생각하다가 잠들었다. 뭔가 나자신에 대한 확신이 없었다.
```suggestion
밝고 적극적인 크루들 사이에서 적응할 시간이 필요했고, 항상 혼자하던 코딩을 페어와 같이 맞춰가는 상황 속에서도 적응을 해야했다. 그런 시간들 속에서도 잠 자기 전 침대에 누워서는 내가 10개월 동안 우테코를 할 수 있을까 생각하다가 잠들었다. 뭔가 나 자신에 대한 확신이 없었다.
```

2021-03-27 14:50 UTC, dusdn1702 commented on level-1.md
> +그런데, 그렇게 10시에 데일리 미팅하고 코딩하고 밥먹고 코딩하고 하다가 문득 이런 생각을 했다.
```suggestion
그런데 10시에 데일리 미팅하고 코딩하고 밥먹고 코딩하고를 반복하다가 문득 이런 생각을 했다. 
```
조금 더 자연스럽게 바꾸어보았어요! 무시하셔도 좋습니다 ㅎㅎ

2021-03-27 14:50 UTC, dusdn1702 commented on level-1.md
> +이전까지는 그냥 코딩 하는게 재밌었고, 재밌게 하다보면 알아서 실력은 늘어있을 줄 알았는데 그게 아니었다. 내가 무언가에 대해 실력있는 사람이 되려면, 엄청난 노력이 필요하다. 그리고 그 노력의 결실은 단기간에 오지 않는다. 그래서 그 노력을 지금 우테코에서 쏟아내야 겠다는 생각을 했다.
```suggestion
이전까지는 그냥 코딩 하는게 재밌었고, 재밌게 하다보면 알아서 실력은 늘어있을 줄 알았는데 그게 아니었다. 내가 무언가에 대해 실력있는 사람이 되려면, 엄청난 노력이 필요하다는 것을 알았다. 그리고 그 노력의 결실은 단기간에 오지 않는다. 그래서 그 노력을 지금 우테코에서 쏟아내겠다는 생각을 했다.
```  
제 기준에 더 이해가 쉬운 말로 바꾸어보았어요! 엘라가 보시고 원하시는대로 해주셔도 됩니다 :)

2021-03-27 14:50 UTC, dusdn1702 commented on level-1.md
> +사실 할게 많아서 시간 관리에 대한 압박이 조금은 있지만, 이 압박도 한 두달 지속되다 보니 점점 없어지는 것 같다. 일단 할 거는 쌓여있고, 계속 쌓일 거고, 내가 지금 놀지 않고 열심히 하고 있으니 됐지 뭐. 이런 마인드가 생겼다.
```suggestion
사실 할게 많아서 시간 관리에 대한 압박이 조금은 있지만, 이 압박도 한두 달 지속되다 보니 점점 없어지는 것 같다. 일단 할 거는 쌓여있고, 계속 쌓일 거고, 내가 지금 놀지 않고 열심히 하고 있으니 됐지 뭐. 이런 마음가짐이 생겼다. 
```
저도 헷갈려서 찾아보니 `한두 달`이 옳다고 하네요! :) 마음가짐이 더 좋을 듯 하여 제시해봐요 ㅎㅎ

2021-03-27 19:54 UTC, SunYoungKwon requested changes
코딩을 시작하게 된 시점부터 현재까지의 이야기 잘 읽었습니다. 공감되는 내용도 많더라구요. 성장하고 싶다는 생각을 가지게 된 시점에 이미 엘라의 성장이 시작되지 않았나 생각합니다. 응원해요🎉!!

첫 번째 글쓰기 미션 수고하셨습니다.

2021-03-27 19:54 UTC, SunYoungKwon commented on level-1.md
> +당시에는, 지금처럼 재밌게 코딩하다보면 어느샌가 내가 훌륭한 개발자가 되어있을 줄 알았다. 코딩이 나한테 있어서 재밌다는게 중요하다고 생각했고, 그렇게 그냥 즐기면서 했던 것 같다.
```suggestion
당시에는, 지금처럼 재밌게 코딩하다 보면 어느샌가 내가 훌륭한 개발자가 되어있을 줄 알았다. 그저 나에게 코딩이 재밌다는 사실이 중요했고, 그렇게 그냥 즐기면서 공부했다. 
```

저도 이 문장 완전 공감합니다🥲

2021-03-27 19:54 UTC, SunYoungKwon commented on level-1.md
> +그런데 시간이 흐를수록 그리고 취업할 시기가 다가올 수록, 나는 코딩에 대한 부담감을 갖기 시작했다. 막상 개발자로 취업하려하니 내가 참 이도저도 아닌 실력이라는 게 확연히 느껴졌다. 코딩 입문자들 중에서는 1등, 코딩 좀 해본 사람들 중에서는 꼴등. 딱 내 위치였다. 이런 생각들과 부담감을 계속 느끼다 보니 코딩이 재미없어졌다.
```suggestion
그런데 시간이 흐르고 취업할 시기가 다가올수록, 코딩이 점차 부담스러워지기 시작했다. 막상 개발자로 취업하려니 내가 참 애매한 실력이라는 게 느껴졌다. 입문자 중에서는 1등, 코딩 좀 해본 사람들 중에서는 꼴등. 그게 딱 내 위치였다. 떨칠 수 없는 이런 생각과 계속되는 부담감에 어느센가 코딩이 재미없어졌다. 
```

졸업하고 난 뒤 제 심정같아요🥲 제가 맘대로 수정해봤는데, 엘라가 마음에 드는 부분이 있다면 반영하고 아니라면 넘어가시면 될 것 같아요.

2021-03-27 19:54 UTC, SunYoungKwon commented on level-1.md
> +내가 제일 재밌어 하던 일이 더 이상 재미없어 진다는 건, 참 슬픈일이다.
맞아요...

2021-03-27 19:54 UTC, SunYoungKwon commented on level-1.md
> +약간의 번아웃이 온 상태에서, 감사하게도 우테코에 합격을 했고 그렇게 다시 코딩을 시작했다. 2월, 3월을 비교해 보았을 때 지금 3월이 훨씬 바쁘고 미션도 어렵지만, 나에게는 2월이 더 힘든 시간들이었다.
```suggestion
약간의 번아웃이 온 상태에서, 감사하게도 우테코에 합격했다. 그렇게 다시 코딩을 시작했다. 2월과 비교해 보았을 때 지금 3월이 훨씬 바쁘고 미션도 어렵지만, 나에게는 2월이 더 힘든 시간이었다. 
```

어색하게 보이는 부분 살짝 수정해봤습니다.

2021-03-27 19:54 UTC, SunYoungKwon commented on level-1.md
> +밝고 적극적인 크루들 사이에서 적응할 시간이 필요했고, 항상 혼자하던 코딩을 페어와 같이 맞춰가는 상황 속에서도 적응을 해야했다. 그런 시간들 속에서도 잠 자기 전 침대에 누워서는 내가 10개월 동안 우테코를 할 수 있을까 생각하다가 잠들었다. 뭔가 나자신에 대한 확신이 없었다.
```suggestion
밝고 적극적인 크루들 사이에서 적응할 시간이 필요했다. 항상 혼자 하던 코딩을 페어와 같이 맞춰가야 하는 상황 또한 적응해야 했다. 그 시간동안 매일 잠 자기 전 침대에 누워 '내가 10개월 동안 우테코 과정을 잘 따라갈 수 있을까?' 생각하다 잠들었다. 나 자신에 대한 확신이 없었다.
```

우테코는 교육과정인데 '교육과정을 한다'라는 문장이 부자연스럽게 느껴져 수정해봤어요.

2021-03-27 19:54 UTC, SunYoungKwon commented on level-1.md
> +그런데, 그렇게 10시에 데일리 미팅하고 코딩하고 밥먹고 코딩하고 하다가 문득 이런 생각을 했다.
저도 샐리 제안이 좋아보이네요! 다만 저는 '그렇게' 보다 '그런데'를 제거하는 것이 조금 더 낫지 않을까 조심스레 의견내봅니다. 어느 쪽을 남기든 문장은 괜찮은 것 같지만 읽는 사람이 받는 느낌에 약간 차이가 있는 것 같아요.

2021-03-27 19:54 UTC, SunYoungKwon commented on level-1.md
> +이전까지는 그냥 코딩 하는게 재밌었고, 재밌게 하다보면 알아서 실력은 늘어있을 줄 알았는데 그게 아니었다. 내가 무언가에 대해 실력있는 사람이 되려면, 엄청난 노력이 필요하다. 그리고 그 노력의 결실은 단기간에 오지 않는다. 그래서 그 노력을 지금 우테코에서 쏟아내야 겠다는 생각을 했다.
저도 앞의 '아니었다'가 과거형인데 '필요하다'가 현재 시제인게 안 어울린다고 느꼈어요.

2021-03-27 19:54 UTC, SunYoungKwon commented on level-1.md
> +성장하고 싶다. 더 성장해서 진짜 개발자가 되고싶다.
👍

2021-03-28 06:38 UTC, ggyool reviewed
저는 엘라가 되게 밝은 사람이라고 생각했어요.
많이 힘들었군요. 😭😭😭
잘하는 크루들을 보며 자극을 받기도 하지만, 한편으로는 비교하게 되는 것 같아요.
너무 압박받지 않으면 좋겠어요.
우테코에 들어오고, 따라가고 있는 것만으로도 충분히 대단하다고 생각해요.
재밌게 코딩하는 마인드 참 좋아보여요.👍
함께 성장해나가요!

글에 대해서는 많은 분들이 코멘트를 남겨주셨고, 반영하시면 좋은 글이 될 것 같아요.
사소할 수도 있지만 띄어쓰기가 잘못된 부분이 꽤 보여요.
저도 띄어쓰기를 잘 못 해서 글 올리기 전에 항상 돌려보는데요.
전체적으로 한번 체크하시면 좋을 것 같아요.💦

2021-03-28 06:38 UTC, ggyool commented on level-1.md
> +이전까지는 그냥 코딩 하는게 재밌었고, 재밌게 하다보면 알아서 실력은 늘어있을 줄 알았는데 그게 아니었다. 내가 무언가에 대해 실력있는 사람이 되려면, 엄청난 노력이 필요하다. 그리고 그 노력의 결실은 단기간에 오지 않는다. 그래서 그 노력을 지금 우테코에서 쏟아내야 겠다는 생각을 했다.
```suggestion
이전까지는 그냥 코딩하는 게 재밌었고, 재밌게 하다 보면 알아서 실력이 늘어있을 줄 알았는데 그게 아니었다. 어떤 분야에서 실력있는 사람이 되려면 엄청난 노력이 필요하다. 그리고 그 노력의 결실은 단기간에 얻을 수 있는 것이 아니다. 그래서 그 노력을 지금 우테코에 쏟아내야겠다는 생각을 했다.
```
문장이 자연스럽게 느껴지도록 연결을 조금씩 고쳐 봤어요. 😆
'결실이 온다' 는 부분이 어색해서 결실을 얻는다고 바꿨습니다.
수정한 부분이 많은데 그냥 주관적인 관점으로 바꿔봤습니다. 
엘라가 마음에 드는 부분이 있으면 반영하시면 될 것 같아요.

2021-03-28 12:40 UTC, HyuuunjuKim commented on level-1.md
> +3년 전, 코딩을 시작했다. 그냥 전공 공부 하기 싫어서 혼자 고민하던 중에 아는 선배를 따라 얼떨결에 코딩 동아리에 들어갔고, 그렇게 코딩을 하게 되었다.
오홍!!! 저도 약간 첫 문장 호흡이 짧은 것 같아서 조금 고민했는데, 딱 바로 잡아 주셨네요 ㅎㅎ 감사합니다.

2021-03-28 12:41 UTC, HyuuunjuKim commented on level-1.md
> +그런데 생각보다 너무 재밌었다. 이 이유가 내가 지금도 코딩을 하고있는 이유다. 처음으로 내가 하는 공부와 일에 대해 열정을 느꼈고, 재미를 느꼈고, 밤을 새며 공부를 했고, 그렇게 '개발자'라는 꿈을 막연하게 꾸기 시작했다.
훨씬 글이 자연스러워지네요 ㅎㅎ 감사합니다.😁

2021-03-28 12:43 UTC, HyuuunjuKim commented on level-1.md
> +그런데 시간이 흐를수록 그리고 취업할 시기가 다가올 수록, 나는 코딩에 대한 부담감을 갖기 시작했다. 막상 개발자로 취업하려하니 내가 참 이도저도 아닌 실력이라는 게 확연히 느껴졌다. 코딩 입문자들 중에서는 1등, 코딩 좀 해본 사람들 중에서는 꼴등. 딱 내 위치였다. 이런 생각들과 부담감을 계속 느끼다 보니 코딩이 재미없어졌다.
코딩 입문자들 중에서는 1등, 코딩 좀 해본 사람들 중에서는 꼴등

이 부분을 조금 강조하면서 수정했습니다 ㅎㅎㅎ 감사합니다.

2021-03-28 12:44 UTC, HyuuunjuKim commented on level-1.md
> +그런데, 그렇게 10시에 데일리 미팅하고 코딩하고 밥먹고 코딩하고 하다가 문득 이런 생각을 했다.
호곡 그런 부분까지는 생가해보지  못했네요 ㅎㅎㅎ,,, 조금 더 생각해서 수정해봐야겠어요 ㅎㅎㅎ

2021-03-28 12:48 UTC, HyuuunjuKim commented on level-1.md
> +사실 할게 많아서 시간 관리에 대한 압박이 조금은 있지만, 이 압박도 한 두달 지속되다 보니 점점 없어지는 것 같다. 일단 할 거는 쌓여있고, 계속 쌓일 거고, 내가 지금 놀지 않고 열심히 하고 있으니 됐지 뭐. 이런 마인드가 생겼다.
오홍 그렇네요 ㅎㅎㅎ 제 생각을 전달하는 문구이니 작은 따옴표로 묶는 게 훨씬 좋을 것 같아요 ㅎㅎㅎ 감사합니다.😁

2021-03-28 12:50 UTC, HyuuunjuKim commented on level-1.md
> +그리고 이런 생활을 하면서, 이런 생각들을 하면서 다시 코딩이 재밌어졌다. 요구사항에 맞춰서 어플리케이션의 흐름을 파악하고, 논리를 생각하고, 코드를 작성하는 게 다시 너무 재밌어졌다. 이번에는 재미뿐만 아니라 코딩 실력까지도 끝까지 가져가고싶다. 이 마인드로 10개월을 버텨봐야겠다.
``이번에는 재미뿐만 아니라 코딩 실력까지도 끝까지 가져가고싶다.``

이 마인드를 전달하고 싶었던 건데,,, 잘 전달이 안됐나 보네요 ㅜㅜㅜ

2021-03-28 12:52 UTC, HyuuunjuKim commented on level-1.md
> +밝고 적극적인 크루들 사이에서 적응할 시간이 필요했고, 항상 혼자하던 코딩을 페어와 같이 맞춰가는 상황 속에서도 적응을 해야했다. 그런 시간들 속에서도 잠 자기 전 침대에 누워서는 내가 10개월 동안 우테코를 할 수 있을까 생각하다가 잠들었다. 뭔가 나자신에 대한 확신이 없었다.
오 훨씬 좋은 것 같아요 !!! 감사합니다. ㅎㅎ

2021-03-28 12:53 UTC, HyuuunjuKim commented on level-1.md
> +당시에는, 지금처럼 재밌게 코딩하다보면 어느샌가 내가 훌륭한 개발자가 되어있을 줄 알았다. 코딩이 나한테 있어서 재밌다는게 중요하다고 생각했고, 그렇게 그냥 즐기면서 했던 것 같다.
감사합니다 ㅎㅎ

2021-03-28 12:55 UTC, HyuuunjuKim commented on level-1.md
> +그런데, 그렇게 10시에 데일리 미팅하고 코딩하고 밥먹고 코딩하고 하다가 문득 이런 생각을 했다.
꺄하 두 분의 의견 감사합니다 ㅎ ㅎ 훨씬 저 한 줄의 흐름이 자연스러워지게 수정했습니다 😁😁😁

2021-03-28 12:57 UTC, HyuuunjuKim commented on level-1.md
> +이전까지는 그냥 코딩 하는게 재밌었고, 재밌게 하다보면 알아서 실력은 늘어있을 줄 알았는데 그게 아니었다. 내가 무언가에 대해 실력있는 사람이 되려면, 엄청난 노력이 필요하다. 그리고 그 노력의 결실은 단기간에 오지 않는다. 그래서 그 노력을 지금 우테코에서 쏟아내야 겠다는 생각을 했다.
저는 저 현재형이 제 생각을 더 강조해 줄 수 있다고 생각했는데, 반대로 부자연스럽게 다가갔나보네요 ㅎㅎㅎ 두 분 다 의견 내주셔서 감사합니다😄😄😄

2021-03-28 13:00 UTC, HyuuunjuKim commented on level-1.md
> +내가 제일 재밌어 하던 일이 더 이상 재미없어 진다는 건, 참 슬픈일이다.
그쵸,,,,,, `내가 제일 재밌어 하던 일이 더 이상 재미없어 진다는 건, 참 슬픈일이다.` 작년에 참 이 생각을 많이 하고 느꼈던 것 같아요 ㅎㅎㅎ,,

2021-03-28 13:01 UTC, HyuuunjuKim commented on level-1.md
> +약간의 번아웃이 온 상태에서, 감사하게도 우테코에 합격을 했고 그렇게 다시 코딩을 시작했다. 2월, 3월을 비교해 보았을 때 지금 3월이 훨씬 바쁘고 미션도 어렵지만, 나에게는 2월이 더 힘든 시간들이었다.
썬이 제시해주신 흐름이 훨씬 자연스러운 것 같아요 ㅎㅎㅎ 감사합니다.🥰🥰🥰

2021-03-28 13:04 UTC, HyuuunjuKim commented on level-1.md
> +이전까지는 그냥 코딩 하는게 재밌었고, 재밌게 하다보면 알아서 실력은 늘어있을 줄 알았는데 그게 아니었다. 내가 무언가에 대해 실력있는 사람이 되려면, 엄청난 노력이 필요하다. 그리고 그 노력의 결실은 단기간에 오지 않는다. 그래서 그 노력을 지금 우테코에서 쏟아내야 겠다는 생각을 했다.
감사합니다. 중간곰😄 

저 부분 흐름이 많이 부자연스러웠던 것 같아요. 많은 크루들이 코멘트 주셨네요 ㅎㅎㅎㅎ 다시 한 번 수정해 봤어요 ㅎㅎㅎ

2021-03-28 13:29 UTC, sakjung approved these changes
안녕하세요 엘라. 삭정입니다 ㅎㅎ 리뷰 늦어져서 죄송해요 ㅠ

글 잘 읽었어요. 특히, 실력을 빨리 늘리고 싶은 엘라의 마음이 너무 공감갔습니다. 
우테코 기간동안 열심히 달려서 진짜 실력있는 개발자가 되어봅시다!

피드백은 다른분들이 촘촘하게 주셔서 딱히 건드릴 부분은 없는 것 같아요. 한 부분에 대해서 제안 하나 드렸는데, 사소한 부분이라 참고만 해주세요. 바로 approve 드리겠습니다!

2021-03-28 13:29 UTC, sakjung commented on level-1.md
> +그렇게 시작한 코딩은 생각보다 너무 재밌었다. 이게 내가 지금도 코딩을 하고있는 이유다. 처음으로 내가 하는 공부와 일에 대해 열정과 재미를 느꼈고, 밤을 새며 공부를 했고, 그렇게 '개발자'라는 꿈을 막연하게 꾸기 시작했다.
저 처음 코딩 시작했을 때랑 똑같네요 ㅋㅋ 너무 공감갑니다

2021-03-28 13:29 UTC, sakjung commented on level-1.md
> +'아, 코딩 잘하고 싶다.'
저두요 ㅋㅋ ㅠ..ㅠ

2021-03-28 13:29 UTC, sakjung commented on level-1.md
> +자바스크립트를 자유자재로 쓰는 크루를 보면서, 차분하게 본인의 의견을 논리적으로 전달하는 크루를 보면서 많은 자극을 받았다. 슬랙 방에서 적극적으로 질문하고 답변하는 크루들 코치들을 보면서, 나도 참여하고 싶다는 생각을 했다. 그렇게 더더욱 코딩을 '잘'하고 싶어졌다.
```suggestion
자바스크립트를 자유자재로 쓰고 차분하게 본인의 의견을 논리적으로 전달하는 크루들을 보면서 저들과 같은 실력자가 되고싶다는 생각을 했다. 슬랙 방에서 적극적으로 질문하고 답변하는 크루들과 코치들을 보면서 저들의 대화에 참여하고 싶다는 생각을 했다. 그렇게 더더욱 코딩을 '잘'하고 싶어졌다.
```

약간 반복적인 느낌의 문장으로 바꿔봤어요. 뭔가 엘라의 간절함이 더 강해지는 느낌을 줄 수 있을 것 같아서요 ㅎㅎ. 참고만해주세요!

2021-03-28 15:12 UTC, dusdn1702 approved these changes
수정된 것 확인하고 approve 하겠습니다~ 수고 많으셨습어요:)
앞으로 직접 뵐 기회가 생겼으면 좋겠어요!!🤗

2021-03-28 15:35 UTC, ggyool approved these changes
고생했어요 엘라. Approve 드릴게요!
조만간 꼭 봐요. 😄

2021-03-28 15:42 UTC, SunYoungKwon approved these changes
엘라의 성장이 기대돼요! 같이 열심히 해 봐요😉

2021-03-28 22:56 UTC, Sehwan-Jang approved these changes
깔끔하게 고쳐주신 것 같아서 approve 드릴게요!
첫 글쓰기 미션 고생 많으셨고 루터에서 직접 뵐 수 있기를 바랄게요~ 🙏

2021-03-28 23:10 UTC, bperhaps approved these changes
수정하시느라 정말 수고하셨습니다!!!
저도 이만 approve하겠습니다!

2021-04-06 04:09 UTC, wmakerjun commented
오늘 하루를 알차게, 단 내가 주인공이게 지낸다면 남은 기간을 통해 더 🌟 빛나는 엘라가 될거에요!
우테코 과정 통해서 코딩해본 사람 중에서 🌟 빛나는 엔지니어가 되길 바랄게요! 남은 기간도 함께 파이팅입니다!!!

2021-04-06 04:09 UTC, merged