[레벨 1 글쓰기 미션] 에드(박성진) 미션 제출합니다.
woowacourse/woowa-writing-3 pull request #45
Opened 2021-03-26 06:22 UTC by sjpark-dev

안녕하세요, 백엔드 크루 에드입니다. 😊
부족한 글이지만 리뷰 잘 부탁드립니다. 👍

[글 링크](https://github.com/sjpark-dev/woowa-writing-3/blob/sjpark-dev/README.md)

[리뷰어]
@sjpark-dev

소중한 리뷰 감사합니다. 👍

2021-03-26 06:36 UTC, sihyung92 commented on README.md
> +나는 아직 성장 중이다.
애드~~~~~~~~~~~~~~~지나가다가~~ 글 잘 읽었어요 ㅎㅎㅎ
성장하는 애드 항상 응원합니다!!

2021-03-26 06:36 UTC, qhals321 commented
에드... 오구오구가 절로 나오는 글이에여...ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
에드 pull request 있길래 바로 읽고 가여!!
완전 글 진솔한 것 같아 너무 잘 읽고 가요!!!!
파이팅!!

2021-03-26 06:40 UTC, bperhaps commented
애드 글 읽는데 마음이 뭉클해지네요..ㅠㅠ
우리 남은 8개월도 열심히 달려봐요!!

2021-03-26 08:14 UTC, sjpark-dev commented on README.md
> +나는 아직 성장 중이다.
감사합니다. 저도 웨지 항상 응원합니다~!! 👍👍👍

2021-03-26 08:14 UTC, sjpark-dev commented
> 에드... 오구오구가 절로 나오는 글이에여...ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
> 에드 pull request 있길래 바로 읽고 가여!!
> 완전 글 진솔한 것 같아 너무 잘 읽고 가요!!!!
> 파이팅!!

2021-03-26 11:04 UTC, thisisyoungbin reviewed
에드 안녕하세요!! 매번 같은 방에서 뵙다가 글쓰기 리뷰어로 또 뵙네요!! ㅎㅎ
솔직하고 담백한 글 잘 읽었습니다.
제가 읽었을 땐 긴 호흡의 문장도 없고, 우테코 시작부터 지금까지의 과정동안 에드의 생각이 잘 정리돼 있어 공감만 하고 리뷰드릴 부분은 많이 못 찾았네요...


개인적으로 딱 한 가지 아쉬웠던 점만 말씀드려볼게요! 한 달간의 우테코 과정에서 있었던 구체적인 일들(보이는 라디오, 미션, 생활 등등)에 대해 좋았거나 아쉬웠던 부분들도 있다면 좀 더 풍성한 글이 될 것 같은데 어떻게 생각하세요?! 반드시 들어가야 하는 건 아니지만 제 개인적인 생각을 말씀드려봤습니다...!


글 잘 읽었어요!!

2021-03-26 11:04 UTC, thisisyoungbin commented on README.md
> +우아한테크코스의 초반은 다양한 사람들의 뛰어남을 접하는 시간이었다.
`우아한테크코스 초반 기간동안 다양한 사람들의 뛰어남을 접했다.` 혹은 `우아한테크코스 초반 기간동안 다양한 사람들의 뛰어남을 경험했다` 식으로 표현하면 좀 더 생동감 있는 문장이 될 것 같아요!!

2021-03-26 11:04 UTC, thisisyoungbin commented on README.md
> +만나는 사람마다 말로 표현은 하지 않았지만, 속으로는 대단한 사람이구나 생각했다.
`뛰어난 사람을 만날 때 마다 말로 표현하진 않았지만, 속으로 '대단한 사람이구나' 생각했다.`는 어때요?! 어떤 의미인지는 알겠는데 문장이 좀 모호한 것 같아서 코멘트 남겨봅니다!

2021-03-26 11:04 UTC, thisisyoungbin commented on README.md
> +모든 사람들에게 후광이 보이는 신기한 경험이었다.
공감합니다. 적응하기 전에 자괴감 엄청 났어요. 지금은 이런 익숙해져서 그런가 무덤덤하네요ㅎㅎ

2021-03-26 11:04 UTC, thisisyoungbin commented on README.md
> +머리 속은 이런 자책들도 가득했고 정신은 점점 지쳐 갔다.
크... 저도 같은 생각이었어요. '아니 너무 비교 되잖아.. 나 어떻게 붙은거지?' 따위의 생각요..ㅎㅎㅎ
저 같은 경우엔 '레벨4까지 가면 모두 비슷한 수준으로 올라간다는데, 지금의 공부하는 관성을 잃지말자..!'라고 생각하고 있어요.
그러니까 마음이 좀 여유로워지고 더 이상 흔들리지 않았던 것 같습니다!

2021-03-26 14:38 UTC, Be-poz commented
에드 잘 읽고 갑니다~! 에드가 느끼는 상대방에 대한 감정을 누군가가 그대로 에드한테 느끼고 있을 지에 대한 여부는 아무도 모르잖아요? 에드 화이팅! 같이 잘해봅시다~!

2021-03-26 14:44 UTC, knae11 reviewed
문장이 전체적으로 간결하고 깔끔해서 읽기 좋네요 :) 리뷰할 내용이 안 보여요ㅋㅋㅋㅋㅋ 반전되는 내용도 좋고, 솔직한 이야기라 흥미롭게 읽었어요 :)  에드의 성격이 보이는 듯한 글이라고 생각이 들었어요 👍

다만 한가지 리뷰어로서 드리는 코멘트는 에드만의 제목을 붙여주세요!ㅋㅋㅋㅋㅋ 제목이 생기면 approve 할게요 :)

2021-03-26 14:44 UTC, knae11 commented on README.md
> +나는 아직 성장 중이다.
저도 이 내용에 공감합니다!ㅎㅎㅎㅎㅎ   부족하다는 것은 성장할 수 있는 공간이 많은 거니까요! 언제나 뛰어난 사람들 속에 속할 수 있다는게 저는 좋더라구요!ㅋㅋㅋㅋㅋㅋ 저는 사실 여기서 오히려 모두 나보다 잘하는 사람들이겠지라고 생각해서 스트레스를 많이 받지 않는 편이에요ㅋㅋㅋ 아무도 못한다고 뭐라 하지도 않으니깤ㅋㅋㅋㅋ 각자의 페이스대로 성장해나가요!><

2021-03-26 15:43 UTC, unluckyjung commented
에 대리 화이팅! 
영부장님 눈치를 안 보고 칼퇴근 할 수 있는 우아 상사를 완성 할 때까지 8개월간 함께 잘 달려봐요.

경쟁하는 것은 어제의 에드 일뿐 포과장 영부장이 아니잖아요. 
분명 지금의 에드는 우리가 처음 만났을 때의 에드보다 성장했고, 지금 마인드라면 계속해서 성장할 일만 남았음을 의심치 않습니다. ㅎㅎ

2021-03-26 16:18 UTC, 365kim commented on README.md
> +예를 들면, 누구는 새벽까지 공부를 해도 아침 일찍 일어날 수 있는 강철 체력이 있고, 또 다른 누구는 어려운 문제를 간단히 해결하는 뛰어난 사고력이 있다.
맞아요,,, 저는 강철체력 제일 부러워요,,,🦾🦾

2021-03-26 16:19 UTC, 365kim commented on README.md
> +'어떻게 하나를 배워도 열을 알지? 진짜 멋있다...'
`어떻게 하나'만' 배워도 열을 알지?`는 어떨까용~~~

2021-03-26 16:20 UTC, 365kim commented on README.md
> +아이러니하게도 크루들의 빛에 계속 노출되면서 마음 한 켠에는 그늘이 지기 시작했다.
에드의 표현력이 너무 좋아서 맘에 드는 문장이에요 🙏

2021-03-26 16:21 UTC, 365kim commented on README.md
> +우아한테크코스의 환경은 내 부족함을 항상 따라다니는 그림자로 만들었다.
`그림자👤`라는 표현도 좋네용 ㅎㅎ ☺️☺️

2021-03-26 16:23 UTC, 365kim commented on README.md
> +하지만 나는 생각보다 적응력이 뛰어나다.
단 두 문장 만에 분위기가 확! 반전되어서 읽는 재미가 있었어요~~ 👍👍👍

2021-03-26 16:23 UTC, 365kim commented on README.md
> +나는 아직 성장 중이다.
마지막 문장이 짧은데 정말 강렬하네요...! `나는 아직 성장 중이다.` 🚀🚀🚀

2021-03-26 16:26 UTC, 365kim requested changes
에드, 한 달 생활기 잘 읽었어요! 짧은 호흡으로 크~~게 와닿는 글이네요 🥺 👍
저는 에드의 글이 시원시원하게 잘 읽혀서 피드백 드릴 게 크게 없네용,,,
사소한 제안 하나 코멘트 남겨보았는데 확인만 해주시면 바로 Approve하겠습니당!

2021-03-27 01:35 UTC, zereight commented on README.md
> +예를 들면, 누구는 새벽까지 공부를 해도 아침 일찍 일어날 수 있는 강철 체력이 있고, 또 다른 누구는 어려운 문제를 간단히 해결하는 뛰어난 사고력이 있다.
나는 뛰어난 사고력이 부럽다...🧩🧩

2021-03-27 01:36 UTC, zereight commented on README.md
> +아이러니하게도 크루들의 빛에 계속 노출되면서 마음 한 켠에는 그늘이 지기 시작했다.
역광을 맞으셨군요.

2021-03-27 01:38 UTC, zereight commented on README.md
> +하지만 나는 생각보다 적응력이 뛰어나다.
두근두근

2021-03-27 01:39 UTC, zereight commented on README.md
> +나는 아직 성장 중이다.
오~ 장군이 전쟁나갈때 출사표 던지는 것처럼 멋있어요~

2021-03-27 01:45 UTC, zereight commented on README.md
> +'어떻게 하나를 배워도 열을 알지? 진짜 멋있다...'
`...` 을 많이 쓰는 것 같은데, `.` 으로 상관이 없을까요?! (개인 취향이라 수정안해도됨.)

2021-03-27 01:47 UTC, zereight commented
에드! 진짜진짜 제가 수정제안 드릴만한게 없어요...!
지금까지 뭐라도 코멘트 달았는데, 이 글은 공감이거나 멋있다라고 느끼지만했지 어색함이나 수정할 사항이 보이지 않았어요 ㅜㅜ (제기준)
그래서 사소한 제 코멘트확인해주시면 (수정 안해도되는 되는 부분입니다 ㅎㅎ) Approve 할게요~!

2021-03-27 02:20 UTC, sjpark-dev commented on README.md
> +우아한테크코스의 초반은 다양한 사람들의 뛰어남을 접하는 시간이었다.
확실히 욘의 제안대로 바꾸면 더 생동감 있을 것 같아요 😊
좋은 의견 감사합니다~!! 👍👍👍

2021-03-27 02:21 UTC, sjpark-dev commented on README.md
> +만나는 사람마다 말로 표현은 하지 않았지만, 속으로는 대단한 사람이구나 생각했다.
작은따옴표를 사용하면 표현이 더 명확해지네요. 👍👍👍

2021-03-27 02:29 UTC, sjpark-dev commented on README.md
> +우아한테크코스의 초반은 다양한 사람들의 뛰어남을 접하는 시간이었다.
> 개인적으로 딱 한 가지 아쉬웠던 점만 말씀드려볼게요! 한 달간의 우테코 과정에서 있었던 구체적인 일들(보이는 라디오, 미션, 생활 등등)에 대해 좋았거나 아쉬웠던 부분들도 있다면 좀 더 풍성한 글이 될 것 같은데 어떻게 생각하세요?! 반드시 들어가야 하는 건 아니지만 제 개인적인 생각을 말씀드려봤습니다...!

욘 말대로 이런 저런 에피소드를 넣었다면 더 풍성한 글이 되었을텐데 생각을 하지 못했었네요 😅
지금의 글 구조를 변경하지 않으면서 에피소드를 추가할 수 있을 지 고민해보겠습니다. 👍

2021-03-27 02:32 UTC, sjpark-dev commented on README.md
> +나는 아직 성장 중이다.
> 다만 한가지 리뷰어로서 드리는 코멘트는 에드만의 제목을 붙여주세요!ㅋㅋㅋㅋㅋ 제목이 생기면 approve 할게요 :)

좋은 제목 생각해보겠습니다 😊
피드백 감사합니다. 👍👍👍

2021-03-27 02:36 UTC, sjpark-dev commented on README.md
> +'어떻게 하나를 배워도 열을 알지? 진짜 멋있다...'
> `어떻게 하나'만' 배워도 열을 알지?`는 어떨까용~~~

`하나만`으로 고치면 전달하고 싶은 의미를 더 강조할 수 있겠네요. 👍👍👍

2021-03-27 02:39 UTC, sjpark-dev commented on README.md
> +'어떻게 하나를 배워도 열을 알지? 진짜 멋있다...'
> `...` 을 많이 쓰는 것 같은데, `.` 으로 상관이 없을까요?! (개인 취향이라 수정안해도됨.)

`.`도 괜찮을 것 같네요.  👍👍👍

2021-03-27 02:59 UTC, PapimonLikelion reviewed
안녕하세요 에드! 조엘이라고 합니다!
한 달 생활기 공유해주셔서 감사해요ㅎㅎ
저의 생각과도 닮은 점이 느껴져서 읽는 동안 재미있고, 좋았습니다 :)

제가 드린 제안은 수정이 필수적인 부분들이 아니에요. 내용이 좋아서요!
다만 저는 내용을 조금 더 강조할 수 있도록 제안을 몇 개 드려봤어요. 

하지만~ 적응력 문장에서 글의 분위기가 바뀌면서 멋지게 끝나는데, 
조금 더 출사표(?) 같을 수 있도록, 조금 더 확신이 있는 문체라면 글이 더 강렬하지 않을까 생각해서 몇 개 제안드렸습니다!

다시한번 말씀드리지만 필수적인것은 아니고, 에드의 색을 유지하면서 피드백 필요한 부분은 반영해주세요~

2021-03-27 02:59 UTC, PapimonLikelion commented on README.md
> +어릴 때부터 이사를 많이 다녀서 그런지 어떤 낯설고 힘든 환경에서도 결국에는 잘 적응할 수 있었다.
```suggestion
나에겐 낯설고 힘든 환경에서도 잘 적응할 수 있는 힘이 있다. 아마 어릴 때부터 이사를 많이 다녀서 그랬을 것이다  
```
개인적으로 분위기가 "하지만" 기점으로 확 반전되는것 같아요!
문체에 조금 더 확신과 힘이 생기면 좋을 것 같다는 개인적인 의견입니다!

2021-03-27 02:59 UTC, PapimonLikelion commented on README.md
> +물론 남들의 장점을 흡수하는 것이 쉬운 일은 아니고 오래 걸릴 수도 있다.
```suggestion
물론 남들의 장점을 흡수하는 것이 쉬운 일이 아니다. 
경우에 따라 굉장히 오래 걸릴 수도 있다. 
```
저는 한 번 나눌것 같아요!

2021-03-27 02:59 UTC, PapimonLikelion commented on README.md
> +과거의 경험에서 나오는 자신감이 있기 때문이다.
```suggestion
낯선 환경을 극복했던 경험들이 나를 단단하게 만들었기 때문이다. 
우아한테크코스의 낯섬을 이번에도 극복해 낼 것이다.
```
저는 개인적으로 이 한 문장에서 에드의 자신감을 더 드러낼 수 있을것 같아요!
위의 제안은 그저 예시입니다...!

2021-03-27 03:08 UTC, sjpark-dev commented on README.md
> +어릴 때부터 이사를 많이 다녀서 그런지 어떤 낯설고 힘든 환경에서도 결국에는 잘 적응할 수 있었다.
와... 너무 좋아요 👍👍👍
좋은 제안 감사합니다. 😊

2021-03-27 03:09 UTC, sjpark-dev commented on README.md
> +물론 남들의 장점을 흡수하는 것이 쉬운 일은 아니고 오래 걸릴 수도 있다.
저도 이부분을 나눌지 고민했었는데 결정할 수 있게 해주셔서 감사합니다. 👍

2021-03-27 03:12 UTC, sjpark-dev commented on README.md
> +과거의 경험에서 나오는 자신감이 있기 때문이다.
저도 조금 심심하다고 생각했었는데 이렇게 좋은 아이디어를 주셔서 감사합니다. 👍👍👍

2021-03-27 05:18 UTC, thisisyoungbin commented on README.md
> +우아한테크코스의 초반은 다양한 사람들의 뛰어남을 접하는 시간이었다.
사실 지금 글의 구조가 좋아서 더 건드리면 테마 자체가 깨질 것 같기도해서... 반드시 넣어야하는 것은 아니니 에드의 생각대로 진행해도 될 것 같아요!!

2021-03-27 06:28 UTC, Hyeon9mak commented
건대에서의 추억...⭐

2021-03-27 07:24 UTC, Rok93 reviewed
에드 안녕하세요 : )  로키입니다. 
에드의 ✨표현력이 눈부셨던✨ 글이었네요 👍
같은 말인데 에드만의 표현력으로 더 깊이 와닿는 문장들이 많았어요😍!!  정말 갖고싶은 능력입니다 😆
글의 의도가 잘 드러나는 글이었고 표현을 잘했던 것 같아요. 그래서 크루들이 피드백을 더 명확하게 잘 해주신 것 같습니다. 동일한 문장이라도 피드백을 남기는 편인데... 크루들이 이미 주신 피드백을 더 보완하는 피드백을 드리기가 쉽지가 않더라구요... 😅 

사실상 피드백은 하나뿐이고 온통 공감 코멘트만 달아놨네요ㅎㅎㅎㅎ 
그만큼 공감이 많이 됐던거겠죠?? 
바로 Approve를 드려도 사실 상관없겠지만, (월요일이 마감이니) 일요일 오후에 한번 더 보고 추가적으로 피드백 드릴 부분이 있으면 더 추가해서 approve 하도록 하겠습니다 : )

2021-03-27 07:24 UTC, Rok93 commented on README.md
> +모든 사람들에게 후광이 보이는 신기한 경험이었다.
저도 크루들 보면서 많이 느끼는 감정입니다 😳😳😳😳

2021-03-27 07:24 UTC, Rok93 commented on README.md
> +아이러니하게도 크루들의 빛에 계속 노출되면서 마음 한 켠에는 그늘이 지기 시작했다.
이 표현 너무 좋네요 !!

2021-03-27 07:24 UTC, Rok93 commented on README.md
> +우아한테크코스의 환경은 내 부족함을 항상 따라다니는 그림자로 만들었다.
에드의 다른 부분들은 잘 모르겠지만 ``사고력, 탐구심, 열정, 표현력, 체력 등등 셀 수 없이 많은 형태로 나타난다`` <-- 이 문구를 돌이켜봤을 때, 표현력이 정말 좋으신거같아요 !!  👍

2021-03-27 07:24 UTC, Rok93 commented on README.md
> +하지만 나는 생각보다 적응력이 뛰어나다.
반전잼 😍

2021-03-27 07:24 UTC, Rok93 commented on README.md
> +나는 아직 성장 중이다.
``부족함이 많다는 뜻은 생각을 바꾸면 그 만큼 더 성장할 수 있다는 뜻이다.``  긍정적인 마음가짐  👍
``나는 아직 성장 중이다.`` 이 문장은 엄청 멋지네요 -ing 👍

여기서 억~~~지로 피드백을 드려보자면 
``부족함이 많다는 뜻은 생각을 바꾸면 그 만큼 더 성장할 수 있다는 뜻이다.`` 
--> ``부족함이 많다는 것은 그 만큼 더 성장할 수 있다는 뜻이다.``  

이렇게 바꿔보면 어떨까 싶어요! 

``나는 아직 우아한테크코스에 적응 중이다.`` 의 표현이 없어도 문장이 괜찮을 것 같아요!  
이 부분을  ``나는``이라는 표현이 반복돼서 피드백 드렸어요! 

그런데 아마 에드의 의도인 것 같다고 느껴져서 에드의 의도가 맞다면 그대로 가셔도 될 것 같습니다.

2021-03-27 07:47 UTC, sjpark-dev commented on README.md
> +나는 아직 성장 중이다.
`부족함이 많다는 것은 그 만큼 더 성장할 수 있다는 뜻이다.`
`나는 아직 성장 중이다.`

로키 말대로 이렇게 바꾸는 것도 간결하게 제 의도를 드러낼 수 있겠네요. 👍👍👍
이 부분은 바꿀 생각이 없었는데 로키의 제안이 너무 마음에 들어서 고민이되네요. 🤔

2021-03-27 17:10 UTC, sjpark-dev commented
배럴, 조엘, 로키, 욘, 도비, 하루! 피드백 감사드립니다. 😊
대부분의 피드백을 반영하려고 노력했습니다. 
덕분에 글을 더 매끄럽게 만들 수 있었어요. 
글 읽어 보시고 이상한 점 있으면 말씀해주시면 감사하겠습니다. 👍

아직 배럴이 말한 저만의 제목을 정하지는 못했어요. 😅
(제목 짓는게 생각보다 어렵네요...)

2021-03-27 17:57 UTC, 365kim approved these changes
에드! 수정해주신 글을 읽어봤는데 이전 글보다 더 다채로워진  느낌이에요👍 제가 말씀드린 피드백도 잘 반영된 걸로 확인했어요. 그럼 이만 Approve할게요!

\+ 제목은 너무 스포(?)여서도 안되고 너무 부정적이어서도 안될 것 같아서 어렵긴하네요...! 저는 마지막 문장인 "나는 아직 성장 중이다"를 제목으로 해도 좋을 것 같아요 :)

2021-03-28 04:29 UTC, thisisyoungbin commented
에드 안녕하세요~~! 피드백 반영되어 수정된 부분들 잘 읽어봤어요! 
다시 읽어봐도 에드의 생각과 감정이 솔직하게 정리되어 있어 참 많이 공감했어요ㅎㅎ 
아직 제목이 확정되지 않고 가제로 적혀있는데 제목만 정하시면 되겠군요! 
어떤 제목이 어울릴까 생각해봤는데요! 저도 하루 의견과 비슷하게 마지막 문장이 인상적이었어서 `우테코 한 달 생활기 - 나의 성장기` 식으로 부제를 붙여주는 것도 괜찮지 않을까 싶어서 의견 남겨봅니다 ㅎㅎ 
제목은 수정될 거라 생각하고 Approve 하겠습니다!

2021-03-28 04:30 UTC, thisisyoungbin approved these changes
에드 안녕하세요~~! 피드백 반영되어 수정된 부분들 잘 읽어봤어요!
다시 읽어봐도 에드의 생각과 감정이 솔직하게 정리되어 있어 참 많이 공감했어요ㅎㅎ
아직 제목이 확정되지 않고 가제로 적혀있는데 제목만 정하시면 되겠군요!
어떤 제목이 어울릴까 생각해봤는데요! 저도 하루 의견과 비슷하게 마지막 문장이 인상적이었어서 우테코 한 달 생활기 - 나의 성장기 식으로 부제를 붙여주는 것도 괜찮지 않을까 싶어서 의견 남겨봅니다 ㅎㅎ
제목은 수정될 거라 생각하고 Approve 하겠습니다!

2021-03-28 04:44 UTC, sjpark-dev commented
하루, 욘! 제목 아이디어 감사합니다. 😊
하루 의견대로 마지막 문장에 초점을 두면서, 욘의 의견대로 부제로 붙여봤어요.
너무 마음에 드네요. 👍👍👍

2021-03-28 06:43 UTC, Rok93 approved these changes
에드 !! 수정한 글 다시 한번 전체적으로 읽어봤는데, 다른 크루들이 좋은 피드백은 많이 줘서인지?
이전에도 이미 좋은 글이었짐나 더 좋은글이 된 것 같아요! 
피드백 드릴 부분이 딱히 떠오르지 않아서 이제 approve 할 시기가 아닌가 싶습니다!? 
approve 할게요 ㅎㅎ
앞으로의 우테코 생활도 화이팅이에요!

2021-03-28 07:17 UTC, PapimonLikelion approved these changes
글이 너무 좋아졌네요!! 읽으면서 기분좋아지는 글이었어요~
에드의 우테코 생활 응원합니다~
어프루브 할게요~🎁

2021-03-28 10:13 UTC, knae11 approved these changes
약속대로 approve 합니다~😁😁 글에 에드의 성격이 잘 드러나는 것 같다고 생각했어요. 진심이 보이는 글이고, 짧고 간결하게 작성된 글이라 인상 깊었어요!ㅎㅎㅎ

2021-03-28 15:36 UTC, zereight approved these changes

2021-03-28 15:36 UTC, zereight commented
에드~~ Approve했어요. 정말 글 잘쓰시네요!
앞으로도 같이 파이팅해요~

2021-04-06 04:11 UTC, wmakerjun commented
마지막 문단을 읽고 빛나는 에드의 모습을 상상하게 됐어요.
남은 우테코 기간 점차 빛나고 자신감 가질 수 있는 에드의 모습을 응원합니다!

2021-04-06 04:12 UTC, merged