[레벨 1 글쓰기 미션] 마크(김병화) 미션 제출합니다.
woowacourse/woowa-writing-3 pull request #48
Opened 2021-03-26 09:24 UTC by binghe819

### [여기](https://github.com/binghe819/woowa-writing-3/blob/binghe819/level01.md)로 가면 편하게 읽으실 수 있어요!

안녕하세요!! 마크에요! 

우테코에 들어와서 크게 다가왔던 두 가지에 대해서 적어봤어요 :)

글을 많이 써보질 않아서 전체적으로 엉망인 것 같네요..ㅎ

편하게 피드백 남겨주세요~  신세한탄, 다니, 디토, 루트, 멍토

#### PR 늦어서 죄송해요!!ㅠ

2021-03-26 15:35 UTC, da-nyee commented on level01.md
> +대부분의 사람은 교실에 앉아서 선생님의 말씀이 곧 진리라고 생각해본 경험이 있을 것이다. 왜냐하면 대부분의 시험의 정답이 하나이고 선생님이 정답을 알려주기 때문이다. 그래서 많은 사람은 어릴 때부터 습관적으로 '정답을 추구하는 것'에 익숙해져 있다고 생각한다. 적어도 나는 그랬다.
생각해본 👉 생각해 본 이 맞는 띄어쓰기입니다!

2021-03-26 16:08 UTC, da-nyee requested changes
안녕하세요 마크! 반갑습니다 ✨
글쓰기 미션 리뷰를 함께할 다니입니다 🙌

마크의 글 잘 읽었습니다!
지금까지 우테코에서 생활하며 개발에 대한 마크의 생각이 변화하는 모습이 인상 깊었습니다!

몇 가지 피드백을 달았는데요,
제 관점에서 이렇게 작성하면 문장이 더 자연스러워지지 않을까? 라는 생각으로 남겼습니다!

피드백은 어디까지나 주관적인 것이니까 전부 반영할 필요는 없을 거 같아요!
납득 가능한 선에서 수정해주시면 감사하겠습니다 ㅎㅎ

앞으로 잘 지내봅시다~! 남은 기간 동안 함께 열심히 달려봐요 🔥

2021-03-26 16:08 UTC, da-nyee commented on level01.md
> +대부분의 사람은 교실에 앉아서 선생님의 말씀이 곧 진리라고 생각해본 경험이 있을 것이다. 왜냐하면 대부분의 시험의 정답이 하나이고 선생님이 정답을 알려주기 때문이다. 그래서 많은 사람은 어릴 때부터 습관적으로 '정답을 추구하는 것'에 익숙해져 있다고 생각한다. 적어도 나는 그랬다.
```suggestion
대부분의 사람은 교실에 앉아서 선생님의 말씀이 곧 진리라고 생각해 본 경험이 있을 것이다. 왜냐하면 대부분 시험의 정답은 하나이고 선생님이 정답을 알려주기 때문이다. 그래서 많은 사람들은 어릴 때부터 습관적으로 '정답을 추구하는 것'에 익숙해져 있다고 생각한다. 적어도 나는 그랬다.
```

2021-03-26 16:08 UTC, da-nyee commented on level01.md
> +우테코에 오기 전에 공부 할 때도 정답을 추구했었다. 나만의 코드를 작성하기보다는 정답을 찾듯 구글과 책에 나와 있는 코드를 그대로 사용했었다. 또한, 책이나 강연에서 어떤 패러다임이 좋다고 하면 왜 좋은지도 생각하지 않고 무작정 좋다고 생각하고 사용했다.
```suggestion
우테코를 시작하기 전에 공부 할 때도 정답을 추구했었다. 나만의 코드를 작성하기보다는 정답을 찾듯 구글과 책에 나와 있는 코드를 그대로 사용했다. 또한, 책이나 강연에서 어떤 패러다임이 좋다고 하면 왜 좋은지도 생각하지 않고 무작정 좋다고 생각하고 사용했다.
```

2021-03-26 16:08 UTC, da-nyee commented on level01.md
> +우테코에 들어와서 나의 기존 공부 방식이 좋지 않다고 바로 느낄 수 있었다.
```suggestion
우테코에 들어와서 나의 기존 공부 방식이 좋지 않다고 바로 느끼게 됐다.
```

2021-03-26 16:08 UTC, da-nyee commented on level01.md
> +대표적으로 각 객체의 역할과 책임을 모두 다르게 생각하고 구현한다. 또한, 어떤 크루의 코드는 가독성이 좋지만 확장하기 안 좋아 보였고, 어떤 크루의 코드는 가독성이 비교적 좋지 않지만 확장하기에 좋아 보였다. 처음엔 확장성이 좋은 코드가 좋다고 느꼈지만, 크루마다 자신의 확고한 이유를 들어보니 그것도 맞다는 생각이 들었다.
```suggestion
대표적으로 각 객체의 역할과 책임을 모두 다르게 생각하고 구현한다. 어떤 크루의 코드는 가독성이 좋지만 확장하기 좋지 않아 보였고, 어떤 크루의 코드는 가독성이 비교적 좋지 않지만 확장하기에 좋아 보였다. 처음에는 확장성이 좋은 게 좋은 코드라고 느꼈지만, 크루마다 자신의 확고한 이유를 들어보니 그것도 맞다는 생각이 들었다.
```

2021-03-26 16:08 UTC, da-nyee commented on level01.md
> +대표적으로 각 객체의 역할과 책임을 모두 다르게 생각하고 구현한다. 또한, 어떤 크루의 코드는 가독성이 좋지만 확장하기 안 좋아 보였고, 어떤 크루의 코드는 가독성이 비교적 좋지 않지만 확장하기에 좋아 보였다. 처음엔 확장성이 좋은 코드가 좋다고 느꼈지만, 크루마다 자신의 확고한 이유를 들어보니 그것도 맞다는 생각이 들었다.
마지막 문장에 `크루마다 자신의 확고한 이유를 들어보니 그것도 맞다는 생각이 들었다.` 이 부분에서 `그것`이 뭔지 명확하게 명시해주시면 더 좋을 것 같습니다!

2021-03-26 16:08 UTC, da-nyee commented on level01.md
> +이후로 정답을 찾는 습관을 버리고, 여러 개념을 받아들여 명확한 이유를 바탕으로 적절한 코드를 작성해야겠다는 다짐을 하게 되었다.
`명확한 이유`가 두 번 중복해서 나타나는데, 아래 문장에서 이를 대체할 만한 다른 단어가 없을까요? 👀

2021-03-26 16:08 UTC, da-nyee commented on level01.md
> +#### 객관적인 나를 보지 못하였다
```suggestion
#### 객관적인 나를 보지 못했다
```

2021-03-26 16:08 UTC, da-nyee commented on level01.md
> +하지만 자신이 어떤 평가를 받는지 타인에게 물어본다면 아마 대부분이 긍정적인 대답만 돌아온다.
```suggestion
자신이 어떤 평가를 받는지 타인에게 물어본다면, 아마 대부분의 사람들은 긍정적인 대답만 받을 것이다. 
```

2021-03-26 16:08 UTC, da-nyee commented on level01.md
> +나 역시도 우테코 이전에 여러 명과 팀 프로젝트를 진행해도 부정적인 대답을 직설적으로 받지 못하였다. 결국 나 자신을 객관적으로 돌아본 적이 없었다.
```suggestion
나 또한 우테코 이전에 여러 명과 팀 프로젝트를 진행해도 부정적인 평가를 직접적으로 받지 못했다. 결국 나 자신을 객관적으로 돌아본 적이 없었다.
```

2021-03-26 16:08 UTC, da-nyee commented on level01.md
> +우테코에서는 페어 프로그래밍이라는 개발 방식을 적극 추천한다. 페어 프로그래밍은 한 컴퓨터로 하나의 프로그램을 두 명이 앉아 번갈아 가며 코딩을 하는 개발 방법이다.
```suggestion
우테코에서는 페어 프로그래밍이라는 개발 방식을 적극 활용한다. 페어 프로그래밍은 한 컴퓨터로 하나의 프로그램을 두 명이 앉아 번갈아 가며 코딩을 하는 개발 방법이다.
```

2021-03-26 16:08 UTC, da-nyee commented on level01.md
> +당연히 사람마다 개발 방법, 생활 패턴, 설계 기준에서 지향하는 점이 다르기 때문에 충돌이 자주 발생하게 된다.
```suggestion
당연히 사람마다 개발 방법, 생활 패턴, 설계 기준에서 지향하는 점이 다르기 때문에 페어 사이의 충돌이 자주 발생하게 된다. 
```

2021-03-26 16:08 UTC, da-nyee commented on level01.md
> +오랜 충돌 끝에 페어가 끝나고 피드백을 남기는 회고를 하면 타인이 바라보는 자신을 조금은 알 수 있었다. 페어를 하며 좋았던 점과 나빴던 점을 알 수 있었기 때문이다.
```suggestion
이런 충돌 속에서 페어가 끝나고 피드백을 남기는 회고를 할 때는 타인이 바라보는 자신을 조금은 알 수 있었다. 페어를 하며 좋았던 점과 나빴던 점을 되돌아볼 수 있었기 때문이다.
```

2021-03-26 16:08 UTC, da-nyee commented on level01.md
> +레벨1이 시작되자마자 객체지향 설계 책을 많이 읽었다. 그래서 프로그램의 구조를 잡는 것에 많은 자신이 있었고, 페어와 구조를 설계할 때 나의 생각을 마구마구 쏟아냈다. 그러다보니 페어에 대한 생각은 잘 듣지도 않았고, 나의 생각을 고수하기 바빴다. 그러다보니 서로 성장한다는 느낌을 받지 못했다.
```suggestion
레벨 1이 시작되자마자 객체지향 설계 책을 많이 읽었다. 그래서 프로그램의 구조를 잡는 것에 많은 자신이 있었고, 페어와 구조를 설계할 때 나의 생각을 마구마구 쏟아냈다. 그러다보니 페어의 생각은 잘 듣지 않았고, 나의 생각을 고수하기 바빴다. 그러다보니 서로 성장한다는 느낌을 받기 어려웠다.
```

2021-03-26 16:08 UTC, da-nyee commented on level01.md
> +페어 프로그래밍의 취지 자체가 상대방과 소통을 하면서 같이 성장을하는 것인데, 나는 반대로 실행하고 있던 것이다. 또한, 나의 부족함을 발견할 수 있었다. 큰 반성을 하게 되었고, 앞으론 기술 뿐만 아니라 사람으로서의 성장과 소프트 스킬을 증진시켜야겠다는 생각을 하게 되었다.
```suggestion
페어 프로그래밍의 취지 자체가 상대방과 소통을 하면서 같이 성장을하는 것인데, 나는 반대로 실행하고 있었다. 한편, 나의 부족함을 발견할 수 있었다. 큰 반성을 하게 되었고, 앞으로는 기술 뿐만 아니라 사람으로서의 성장과 소프트 스킬을 증진시켜야겠다는 생각을 하게 됐다.
```

2021-03-27 05:27 UTC, daum7766 commented on level01.md
> +대부분의 사람은 교실에 앉아서 선생님의 말씀이 곧 진리라고 생각해본 경험이 있을 것이다. 왜냐하면 대부분의 시험의 정답이 하나이고 선생님이 정답을 알려주기 때문이다. 그래서 많은 사람은 어릴 때부터 습관적으로 '정답을 추구하는 것'에 익숙해져 있다고 생각한다. 적어도 나는 그랬다.
많이 공감되네요!

2021-03-27 05:27 UTC, daum7766 commented on level01.md
> +* 정답은 없습니다. 자신만의 기준을 세우세요!
해당 말을 듣고 바로 느끼기는 힘들다는 생각이 들었어요
어떠한 경험을 통해서 느끼게 되었다. 로 문맥을 구성해보는 것은 어떨까요?

2021-03-27 06:52 UTC, daum7766 approved these changes
안녕하세요 마크! 멍토입니다.
다니가 피드백을 너무 잘 달아줘서 제가 할 피드백이 없네요!
저는 피드백 하나로 끝내겠습니다.
수고하셨어요!

2021-03-27 06:53 UTC, dudtjr913 reviewed
안녕하세요. 디토입니다! 글 잘 읽었습니다.😍😍
이미 다른 크루들이 피드백을 많이 남겨서 피드백할게 많지 않네요. 저는 과거형으로 쓰인 문장에 대해 피드백을 남겼습니다!
저의 의견일 뿐이니 꼭 수정하지 않으셔도 됩니다~

수고하셨어요!!👍👍

2021-03-27 06:53 UTC, dudtjr913 commented on level01.md
> +우테코에 오기 전에 공부 할 때도 정답을 추구했었다. 나만의 코드를 작성하기보다는 정답을 찾듯 구글과 책에 나와 있는 코드를 그대로 사용했었다. 또한, 책이나 강연에서 어떤 패러다임이 좋다고 하면 왜 좋은지도 생각하지 않고 무작정 좋다고 생각하고 사용했다.
```suggestion
우테코에 오기 전에 공부할 때도 정답을 추구했었다. 나만의 코드를 작성하기보다는 정답을 찾듯 구글과 책에 나와 있는 코드를 그대로 사용했었다. 또한, 책이나 강연에서 어떤 패러다임이 좋다고 하면 왜 좋은지도 생각하지 않고 무작정 좋다고 생각하고 사용했다.
```

2021-03-27 06:53 UTC, dudtjr913 commented on level01.md
> +오랜 충돌 끝에 페어가 끝나고 피드백을 남기는 회고를 하면 타인이 바라보는 자신을 조금은 알 수 있었다. 페어를 하며 좋았던 점과 나빴던 점을 알 수 있었기 때문이다.
```suggestion
오랜 충돌 끝에 페어가 끝나고 피드백을 남기는 회고를 하면 타인이 바라보는 자신을 조금은 알 수 있다. 페어를 하며 좋았던 점과 나빴던 점을 알 수 있기 때문이다.
```

2021-03-27 06:53 UTC, dudtjr913 commented on level01.md
> +이 과정을 반복하다보니 내가 고쳐야 할 문제점을 발견할 수 있었다.
```suggestion
이 과정을 반복하다보니 내가 고쳐야 할 문제점을 발견했다. 
```

2021-03-27 06:53 UTC, dudtjr913 commented on level01.md
> +페어 프로그래밍의 취지 자체가 상대방과 소통을 하면서 같이 성장을하는 것인데, 나는 반대로 실행하고 있던 것이다. 또한, 나의 부족함을 발견할 수 있었다. 큰 반성을 하게 되었고, 앞으론 기술 뿐만 아니라 사람으로서의 성장과 소프트 스킬을 증진시켜야겠다는 생각을 하게 되었다.
저는 마크와 반대로 초반에 제 의견 없이 페어에 맞추기만 했었는데 결국 느끼는 것은 똑같네요!
`페어 프로그래밍의 취지 자체가 상대방과 소통을 하면서 같이 성장을하는 것인데`
`앞으론 기술 뿐만 아니라 사람으로서의 성장과 소프트 스킬을 증진시켜야겠다는 생각을 하게 되었다.`
이 부분에서 공감이 많이 되었습니다.👍👍

2021-03-27 06:53 UTC, dudtjr913 commented on level01.md
> +이렇듯 정답보다는 자신의 명확한 이유를 바탕으로 적절한 처리가 더 중요하다고 느끼게 되었다.
정말 저와 느낀 것이 똑같네요! 저도 프로그래밍에서는 자신만의 명확한 이유가 있는 것이 정답이라고 생각합니다.😍😍

2021-03-27 12:34 UTC, Junroot requested changes
안녕하세요 루트입니다!! 늦어서 죄송해요 ㅠㅠㅠ
간단한 띄어쓰기 몇 개만 수정하면 될것같네요!!

2021-03-27 12:34 UTC, Junroot commented on level01.md
> +사람들은 보통 외모, 성격 특성, 습관 등을 통해 타인을 평가한다.
```suggestion
사람들은 보통 외모, 성격, 특성, 습관 등을 통해 타인을 평가한다. 
```

2021-03-27 12:34 UTC, Junroot commented on level01.md
> +우테코에서는 페어 프로그래밍이라는 개발 방식을 적극 추천한다. 페어 프로그래밍은 한 컴퓨터로 하나의 프로그램을 두 명이 앉아 번갈아 가며 코딩을 하는 개발 방법이다.
```suggestion
우테코에서는 페어 프로그래밍이라는 개발 방식을 적극적으로 추천한다. 페어 프로그래밍은 한 컴퓨터로 하나의 프로그램을 두 명이 앉아 번갈아 가며 코딩을 하는 개발 방법이다.
```
말할 때 자주 사용하지만, 적극(명사) + 추천(명사) 형태이므로 어색하게 느껴질 수도 있다고 생각해요.

2021-03-27 12:34 UTC, Junroot commented on level01.md
> +당연히 사람마다 개발 방법, 생활 패턴, 설계 기준에서 지향하는 점이 다르기 때문에 충돌이 자주 발생하게 된다.
```suggestion
당연히 사람마다 개발 방법, 생활 패턴, 설계 기준에서 지향하는 점이 다르므로 충돌이 자주 발생하게 된다. 
```
같은 의미면 짧은 단어를 사용하는 것이 이해하기 쉽다고 생각해요!

2021-03-27 12:34 UTC, Junroot commented on level01.md
> +이 과정을 반복하다보니 내가 고쳐야 할 문제점을 발견할 수 있었다.
```suggestion
이 과정을 반복하다 보니 내가 고쳐야 할 문제점을 발견할 수 있었다. 
```

2021-03-27 12:34 UTC, Junroot commented on level01.md
> +레벨1이 시작되자마자 객체지향 설계 책을 많이 읽었다. 그래서 프로그램의 구조를 잡는 것에 많은 자신이 있었고, 페어와 구조를 설계할 때 나의 생각을 마구마구 쏟아냈다. 그러다보니 페어에 대한 생각은 잘 듣지도 않았고, 나의 생각을 고수하기 바빴다. 그러다보니 서로 성장한다는 느낌을 받지 못했다.
```suggestion
레벨1이 시작되자마자 객체지향 설계 책을 많이 읽었다. 그래서 프로그램의 구조를 잡는 것에 많은 자신이 있었고, 페어와 구조를 설계할 때 내 생각을 마구마구 쏟아냈다. 그러다보니 페어에 대한 생각은 잘 듣지도 않았고, 내 생각을 고수하기 바빴다. 그러다보니 서로 성장한다는 느낌을 받지 못했다.
```

2021-03-27 12:34 UTC, Junroot commented on level01.md
> +레벨1이 시작되자마자 객체지향 설계 책을 많이 읽었다. 그래서 프로그램의 구조를 잡는 것에 많은 자신이 있었고, 페어와 구조를 설계할 때 나의 생각을 마구마구 쏟아냈다. 그러다보니 페어에 대한 생각은 잘 듣지도 않았고, 나의 생각을 고수하기 바빴다. 그러다보니 서로 성장한다는 느낌을 받지 못했다.
```suggestion
레벨1이 시작되자마자 객체지향 설계 책을 많이 읽었다. 그래서 프로그램의 구조를 잡는 것에 많은 자신이 있었고, 페어와 구조를 설계할 때 나의 생각을 마구마구 쏟아냈다. 그러다 보니 페어에 대한 생각은 잘 듣지도 않았고, 나의 생각을 고수하기 바빴다. 그러다보니 서로 성장한다는 느낌을 받지 못했다.
```
마지막 문단에 띄어쓰기 오류가 조금 있네요! 글 작성하고 나서 맞춤법 검사기를 돌려보는 것을 추천드려요!!

2021-03-27 13:58 UTC, shinsehantan reviewed
안녕하세요 마크:) 신세한탄입니다.
이미 다른 분들이 리뷰를 많이 남겨주셔서 제가 추가로 남길 게 많지 않네요!

저는 아직 저만의 기준을 세우고 코드를 작성하고 있지 못하고
이리저리 휘둘리고 있는 것 같아 글 읽으면서 반성을 하게 됐습니다.ㅎㅎㅎ

좋은 글 감사합니다 :)

2021-03-27 13:58 UTC, shinsehantan commented on level01.md
> +이후로 정답을 찾는 습관을 버리고, 여러 개념을 받아들여 명확한 이유를 바탕으로 적절한 코드를 작성해야겠다는 다짐을 하게 되었다.
먼저 남겨주신 분이 계시네요! `명확한 이유를 바탕으로 적절한 처리`, `명확한 이유를 바탕으로 적절한 코드`가 반복되기도 하지만, '적절한 처리'와 '적절한 코드'라는 표현이 조금 포괄적이고 모호한 것 같아 더 자세하게 적어주셔도 좋지 않을까 싶습니다 🙃

2021-03-27 13:58 UTC, shinsehantan commented on level01.md
> +
`번갈아 가며`는 `번갈아가며`로 붙여서 써주시면 될 것 같아요 :)

2021-03-28 10:12 UTC, shinsehantan approved these changes
피드백 반영 확인했습니다 :) 
여러 피드백이 반영되어 훨씬 읽기 매끄러운 글이 된 것 같네요!
레벨 1 남은 미션도 화이팅하세요! 다음 글쓰기 미션 때 또 구경올게요 ㅎㅎㅎ

2021-03-28 10:28 UTC, dudtjr913 approved these changes
더이상 피드백드릴 것이 없네요! 
우테코에서 생활하면서 느낀 것들이 저와 비슷한 것 같아서 공감이 많이 되었어요.

`우테코에서 미션을 진행하며 내가 생각한 정답 같은 코드가 상황에 따라선 정답이 아닐 수도 있다는 것을 깨닫게 되었다.` 이 부분에서 공감이 많이 된 것 같아요!

이제 곧 방학인데 푹 쉬고 레벨 2때 열심히 달려요!!😍😍

2021-03-28 17:18 UTC, binghe819 commented
> 피드백 반영 확인했습니다 :)
> 여러 피드백이 반영되어 훨씬 읽기 매끄러운 글이 된 것 같네요!
> 레벨 1 남은 미션도 화이팅하세요! 다음 글쓰기 미션 때 또 구경올게요 ㅎㅎㅎ

2021-03-29 04:26 UTC, Junroot approved these changes
피드백 전부 반영 해주셨네요! 이번 글쓰기는 여기서 마무리하도록 하겠습니다! 저랑 비슷한 경험을 하신 것 같아서 공감이 많이됐어요! 아직 접점이 없어서 직접 이야기를 나눠본 적이 없지만 좀더 이야기 해보고싶다는 느낌을 받았습니다! 전체적으로 글이 깔끔해서 읽는데 불편함이 없었습니다! 수고하셨어요!!

2021-03-29 04:48 UTC, da-nyee approved these changes
안녕하세요 마크!
피드백 전부 반영해주신 거 확인 완료했습니다 👏

루터에서 지나다니면서 얼굴은 몇 번 뵌 것 같은데, 아직 같이 말해본 적이 없네요!
다음에 뵈면 인사할게요 ㅎㅎㅎ 글쓰기 미션은 여기서 Approve 하겠습니다!

수고하셨습니다 👍✨

2021-05-30 10:31 UTC, closed without merging