[레벨 1 글쓰기 미션] 하루(김하루) 미션 제출합니다.
woowacourse/woowa-writing-3 pull request #5
Opened 2021-03-15 03:20 UTC by 365kim

### 레벨 1 글쓰기 미션<br><br>[우아한테크코스 한 달 생활기](https://github.com/365kim/woowa-writing-3/blob/365kim/level1.md)

<br>

✨리뷰어님들을 모셔봅니다✨

에드 (@sjpark-dev)
배럴 (@knae11)
조엘 (@PapimonLikelion)
로키 (@Rok93)
욘 (@thisisyoungbin)
도비 (@zereight)

<br>

저만 들려드릴 수 있는 이야기가 무엇일까 고민하면서 글을 작성해봤습니당!
리뷰어님들 잘 부탁드립니다 🙋🏻‍♀️

2021-03-15 06:00 UTC, sjpark-dev requested changes
블로그를 꾸준히 작성하셔서 그런지 글을 굉장히 잘 쓰신다는 인상을 받았습니다.
한가지 개선할 만한 점을 코멘트 달아 놓기는 했지만 꼭 고칠 필요는 없어 보입니다. 😊

2021-03-15 06:00 UTC, sjpark-dev commented on level1.md
> +코로나 여파로 집에만 있어서 바뀐 이름이 불릴 일이 많이 없었다. 우테코 시작 전에 문의해보니 본명으로 닉네임을 사용해도 된다는 답변을 받았다. 그래서 바꾼 이름인 '하루'를 닉네임으로 사용하게 되었다. 줌으로 하는 데일리 미팅이나, 슬랙 메신저에도 항상 '하루'라는 사용자 이름이 따라붙고, 코치님, 크루들, 리뷰어님까지 모두 나를 당연하게도 '하루'라고
문단의 흐름을
이름을 바꾼 사실 -> 이름을 바꾼 이유 -> 새로운 이름의 체험기
로 논리적으로 구성해서 아주 읽기 편했습니다. 👍

2021-03-15 06:00 UTC, sjpark-dev commented on level1.md
> +그래도 레벨 1을 진행하면서 10개가 넘는 글을 작성했다는 점은 스스로 칭찬해주고 싶다. 작성한 글을 크루들에게 소개한 날에는 조회수가 폭발하기도 했다. _(FE크루들 영업 당해줘서 고마워요.)_ 나의 글이 누군가에게 도움이 되고 피드백을 받는 경험은 이전에 느껴보지 못한 성취감과 만족감을 가져다주었다. 최근에는 감사하게도 리뷰어분들 중 한 분께서 내 블
내가 쓴 글을 누군가 읽어주고 공유해준다면 정말 블로그 할맛 나겠네요! 👍
개인적으로 이 문단에서 하루의 행복한 감정을 느낄 수 있어서 좋았습니다. 😊

2021-03-15 06:00 UTC, sjpark-dev commented on level1.md
> +앞서 말한 것처럼 나는 '열심히, 즐겁게 일할 수 있는 환경'이라는 나의 최대 목표를 이미 이루었다. 하지만 우테코는 영원한 과정이 아니다. 그렇기에 나는 다음에도 이런 조직의 구성원이 되기 위해 계속해서 부단히 노력해야 한다. 내가 지향하는 조직에서 기꺼이 나를 받아줄 수 있도록 앞으로 더 열심히 나를 단련시켜 나갈 것이다.
판타지를 이어가고자 미래까지 생각하시는 모습이 멋지네요! 👍

2021-03-15 06:00 UTC, sjpark-dev commented on level1.md
> +나는 사실 최근에 실제 이름을 바꾸었다. 원래는 평범한 한자 이름이었다. 사전에 가족들의 동의를 얻긴 했지만 이름을 바꾼 것은 온전히 나의 선택이었다. 꽤 오래전부터 이름을 바꾸고 싶은 마음은 있었는데, 그와 별개로 이름에 담고 싶었던 나의 뜻 또는 의지가 있었다.
'나' 혹은 '저' 로 시작하는 문장은 되도록이면 지양하는게 어떨까요? 🤔

2021-03-15 08:21 UTC, 365kim commented on level1.md
> +코로나 여파로 집에만 있어서 바뀐 이름이 불릴 일이 많이 없었다. 우테코 시작 전에 문의해보니 본명으로 닉네임을 사용해도 된다는 답변을 받았다. 그래서 바꾼 이름인 '하루'를 닉네임으로 사용하게 되었다. 줌으로 하는 데일리 미팅이나, 슬랙 메신저에도 항상 '하루'라는 사용자 이름이 따라붙고, 코치님, 크루들, 리뷰어님까지 모두 나를 당연하게도 '하루'라고
와,,, 상세한 피드백 감사해요 에드 😄😄😄

2021-03-15 08:26 UTC, 365kim commented on level1.md
> +나는 사실 최근에 실제 이름을 바꾸었다. 원래는 평범한 한자 이름이었다. 사전에 가족들의 동의를 얻긴 했지만 이름을 바꾼 것은 온전히 나의 선택이었다. 꽤 오래전부터 이름을 바꾸고 싶은 마음은 있었는데, 그와 별개로 이름에 담고 싶었던 나의 뜻 또는 의지가 있었다.
으헉 첫 문장부터 요구사항에 나와있는 것을 못지켰네요,,,🥲 짚어주셔서 감사합니다 에드! 어떻게 수정하면 좋을지는 조금 더 고민해보겠습니다...!

2021-03-15 08:52 UTC, 365kim commented on level1.md
> +나는 사실 최근에 실제 이름을 바꾸었다. 원래는 평범한 한자 이름이었다. 사전에 가족들의 동의를 얻긴 했지만 이름을 바꾼 것은 온전히 나의 선택이었다. 꽤 오래전부터 이름을 바꾸고 싶은 마음은 있었는데, 그와 별개로 이름에 담고 싶었던 나의 뜻 또는 의지가 있었다.
문장 첫 부분 어순만 변경해 보았습니다...! 처음에는 바로 뒷 문장과 합쳐서 새로운 주어를 만드는 방법을 생각해 보았는데요, 합치면 도입부의 짧은 호흡을 잃게 되어서 결국 문장은 그대로 두었습니다. 단순히 어순만 변경했지만 '사실 ~'로 시작하는 문장이 '나는 ~'으로 시작하는 문장보다 덜 지루하게 느껴지고 나아졌다고 생각하고 커밋했습니다...!

2021-03-15 09:35 UTC, zereight reviewed
하루~~ 사실 리뷰달게 없어서 그냥 제 뇌피셜로 리뷰를 달아봤어요.
리뷰받은걸로 기분나빠하시면 안되는거 아시죠? >_<

2021-03-15 09:35 UTC, zereight commented on level1.md
> +코로나 여파로 집에만 있어서 바뀐 이름이 불릴 일이 많이 없었다. 우테코 시작 전에 문의해보니 본명을 닉네임으로 정해도 된다는 답변을 받았다. 그래서 바꾼 이름인 '하루'를 닉네임으로 사용하게 되었다. 줌으로 하는 데일리 미팅이나, 슬랙 메신저에도 항상 '하루'라는 사용자 이름이 따라붙고, 코치님, 크루들, 리뷰어님까지 모두 나를 당연하게도 '하루'라고
닉네임을 본명으로 정한 것이 왜 잘한 결정이었나요? 궁금해요!

2021-03-15 09:35 UTC, zereight commented on level1.md
> +작년 12월 프리코스를 진행하면서 처음 블로그를 만들었다. 느낀 점과 배운 점을 기록해두고 싶어서 만들긴 했는데, 당시에 내 글을 불특정 다수에게 공개할 용기는 없었다. 그래서 나만 볼 수 있도록 비공개로 설정해놓고 프리코스 후기를 작성했다. 순수하게 '저장소' 역할만 하는 블로그였다. 그러다 올해 1월 말, 알 수 없는 용기가 생겨 블로그를 다시 단장하
알 수 없는 용기가 생긴 후에 블로그 글을 공개로 설정했다는 뜻인가요? 아니면 디자인과 포스팅 주제를 바꿨다는 것인가요!
문맥상으론 비공개였다가 용기가 생겨서 공개로 전환했다는 뜻 같은데 맞나요?!

2021-03-15 09:35 UTC, zereight commented on level1.md
> +흔히 말하는 대학 과제의 팀플을 떠올려보면, 팀에 속한 '모두'가 열심히 한다는 것이 얼마나 비현실적인 이야기인지 알 수 있다. 그런데 그 비현실적인 일이 우테코에서는 벌어지고 있다. 그런 점에서 우테코는 현실보다 판타지에 가깝다고 표현하고 싶다. 주변 사람들이 물으면 나는 우테코에서의 생활에 200% 만족한다고 대답한다.
`주변 사람들이 물으면 나는 우테코에서의 생활에 200% 만족한다고 대답한다.`는 2번째 문단에 들어가는게 자연스럽지 않나요? 제 생각입니다 ㅎㅎ

2021-03-15 09:35 UTC, zereight commented on level1.md
> +그래도 레벨 1을 진행하면서 10개가 넘는 글을 작성했다는 점은 스스로 칭찬해주고 싶다. 작성한 글을 크루들에게 소개한 날에는 조회수가 폭발하기도 했다. _(FE크루들 영업 당해줘서 고마워요.)_ 나의 글이 누군가에게 도움이 되고 피드백을 받는 경험은 이전에 느껴보지 못한 성취감과 만족감을 가져다주었다. 최근에는 감사하게도 리뷰어분들 중 한 분께서 내 블
`우테코와 함께가 아니었다면` 우테코를 일부러 의인화하신건가요? 궁금해요!
`우테코에 합류하지 않았더라면`, `우테코 과정에 참여하지 못했더라면` 등등이 자연스럽지 않을까용?

2021-03-15 12:54 UTC, 365kim commented on level1.md
> +코로나 여파로 집에만 있어서 바뀐 이름이 불릴 일이 많이 없었다. 우테코 시작 전에 문의해보니 본명을 닉네임으로 정해도 된다는 답변을 받았다. 그래서 바꾼 이름인 '하루'를 닉네임으로 사용하게 되었다. 줌으로 하는 데일리 미팅이나, 슬랙 메신저에도 항상 '하루'라는 사용자 이름이 따라붙고, 코치님, 크루들, 리뷰어님까지 모두 나를 당연하게도 '하루'라고
새 이름에 빨리 적응할 수 있어서요! 무의식중에 옛날 이름을 쓸 때가 있었거든요. 닉네임 '하루'로 생활한지 한 달이 지난 지금은 바뀐 본명에 완벽 적응했습니다! ㅎㅎㅎ

2021-03-15 12:57 UTC, 365kim commented on level1.md
> +작년 12월 프리코스를 진행하면서 처음 블로그를 만들었다. 느낀 점과 배운 점을 기록해두고 싶어서 만들긴 했는데, 당시에 내 글을 불특정 다수에게 공개할 용기는 없었다. 그래서 나만 볼 수 있도록 비공개로 설정해놓고 프리코스 후기를 작성했다. 순수하게 '저장소' 역할만 하는 블로그였다. 그러다 올해 1월 말, 알 수 없는 용기가 생겨 블로그를 다시 단장하
CSS디자인도 새로 하고 비공개에서 공개로 돌리기도 했어요! 내용 전달이 조금 더 명확하도록 수정했습니당. 좋은 피드백 감사해용 :D

2021-03-15 13:01 UTC, PapimonLikelion reviewed
안녕하세요 하루! 백엔드 크루 조엘이라고 합니다!
한달 생활기 공유해 주셔서 감사해요!

하루의 글을 읽고 우테코가 판타지 같은 환경이었음을 한 번더 깨달았네요. 
감사함을 느끼게 된 글이었어요 :) 
제가 커멘트로 남긴 부분은 그저 제 의견이니, 무엇보다 중요한 하루의 색깔을 유지하시면서 글 써주세요! 

잘 읽었습니다!

2021-03-15 13:01 UTC, joelonsw commented on level1.md
> +
'나'라는 말을 줄여보라는 요구사항이 있어서요! 

사실 저에겐 하루의 글이 전혀 어색하게 읽히지 않는데, 요구사항 때문에 한 번 말씀드렸어요!!

2021-03-15 13:01 UTC, joelonsw commented on level1.md
> +작년 12월 프리코스를 진행하면서 처음 블로그를 만들었다. 느낀 점과 배운 점을 기록해두고 싶어서 만들긴 했는데, 당시에 내 글을 불특정 다수에게 공개할 용기는 없었다. 그래서 나만 볼 수 있도록 비공개로 설정해놓고 프리코스 후기를 작성했다. 순수하게 '저장소' 역할만 하는 블로그였다. 그러다 올해 1월 말, 알 수 없는 용기가 생겨 블로그를 다시 단장하
문장을 짧게 가져가 보는 것은 어떨까요? 
아래는 예시에요! 지금도 좋습니다! 하나의 제안일 뿐이에요 😊

작년 12월 프리코스를 진행하면서 처음 블로그를 만들었다. 
느낀 점과 배운 점을 기록해두고 싶어서 만들었던 블로그이다.
하지만 당시에 내 글을 불특정 다수에게 공개할 용기는 없었다. 
그래서 나만 볼 수 있도록 비공개로 설정해놓고 프리코스 후기를 작성했다. 
순수하게 '저장소' 역할만 하는 블로그였다. 
그러다 올해 1월 말, 알 수 없는 용기가 생겨 블로그를 다시 단장했다.
새 단장한 블로그에 나의 일상, 나의 학습내용을 하나 하나 담아나갔다.

2021-03-15 13:01 UTC, joelonsw commented on level1.md
> +앞서 말한 것처럼 나는 '열심히, 즐겁게 일할 수 있는 환경'이라는 나의 최대 목표를 이미 이루었다. 하지만 우테코는 영원한 과정이 아니다. 그렇기에 나는 다음에도 이런 조직의 구성원이 되기 위해 계속해서 부단히 노력해야 한다. 내가 지향하는 조직에서 기꺼이 나를 받아줄 수 있도록 앞으로 더 열심히 나를 단련시켜 나갈 것이다.
우테코 코치분들이 보면 보람차서 눈물 흘리실 것 같군요 😭
하루의 최대 목표를 이룬 것 너무 축하드려요!

다만 최대 목표를 이미 이루었다라는 문장 바로 뒤에,
부단히 노력해야 한다라는 말이 저는 조금 어색해보여요. _(저는 목표 이루면 부단히 노력안해서 그럴수도 😅)_

'열심히, 즐겁게 일할 수 있는 환경' 에 속하자는 최선의 목표를 이루게되었다. 
이제, 이런 환경에서 지속적으로 일할 수 있는 자신을 만들어 나가는 것이 다음 목표가 되었다. 
와 같은 느낌으로 수정해보는 것도 고려해보실 수 있을 것 같아요!

2021-03-15 13:04 UTC, 365kim commented on level1.md
> +흔히 말하는 대학 과제의 팀플을 떠올려보면, 팀에 속한 '모두'가 열심히 한다는 것이 얼마나 비현실적인 이야기인지 알 수 있다. 그런데 그 비현실적인 일이 우테코에서는 벌어지고 있다. 그런 점에서 우테코는 현실보다 판타지에 가깝다고 표현하고 싶다. 주변 사람들이 물으면 나는 우테코에서의 생활에 200% 만족한다고 대답한다.
앗 저도 고치고 싶던 부분인데 말씀 꺼내주셔서 넘 감사하네용 ☺️☺️ '만족도'에 관해 운을 먼저 띄우고 첫 문단을 마치고 싶었어요! 그런데 지금은 흐름이 어색해 말씀해 주신대로 두 번째 문단에 더 어울리는 문장으로 보이네요...! 첫 문단의 마지막 문장과 두 번째 문단의 첫 번째 문장의 위치는 그대로 유지하고 싶어서, 해당 문장에 접속사만 추가하고 흐름이 조금 더 자연스럽도록 하는 방향으로 수정해보았습니다!

2021-03-15 13:11 UTC, 365kim commented on level1.md
> +그래도 레벨 1을 진행하면서 10개가 넘는 글을 작성했다는 점은 스스로 칭찬해주고 싶다. 작성한 글을 크루들에게 소개한 날에는 조회수가 폭발하기도 했다. _(FE크루들 영업 당해줘서 고마워요.)_ 나의 글이 누군가에게 도움이 되고 피드백을 받는 경험은 이전에 느껴보지 못한 성취감과 만족감을 가져다주었다. 최근에는 감사하게도 리뷰어분들 중 한 분께서 내 블
앗 아니요, 번역투의 어색한 표현을 사용해버렸네요...🥲 비슷한 예로 `OO교육과 함께가 아니었다면`, `OO프로그램과 함께가 아니었다면` 어떤 예시를 들어도 모두 어색하네요...! 추천해주신대로 수정했습니다. 도비 감사합니당!

2021-03-15 13:44 UTC, Rok93 reviewed
하루 글 공유해줘서 고마워요~! 
이름의 의미부터 블로깅을 함으로써 얻은 뿌듯함도, 또 '하루에게 우테코란? '이 잘 드러나는 글인 것 같아요. 
다른 리뷰어들이 워니의 ``글쓰기 규칙``에 대해서는 많이 피드백해준 것 같아서 저는 하루의 글을 맞춤법 검사기로 돌려봤어요! 몇몇 문장이 문맥상 알맞지 않다고 나와서 그 부분 피드백 드렸어요. 👍

2021-03-15 13:44 UTC, Rok93 commented on level1.md
> +사람들은 흔히 시간을 '과거', '현재', '미래' 세 가지로 분류한다. 그리고 저마다 더 중요하다고 생각하는 가중치가 있다. 나는 마음으로는 '현재'가 가장 중요하다고 생각하면서도, 습관적으로 항상 '미래'부터 챙기곤 했다. 지금 이 순간을 놓치고 있다고 생각이 들 때면 환기차원에서 '오늘을 찾아요', '지금이 우리의 전부'와 같은 노래를 찾아 듣곤 했
```suggestion
사람들은 흔히 시간을 '과거', '현재', '미래' 세 가지로 분류한다. 그리고 저마다 더 중요하다고 생각하는 가중치가 있다. 나는 마음으로는 '현재'가 가장 중요하다고 생각하면서도, 습관적으로 항상 '미래'부터 챙기곤 했다. 지금, 이 순간을 놓치고 있다는 생각이 들 때면 환기 차원에서 '오늘을 찾아요', '지금이 우리의 전부'와 같은 노래를 찾아 듣곤 했다. 이 노래들의 가사처럼 '오늘 하루'를 소홀히 하지 않고자 하는 나의 바람을 이름에 담았다.
```

2021-03-15 13:44 UTC, Rok93 commented on level1.md
> +작년 12월 프리코스를 진행하면서 처음 블로그를 만들었다. 느낀 점과 배운 점을 기록해두고 싶어서 만들긴 했는데, 당시에 내 글을 불특정 다수에게 공개할 용기는 없었다. 그래서 나만 볼 수 있도록 비공개로 설정해놓고 프리코스 후기를 작성했다. 순수하게 '저장소' 역할만 하는 블로그였다. 그러다 올해 1월 말, 알 수 없는 용기가 생겨 블로그를 새로 단장해
```suggestion
작년 12월 프리코스를 진행하면서 처음 블로그를 만들었다. 느낀 점과 배운 점을 기록해두고 싶어서 만들긴 했는데, 당시에 내 글을 불특정 다수에게 공개할 용기는 없었다. 그래서 나만 볼 수 있도록 비공개로 설정해놓고 프리코스 후기를 작성했다. 순수하게 '저장소' 역할만 하는 블로그였다. 그러다 올해 1월 말, 알 수 없는 용기가 생겨 블로그를 새로 단장해서 오픈한 후, 나의 일상과 학습 내용을 하나하나 담아나갔다.
```

2021-03-15 13:44 UTC, Rok93 commented on level1.md
> +우테코 과정을 시작한 이후에도 과정에서 배운 내용을 블로그에 틈틈이 포스팅했다. 돌아보니 다루고 싶은 주제를 모두 다루지 못한 점이 아쉬움으로 남는다. 개인적으로 정말 구미가 당기고 더 탐구해서 글로 풀어보고 싶은 주제인데, 생각보다 자료 찾기가 쉽지 않아 포스팅을 포기한 글이 적지 않다. 또, 미션을 진행하면서 시간관리를 잘 못해서, 정리해야겠다는 생각
```suggestion
우테코 과정을 시작한 이후에도 과정에서 배운 내용을 블로그에 틈틈이 포스팅했다. 돌아보니 다루고 싶은 주제를 모두 다루지 못한 점이 아쉬움으로 남는다. 개인적으로 정말 구미가 당기고 더 탐구해서 글로 풀어보고 싶은 주제인데, 생각보다 자료 찾기가 쉽지 않아 포스팅을 포기한 글이 적지 않다. 또, 미션을 진행하면서 시간 관리를 잘 못 해서, 정리해야겠다는 생각으로 제목만 써놓고 아예 건드리지 못한 주제도 많다.
```

2021-03-15 13:44 UTC, Rok93 commented on level1.md
> +그래도 레벨 1을 진행하면서 10개가 넘는 글을 작성했다는 점은 스스로 칭찬해주고 싶다. 작성한 글을 크루들에게 소개한 날에는 조회수가 폭발하기도 했다. _(FE크루들 영업 당해줘서 고마워요.)_ 나의 글이 누군가에게 도움이 되고 피드백을 받는 경험은 이전에 느껴보지 못한 성취감과 만족감을 가져다주었다. 최근에는 감사하게도 리뷰어분들 중 한 분께서 내 블
```suggestion
그래도 레벨 1을 진행하면서 10개가 넘는 글을 작성했다는 점은 스스로 칭찬해주고 싶다. 작성한 글을 크루들에게 소개한 날에는 조회수가 폭발하기도 했다. _(FE크루들 영업 당해줘서 고마워요)_ 나의 글이 누군가에게 도움이 되고 피드백을 받는 경험은 이전에 느껴보지 못한 성취감과 만족감을 가져다주었다. 최근에는 감사하게도 리뷰어분들 중 한 분께서 내 블로그를 SNS에 공유해주셔서 조회수 최대치를 경신하는 즐거운 경험도 할 수 있었다. 우테코 과정에 참여하지 못했다면 이 모든 새로운 경험을 놓쳤을지도 모른다. 즐거운 마음으로 남은 9개월의 여정도 블로그에 차곡차곡 기록해보려고 한다.
```

이 부분은 제 개인적인 의견인데, 괄호안에는 '.' 마침표를 잘 안찍는 것 같더라구요? 
저도 ``(속삭이는 말)`` 많이 쓰는 편인데  늘 마침표 없이 사용하고있어요 : )

2021-03-15 13:44 UTC, Rok93 commented on level1.md
> +조직생활을 하는 사람들은 대개 조직 내 불합리한 의사결정을 경험하며 자괴감을 느낀다. 나도 그런 사람들 중 하나였다. 퇴사를 결심하며 정했던 단 하나의 목표는 '열심히, 즐겁게 일할 수 있는 조직에 속하는 것'이었다. 우테코에 들어온 나는 그 목표를 이미 이룬 셈이다. 때문에 나는 한없이 만족스러울 수 밖에 없다. 합리적이고 배려 넘치는 우테코 시스템을
```suggestion
조직생활을 하는 사람들은 대개 조직 내 불합리한 의사결정을 경험하며 자괴감을 느낀다. 나도 그런 사람 중 하나였다. 퇴사를 결심하며 정했던 단 하나의 목표는 '열심히, 즐겁게 일할 수 있는 조직에 속하는 것'이었다. 우테코에 들어온 나는 그 목표를 이미 이룬 셈이다. 그 때문에 나는 한없이 만족스러울 수 밖에 없다. 합리적이고 배려 넘치는 우테코 시스템을 경험할 때, 그리고 열정적인 크루들과 함께할 때, 나는 말로 다 할 수 없는 만족감을 느낀다. 내가 현재 이 조직에 속해있을 수 있음에, 이 동료들이 나와 함께 해줌에 감사하고 또 감사하다.
```

2021-03-15 13:44 UTC, Rok93 commented on level1.md
> +앞서 말한 것처럼 나는 '열심히, 즐겁게 일할 수 있는 환경'이라는 나의 최대 목표를 이미 이루었다. 하지만 우테코는 영원한 과정이 아니다. 그렇기에 나는 다음에도 이런 조직의 구성원이 되기 위해 계속해서 부단히 노력해야 한다. 내가 지향하는 조직에서 기꺼이 나를 받아줄 수 있도록 앞으로 더 열심히 나를 단련시켜 나갈 것이다.
```suggestion
앞서 말한 것처럼 나는 '열심히, 즐겁게 일할 수 있는 환경'이라는 나의 최대 목표를 이미 이루었다. 하지만 우테코는 영원한 과정이 아니다. 그렇기에 나는 다음에도 이런 조직의 구성원이 되기 위해 계속해서 부단히 노력해야 한다. 내가 지향하는 조직에서 기꺼이 나를 받아줄 수 있도록 앞으로 더 열심히 나를 단련 시켜 나갈 것이다.
```

2021-03-15 13:59 UTC, zereight approved these changes
하루! 제 뇌피셜이었던 의견들을 잘 반영해줘서 감사합니다!
다른 크루분들이 추가적인 리뷰를 잘 달아주시는군요. 👍👍👍
제 의견은 모두 반영되어서 Approve하겠습니다!
그래도 읽어보고 어색한점 찾으면 계속 리뷰 할게요 ㅋㅋ (방심하지 마시길..)
수고하셨습니다. 👏👏👏

2021-03-15 14:32 UTC, 365kim commented on level1.md
> +
저도 '나는'으로 시작하는 문장이 남아있어서 고민했었는데, 요부분은 저도 남겨둬도 괜찮을 것 같아서 남겨둘게용! 🙏

2021-03-15 14:59 UTC, thisisyoungbin reviewed
하루 안녕하세요~~ :) 백엔드 크루 욘입니다 !
레벨 1이 끝날 때 까지 얼굴도 못 뵙고 이렇게 리뷰로 먼저 만나게 돼 아쉽네요 😭 


글 쓰신 거 잘 읽었습니다! 판타지 같다는 부분은 특히 더 공감하면서 읽었네요ㅎㅎ 목표를 이루고, 또 미래의 목표를 위해 학습에 정진하시는 모습도 멋지십니다 👍 


리뷰 드린 부분들은 글을 읽으며 든 지극히 개인적인 생각들인데요. '넌 그렇게 생각했구나~' 정도로만 읽어주시면 될 것 같아요ㅎㅎ 혹시나 도움이 될 부분들이 있다면 다행이구요! 
하루의 생각이 담긴 글 잘 읽었습니다 ❗

2021-03-15 14:59 UTC, thisisyoungbin commented on level1.md
> +사실 나는 최근에 실제 이름을 바꾸었다. 원래는 평범한 한자 이름이었다. 사전에 가족들의 동의를 얻긴 했지만 이름을 바꾼 것은 온전히 나의 선택이었다. 꽤 오래전부터 이름을 바꾸고 싶은 마음은 있었는데, 그와 별개로 이름에 담고 싶었던 나의 뜻 또는 의지가 있었다.
**'나' 혹은 '저' 로 시작하는 문장은 되도록이면 쓰지 않는다.** 이 글쓰기 요구사항에 맞게 바꾼다면 어떻게 써야할까? 생각해봤을 때 
`최근 평범한 한자 이름에서 한글 이름으로 개명을 했다.` 혹은 `최근 평범한 한자 이름에서 순우리말인 '하루'로 개명을 했다`가 생각났어요!


우테코 한 달 생활기와 더불어 '하루'로서 한 달 생활기!! 새로운 환경에서 설레는 한 달을 보내셨겠군요!!! :)

2021-03-15 14:59 UTC, thisisyoungbin commented on level1.md
> +사람들은 흔히 시간을 '과거', '현재', '미래' 세 가지로 분류한다. 그리고 저마다 더 중요하다고 생각하는 가중치가 있다. 나는 마음으로는 '현재'가 가장 중요하다고 생각하면서도, 습관적으로 항상 '미래'부터 챙기곤 했다. 지금 이 순간을 놓치고 있다고 생각이 들 때면 환기차원에서 '오늘을 찾아요', '지금이 우리의 전부'와 같은 노래를 찾아 듣곤 했
**가중치 : 
 「1」 일반적으로 평균치를 산출할 때 개별치에 부여되는 중요도.**


가중치라는 단어 뜻에 이미 중요하다는 의미가 포함되어 있네요! `중요하다고 생각하는 가중치`라는 표현은 의미의 중복이 일어나는 것 같아요.

`그리고 저마다 다른 가중치를 둔다` 혹은 `그리고 각자 중요시 하는 시간이 있다.` 라는 표현은 어떤지 제안드려봐요...!

2021-03-15 14:59 UTC, thisisyoungbin commented on level1.md
> +작년 12월 프리코스를 진행하면서 처음 블로그를 만들었다. 느낀 점과 배운 점을 기록해두고 싶어서 만들긴 했는데, 당시에 내 글을 불특정 다수에게 공개할 용기는 없었다. 그래서 나만 볼 수 있도록 비공개로 설정해놓고 프리코스 후기를 작성했다. 순수하게 '저장소' 역할만 하는 블로그였다. 그러다 올해 1월 말, 알 수 없는 용기가 생겨 블로그를 새로 단장해
`그러다 올해 1월 말, 알 수 없는 용기가 생겨 블로그를 새로 단장해서 오픈한 후, 나의 일상과 학습내용을 하나하나 담아나갔다.`
문장에 담긴 정보가 많아서 호흡이 길어진 것 같은데 
`~ 단장해서 오픈했다. 그리고 나의 일상과 학습내용을 ...` 이렇게 나누는 건 어떨까요..!?

2021-03-15 14:59 UTC, thisisyoungbin commented on level1.md
> +우테코 과정을 시작한 이후에도 과정에서 배운 내용을 블로그에 틈틈이 포스팅했다. 돌아보니 다루고 싶은 주제를 모두 다루지 못한 점이 아쉬움으로 남는다. 개인적으로 정말 구미가 당기고 더 탐구해서 글로 풀어보고 싶은 주제인데, 생각보다 자료 찾기가 쉽지 않아 포스팅을 포기한 글이 적지 않다. 또, 미션을 진행하면서 시간관리를 잘 못해서, 정리해야겠다는 생각
`포스팅을 포기한 글이 적지 않다`
틀린 표현은 아니지만 `포스팅을 포기한 글이 많다`로 표현하면 더 명확한 표현이 될 것 같아요! 😄

2021-03-15 15:15 UTC, 365kim commented on level1.md
> +작년 12월 프리코스를 진행하면서 처음 블로그를 만들었다. 느낀 점과 배운 점을 기록해두고 싶어서 만들긴 했는데, 당시에 내 글을 불특정 다수에게 공개할 용기는 없었다. 그래서 나만 볼 수 있도록 비공개로 설정해놓고 프리코스 후기를 작성했다. 순수하게 '저장소' 역할만 하는 블로그였다. 그러다 올해 1월 말, 알 수 없는 용기가 생겨 블로그를 다시 단장하
앗 이것도 30자가 넘어가서 고민했던 부분인데,,,, 짧은 호흡의 문장으로 친절하게 제안해주셔서 다시 고민해봤는데 쉼표로 명확하게 호흡을 끊어두었으니 괜찮지 않을까 싶어서 유지해 볼게요...!! (긴 문장이 저의 취향인가 봅니다 😭)

2021-03-15 15:19 UTC, 365kim commented on level1.md
> +앞서 말한 것처럼 나는 '열심히, 즐겁게 일할 수 있는 환경'이라는 나의 최대 목표를 이미 이루었다. 하지만 우테코는 영원한 과정이 아니다. 그렇기에 나는 다음에도 이런 조직의 구성원이 되기 위해 계속해서 부단히 노력해야 한다. 내가 지향하는 조직에서 기꺼이 나를 받아줄 수 있도록 앞으로 더 열심히 나를 단련시켜 나갈 것이다.
감사합니다 조엘! 말씀 듣고 나니까 정말 어색해 보이네요...! 제안해주신 느낌으로 수정해봤습니다~! 좋은 피드백 감사드려용 👍👍
📌관련 커밋: f0a2640

2021-03-15 15:21 UTC, 365kim commented on level1.md
> +사람들은 흔히 시간을 '과거', '현재', '미래' 세 가지로 분류한다. 그리고 저마다 더 중요하다고 생각하는 가중치가 있다. 나는 마음으로는 '현재'가 가장 중요하다고 생각하면서도, 습관적으로 항상 '미래'부터 챙기곤 했다. 지금 이 순간을 놓치고 있다고 생각이 들 때면 환기차원에서 '오늘을 찾아요', '지금이 우리의 전부'와 같은 노래를 찾아 듣곤 했
와우...! 제가 먼저 돌려서 올렸어야 했는데... 😭 죄송하고 감사합니다!

2021-03-15 15:22 UTC, 365kim commented on level1.md
> +사람들은 흔히 시간을 '과거', '현재', '미래' 세 가지로 분류한다. 그리고 저마다 더 중요하다고 생각하는 가중치가 있다. 나는 마음으로는 '현재'가 가장 중요하다고 생각하면서도, 습관적으로 항상 '미래'부터 챙기곤 했다. 지금 이 순간을 놓치고 있다고 생각이 들 때면 환기차원에서 '오늘을 찾아요', '지금이 우리의 전부'와 같은 노래를 찾아 듣곤 했
틀리게 쓴 부분이 정말 많군요... 감사해요 로키! 👍👍👍 커밋은 맞춤법 수정 한 줄로 남기고 싶어서 제안해주신 내용 참고해서 하나로 올려볼게요!

2021-03-15 15:34 UTC, 365kim commented on level1.md
> +우테코 과정을 시작한 이후에도 과정에서 배운 내용을 블로그에 틈틈이 포스팅했다. 돌아보니 다루고 싶은 주제를 모두 다루지 못한 점이 아쉬움으로 남는다. 개인적으로 정말 구미가 당기고 더 탐구해서 글로 풀어보고 싶은 주제인데, 생각보다 자료 찾기가 쉽지 않아 포스팅을 포기한 글이 적지 않다. 또, 미션을 진행하면서 시간관리를 잘 못해서, 정리해야겠다는 생각
`잘 못해서`, `잘 못 해서`는 전자가 맞는 표현인 것 같아요...! 참고한 국립국어원 답변입니다 [(링크)](https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=138056) 그 외 나머지 말씀해주신 부분은 모두 반영했습니다 :)

2021-03-15 15:36 UTC, 365kim commented on level1.md
> +그래도 레벨 1을 진행하면서 10개가 넘는 글을 작성했다는 점은 스스로 칭찬해주고 싶다. 작성한 글을 크루들에게 소개한 날에는 조회수가 폭발하기도 했다. _(FE크루들 영업 당해줘서 고마워요.)_ 나의 글이 누군가에게 도움이 되고 피드백을 받는 경험은 이전에 느껴보지 못한 성취감과 만족감을 가져다주었다. 최근에는 감사하게도 리뷰어분들 중 한 분께서 내 블
괄호 안에 쓰는 내용에 문장부호를 어떻게 쓸 지 깊게 생각해보지 못했네요..! 말씀해주셔서 감사해요👍 제안해주신 내용 보고 [검색](https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=108512)해봤는데, 제가 괄호 안에 작성한 내용이 온전한 문장이라서 온점을 찍어주는게 좋을 것 같아요...! 요 부분 외에 다른 맞춤법 잡아주신 것은 모두 반영해서 커밋했습니다 :)
📌관련 커밋: 2bea6d3

2021-03-15 15:52 UTC, 365kim commented on level1.md
> +사실 나는 최근에 실제 이름을 바꾸었다. 원래는 평범한 한자 이름이었다. 사전에 가족들의 동의를 얻긴 했지만 이름을 바꾼 것은 온전히 나의 선택이었다. 꽤 오래전부터 이름을 바꾸고 싶은 마음은 있었는데, 그와 별개로 이름에 담고 싶었던 나의 뜻 또는 의지가 있었다.
안녕하세 __욘__ !! 🙋🏻‍♀️
우선 좋은 피드백 감사합니당! 다른 크루분께서도 같은 내용을 말씀해주셔서 고민해봤는데,,, 솔직히 말씀드리면 저는 그대로 두고 싶은 마음입니다,,,👉👈 저는 해당 요구사항의 의도를 아래 예시와 같이 '지루한 문장을 피하자'는 의도로 이해했는데요..! 
```
(예시)
나는 아침에 일어났다. 나는 습관적으로 밥을 먹으려고 했다. 나는 배가 그다지 고프지 않다는 사실을 깨달았다. 나는 다시 잠에 들었다.
```
그래서 "`나는`을 아예 쓰면 안된다"라는 의미는 아니라고 해석했습니다. 의도한 대로 글이 작성되었는지는 모르지만, 이 부분은 시원한 느낌 없이(ㅎㅎㅎ;;) 작성하고 싶었어서 원래대로 두고 싶습니다...!🙏

2021-03-15 15:54 UTC, 365kim commented on level1.md
> +사람들은 흔히 시간을 '과거', '현재', '미래' 세 가지로 분류한다. 그리고 저마다 더 중요하다고 생각하는 가중치가 있다. 나는 마음으로는 '현재'가 가장 중요하다고 생각하면서도, 습관적으로 항상 '미래'부터 챙기곤 했다. 지금 이 순간을 놓치고 있다고 생각이 들 때면 환기차원에서 '오늘을 찾아요', '지금이 우리의 전부'와 같은 노래를 찾아 듣곤 했
오오,,, DRY하지 못했군요,,, "더 중요하다고 생각하는 중요도가 있다"라고 쓴 셈이네요...! 바로 수정해서 커밋하겠습니다. 감사합니다 👍

2021-03-15 16:03 UTC, 365kim commented on level1.md
> +작년 12월 프리코스를 진행하면서 처음 블로그를 만들었다. 느낀 점과 배운 점을 기록해두고 싶어서 만들긴 했는데, 당시에 내 글을 불특정 다수에게 공개할 용기는 없었다. 그래서 나만 볼 수 있도록 비공개로 설정해놓고 프리코스 후기를 작성했다. 순수하게 '저장소' 역할만 하는 블로그였다. 그러다 올해 1월 말, 알 수 없는 용기가 생겨 블로그를 새로 단장해
오우 이거 다른 크루분께서도 말씀해주셨던 부분인데,,, 제가 고집을 피워봤지만 역시 호흡이 너무 긴가봅니다 ㅠ_ㅠ 제안해주신대로 수정했습니다! 좋은 피드백 감사합니다! 👍👍
📌관련 커밋: fb0dd98

2021-03-15 16:06 UTC, 365kim commented on level1.md
> +우테코 과정을 시작한 이후에도 과정에서 배운 내용을 블로그에 틈틈이 포스팅했다. 돌아보니 다루고 싶은 주제를 모두 다루지 못한 점이 아쉬움으로 남는다. 개인적으로 정말 구미가 당기고 더 탐구해서 글로 풀어보고 싶은 주제인데, 생각보다 자료 찾기가 쉽지 않아 포스팅을 포기한 글이 적지 않다. 또, 미션을 진행하면서 시간관리를 잘 못해서, 정리해야겠다는 생각
뒤에 이어지는 문장의 술어가 똑같이 '많다'여서 둘 중 고민하다가 앞 쪽을 '적지 않다'로 바꿔준 것이었어요...! 요 부분은 저의 취향으로 이해해 주시면 감사하겠습니다...!! 😆🙏

2021-03-16 01:50 UTC, knae11 reviewed
전체적으로 상당히 잘 읽히는 글이라 수정할 곳이 많지 않아보였어요! 그래도 리뷰어니까 눈에 불을 켜고 찾았네요.ㅎㅎㅎ  재밌게 읽었어요!

2021-03-16 01:50 UTC, knae11 commented on level1.md
> +사람들은 흔히 시간을 '과거', '현재', '미래' 세 가지로 분류한다. 그리고 저마다 다른 가중치를 둔다. 나는 마음으로는 '현재'가 가장 중요하다고 생각하면서도, 습관적으로 항상 '미래'부터 챙기곤 했다. 지금, 이 순간을 놓치고 있다는 생각이 들 때면 환기 차원에서 '오늘을 찾아요', '지금이 우리의 전부'와 같은 노래를 찾아 듣곤 했다. 이 노래들
좋은 이름이네요ㅎㅎㅎ

2021-03-16 01:50 UTC, knae11 commented on level1.md
> +조직생활을 하는 사람들은 대개 조직 내 불합리한 의사결정을 경험하며 자괴감을 느낀다. 나도 그런 사람 중 하나였다. 퇴사를 결심하며 정했던 단 하나의 목표는 '열심히, 즐겁게 일할 수 있는 조직에 속하는 것'이었다. 우테코에 들어온 나는 그 목표를 이미 이룬 셈이다. 그 때문에 나는 한없이 만족스러울 수 밖에 없다. 합리적이고 배려 넘치는 우테코 시스템을
지금도 충분히 깔끔한 전개라고 생각합니다. 혹시 두 단락을

`그전에 불만이었던 점 --> 그에 비해 우테코가 얼마나 좋은지`

방식으로 바꿔보면 전개가 더 자연스럽지 않을까 생각해 보았습니다 ㅎㅎㅎ

2021-03-16 12:07 UTC, sjpark-dev approved these changes
하루! 다시 한번 글을 읽어 봤어요! 😊
다른 리뷰어들 덕분에 더 좋은 글이 되었군요. 👍
저는 이만 Approve하겠습니다. ✔
수고하셨습니다. 👍

2021-03-16 14:31 UTC, 365kim commented on level1.md
> +조직생활을 하는 사람들은 대개 조직 내 불합리한 의사결정을 경험하며 자괴감을 느낀다. 나도 그런 사람 중 하나였다. 퇴사를 결심하며 정했던 단 하나의 목표는 '열심히, 즐겁게 일할 수 있는 조직에 속하는 것'이었다. 우테코에 들어온 나는 그 목표를 이미 이룬 셈이다. 그 때문에 나는 한없이 만족스러울 수 밖에 없다. 합리적이고 배려 넘치는 우테코 시스템을
안녕하세요 배럴! 😆 좋은 피드백 감사드려용 :) 
저도 말씀해주신 전개가 훨씬 자연스럽고 논리적으로 느껴져서 수정해봤습니다! 그런데 불만을 표현하는 '불합리한', '자괴감'과 같이 부정적인 어감이 강한 단어가 글의 초반에 등장하니, 글 전체의 인상이 제가 생각했던 것과 달라진다는 느낌을 받았어요...! 저 단어들이 주는 부정적인 어감을 이용하고 싶지만, 글의 첫 부분에 등장하는 것은 피하고 싶어서, 비교적 더 가벼운 이야기로 운을 떼는 지금의 구조를 유지해보려고 합니다...! 🙏🙏🙏

2021-03-16 14:32 UTC, PapimonLikelion approved these changes
제가 드리고 싶은 피드백은 모두 드린거같아요!
좋은글 감사합니다 하루!
코로나가 나아져서 얼른 뵙고싶네요! :)

2021-03-16 15:25 UTC, thisisyoungbin approved these changes
하루 안녕하세요~~!!! 제가 드린 피드백은 지난 피드백에서 다 드렸고 몇 가지 반영된 부분들도 있어서 
저또한 뿌듯함을 느꼈어요!! ㅎㅎㅎ 루터회관에서 뵙는 날을 바라며 이만 Approve 하겠습니다 !! 
좋은 글 다시 한 번 잘 읽었습니다.!!

2021-03-17 09:24 UTC, knae11 commented on level1.md
> +조직생활을 하는 사람들은 대개 조직 내 불합리한 의사결정을 경험하며 자괴감을 느낀다. 나도 그런 사람 중 하나였다. 퇴사를 결심하며 정했던 단 하나의 목표는 '열심히, 즐겁게 일할 수 있는 조직에 속하는 것'이었다. 우테코에 들어온 나는 그 목표를 이미 이룬 셈이다. 그 때문에 나는 한없이 만족스러울 수 밖에 없다. 합리적이고 배려 넘치는 우테코 시스템을
오 그렇군요! 그렇다면 하루의 의견을 존중합니다!ㅎㅎㅎ

2021-03-17 09:54 UTC, knae11 reviewed
제가 저번에 정신없이 읽어서 이번에 좀 더 꼼꼼한 리뷰를 작성해보았습니다ㅎㅎㅎ 리뷰는 꼭 반영하지 않아도 됩니다! 저도 글을 잘 쓰는 사람이 제 리뷰가 좋은 내용인지 몰라요~~ㅎㅎㅎ 최대한 제가 생각하는 범위에서 조금이라도 개선되면 좋을 점을 찾아보았어요! 글을 다시 읽으니까 개선되었으면 하는 내용들이 더 잘보이더라구요ㅎㅎㅎ

일단 앞서 말씀드렸다시피 너무 좋은 글이고 전반적으로 잘 읽혀서 사실 크게 고칠 곳은 없어요!ㅎㅎㅎ 
하지만, 굳이굳이 찾아보면 전반적으로 느낀 점은 

1. 문장간 이어주는 접속부사가 전반적으로 많은 느낌입니다. 제 생각에 접속부사가 많으면 호흡이 계속 이어지는 느낌이라 약간은 줄여도 충분히 좋을 것 같다는 느낌을 받았어요!  
2. 나 라는 단어가 많이 사용된 편인 것 같아요! 나를 강조하기 위해서 일부러 사용하신 것들 이외에는 나라는 단어를 줄이는게 오히려 강조하고 싶은 `나`를 더 돋보이게 해줄 수 있지 않을까 생각했어요 :)

2021-03-17 09:54 UTC, knae11 commented on level1.md
> +사실 나는 최근에 실제 이름을 바꾸었다. 원래는 평범한 한자 이름이었다. 사전에 가족들의 동의를 얻긴 했지만 이름을 바꾼 것은 온전히 나의 선택이었다. 꽤 오래전부터 이름을 바꾸고 싶은 마음은 있었는데, 그와 별개로 이름에 담고 싶었던 나의 뜻 또는 의지가 있었다.
```suggestion
사실 나는 최근에 실제 이름을 바꾸었다. 원래는 평범한 한자 이름이었다. 사전에 가족들의 동의를 얻긴 했지만 이름을 바꾼 것은 온전히 나의 선택이었다. 꽤 오래전부터 이름을 바꾸고 싶은 마음은 있었는데, 그와 별개로 이름에 담고 싶었던 나만의 의미가 있었다.
```

이렇게 하면 좀 더 자연스러울까요?

2021-03-17 09:54 UTC, knae11 commented on level1.md
> +코로나 여파로 집에만 있어서 바뀐 이름으로 불릴 일이 많이 없었다. 그래서 나도 모르게 옛날 이름을 쓰는 경우도 더러 있었다. 우테코 시작 전에 문의해보니 본명을 닉네임으로 정해도 된다는 답변을 받았다. 그래서 바꾼 이름인 '하루'를 닉네임으로 사용하게 되었다. 줌으로 하는 데일리 미팅이나, 슬랙 메신저에도 항상 '하루'라는 사용자 이름이 따라붙고, 코치
```suggestion
코로나 여파로 집에만 있어서 바뀐 이름으로 불릴 일이 많이 없었다. 그러다보니 나도 모르게 옛날 이름을 쓰는 경우도 더러 있었다. 우테코 시작 전에 문의해보니 본명을 닉네임으로 정해도 된다는 답변을 받았다. 그래서 바꾼 이름인 '하루'를 닉네임으로 사용하기로 했다. 줌으로 하는 데일리 미팅이나, 슬랙 메신저에도 항상 '하루'라는 사용자 이름이 따라붙고, 코치님, 크루들, 리뷰어님까지 모두 나를 당연하게 '하루'라고 불러주셨다. 덕분에 이제는 나의 새로운 이름에 완벽 적응했다. 닉네임을 본명으로 정한 건 잘한 결정이었다.
```

약간 그래서가 계속 겹치는 것 같아 수정해보았습니다 :)

2021-03-17 09:54 UTC, knae11 commented on level1.md
> +작년 12월 프리코스를 진행하면서 처음 블로그를 만들었다. 느낀 점과 배운 점을 기록해두고 싶어서 만들긴 했는데, 당시에 내 글을 불특정 다수에게 공개할 용기는 없었다. 그래서 나만 볼 수 있도록 비공개로 설정해놓고 프리코스 후기를 작성했다. 순수하게 '저장소' 역할만 하는 블로그였다. 그러다 올해 1월 말, 알 수 없는 용기가 생겨 블로그를 새로 단장해
```suggestion
작년 12월 프리코스를 진행하면서 처음 블로그를 만들었다. 느낀 점과 배운 점을 기록해두고 싶어서 만들었지만, 당시에 불특정 다수에게 공개할 용기는 없었다. 그래서 비공개로 설정해놓고 프리코스 후기를 작성했다. 순수하게 '저장소' 역할만 하는 블로그였다. 올해 1월 말, 알 수 없는 용기가 생겨 블로그를 새로 단장해서 오픈했다. 그리고 나의 일상과 학습 내용을 하나하나 담아나갔다.
```
글 전반에 걸쳐 `나`를 많이 사용하시는 것 같아서 의도적으로 강조한 부분 이외에는 자제하면 좋을 것 같아요! 또한 문장 연결구가 거의 2문장에 1번 빈도로 등장하는 것 같아서 약간은 줄이면 좋지 않을까 생각했어요!

2021-03-17 09:54 UTC, knae11 commented on level1.md
> +우테코 과정을 시작한 이후에도 과정에서 배운 내용을 블로그에 틈틈이 포스팅했다. 돌아보니 다루고 싶은 주제를 모두 다루지 못한 점이 아쉬움으로 남는다. 개인적으로 정말 구미가 당기고 더 탐구해서 글로 풀어보고 싶은 주제인데, 생각보다 자료 찾기가 쉽지 않아 포스팅을 포기한 글이 적지 않다. 또, 미션을 진행하면서 시간 관리를 잘 못해서, 정리해야겠다는 생
```suggestion
우테코 과정을 시작한 이후에도 과정에서 배운 내용을 블로그에 틈틈이 포스팅했다. 돌아보니 다루고 싶은 주제를 모두 다루지 못한 점이 아쉬움으로 남는다. 개인적으로 정말 구미가 당겨 더 탐구해서 글로 풀어보고 싶은 주제인데, 생각보다 자료 찾기가 쉽지 않아 포스팅을 포기한 글도 많다. 또, 미션을 진행하면서 시간 관리를 잘 못해서, 정리해야겠다는 생각으로 제목만 작성한 채 아예 건드리지 못한 주제도 많다.
```
굳이 적지 않다로 사용한 의미가 있을까요? 더불어 몇가지 수정하면 좋을 것 같은 부분 작성해보았습니다!

2021-03-17 09:54 UTC, knae11 commented on level1.md
> +그래도 레벨 1을 진행하면서 10개가 넘는 글을 작성했다는 점은 스스로 칭찬해주고 싶다. 작성한 글을 크루들에게 소개한 날에는 조회수가 폭발하기도 했다. _(FE크루들 영업 당해줘서 고마워요.)_ 나의 글이 누군가에게 도움이 되고 피드백을 받는 경험은 이전에 느껴보지 못한 성취감과 만족감을 가져다주었다. 최근에는 감사하게도 리뷰어분들 중 한 분께서 내 블
```suggestion
스스로 칭찬해 주고 싶은 점은 그래도 레벨 1을 진행하면서 10개가 넘는 글을 작성했다는 것이다. 작성한 글을 크루들에게 소개한 날에는 조회수가 폭발하기도 했다. _(FE크루들 영업 당해줘서 고마워요.)_ 나의 글이 누군가에게 도움이 되고 피드백을 받는 경험은 이전에 느껴보지 못한 성취감과 만족감을 가져다주었다. 최근에는 감사하게도 리뷰어분들 중 한 분께서 내 블로그를 SNS에 공유해주셔서 조회수 최대치를 경신하는 즐거운 경험도 할 수 있었다. 우테코 과정에 참여하지 못했다면 이 모든 새로운 경험을 놓쳤을지도 모른다. 즐거운 마음으로 남은 9개월의 여정도 블로그에 차곡차곡 기록해보려고 한다.
```
주어가 좀 더 짧으면 읽기 편할 듯 싶어서요! 저도 주어를 길게 작성하는 편이라...ㅠㅠ 하루가 판단해 주세요!ㅎㅎㅎ

2021-03-17 09:54 UTC, knae11 commented on level1.md
> +흔히 말하는 대학 과제의 팀플을 떠올려보면, 팀에 속한 '모두'가 열심히 한다는 것이 얼마나 비현실적인 이야기인지 알 수 있다. 그런데 그 비현실적인 일이 우테코에서는 벌어지고 있다. 그런 점에서 우테코는 현실보다 판타지에 가깝다고 표현하고 싶다. 그래서 주변 사람들이 물으면 나는 우테코에서의 생활에 200% 만족한다고 대답한다.
```suggestion
흔히 말하는 대학 과제의 팀플을 떠올려보면, 팀에 속한 '모두'가 열심히 한다는 것이 얼마나 비현실적인 이야기인지 알 수 있다. 그런데 그 비현실적인 일이 우테코에서는 벌어지고 있다. 그런 점에서 우테코는 현실보다 판타지에 가깝다고 표현하고 싶다. 주변 사람들이 물으면 나는 우테코에서의 생활에 200% 만족한다고 대답한다.
```
전반적으로 문장간 이어주는 어구가 많은 듯 한 느낌이 약~~간 들어요!ㅎㅎㅎ 주관적인 생각으로는 이어주는 어구가 많으면 짧은 문장이라도 길게 느껴지는 것 같아서요.

2021-03-17 09:54 UTC, knae11 commented on level1.md
> +조직생활을 하는 사람들은 대개 조직 내 불합리한 의사결정을 경험하며 자괴감을 느낀다. 나도 그런 사람 중 하나였다. 퇴사를 결심하며 정했던 단 하나의 목표는 '열심히, 즐겁게 일할 수 있는 조직에 속하는 것'이었다. 우테코에 들어온 나는 그 목표를 이미 이룬 셈이다. 그 때문에 나는 한없이 만족스러울 수 밖에 없다. 합리적이고 배려 넘치는 우테코 시스템을
```suggestion
조직생활을 하는 사람들은 대개 조직 내 불합리한 의사결정을 경험하며 자괴감을 느낀다. 나도 그런 사람 중 하나였다. 퇴사를 결심하며 정했던 단 하나의 목표는 '열심히, 즐겁게 일할 수 있는 조직에 속하는 것'이었다. 우테코에 들어온 순간 그 목표를 이미 이룬 셈이다. 우테코 생활이 한없이 만족스럽다. 합리적이고 배려 넘치는 우테코 시스템을 경험할 때, 그리고 열정적인 크루들과 함께할 때, 말로 다 할 수 없는 만족감을 느낀다. 내가 현재 이 조직에 속할 수 있음에, 이 동료들이 함께 해줌에 감사하고 또 감사하다.
```
약간 수정해 봤는데,, 어떤가요?

2021-03-17 09:54 UTC, knae11 commented on level1.md
> +앞서 말한 것처럼 나는 목표를 이미 이루었다. 목표를 정할 당시에만 해도 실현 가능한 목표인지 몰랐다. 우테코에서 한 달 생활을 마친 지금은, 내 노력 여하에 따라 앞으로도 이를 계속 현실로 만들 수 있으리라는 확신이 있다. 그래서 다음 목표는 '내년에도 내가 지향하는 조직에 속할 수 있도록, 그 조직에서 필요로 하는 인재가 되는 것'으로 정했다. '열심
```suggestion
앞서 말한 것처럼 나는 목표를 이미 이루었다. 목표를 정할 당시에만 해도 실현 가능한 목표인지 몰랐다. 우테코에서 한 달 생활을 마친 지금은, 노력 여하에 따라 앞으로도 **이를 계속 현실로 만들 수 있으리라는 확신이 있다.** 그래서 다음 목표는 '내년에도 내가 지향하는 조직에 속할 수 있도록, 그 조직에서 필요로 하는 인재가 되는 것'으로 정했다. '열심히, 즐겁게 일할 수 있는 곳'에서 기꺼이 나를 받아줄 수 있도록, 앞으로 더 열심히 나를 단련 시키고 성장해 나갈 것이다.
```
저기 강조한 (어떻게 부분으로 선택하는지 몰라서ㅠㅠㅠ 문단 단위로 선택되네요ㅠㅠ) 

이를 계속 현실로 만들 수 있으리라는 확신 --> 이미 판타지가 현실이 되었는데 계속 현실이 된다?! 약간은 모호할 수 있는 문장이라고 생각되요. 풀어 작성해주시면 더 좋을 것 같기도 합니다!

2021-03-17 09:54 UTC, knae11 commented on level1.md
> +앞서 말한 것처럼 나는 목표를 이미 이루었다. 목표를 정할 당시에만 해도 실현 가능한 목표인지 몰랐다. 우테코에서 한 달 생활을 마친 지금은, 내 노력 여하에 따라 앞으로도 이를 계속 현실로 만들 수 있으리라는 확신이 있다. 그래서 다음 목표는 '내년에도 내가 지향하는 조직에 속할 수 있도록, 그 조직에서 필요로 하는 인재가 되는 것'으로 정했다. '열심
강조의 의미로 작성한 `나` 이외에는 약간 줄여서 사용하면 좋을 듯 싶어요!ㅎㅎㅎ

2021-03-17 15:04 UTC, 365kim commented on level1.md
> +사실 나는 최근에 실제 이름을 바꾸었다. 원래는 평범한 한자 이름이었다. 사전에 가족들의 동의를 얻긴 했지만 이름을 바꾼 것은 온전히 나의 선택이었다. 꽤 오래전부터 이름을 바꾸고 싶은 마음은 있었는데, 그와 별개로 이름에 담고 싶었던 나의 뜻 또는 의지가 있었다.
여기에서 '뜻'은 `무엇을 하겠다고 속으로 먹는 마음`의 의미로, '의지'는 `어떠한 일을 이루고자 하는 마음`의 의미로 사용했습니다! 추천해주신 '의미'라는 단어도 좋지만 변하고자 하는 '의지'를 강조하기 위해서 이 단어는 남겨놓도록 하겠습니다 🙏🙏

2021-03-17 15:04 UTC, 365kim commented on level1.md
> +코로나 여파로 집에만 있어서 바뀐 이름으로 불릴 일이 많이 없었다. 그래서 나도 모르게 옛날 이름을 쓰는 경우도 더러 있었다. 우테코 시작 전에 문의해보니 본명을 닉네임으로 정해도 된다는 답변을 받았다. 그래서 바꾼 이름인 '하루'를 닉네임으로 사용하게 되었다. 줌으로 하는 데일리 미팅이나, 슬랙 메신저에도 항상 '하루'라는 사용자 이름이 따라붙고, 코치
오오 바꿔주신대로 읽어보니까 훨씬 좋네요! 반영해서 커밋하겠습니다! 좋은 피드백 감사해요 >_<

2021-03-17 15:15 UTC, 365kim commented on level1.md
> +작년 12월 프리코스를 진행하면서 처음 블로그를 만들었다. 느낀 점과 배운 점을 기록해두고 싶어서 만들긴 했는데, 당시에 내 글을 불특정 다수에게 공개할 용기는 없었다. 그래서 나만 볼 수 있도록 비공개로 설정해놓고 프리코스 후기를 작성했다. 순수하게 '저장소' 역할만 하는 블로그였다. 그러다 올해 1월 말, 알 수 없는 용기가 생겨 블로그를 새로 단장해
저는 저에 대한 이야기를 쓴 글이라면 '나의', '내', '나는' 과 같은 단어가 많은 건 자연스러운 일이라고 생각합니다...! 객체지향에 대한 글을 쓰면 '객체지향은', '객체지향의'과 같은 단어가 글에 많이 등장하는 것과 같은 이유로요...! 혹시 자제하는게 좋을 것 같다고 생각하신 이유를 공유해주실 수 있을까용,,,???

2021-03-17 15:19 UTC, 365kim commented on level1.md
> +작년 12월 프리코스를 진행하면서 처음 블로그를 만들었다. 느낀 점과 배운 점을 기록해두고 싶어서 만들긴 했는데, 당시에 내 글을 불특정 다수에게 공개할 용기는 없었다. 그래서 나만 볼 수 있도록 비공개로 설정해놓고 프리코스 후기를 작성했다. 순수하게 '저장소' 역할만 하는 블로그였다. 그러다 올해 1월 말, 알 수 없는 용기가 생겨 블로그를 새로 단장해
덧붙여 접속사를 적게 쓰는 것을 추천해주신 이유도 궁금합니다,,!!🙏🙏🙏

2021-03-17 15:20 UTC, 365kim commented on level1.md
> +우테코 과정을 시작한 이후에도 과정에서 배운 내용을 블로그에 틈틈이 포스팅했다. 돌아보니 다루고 싶은 주제를 모두 다루지 못한 점이 아쉬움으로 남는다. 개인적으로 정말 구미가 당기고 더 탐구해서 글로 풀어보고 싶은 주제인데, 생각보다 자료 찾기가 쉽지 않아 포스팅을 포기한 글이 적지 않다. 또, 미션을 진행하면서 시간 관리를 잘 못해서, 정리해야겠다는 생
뒷 문장의 술어와 다르게 작성하기 위해 의도적으로 적지 않다고 적었습니다 :) 꼼꼼한 피드백 감사드립니다!!

2021-03-17 15:22 UTC, 365kim commented on level1.md
> +그래도 레벨 1을 진행하면서 10개가 넘는 글을 작성했다는 점은 스스로 칭찬해주고 싶다. 작성한 글을 크루들에게 소개한 날에는 조회수가 폭발하기도 했다. _(FE크루들 영업 당해줘서 고마워요.)_ 나의 글이 누군가에게 도움이 되고 피드백을 받는 경험은 이전에 느껴보지 못한 성취감과 만족감을 가져다주었다. 최근에는 감사하게도 리뷰어분들 중 한 분께서 내 블
오오 짧게 바꾼게 훨씬 읽기 좋네요! 배럴이 말씀해주신대로 주어를 짧게 가져가는게 좋겠어요 👍👍👍

2021-03-17 15:30 UTC, 365kim commented on level1.md
> +흔히 말하는 대학 과제의 팀플을 떠올려보면, 팀에 속한 '모두'가 열심히 한다는 것이 얼마나 비현실적인 이야기인지 알 수 있다. 그런데 그 비현실적인 일이 우테코에서는 벌어지고 있다. 그런 점에서 우테코는 현실보다 판타지에 가깝다고 표현하고 싶다. 그래서 주변 사람들이 물으면 나는 우테코에서의 생활에 200% 만족한다고 대답한다.
아하 그래서 위에서도 접속사를 적게 쓰기를 추천해주셨군요...! 전 문장간의 관계를 명확히 나타내는 것이 더 읽는데 도움이 된다고 생각했어요...! 그렇다고 일부러 접속사를 열심히 추가한건 아니지만서도,,, 배럴 말씀 듣고나서 반복해서 읽어봤는데, 저는 역시 접속사가 있는 쪽이 더 편하게 읽히네용 😭😭 문체 취향의 영역이라고 생각하고 유지해보겠습니다...!! 🙏🙏🙏

2021-03-17 15:34 UTC, 365kim commented on level1.md
> +조직생활을 하는 사람들은 대개 조직 내 불합리한 의사결정을 경험하며 자괴감을 느낀다. 나도 그런 사람 중 하나였다. 퇴사를 결심하며 정했던 단 하나의 목표는 '열심히, 즐겁게 일할 수 있는 조직에 속하는 것'이었다. 우테코에 들어온 나는 그 목표를 이미 이룬 셈이다. 그 때문에 나는 한없이 만족스러울 수 밖에 없다. 합리적이고 배려 넘치는 우테코 시스템을
오 조직에 '속해있을 수 있음'보다 '속할 수 있음'으로 더 깔끔하게 의미전달이 가능하네요! 감사합니다 ㅎㅎ 그리고,,, 저는 접속사도, '나는'도 있는게 더 좋은 것 같아요,,, 😭😭😭

2021-03-17 15:37 UTC, 365kim commented on level1.md
> +앞서 말한 것처럼 나는 목표를 이미 이루었다. 목표를 정할 당시에만 해도 실현 가능한 목표인지 몰랐다. 우테코에서 한 달 생활을 마친 지금은, 내 노력 여하에 따라 앞으로도 이를 계속 현실로 만들 수 있으리라는 확신이 있다. 그래서 다음 목표는 '내년에도 내가 지향하는 조직에 속할 수 있도록, 그 조직에서 필요로 하는 인재가 되는 것'으로 정했다. '열심
오오 예리하십니다 배럴!! 말씀해 주신대로 모호한 부분을 해결할 수 있게끔 풀어서 작성해볼게용 감사합니당!!! 👍👍👍

2021-03-19 01:26 UTC, knae11 commented on level1.md
> +사실 나는 최근에 실제 이름을 바꾸었다. 원래는 평범한 한자 이름이었다. 사전에 가족들의 동의를 얻긴 했지만 이름을 바꾼 것은 온전히 나의 선택이었다. 꽤 오래전부터 이름을 바꾸고 싶은 마음은 있었는데, 그와 별개로 이름에 담고 싶었던 나의 뜻 또는 의지가 있었다.
넵넵:) 👍👍

2021-03-19 01:28 UTC, knae11 commented on level1.md
> +코로나 여파로 집에만 있어서 바뀐 이름으로 불릴 일이 많이 없었다. 그래서 나도 모르게 옛날 이름을 쓰는 경우도 더러 있었다. 우테코 시작 전에 문의해보니 본명을 닉네임으로 정해도 된다는 답변을 받았다. 그래서 바꾼 이름인 '하루'를 닉네임으로 사용하게 되었다. 줌으로 하는 데일리 미팅이나, 슬랙 메신저에도 항상 '하루'라는 사용자 이름이 따라붙고, 코치
오!! 레퍼런스 👍

2021-03-19 01:29 UTC, knae11 commented on level1.md
> +작년 12월 프리코스를 진행하면서 처음 블로그를 만들었다. 느낀 점과 배운 점을 기록해두고 싶어서 만들긴 했는데, 당시에 내 글을 불특정 다수에게 공개할 용기는 없었다. 그래서 나만 볼 수 있도록 비공개로 설정해놓고 프리코스 후기를 작성했다. 순수하게 '저장소' 역할만 하는 블로그였다. 그러다 올해 1월 말, 알 수 없는 용기가 생겨 블로그를 새로 단장해
넵넵~! :)  👍👍

2021-03-19 01:31 UTC, knae11 commented on level1.md
> +앞서 말한 것처럼 나는 목표를 이미 이루었다. 목표를 정할 당시에만 해도 실현 가능한 목표인지 몰랐다. 우테코에서 한 달 생활을 마친 지금은, 내 노력 여하에 따라 앞으로도 이를 계속 현실로 만들 수 있으리라는 확신이 있다. 그래서 다음 목표는 '내년에도 내가 지향하는 조직에 속할 수 있도록, 그 조직에서 필요로 하는 인재가 되는 것'으로 정했다. '열심
훨씬 좋네요! :)

2021-03-19 01:34 UTC, knae11 approved these changes
하루 레퍼런스에 더불어 자신의 의견을 확실하게 표현해주셔서 리뷰의 리뷰를 받는 입장에서도 많이 고민하신 것이 느껴졌습니다! 👍👍 저는 하루의 글이 충분한 퇴고의 과정을 거쳤다고 생각하기 때문에 approve 하겠습니다! 고생하셨습니다!😃

approve 했는데 됬는지 모르겠네요;; 혹시 안 되었다면 하고 싶은데 어떻게 하는지 모르겠네요ㅎㅎㅎ 혹시 안되셨다면 알려주세요!

2021-03-19 01:35 UTC, knae11 approved these changes

2021-03-20 15:26 UTC, Rok93 approved these changes
지난번에 피드백 드렸던부분은 잘 반영해주신 것 같아요 : ) 
다른부분들도 조금 더 읽어봤는데, 제 기준에서는 피드백 드릴 부분이 없었어요 👍 

간단한 피드백 하나 남겨드렸는데, 이 또한 하루가 취할지 말지에 대해서는 선택적인 요소가 될 것 같아요! 
저는 이만 Approve 하도록 하겠습니다.

2021-03-20 15:26 UTC, Rok93 commented on level1.md
> +그래도 틈틈이 계속 글을 써왔다는 점은 스스로 칭찬해주고 싶다. 돌아보니 그 사이 10개가 넘는 글을 남겼다. 작성한 글을 크루들에게 소개한 날에는 조회수가 폭발하기도 했다. _(FE크루들 영업 당해줘서 고마워요.)_ 나의 글이 누군가에게 도움이 되고 피드백을 받는 경험은 이전에 느껴보지 못한 성취감과 만족감을 가져다주었다. 최근에는 감사하게도 리뷰어분들
``최근에는 감사하게도 리뷰어분들 중 한 분께서 내 블로그를 SNS에 공유해주셔서`` 이 부분은 ``서``가 중복되는 느낌이 들어서 아래와 같이 바꿔보면 어떨까요? 
--> ``최근에는 감사하게도 리뷰어분이 내 블로그를 SNS에 공유해주셔서``

2021-03-20 15:26 UTC, Rok93 commented on level1.md
> +앞서 말한 것처럼 나는 목표를 이미 이루었다. 하지만 우테코는 영원한 과정이 아니다. 그래서 다음 목표는 '내년에도 내가 지향하는 조직에 속할 수 있도록, 그 조직에서 필요로 하는 인재가 되는 것'으로 정했다. 우테코에서 한 달 생활을 마친 지금은, 내가 다분히 노력한다면 앞으로도 이 판타지를 이어나갈 수 있으리라는 확신이 든다. '열심히, 즐겁게 일할
판타지를 이어나가기 위한 공부라...  멋지네요 👍  
저도 우테코를 통한 결실이 제가 지향하는 것들을 갖춘 조직이었으면해요 !! 
앞으로의 과정도 함께 힘내봅시다 💪💪💪💪💪

2021-03-21 07:05 UTC, 365kim commented on level1.md
> +그래도 틈틈이 계속 글을 써왔다는 점은 스스로 칭찬해주고 싶다. 돌아보니 그 사이 10개가 넘는 글을 남겼다. 작성한 글을 크루들에게 소개한 날에는 조회수가 폭발하기도 했다. _(FE크루들 영업 당해줘서 고마워요.)_ 나의 글이 누군가에게 도움이 되고 피드백을 받는 경험은 이전에 느껴보지 못한 성취감과 만족감을 가져다주었다. 최근에는 감사하게도 리뷰어분들
앗 말씀해주신대로 ~~서, ~~서 요런느낌이네용 ㅜㅜ 그런데 높임을 나타내는 조사 "께서"를 유지하고 싶어서 뒷부분 '공유해주셔서'를 수정해볼게요!

2021-03-21 07:11 UTC, 365kim commented on level1.md
> +앞서 말한 것처럼 나는 목표를 이미 이루었다. 하지만 우테코는 영원한 과정이 아니다. 그래서 다음 목표는 '내년에도 내가 지향하는 조직에 속할 수 있도록, 그 조직에서 필요로 하는 인재가 되는 것'으로 정했다. 우테코에서 한 달 생활을 마친 지금은, 내가 다분히 노력한다면 앞으로도 이 판타지를 이어나갈 수 있으리라는 확신이 든다. '열심히, 즐겁게 일할
같이 힘내보아요 아자아자!! 🚀🚀🚀🚀

2021-03-24 16:33 UTC, Rok93 approved these changes

2021-03-27 02:32 UTC, qhals321 commented
매일 미션 하면서 항상 친절하게 답글을 달아주시는 하루!!!
어떤 분인가 너무 궁금해서 찾아오게 되었네요!
'열심히, 즐겁게 일할 수 있는 조직에 속하는 것' 이 목표였다고 했는데
저는 오히려 하루덕에 열심히 그리고 즐겁게 우테코에 임하고 있는 것 같아요!!!
너무나도 고맙고! 남은 우테코 기간에도 파이팅 파이팅하세요!!!!

2021-03-27 10:08 UTC, pkeugine commented
헐 저만 찾아오는게 아니었군요!
매일 인증할 때마다 하루 덕에 힘이 납니다 🔥
아직 본 적도 없는데 벌써 팬이에요!
이미 엄청난 분인 것 같은데, 앞으로 더 단련해서 강해진다니!
인간자동차는 제가 아니라 하루였던걸로... 🏎💨💨💨💨

2021-03-28 05:01 UTC, pobiconan approved these changes
봄내음이 물씬 풍기던 3월의 어느 날.
프론트엔드 크루들과의 첫 오프라인 만남이 있던 날이네요.
백엔드 강의를 준비하던 내게로 거부감없이 다가와 앉으면서 "여기서 뭐하세요?"라고 당돌하게 묻던 하루가 기억 나네요.
즐겁게 학습하고 일할 수 있는 공간이 판타지가 아니라 현실에서도 가능하다는 것을 보여주고 싶은 마음이 큰데요. 하루가 같이하면 좋겠네요.

2021-03-28 05:01 UTC, merged