[레벨 1 글쓰기 미션] 멍토(김유기) 미션 제출합니다.
woowacourse/woowa-writing-3 pull request #6
Opened 2021-03-15 07:51 UTC by daum7766

제가 작성한 글은 다시 읽어봐도 어디가 문제인지 감이 잘 오지 않더라고요!

많은 피드백 부탁합니다.

2021-03-15 08:38 UTC, Junroot requested changes
안녕하세요 멍토! 잘 읽었어요! 코멘트를 몇 개 남겼으니 참고하길 바랍니다!

2021-03-15 08:38 UTC, Junroot commented on README.md
> +
여기서 문단 구분을 위한 개행을 시도하신 것 같은데 개행이 제대로 안 이루졌네요😭
그리고 문장마다 개행을 하셨는데, 굳이 그럴 필요가 있을지에대한 생각이 드네요. 읽을 때, 어디서 문단이 끝나는지 파악하기가 힘들었어요 ㅠㅠㅠㅠ

2021-03-15 08:38 UTC, Junroot commented on README.md
> +의견이 맞지 않을 때는 서로를 설득하기 위해 각자의 논리를 펼치며 소프트 스킬을 늘려간다.
독자를 고려해 사실을 자세하게 나열하는 것도 좋지만, 그 상황의 감정을 표현하는 것도 중요하다고 생각해요. 감정 표현을 통해 독자가 필자의 심정을 이해하고 좀 더 몰입할 수 있을 거라는 생각이 들어요!

2021-03-15 08:38 UTC, Junroot commented on README.md
> +이것이 우아한 테크 코스의 장점이다.
`우아한 테크 코스`라고 띄어쓰셨네요! 원칙적으로는 띄어쓰는게 맞지만 고유명사의 경우에는 하나의 대상으로 파악을 쉽게하기 위해 단위별로 붙여쓰는 것을 인정해주고 있습니다! `우아한테크코스`라고 붙여쓰는게 이게 하나의 대상이라고 이해하기 쉽지 않을까요?

https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=111519

2021-03-15 08:50 UTC, dudtjr913 reviewed
안녕하세요. 리뷰를 하게 된 디토입니다!😙😙
우아한테크코스 한 달 생활기 잘 읽었고, 한 달을 돌아보는 기분으로 재미있게 읽었습니다.
코멘트로 제 의견을 남겨놨습니다. 꼭 수정하실 필요는 없습니다.😍😍

2021-03-15 08:50 UTC, dudtjr913 commented on README.md
> +아쉬움을 뒤로 남기고 데일리 미팅 조와 페어와 조금씩 더 친해지며 적응해간다.
아쉬움을 뒤로 남기고에서 **아쉬움을 뒤로하고**로 바꾸면 더 좋은 문장이 될 것 같습니다!!🤗

2021-03-15 08:50 UTC, dudtjr913 commented on README.md
> +시작 전에는 굳이 이런 걸 한다고 생각했다.
제가 느끼기에 문장이 살짝 어색한 것 같아요.
`시작 전에는 왜 이런 걸 해야 하는지 이해할 수 없었다.`
정도로 바꾸는 건 어떠신가요??

2021-03-15 08:50 UTC, dudtjr913 commented on README.md
> +나는 한 달 전과 비교해 많은 발전을 해 왔다.
한 달 전과 비교했을 때 어떤 부분이 발전했는지 작성하는 것도 좋을 것 같다고 생각합니다.😍

2021-03-15 09:51 UTC, daum7766 commented
피드백 한번 반영했습니다.

힘드시겠지만 다시한번 리뷰 부탁드려요!

2021-03-21 17:48 UTC, shinsehantan commented on README.md
> +> 친해질 기회가 생긴 것이다.
`시작 전에는 왜 이런 걸 해야 하는지 이해할 수 없었다.` 이후에는 어떻게 변했는지 바뀐 생각이나 감정도 추가하면 좋을 것 같아요 :)

2021-03-21 17:53 UTC, shinsehantan commented on README.md
> +>
어떤 것에 대한 기반을 다지는 기회가 된 건지 궁금합니다! 내용 추가해주시면 좋을 것 같아요ㅎㅎ
(`메워` 오타가 있네요!)

2021-03-21 17:57 UTC, shinsehantan commented on README.md
> +> 한 달만으로도 이런 데 모든 과정이 끝나면 어떨까? 하고 기대를 해본다.
`이런 데`는 '이런 장소, 이런 곳'을 뜻할 때만 띄어쓰기 하시면 돼서 `이런데`로 수정하시면 될 것 같습니다 :)

2021-03-21 18:01 UTC, shinsehantan commented on README.md
> +>
`적응하는데`는 '적응하는 것에'라는 뜻으로 쓰신 것일테니 `적응하는 데`로 띄어쓰기 해주시면 될 것 같아요 :)

2021-03-21 18:05 UTC, shinsehantan commented on README.md
> +
'와'가 두 번 반복되니, `데일리 미팅조, 페어와`로 바꾸는 건 어떨까요?

2021-03-24 05:19 UTC, daum7766 commented on README.md
> +
바꾸고 다시올리려 했는데 피드백이 빠르시네요 ㅜㅠ
수정했습니다!

2021-03-24 05:20 UTC, daum7766 commented on README.md
> +의견이 맞지 않을 때는 서로를 설득하기 위해 각자의 논리를 펼치며 소프트 스킬을 늘려간다.
감정표현.... 어렵네요...
공부해오겠습니다.

2021-03-24 05:22 UTC, daum7766 commented on README.md
> +이것이 우아한 테크 코스의 장점이다.
붙여서 수정했습니다!

2021-03-24 05:23 UTC, daum7766 commented on README.md
> +아쉬움을 뒤로 남기고 데일리 미팅 조와 페어와 조금씩 더 친해지며 적응해간다.
굿굿!
바로 반영하겠습니다.

2021-03-24 05:24 UTC, daum7766 commented on README.md
> +시작 전에는 굳이 이런 걸 한다고 생각했다.
이것 역시! 바로 반영갑니다.

2021-03-24 05:25 UTC, daum7766 commented on README.md
> +나는 한 달 전과 비교해 많은 발전을 해 왔다.
밑에 정리해서 추가하겠습니다!

2021-03-24 05:25 UTC, daum7766 commented on README.md
> +> 친해질 기회가 생긴 것이다.
오! 좋은 의견 입니다.
고민해서 반영하겠습니다

2021-03-24 05:26 UTC, daum7766 commented on README.md
> +> 한 달만으로도 이런 데 모든 과정이 끝나면 어떨까? 하고 기대를 해본다.
앗... 반영하겠습니다.

2021-03-24 05:31 UTC, daum7766 commented on README.md
> +>
굿굿!! 제가 한글을 덜 배워서... 많이 배워갑니다.

2021-03-24 05:33 UTC, daum7766 commented on README.md
> +
어색한 느낌이 나네요!
반영하겠습니다.

2021-03-24 05:36 UTC, daum7766 commented on README.md
> +>
!!!
매워가 아니라 메워군요!
그렇지만 채워가며로 바꾸겠습니다 ㅎㅎ

2021-03-24 06:13 UTC, daum7766 commented
보이는 라디오를 왜 했는지? vs 왜 보이는 라디오를 했는지?
머가 더 좋은거 같나요?

2021-03-25 08:11 UTC, dudtjr913 approved these changes
피드백 반영이 잘 된 것 같아요!! 중간에 한 칸이 실수로 띄워진 것 같은데 그 부분만 수정해주시면 좋을 것 같아요.😍😍

보이는 라디오를 진행한 이유, 페어 프로그래밍의 장점, 피드백 등 정말 공감가는 내용이 많았던 것 같아요. 특히 보이는 라디오를 한다고 했을 때 `시작 전에는 왜 이런 걸 해야 하는지 이해할 수 없었다.`이 부분이 공감가네요.😆😆 또한 우테코를 진행하면서 `생각하는 방법`을 배운다는 것도 정말 공감되는 부분이에요!

멍토가 발전한 모습을 보니 우테코 과정을 잘 소화할 것 같아요. 우리 모두 열심히 해봐요!! 수고하셨습니다~

2021-03-25 08:11 UTC, dudtjr913 commented on README.md
> +>
엇.. 여기 실수로 한 칸 띄워진 것 같아요! 이것만 수정하면 저에게는 완벽합니다!

2021-03-25 10:09 UTC, daum7766 commented on README.md
> +>
삭제했습니다! 고생하셨어요!

2021-03-26 06:41 UTC, Junroot approved these changes
피드백을 전부 반영해주셨네요! 더 피드백할 내용이 보이지 않으니 여기서 마무리하도록 하겠습니다! 
글 읽으면서 크루들 처음 만났을 때 어색했던 순간들이 새록새록 떠오르네요. 😊
페어 프로그래밍 힘들지만 도움이 많이 되고 있는 점에서 공감이 됩니다!
기회가 된다면 멍토와도 페어 프로그래밍 할 수 있으면 좋겠네요! 수고하셨어요!

2021-03-26 15:15 UTC, Livenow14 commented
글이 정말 깔끔하네요..! 
발전하는 하루하루가 되길 바랍니다. 같이 성장해요 😊

2021-03-26 15:53 UTC, unluckyjung commented on README.md
> +> 한 달만으로도 이런데 모든 과정이 끝나면 어떨까? 하고 기대를 해본다.
![image](https://user-images.githubusercontent.com/43930419/112658522-d1bd1300-8e96-11eb-84bc-872d6870e556.png)



**만랩 토끼** 가 되실겁니다.

2021-03-26 20:45 UTC, pkeugine commented
멍토 인생의 최고로 멋진 한 달! 저도 마찬가지입니다 :)
조만간 다시 온라인으로 만나서 함께 파이팅해봐요! 💪💪💪

2021-03-27 05:50 UTC, binghe819 approved these changes
멍토 안녕하세요!!

글의 내용도 인상 깊지만, 전체적인 구조가 굉장히 인상 깊네요!!

너무 잘 읽었습니다 👍 

제가 읽기엔 글에 어색한 부분이 없어서 이만 Approve할게요!!

글쓰기 미션 고생하셨어요~~

2021-03-27 14:33 UTC, shinsehantan approved these changes
안녕하세요 멍토:) 신세한탄입니다.

멍토의 글은 '한 달 생활기'라는 주제에 딱 맞는 구조였던 것 같아서 정말 잘 읽었습니다 :)
리뷰 반영해주신 것 감사해요🙃

글쓰기 미션 수고 많으셨습니다. 남은 미션도 화이팅!

2021-03-28 13:11 UTC, da-nyee approved these changes
안녕하세요 멍토~! 리뷰가 늦어져서 죄송합니다 😥

글 잘 읽었습니다! 공감이 많이 되는 글이었어요 👏
우테코에서 저희 모두는 각자에게 맞는 학습 방법을 배워가는 것 같아요!

앞서 다른 크루들이 피드백을 잘 남겨주어 저는 바로 Approve 하겠습니다 ~!

딱 한 부분에만 리뷰를 남겼어요. 자유롭게 수정해주세요!

글쓰기 미션 수고하셨습니다 👍 앞으로 남은 기간 동안 함께 열심히 공부해요 ✨

2021-03-28 13:11 UTC, da-nyee commented on README.md
> +> 우아한테크코스에서는 미션마다 페어가 바뀌게 된다.
```suggestion
> 우아한테크코스에서는 미션마다 페어가 바뀐다.
```

2021-04-12 08:18 UTC, Wonmi91 approved these changes
안녕하세요 멍토 : )

멍토의 한 달 생활기는 우테코가 한 달 동안 어떤 일을 하고 있는지 잘 드러내 주는 것 같아요. 
요구 사항에 맞게 문장도 짧게, 하나의 내용만 잘 담아주셨네요! (줄바꿈만 적절하게 해주시면 좋을 것 같아요. 문장마다 줄을 바꾸는 게 가독성은 좋아져도 흐름이 끊기는 느낌이 들 수도 있답니다~!)
설명하는 글도 물론 좋지만, 그 속에서 멍토가 느낀 점을 조금만 더 작성해 주었다면 더 풍부한 글이 되지 않았을까요~?
다음 글에서는 ‘서술’의 글보다는 ‘생각’, ‘감정’ 이 많이 담긴 글을 써보시면 좋겠어요.

남은 기간 동안에도 우아한 발전을 위하여 : )
고생하셨습니다!

2021-04-12 08:18 UTC, merged