docs: update 레벨1 글쓰기 미션 - 조이
woowacourse/woowa-writing-3 pull request #70
Opened 2021-03-28 01:47 UTC by Joyykim

늦어져서 미안해요 여러분ㅜ
글쓰기가 익숙하지 않은 저에겐 프론트엔드 미션보다 어려운 미션이었네요🥲
[편하게 보세요](https://github.com/Joyykim/woowa-writing-3/blob/joyykim/joy_level_1.md)

리뷰해주실 동동, 현구막, 피터, 우기, 인치, 피케이 감사합니다🙌

2021-03-28 02:55 UTC, pkeugine requested changes
안녕하세요 조이!!!

글 정말 잘 읽었어요 :)
조이와 마주칠 때마다 편하게 말 걸어주셔서 즐거웠는데,
페어와 함께할 때도 그러는 모습이 정말 멋있네요!
며칠 전에 주셨던 젤리가 전 아직도 기억난다구요 😁

딱히 큰 수정은 없고, 리뷰를 보고 조이가 편한대로 수정하시면 될 것 같습니다!

2021-03-28 02:55 UTC, pkeugine commented on joy_level_1.md
> +우아한테크코스에서는 대부분의 미션을 페어 프로그래밍으로 진행한다. 페어 프로그래밍은 두 명의 개발자가 짝을 이뤄서 하나의 PC로 개발을 하는 개발 방법론이다. 잠깐, 둘이서 하나의 PC로? 그런 비효율적인 짓을 한다니? 이해는 가지 않지만 일단 까라면 깐다. 어느새 우테코 Level-1이 끝나간다. 그 동안 4명의 크루와 페어 프로그래밍을 했다. 그리고
문장마다 줄바꿈을 하거나, 관련있는 녀석들로 묶어서 줄을 나눠도 괜찮을 것 같아요! 그러면 리뷰가 더 수월하더라구요 :)
사실 저도 이런거 잘 몰랐는데, @Hyeon9mak 덕에 알게되었습니다 ㅋㅋㅋ

2021-03-28 02:55 UTC, pkeugine commented on joy_level_1.md
> +우아한테크코스에서는 대부분의 미션을 페어 프로그래밍으로 진행한다. 페어 프로그래밍은 두 명의 개발자가 짝을 이뤄서 하나의 PC로 개발을 하는 개발 방법론이다. 잠깐, 둘이서 하나의 PC로? 그런 비효율적인 짓을 한다니? 이해는 가지 않지만 일단 까라면 깐다. 어느새 우테코 Level-1이 끝나간다. 그 동안 4명의 크루와 페어 프로그래밍을 했다. 그리고
PC -> 컴퓨터 로 바꿔보는건 어떨까요? 글을 읽다보면 컴퓨터가 더 잘 읽힐 것 같아요!

2021-03-28 02:55 UTC, pkeugine commented on joy_level_1.md
> +그 동안 혼자 혹은 학원에서 공부할 때도 다른 사람과 의견을 나누거나 토론한 적은 있었다. 하지만 페어 프로그래밍을 할 때는 그 깊이가 전혀 다르다. 보통이라면 토론을 하다가 의견이 맞춰지지 않는다면 그냥 넘어가거나 할 수 있다.
```suggestion
그 동안 혼자 혹은 학원에서 공부할 때도 다른 사람과 의견을 나누거나 토론한 적이 있었다. 이 경우, 토론을 하다가 의견이 맞춰지지 않더라도 그냥 넘어갈 수 있었다. 하지만 하나의 프로젝트, 하나의 컴퓨터로 개발을 하면 얘기가 달라진다.
```
약간의 수정!
그리고 `하지만 페어 프로그래밍을 할 때는 그 깊이가 전혀 다르다.`를 뒤로 빼봤어요. 여기서는 과거를 말하고 다음 문단에서는 우아한테크코스와 페어프로그래밍에 대해 말하기 때문에 그게 더 잘 연결되는 느낌이 들었거든요!

뒷 문단에서 `하지만 하나의 프로젝트, 하나의 PC로 개발을 하면 얘기가 다르다.`를 이쪽으로 가지고 왔어요. 이 말을 하고 페어 프로그래밍을 설명하면 더 자연스러운 연결이 되지 않을까 하는 생각에...

물론 굉장히 큰 변경이라 조이가 결정하면 될 것 같아요. 지금 그대로도 딱히 큰 문제는 없어보입니다!! 😁

2021-03-28 02:55 UTC, pkeugine commented on joy_level_1.md
> +하지만 하나의 프로젝트, 하나의 PC로 개발을 하면 얘기가 다르다. 어떻게든 합의를 봐야한다. 그러려면 내가 생각하는 방식이 맞는지, 상대가 맞는지 계속 고민하고 근거를 찾아내야 한다. 무조건 내 의견만 주장해도 안되고 상대의 생각을 필터링 없이 받아들이는 것도 안된다. 끊임없이 의심하고 서로의, 스스로의 생각을 깨야한다.
```suggestion
페어 프로그래밍을 할 때는 그 깊이부터 전혀 다르다. 어떻게든 합의를 봐야한다. 그러려면 내가 생각하는 방식이 맞는지, 상대가 맞는지 계속 고민하고 근거를 찾아야 한다. 무조건 내 의견만 주장하거나 상대의 생각을 필터링 없이 받아들이면 안된다. 양쪽 모두 끊임없이 의심하고, 생각의 틀을 깨야한다.
```
이전 코멘트에 적었는데, 전 문단에서 페어 프로그래밍의 깊이에 관한 문장을 가지고 왔어요! 그리고 약간의 수정을 해봤습니다. 특히 `생각을 깨야한다`를 `생각의 틀을 깨야한다`로 바꿔봤는데 어떤가요? 뭔가 그 표현이 더 자연스러운 것 같았어요. 🤜💥💭

여기도 조이가 결정하면 됩니다! 지금 그대로도 큰 문제는 없네요 👍

2021-03-28 02:55 UTC, pkeugine commented on joy_level_1.md
> +그 과정에서 좋은 설계, 클린한 코드가 나온다. 각자 따로 작업했다면 절대 나오지 않았을 퀄리티다. 페어 프로그래밍의 장점 중 하나는 코드의 품질이 높아진다는 것이다.
```suggestion
그 과정에서 좋은 설계, 클린한 코드가 나온다. 각자 따로 작업했다면 절대 나오지 않았을 퀄리티다. 코드 품질 향상은 페어 프로그래밍의 꽃이라고 볼 수 있다.
```
이 다음에 페어 프로그래밍의 다른 장점을 적지 않기 때문에 `장점 중 하나는` 표현을 바꿔봤어요. 장점 하나를 적는다면 이왕 하나인 김에 **🌸강조🌼**를!

2021-03-28 02:55 UTC, pkeugine commented on joy_level_1.md
> +하지만 여유는 잠시 뿐이었다. 로또 미션부터 목요일 6시까지 첫 리뷰요청을 보낸다는 조건이 생겼다. 화요일 점심에 만났는데 목요일 6시까지 제출하라고? 친해질 시간은 없다, 얼른 코드부터 짜!
```suggestion
하지만 여유는 잠시 뿐이었다. 두번째 미션부터 목요일 6시까지 첫 리뷰요청을 보낸다는 조건이 생겼다. 화요일 점심에 만났는데 목요일 6시까지 제출하라고? 친해질 시간은 없다, 얼른 코드부터 짜!
```
바로 전에 첫번째 미션이라고 하셔서 여기서 두번째 미션으로 살짝 바꿔봤습니다! 큰 변화는 아니네요 ㅋㅋㅋㅋ

2021-03-28 02:55 UTC, pkeugine commented on joy_level_1.md
> +"구현하기 바쁜데 무슨 아이스 브레이킹이야?"
로또 때부터였어요... "일단 구현부터 해보죠"를 말하기 시작한게... 😂

2021-03-28 02:55 UTC, pkeugine commented on joy_level_1.md
> +"뭐야, 안 친해져도 충분히 잘 끝냈는데?"
앗... 그 페어 누군진 모르지만 일러야겠다 ㅎㅎ 😁

2021-03-28 02:55 UTC, pkeugine commented on joy_level_1.md
> +다음 페어와의 미션은 전보다 어려워졌고 제한시간은 그대로였다. 난 당연히 전 미션처럼 빠르게 작업부터했다. 하지만 실제는 예상과 다르게 흘러갔다. 페어와 의견이 다른 부분이 많았고 토론하는 시간이 길어졌다. 페어의 생각을 이해할 수 없었다. 소모적인 토론이 많아졌고 진행이 더뎠다. 제한 시간은 다가오면서 마음이 급해져 서로 리팩터링하고 알아서 끝내기로하고
```suggestion
다음 페어와의 미션은 전보다 어려워졌고 제한시간은 그대로였다. 난 당연히 전 미션처럼 빠르게 작업부터했다. 하지만 실제는 예상과 다르게 흘러갔다. 페어와 의견이 다른 부분이 많았고 토론하는 시간이 길어졌다. 페어의 생각을 이해할 수 없었다. 소모적인 토론이 많아졌고 진행이 더뎠다. 제한 시간은 다가오면서 마음이 급해져 서로 각자 리팩터링하기로 하고 헤어졌다.
```
약간의 수정!

2021-03-28 02:55 UTC, pkeugine commented on joy_level_1.md
> +다음 페어와 미션을 하면서는 그런 부분을 의식하고 고치려 노력했다. 만나면 우선 잡담부터 했다. 가벼운 얘기로 분위기를 풀고 서로를 알아가는 시간이다. 사소한 이야기라도 페어를 이해할 수 있는 단서가 된다. 그런 단서가 조금씩 쌓이다 보면 나와 다른 페어의 생각을 이해할 수 있다.
```suggestion
다음 페어와 미션을 하면서는 그런 부분을 의식하고 고치려 노력했다. 만나면 우선 잡담부터 했다. 가벼운 이야기로 분위기를 풀고 서로를 알아가는 시간을 가졌다. 사소한 이야기라도 페어를 이해할 수 있는 단서가 된다. 그런 단서가 조금씩 쌓이다 보면 나와 다른 페어의 생각을 이해할 수 있다.
```
와우 회고하고 바로 변화하는 당신... 슬랙이었다면 여기에 이모지를 왕창 달았을 것 같아요!!
:킹: :갓: :황: :조이: 👍👏😁🤣🙌

2021-03-28 02:55 UTC, pkeugine commented on joy_level_1.md
> +잡담은 신뢰를 만들어나가는 원료다. 잡담을 통해 유대감을 만들고 유대감이 쌓여 신뢰로 발전한다!
```suggestion
잡담은 신뢰를 만들기 위해 필요한 원료다. 잡담을 통해 유대감을 만들고 유대감이 쌓여 신뢰로 발전한다!
```
가즈아아아아아아!!!! 🔥🔥🔥🔥

2021-03-28 05:30 UTC, Joyykim commented on joy_level_1.md
> +우아한테크코스에서는 대부분의 미션을 페어 프로그래밍으로 진행한다. 페어 프로그래밍은 두 명의 개발자가 짝을 이뤄서 하나의 PC로 개발을 하는 개발 방법론이다. 잠깐, 둘이서 하나의 PC로? 그런 비효율적인 짓을 한다니? 이해는 가지 않지만 일단 까라면 깐다. 어느새 우테코 Level-1이 끝나간다. 그 동안 4명의 크루와 페어 프로그래밍을 했다. 그리고
헉 지금 알았네요! 리뷰하기 불편하셨겠어요ㅜ 바로 수정할게요!

2021-03-28 05:45 UTC, Joyykim commented on joy_level_1.md
> +그 동안 혼자 혹은 학원에서 공부할 때도 다른 사람과 의견을 나누거나 토론한 적은 있었다. 하지만 페어 프로그래밍을 할 때는 그 깊이가 전혀 다르다. 보통이라면 토론을 하다가 의견이 맞춰지지 않는다면 그냥 넘어가거나 할 수 있다.
한 문단에서 하나의 내용만 하는게 훨씬 읽기 쉽고 자연스럽네요ㅎㅎ
반영하겠습니다! 고마워요!

2021-03-28 05:47 UTC, Joyykim commented on joy_level_1.md
> +우아한테크코스에서는 대부분의 미션을 페어 프로그래밍으로 진행한다. 페어 프로그래밍은 두 명의 개발자가 짝을 이뤄서 하나의 PC로 개발을 하는 개발 방법론이다. 잠깐, 둘이서 하나의 PC로? 그런 비효율적인 짓을 한다니? 이해는 가지 않지만 일단 까라면 깐다. 어느새 우테코 Level-1이 끝나간다. 그 동안 4명의 크루와 페어 프로그래밍을 했다. 그리고
PC보다 컴퓨터가 자연스럽군요ㅎㅎ 이것도 반영할게요~

2021-03-28 05:56 UTC, Joyykim commented on joy_level_1.md
> +하지만 하나의 프로젝트, 하나의 PC로 개발을 하면 얘기가 다르다. 어떻게든 합의를 봐야한다. 그러려면 내가 생각하는 방식이 맞는지, 상대가 맞는지 계속 고민하고 근거를 찾아내야 한다. 무조건 내 의견만 주장해도 안되고 상대의 생각을 필터링 없이 받아들이는 것도 안된다. 끊임없이 의심하고 서로의, 스스로의 생각을 깨야한다.
`무조건 내 의견만 주장하거나 상대의 생각을 필터링 없이 받아들이면 안된다.`
중복 제거 좋네요! 감사합니다😃

`끊임없이 의심하고 서로의, 스스로의` 까지 맘에 들어서 그 뒤에 `생각의 틀`이 오면 `의`가 반복되서 보기 안좋네여ㅜ
사실 `생각의 틀을 깨다`가 흔히 쓰이는 표현이긴 한데 전 생각의 틀같은 큰 관념보단 아이디어?를 깬다는 의미로 쓰고 싶어서 `생각을 깨다`로 가보겠습니다ㅎㅎ

2021-03-28 05:57 UTC, Joyykim commented on joy_level_1.md
> +그 과정에서 좋은 설계, 클린한 코드가 나온다. 각자 따로 작업했다면 절대 나오지 않았을 퀄리티다. 페어 프로그래밍의 장점 중 하나는 코드의 품질이 높아진다는 것이다.
🌼**너무 좋아요**🌸

2021-03-28 05:59 UTC, Joyykim commented on joy_level_1.md
> +하지만 여유는 잠시 뿐이었다. 로또 미션부터 목요일 6시까지 첫 리뷰요청을 보낸다는 조건이 생겼다. 화요일 점심에 만났는데 목요일 6시까지 제출하라고? 친해질 시간은 없다, 얼른 코드부터 짜!
굿뜨👍

2021-03-28 06:00 UTC, Joyykim commented on joy_level_1.md
> +"구현하기 바쁜데 무슨 아이스 브레이킹이야?"
ㅜㅅㅜ 제한시간 너무 짧아요...

2021-03-28 06:00 UTC, Joyykim commented on joy_level_1.md
> +"뭐야, 안 친해져도 충분히 잘 끝냈는데?"
쉿...!🤫

2021-03-28 06:01 UTC, Joyykim commented on joy_level_1.md
> +다음 페어와의 미션은 전보다 어려워졌고 제한시간은 그대로였다. 난 당연히 전 미션처럼 빠르게 작업부터했다. 하지만 실제는 예상과 다르게 흘러갔다. 페어와 의견이 다른 부분이 많았고 토론하는 시간이 길어졌다. 페어의 생각을 이해할 수 없었다. 소모적인 토론이 많아졌고 진행이 더뎠다. 제한 시간은 다가오면서 마음이 급해져 서로 리팩터링하고 알아서 끝내기로하고
ㅎㅎ부자연스러운 표현이 좀 많죠..? 평소에 책을 안읽어서ㅜ

2021-03-28 06:08 UTC, Joyykim commented on joy_level_1.md
> +다음 페어와 미션을 하면서는 그런 부분을 의식하고 고치려 노력했다. 만나면 우선 잡담부터 했다. 가벼운 얘기로 분위기를 풀고 서로를 알아가는 시간이다. 사소한 이야기라도 페어를 이해할 수 있는 단서가 된다. 그런 단서가 조금씩 쌓이다 보면 나와 다른 페어의 생각을 이해할 수 있다.
ㅎㅎㅎ
:피케이: :짱: 😀👍🙏

2021-03-28 06:09 UTC, Joyykim commented on joy_level_1.md
> +잡담은 신뢰를 만들어나가는 원료다. 잡담을 통해 유대감을 만들고 유대감이 쌓여 신뢰로 발전한다!
🔥🔥🔥🔥🔥

2021-03-28 06:26 UTC, pkeugine approved these changes
빠른 리뷰 반영!!!
조이 글을 보고 정신없는 하루 속에 잠시나마 힐링했어요 :)
덕분에 다시 리팩토링 + todo list 할 힘이 납니다!!!
조이도 파이팅하세요~~ 또 젤리 같이 먹는걸로 ㅎㅎ 🍬🍫🍭

2021-03-28 08:23 UTC, Hyeon9mak reviewed
조이의 페어프로그래밍 경험담 리얼하게 잘 읽었어요! 😆 
워낙 담백하고 깔끔하게 잘 써주셔서 `우테코`로 줄여쓰신 것과 같이 사소한 부분들에 대해서만 
몇가지 코멘트 남겼어요! 취향껏 적용해주시면 될 것 같아요!!

2021-03-28 08:23 UTC, Hyeon9mak commented on joy_level_1.md
> +잠깐, 둘이서 하나의 컴퓨터로? 그런 비효율적인 짓을 한다니? 이해는 가지 않지만 일단 까라면 깐다.
`까라면 깐다` 일부러 매운맛 표현을 쓰신거라면 🤣👍 
아니라면 `시키는 대로 해본다` 도 괜찮을 것 같아요!

2021-03-28 08:23 UTC, Hyeon9mak commented on joy_level_1.md
> +어느새 우테코 Level-1이 끝나간다. 그 동안 4명의 크루와 페어 프로그래밍을 했다. 그리고 그 경험이 내가 개발을 대하는 태도에 많은 영향을 끼쳤다.
줄임말보단 정식표현 `우아한테크코스` 어떨까요? 저희뿐만 아니라 다른 사람들도 읽을 수 있으니까요!

2021-03-28 08:23 UTC, Hyeon9mak commented on joy_level_1.md
> +하지만 하나의 프로젝트, 하나의 컴퓨터로 개발을 하면 얘기가 달라진다.
`이 경우` 에 대한 설명이 살짝만 덧붙여지면 좋을 거 같아요! 👍 
혼자 혹은 학원에서 개별 프로젝트를 진행한 경험이나 강의 내용에 대해 토론한 것?!

2021-03-28 08:23 UTC, Hyeon9mak commented on joy_level_1.md
> +끊임없이 의심하고 서로의, 스스로의 생각을 깨야한다.
👍 👍 👍

2021-03-28 08:23 UTC, Hyeon9mak commented on joy_level_1.md
> +"구현하기 바쁜데 무슨 아이스 브레이킹이야?"
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ 모두 똑같군요.. 🤪

2021-03-28 08:23 UTC, Hyeon9mak commented on joy_level_1.md
> +우테코 들어오기 전엔 뭘 했는지, 취미가 뭔지, 맛집 공유도 하면서 잡담을 했다.
역시 `우아한테크코스`!

2021-03-28 08:23 UTC, Hyeon9mak commented on joy_level_1.md
> +"구현하기 바쁜데 무슨 아이스 브레이킹이야?"
??? : 밥부터 먹고 할까요?

2021-03-28 08:23 UTC, Hyeon9mak commented on joy_level_1.md
> +하지만 실제는 예상과 다르게 흘러갔다. 페어와 의견이 다른 부분이 많았고 토론하는 시간이 길어졌다.
`실제는`->`현실은` 은 어떨까요?
`하지만 ~ 않았다` 등의 표현도 좋을거같아요!

2021-03-28 08:23 UTC, Hyeon9mak commented on joy_level_1.md
> +난 이번 페어와 충분한 신뢰를 쌓지 못했다. 전의 페어와는 미션을 하면서 서로 비슷한 코딩 스타일을 통해서 신뢰가 쌓인 것이었다.
`전의 페어`가 어떤 미션의 페어인지 바로 떠올릴 수 있으면 좋겠어요!

2021-03-28 08:23 UTC, Hyeon9mak commented on joy_level_1.md
> +> 잡담을 많이 나누는 것이 경쟁력이다.
오우 깔끔하게 예시로 요약 👍 👍 👍 👍

2021-03-28 08:30 UTC, Joyykim commented on joy_level_1.md
> +어느새 우테코 Level-1이 끝나간다. 그 동안 4명의 크루와 페어 프로그래밍을 했다. 그리고 그 경험이 내가 개발을 대하는 태도에 많은 영향을 끼쳤다.
디테일한 배려 좋아요~ 반영할게요!

2021-03-28 08:32 UTC, Joyykim commented on joy_level_1.md
> +"구현하기 바쁜데 무슨 아이스 브레이킹이야?"
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ밥부터 먹고 리뷰하시죠🤣

2021-03-28 09:03 UTC, Joyykim commented on joy_level_1.md
> +하지만 하나의 프로젝트, 하나의 컴퓨터로 개발을 하면 얘기가 달라진다.
오호 반영해볼게요~

2021-03-28 09:04 UTC, Joyykim commented on joy_level_1.md
> +끊임없이 의심하고 서로의, 스스로의 생각을 깨야한다.
실력이 미숙하다보니 주로 깨지는 건 제 쪽이더라고요..ㅎㅎ

2021-03-28 09:05 UTC, Joyykim commented on joy_level_1.md
> +우테코 들어오기 전엔 뭘 했는지, 취미가 뭔지, 맛집 공유도 하면서 잡담을 했다.
🙆‍♂️

2021-03-28 09:09 UTC, Joyykim commented on joy_level_1.md
> +하지만 실제는 예상과 다르게 흘러갔다. 페어와 의견이 다른 부분이 많았고 토론하는 시간이 길어졌다.
조금 수정해봤어요~

2021-03-28 09:10 UTC, Joyykim commented on joy_level_1.md
> +난 이번 페어와 충분한 신뢰를 쌓지 못했다. 전의 페어와는 미션을 하면서 서로 비슷한 코딩 스타일을 통해서 신뢰가 쌓인 것이었다.
반! 영!

2021-03-28 09:10 UTC, Joyykim commented on joy_level_1.md
> +> 잡담을 많이 나누는 것이 경쟁력이다.
😜

2021-03-28 11:07 UTC, hchayan reviewed
저도 정말 스타일이 달랐던 크루와 할 때 이런부분에서 많은 고민들이 있었는데 ㅠㅠ
서로를 신뢰하는것이 정말 중요한것 같습니다..!

2021-03-28 11:07 UTC, hchayan commented on joy_level_1.md
> +어느새 우아한테크코스 Level-1이 끝나간다. 그 동안 4명의 크루와 페어 프로그래밍을 했다. 그리고 그 경험이 내가 개발을 대하는 태도에 많은 영향을 끼쳤다.
```suggestion
어느새 우아한테크코스 Level-1이 끝나간다. 그 동안 4명의 크루와 페어 프로그래밍을 했다. 그리고 그 경험들은 개발에 대한 태도에 많은 영향을 끼쳤다.
```

나 라는 단어는 안쓰는게 좋을것 같아요..! 😁

2021-03-28 11:07 UTC, hchayan commented on joy_level_1.md
> +잡담은 신뢰를 만들어나가는 원료다. 잡담을 통해 유대감을 만들고 유대감이 쌓여 신뢰로 발전한다!
```suggestion
잡담은 신뢰를 만들어나가는 원료다. 잡담을 통해 유대감을 만들고 신뢰로 발전한다!
```

중복된 표현 제거!!

2021-03-28 11:07 UTC, hchayan commented on joy_level_1.md
> +"페어랑 20분은 얘기하고 시작하세요 안그러면 싸움납니다"라고 포비는 조언했지만 나에겐 와닿지 않았다.
```suggestion
"페어랑 20분은 얘기하고 시작하세요 안그러면 싸움납니다"라고 포비는 조언했지만 그렇게 와닿지 않았다.
```

2021-03-28 11:59 UTC, Joyykim commented on joy_level_1.md
> +어느새 우아한테크코스 Level-1이 끝나간다. 그 동안 4명의 크루와 페어 프로그래밍을 했다. 그리고 그 경험이 내가 개발을 대하는 태도에 많은 영향을 끼쳤다.
> '나' 혹은 '저' 로 시작하는 문장은 되도록이면 쓰지 않는다.
(지루하게 시작하는 문장을 줄이자.)

오잉? 혹시 미션 요구사항을 말씀하시는 거라면 '나'로 **시작하는** 문장을 쓰지 않는 것 아닌가요??🧐

2021-03-28 11:59 UTC, Joyykim commented on joy_level_1.md
> +어느새 우아한테크코스 Level-1이 끝나간다. 그 동안 4명의 크루와 페어 프로그래밍을 했다. 그리고 그 경험이 내가 개발을 대하는 태도에 많은 영향을 끼쳤다.
`경험이` -> `경험은`으로 변경하는게 좋겠네요ㅎㅎ

2021-03-28 12:04 UTC, Joyykim commented on joy_level_1.md
> +잡담은 신뢰를 만들어나가는 원료다. 잡담을 통해 유대감을 만들고 유대감이 쌓여 신뢰로 발전한다!
`잡담을 통해 유대감을 만들고`와 `유대감이 쌓여 신뢰로 발전한다!`를 따로 봤는데 중복된다고 볼 수 도 있겠네용

`잡담을 통해 유대감을 만든다. 그리고 유대감이 쌓여 신뢰로 발전한다!` 이건 어떤가요??!

2021-03-28 13:34 UTC, iborymagic reviewed
재밌게 잘 읽었어용~

다른 분들이 이미 멋지게 리뷰를 해놓으셔서

제가 리뷰할 게 별로 없네요..

그저 저의 개인적인 취향들로 리뷰를 해봤으니, 맘에 안드시면 반영하지 않으셔도 됩니다!

2021-03-28 13:34 UTC, iborymagic commented on joy_level_1.md
> +어느새 우아한테크코스 Level-1이 끝나간다. 그 동안 4명의 크루와 페어 프로그래밍을 했다. 그리고 그 경험이 내가 개발을 대하는 태도에 많은 영향을 끼쳤다.
```suggestion
잠깐, 둘이서 하나의 컴퓨터로? 그런 비효율적인 짓을 한다니? 이해는 가지 않지만 까라면 까야지 뭐...  

어느새 우아한테크코스 Level-1이 끝나간다. 그 동안 4명의 크루와 페어 프로그래밍을 했다. 그리고 그 경험은 개발을 대하는 나의 태도에 많은 영향을 끼쳤다.
```
저는 요렇게 고쳐봤습니당..
'잠깐, 둘이서 ~' 부터 '~ 까라면 까야지 뭐...' 까지는 우테코를 막 시작한 시점인 것 같고,
그 이후는 레벨 1이 끝나가는 시점인 것 같아서, 공백을 주면 어떨까 생각했어염

2021-03-28 13:34 UTC, iborymagic commented on joy_level_1.md
> +끊임없이 의심하고 서로의, 스스로의 생각을 깨야한다.
공감!

2021-03-28 13:34 UTC, iborymagic commented on joy_level_1.md
> +제한 시간은 다가오면서 마음이 급해져 서로 각자 리팩터링하기로하고 헤어졌다.
```suggestion
제한 시간이 다가오면서 마음이 급해져 각자 리팩터링하기로하고 헤어졌다.
```
개인적인 생각이에용

2021-03-28 13:54 UTC, Hyeon9mak approved these changes
피드백 반영해주신 부분 잘 읽었어요! 특히
`학원 동기들과 팀 프로젝트를 하면서 서로의 조언을 구했다. 각자 기능을 분배해서 작업하다보니 서로의 코드에 깊이 관여하지 않았다.` 에서 팀 프로젝트를 하는 모습이 그려지네요.
피드백 반영 대성공입니다! 👍 👍 👍 
상으로 Approve를 드리겠습니다!
남은 미션 컨디션 조절 잘 하시면서 해내시고, 목요일 회식날 가벼운 마음으로 봅시다!

2021-03-28 14:20 UTC, Joyykim commented on joy_level_1.md
> +제한 시간은 다가오면서 마음이 급해져 서로 각자 리팩터링하기로하고 헤어졌다.
굿굿!!!

2021-03-28 14:20 UTC, Joyykim commented on joy_level_1.md
> +끊임없이 의심하고 서로의, 스스로의 생각을 깨야한다.
😆

2021-03-28 14:21 UTC, Joyykim commented on joy_level_1.md
> +어느새 우아한테크코스 Level-1이 끝나간다. 그 동안 4명의 크루와 페어 프로그래밍을 했다. 그리고 그 경험이 내가 개발을 대하는 태도에 많은 영향을 끼쳤다.
오호라 이게 더 자연스럽네요 고마워요ㅎㅎ

2021-03-28 14:22 UTC, Joyykim commented on joy_level_1.md
> +"페어랑 20분은 얘기하고 시작하세요 안그러면 싸움납니다"라고 포비는 조언했지만 나에겐 와닿지 않았다.
혹시 이것도 **"나로 시작하는 문장 쓰지않기"** 요구사항인가용?

2021-03-28 15:18 UTC, jujubebat approved these changes
안녕하세요! 조이 😆
글 정말 잘 읽었습니다. 👍 페어 프로그래밍 관련 부분에서 많은 걸 느낄 수 있었어요.
크게 문제점을 찾을 수 없는 좋은 글이라 소소한 피드백 몇가지 남기고 가볼게요!!
수고 많으셨습니다. 😊

2021-03-28 15:18 UTC, jujubebat commented on joy_level_1.md
> +끊임없이 의심하고 서로의, 스스로의 생각을 깨야한다.
```suggestion
끊임없이 의심하고 서로 각자의 생각을 깨야한다.
```

2021-03-28 15:18 UTC, jujubebat commented on joy_level_1.md
> +끊임없이 의심하고 서로의, 스스로의 생각을 깨야한다.
이렇게 바꾸어 보는 것은 어떨까요?!

2021-03-28 15:18 UTC, jujubebat commented on joy_level_1.md
> +"오류만 안나면 되지 뭐~"
```suggestion
"오류만 안 나면 되지 뭐~"
```

2021-03-28 15:18 UTC, jujubebat commented on joy_level_1.md
> +"오류만 안나면 되지 뭐~"
사소한 띄어쓰기 오류 확인해봤어요!! 😃

2021-03-28 15:18 UTC, jujubebat commented on joy_level_1.md
> +> 잡담을 많이 나누는 것이 경쟁력이다.
성장을 위한 의식적인 노력 저도 실천해봐야겠네요 👍

2021-03-28 15:34 UTC, hchayan approved these changes

2021-03-28 15:36 UTC, hchayan commented on joy_level_1.md
> +어느새 우아한테크코스 Level-1이 끝나간다. 그 동안 4명의 크루와 페어 프로그래밍을 했다. 그리고 그 경험이 내가 개발을 대하는 태도에 많은 영향을 끼쳤다.
나, 내 이런 표현들 자체를 제거해도 자연스러워서 빼는것을 추천드렸어요 ㅎㅎ

2021-03-28 15:37 UTC, hchayan commented on joy_level_1.md
> +잡담은 신뢰를 만들어나가는 원료다. 잡담을 통해 유대감을 만들고 유대감이 쌓여 신뢰로 발전한다!
네 중복된 표현이라 생각했던 부분이였는데 분리하면 작성하신거 같이 적어도 괜찮은거 같아요!!

2021-03-28 15:37 UTC, hchayan commented on joy_level_1.md
> +"페어랑 20분은 얘기하고 시작하세요 안그러면 싸움납니다"라고 포비는 조언했지만 나에겐 와닿지 않았다.
이건 제 개인적인 취향입니다... ㅎㅎㅎ

2021-03-28 16:42 UTC, Joyykim commented on joy_level_1.md
> +끊임없이 의심하고 서로의, 스스로의 생각을 깨야한다.
서로의 생각도 깨고 각자의 생각도 깬다는 뜻으로 썼는데, `서로 각자의`라고 하면 서로 자기 생각만 깬다는 의미로 들리네요ㅜ!

2021-03-28 16:42 UTC, Joyykim commented on joy_level_1.md
> +"오류만 안나면 되지 뭐~"
ㅋㅋㅋㅋ오류발견 고마워요~

2021-03-28 17:52 UTC, iborymagic approved these changes
좋은 글 재밌게 잘 읽었슴다!!
곧 만날 수 있기를 기원해봅니다..!

2021-04-12 08:54 UTC, Wonmi91 approved these changes
안녕하세요 조이 :)

조이가 직접 겪었던 일화를 통해 한 달 동안 무엇을 깨달았는지 쉽고 재밌게 알 수 있어서 좋았어요.
사람은 경험을 통해 얻는 게 정말 많은 것 같아요. 직접 경험해보지 않으면 모르는 것들이 참 많죠.
레벨 1 기간 동안 조이가 직접 경험하고 알게 된 것들을 발전시켜 더 많은 사람들과 신뢰를 쌓아갈 수 있길 바랄게요!

사소하지만, 혹~시나 중간중간 큰따옴표로 쓴 부분들이 조이의 ‘생각’이었다면 작은따옴표로 작성해 주셔도 될 것 같아요.
잘 읽었습니다!

2021-04-12 08:54 UTC, merged