[레벨 1 글쓰기 미션] 동동(김동희) 미션 제출합니다.
woowacourse/woowa-writing-3 pull request #74
Opened 2021-03-28 13:09 UTC by bigsaigon333

안녕하세요 프론트엔드 개발을 하고 있는 동동(김동희)입니다.

글쓰기 미션이 이제껏 한 미션 중 제일 어려웠네요...

미루다 미루다, 도무지 글이 안써져서 맥주 한 잔 :beer:  마시고 후다닥 글을 썼습니다. 

우아한테크코스 한 달 생활기라는 주제와 약간 어긋나는 내용은 아닌가 싶네요.. 

[:fire: 글보러가기 :fire: ](https://github.com/bigsaigon333/woowa-writing-3/blob/step1/step1.md)

<br>

리뷰해주실 조이 현구막, 피터, 우기, 인치, 피케이 께 미리 감사의 말씀올립니다 :bow: :bow: :bow: 

리뷰는 천천히 해주셔도 괜찮고, 리뷰 없이 그냥 approve 해주셔도 완전 괜찮고,  실수로 merge까지 해주시면 더욱 땡큐입니다 :ok_man:

2021-03-28 13:13 UTC, seojihwan commented on step1.md
> +기억보단 기록을.
멋진말이네요! 저도 기록하는 습관을 길러야 겠어요  👍👍

2021-03-28 13:41 UTC, Hyeon9mak reviewed
안녕하세요 동동! 세상에나... 우아한테크코스 홍보 글을 읽는 줄 알았네요 ㅋㅋㅋ 🤣 👍 
맥주의 힘인가요? 🍺 

글 전반적으로 어떤 말을 하고싶으신지 전해져서, 문법에 관해서만 피드백 몇 가지 남겼어요!
남은 우테코 생활 같이 파이팅해요! 🔥 🔥 🔥

2021-03-28 13:41 UTC, Hyeon9mak commented on step1.md
> +## 우아한테크코스 두달 생활기
https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=62492

숫자는 띄어서 사용한다고 하네요! `두 달 생활기`가 되지 않을까 싶어요!

2021-03-28 13:41 UTC, Hyeon9mak commented on step1.md
> +대학에 가서는 대학 친구들이 또 취업 시의 암묵적 경쟁상대가 되었습니다.
- `대학에 가서는 대학 친구들이` 이 부분도 취향이긴한데, `대학에선 동기들이`는 어떠실까요?!

- 바로 윗 줄의 `경쟁상대`와 `경쟁 상대` 띄어쓰기가 서로 다르네요!

2021-03-28 13:41 UTC, Hyeon9mak commented on step1.md
> +그렇게 중・고등학교, 대학, 군대, 회사를 통해 경쟁 지향적인 사회를 저도 모르게 자연스럽게 받아드려 왔습니다.
- https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=114219
`받아들이다`가 맞다고 하네요!

- 첫 문장에서 `제가 겪어온 교육과정들은`에 군대와 회사가 추가되면서 `사회`로 바꼈어요! 통일을 해주시면 더 자연스러울 것 같아요.

2021-03-28 13:41 UTC, Hyeon9mak commented on step1.md
> +이러한 페어 프로그래밍이야말로 우아한테크코스가 지향하는 가치를 명확히 보여주며, 올바른 방향으로 제가 성장해 나가고 있다는 확신을 줍니다.
와우 우아한테크코스 홍보문구인줄 알았네요 🤣 👍

2021-03-28 13:41 UTC, Hyeon9mak commented on step1.md
> +우아한테크코스에서의 2달을 보낸 지금의 저는 어떤 모습인지 곰곰이 생각해봅니다.
여기선 숫자가! 통일 해주시면 좋을거 같아요!

2021-03-28 13:41 UTC, Hyeon9mak commented on step1.md
> +지금도 미션이 4개나 밀려있습니다.
동동도? 저도.. 😨

2021-03-28 13:41 UTC, Hyeon9mak commented on step1.md
> +기술보다 사람이 먼저인 것을 잊지 않기 위해 노력해야겠습니다.
이 문장이 끝난 후 문단을 한 번 나눠주시면 더 좋을거 같아요!

2021-03-28 13:41 UTC, Hyeon9mak commented on step1.md
> +8달 뒤에는 우아한테크코스가 지향하는 가치를 온전히 다 받아들여 더욱더 성장한 저 자신이, 우리들이 되어있기를 바라봅니다.
`여덟 달` 혹은 `8개월` 표현은 어떨까요? 👍

2021-03-28 13:45 UTC, iborymagic reviewed
와 재밌게 잘 읽었어요!
동동은 항상 잘하는 이미지가 있어서 별 고민이 없을 줄 알았는데
저와 비슷한 고민을 하고 있다는 게 신기하네요.
리뷰는 개인적인 취향을 가득 담은 리뷰이니까, 맘에 들지 않으시면 그냥 넘어가셔도 돼용

2021-03-28 13:45 UTC, iborymagic commented on step1.md
> +그렇게 중・고등학교, 대학, 군대, 회사를 통해 경쟁 지향적인 사회를 저도 모르게 자연스럽게 받아드려 왔습니다.
```suggestion
그렇게 중・고등학교, 대학, 군대, 회사를 통해 경쟁 지향적인 사회를 저도 모르게 자연스럽게 받아들여 왔습니다.
```

2021-03-28 13:45 UTC, iborymagic commented on step1.md
> +저 스스로는 당연하다고 생각했던 것을 페어가 왜 그렇냐고 물어보면, '어? 이게 맞는 건데? 근데 왜 맞는 거지?'' 라고 생각하게 됩니다. 페어를 설득하기 위해 레퍼런스를 검색해봅니다.
ㅋㅋㅋㅋ 진짜 공감되네요

2021-03-28 13:45 UTC, iborymagic commented on step1.md
> +제가 알고 싶어서, 페어를 설득하고 싶어서, 진리를 탐구합니다.
```suggestion
제가 알고 싶어서, 페어를 설득하고 싶어서, 지식을 탐구합니다.
```
요건 저도 좀 애매하긴 한데, '진리'는 뭔가 '지식'보다는 '지혜'에 가까운 느낌이 들어서
고냥 개인적인 느낌으로다가 단어만 살짝 한 번 고쳐봤습니당

2021-03-28 13:45 UTC, iborymagic commented on step1.md
> +기억보단 기록을.
저랑 같은 고민을 가지고 계시네요!
같이 화이팅해봅시다!!

2021-03-28 14:13 UTC, Joyykim approved these changes
정말 잘 쓰시는데요?? 맥주의 힘일까요ㅋㅋ🍺
공감가는 내용이 많아서 재밌게 읽었어요~!
다음에 루터에서 마주치면 인사해요👋

2021-03-28 14:13 UTC, Joyykim commented on step1.md
> +남의 성장이 곧 나의 성장이 됩니다.
전 `남`이라고 하면 찌끔 부정적인? 그런 뉘앙스가 드는데 동동은 어떤가요ㅎㅎ
`옆 사람`도 좋고 `크루`도 좋을 것 같아요!

2021-03-28 14:13 UTC, Joyykim commented on step1.md
> +'페어 프로그래밍'에서는 두 명이 하나의 프로그램을 같이 개발합니다.
두 명이 하나의 컴퓨터로 개발한다는게 페어 프로그래밍의 핵심이지 않을까 싶어요!ㅎㅎ
팀이 하나의 프로그램을 개발하는건 페어 프로그래밍 말고도 많으니까요~!

2021-03-28 14:13 UTC, Joyykim commented on step1.md
> +지금도 미션이 4개나 밀려있습니다.
yanadoo...🥲

2021-03-28 14:13 UTC, Joyykim commented on step1.md
> +분명히 처음 우아한테크코스를 시작했을 때에는 동료들에게 믿음을 주는 프로그래머로 성장하자고 다짐했었습니다.
`분명히`는 빼도 의미가 잘 전달될 것 같아요!!

`동료들에게 믿음을 주는 프로그래머`가 목표라니, 꼭 같이 일해보고 싶네요😆

2021-03-28 14:13 UTC, Joyykim commented on step1.md
> +한 팀이 되어 성과를 내므로 개인보다 전체가 중요시될 것 같은 회사입니다.
```suggestion
회사는 다같이 한 팀이 되어 성과를 내기 때문에 경쟁보다 협력이 중요할거라 기대했습니다.
```
`개인보다 전체가 중요시`라는 표현이 뭔가 전체주의적인 느낌이 드네용. 아마 공통된 팀의 목표를 향해 다같이 노력한다~ 라는 느낌으로 쓰고 싶으셨던 걸까요? 뒤의 문장을 보니 그런 것 같네요!

`기대`라는 표현을 써봤는데 동동 맘대로 취사선택해주세요ㅎㅎ

2021-03-28 14:44 UTC, pkeugine requested changes
🙌안녕하세요 동동!!!
피케이입니다 :)

경쟁이 너무나도 자연스러웠던 우리... 어쩔 땐 진짜 피곤해지죠.
그래서 이 곳이 더 의미있을지도 모르겠습니다.
동동 말대로 내 곁에 있는 크루의 성장은 곧 제가 성장할 추진력이 되니까요.

글 정말 잘 읽었어요.
하지만 아쉽게도 실수로 머지하지는 않을겁니다 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
기.필.코. 수정을 해야 approve 할거니까, 긴장하라구요!!! 😂

2021-03-28 14:44 UTC, pkeugine commented on step1.md
> +대학에 가서는 대학 친구들이 또 취업 시의 암묵적 경쟁상대가 되었습니다.
```suggestion
대학에서는 동기들이 또 취업전선의 암묵적인 경쟁 상대가 되었습니다.
```
현구막의 리뷰를 이어받아 이렇게 수정해보는 건 어떨까요? 😁

2021-03-28 14:44 UTC, pkeugine commented on step1.md
> +그렇게 중・고등학교, 대학, 군대, 회사를 통해 경쟁 지향적인 사회를 저도 모르게 자연스럽게 받아드려 왔습니다.
ㅠㅜ 힘든 나날의 연속....

2021-03-28 14:44 UTC, pkeugine commented on step1.md
> +남의 성장이 곧 나의 성장이 됩니다.
크루! 저도 크루가 좋다고 생각해요!!

2021-03-28 14:44 UTC, pkeugine commented on step1.md
> +'페어 프로그래밍'에서는 두 명이 하나의 프로그램을 같이 개발합니다.
@Joyykim 이 표현 어디서 읽어본 것 같은데 🤔 ㅋㅋㅋㅋㅋㅋㅋ

2021-03-28 14:44 UTC, pkeugine commented on step1.md
> +제가 알고 싶어서, 페어를 설득하고 싶어서, 진리를 탐구합니다.
```suggestion
제가 알고 싶어서, 그리고 페어를 설득하고 싶어서 끊임없이 지식을 탐구합니다.
```
저도 피터와 동의합니다. 그리고 더 나아가 문장을 살짝 더 바꿔봤어요!

2021-03-28 14:44 UTC, pkeugine commented on step1.md
> +이러한 페어 프로그래밍이야말로 우아한테크코스가 지향하는 가치를 명확히 보여주며, 올바른 방향으로 제가 성장해 나가고 있다는 확신을 줍니다.
```suggestion
이러한 페어 프로그래밍이야말로 우아한테크코스가 지향하는 가치를 명확히 보여주며, 제 자신이 올바른 방향으로 성장해 나가고 있다는 확신을 줍니다.
```
딱히 중요하진 않지만 조금 더 부드럽게 이어지지 않나 싶어요!

2021-03-28 14:44 UTC, pkeugine commented on step1.md
> +지금도 미션이 4개나 밀려있습니다.
<img width="162" alt="Screen Shot 2021-03-28 at 11 39 35 PM" src="https://user-images.githubusercontent.com/48251668/112756176-fc39d800-901e-11eb-877f-b4fb3f631205.png">
🤯

2021-03-28 14:44 UTC, pkeugine commented on step1.md
> +앞으로 우아한테크코스에서의 8달 생활이 너무 기대됩니다.
동동 파이팅입니다!!! 기억보단 기록을, 함께 지켜보도록 최선을 다해보자구요!!!! 🔥 🔥 🔥 🔥

2021-03-28 14:59 UTC, pkeugine approved these changes

2021-03-28 15:05 UTC, jujubebat approved these changes
안녕하세요 동동!! 
글의 분위기가 잔잔해서 제 스타일이네요 차분하게 잘 읽을 수 있었어요 👍👍
크게 흠이 없고 다른 분들이 이미 리뷰 주신 부분들이 많아서 크게 피드백할 부분이 없었습니다 ㅎㅎ
수고하셨습니다. 😊

2021-03-28 15:05 UTC, jujubebat commented on step1.md
> +'아무리 흐린 먹물이라도 가장 훌륭한 기억력보다 낫다'라는 중국 속담이 있다고 합니다.
멋진 속담이네요 저도 잠시 멈췄던 블로그 활동을 다시 시작해봐야겠어요 ㅎㅎ

2021-03-28 15:05 UTC, jujubebat commented on step1.md
> +8달 뒤에는 우아한테크코스가 지향하는 가치를 온전히 다 받아들여 더욱더 성장한 저 자신이, 우리들이 되어있기를 바라봅니다.
```suggestion
8달 뒤에는 우아한테크코스가 지향하는 가치를 온전히 다 받아들여 성장한 우리가 되어있기를 바라봅니다. 
```

2021-03-28 15:05 UTC, jujubebat commented on step1.md
> +8달 뒤에는 우아한테크코스가 지향하는 가치를 온전히 다 받아들여 더욱더 성장한 저 자신이, 우리들이 되어있기를 바라봅니다.
우리라는 표현은 동동 자신도 포함하지 않나요?? 위와 같이 제안드려 볼게요 😀

2021-03-28 15:09 UTC, Joyykim commented on step1.md
> +'페어 프로그래밍'에서는 두 명이 하나의 프로그램을 같이 개발합니다.
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ😉

2021-03-28 15:48 UTC, hchayan reviewed
동동 잘 읽었어요..!
정말 경쟁 시대에 살아가는 우리에게
우테코의 과정은 정말 많은 부분을 경험하게 해주는
몇 없는 기회인거 같아요..!
같이 남은 기간동안 열심히 해봅시다 😁😁

2021-03-28 15:48 UTC, hchayan commented on step1.md
> +하지만 회사 동기들도 눈앞의 성과급을 두고, 언젠가의 승진 자리를 두고 경쟁하는 상대가 되었습니다.
```suggestion
하지만 회사 동기들도 성과급과 승진 자리를 두고 경쟁하는 상대가 되었습니다.
```
조금 추상적으로, 성과급과 승진 자리를 설명해도 괜찮을꺼같아요..!

2021-03-28 15:48 UTC, hchayan commented on step1.md
> +저 스스로는 당연하다고 생각했던 것을 페어가 왜 그렇냐고 물어보면, '어? 이게 맞는 건데? 근데 왜 맞는 거지?'' 라고 생각하게 됩니다. 페어를 설득하기 위해 레퍼런스를 검색해봅니다.
스스로의 코드를 변론하는 나날이 ㅋㅋㅋ

2021-03-28 15:48 UTC, hchayan commented on step1.md
> +기록을 남기면, 다시 되돌아보지 않더라도 기록을 남기는 행위 자체로 마음속에 깊이 각인됩니다.
제게도 정말 와닿는 말인거 같아요 🤣

2021-03-28 17:50 UTC, iborymagic approved these changes
글 재밌게 잘 읽었어요!!
우테코 생활 열심히 해봅시닷!

2021-03-29 05:05 UTC, bigsaigon333 commented on step1.md
> +## 우아한테크코스 두달 생활기
말씀해주신 사항 반영하였습니다!

2021-03-29 06:42 UTC, bigsaigon333 commented on step1.md
> +대학에 가서는 대학 친구들이 또 취업 시의 암묵적 경쟁상대가 되었습니다.
`대학에서는 동기들이 취업전선의 암묵적인 경쟁 상대가 되었습니다. `
 로 수정하였습니다!

2021-03-29 06:43 UTC, bigsaigon333 commented on step1.md
> +그렇게 중・고등학교, 대학, 군대, 회사를 통해 경쟁 지향적인 사회를 저도 모르게 자연스럽게 받아드려 왔습니다.
`제가 겪어온 사회는 모두 경쟁의 연속이었습니다.`

`그렇게 중・고등학교, 대학, 군대, 회사를 거치며 경쟁 지향적인 사회를 저도 모르게 자연스럽게 받아들여 왔습니다.`

교육과정을 사회로 수정하였습니다!

2021-03-29 06:44 UTC, bigsaigon333 commented on step1.md
> +우아한테크코스에서의 2달을 보낸 지금의 저는 어떤 모습인지 곰곰이 생각해봅니다.
`우아한테크코스에서의 두 달을 보낸 지금의 저는 어떤 모습인지 곰곰이 생각해봅니다.` 으로 수정하였습니다 :smile:

2021-03-29 06:44 UTC, bigsaigon333 commented on step1.md
> +8달 뒤에는 우아한테크코스가 지향하는 가치를 온전히 다 받아들여 더욱더 성장한 저 자신이, 우리들이 되어있기를 바라봅니다.
`여덟 달` 으로 수정하였습니다 :smile:

2021-03-29 06:45 UTC, bigsaigon333 commented on step1.md
> +그렇게 중・고등학교, 대학, 군대, 회사를 통해 경쟁 지향적인 사회를 저도 모르게 자연스럽게 받아드려 왔습니다.
수정하였습니다 감사합니다~~

2021-03-29 06:46 UTC, bigsaigon333 commented on step1.md
> +제가 알고 싶어서, 페어를 설득하고 싶어서, 진리를 탐구합니다.
`제가 알고 싶어서. 그리고 페어를 설득하고 싶어서. 끊임없이 지식을 탐구합니다.`  로 수정하였습니다!

  그리고 를 넣으니까, 쉼표보다 구둣점을 넣는게 더 자연스러운 거 같아서 바꾸었는데, 어떠신지 의견 남겨주시면 감사하겠습니다~~

2021-03-29 06:47 UTC, bigsaigon333 commented on step1.md
> +남의 성장이 곧 나의 성장이 됩니다.
`다른 크루의 성장이 곧 나의 성장이 됩니다.`   

저 자신도 한 명의 크루라고 할 때, 제가 포함되지 않는 다른 크루들이라는 걸 좀 더 명확히 하고 싶어서 `다른 크루` 로 해보았는데, 어떠신가요...? 그냥 크루가 더 나을까요?

2021-03-29 06:48 UTC, bigsaigon333 commented on step1.md
> +분명히 처음 우아한테크코스를 시작했을 때에는 동료들에게 믿음을 주는 프로그래머로 성장하자고 다짐했었습니다.
분명히 삭제하는 것으로 수정하였습니다~~!

3단계 프로젝트때 만나요~ :heart:

2021-03-29 06:49 UTC, bigsaigon333 commented on step1.md
> +한 팀이 되어 성과를 내므로 개인보다 전체가 중요시될 것 같은 회사입니다.
`회사는 모두가 한 팀이 되어 성과를 내기 때문에 경쟁보다 협력이 중요할 거라 생각했습니다.` 로 바꾸어보았습니다!

첨에 기대했습니다 라고 수정하였는데, 읽다보니 제가 딱히 회사에서는 협업을 하고 싶다! 라고 기대하지는 않은 것 같아서, `생각`이라고 하였어요 :smile:

2021-03-29 06:49 UTC, bigsaigon333 commented on step1.md
> +이러한 페어 프로그래밍이야말로 우아한테크코스가 지향하는 가치를 명확히 보여주며, 올바른 방향으로 제가 성장해 나가고 있다는 확신을 줍니다.
`이러한 페어 프로그래밍이야말로 우아한테크코스가 지향하는 가치를 명확히 보여주며, 저 자신이 올바른 방향으로 성장해 나가고 있다는 확신을 줍니다.` 

부산대 맞춤법 검색기가 `저 자신`으로 하라고 해서 `저 자신`으로 수정했어요 ㅎㅎ..

2021-03-29 06:50 UTC, bigsaigon333 commented on step1.md
> +8달 뒤에는 우아한테크코스가 지향하는 가치를 온전히 다 받아들여 더욱더 성장한 저 자신이, 우리들이 되어있기를 바라봅니다.
`여덟 달 뒤에는 우아한테크코스가 지향하는 가치를 온전히 다 받아들여 더욱더 성장한 우리가 되어있기를 바라봅니다.`  로 수정하였습니다!

2021-03-29 06:50 UTC, bigsaigon333 commented on step1.md
> +하지만 회사 동기들도 눈앞의 성과급을 두고, 언젠가의 승진 자리를 두고 경쟁하는 상대가 되었습니다.
`하지만 회사 동기들도 성과급과 승진 자리를 두고 경쟁하는 상대가 되었습니다.` 로 수정하였습니다!

2021-03-29 06:52 UTC, bigsaigon333 commented on step1.md
> +기술보다 사람이 먼저인 것을 잊지 않기 위해 노력해야겠습니다.
```
우아한테크코스에서의 두 달을 보낸 지금의 저는 어떤 모습인지 곰곰이 생각해봅니다.
첫째, 소프트스킬은 내팽개치고 기술에만 집착하고 있는 모습인 것 같습니다.
처음 우아한테크코스를 시작했을 때에는 동료들에게 믿음을 주는 프로그래머로 성장하자고 다짐했었습니다.
프론트엔드 개발의 최고 실력자가 아니라, 일을 믿고 맡길 수 있고, 배울 점이 있고, 같이 일하면 항상 기분이 좋은 그런 동료가 되자고.
그런데 어느새인가 기술에 집착하고 있는 것 같습니다.
기술을 다루는 것은 사람이고, 그 기술 또한 궁극적으로는 사람을 위한 것입니다.
기술보다 사람이 먼저인 것을 잊지 않기 위해 노력해야겠습니다.
둘째, 항상 일정에 쫓기는 모습인 것 같습니다.
정말 매일 정신없이 지내왔습니다.
지금도 미션이 4개나 밀려있습니다.
딱히 늑장을 부리거나 게으름을 피운 적은 없지만, 결과적으로 시간 관리를 잘하지 못했습니다.
여유가 없어지니 항상 일정에 쫓기어 마음이 불편합니다.
시간 관리 능력을 길러야겠습니다.
셋째, 매일매일의 성장을 기록으로 잘 남기지 못하고 있는 것 같습니다.
'아무리 흐린 먹물이라도 가장 훌륭한 기억력보다 낫다'라는 중국 속담이 있다고 합니다.
기록을 남기면, 설령 다시 찾아보지 않더라도 기록을 남기는 행위 자체로 마음속에 깊이 각인됩니다.
기억보단 기록을.
```

저의 모습을 곰곰이 뒤돌아보았을 때 세가지 모습이 있는 것 같아서, 그렇게 붙여서 썼었습니다. 한 곳만 띄어쓰기를 하면 어색한것 같아서, 첫째, 둘째, 셋째 네이밍을 하고  각자가 '우아한테크코스에서의 두 달을 보낸 지금의 저는 어떤 모습`에 해당하는지를 구체적으로 기재해보았습니다. 어떠실까요? :smile:

2021-03-29 12:21 UTC, hchayan approved these changes

2021-03-29 13:05 UTC, Hyeon9mak approved these changes

2021-03-29 13:08 UTC, Hyeon9mak approved these changes
동동! 이전에 approve 드렸던게 사라졌군요 😭 
기억을 더듬어서 그 때 approve 멘트를 떠올려보면...

> 우아한테크코스 홍보글을 읽는 줄 알았어요!

밖에 떠오르지 않네요 😄 그만치 우아한테크코스 생활에 대해 자세하게 잘 써주신 글인거 같아요.
다시 approve 드리도록 하겠습니다! 어서 PR쏘시죠!

2021-05-10 06:46 UTC, woowahan-pjs approved these changes
총명불여둔필. 아무리 똑똑하고 기억이 좋더라도 못난 글씨나마 적어 놓는 것을 당하지 못한다. 이만 Merge 할게요.

2021-05-10 06:47 UTC, merged