[레벨 2 글쓰기 미션] 인비(김태희) 미션 제출합니다.
woowacourse/woowa-writing-3 pull request #82
Opened 2021-05-14 07:58 UTC by taehee-kim-dev

### 안녕하세요!! 😄 

글쓰기는 여전히 쉽지 않네요. 😅 

제 글은 아래 링크에서 읽을 수 있어요.
[효율적인 공부를 하자.](https://github.com/taehee-kim-dev/woowa-writing-3/blob/taehee-kim-dev/level2.md)

소중한 시간 내어 제 글 읽어주셔서 감사합니다!!

2021-05-19 07:41 UTC, zigsong reviewed
안녕하세요 인비! Lv2 첫 번째 리뷰네요ㅎㅎ
과거-현재 대조의 방식으로 글을 깔끔하고 담백하게 잘 써주신 것 같아요! 
함께하는 것의 즐거움, 공부할 것이 너무 많아 벅찼지만 마음을 편하게 먹고자 생각하는 부분들이 공감이 많이 되었어요!

사소한 부분들만 코멘트 남깁니다. 확인 부탁드릴게용 😉

2021-05-19 07:41 UTC, zigsong commented on level2.md
> +우테코에서 자연스럽게 야생형(탑 - 다운) 방식으로 학습하게 됐다. 미션을 하면서 모르는 부분이 생기거나, 새로운 것을 도입하고 싶으면 해당 부분만 찾아서 학습한다. 찾아본 내용의 세부 내용에 대해 궁금증이 생기면, __"왜?"__라는 의문이 더 생기지 않을 때까지 깊이 파고든다. 이를 미션에 적용하고 개인 블로그에 정리하면 완전히 내 것이 된 느낌이다.
> __"왜"__

여기도 아마..? 

> 우테코 모의 면접을 통해, 정말 제대로 학습했는지 확인할 수 있다.

조금 갑작스레 모의면접 이야기가 나온 것 같아요!
앞 내용과 살짝 더 이어주면 좋을 것 같습니다 ㅎㅎ

2021-05-19 07:41 UTC, zigsong commented on level2.md
> +책의 첫 글자부터 마지막 글자까지 모두 읽어야 마음이 편했다. 일종의 강박이었다. 그러다 보니 시간도 오래 걸리고, 중요한 부분과 그렇지 않은 부분을 구분하기 어려웠다. 책을 모두 본 뒤에 __"내가 뭘 학습했지?"__ 돌이켜 보면, 떠오르는 게 몇 개 없고 정리가 되지 않았다. 또한, 학습한 내용을 막상 사용하지 않으면, 금세 다시 잊혀졌다. 그래서 학
> __"내가 뭘 학습했지?"__

여기 앞뒤에 언더바를 두 개씩 붙인 게 아마 italic체를 노리신 걸까요...? 마크다운이 안 먹힌 것 같습니다 😂

> 또한, 학습한 내용을 막상 사용하지 않으면, 금세 다시 잊혀졌다.

짧은 문장에 쉼표가 두 개나 있어서, 한 군데는 빼줘도 좋을 것 같아요!

2021-05-19 07:41 UTC, zigsong commented on level2.md
> +위의 상황이 계속되니 점점 해탈하는 것 같다. 어차피 개발자로서 평생 공부해야 하니, 마음을 편하게 가져야 한다는 생각이 문득 들었다. 지금도 과거의 습관이 남아있긴 하지만, 의식적으로 연습하는 중이다. __조급해하거나 불안해하지 않기. 새로운 것을 학습하는 것에 흥미 가지기. "몰라도 돼. 괜찮아."__ 라고 자신에게 말해주기. 이와 같은 노력으로 조금
> __조급해하거나 불안해하지 않기. 새로운 것을 학습하는 것에 흥미 가지기. "몰라도 돼. 괜찮아."__

여기도 아마 마크다운...?

2021-05-19 12:16 UTC, taehee-kim-dev commented on level2.md
> +우테코에서 자연스럽게 야생형(탑 - 다운) 방식으로 학습하게 됐다. 미션을 하면서 모르는 부분이 생기거나, 새로운 것을 도입하고 싶으면 해당 부분만 찾아서 학습한다. 찾아본 내용의 세부 내용에 대해 궁금증이 생기면, __"왜?"__라는 의문이 더 생기지 않을 때까지 깊이 파고든다. 이를 미션에 적용하고 개인 블로그에 정리하면 완전히 내 것이 된 느낌이다.
1. 앗, 마크다운이 안 먹혔네요!! 
2. 다시 읽어보니 저도 어색하군요.. ㅠㅠ

반영했습니다!! 😄

2021-05-19 12:16 UTC, taehee-kim-dev commented on level2.md
> +책의 첫 글자부터 마지막 글자까지 모두 읽어야 마음이 편했다. 일종의 강박이었다. 그러다 보니 시간도 오래 걸리고, 중요한 부분과 그렇지 않은 부분을 구분하기 어려웠다. 책을 모두 본 뒤에 __"내가 뭘 학습했지?"__ 돌이켜 보면, 떠오르는 게 몇 개 없고 정리가 되지 않았다. 또한, 학습한 내용을 막상 사용하지 않으면, 금세 다시 잊혀졌다. 그래서 학
![image](https://user-images.githubusercontent.com/53412998/118810181-8a775f80-b8e6-11eb-99cf-69fcc9ed840c.png)
제게는 먹힌걸로 보이는데.. 서로 다르게 보이나 봐요 😢

2021-05-19 12:16 UTC, taehee-kim-dev commented on level2.md
> +위의 상황이 계속되니 점점 해탈하는 것 같다. 어차피 개발자로서 평생 공부해야 하니, 마음을 편하게 가져야 한다는 생각이 문득 들었다. 지금도 과거의 습관이 남아있긴 하지만, 의식적으로 연습하는 중이다. __조급해하거나 불안해하지 않기. 새로운 것을 학습하는 것에 흥미 가지기. "몰라도 돼. 괜찮아."__ 라고 자신에게 말해주기. 이와 같은 노력으로 조금
![image](https://user-images.githubusercontent.com/53412998/118810350-beeb1b80-b8e6-11eb-9202-c27f113dc3e8.png)

여기도 제게는 마크다운 적용돼서 보이는데, 적용이 안 된걸로 보이나요?? 😭

2021-05-19 12:17 UTC, taehee-kim-dev commented
@zigsong 안녕하세요, 지그!!

좋은 피드백 감사합니다.
반영했어요!!

혹시 계속 마크다운이 적용 안 된 채로 보인다면, 말씀해주세요!!
감사합니다. 🙇

2021-05-19 12:42 UTC, zigsong approved these changes
확인했습니다! 마크다운이 저만 깨져보인 걸까요 😂
전반적으로 글이 군더더기 없어서 많은 피드백 못 드린 것 같아 죄송하네요 ㅜㅜ

피드백 빠른 반영 감사합니다. approve 할게요! 😉

2021-05-23 01:25 UTC, sihyung92 reviewed
인비 하이~~~~ 글 잘 읽었어용~~
학습법에 공감가는 점이 많아 넘넘 재밌게 잘 읽었습니당
리뷰 남겼으니 확인해주세요~~

2021-05-23 01:25 UTC, sihyung92 commented on level2.md
> +학습 방법에 정답은 없다. 필요한 지식, 상황에 따라 적절한 학습 방법을 선택해야 한다. 그것이 효과적이고 스스로 만족스럽다면 자신에게 맞는 학습법이라 생각한다.
완전~~히 동의합니다!! 😀😀😀

2021-05-23 01:25 UTC, sihyung92 commented on level2.md
> +위의 상황이 계속되니 점점 해탈하는 것 같다. 어차피 개발자로서 평생 공부해야 하니, 마음을 편하게 가져야 한다는 생각이 문득 들었다. 지금도 과거의 습관이 남아있긴 하지만, 의식적으로 연습하는 중이다. __조급해하거나 불안해하지 않기. 새로운 것을 학습하는 것에 흥미 가지기. "몰라도 돼. 괜찮아."__ 라고 자신에게 말해주기. 이와 같은 노력으로 조금
방법 중...

AS IS
**"몰라도 돼. 괜찮아."** 라고 자신에게 말해주기. 

TO BE
**"몰라도 돼. 괜찮아."라고 자신에게 말해주기.** 

는 어떨까요?? 말해주는 것 까지가 방법인데 "괜찮아" 까지만 방법인 것 처럼 보여서 조금 헷갈렸어용!
혹은 방법 세가지를 

TO BE
하나, 조급해하거나 불안해하지 ...
둘, 새로운 것을 학습하는 것에 ...
셋, 몰라도 돼... 

이런 식으로 라벨링해주는 것도 좋을 것 같아요! 개인 의견이니 참고만 해주셔요 :)

2021-05-23 01:25 UTC, sihyung92 commented on level2.md
> +우테코에서 자연스럽게 야생형(탑 - 다운) 방식으로 학습하게 됐다. 미션을 하면서 모르는 부분이 생기거나, 새로운 것을 도입하고 싶으면 해당 부분만 찾아서 학습한다. 찾아본 내용의 세부 내용에 대해 궁금증이 생기면, __"왜?"__ 라는 의문이 더 생기지 않을 때까지 깊이 파고든다. 이를 미션에 적용하고 개인 블로그에 정리하면 완전히 내 것이 된 느낌이다
왜지?

2021-05-23 01:25 UTC, sihyung92 commented on level2.md
> +우테코에서 자연스럽게 야생형(탑 - 다운) 방식으로 학습하게 됐다. 미션을 하면서 모르는 부분이 생기거나, 새로운 것을 도입하고 싶으면 해당 부분만 찾아서 학습한다. 찾아본 내용의 세부 내용에 대해 궁금증이 생기면, __"왜?"__ 라는 의문이 더 생기지 않을 때까지 깊이 파고든다. 이를 미션에 적용하고 개인 블로그에 정리하면 완전히 내 것이 된 느낌이다
탑 - 다운이라는 표현에 대해서 개인적으로 조금 아리송 했어용! 해당 방식은 제가 느끼기엔 바텀-업이라고 느껴졌거든요. (전체적으로 공부하지 않고 필요한 부분만 학습하고- **바텀**, 세부 내용을 위해 더 많은 것을 학습한다 - **업**)
비유에 대한 설명이 조금 더 있으면 좋겠다는 느낌이 있었습니다 '_' 
그런데 내용에 대한 이해를 해치는 수준은 아니기 때문에,
반영해도 되고 안 하셔도 좋은,
리뷰를 위한 리뷰라는 것 참고해주세용 😏

2021-05-23 04:18 UTC, taehee-kim-dev commented on level2.md
> +위의 상황이 계속되니 점점 해탈하는 것 같다. 어차피 개발자로서 평생 공부해야 하니, 마음을 편하게 가져야 한다는 생각이 문득 들었다. 지금도 과거의 습관이 남아있긴 하지만, 의식적으로 연습하는 중이다. __조급해하거나 불안해하지 않기. 새로운 것을 학습하는 것에 흥미 가지기. "몰라도 돼. 괜찮아."__ 라고 자신에게 말해주기. 이와 같은 노력으로 조금
오오 정말 그러네요.
좋은 피드백 고마워요!!
바로 반영했습니다 😄

2021-05-23 04:18 UTC, taehee-kim-dev commented on level2.md
> +우테코에서 자연스럽게 야생형(탑 - 다운) 방식으로 학습하게 됐다. 미션을 하면서 모르는 부분이 생기거나, 새로운 것을 도입하고 싶으면 해당 부분만 찾아서 학습한다. 찾아본 내용의 세부 내용에 대해 궁금증이 생기면, __"왜?"__ 라는 의문이 더 생기지 않을 때까지 깊이 파고든다. 이를 미션에 적용하고 개인 블로그에 정리하면 완전히 내 것이 된 느낌이다
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2021-05-23 04:20 UTC, taehee-kim-dev commented on level2.md
> +우테코에서 자연스럽게 야생형(탑 - 다운) 방식으로 학습하게 됐다. 미션을 하면서 모르는 부분이 생기거나, 새로운 것을 도입하고 싶으면 해당 부분만 찾아서 학습한다. 찾아본 내용의 세부 내용에 대해 궁금증이 생기면, __"왜?"__ 라는 의문이 더 생기지 않을 때까지 깊이 파고든다. 이를 미션에 적용하고 개인 블로그에 정리하면 완전히 내 것이 된 느낌이다
오 그렇군요.. 조금 더 세부적인 설명을 추가 해 볼게요!! 😃 
좋은 피드백 고마워용

2021-05-23 05:17 UTC, sihyung92 approved these changes
리뷰 반영한 내용 확인했습니다아~~~~~~~~~~~~~~~~~~~~~~~~~~~ 어프로브 할게용~~ 👍👍👍👍

2021-05-23 13:59 UTC, swon3210 approved these changes
글이 대체적으로 깔끔하고 비교-대조의 구조가 명확했습니다. 이미 이대로도 괜찮은 글이지만, 여기 더 살을 붙일 수 있는 부분이 있는 것 같아서 그것을 중심으로 리뷰해보았습니다!

2021-05-23 13:59 UTC, swon3210 commented on level2.md
> +학습 방법에 정답은 없다. 필요한 지식, 상황에 따라 적절한 학습 방법을 선택해야 한다. 그것이 효과적이고 스스로 만족스럽다면 자신에게 맞는 학습법이라 생각한다.
과거와 현재와의 공부 방식의 차이를 잘 설명해주셨지만, 어떤 과정을 통해 이런 방식을 택하게 되었는지, 혹시 시행착오는 없었는지가 궁금합니다. 그런 내용이 추가되면 두 대상을 대조하는 것과 더불어서 글 내용을 더 풍부하게 만들 수 있을 거라고 생각합니다.

2021-05-23 13:59 UTC, swon3210 commented on level2.md
> +혼자 하는 미션도, 크루들과 같이한다. 속도가 훨씬 빠르다. 집단지성의 위대함을 느끼고 있다. 혼자 할 때보다 2배 이상 빠른 것 같다. 최근 미션은 3명의 크루들과 함께 했다. 서로 모르는 부분들을 알려주며 상호보완적으로 코딩했다.
저는 이 부분 읽으면서 개인적으로 놀랐습니다. 저의 경우는 제가 정확히 모르던 부분을 페어가 짚어주거나 서로 의견을 주고 받느라 코딩 시간이 훨씬 늘어나던데, 구체적으로 어떤 이유에서 코딩 시간이 빨라질 수 있었던 것인가요? 서로 모르는 이유를 알려줬고 상호 보완적으로 코딩했다는 것보다 더 상세한 설명이 있으면 좋을 것이라 생각합니다.

2021-05-23 13:59 UTC, swon3210 commented on level2.md
> +이와 같은 노력으로 조금씩 스트레스가 줄어드는 것 같다. 아직 갈 길이 멀고 많이 부족하지만, 꾸준한 노력을 하면 더 좋은 개발자로 성장할 수 있을 거라 믿는다.
리스트 형식으로 나열해주신 것이 이해하기 훨씬 편해서 좋습니다! 다만 이 방식들을 어떤 경우에 어떻게 적용했다는 식의 예시를 들어주시면 더 이해가 잘 될 것이라 생각합니다.

2021-05-23 22:04 UTC, taehee-kim-dev commented on level2.md
> +학습 방법에 정답은 없다. 필요한 지식, 상황에 따라 적절한 학습 방법을 선택해야 한다. 그것이 효과적이고 스스로 만족스럽다면 자신에게 맞는 학습법이라 생각한다.
야생형 학습 방식의 선택 계기와, 단점을 추가했습니다!

2021-05-23 22:07 UTC, taehee-kim-dev commented on level2.md
> +혼자 하는 미션도, 크루들과 같이한다. 속도가 훨씬 빠르다. 집단지성의 위대함을 느끼고 있다. 혼자 할 때보다 2배 이상 빠른 것 같다. 최근 미션은 3명의 크루들과 함께 했다. 서로 모르는 부분들을 알려주며 상호보완적으로 코딩했다.
> 여러 개의 뇌가 동시에 한 가지의 문제를 고민하니 다양한 아이디어가 여러 가지 관점에서 빠르게 나온다.

의 내용을 보완했습니다!! 😄

2021-05-23 22:13 UTC, taehee-kim-dev commented on level2.md
> +이와 같은 노력으로 조금씩 스트레스가 줄어드는 것 같다. 아직 갈 길이 멀고 많이 부족하지만, 꾸준한 노력을 하면 더 좋은 개발자로 성장할 수 있을 거라 믿는다.
각 리스트들을 조금 더 자세히 작성해 봤습니다!! :)

2021-05-23 22:20 UTC, taehee-kim-dev commented
@swon3210 
안녕하세요, 크리스!
글을 더 풍부하게 해 주는 피드백들 감사합니다!!
제 스타일대로 반영해 봤어요!! 😄

2021-05-24 12:02 UTC, DWL5 requested changes
인비 전체적으로 정말 깔끔한 글 이네요!

우아한 테크코스가 시작 된지 3개월 정도 지났는데 정말 많은 변화가 일어난 것 같아요
그래서 인비의 과거와 현재를 비교하는 듯한 구성이 좋았어요....!

그리고 글이 전반적으로 깔끔해서 쉼표 관련 피드백 밖에 못 드렸어요 ㅜㅜ
검색해보니 쉼표는 아래와 같이 쓰인다고 합니다...! 기준이 애매모호 한 것 같아요!
그냥 참고만 해주시면 될 것 같습니다.

` 쉼표의 쓰임은 일반적으로 감탄사 뒤, 이어진 문장에서 앞 문장 뒤, 나열하는 말 사이 등으로 많이 알려져 있지만, 가장 큰 원칙은 가독성(의미에 대한 오해 없이 읽는 이가 쉽게 읽을 수 있게)을 높이는 데에 있습니다.`

잘 읽었고 좋은 글 감사합니다 :)

2021-05-24 12:02 UTC, DWL5 commented on level2.md
> +이제 혼자 코딩하거나 공부하면 허전하다. 루터에 출근하지 않는 날에도, 카페에 모여서 같이 공부하고 코딩한다. 매우 효율적이고, 즐겁다. 함께 하는 것의 즐거움을 알려준 우테코에게 감사하다.
저도 혼자 하는 날은 허전함을 느끼네요 ㅜ 공감합니다.

2021-05-24 12:02 UTC, DWL5 commented on level2.md
> +이제 혼자 코딩하거나 공부하면 허전하다. 루터에 출근하지 않는 날에도, 카페에 모여서 같이 공부하고 코딩한다. 매우 효율적이고, 즐겁다. 함께 하는 것의 즐거움을 알려준 우테코에게 감사하다.
여기에 쉼표가 두 문장에 연달아 들어가 있어서 약간 끊이는 느낌이 들었습니다!

루터에 출근하지 않는 날에도, 카페에 모여서 같이 공부하고 코딩한다. 매우 효율적이고, 즐겁다.

2021-05-24 12:02 UTC, DWL5 commented on level2.md
> +위의 상황이 계속되니 점점 해탈하는 것 같다. 어차피 개발자로서 평생 공부해야 하니, 마음을 편하게 가져야 한다는 생각이 문득 들었다. 지금도 과거의 습관이 남아있긴 하지만, 의식적으로 연습하는 중이다. __조급해하거나 불안해하지 않기. 새로운 것을 학습하는 것에 흥미 가지기. "몰라도 돼. 괜찮아."__ 라고 자신에게 말해주기. 이와 같은 노력으로 조금
어차피 개발자로서 평생 공부해야 하니, 마음을 편하게 가져야 한다는 생각이 문득 들었다. 지금도 과거의 습관이 남아있긴 하지만, 의식적으로 연습하는 중이다.

여기도 쉼표가 자주 사용되는 것 같아요!

2021-05-25 00:06 UTC, taehee-kim-dev commented
@DWL5 
### 안녕하세요, 수리!!
글을 쓰면서도 쉼표를 너무 자주 쓴다고 느꼈는데,
수리가 좋은 피드백을 주셨어요!!
반영했습니다.

좋은 리뷰 감사합니다. 😃 🙇

2021-05-29 09:23 UTC, yjksw approved these changes
인비 !!!  
글 잘 읽었어요 !! 정말 깔끔하고 인비가 실제로 어떻게 학습을 하고 있는지 잘 알 수 있는 내용이었어요 ~! 
정말 함께 학습할 수 있는 것이 우테코 최고 장점인 것 같아요. 그러니까 더 자주 열심히 같이 학습 합시다아~!! 
화이티이이잉!! 👍🙌

2021-05-29 09:23 UTC, yjksw commented on level2.md
> +이제 혼자 코딩하거나 공부하면 허전하다. 루터에 출근하지 않는 날에도 카페에 모여서 같이 공부하고 코딩한다. 매우 효율적이고 즐겁다. 함께 하는 것의 즐거움을 알려준 우테코에게 감사하다.
그럼.....조금 더 자주 나와 주시죠...? 인비 얼굴보기 힘든데 ,,,

2021-05-29 09:23 UTC, yjksw commented on level2.md
> +3. 나만 모르는 것 같아 조바심이 들 때, __"몰라도 돼. 괜찮아."__ 라고 자신에게 말해주기.
인비는 천재라서 그런 고민 하는 줄도 몰랐네여 ..!! 인간미 하나 느끼고 갑니다 👍 우리 잘 천천히 해봐요 🙌

2021-05-29 14:56 UTC, DWL5 approved these changes
인비 빠른 피드백 반영 정말 최곱니다!!!

이만 Approve 하겠습니다!

2021-05-30 09:26 UTC, swon3210 approved these changes

2021-05-30 10:51 UTC, qhals321 commented
인비!! 야생형 프로그래밍!! 인비의 속도로 봐서는 야생 치타형 프로그래밍을 선택했구만유!!
항상 멋진 모습 잘 보고있구!! 응원해유~!!!

2021-05-30 13:39 UTC, Joyykim commented
인비 하이👋 글 재밌게 읽었어!
`다른 크루들이 뛰어난 역량을 보일 때, 자신을 비교하며 조급해하거나 불안해하지 않기.`
인비도 불안해할 때가 있구나, 난 인비를 보면서 조급해질 때가 가끔있었는데 ㅎㅅㅎ
레벨3,4도 잘부탁해!

2021-07-14 08:25 UTC, woowapark approved these changes
안녕하세요 인비, 공원입니다.        

정리해주신 글을 읽다보니 이미 인비에게 맞는 단단하고 건강한 학습법을 향해 한발한발 잘 걸어가고 계신 것 같다는 생각이 들었어요 :)       
'길게 보고 즐기'기 위한 3가지 노력을 보니 아마 그런 노력을 하게 되기까지 고민도 많으셨을 것 같고요 🥲             

비교하지 않고 나만의 길을 보며 가는 게 때로는 참 쉽지 않겠지만,       
적어주신 것처럼 '야생'에서 '함께'하며       
앞으로 우테코 이후에도 계속해서 인비가 개발자로서 즐거운 길을 걸어갈 힘을 비축할 수 있길 응원합니다. 💪       
("몰라도 돼, 괜찮아"같이 스스로를 다독이는 조금 더 구체적인 지침들이 있었다면 하나씩 더 쟁여두는 것도 추천해보고 싶네요 :) )       

글쓰기 고생하셨어요~

2021-07-14 08:25 UTC, merged