[레벨 2 글쓰기 미션] 웨지(성시형) 미션 제출합니다.
woowacourse/woowa-writing-3 pull request #90
Opened 2021-05-23 01:04 UTC by sihyung92

안녕하세염~~~~~

[편하게 보는 링크](https://github.com/sihyung92/woowa-writing-3/tree/sihyung92)

수리
인비
지그
코다
크리스

잘 부탁 드립니다~~~

2021-05-23 04:27 UTC, sakjung commented
글 잘읽었습니다 ^..^

항상 웨지의 미친 강의력이 부러웠는데... 저도 이제 말로 풀어 설명하는 법을 연습 해야겠어요. 
제가 진짜 부족한 부분 중 하나거든요 ㅋㅋㅋ

자기만의 학습법이 있다는 것도 극공감합니다 ㅋㅋ. 자기 스탈대로 밀어 붙여봅시다!

- 창녕 성씨, the 근본, 검교공파 성정석 aka 삭정 -

2021-05-23 05:49 UTC, taehee-kim-dev reviewed
### 웨지 하이~~~ 에이치 아이~~

멀리서 보며 웨지를 존경하고 있습니다.. ㅎㅎ

굉장히 열심히 하는 웨지의 모습에 항상 놀라는데,
역시 그 원동력은 __"즐거움"__ 이었군요!!

글에서 공부의 즐거움에 대한 흥분이 느껴져서 좋았어요. :)
개성있는 표현과 이모지들이 인상적이예요!

소소한 개인적인 의견 남겼는데,
반영해도 좋고 안 해도 좋아요!!

잘 읽었습니다!! 😄

2021-05-23 05:49 UTC, taehee-kim-dev commented on step2/README.md
> +시간을 조금만 뒤로 돌려서, 우테코에 들어오기 전 개발 공부를 하며 TIL과 1일 1커밋 운동, 블로깅에 관심이 많았습니다. 롤모델인 조졸두님 께서 앞서 해나가고 있었던 것이기 때문이었죠. 하지만 3번 시도해서 3번 실패하는데요, 조졸두님 보다 의지력도, 열정도 약하기 때문이라 결론 내렸습니다. 어쩌겠어요? 전 그 정도밖에 안 되는 인간인걸요......
```suggestion
시간을 조금만 뒤로 돌려서, 우테코에 들어오기 전 개발 공부를 하며 TIL과 1일 1커밋 운동, 블로깅에 관심이 많았습니다. 롤모델인 조졸두님 께서 앞서 해나가고 있었던 것이기 때문이었죠. 하지만 3번 시도해서 3번 실패하는데요. 조졸두님 보다 의지력도, 열정도 약하기 때문이라 결론 내렸습니다. 어쩌겠어요? 전 그 정도밖에 안 되는 인간인걸요...... 흑흑
```

쉼표 부분을 아예 마침표로 바꿔서 문장을 분리해도 괜찮을 것 같아요! :)

2021-05-23 05:49 UTC, taehee-kim-dev commented on step2/README.md
> +단순히 서로에게 동기부여가 되는 수준을 넘어서 본인이 궁금했던 부분을 추가로 학습하여 공유하고, 주기적으로 모여 특정 주제에 관해 토론을 나누는 시간이 이어졌어요. 제가 잘 알지 못하는 분야에 대해 전문성을 가지고 있는 크루들이 해당 관점에서 토론과 학습을 풍성하게 해주었습니다. 또한, 의견이 다른 크루는 이야기를 나누면서 어떤 사고 흐름을 통해 결론에
> 해당 관점에서

해당 관점이라는 것이 어떤 관점을 의미하는 건지 궁금해요!!
조금 더 설명해 줘도 좋을 것 같아요. :)

2021-05-23 05:49 UTC, taehee-kim-dev commented on step2/README.md
> +저도 스터디를 모집하기 전까진(이전엔 스터디를 제대로 운영해본 경험이 없습니다) 운영을 잘 못 하면 어쩌지, 크루들이 불편해하면 어쩌지, 실패하면 어쩌지 정말 고민이 많았습니다.
> (이전엔 스터디를 제대로 운영해본 경험이 없습니다)

괄호 안의 문장을 새로운 문장으로 빼내도 좋을 것 같아요! :)

2021-05-23 06:15 UTC, sihyung92 commented on step2/README.md
> +저도 스터디를 모집하기 전까진(이전엔 스터디를 제대로 운영해본 경험이 없습니다) 운영을 잘 못 하면 어쩌지, 크루들이 불편해하면 어쩌지, 실패하면 어쩌지 정말 고민이 많았습니다.
불필요한 내용인 것 같아서 제거했습니다잉~!

2021-05-23 06:15 UTC, sihyung92 commented on step2/README.md
> +단순히 서로에게 동기부여가 되는 수준을 넘어서 본인이 궁금했던 부분을 추가로 학습하여 공유하고, 주기적으로 모여 특정 주제에 관해 토론을 나누는 시간이 이어졌어요. 제가 잘 알지 못하는 분야에 대해 전문성을 가지고 있는 크루들이 해당 관점에서 토론과 학습을 풍성하게 해주었습니다. 또한, 의견이 다른 크루는 이야기를 나누면서 어떤 사고 흐름을 통해 결론에
'그 크루가 전문성을 가지고 있는 분야' 라는 의미였습니당~!

"자기만의 관점" 이라는 단어로 수정하였어요 ㅎ_ㅎ

2021-05-23 06:25 UTC, sihyung92 commented on step2/README.md
> +시간을 조금만 뒤로 돌려서, 우테코에 들어오기 전 개발 공부를 하며 TIL과 1일 1커밋 운동, 블로깅에 관심이 많았습니다. 롤모델인 조졸두님 께서 앞서 해나가고 있었던 것이기 때문이었죠. 하지만 3번 시도해서 3번 실패하는데요, 조졸두님 보다 의지력도, 열정도 약하기 때문이라 결론 내렸습니다. 어쩌겠어요? 전 그 정도밖에 안 되는 인간인걸요......
짧은 호흡의 문장이 좋다는데, 항상 질질질 늘여쓰는 습관이 있습니다ㅋㅋㅋ 분리했습니당

2021-05-23 06:33 UTC, taehee-kim-dev approved these changes
피드백 반영 확인했습니다!!
고생 많으셨어요~ approve 할게요!!

2021-05-23 08:16 UTC, zigsong requested changes
안녕하세요 웨지! 
글을 읽으면서 덩달아 같이 즐거워지는 기분이네요 😆
작은 코멘트들 남겼습니다! 
전반적으로 글이 통통 튀고 웨지만의 스타일이 잘 묻어나는 것 같아요!
잘 읽었습니다 ㅎㅎ

2021-05-23 08:16 UTC, zigsong commented on step2/README.md
> +하지만 3번 시도해서 3번 실패하는데요.
> 조졸두님 께서

`조졸두님께서`로 붙여 써야할 것 같아요!

2021-05-23 08:16 UTC, zigsong commented on step2/README.md
> +
> 조졸두님 보다

`조졸두님보다` 붙여쓰기!

2021-05-23 08:16 UTC, zigsong commented on step2/README.md
> +시간이 흘러 우테코 레벨2를 시작하고 얼마 지나지 않은 어느 날, 이런 이력서를 가진 신입 개발자면 바로 채용한다는 내용의 [유투브 영상](https://www.youtube.com/watch?v=Yc56NpYW1DM&t=784s)을 보게 되었습니다.
저도 이거 봤는데 넘 대단하시더라구요 👍👍

2021-05-23 08:16 UTC, zigsong commented on step2/README.md
> +불현듯 깨달음이 옵니다! 전 이미 몹시 **즐겁고 행복하게** 학습을 하고 있다는 걸요. 그러므로 굳이 남의 방법을 따라 할 필요가 없고, 저만의 길을 가면 됩니다.
진짜 멋진 깨달음이네요! 이 대목에서 공감 크게 누르고 갑니당

2021-05-23 08:16 UTC, zigsong commented on step2/README.md
> +레벨1을 거치면서, 저는 사람에게서 에너지를 얻는다는 사실을 깨달았습니다. 제게 에너지와 영감을 준 레벨1 CU조, 우테코 여러분 다 사...사...사리 추가!!
무슨 사리 추가하셨나요? 👀

2021-05-23 08:16 UTC, zigsong commented on step2/README.md
> +혹여나 제게 뭔가 물어볼 게 있으시다면 아무때나 말 걸어주시거나 DM 주세요. 제겐 포상입니다.
저도 뭐 물어봐도 되나요!

2021-05-23 08:16 UTC, zigsong commented on step2/README.md
> +우테코에서 처음 스터디를 모집할 땐 운영을 잘 못 하면 어쩌지, 크루들이 불편해하면 어쩌지, 실패하면 어쩌지 정말 고민이 많았습니다.
> 잘 못 하면

`잘 못하면`인 것 같아요!

2021-05-23 08:16 UTC, zigsong commented on step2/README.md
> +예전엔 스펙과 실력이 모자란 것이 고민이었지만, 지금은 시간이 모자란 것이 고민입니다. 시간만 주면 실력은 채울 자신이 있답니다. 호호
와우우우우

2021-05-23 14:16 UTC, swon3210 reviewed
정리를 해보자면, 기존에 재미없었지만 꾹 참고 그냥 혼자 했던 공부를 스터디, 토의, 다른 사람에게 설명해보는 활동 등을 통해 즐겁고 효과적으로 했다는 내용으로 글이 이해가 됩니다. 다만 처음에 글을 한번에 쭉 읽을 때는 내용이 잘 정리가 되지 않았습니다.

글을 말 그대로 눈 앞에 있는 사람에게 이야기 하듯이 편하고 친근하게 쓰는, 특색 있는 스타일이라서 개인적으로 재미있게 읽었습니다. 하지만 주제들이 너무 다양하고, 산발적으로 흩어져 있는 것 같습니다. 좀 더 '학습 동기'와 '학습법' 과 같은 몇 가지 키워드에 초점을 맞춰서 글을 전체적으로 정리해보시는 것을 권해드리고 싶습니다.

2021-05-23 14:16 UTC, swon3210 commented on step2/README.md
> +그리고 저는 남에게 뭔가 설명하는 것이 **재밌습니다**. 아마 저한테 뭔가 물어보신 분들은 제가 흥분해서 설명하는 바람에 도망도 못 가고 '아 괜히 물어봤다......'라고 생각해보신 경험이 있을 거예요.
학습법이 크게 스터디 & 설명하기로 나뉘는 것 같은데, 문단이 산발적으로 나뉘어 있어서 그 구조가 분명하게 드러나지 않는 것 같습니다. 단락을 연관 있는 내용끼리 좀 더 묶어보시는 건 어떨까요?

2021-05-23 14:16 UTC, swon3210 commented on step2/README.md
> +
글이 단순히 과거 vs 현재의 학습방식이 아니라 매우 많은 주제들을 다루고 있어서 바로 본론으로 들어가기 보다는 서론에서 글의 내용을 요약해주거나 구조를 좀 정리해주는 부분이 필요할 것 같습니다.

2021-05-23 23:06 UTC, sihyung92 commented on step2/README.md
> +하지만 3번 시도해서 3번 실패하는데요.
확인~~!

2021-05-23 23:06 UTC, sihyung92 commented on step2/README.md
> +
확인2~~!

2021-05-23 23:09 UTC, sihyung92 commented on step2/README.md
> +시간이 흘러 우테코 레벨2를 시작하고 얼마 지나지 않은 어느 날, 이런 이력서를 가진 신입 개발자면 바로 채용한다는 내용의 [유투브 영상](https://www.youtube.com/watch?v=Yc56NpYW1DM&t=784s)을 보게 되었습니다.
진짜루여!! 존경심이 절로 듭니당
볼때마다 부럽긴 하지만 난 나만의 속도로😊

2021-05-23 23:14 UTC, sihyung92 commented on step2/README.md
> +불현듯 깨달음이 옵니다! 전 이미 몹시 **즐겁고 행복하게** 학습을 하고 있다는 걸요. 그러므로 굳이 남의 방법을 따라 할 필요가 없고, 저만의 길을 가면 됩니다.
마이웨이~~~!

2021-05-23 23:15 UTC, sihyung92 commented on step2/README.md
> +레벨1을 거치면서, 저는 사람에게서 에너지를 얻는다는 사실을 깨달았습니다. 제게 에너지와 영감을 준 레벨1 CU조, 우테코 여러분 다 사...사...사리 추가!!
중국당면사리.. 일껄요?👀

2021-05-23 23:17 UTC, sihyung92 commented on step2/README.md
> +혹여나 제게 뭔가 물어볼 게 있으시다면 아무때나 말 걸어주시거나 DM 주세요. 제겐 포상입니다.
당근입니당~~~~~~~~~~~

2021-05-23 23:17 UTC, sihyung92 commented on step2/README.md
> +예전엔 스펙과 실력이 모자란 것이 고민이었지만, 지금은 시간이 모자란 것이 고민입니다. 시간만 주면 실력은 채울 자신이 있답니다. 호호
자만 스위치 ON

2021-05-24 11:46 UTC, DWL5 approved these changes

2021-05-24 11:46 UTC, DWL5 commented on step2/README.md
> +또 다른 학습법으로는, 남에게 설명해보기가 있습니다. 머릿속에서 구조화되지 않은 형태로 쌓여있던 지식이 남에게 설명하기 위해 풀어내다 보면 점점 자리잡히는 걸 느낍니다. 그래서 저는 누가 학습법을 물어보면 말로 풀어 설명해보는 것을 꼭 권해요.
머릿속에서 구조화되지 않은 형태로 쌓여있던 지식이 남에게 설명하기 위해 풀어내다 보면 점점 자리잡히는 걸 느낍니다.

지식이 > 지식을 이 더 자연스러워보여요! 
설명하기 위해 풀어내다  보면 > 중복이 되는 느낌이라 설명하다 하나만 써도 될 것 같숩니다!

아래는 예시에요~

> 머릿속에서 구조화되지 않은 형태로 쌓여있던 지식을 남에게 설명하다 보면 점점 자리잡히는 걸 느낍니다.

2021-05-24 11:48 UTC, DWL5 requested changes
웨지스러움이 느껴지는 글이네요 ㅋㅋㅋㅋㅋ (칭찬입니다.)
글에서 부터 에너지가 느껴져서 무기력 해 졌을 때 한번씩 꺼내 봐야겠어요!
피드백 남겼으니 확인 부탁드려요~

2021-05-24 22:27 UTC, sihyung92 commented on step2/README.md
> +그리고 저는 남에게 뭔가 설명하는 것이 **재밌습니다**. 아마 저한테 뭔가 물어보신 분들은 제가 흥분해서 설명하는 바람에 도망도 못 가고 '아 괜히 물어봤다......'라고 생각해보신 경험이 있을 거예요.
좋습니당당~~~ 재구성해보겠습니당~

2021-05-24 22:27 UTC, sihyung92 commented on step2/README.md
> +
매우 좋은 의견임돠 서론부를 추가했습니당!!!

2021-05-24 22:28 UTC, sihyung92 commented on step2/README.md
> +또 다른 학습법으로는, 남에게 설명해보기가 있습니다. 머릿속에서 구조화되지 않은 형태로 쌓여있던 지식이 남에게 설명하기 위해 풀어내다 보면 점점 자리잡히는 걸 느낍니다. 그래서 저는 누가 학습법을 물어보면 말로 풀어 설명해보는 것을 꼭 권해요.
수리 H I~ 
조와용 조와용 확인하고 반영하겠슴돠!

2021-05-25 02:26 UTC, zigsong commented
> 그리고 실패에는 내성이 생겨요. 공부할 때만큼은 맘껏 실패해봐도 됩니다. 용기를 내서 시도해보고, 실패하고, 때로는 성공하고, 나만의 학습법을 만들어 가세요.

다시 읽어보니 위 문장이 마음에 남네요! 저도 실패를 두려워하지 말고, 웨지처럼 자신감을 가지고 행복하게 공부할 수 있었으면 좋곘어요 ㅎㅎ 
글 재밌게 잘 읽었습니다 웨지! 어프루브할게용 😆

2021-05-25 02:27 UTC, zigsong commented
> 그리고 실패에는 내성이 생겨요. 공부할 때만큼은 맘껏 실패해봐도 됩니다. 용기를 내서 시도해보고, 실패하고, 때로는 성공하고, 나만의 학습법을 만들어 가세요.

다시 읽어보니 위 문장이 마음에 남네요! 저도 실패를 두려워하지 말고, 웨지처럼 자신감을 가지고 행복하게 공부할 수 있었으면 좋곘어요 ㅎㅎ 
글 재밌게 잘 읽었습니다 웨지! 근데 어프루브하고 싶은데 버튼이 없네요! 저한테 re-request 보내셔야 할 것 같아요 😆

2021-05-27 00:09 UTC, zigsong approved these changes
웨지 이제 approve된 것 같아요~~! 아마두 👾👾

2021-05-29 08:48 UTC, yjksw approved these changes
웨지가 진짜 즐겁게 공부하고 있는 게 느껴지는 글이에요~! 웨지가 옆에서 엄청 잘 즐기고 있으니까 저도 덩달아서 열심히 하게 되는 것 같습니당 ㅎㅎㅎ 역시 웨지는 우테코에서 없어서는 안되는 인재!! 진심으로!! 
앞으로도 텐션 유지하면서 즐겁게 함께 학습할 수 있었으면 좋겠습니다아아아 ~!

2021-05-29 08:48 UTC, yjksw commented on step2/README.md
> +`바뀐 나`라는 주제로 6시간 정도 떠들고 싶지만, 여러분 고막도 보호해야하고  주제도 정해져 있으니 자제하겠습니다. 😉
웨지톡 한번 하죠!!! 궁금한데!!

2021-05-29 08:48 UTC, yjksw commented on step2/README.md
> +`내게 맞는 학습법을 찾아야 한다` 라는 깨달음을 전달해드리고자 함입니다.
좋은 인트로인 것 같아요 ~! 흥미롭게 시작하네요 👍

2021-05-29 08:48 UTC, yjksw commented on step2/README.md
> +그중 가장 효과를 본 것은 스터디와 남에게 설명해주기였습니다.
명료하네요!!

2021-05-29 08:48 UTC, yjksw commented on step2/README.md
> +그런데 이 모든 과정이 '유익하다'를 넘어 **즐겁다고** 느껴졌어요.
즐거웠던 간단한 예시가 있으면 더 잘 느낄 것 같아요~! 물론 개인적인 의견입니당

2021-05-29 08:48 UTC, yjksw commented on step2/README.md
> +> 나와 맞는 방법인가?
맞아유 ㅠㅠ

2021-05-29 14:59 UTC, DWL5 approved these changes
오 웨지~~ Approve하러 왔는데 한번 더 읽고가욥!

2021-05-30 06:12 UTC, Be-poz commented
> 혼자 꾸준히 할 자신이 없으면 일단 웨지가 주최하는 스터디에  스스로 족쇄를 채워라. 그럼 반은 간다  -파즈-

2021-05-30 09:17 UTC, TaewanKimmmm commented on step1/README.md
> +갑자기 사족이지만 우테코 4기는 꼭 뮤지컬을 했으면 좋겠다. 안무와 자작곡을 곁들인. 이런 새로운 경험을 어디서 해보겠는가? ^^
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2021-05-30 09:22 UTC, TaewanKimmmm commented
지나가던 파피입니다.

슬랙에 올리시는 글에서도 느껴졌지만, 특히 학습 로그 토론을 하면서 정말 깊이있게 공부하신다는 느낌을 받았답니다..

질문 세례 자주 하겠습니다 😀

2021-05-30 09:24 UTC, swon3210 approved these changes

2021-05-30 09:38 UTC, seojihwan commented
웨지는 몸이 몇개인가요? 
즐겁게 자신만의 학습법을 유지하는 모습이 멋잇네요!

저도 루터에 가는 것이 즐거운데 웨지만큼 즐겁지는 않았나봐요~ 아침일찍 출근하는 것이 어렵네요😭
제 몫까지 일찍 출근해주시는 모습 앞으로도 기대할게요~

2021-05-30 11:13 UTC, qhals321 commented
지나가던 나봄입니다~!!!
웨지가 너무 잘 표현된 글 같네요~!!!
웨지와 함께 공부할 수 있다는 사실에 항상 행복해요~!!
항상 좋은 스터디 열어줘서 고마워요!!!

2021-05-30 13:51 UTC, zereight commented on step2/README.md
> +불현듯 깨달음이 옵니다! 전 이미 몹시 **즐겁고 행복하게** 학습을 하고 있다는 걸요. 그러므로 굳이 남의 방법을 따라 할 필요가 없고, 저만의 길을 가면 됩니다.
웨지 이력서는 내년에 유투브에 올라갑니다

2021-05-30 13:53 UTC, zereight commented on step2/README.md
> +그리고 저는 남에게 뭔가 설명하는 것이 **재밌습니다**. 아마 저한테 뭔가 물어보신 분들은 제가 흥분해서 설명하는 바람에 도망도 못 가고 '아 괜히 물어봤다......'라고 생각해보신 경험이 있을 거예요.
웨지의 테코톡 채널한개 더 파주세요

2021-05-30 13:53 UTC, zereight commented on step2/README.md
> +그리고 실패에는 내성이 생겨요. 공부할 때만큼은 맘껏 실패해봐도 됩니다. 용기를 내서 시도해보고, 실패하고, 때로는 성공하고, 나만의 학습법을 만들어 가세요.
맞아요 계속 실패합시다 여러분

2021-05-30 13:57 UTC, zereight approved these changes
저는 재치 있고 경험이 많은 귀하의 글에 감동을 받았기 때문에 제 역할은 아니었지만 승인하고 싶었습니다. 좋은 기사 주셔서 감사합니다. 나머지 우아한 기술 과정을 위해 싸우십시오! 응원하겠습니다!

2021-05-31 06:45 UTC, RinSabbit commented
웨지 하이~~ H I ~~ 지나가다 들려봤어욤ㅎㅎ
글 넘 재밋게 읽었습니다ㅋㅋㅋㅋㅋ 읽다가 현웃 포인트 넘 많아서ㅋㅋㅋㅋㅋ 토크쇼인줄ㅋㅋㅋㅋㅋ
웨지 덕에 스터디도 열심히 참여하게 되고(일단 갈겨보자 식도 많지만..?) 힘을 많이 얻어가요 땡큐땡큐
앞으로도 햎피 웨지 길만 걷자~~~~

2021-05-31 07:36 UTC, iborymagic commented
ㅋㅋㅋㅋ 글에서 웨지가 물씬 느껴집니다.. 재밌게 잘 읽었어요.
주말에 마주칠 때마다 NPC처럼 인사해주는 웨지..
테코톡도 인상깊게 잘 봤슴다.
앞으로도 건강한 에너지 이곳저곳에 전파해주십쇼

2021-08-02 04:07 UTC, woowahan-pjs approved these changes

2021-08-02 04:08 UTC, merged